### ISSUE TITLE
[.Net] `Handle is not initialized.` when assigning `TweenMethod` to a later-disposed `Tween`

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot#100691]
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.3.stable.mono - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6603) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Assigning `TweenMethod` to a `Tween` that will be disposed later will result in the following counterintuitive error.

```csharp
ERROR: System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at Godot.Bridge.ScriptManagerBridge.SetGodotObjectPtr(IntPtr gcHandlePtr, IntPtr newPtr) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 295
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113)
```

### Steps to reproduce

Run the following code:

```csharp
using Godot;

public partial class Main : Node
{
    public override void _Process(double delta)
    {
        for (var i = 0; i < 1000; i++)
        {
            var node = new Node2D();
            using var tween = node.CreateTween();
            tween.TweenMethod(
                new(node, CanvasItem.MethodName.SetModulate),
                Colors.Black,
                Colors.White,
                0.1f
            );
            AddChild(node);
        }
    }
}
```

Please note that removing the `using` keyword stops the issue from happening.

### Minimal reproduction project (MRP)

[Mrp_HandleNotInitialized.zip](https://github.com/user-attachments/files/18218193/Mrp_HandleNotInitialized.zip)

**Comment by zaevi** [comment]
More simplified reproduction:

```C#
public override void _Process(double delta)
{
	var tree = GetTree();
	for (var i = 0; i < 1000; i++)
	{
		using var timer = tree.CreateTimer(0.1f);
		timer.Timeout += () => { };
	}
}
```

**Comment by Delsin-Yu** [comment]
This may boil down to a Callable issue on disposed nodes.

**Comment by zaevi** [comment]
I narrowed down the troubleshooting to disposing `RefCounted`.

It seems that when disposing `RefCounted` that holds more than 1 ref-count, it doesn't untie the instance binding correctly:

```C#
public override void _Ready()
{
	var rc = new RefCounted();
	rc.Reference();

	var id = rc.GetInstanceId();
	rc.Dispose();

	var rc2 = InstanceFromId(id) as RefCounted;

	// rc2.GetReferenceCount(); // ObjectDisposedException
	Debug.Assert(ReferenceEquals(rc, rc2) == false); // Fail
}
```

**Comment by zaevi** [comment]
Simplest reproduction:

```csharp
public override void _Ready()
{
	Foo();
	GC.Collect();

	void Foo()
	{
		var tree = GetTree();
		using var timer = tree.CreateTimer(0.001f);
		timer.Timeout += () => { };
	}
}
```
