### ISSUE TITLE
Segfault on quit in project manager (memdelete<GDNativeSingletonDiscover>)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10992]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mageia 6 x86_64, Godot master 9b9344cab

**Issue description:**
When closing the project manager, Godot segfaults:
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x00000000021f982a in Object::_predelete (this=0x0) at core/object.cpp:384
384             _predelete_ok = 1;

(gdb) bt
#0  0x00000000021f982a in Object::_predelete (this=0x0) at core/object.cpp:384
#1  0x0000000002204048 in predelete_handler (p_object=0x0) at core/object.cpp:1774
#2  0x0000000000d935b8 in memdelete<GDNativeSingletonDiscover> (p_class=0x0) at core/os/memory.h:107
#3  0x0000000000d922b9 in unregister_gdnative_types () at modules/gdnative/register_types.cpp:252
#4  0x0000000000d839a2 in unregister_module_types () at modules/register_module_types.gen.cpp:129
#5  0x0000000000d46193 in Main::cleanup () at main/main.cpp:1714
#6  0x0000000000d1a5f0 in main (argc=1, argv=0x7fffffffda88) at platform/x11/godot_x11.cpp:55
```
Seems related to GDNative, cc @karroffel.

**Steps to reproduce:**
- Start Godot
- Close it

**Comment by karroffel** [comment]
Will take a look
