### ISSUE TITLE
Game crash: Segmentation fault in SortArray<RasterizerGLES2::RenderList::Element*, RasterizerGLES2::RenderList::SortZ>::introsort()

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#1233]
Suddenly, during playing this happens:

```
Program received signal SIGSEGV, Segmentation fault.
0x0815ef6b in SortArray<RasterizerGLES2::RenderList::Element*, RasterizerGLES2::RenderList::SortZ>::introsort(int, int, RasterizerGLES2::RenderList::Element**, int) const ()
(gdb) backtrace
#0  0x0815ef6b in SortArray<RasterizerGLES2::RenderList::Element*, RasterizerGLES2::RenderList::SortZ>::introsort(int, int, RasterizerGLES2::RenderList::Element**, int) const ()
#1  0x08148b29 in RasterizerGLES2::end_scene() ()
#2  0x08b0f085 in VisualServerRaster::_render_camera(VisualServerRaster::Viewport*, VisualServerRaster::Camera*, VisualServerRaster::Scenario*) ()
#3  0x08b10fb1 in VisualServerRaster::_draw_viewport(VisualServerRaster::Viewport*, int, int, int, int) ()
#4  0x08b11631 in VisualServerRaster::_draw_viewports() ()
#5  0x08b118ef in VisualServerRaster::draw() ()
#6  0x08058dfc in Main::iteration() ()
#7  0x08055f05 in OS_X11::run() ()
#8  0x0805213c in main ()
(gdb) 
```

**Comment by akien-mga** [comment]
Were you able to trigger this issue reliably, and can you still reproduce it in the current master branch?

**Comment by akien-mga** [comment]
Closing, as without steps to reproduce or a test project there's not much that can be done to fix this potential bug. Feel free to reopen or open a new issue if you can reproduce a segfault with a similar backtrace.
