### ISSUE TITLE
editor does not respond while saving scene has GIProbe

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#13338]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 6aa331e

**Issue description:**

editor does not respond while saving scene has GIProbe.
it happens often.

**Steps to reproduce:**
try to save a scene has GIProbe multiple times.
then it stuck on saving.

I think it stuck in this loop.
https://github.com/godotengine/godot/blob/master/servers/visual/visual_server_scene.cpp#L334-L337

**Link to minimal example project:**

[save_giprobe_scene.tar.gz](https://github.com/godotengine/godot/files/1505856/save_giprobe_scene.tar.gz)

1. open this project
2. select `Spatial` node
3. add instance child scene
4. select `main.tscn`
5. save scene

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/33266403-dbc7f42e-d3b8-11e7-80cc-5ee135c8db43.png)

**Comment by reduz** [comment]
can you procure a demo scene that triggers this? I have never encountered
this problem

**Comment by volzhs** [comment]
@reduz try to do ctrl+s multiple times fast.
It happens randomly.

**Comment by volzhs** [comment]
@reduz 
![image](https://user-images.githubusercontent.com/8281454/33267053-4edac08e-d3bb-11e7-9171-0256e2c4661c.png)
it happens material tester demo also (with gi probe)
it happens more often when play scene.

**Comment by volzhs** [comment]
@reduz 

[save_giprobe_scene.tar.gz](https://github.com/godotengine/godot/files/1505856/save_giprobe_scene.tar.gz)

1. open this project
2. select `Spatial` node
3. add instance child scene
4. select `main.tscn`
5. save scene

**Comment by volzhs** [comment]
still happen with attached example project. :cry:

**Comment by reduz** [comment]
will try to fix today

**Comment by akien-mga** [comment]
I could reproduce it with the current master branch using https://github.com/Calinou/godot-sponza. It does not happen all the time, but it did happen for me right now (this was when autosaving the scene to play it, after having changed project settings without hitting save manually).

As debugged by @volzhs, there's an infinite sleep loop:
```
(gdb) bt
#0  0x0000003d94c103ed in nanosleep () from /lib64/libpthread.so.0
#1  0x000000000157603e in OS_Unix::delay_usec (this=0x7fffd697c070, p_usec=1) at drivers/unix/os_unix.cpp:267
#2  0x000000000255fb0f in VisualServerScene::instance_set_base (this=0x7f8edfe3e020, p_instance=..., p_base=...) at servers/visual/visual_server_scene.cpp:336
#3  0x0000000002569528 in VisualServerScene::free (this=0x7f8edfe3e020, p_rid=...) at servers/visual/visual_server_scene.cpp:2961
#4  0x00000000024ea84e in VisualServerRaster::free (this=0x47a82f0, p_rid=...) at servers/visual/visual_server_raster.cpp:78
#5  0x00000000025041d8 in VisualServerWrapMT::free (this=0x47e4010, p1=...) at servers/visual/visual_server_wrap_mt.h:537
#6  0x0000000001fcaa2e in VisualInstance::~VisualInstance (this=0x184c33f0, __in_chrg=<optimized out>) at scene/3d/visual_instance.cpp:134
#7  0x0000000001f8d1ad in GIProbe::~GIProbe (this=0x184c33f0, __in_chrg=<optimized out>) at scene/3d/gi_probe.cpp:1524
#8  0x00000000011438ef in memdelete<Node> (p_class=0x184c33f0) at core/os/memory.h:117
#9  0x0000000001c81817 in Node::_notification (this=0x1885fa30, p_notification=1) at scene/main/node.cpp:163
#10 0x0000000000ec064e in Node::_notificationv (this=0x1885fa30, p_notification=1, p_reversed=true) at ./scene/main/node.h:45
#11 0x0000000001f5a7e1 in WorldEnvironment::_notificationv (this=0x1885fa30, p_notification=1, p_reversed=true) at scene/3d/scenario_fx.h:41
#12 0x000000000275b2ec in Object::notification (this=0x1885fa30, p_notification=1, p_reversed=true) at core/object.cpp:923
#13 0x0000000002758435 in Object::_predelete (this=0x1885fa30) at core/object.cpp:385
#14 0x0000000002763688 in predelete_handler (p_object=0x1885fa30) at core/object.cpp:1904
#15 0x00000000011438cf in memdelete<Node> (p_class=0x1885fa30) at core/os/memory.h:115
#16 0x0000000001713576 in EditorNode::_save_scene (this=0x75596c0, p_file=..., idx=-1) at editor/editor_node.cpp:1031
#17 0x0000000001712e67 in EditorNode::_save_scene_with_preview (this=0x75596c0, p_file=..., p_idx=-1) at editor/editor_node.cpp:980
#18 0x0000000001719a2e in EditorNode::_run (this=0x75596c0, p_current=false, p_custom=...) at editor/editor_node.cpp:1763
#19 0x000000000171d6f7 in EditorNode::_menu_option_confirm (this=0x75596c0, p_option=38, p_confirmed=false) at editor/editor_node.cpp:2251
#20 0x000000000170fba5 in EditorNode::_menu_option (this=0x75596c0, p_option=38) at editor/editor_node.cpp:664
#21 0x0000000000fbbcfe in MethodBind1<int>::call (this=0xc4ad160, p_object=0x75596c0, p_args=0x1848dc30, p_arg_count=1, r_error=...) at core/method_bind.gen.inc:729
#22 0x000000000275b16f in Object::call (this=0x75596c0, p_method=..., p_args=0x1848dc30, p_argcount=1, r_error=...) at core/object.cpp:913
#23 0x000000000275c93b in Object::emit_signal (this=0x99f2ad0, p_name=..., p_args=0x7fffd6979ce0, p_argcount=0) at core/object.cpp:1194
#24 0x000000000275ce93 in Object::emit_signal (this=0x99f2ad0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1239
#25 0x0000000001d4ffaf in BaseButton::_gui_input (this=0x99f2ad0, p_event=...) at scene/gui/base_button.cpp:145
#26 0x00000000017ddd4e in MethodBind1<Ref<InputEvent> >::call (this=0x536b150, p_object=0x99f2ad0, p_args=0x7fffd697ab10, p_arg_count=1, r_error=...) at core/method_bind.gen.inc:729
#27 0x000000000275a51a in Object::call_multilevel (this=0x99f2ad0, p_method=..., p_args=0x7fffd697ab10, p_argcount=1) at core/object.cpp:747
#28 0x000000000275ad57 in Object::call_multilevel (this=0x99f2ad0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:853
#29 0x0000000001cadacf in Viewport::_gui_call_input (this=0x5b0a620, p_control=0x99f2ad0, p_input=...) at scene/main/viewport.cpp:1461
```

**Comment by reduz** [comment]
I did some changes that may fix it, but I'm not sure because I still can't reproduce. Please give it a check.

**Comment by volzhs** [comment]
it still happens with 431dfc14585fa12750b2c1ef2e7efaeed6df2f68
