### ISSUE TITLE
Godot Editor crashes while opening an inherited glTF scene

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#14896]
**Godot version:**
Latest version from master branch

**OS/device including version:**
Ubuntu Linux 16.04 64 bit

**Issue description:**
I've used the Blender glTF exporter to export a car model to Godot.
I can open the scene with Godot, but the Godot editor crashes when I try to open the gtTF scene inside a tscn scene.

**Steps to reproduce:**
- Download master branch from Github
- compile with scons
- open the demo project below
- don't open the glTF file manually with the file manager
- node Spatial in world.tscn --> open in editor
- node Scene Root --> open in editor
- Godot crashes

**Minimal reproduction project:**
[Demo.zip](https://github.com/godotengine/godot/files/1577139/Demo.zip)

**Comment by capnm** [comment]
back trace (tip 8297ea903a0568c715bdcd421382788174c7d14f)
```
[Thread 0x7fffe51cf700 (LWP 21947) exited]
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.
ERROR: get_global_transform: Condition ' !is_inside_tree() ' is true. returned: Transform()
   At: scene/3d/spatial.cpp:265.

Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
0x00000000017c23b7 in HashMap<StringName, HashMap<StringName, Ref<StyleBox>, StringNameHasher, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>, StringNameHasher, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr () at core/hash_map.h:332
332			const Element *e = const_cast<Element *>(get_element(p_key));
(gdb) bt
#0  0x00000000017c23b7 in HashMap<StringName, HashMap<StringName, Ref<StyleBox>, StringNameHasher, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>, StringNameHasher, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr () at core/hash_map.h:332
#1  HashMap<StringName, HashMap<StringName, Ref<StyleBox>, StringNameHasher, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>, StringNameHasher, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::has () at core/hash_map.h:286
#2  Theme::has_stylebox () at scene/resources/theme.cpp:379
#3  0x00000000012ad254 in Control::get_stylebox () at scene/gui/control.cpp:856
#4  0x0000000001257538 in ScrollBar::get_grabber_min_size () at scene/gui/scroll_bar.cpp:441
#5  0x000000000125aa66 in ScrollBar::get_minimum_size () at scene/gui/scroll_bar.cpp:537
#6  0x0000000001295e31 in Control::get_combined_minimum_size () at scene/gui/control.cpp:149
#7  0x000000000136654b in Tree::get_column_width () at scene/gui/tree.cpp:3206
#8  0x0000000001366b57 in Tree::_find_item_at_pos () at scene/gui/tree.cpp:3486
#9  0x0000000001366a8b in Tree::_find_item_at_pos () at scene/gui/tree.cpp:3512
#10 0x0000000001366a8b in Tree::_find_item_at_pos () at scene/gui/tree.cpp:3512
#11 0x000000000136701f in Tree::get_item_at_position () at scene/gui/tree.cpp:3590
#12 0x0000000001370964 in Tree::_gui_input () at scene/gui/tree.cpp:2515
#13 0x0000000000cf1ed7 in MethodBind1<Ref<InputEvent> >::call () at core/method_bind.gen.inc:729
#14 0x0000000001cc8419 in Object::call_multilevel () at core/object.cpp:747
#15 0x0000000001cc2941 in Object::call_multilevel () at core/object.cpp:853
#16 0x00000000011c096a in Viewport::_gui_show_modal () at scene/main/viewport.cpp:2380
#17 0x0000000001296bd1 in Control::show_modal () at scene/gui/control.cpp:2094
#18 0x000000000133f66c in Popup::popup_centered () at scene/gui/popup.cpp:160
#19 0x000000000133f883 in Popup::popup_centered_minsize () at scene/gui/popup.cpp:144
#20 0x0000000000c44af2 in EditorNode::load_scene () at editor/editor_node.cpp:3020
#21 0x00000000004ad620 in MethodBind1<String const&>::call () at core/method_bind.gen.inc:729
#22 0x0000000001cc87a6 in Object::call () at core/object.cpp:913
#23 0x0000000001ccd929 in Object::emit_signal () at core/object.cpp:1194
#24 0x0000000001cce4d0 in Object::emit_signal () at core/object.cpp:1239
#25 0x0000000000cb0e13 in SceneTreeEditor::_cell_button_pressed () at editor/scene_tree_editor.cpp:63
#26 0x00000000004abf44 in MethodBind3<Object*, int, int>::call () at core/method_bind.gen.inc:2151
#27 0x0000000001cc87a6 in Object::call () at core/object.cpp:913
#28 0x0000000001ccd929 in Object::emit_signal () at core/object.cpp:1194
#29 0x0000000001cce4d0 in Object::emit_signal () at core/object.cpp:1239
#30 0x0000000001370a04 in Tree::_gui_input () at scene/gui/tree.cpp:2516
#31 0x0000000000cf1ed7 in MethodBind1<Ref<InputEvent> >::call () at core/method_bind.gen.inc:729
#32 0x0000000001cc8419 in Object::call_multilevel () at core/object.cpp:747
#33 0x0000000001cc2941 in Object::call_multilevel () at core/object.cpp:853
#34 0x00000000011c096a in Viewport::_gui_show_modal () at scene/main/viewport.cpp:2380
#35 0x0000000001296bd1 in Control::show_modal () at scene/gui/control.cpp:2094
#36 0x000000000133f66c in Popup::popup_centered () at scene/gui/popup.cpp:160
---Type <return> to continue, or q <return> to quit---

(gdb) list
327		_FORCE_INLINE_ const TData *getptr(const TKey &p_key) const {
328	
329			if (unlikely(!hash_table))
330				return NULL;
331	
332			const Element *e = const_cast<Element *>(get_element(p_key));
333	
334			if (e)
335				return &e->pair.data;
336	

```

**Comment by capnm** [comment]
1fa9aac3e415f53a095e955c8a37000629d56dde fixes this too.

**Comment by LinuxUserGD** [comment]
Ok
