### ISSUE TITLE
Duplication of a GiProbe causes editor crash in some instances.

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#15384]
**Godot version:**
 a8a3d5c83

**OS/device including version:**
Windows 10 x64 pro

**Issue description:**
When baking GiProbes it is possible to crash the editor. If the GiProbes are duplicated and not added to the scene the chance for a crash is more likely.

**Steps to reproduce:**
To reproduce a crash, load the project and try to bake a GiProbe. Or duplicate a probe and try to bake it.

**Minimal reproduction project:**
[FPS_Controller_Kinematic_2.zip](https://github.com/godotengine/godot/files/1608437/FPS_Controller_Kinematic_2.zip)

**Comment by akien-mga** [comment]
I can reproduce the crash using the provided project:
```
Thread 3 "godot-git" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffee9ac700 (LWP 3206)]
0x00000000025d6c6b in VisualServerScene::_bake_gi_probe_light (this=0x7fffee9ad020, header=0x13ad3b10, cells=0x13ad3b50, local_data=0x11cc7a80, leaves=0x106360a0, p_leaf_count=65993, 
    light_cache=..., p_sign=-1) at servers/visual/visual_server_scene.cpp:2517
2517                                                    (((cells[idx].normal >> 0) & 0xFF) / 255.0) * 2.0 - 1.0);
#0  0x00000000025d6c6b in VisualServerScene::_bake_gi_probe_light (this=0x7fffee9ad020, header=0x13ad3b10, cells=0x13ad3b50, local_data=0x11cc7a80, leaves=0x106360a0, p_leaf_count=65993, 
    light_cache=..., p_sign=-1) at servers/visual/visual_server_scene.cpp:2517
(gdb) bt
#1  0x00000000025d84b8 in VisualServerScene::_bake_gi_probe (this=0x7fffee9ad020, p_gi_probe=0x102431a0) at servers/visual/visual_server_scene.cpp:2731
#2  0x00000000025d63b6 in VisualServerScene::_gi_probe_bake_thread (this=0x7fffee9ad020) at servers/visual/visual_server_scene.cpp:2392
#3  0x00000000025d506a in VisualServerScene::_gi_probe_bake_threads (self=0x7fffee9ad020) at servers/visual/visual_server_scene.cpp:2159
#4  0x000000000158db33 in ThreadPosix::thread_callback (userdata=0x41afa10) at drivers/unix/thread_posix.cpp:70
#5  0x00007ffff57ad66d in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff4a4fd4d in clone () from /lib64/libc.so.6
```

**Comment by AndreaCatania** [comment]
This  #15531 will fix it
