### ISSUE TITLE
Exporting auto-property of C# class makes scene fail to run

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15387]
**Godot version:**
`master` / 8e8240450edc48f4fb379e593a4ef7f54ab656b7 (with the fix applied from #15385)

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
When I put `[Export]` attribute on an auto property of a C# class, it makes the scene which contains the class crash when run with the following error:
```
ERROR: gdmono_MonoLogCallback: Mono: FATAL ERROR, ABORTING! Logfile: /home/fender/.local/share/godot/mono/mono_logs/1515221386.txt

   At: modules/mono/mono_gd/gd_mono_log.cpp:74.
```
Not sure if it'd help, but it also logs following native stack information when it happens:

```
Native stacktrace:

        /usr/lib/libmonosgen-2.0.so.1(+0xe07e5) [0x7f677b2f07e5]
        /usr/lib/libpthread.so.0(+0x11da0) [0x7f677a8abda0]
        /usr/lib/libc.so.6(gsignal+0x110) [0x7f6779f78860]
        /usr/lib/libc.so.6(abort+0x1c9) [0x7f6779f79ec9]
        /usr/bin/godot(_Z22gdmono_MonoLogCallbackPKcS0_S0_iPv+0x2d8) [0x68680f2848]
        /usr/lib/libmonosgen-2.0.so.1(monoeg_g_logv+0x4e) [0x7f677b50aa5e]
        /usr/lib/libmonosgen-2.0.so.1(monoeg_g_log+0x90) [0x7f677b50ab30]
        /usr/lib/libmonosgen-2.0.so.1(+0x22e92b) [0x7f677b43e92b]
        /usr/lib/libmonosgen-2.0.so.1(mono_runtime_invoke_array+0x2b) [0x7f677b43f07b]
        /usr/bin/godot(_ZN14GDMonoProperty9set_valueEP11_MonoObjectS1_PS1_+0x7e) [0x68680ee12e]
        /usr/bin/godot(_ZN14CSharpInstance3setERK10StringNameRK7Variant+0x241) [0x68680d7821]
        /usr/bin/godot(_ZN6Object3setERK10StringNameRK7VariantPb+0x41) [0x6869b4dda1]
        /usr/bin/godot(_ZNK10SceneState8instanceENS_12GenEditStateE+0x1160) [0x6869799e70]
        /usr/bin/godot(_ZNK11PackedScene8instanceENS_12GenEditStateE+0x27) [0x686979c0f7]
        /usr/bin/godot(_ZN4Main5startEv+0x4709) [0x6867f8eff9]
        /usr/bin/godot(main+0x80) [0x6867f6d7d0]
        /usr/lib/libc.so.6(__libc_start_main+0xea) [0x7f6779f64f4a]
        /usr/bin/godot(_start+0x2a) [0x6867f6d66a]

Debug info from gdb:

[New LWP 14967]
[New LWP 14968]
[New LWP 14969]
[New LWP 14970]
[New LWP 14971]
[New LWP 14972]
[New LWP 14973]
[New LWP 14974]
[setting tty state failed in terminal_inferior: 입력/출력 오류]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f677a8ab687 in waitpid () from /usr/lib/libpthread.so.0
  Id   Target Id         Frame 
* 1    Thread 0x7f677dd8b840 (LWP 14966) "godot" 0x00007f677a8ab687 in waitpid () from /usr/lib/libpthread.so.0
  2    Thread 0x7f677dde4700 (LWP 14967) "godot" 0x00007f677a8a9cc6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  3    Thread 0x7f6772148700 (LWP 14968) "godot" 0x00007f677a8a9cc6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  4    Thread 0x7f676e107700 (LWP 14969) "threaded-ml" 0x00007f677a02ff2b in poll () from /usr/lib/libc.so.6
  5    Thread 0x7f676d906700 (LWP 14970) "godot" 0x00007f677a8a738d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  6    Thread 0x7f676c0b8700 (LWP 14971) "godot" 0x00007f677a008170 in nanosleep () from /usr/lib/libc.so.6
  7    Thread 0x7f675abff700 (LWP 14972) "SGen worker" 0x00007f677a8a738d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  8    Thread 0x7f675b777700 (LWP 14973) "Finalizer" 0x00007f677a8a9cc6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  9    Thread 0x7f675b251700 (LWP 14974) "Debugger agent" 0x00007f677a8aac7b in accept () from /usr/lib/libpthread.so.0

Thread 9 (Thread 0x7f675b251700 (LWP 14974)):
#0  0x00007f677a8aac7b in accept () from /usr/lib/libpthread.so.0
#1  0x00007f677b3118c5 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#2  0x00007f677b323355 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#3  0x00007f677b458e51 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7f675b777700 (LWP 14973)):
#0  0x00007f677a8a9cc6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007f677a8a9db8 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x00007f677b499409 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#3  0x00007f677b458e51 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7f675abff700 (LWP 14972)):
#0  0x00007f677a8a738d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f677b4e997b in ?? () from /usr/lib/libmonosgen-2.0.so.1
#2  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7f676c0b8700 (LWP 14971)):
#0  0x00007f677a008170 in nanosleep () from /usr/lib/libc.so.6
#1  0x00007f677a032674 in usleep () from /usr/lib/libc.so.6
#2  0x0000006867f7c3b1 in JoypadLinux::monitor_joypads() ()
#3  0x000000686868f680 in ThreadPosix::thread_callback(void*) ()
#4  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7f676d906700 (LWP 14970)):
#0  0x00007f677a8a738d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f677bd65d89 in pa_threaded_mainloop_wait () from /usr/lib/libpulse.so.0
#2  0x00007f677bf84ae7 in pa_simple_write () from /usr/lib/libpulse-simple.so.0
#3  0x0000006868620629 in AudioDriverPulseAudio::thread_func(void*) ()
#4  0x000000686868f680 in ThreadPosix::thread_callback(void*) ()
#5  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f676e107700 (LWP 14969)):
#0  0x00007f677a02ff2b in poll () from /usr/lib/libc.so.6
#1  0x00007f677bd65773 in ?? () from /usr/lib/libpulse.so.0
#2  0x00007f677bd56bd0 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#3  0x00007f677bd57271 in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#4  0x00007f677bd57301 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#5  0x00007f677bd656ae in ?? () from /usr/lib/libpulse.so.0
#6  0x00007f677901a81c in ?? () from /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f6772148700 (LWP 14968)):
#0  0x00007f677a8a9cc6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007f677a8a9db8 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x000000686868f923 in SemaphorePosix::wait() ()
#3  0x0000006869a10f6a in VisualServerScene::_gi_probe_bake_thread() ()
#4  0x000000686868f680 in ThreadPosix::thread_callback(void*) ()
#5  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f677dde4700 (LWP 14967)):
#0  0x00007f677a8a9cc6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007f677a8a9db8 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x000000686868f923 in SemaphorePosix::wait() ()
#3  0x0000006869d92fac in _IP_ResolverPrivate::_thread_function(void*) ()
#4  0x000000686868f680 in ThreadPosix::thread_callback(void*) ()
#5  0x00007f677a8a108a in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f677a03a42f in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f677dd8b840 (LWP 14966)):
#0  0x00007f677a8ab687 in waitpid () from /usr/lib/libpthread.so.0
#1  0x00007f677b2f089d in ?? () from /usr/lib/libmonosgen-2.0.so.1
#2  <signal handler called>
#3  0x00007f6779f78860 in raise () from /usr/lib/libc.so.6
#4  0x00007f6779f79ec9 in abort () from /usr/lib/libc.so.6
#5  0x00000068680f2848 in gdmono_MonoLogCallback(char const*, char const*, char const*, int, void*) ()
#6  0x00007f677b50aa5e in monoeg_g_logv () from /usr/lib/libmonosgen-2.0.so.1
#7  0x00007f677b50ab30 in monoeg_g_log () from /usr/lib/libmonosgen-2.0.so.1
#8  0x00007f677b43e92b in ?? () from /usr/lib/libmonosgen-2.0.so.1
#9  0x00007f677b43f07b in mono_runtime_invoke_array () from /usr/lib/libmonosgen-2.0.so.1
#10 0x00000068680ee12e in GDMonoProperty::set_value(_MonoObject*, _MonoObject*, _MonoObject**) ()
#11 0x00000068680d7821 in CSharpInstance::set(StringName const&, Variant const&) ()
#12 0x0000006869b4dda1 in Object::set(StringName const&, Variant const&, bool*) ()
#13 0x0000006869799e70 in SceneState::instance(SceneState::GenEditState) const ()
#14 0x000000686979c0f7 in PackedScene::instance(PackedScene::GenEditState) const ()
#15 0x0000006867f8eff9 in Main::start() ()
#16 0x0000006867f6d7d0 in main ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Nothing read: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.
```

**Steps to reproduce:**

Adding this code snippet reproduces the problem:
```c#
        [Export]
        public string SomeProperty { get; set; }
```
On the other hand, the following code does not result in a crash:
```c#
        [Export]
        public string SomeProperty;
```

**Comment by mysticfall** [comment]
It seems that the problem only occur with auto properties that are writable. In other words, the following code does not cause a crash (though it's quite useless for an obvious reason) : 
```c#
[Export]
public string SomeProperty { get; } = "Value";
```
