### ISSUE TITLE
errors during link when building javascript export templates

### ISSUE THREAD

**Issue by brainsick** [godotengine/godot#15652]
**Godot version:**
702e28f

**OS/device including version:**
Ubuntu 17.10 x64
Latest Emscripten SDK

**Issue description:**
I was following the [compiling for the web](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_web.html) instructions and get the following error during the build.

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot$ source ~/Downloads/emsdk-portable/emsdk_env.sh
Adding directories to PATH:
PATH += /home/todd/Downloads/emsdk-portable
PATH += /home/todd/Downloads/emsdk-portable/clang/e1.37.28_64bit
PATH += /home/todd/Downloads/emsdk-portable/node/4.1.1_64bit/bin
PATH += /home/todd/Downloads/emsdk-portable/emscripten/1.37.28

Setting environment variables:
EMSDK = /home/todd/Downloads/emsdk-portable
EM_CONFIG = /home/todd/.emscripten
BINARYEN_ROOT = /home/todd/Downloads/emsdk-portable/clang/e1.37.28_64bit/binaryen
EMSCRIPTEN = /home/todd/Downloads/emsdk-portable/emscripten/1.37.28

todd@todd-ab28d3:~/repos/remote/brainsick-godot$ scons platform=javascript tools=no target=release
scons: Reading SConscript files ...
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 99%] Linking Program        ==> bin/godot.javascript.opt.js
emcc: warning: cannot represent a NaN literal '0xc252b10' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
emcc: warning: cannot represent a NaN literal '0xc252b10' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
warning: unresolved symbol: glMapBufferRange
warning: unresolved symbol: glUnmapBuffer
warning: unresolved symbol: posix_spawn_file_actions_adddup2
warning: unresolved symbol: posix_spawn_file_actions_destroy
warning: unresolved symbol: posix_spawn_file_actions_init
warning: unresolved symbol: sem_getvalue
Stack: Error
    at assertTrue (eval at globalEval (/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/js-optimizer.js:114:8), <anonymous>:59:26)
    at Object.emitDCEGraph (/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/js-optimizer.js:8125:3)
    at /home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/js-optimizer.js:8349:14
    at Array.forEach (native)
    at Object.<anonymous> (/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/js-optimizer.js:8348:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

undefined:60
    throw msg;
    ^
Assertion failed: undefined
Traceback (most recent call last):
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/emcc", line 13, in <module>
    emcc.run()
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/emcc.py", line 1886, in run
    wasm_text_target, misc_temp_files, optimizer)
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/emcc.py", line 2428, in do_binaryen
    emit_symbol_map=emit_symbol_map)
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 2300, in minify_wasm_js
    js_file = Building.metadce(js_file, wasm_file, minify_whitespace=minify_whitespace, debug_info=debug_info)
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 2322, in metadce
    txt = Building.js_optimizer_no_asmjs(js_file, ['emitDCEGraph', 'noEmitAst'], return_output=True)
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 2171, in js_optimizer_no_asmjs
    return run_process(NODE_JS + [js_optimizer.JS_OPTIMIZER, filename] + passes, stdout=PIPE).stdout
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 223, in run_process
    return run_base(cmd, universal_newlines=universal_newlines, check=check, *args, **kw)
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 219, in run_base
    result.check_returncode()
  File "/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/shared.py", line 206, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['/home/todd/Downloads/emsdk-portable/node/4.1.1_64bit/bin/node', '/home/todd/Downloads/emsdk-portable/emscripten/1.37.28/tools/js-optimizer.js', '/tmp/tmph3q5hr/godot.javascript.opt.bc.o.js.pp.js.mem.js.jso.js', 'emitDCEGraph', 'noEmitAst']' returned non-zero exit status 1
scons: *** [bin/godot.javascript.opt.js] Error 1
scons: building terminated because of errors.
```

emcc at least seems happy:

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.28
clang version 4.0.0  (emscripten 1.37.28 : 1.37.28)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/todd/Downloads/emsdk-portable/clang/e1.37.28_64bit
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/7.2.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.2.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```

**Comment by akien-mga** [comment]
CC @eska014

**Comment by brainsick** [comment]
For what it's worth, EMSCRIPTEN_ROOT was exported at the time and it matched the value in the .emscripten file:

```
todd@todd-ab28d3:~$ cat ~/.emscripten
import os
LLVM_ROOT='/home/todd/Downloads/emsdk-portable/clang/e1.37.28_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='/home/todd/Downloads/emsdk-portable/clang/e1.37.28_64bit/optimizer'
BINARYEN_ROOT='/home/todd/Downloads/emsdk-portable/clang/e1.37.28_64bit/binaryen'
NODE_JS='/home/todd/Downloads/emsdk-portable/node/4.1.1_64bit/bin/node'
EMSCRIPTEN_ROOT='/home/todd/Downloads/emsdk-portable/emscripten/1.37.28'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```
