### ISSUE TITLE
Bake with no meshes and crash

### ISSUE THREAD

**Issue by honix** [godotengine/godot#1990]
upd: ops... wrong usage. but crash is not good :) if it have child meshes it is work fine

Pressing Bake! button of BakedLightInstance and got crashed

![error](https://cloud.githubusercontent.com/assets/11596541/7814522/57f3f8a6-03cb-11e5-9830-d3e27b395e1e.PNG)

"Program is not working"

**Comment by bojidar-bg** [comment]
Is this still valid on 2.0 or master?

**Comment by 29jm** [comment]
I can confirm the crash in the current master

**Comment by akien-mga** [comment]
I'm not sure what should be the exact setup for a BakedLightInstance to be able to bake properly, but the misconfigured should be checked before baking, and a warning displayed instead of starting to bake.

Here is the segfault backtrace:
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x0000000000aaac54 in BakedLightBaker::_make_octree (this=0x78a1800) at tools/editor/plugins/baked_light_baker.cpp:733
733             AABB base = bvh->aabb;

(gdb) bt
#0  0x0000000000aaac54 in BakedLightBaker::_make_octree (this=0x78a1800) at tools/editor/plugins/baked_light_baker.cpp:733
#1  0x0000000000ab0143 in BakedLightBaker::bake (this=0x78a1800, p_light=..., p_node=0x8481d90) at tools/editor/plugins/baked_light_baker.cpp:1780
#2  0x0000000000aa42c5 in BakedLightEditor::_bake_pressed (this=0x78990c0) at tools/editor/plugins/baked_light_editor_plugin.cpp:234
#3  0x00000000004ab34a in MethodBind0::call (this=0x78a2bf0, p_object=0x78990c0, p_args=0x7fffffffb550, p_arg_count=0, r_error=...) at core/method_bind.inc:47
#4  0x00000000018591bd in Object::call (this=0x78990c0, p_method=..., p_args=0x7fffffffb550, p_argcount=0, r_error=...) at core/object.cpp:896
#5  0x000000000185ac81 in Object::emit_signal (this=0x7899d50, p_name=..., p_args=0x7fffffffb550, p_argcount=0) at core/object.cpp:1209
#6  0x000000000185b0ff in Object::emit_signal (this=0x7899d50, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1253
#7  0x0000000000f8549e in BaseButton::_input_event (this=0x7899d50, p_event=...) at scene/gui/base_button.cpp:124
#8  0x00000000009e8658 in MethodBind1<InputEvent>::call (this=0x361cbf0, p_object=0x7899d50, p_args=0x7fffffffc100, p_arg_count=1, r_error=...) at core/method_bind.inc:653
#9  0x000000000185853f in Object::call_multilevel (this=0x7899d50, p_method=..., p_args=0x7fffffffc100, p_argcount=1) at core/object.cpp:622
#10 0x0000000001858d9d in Object::call_multilevel (this=0x7899d50, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:830
#11 0x0000000000f22b98 in Viewport::_gui_call_input (this=0x38e5680, p_control=0x7899d50, p_input=...) at scene/main/viewport.cpp:1619
#12 0x0000000000f24034 in Viewport::_gui_input_event (this=0x38e5680, p_event=...) at scene/main/viewport.cpp:1919
#13 0x0000000000f26805 in Viewport::input (this=0x38e5680, p_event=...) at scene/main/viewport.cpp:2433
#14 0x0000000000f21f11 in Viewport::_vp_input (this=0x38e5680, p_ev=...) at scene/main/viewport.cpp:1462
#15 0x000000000098b1d0 in MethodBind1<InputEvent const&>::call (this=0x35e3f90, p_object=0x38e5680, p_args=0x7fffffffce20, p_arg_count=1, r_error=...) at core/method_bind.inc:653
#16 0x00000000018591bd in Object::call (this=0x38e5680, p_method=..., p_args=0x7fffffffce20, p_argcount=1, r_error=...) at core/object.cpp:896
#17 0x0000000001858cf4 in Object::call (this=0x38e5680, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:770
#18 0x0000000000f06f9c in SceneTree::call_group (this=0x38e6e80, p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at scene/main/scene_main_loop.cpp:215
#19 0x0000000000f07bd5 in SceneTree::input_event (this=0x38e6e80, p_event=...) at scene/main/scene_main_loop.cpp:431
#20 0x000000000041b37b in InputDefault::parse_input_event (this=0x347ce20, p_event=...) at main/input_default.cpp:345
#21 0x0000000000412775 in OS_X11::process_xevents (this=0x7fffffffd740) at platform/x11/os_x11.cpp:1362
#22 0x000000000041494b in OS_X11::run (this=0x7fffffffd740) at platform/x11/os_x11.cpp:1917
#23 0x000000000040cf20 in main (argc=2, argv=0x7fffffffdc48) at platform/x11/godot_x11.cpp:41
```

**Comment by djrm** [comment]
i managed to solve this by checking if the triangles count > 0, but i dont know if this is the only case.
