### ISSUE TITLE
Clicking on the arrows on unmapped input keys crashes the editor

### ISSUE THREAD

**Issue by hungrymonkey** [godotengine/godot#20184]
**Godot version:**

master

https://github.com/godotengine/godot/commit/c0c243ac5c0a8b03a64fdb18b0e647ae6427279c

**OS/device including version:**

tested on osx 10.13.6

**Issue description:**

```
ERROR: clear: Condition ' blocked > 0 ' is true.
   At: scene/gui/tree.cpp:3120.
ERROR: create_item: Condition ' blocked > 0 ' is true. returned: __null
   At: scene/gui/tree.cpp:2975.
ERROR: create_item: Condition ' blocked > 0 ' is true. returned: __null
   At: scene/gui/tree.cpp:2975.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff4fd07f5a _sigtramp + 26
[2] 2   libsystem_malloc.dylib              0x00007fff884fd000 virtual_default_zone + 0
[3] Vector<TreeItem::Cell>::size() const (in godot.osx.tools.64) (vector.h:113)
[4] TreeItem::set_text(int, String) (in godot.osx.tools.64) (tree.cpp:159)
[5] ProjectSettingsEditor::_update_actions() (in godot.osx.tools.64) (project_settings_editor.cpp:678)
[6] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (in godot.osx.tools.64) (method_bind.gen.inc:56)
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (in godot.osx.tools.64) (object.cpp:914)
[8] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (in godot.osx.tools.64) (object.cpp:839)
```

**Steps to reproduce:**

Project -> Project Settings -> Input Map -> add action -> click on the arrows -> crashes the editor

**Minimal reproduction project:**

any project.

**Comment by hungrymonkey** [comment]
workaround, edit project.godot manually

**Comment by akien-mga** [comment]
Can't reproduce it on Linux (Mageia 6 x86_64) with de910f8.

**Comment by hungrymonkey** [comment]
```
./bin/godot.osx.tools.64
arguments
0: ./bin/godot.osx.tools.64
Current path: /Users/psuedofinnish/godot_test
OpenGL ES 3.0 Renderer: AMD Radeon Pro 455 OpenGL Engine
OPENING: /Users/psuedofinnish/New Game Project (::Users::psuedofinnish::New Game Project)
arguments
0: /Users/psuedofinnish/godot_test/bin/godot.osx.tools.64
1: --path
2: /Users/psuedofinnish/New Game Project
3: --editor
Current path: /Users/psuedofinnish/godot_test
psuedos-MBP:godot_test psuedofinnish$ OpenGL ES 3.0 Renderer: AMD Radeon Pro 455 OpenGL Engine
ERROR: clear: Condition ' blocked > 0 ' is true.
   At: scene/gui/tree.cpp:3120.
ERROR: create_item: Condition ' blocked > 0 ' is true. returned: __null
   At: scene/gui/tree.cpp:2975.
ERROR: create_item: Condition ' blocked > 0 ' is true. returned: __null
   At: scene/gui/tree.cpp:2975.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] 1   libsystem_platform.dylib            0x00007fff4fd07f5a _sigtramp + 26
[2] 2   libsystem_malloc.dylib              0x00007fff884fd000 virtual_default_zone + 0
[3] Vector<TreeItem::Cell>::size() const (in godot.osx.tools.64) (vector.h:113)
[4] TreeItem::set_text(int, String) (in godot.osx.tools.64) (tree.cpp:159)
[5] ProjectSettingsEditor::_update_actions() (in godot.osx.tools.64) (project_settings_editor.cpp:687)
[6] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (in godot.osx.tools.64) (method_bind.gen.inc:56)
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (in godot.osx.tools.64) (object.cpp:914)
[8] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (in godot.osx.tools.64) (object.cpp:839)
[9] UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) (in godot.osx.tools.64) (undo_redo.cpp:271)
```

tested c5690240b440871f2121afa3cc8c470152836558

still crashes on OSX. i am debating whether or not to test on my linux machine. it would be strange if this bug is OSX specific.

**Comment by hungrymonkey** [comment]
tested 2f365bb9bb9f0402100ecd1c05670065fd95acf3


```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 4.2 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.20

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```
I cannot reproduce the bug. it seem like this bug might be osx only.

**Comment by AlexHolly** [comment]
x11
Maybe related? Happens when I press on the arrows for the deadzone.

![image](https://user-images.githubusercontent.com/4741886/43047726-e96e7502-8ddb-11e8-8a93-12749e9e060e.png)

```
Thread 1 "godot.x11.tools" received signal SIGSEGV, Segmentation fault.
0x00000000022fc4a2 in Vector<TreeItem::Cell>::_get_size (this=0xe8)
    at ./core/vector.h:61
61			if (!_ptr)
(gdb) bt
#0  0x00000000022fc4a2 in Vector<TreeItem::Cell>::_get_size (this=0xe8)
    at ./core/vector.h:61
#1  0x00000000022f9a10 in Vector<TreeItem::Cell>::size (this=0xe8)
    at ./core/vector.h:113
#2  0x00000000022d6ed3 in TreeItem::set_text (this=0x0, p_column=0, p_text=...)
    at scene/gui/tree.cpp:159
#3  0x0000000001a8b526 in ProjectSettingsEditor::_update_actions (
    this=0x6329070) at editor/project_settings_editor.cpp:693
#4  0x00000000010d52a1 in MethodBind0::call (this=0x654d280, 
    p_object=0x6329070, p_args=0x7fffffffab50, p_arg_count=0, r_error=...)
    at core/method_bind.gen.inc:54
#5  0x0000000002f1b9f8 in Object::call (this=0x6329070, p_method=..., 
    p_args=0x7fffffffab50, p_argcount=0, r_error=...) at core/object.cpp:918
#6  0x0000000002f1b4d0 in Object::call (this=0x6329070, p_name=..., 
    p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at core/object.cpp:842
#7  0x0000000002e3693b in UndoRedo::_process_operation_list (this=0x53299d8, 
    E=0x90fde90) at core/undo_redo.cpp:271
#8  0x0000000002e36c89 in UndoRedo::redo (this=0x53299d8)
    at core/undo_redo.cpp:310
#9  0x0000000002e3677a in UndoRedo::commit_action (this=0x53299d8)
    at core/undo_redo.cpp:247
#10 0x0000000001a837ae in ProjectSettingsEditor::_action_edited (
---Type <return> to continue, or q <return> to quit---bg
    this=0x6329070) at editor/project_settings_editor.cpp:221
#11 0x00000000010d52a1 in MethodBind0::call (this=0x654cf30, 
    p_object=0x6329070, p_args=0x7fffffffb780, p_arg_count=0, r_error=...)
    at core/method_bind.gen.inc:54
#12 0x0000000002f1b9f8 in Object::call (this=0x6329070, p_method=..., 
    p_args=0x7fffffffb780, p_argcount=0, r_error=...) at core/object.cpp:918
#13 0x0000000002f1d38b in Object::emit_signal (this=0x6365b70, p_name=..., 
    p_args=0x7fffffffb780, p_argcount=0) at core/object.cpp:1199
#14 0x0000000002f1d922 in Object::emit_signal (this=0x6365b70, p_name=..., 
    p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at core/object.cpp:1244
#15 0x00000000022ef5c3 in Tree::item_edited (this=0x6365b70, p_column=1, 
    p_item=0xa344980, p_lmb=true) at scene/gui/tree.cpp:3049
#16 0x00000000022e7184 in Tree::propagate_mouse_event (this=0x6365b70, 
    p_pos=..., x_ofs=0, y_ofs=875, p_doubleclick=false, p_item=0xa344980, 
    p_button=1, p_mod=...) at scene/gui/tree.cpp:1869
#17 0x00000000022e79ea in Tree::propagate_mouse_event (this=0x6365b70, 
    p_pos=..., x_ofs=0, y_ofs=875, p_doubleclick=false, p_item=0xa302e70, 
    p_button=1, p_mod=...) at scene/gui/tree.cpp:1951
#18 0x00000000022ebe5a in Tree::_gui_input (this=0x6365b70, p_event=...)
    at scene/gui/tree.cpp:2603
#19 0x0000000001c80313 in MethodBind1<Ref<InputEvent> >::call (this=0x4d0d040, 
    p_object=0x6365b70, p_args=0x7fffffffc5d0, p_arg_count=1, r_error=...)
---Type <return> to continue, or q <return> to quit---
    at core/method_bind.gen.inc:729
#20 0x0000000002f1ac84 in Object::call_multilevel (this=0x6365b70, 
    p_method=..., p_args=0x7fffffffc5d0, p_argcount=1) at core/object.cpp:752
#21 0x0000000002f1b5a4 in Object::call_multilevel (this=0x6365b70, p_name=..., 
    p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at core/object.cpp:858
#22 0x0000000002238414 in Viewport::_gui_call_input (this=0x51fde70, 
    p_control=0x6365b70, p_input=...) at scene/main/viewport.cpp:1436
#23 0x000000000223966e in Viewport::_gui_input_event (this=0x51fde70, 
    p_event=...) at scene/main/viewport.cpp:1715
#24 0x000000000223db1e in Viewport::input (this=0x51fde70, p_event=...)
    at scene/main/viewport.cpp:2450

#25 0x000000000223728a in Viewport::_vp_input (this=0x51fde70, p_ev=...)
    at scene/main/viewport.cpp:1218
#26 0x00000000012aed81 in MethodBind1<Ref<InputEvent> const&>::call (
    this=0x4caa340, p_object=0x51fde70, p_args=0x7fffffffcf70, p_arg_count=1, 
    r_error=...) at core/method_bind.gen.inc:729
#27 0x0000000002f1b9f8 in Object::call (this=0x51fde70, p_method=..., 
    p_args=0x7fffffffcf70, p_argcount=1, r_error=...) at core/object.cpp:918
#28 0x0000000002f1b4d0 in Object::call (this=0x51fde70, p_name=..., 
    p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at core/object.cpp:842
#29 0x00000000021e25dc in SceneTree::call_group_flags (this=0x51b7290, 
---Type <return> to continue, or q <return> to quit---
    p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., 
    p_arg3=..., p_arg4=..., p_arg5=...) at scene/main/scene_tree.cpp:251
#30 0x00000000021e33ba in SceneTree::input_event (this=0x51b7290, p_event=...)
    at scene/main/scene_tree.cpp:407
#31 0x0000000001043c63 in InputDefault::_parse_input_event_impl (
    this=0x4b5ff10, p_event=..., p_is_emulated=false)
    at main/input_default.cpp:417
#32 0x0000000001042dd6 in InputDefault::parse_input_event (this=0x4b5ff10, 
    p_event=...) at main/input_default.cpp:259
#33 0x0000000001031ea1 in OS_X11::process_xevents (this=0x7fffffffd710)
    at platform/x11/os_x11.cpp:1921
#34 0x00000000010358e9 in OS_X11::run (this=0x7fffffffd710)
    at platform/x11/os_x11.cpp:2628
#35 0x0000000001028bd9 in main (argc=2, argv=0x7fffffffdd38)
    at platform/x11/godot_x11.cpp:55

```

**Comment by hungrymonkey** [comment]
hmmm, i was probably clicking the wrong key because osx seems to have an ui rendering issue

@AlexHolly 

you are right

```
ERROR: clear: Condition ' blocked > 0 ' is true.
   At: scene/gui/tree.cpp:3120.
ERROR: create_item: Condition ' blocked > 0 ' is true. returned: __null
   At: scene/gui/tree.cpp:2975.
ERROR: create_item: Condition ' blocked > 0 ' is true. returned: __null
   At: scene/gui/tree.cpp:2975.
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f2cb9072f20] (??:0)
[2] Vector<TreeItem::Cell>::_get_size() const (??:0)
[3] Vector<TreeItem::Cell>::size() const (??:0)
[4] TreeItem::set_text(int, String) (??:0)
[5] ProjectSettingsEditor::_update_actions() (??:0)
[6] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[8] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[9] UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) (??:0)
[10] UndoRedo::redo() (??:0)
[11] UndoRedo::commit_action() (??:0)
[12] ProjectSettingsEditor::_action_edited() (??:0)
[13] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[14] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[15] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[16] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[17] Tree::item_edited(int, TreeItem*, bool) (??:0)
[18] Tree::propagate_mouse_event(Point2i const&, int, int, bool, TreeItem*, int, Ref<InputEventWithModifiers> const&) (??:0)
[19] Tree::propagate_mouse_event(Point2i const&, int, int, bool, TreeItem*, int, Ref<InputEventWithModifiers> const&) (??:0)
[20] Tree::_gui_input(Ref<InputEvent>) (??:0)
[21] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[22] Object::call_multilevel(StringName const&, Variant const**, int) (??:0)
[23] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[24] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (??:0)
[25] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[26] Viewport::input(Ref<InputEvent> const&) (??:0)
[27] Viewport::_vp_input(Ref<InputEvent> const&) (??:0)
[28] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (??:0)
[29] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (??:0)
[30] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[31] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[32] SceneTree::input_event(Ref<InputEvent> const&) (??:0)
[33] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[34] InputDefault::parse_input_event(Ref<InputEvent> const&) (??:0)
[35] OS_X11::process_xevents() (??:0)
[36] OS_X11::run() (??:0)
[37] /home/doop/godot/bin/godot.x11.tools.64(main+0xd5) [0x55cfe1c0d91f] (??:0)
[38] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f2cb9055b97] (??:0)
[39] /home/doop/godot/bin/godot.x11.tools.64(_start+0x2a) [0x55cfe1c0d76a] (??:0)
-- END OF BACKTRACE --
```
