### ISSUE TITLE
Error building for javascript

### ISSUE THREAD

**Issue by tomasantunes** [godotengine/godot#20821]
**Godot version:**
9bd5315d3

**OS/device including version:**
Ubuntu 18.04.1

**Issue description:**
I'm trying to compile using this command `scons platform=javascript tools=no target=release` but the following error occurs.

```
/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282
        throw new JS_Parse_Error(message, line, col, pos);
        ^
Error
    at new JS_Parse_Error (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:260:22)
    at js_error (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282:15)
    at croak (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:752:17)
    at token_error (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:760:17)
    at unexpected (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:766:17)
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:840:33
    at block_ (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1010:32)
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:989:43
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:993:29
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1123:43
ERROR:root:'/home/user1/Documents/emsdk/node/8.9.1_64bit/bin/node /home/user1/Documents/emsdk/emscripten/1.38.11/tools/js-optimizer.js /tmp/tmpwzFgkE/godot.javascript.opt.bc.o.js.mem.js noPrintMetadata AJSDCE minifyWhitespace' failed
scons: *** [bin/godot.javascript.opt.js] Error 1
scons: building terminated because of errors.
```

**Comment by eska014** [comment]
Emscripten removed `Module.print()` and `Module.printErr()` in 1.38.7. Please use an earlier version until Godot is adjusted for that change

**Comment by kripken** [comment]
I opened #20922 to fix the `print/printErr` issue.

However, I don't think that would cause a `JS_Parse_Error` exception in the compiler. That usually is because of JS code provided to the emscripten optimizer that it can't handle. I don't see that error on Godot master (with or without that PR) when I run `scons platform=javascript tools=no target=release` - @tomasantunes, do you have any local changes or additions? And is there any additional context earlier in the log? (`EMCC_DEBUG=1` in the env might help)

**Comment by tomasantunes** [comment]
I ran it with EMCC_DEBUG and here is the full error:

```
JS optimizer error:
Unexpected token: punc (,) (line: 1679, col: 684, pos: 58565)

================================


// === Body ===

var ASM_CONSTS = [function() { _audioDriver_audioContext = new (window.AudioContext || window.webkitAudioContext); _audioDriver_scriptNode = null; },
 function($0) { var CHANNEL_COUNT = $0; var channelCount = _audioDriver_audioContext.destination.channelCount; try { _audioDriver_scriptNode = _audioDriver_audioContext.createScriptProcessor(0, 0, channelCount); } catch (e) { _audioDriver_scriptNode = _audioDriver_audioContext.createScriptProcessor(4096, 0, channelCount); } _audioDriver_scriptNode.connect(_audioDriver_audioContext.destination); return _audioDriver_scriptNode.bufferSize; },
 function() { { var INTERNAL_BUFFER_PTR = $0; var audioDriverMixFunction = cwrap('audio_driver_js_mix'); _audioDriver_scriptNode.onaudioprocess = function(audioProcessingEvent) { audioDriverMixFunction(); var output = audioProcessingEvent.outputBuffer; var input = HEAPF32.subarray( INTERNAL_BUFFER_PTR / HEAPF32.BYTES_PER_ELEMENT, INTERNAL_BUFFER_PTR / HEAPF32.BYTES_PER_ELEMENT + output.length * output.numberOfChannels); for (var channel = 0; channel < output.numberOfChannels; channel++) { var outputData = output.getChannelData(channel); for (var sample = 0; sample < outputData.length; sample++) { outputData[sample] = input[sample * output.numberOfChannels + channel]; } } }; }, internal_buffer },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^
================================


/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282
        throw new JS_Parse_Error(message, line, col, pos);
        ^
Error
    at new JS_Parse_Error (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:260:22)
    at js_error (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:282:15)
    at croak (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:752:17)
    at token_error (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:760:17)
    at unexpected (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:766:17)
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:840:33
    at block_ (/home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1010:32)
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:989:43
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:993:29
    at /home/user1/Documents/emsdk/emscripten/1.38.11/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1123:43
ERROR:root:'/home/user1/Documents/emsdk/node/8.9.1_64bit/bin/node /home/user1/Documents/emsdk/emscripten/1.38.11/tools/js-optimizer.js /tmp/tmpF2rBLR/godot.javascript.opt.bc.o.js.mem.js noPrintMetadata AJSDCE minifyWhitespace' failed
scons: *** [bin/godot.javascript.opt.js] Error 1
scons: building terminated because of errors.
```

**Comment by kripken** [comment]
The error is correct - there is in fact an invalid `,` on column 684 there. The question is where it comes from.

That EM_ASM is from `./platform/javascript/audio_driver_javascript.cpp`. Is it possible you have local changes in that file? On current Godot master, when I compile it locally I don't see an error.

If it's not due to local changes or a different branch, I'd try to debug this by changing that EM_ASM (in `AudioDriverJavaScript::start`) - removing code until it compiles ok could find the critical thing that is confusing it.

**Comment by eska014** [comment]
I haven't been able to reproduce this either, @tomasantunes Did you find out anything, are there any changes in the source code (`git diff`)?
