### ISSUE TITLE
Error when clicking on a property exporting a custom resource type

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20857]
Godot 3.0.6

I made a plugin which defines a custom node, and that node has a property which exports a custom resource.
I found that when I click on this property in the inspector, a few wrong things happen:

![image](https://user-images.githubusercontent.com/1311555/43923063-96229cf2-9c18-11e8-8e41-4ee52176f3cc.png)

1) I am not given the option to create an instance of that resource. I can only choose `Load`.
2) An error prints in the console, exactly when I click the property:
```
ERROR: can_instance: Condition ' !ti ' is true. returned: false
   At: core/class_db.cpp:530
```
3) When I click `Load`, a file dialog opens, but more errors get printed:
```
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:331
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:331
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:331
...
etc.
```

Reproduction project:
Just download my terrain plugin from the asset library: https://godotengine.org/asset-library/asset/231
Activate it, then create a `HTerrain` node, which has the `data` property.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by Zylann** [comment]
The `New` works in 3.1 beta 2:
![image](https://user-images.githubusercontent.com/1311555/51634491-43fadb80-1f4c-11e9-9f17-0c37fefcec9a.png)

However, in ab843b16984d8b62a1100d9b77d8b0dcdc4252bb this error prints everytime I click on the node:
```
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:325
```

**Comment by akien-mga** [comment]
Backtrace for the error when selecting the node:
```
(gdb) bt
#0  _err_print_error (p_function=0x4094ad0 <ClassDB::get_parent_class(StringName const&)::__FUNCTION__> "get_parent_class", p_file=0x4094132 "core/class_db.cpp", p_line=325, 
    p_error=0x4094100 "Condition ' !ti ' is true. returned: StringName()", p_type=ERR_HANDLER_ERROR) at core/error_macros.cpp:84
#1  0x00000000030d394b in ClassDB::get_parent_class (p_class=...) at core/class_db.cpp:325
#2  0x00000000030d362d in ClassDB::is_parent_class (p_class=..., p_inherits=...) at core/class_db.cpp:278
#3  0x0000000001d00da1 in EditorInspectorDefaultPlugin::parse_property (this=0x6679340, p_object=0xc0e2210, p_type=Variant::OBJECT, p_path=..., p_hint=PROPERTY_HINT_RESOURCE_TYPE, 
    p_hint_text=..., p_usage=7) at editor/editor_properties.cpp:3159
#4  0x0000000001c4f279 in EditorInspector::update_tree (this=0x8ab6630) at editor/editor_inspector.cpp:1664
#5  0x0000000001c50f5f in EditorInspector::edit (this=0x8ab6630, p_object=0xc0e2210) at editor/editor_inspector.cpp:1804
#6  0x0000000001c77c87 in EditorNode::_edit_current (this=0x662c010) at editor/editor_node.cpp:1509
#7  0x0000000001c77144 in EditorNode::push_item (this=0x662c010, p_object=0xc0e2210, p_property=..., p_inspector_only=false) at editor/editor_node.cpp:1410
#8  0x0000000001e5ca15 in SceneTreeDock::_node_selected (this=0x7fa8150) at editor/scene_tree_dock.cpp:1054
#9  0x0000000001249425 in MethodBind0::call (this=0x8a096a0, p_object=0x7fa8150, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:54
#10 0x000000000315208d in Object::call (this=0x7fa8150, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at core/object.cpp:945
#11 0x0000000003148c51 in MessageQueue::_call_function (this=0x4a84d90, p_target=0x7fa8150, p_func=..., p_args=0x7ffff70b2068, p_argcount=0, p_show_error=true)
    at core/message_queue.cpp:256
#12 0x0000000003148ef0 in MessageQueue::flush (this=0x4a84d90) at core/message_queue.cpp:303
#13 0x00000000024c84f6 in SceneTree::idle (this=0x5e22e20, p_time=0.00833333377) at scene/main/scene_tree.cpp:513
#14 0x00000000011e7874 in Main::iteration () at main/main.cpp:1876
#15 0x00000000011bccdb in OS_X11::run (this=0x7fffffffd340) at platform/x11/os_x11.cpp:2986
#16 0x00000000011aeacd in main (argc=2, argv=0x7fffffffdac8) at platform/x11/godot_x11.cpp:55
```

Backtrace when selecting "New":
```
#0  _err_print_error (p_function=0x4094d28 <ClassDB::instance(StringName const&)::__FUNCTION__> "instance", p_file=0x4094132 "core/class_db.cpp", p_line=512, 
    p_error=0x40941a8 "Condition ' !ti ' is true. returned: __null", p_type=ERR_HANDLER_ERROR) at core/error_macros.cpp:84
#1  0x00000000030d461e in ClassDB::instance (p_class=...) at core/class_db.cpp:512
#2  0x0000000001cf581a in EditorPropertyResource::_menu_option (this=0xcb8ed10, p_which=100) at editor/editor_properties.cpp:2190
#3  0x0000000001256aad in MethodBind1<int>::call (this=0x119f4660, p_object=0xcb8ed10, p_args=0x7fffffffb610, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#4  0x000000000315208d in Object::call (this=0xcb8ed10, p_method=..., p_args=0x7fffffffb610, p_argcount=1, r_error=...) at core/object.cpp:945
#5  0x000000000315390e in Object::emit_signal (this=0xcb900e0, p_name=..., p_args=0x7fffffffb610, p_argcount=1) at core/object.cpp:1231
#6  0x0000000003153f7d in Object::emit_signal (this=0xcb900e0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1287
#7  0x000000000261584e in PopupMenu::activate_item (this=0xcb900e0, p_item=0) at scene/gui/popup_menu.cpp:1102
#8  0x000000000260ed0e in PopupMenu::_gui_input (this=0xcb900e0, p_event=...) at scene/gui/popup_menu.cpp:330
#9  0x000000000140d9f7 in MethodBind1<Ref<InputEvent> const&>::call (this=0x5a15a50, p_object=0xcb900e0, p_args=0x7fffffffbc80, p_arg_count=1, r_error=...)
    at ./core/method_bind.gen.inc:729
#10 0x000000000315143c in Object::call_multilevel (this=0xcb900e0, p_method=..., p_args=0x7fffffffbc80, p_argcount=1) at core/object.cpp:779
#11 0x0000000003151c65 in Object::call_multilevel (this=0xcb900e0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:885
#12 0x00000000024f2845 in Viewport::_gui_call_input (this=0x6018500, p_control=0xcb900e0, p_input=...) at scene/main/viewport.cpp:1542
#13 0x00000000024f3fa0 in Viewport::_gui_input_event (this=0x6018500, p_event=...) at scene/main/viewport.cpp:1912
#14 0x00000000024f80f2 in Viewport::input (this=0x6018500, p_event=...) at scene/main/viewport.cpp:2663
#15 0x00000000024f174c in Viewport::_vp_input (this=0x6018500, p_ev=...) at scene/main/viewport.cpp:1320
#16 0x000000000140d9f7 in MethodBind1<Ref<InputEvent> const&>::call (this=0x5978430, p_object=0x6018500, p_args=0x7fffffffc930, p_arg_count=1, r_error=...)
    at ./core/method_bind.gen.inc:729
#17 0x000000000315208d in Object::call (this=0x6018500, p_method=..., p_args=0x7fffffffc930, p_argcount=1, r_error=...) at core/object.cpp:945
#18 0x0000000003151bbc in Object::call (this=0x6018500, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:869
#19 0x00000000024c6c9d in SceneTree::call_group_flags (this=0x5e22e20, p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at scene/main/scene_tree.cpp:262
#20 0x00000000024c7985 in SceneTree::input_event (this=0x5e22e20, p_event=...) at scene/main/scene_tree.cpp:418
#21 0x00000000011ca89a in InputDefault::_parse_input_event_impl (this=0x5849530, p_event=..., p_is_emulated=false) at main/input_default.cpp:440
#22 0x00000000011c9796 in InputDefault::parse_input_event (this=0x5849530, p_event=...) at main/input_default.cpp:259
#23 0x00000000011b86c7 in OS_X11::process_xevents (this=0x7fffffffd340) at platform/x11/os_x11.cpp:2148
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00000000011bccc3 in OS_X11::run (this=0x7fffffffd340) at platform/x11/os_x11.cpp:2982
#25 0x00000000011aeacd in main (argc=2, argv=0x7fffffffdac8) at platform/x11/godot_x11.cpp:55
```
