### ISSUE TITLE
Random crashes after re-exporting glTF models

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#20863]
**Godot version:**

a71a5fc0c3f5d487d3f18c3b9e9a768052795e86

**OS/device including version:**

Linux gcc 7.3.0

**Issue description:**

```
**creating mesh for: Suzanne
node: Suzanne
node: Suzanne
node: Lamp
node: Camera
SAVING TO: res://.import/suzanne.gltf-cab0368f2fda72cb600b4729991aa93c.scn
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fe121001f20] (??:0)
[2] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__dynamic_cast+0x24) [0x7fe1219fb624] (??:0)
[3] godot3(+0xeb4e70) [0x5649df5d9e70] (??:0)
[4] godot3(+0x2ad614) [0x5649de9d2614] (??:0)
[5] godot3(+0x21bf28c) [0x5649e08e428c] (??:0)
[6] godot3(+0x210b09d) [0x5649e083009d] (??:0)
[7] godot3(+0x210b2f3) [0x5649e08302f3] (??:0)
[8] godot3(+0x133ca84) [0x5649dfa61a84] (??:0)
[9] godot3(+0x22a824) [0x5649de94f824] (??:0)
[10] godot3(+0x2222c1) [0x5649de9472c1] (??:0)
[11] godot3(main+0xcc) [0x5649de9398cc] (??:0)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fe120fe4b97] (??:0)
[13] godot3(+0x217aba) [0x5649de93caba] (??:0)
-- END OF BACKTRACE --
```

**Steps to reproduce:**
Modify the model and export it with the same path. If you're unlucky, godot crashes after the editor-window gets into focus. Loks like a concurrency problem.

**Minimal reproduction project:**

You could still investigate stack trace manually, see the issue:
https://github.com/godotengine/godot/issues/18703

Used Godot Linux64 binary (50MB)
https://capitanio.org/intranet/godot/bin-tip-2018-08-09T16.zip

**Comment by capnm** [comment]
Another crash after clicking of the imported models animations player:
```
**creating mesh for: gdman-body
**creating mesh for: gdman-hand.L
**creating mesh for: gdman-hand.R
**creating mesh for: gdman-head
SAVING TO: res://.import/gdman-ulp-03-1-applymodifier.gltf-616af09067238d4f00fbb9aaedde312e.scn

Thread 1 "godot.x11.opt.t" received signal SIGSEGV, Segmentation fault.
0x000055555687bd62 in Viewport::_gui_call_input () at scene/main/viewport.cpp:1452
1452			ev = ev->xformed_by(ci->get_transform()); //transform event upwards
(gdb) bt
#0  0x000055555687bd62 in Viewport::_gui_call_input () at scene/main/viewport.cpp:1452
#1  0x000055555687da8c in Viewport::_gui_input_event () at scene/main/viewport.cpp:1785
#2  0x000055555687f910 in Viewport::input () at scene/main/viewport.cpp:2477
#3  0x000055555687fb14 in Viewport::_vp_input () at scene/main/viewport.cpp:1221
#4  0x0000555555b14a47 in MethodBind1<Ref<InputEvent> const&>::call ()
    at core/method_bind.gen.inc:729
#5  0x000055555774a41c in Object::call () at core/object.cpp:968
#6  0x00005555577494ee in Object::call () at core/object.cpp:892
#7  0x00005555568b3233 in SceneTree::call_group_flags () at scene/main/scene_tree.cpp:262
#8  0x00005555568b6245 in SceneTree::input_event () at scene/main/scene_tree.cpp:418
#9  0x00005555557967fd in InputDefault::_parse_input_event_impl () at main/input_default.cpp:417
#10 0x00005555557763fc in OS_X11::process_xevents () at platform/x11/os_x11.cpp:1928
#11 0x0000555555777a90 in OS_X11::run () at platform/x11/os_x11.cpp:2635
#12 0x000055555576a06c in main () at platform/x11/godot_x11.cpp:55
(gdb) list
1447			}
1448	
1449			if (ci->is_set_as_toplevel())
1450				break;
1451	
1452			ev = ev->xformed_by(ci->get_transform()); //transform event upwards
1453			ci = ci->get_parent_item();
1454		}
1455	
1456		//_unblock();
(gdb) info threads
  Id   Target Id         Frame 
* 1    LWP 5641 "godot.x11.opt.t" 0x000055555687bd62 in Viewport::_gui_call_input ()
    at scene/main/viewport.cpp:1452
  2    LWP 5642 "godot.x11.opt.t" 0x00007ffff5f766d6 in ?? ()
  3    LWP 5643 "amdgpu_cs:0" 0x00007ffff5f739f3 in ?? ()
  4    LWP 5644 "disk_cache:0" 0x00007ffff5f739f3 in ?? ()
  5    LWP 5645 "si_shader:0" 0x00007ffff5f739f3 in ?? ()
  6    LWP 5646 "si_shader_low:0" 0x00007ffff5f739f3 in ?? ()
  7    LWP 5647 "gallium_drv:0" 0x00007ffff5f739f3 in ?? ()
  8    LWP 5648 "godot.x11.opt.t" 0x00007ffff5f766d6 in ?? ()
  9    LWP 5649 "godot.x11.opt.t" 0x00007ffff5f77c60 in ?? ()
  10   LWP 5650 "godot.x11.opt.t" 0x00007ffff5f77c60 in ?? ()
  11   LWP 5651 "godot.x11.opt.t" 0x00007ffff51119d0 in ?? ()
  12   LWP 5652 "godot.x11.opt.t" 0x00007ffff5f77c60 in ?? ()
  13   LWP 5654 "godot.x11.opt.t" 0x00007ffff5f766d6 in ?? ()
  14   LWP 5655 "godot.x11.opt.t" 0x00007ffff5f77c60 in ?? ()
```

**Comment by capnm** [comment]
A reproducible crash with an exported model
[glTF-export-bug-crash.zip](https://github.com/godotengine/godot/files/2294635/glTF-export-bug-nodes-parenting.zip)

![gltf-anim1](https://user-images.githubusercontent.com/4047289/44225051-9d383500-a18c-11e8-8061-4900ee0d0fc8.gif)


glTF Validator:
```
{
	"resource": "glTF-export-bug-nodes-parenting.gltf",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "ACCESSOR_INDEX_TRIANGLE_DEGENERATE",
	"severity": 2,
	"message": "Indices accessor contains 7 degenerate triangles.",
	"source": "glTF Validator",
	"startLineNumber": 101,
	"startColumn": 9,
	"endLineNumber": 112,
	"endColumn": 10
}
```
```
total buffers: 1
total buffer views: 366
total accessors: 366
total images: 4
total materials: 8
on mesh: 0
accessor offset0 view offset: 49344 total buffer len: 1926440 view len 266220
accessor offset0 view offset: 315564 total buffer len: 1926440 view len 266220
accessor offset0 view offset: 581784 total buffer len: 1926440 view len 177480
accessor offset0 view offset: 759264 total buffer len: 1926440 view len 354960
accessor offset0 view offset: 1114224 total buffer len: 1926440 view len 177480
accessor offset0 view offset: 1291704 total buffer len: 1926440 view len 354960
accessor offset0 view offset: 0 total buffer len: 1926440 view len 49344
ERROR: deindex: Index E->get()=29626 out of size (varr.size()=22185)
   At: scene/resources/surface_tool.cpp:474.
on mesh: 1
accessor offset0 view offset: 1664580 total buffer len: 1926440 view len 21336
accessor offset0 view offset: 1685916 total buffer len: 1926440 view len 21336
accessor offset0 view offset: 1707252 total buffer len: 1926440 view len 28448
accessor offset0 view offset: 1735700 total buffer len: 1926440 view len 14224
accessor offset0 view offset: 1749924 total buffer len: 1926440 view len 14224
accessor offset0 view offset: 1764148 total buffer len: 1926440 view len 28448
accessor offset0 view offset: 1646664 total buffer len: 1926440 view len 17916
has targets!
accessor offset0 view offset: 1835268 total buffer len: 1926440 view len 21336
accessor offset0 view offset: 1856604 total buffer len: 1926440 view len 21336
accessor offset0 view offset: 1877940 total buffer len: 1926440 view len 21336
accessor offset0 view offset: 1899276 total buffer len: 1926440 view len 21336
accessor offset0 view offset: 1920612 total buffer len: 1926440 view len 21336
ERROR: _decode_buffer_view: Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
   At: editor/import/editor_scene_importer_gltf.cpp:510.
accessor offset0 view offset: 1941948 total buffer len: 1926440 view len 21336
ERROR: _decode_buffer_view: Condition ' (int)(offset + buffer_end) > buffer.size() ' is true. returned: ERR_PARSE_ERROR
   At: editor/import/editor_scene_importer_gltf.cpp:510.

Thread 1 "godot.x11.opt.t" received signal SIGSEGV, Segmentation fault.
EditorSceneImporterGLTF::_parse_meshes () at editor/import/editor_scene_importer_gltf.cpp:1046
1046									w4[l * 4 + 0] = r3[l].x;


(gdb) l
1041								PoolVector<Vector3>::Read r3 = tangents_v3.read();
1042								PoolVector<float>::Read r4 = src_tangents.read();
1043	
1044								for (int l = 0; l < size4 / 4; l++) {
1045	
1046									w4[l * 4 + 0] = r3[l].x;
1047									w4[l * 4 + 1] = r3[l].y;
1048									w4[l * 4 + 2] = r3[l].z;
1049									w4[l * 4 + 3] = r4[l * 4 + 3]; //copy flip value
1050			


(gdb) bt
#0  EditorSceneImporterGLTF::_parse_meshes () at editor/import/editor_scene_importer_gltf.cpp:1046
#1  0x00005555563781ea in EditorSceneImporterGLTF::import_scene ()
    at editor/import/editor_scene_importer_gltf.cpp:2173
#2  0x00005555563962c7 in ResourceImporterScene::import ()
    at editor/import/resource_importer_scene.cpp:1238
#3  0x0000555556264fde in EditorFileSystem::_reimport_file () at editor/editor_file_system.cpp:1527
#4  0x000055555626be3a in EditorFileSystem::reimport_files () at editor/editor_file_system.cpp:1681
#5  0x000055555626d628 in EditorFileSystem::_update_scan_actions ()
    at editor/editor_file_system.cpp:547
#6  0x000055555626e2a8 in EditorFileSystem::_notification () at editor/editor_file_system.cpp:1065
#7  0x00005555577477d4 in Object::notification () at core/object.cpp:978
#8  0x00005555568b4308 in SceneTree::_notify_group_pause () at scene/main/scene_tree.cpp:957
#9  0x00005555568b6ee4 in SceneTree::idle () at scene/main/scene_tree.cpp:510
#10 0x0000555555780004 in Main::iteration () at main/main.cpp:1800
#11 0x0000555555777aa1 in OS_X11::run () at platform/x11/os_x11.cpp:2639
#12 0x000055555576a06c in main () at platform/x11/godot_x11.cpp:55


```

**Comment by reduz** [comment]
I can't seem to reproduce this, is there a model you are using that makes Godot crash that I can test?
