### ISSUE TITLE
New Tileset editor sometimes crashes Godot when clicking "Open in editor" from a tilemap

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#20887]
**Godot version:**
Godot 3.1 b293dd3

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Create a tilemap, and create a new tileset. Add the tileset to the tilemap, and click the "Open in editor" button for the tileset. Sometimes it will open, sometimes it will crash Godot.

**Comment by guilhermefelipecgs** [comment]
Probably the same error #20501. Do you have any log?

**Comment by CowThing** [comment]
I don't have a log for it, but I think it might be related. I do sometimes crash when opening a shder with open in editor as well.

**Comment by capnm** [comment]
73cf0fd30524a6acc4400ef069210d90eaba29a2
Happens randomly after pressing the button, no matter which editor.
I get identical backtraces, this is from shader editor:

```
Thread 1 "godot" received signal SIGSEGV, Segmentation fault.
BaseButton::_unpress_group () at scene/gui/base_button.cpp:47
47		for (Set<BaseButton *>::Element *E = button_group->buttons.front(); E; E = E->next()) {
(gdb) l
42	
43		if (toggle_mode) {
44			status.pressed = true;
45		}
46	
47		for (Set<BaseButton *>::Element *E = button_group->buttons.front(); E; E = E->next()) {
48			if (E->get() == this)
49				continue;
50	
51			E->get()->set_pressed(false);
(gdb) bt
#0  BaseButton::_unpress_group () at scene/gui/base_button.cpp:47
#1  0x0000555556997199 in BaseButton::_gui_input () at scene/gui/base_button.cpp:155
#2  0x00005555561eac76 in MethodBind1<Ref<InputEvent> >::call () at core/method_bind.gen.inc:729
#3  0x000055555774122b in Object::call_multilevel () at core/object.cpp:752
#4  0x000055555773f606 in Object::call_multilevel () at core/object.cpp:858
#5  0x0000555556872363 in Viewport::_gui_call_input () at scene/main/viewport.cpp:1439
#6  0x000055555687422c in Viewport::_gui_input_event () at scene/main/viewport.cpp:1785
#7  0x00005555568760b0 in Viewport::input () at scene/main/viewport.cpp:2477
#8  0x00005555568762b4 in Viewport::_vp_input () at scene/main/viewport.cpp:1221
#9  0x0000555555b148c7 in MethodBind1<Ref<InputEvent> const&>::call () at core/method_bind.gen.inc:729
#10 0x000055555774049c in Object::call () at core/object.cpp:918
#11 0x000055555773f56e in Object::call () at core/object.cpp:842
#12 0x00005555568a99d3 in SceneTree::call_group_flags () at scene/main/scene_tree.cpp:262
#13 0x00005555568ac9e5 in SceneTree::input_event () at scene/main/scene_tree.cpp:418
#14 0x00005555557961ad in InputDefault::_parse_input_event_impl () at main/input_default.cpp:417
#15 0x0000555555775dac in OS_X11::process_xevents () at platform/x11/os_x11.cpp:1928
#16 0x0000555555777440 in OS_X11::run () at platform/x11/os_x11.cpp:2635
#17 0x0000555555769a1c in main () at platform/x11/godot_x11.cpp:55

```

**Comment by avencherus** [comment]
@guilhermefelipecgs 

I ran into something that fits this description this afternoon.  Just playing around with Tilesets in 3.1.

I can't be sure, because I haven't had time to go back and test it, but it might have something to do with updating the source PNG of the whole set.  This is at least the last thing I remember doing, but I hadn't saved the scene and re-opened it after immediately after creation.  Currently any scene I make with TileMaps in 3.1 will crash with this error log:

![tile crash error](https://user-images.githubusercontent.com/13004169/44036016-76a20abc-9f19-11e8-9520-d52a1550fd3b.png)

**Comment by mateusfccp** [comment]
It's still happening to me, on last build from git. Opened a new issue: https://github.com/godotengine/godot/issues/23672
