### ISSUE TITLE
Editor crashes with SIGFPE when downloading from the asset library

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#21200]
**Godot version:**
3.1.dev.custom_build.5d09877

commit 5d09877da8003740928502aead0b46505495721f
Date:   Sun Aug 19 14:17:55 2018 +0200

**OS/device including version:**
Debian GNU/Linux 9 (Stretch)

**Issue description:**
Editor consistently crashes when I try to download the Python plugin from the asset library.

**Backtrace:**

ERROR: _EDITOR_GET: Condition ' !EditorSettings::get_singleton()->has_setting(p_setting) ' is true. returned: Variant()
   At: editor/editor_settings.cpp:1061.
handle_crash: Program crashed with signal 8
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7f9f0beb6060] (??:0)
[2] String::humanize_size(unsigned long) (??:0)
[3] EditorAssetLibraryItemDownload::_notification(int) (??:0)
[4] EditorAssetLibraryItemDownload::_notificationv(int, bool) (??:0)
[5] Object::notification(int, bool) (??:0)
[6] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[7] SceneTree::idle(float) (??:0)
[8] Main::iteration() (??:0)
[9] OS_X11::run() (??:0)
[10] /home/simon/scratch/godot-git/bin/godot.x11.tools.64(main+0xb7) [0x55658f39d4b7] (??:0)
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f9f0bea32e1] (??:0)
[12] /home/simon/scratch/godot-git/bin/godot.x11.tools.64(_start+0x2a) [0x55658f39d2fa] (??:0)
-- END OF BACKTRACE --

**Comment by akien-mga** [comment]
I can reproduce it on Mageia 6 too:
```
(gdb) bt
#0  0x00000000040a3e46 in String::humanize_size (p_size=18446744073709551615) at core/ustring.cpp:3175
#1  0x00000000021d84de in EditorAssetLibraryItemDownload::_notification (this=0x170c6ec0, p_what=17) at editor/plugins/asset_library_editor_plugin.cpp:424
#2  0x00000000021e9ed3 in EditorAssetLibraryItemDownload::_notificationv (this=0x170c6ec0, p_notification=17, p_reversed=false) at editor/plugins/asset_library_editor_plugin.h:136
#3  0x0000000003fcd2c2 in Object::notification (this=0x170c6ec0, p_notification=17, p_reversed=false) at core/object.cpp:978
#4  0x0000000002792b75 in SceneTree::_notify_group_pause (this=0x6d4aa70, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:957
#5  0x000000000278fe61 in SceneTree::idle (this=0x6d4aa70, p_time=0.0166666675) at scene/main/scene_tree.cpp:510
#6  0x0000000000f445f4 in Main::iteration () at main/main.cpp:1800
#7  0x0000000000f1594b in OS_X11::run (this=0x7fffffffd2a0) at platform/x11/os_x11.cpp:2652
#8  0x0000000000f0860b in main (argc=4, argv=0x7fffffffda08) at platform/x11/godot_x11.cpp:55
(gdb) bt full
#0  0x00000000040a3e46 in String::humanize_size (p_size=18446744073709551615) at core/ustring.cpp:3175
        _div = 0
        prefix = {0x4f9f4c4 " Bytes", 0x4f9f4cb " KB", 0x4f9f4cf " MB", 0x4f9f4d3 " GB", 0x4f9f4d7 "TB", 0x4f9f4da " PB", 0x4f9f4de "HB", 0x4f9ebe6 ""}
        prefix_idx = 7
        digits = -13840
        divisor = 2.0604839283423955e-316
#1  0x00000000021d84de in EditorAssetLibraryItemDownload::_notification (this=0x170c6ec0, p_what=17) at editor/plugins/asset_library_editor_plugin.cpp:424
        cstatus = 7
#2  0x00000000021e9ed3 in EditorAssetLibraryItemDownload::_notificationv (this=0x170c6ec0, p_notification=17, p_reversed=false) at editor/plugins/asset_library_editor_plugin.h:136
No locals.
#3  0x0000000003fcd2c2 in Object::notification (this=0x170c6ec0, p_notification=17, p_reversed=false) at core/object.cpp:978
No locals.
#4  0x0000000002792b75 in SceneTree::_notify_group_pause (this=0x6d4aa70, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:957
        n = 0x170c6ec0
        i = 4
        E = 0xc051ab0
        g = @0xc051ae8: {nodes = {_cowdata = 0xc051930, write = {_parent = 0xc051930}}, changed = false}
        nodes_copy = {_cowdata = 0x16f18d30, write = {_parent = 0x16f18d30}}
        node_count = 14
        nodes = 0x6587b60
#5  0x000000000278fe61 in SceneTree::idle (this=0x6d4aa70, p_time=0.0166666675) at scene/main/scene_tree.cpp:510
        win_size = {{x = 3.90247518e-25, width = 3.90247518e-25}, {y = 0, height = 0}}
#6  0x0000000000f445f4 in Main::iteration () at main/main.cpp:1800
        ticks = 32486921
        ticks_elapsed = 16739
        physics_fps = 60
        frame_slice = 0.0166666675
        time_scale = 1
        advance = {idle_step = 0.0166666675, physics_steps = 1}
        step = 0.01666666753590107
---Type <return> to continue, or q <return> to quit---
        scaled_step = 0.01666666753590107
        physics_process_ticks = 84
        idle_process_ticks = 0
        max_physics_steps = 8
        exit = false
        idle_begin = 32487007
        frame_time = 8666
        target_fps = 0
        __FUNCTION__ = "iteration"
#7  0x0000000000f1594b in OS_X11::run (this=0x7fffffffd2a0) at platform/x11/os_x11.cpp:2652
No locals.
#8  0x0000000000f0860b in main (argc=4, argv=0x7fffffffda08) at platform/x11/godot_x11.cpp:55
        os = {<OS_Unix> = {<OS> = {_vptr.OS = 0x43a3600 <vtable for OS_X11+16>, static singleton = 0x7fffffffd2a0, _execpath = {_cowdata = {_ptr = 0x5904710 L"/usr/local/bin/godot-git"}}, 
              _cmdline = {_data = 0x59047b0}, _keep_screen_on = true, low_processor_usage_mode = true, low_processor_usage_mode_sleep_usec = 8000, _verbose_stdout = false, 
              _local_clipboard = {_cowdata = {_ptr = 0x0}}, _msec_splash = 0, _no_window = false, _exit_code = 0, _orientation = 0, _allow_hidpi = true, _allow_layered = false, 
              _use_vsync = true, last_error = 0x16cee8e0 "Attempt to delete an object in the middle of a signal emission from it", _stack_bottom = 0x7fffffffd0a0, _logger = 0x580cf70, 
              restart_on_exit = false, restart_commandline = {_data = 0x0}, _render_thread_mode = OS::RENDER_THREAD_SAFE, 
              static switch_vsync_function = 0x3658642 <VisualServerWrapMT::set_use_vsync_callback(bool)>}, ticks_start = 1534748583331623, stdin_buf = {_cowdata = {_ptr = 0x0}}}, 
          wm_delete = 362, xdnd_enter = 443, xdnd_position = 444, xdnd_status = 445, xdnd_action_copy = 454, xdnd_drop = 447, xdnd_finished = 448, xdnd_selection = 451, requested = 0, 
          xdnd_version = 0, context_gl = 0x59c7380, visual_server = 0x5c62160, current_videomode = {width = 1920, height = 1011, fullscreen = false, resizable = true, 
            borderless_window = false, maximized = false, always_on_top = false, use_vsync = true, layered_splash = false, layered = false}, args = {_data = 0x5906c00}, 
          x11_window = 102760450, xdnd_source_window = 140737488345608, main_loop = 0x6d4aa70, x11_display = 0x5907d10, xmbstring = 0x0, xmblen = -10904, last_timestamp = 96980941, 
          last_keyrelease_time = 0, xic = 0x5ce9340, xim = 0x59294f0, xim_style = 1032, im_active = false, im_position = {{x = 0, width = 0}, {y = 1, height = 1}}, last_mouse_pos = {{
              x = 1109, width = 1109}, {y = 741, height = 741}}, last_mouse_pos_valid = true, last_click_pos = {{x = 1109, width = 1109}, {y = 741, height = 741}}, last_click_ms = 30979, 
          last_button_state = 1, touch = {opcode = 131, devices = {_cowdata = 0x580c650, write = {_parent = 0x580c650}}, event_mask = {deviceid = -11120, mask_len = 32767, mask = 0x40e8e78
     <Memory::free_static(void*, bool)+176> "\353\fH\213E\370H\211\307\350\312\323\341\374\311\303UH\211\345H\307\300\377\377\377\377]ÐUH\211\345H\213\005?~l\001]ÐUH\211\345H\213\005\071~l\001]ÐUH\211\345H\211}\370H\213E\370", <incomplete sequence \307>}, state = {_data = {_root = 0x0, _nil = 0x57b0d00 <_GlobalNilClass::_nil>, size_cache = 0}}, mouse_pos_to_filter = {{
                x = 1e+10, width = 1e+10}, {y = 1e+10, height = 1e+10}}}, mouse_mode = OS::MOUSE_MODE_VISIBLE, center = {{x = 0, width = 0}, {y = 0, height = 0}}, 
          ip_unix = 0x1007fffffffd548, force_quit = false, minimized = false, window_has_focus = true, do_mouse_warp = false, cursor_theme = 0x5cc5d70 "breeze_cursors", cursor_size = 22, 
          img = {0x5cc6050, 0x5cba020, 0x5cbb050, 0x5cbc080, 0x5cbd0b0, 0x5cbe0e0, 0x5cbf110, 0x5cc8200, 0x5cc0140, 0x5cc9230, 0x5cca260, 0x5ccb290, 0x5ccc2c0, 0x5ccd2f0, 0x5cce320, 
---Type <return> to continue, or q <return> to quit---
            0x5ccf350, 0x5cd0380}, cursors = {102760455, 102760459, 102760463, 102760467, 102760471, 102760475, 102760479, 102760483, 102760487, 102760491, 102760495, 102760499, 
            102760503, 102760507, 102760511, 102760515, 102760519}, null_cursor = 102760522, current_cursor = OS::CURSOR_ARROW, input = 0x65d8320, joypad = 0x664a740, 
          driver_alsa = {<AudioDriver> = {_vptr.AudioDriver = 0x4494738 <vtable for AudioDriverALSA+16>, static singleton = 0x7fffffffd6b0, _last_mix_time = 0, _mix_amount = 0, 
              prof_ticks = 140737488345608, prof_time = 0, input_buffer = {_cowdata = 0x580cf40, write = {_parent = 0x580cf40}}, input_position = 132, input_size = 0, 
              static DEFAULT_MIX_RATE = 44100, static DEFAULT_OUTPUT_LATENCY = 15}, thread = 0x0, mutex = 0x0, pcm_handle = 0x0, device_name = {_cowdata = {_ptr = 0x580cfc0 L"Default"}}, 
            new_device = {_cowdata = {_ptr = 0x580d000 L"Default"}}, samples_in = {_cowdata = 0x580cf00, write = {_parent = 0x580cf00}}, samples_out = {_cowdata = 0x580ce90, write = {
                _parent = 0x580ce90}}, mix_rate = 92327408, speaker_mode = AudioDriver::SPEAKER_MODE_STEREO, buffer_frames = 92327408, buffer_size = 91950312, period_size = 92327408, 
            channels = 0, active = false, thread_exited = false, exit_thread = false}, driver_alsamidi = {<MIDIDriver> = {_vptr.MIDIDriver = 0x4495288 <vtable for MIDIDriverALSAMidi+16>, 
              static singleton = 0x7fffffffd680}, thread = 0x5ce8c10, mutex = 0x5cb20b0, connected_inputs = {_cowdata = 0x580c670, write = {_parent = 0x580c670}}, exit_thread = false}, 
          driver_pulseaudio = {<AudioDriver> = {_vptr.AudioDriver = 0x4494e90 <vtable for AudioDriverPulseAudio+16>, static singleton = 0x7fffffffd6b0, _last_mix_time = 32536790, 
              _mix_amount = 1421824, prof_ticks = 32540044, prof_time = 804, input_buffer = {_cowdata = 0x580d030, write = {_parent = 0x580d030}}, input_position = 0, input_size = 0, 
              static DEFAULT_MIX_RATE = 44100, static DEFAULT_OUTPUT_LATENCY = 15}, thread = 0x5cb5a40, mutex = 0x5cb6050, pa_ml = 0x5ca2e10, pa_ctx = 0x5ca2f10, pa_str = 0x5cb4b20, 
            pa_rec_str = 0x0, pa_map = {channels = 2 '\002', map = {PA_CHANNEL_POSITION_FRONT_LEFT, PA_CHANNEL_POSITION_FRONT_RIGHT, PA_CHANNEL_POSITION_MONO <repeats 30 times>}}, 
            pa_rec_map = {channels = 0 '\000', map = {PA_CHANNEL_POSITION_MONO, PA_CHANNEL_POSITION_MONO, -1082130432, PA_CHANNEL_POSITION_MONO, 91951228, PA_CHANNEL_POSITION_MONO, 
                -10225, 32767, 64, PA_CHANNEL_POSITION_FRONT_RIGHT, 91951252, PA_CHANNEL_POSITION_MONO, PA_CHANNEL_POSITION_FRONT_RIGHT, PA_CHANNEL_POSITION_FRONT_LEFT, 91951252, 
                PA_CHANNEL_POSITION_MONO, PA_CHANNEL_POSITION_MONO, PA_CHANNEL_POSITION_MONO, 91951252, PA_CHANNEL_POSITION_MONO, PA_CHANNEL_POSITION_MONO, 
                PA_CHANNEL_POSITION_FRONT_RIGHT, 91951240, PA_CHANNEL_POSITION_MONO, 119, PA_CHANNEL_POSITION_FRONT_LEFT, 91951240, PA_CHANNEL_POSITION_MONO, 91915072, 
                PA_CHANNEL_POSITION_MONO, 91951240, PA_CHANNEL_POSITION_MONO}}, device_name = {_cowdata = {_ptr = 0x580d110 L"Default"}}, new_device = {_cowdata = {
                _ptr = 0x580d150 L"Default"}}, default_device = {_cowdata = {_ptr = 0x5cb48e0 L"alsa_output.pci-0000_00_1b.0.analog-stereo"}}, capture_device_name = {_cowdata = {
                _ptr = 0x0}}, capture_new_device = {_cowdata = {_ptr = 0x0}}, capture_default_device = {_cowdata = {_ptr = 0x5cb47c0 L"alsa_input.pci-0000_00_1b.0.analog-stereo"}}, 
            samples_in = {_cowdata = 0x580d050, write = {_parent = 0x580d050}}, samples_out = {_cowdata = 0x580d070, write = {_parent = 0x580d070}}, mix_rate = 44100, buffer_frames = 512, 
            input_buffer_frames = 0, pa_buffer_size = 1024, channels = 2, pa_ready = 1, pa_status = 1, pa_devices = {_p = 0x580cee0}, pa_rec_devices = {_p = 0x580d0c0}, active = true, 
            thread_exited = false, exit_thread = false, latency = 0}, net_wm_icon = 91864096, power_manager = 0x6648f60, layered_window = false, crash_handler = {disabled = false}, 
          video_driver_index = 0, audio_driver_index = 65535, capture_idle = 1, maximized = true, xrr_get_monitors = 0x7ffff77cb420 <XRRGetMonitors>, 
          xrr_free_monitors = 0x7ffff77cb990 <XRRFreeMonitors>, xrandr_handle = 0x7ffff7fb8000, xrandr_ext_ok = 1}
        cwd = 0x580e090 "/home/akien"
        err = OK
```

CC @bojidar-bg @Calinou

**Comment by swenner** [comment]
It no longer crashes but shows 100% progress at all time. Thanks for the quick fix!
