### ISSUE TITLE
Errors after add LightOccluder as child of Animation Player ERROR: get: Condition ' !p_rid.is_valid() ' is true. returned: __null 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21286]
**Godot version:**
3.1 faa49c1

**OS/device including version:**
Windows 10 Intel HD 4600, Linux Mint 19 Mate HD 3000

**Issue description:**
When I create child of anim Node(AnimationPlayer) from 2D Lighting Demo Project, a lot of this errors is shown in Output:
**ERROR: get: Condition ' !p_rid.is_valid() ' is true. returned: __null
   At: core/rid.h:154**

**Steps to reproduce:**
1. Download 2D Lightning Demo Project
2. Add LightOccluder2D as child of AnimationPlayer (e.g /root/base/blue_light/anim)
3. Look at the Output

https://streamable.com/doj02 (colors are strange)

If you wanna disable this errors, delete LightOccluder2D

**Minimal reproduction project:**
[light.zip](https://github.com/godotengine/godot/files/2309465/light.zip)

**Comment by qarmin** [comment]
Errors still exists in 3.1 3916a5352250e004504cf97d1eb9df5305c50bbc (master)

**Comment by akien-mga** [comment]
Confirmed in the current master branch (ed22a4c45).

**Comment by akien-mga** [comment]
That's because the occluder polygon hasn't been defined yet. There's a warning in the scene tree dock, but it doesn't seem to prevent the rendering backend from trying to process the occluders.

Backtrace with GLES2:
```
(gdb) bt
#0  RID_Owner<RasterizerStorageGLES2::CanvasOccluder>::get (this=0x56a8a98, p_rid=...) at ./core/rid.h:150
#1  0x000000000200719c in RasterizerCanvasGLES2::canvas_light_shadow_buffer_update (this=0x58414d0, p_buffer=..., p_light_xform=..., p_light_mask=1, p_near=1.44815469, p_far=1592.97009, p_occluders=0x68ed260, 
    p_xform_cache=0x688e1d4) at drivers/gles2/rasterizer_canvas_gles2.cpp:1897
#2  0x00000000035feab7 in VisualServerViewport::_draw_viewport (this=0x5532aa0, p_viewport=0x6694010, p_eye=ARVRInterface::EYE_MONO) at servers/visual/visual_server_viewport.cpp:205
#3  0x00000000035ff455 in VisualServerViewport::draw_viewports (this=0x5532aa0) at servers/visual/visual_server_viewport.cpp:343
#4  0x00000000035d307f in VisualServerRaster::draw (this=0x551b130, p_swap_buffers=true, frame_step=0.13333334028720856) at servers/visual/visual_server_raster.cpp:108
#5  0x000000000360576e in VisualServerWrapMT::draw (this=0x5888270, p_swap_buffers=true, frame_step=0.13333334028720856) at servers/visual/visual_server_wrap_mt.cpp:102
#6  0x0000000001464f7c in Main::iteration () at main/main.cpp:2022
#7  0x00000000014352cd in OS_X11::run (this=0x7fffffffcf70) at platform/x11/os_x11.cpp:3262
#8  0x000000000142578c in main (argc=3, argv=0x7fffffffd738) at platform/x11/godot_x11.cpp:56
```

With GLES3:
```
(gdb) bt
#0  RID_Owner<RasterizerStorageGLES3::CanvasOccluder>::get (this=0x568e748, p_rid=...) at ./core/rid.h:150
#1  0x0000000001ffae94 in RasterizerCanvasGLES3::canvas_light_shadow_buffer_update (this=0x56c74d0, p_buffer=..., p_light_xform=..., p_light_mask=1, p_near=1.44815469, p_far=1592.97009, p_occluders=0x67e6ff0, 
    p_xform_cache=0x6782784) at drivers/gles3/rasterizer_canvas_gles3.cpp:1892
#2  0x00000000035feab7 in VisualServerViewport::_draw_viewport (this=0x552f040, p_viewport=0x65853b0, p_eye=ARVRInterface::EYE_MONO) at servers/visual/visual_server_viewport.cpp:205
#3  0x00000000035ff455 in VisualServerViewport::draw_viewports (this=0x552f040) at servers/visual/visual_server_viewport.cpp:343
#4  0x00000000035d307f in VisualServerRaster::draw (this=0x551afd0, p_swap_buffers=true, frame_step=0.12849299609661102) at servers/visual/visual_server_raster.cpp:108
#5  0x000000000360576e in VisualServerWrapMT::draw (this=0x570f6d0, p_swap_buffers=true, frame_step=0.12849299609661102) at servers/visual/visual_server_wrap_mt.cpp:102
#6  0x0000000001464f7c in Main::iteration () at main/main.cpp:2022
#7  0x00000000014352cd in OS_X11::run (this=0x7fffffffcf90) at platform/x11/os_x11.cpp:3262
#8  0x000000000142578c in main (argc=1, argv=0x7fffffffd758) at platform/x11/godot_x11.cpp:56
```
