### ISSUE TITLE
Crash on missing gdscript, error on missing shader

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#21505]
**Godot version:**

current tip
0565adb20ff01a758c5ae8e4534a2cb7f07952df

**OS/device including version:**

Linux

**What happened, and what was expected:**
Crash or error – I expect the missing dependencies dialog.

**Steps to reproduce:**
In the attached project:

close the editor, **mv spectrum/Spectrum.gd /tmp/**
open editor

```

ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gdscript.cpp:799.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: modules/gdscript/gdscript.cpp:2126.
ERROR: _unref: Condition ' !_p ' is true.
   At: core/dictionary.cpp:171.
ERROR: _load: Failed loading resource: res://spectrum/Spectrum.gd
   At: core/io/resource_loader.cpp:190.
double free or corruption (!prev)

Thread 1 "godot3" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff506d801 in __GI_abort () at abort.c:79
#2  0x00007ffff50b6897 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff51e3b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff50bd90a in malloc_printerr (
    str=str@entry=0x7ffff51e5890 "double free or corruption (!prev)") at malloc.c:5350
#4  0x00007ffff50c4e84 in _int_free (have_lock=0, p=0x55555db12280, av=0x7ffff5418c40 <main_arena>)
    at malloc.c:4281
#5  __GI___libc_free (mem=0x55555db12290) at malloc.c:3124
#6  0x00007ffff50abf42 in __fopen_internal (is32=1, mode=0x5555584d5846 "rb", 
    filename=0x55555e69e300 "/data4/intranet/capnm-godot3-bridge/godot-prj/missing-script-shader-test/spectrum/Spectrum.gd") at iofopen.c:82
#7  _IO_new_fopen (
    filename=0x55555e69e300 "/data4/intranet/capnm-godot3-bridge/godot-prj/missing-script-shader-test/spectrum/Spectrum.gd", mode=0x5555584d5846 "rb") at iofopen.c:89
#8  0x0000555555f0fb1a in FileAccessUnix::_open () at drivers/unix/file_access_unix.cpp:111
#9  0x000055555785d4fe in FileAccess::open () at core/os/file_access.cpp:112
#10 0x0000555555833d64 in GDScript::load_source_code () at modules/gdscript/gdscript.cpp:796
#11 0x000055555583ce3e in ResourceFormatLoaderGDScript::load ()
    at modules/gdscript/gdscript.cpp:2122
#12 0x000055555795457b in ResourceLoader::_load () at core/io/resource_loader.cpp:177
#13 0x00005555579548a0 in ResourceLoader::load () at core/io/resource_loader.cpp:219
#14 0x00005555571672bd in ResourceInteractiveLoaderText::_parse_ext_resource ()
    at scene/resources/scene_format_text.cpp:171
#15 0x00005555576e1ab2 in VariantParser::parse_value () at core/variant_parser.cpp:825
#16 0x00005555576e6784 in VariantParser::parse_tag_assign_eof () at core/variant_parser.cpp:1548
#17 0x0000555557167f73 in ResourceInteractiveLoaderText::_parse_node_tag ()
    at scene/resources/scene_format_text.cpp:273
#18 0x000055555716fac6 in ResourceInteractiveLoaderText::poll ()
    at scene/resources/scene_format_text.cpp:624
#19 0x0000555557954d02 in ResourceFormatLoader::load () at core/io/resource_loader.cpp:142
#20 0x000055555795457b in ResourceLoader::_load () at core/io/resource_loader.cpp:177
#21 0x00005555579548a0 in ResourceLoader::load () at core/io/resource_loader.cpp:219
#22 0x000055555615b72b in EditorNode::load_scene () at editor/editor_node.cpp:2817
#23 0x000055555615c6b0 in EditorNode::_sources_changed () at editor/editor_node.cpp:549
#24 0x0000555555978e94 in MethodBind1<bool>::call () at core/method_bind.gen.inc:729
#25 0x00005555577ad7dc in Object::call () at core/object.cpp:968
#26 0x00005555577b9abb in Object::emit_signal () at core/object.cpp:1254
#27 0x00005555577bab05 in Object::emit_signal () at core/object.cpp:1307
#28 0x000055555629d19e in EditorFileSystem::_notification () at editor/editor_file_system.cpp:1074
#29 0x00005555577aaae4 in Object::notification () at core/object.cpp:978
#30 0x00005555568f4328 in SceneTree::_notify_group_pause () at scene/main/scene_tree.cpp:957
#31 0x00005555568f6f04 in SceneTree::idle () at scene/main/scene_tree.cpp:510
#32 0x00005555557853b4 in Main::iteration () at main/main.cpp:1800
#33 0x000055555577c791 in OS_X11::run () at platform/x11/os_x11.cpp:2785
#34 0x000055555576e20c in main () at platform/x11/godot_x11.cpp:55

```
close editor **mv spectrum/Spectrum.shader /tmp/**
open editor

```


ERROR: get_file_as_array: Condition ' !f ' is true. returned: Vector<uint8_t>()
   At: core/os/file_access.cpp:537.
ERROR: _get_modified_time: Failed to get modified time for: res://spectrum/Spectrum.shader
   At: drivers/unix/file_access_unix.cpp:291.
0 
SHADER ERROR: (null): Expected 'shader_type' at the beginning of shader.
   At: :1.
ERROR: _update_shader: Condition ' err != OK ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1912.

```

**Minimal reproduction project:**

[missing-script-shader-test.zip](https://github.com/godotengine/godot/files/2325655/missing-script-shader-test.zip)

**Comment by capnm** [comment]
Tested with current git tip.

* close the editor
* mv spectrum/Spectrum.gd /tmp/
* open editor

> Doesn't crash for me with a recent master build, it opens the missing dependencies dialog as expected. 

Yes :+1: 

----

* close editor
* mv spectrum/Spectrum.shader /tmp/
* open editor

still prints weird errors: 
```
ERROR: get_file_as_array: Condition ' !f ' is true. returned: Vector<uint8_t>()
   At: core/os/file_access.cpp:560.
ERROR: _get_modified_time: Failed to get modified time for: res://spectrum/Spectrum.shader
   At: drivers/unix/file_access_unix.cpp:292.
```
