### ISSUE TITLE
Crash when moving/rotating an Area containing an empty ConvexPolygonShape

### ISSUE THREAD

**Issue by Windfisch** [godotengine/godot#21532]
**Godot version:** 3.0.6 unofficial custom build 642b26eb5976ccb34756fb7ba38e1a247aad5ae8 (see https://github.com/Windfisch/godot/tree/3.0-backport-clean).

Please note that this is in fact the vanilla 3.0 branch as of d3c4f91c9c644685a72e5704f0bcb85a8dc534c3, with just the INSTANCE_ID shader rename backported.

**OS/device including version:** Windows 10 ver1803, Nvidia GTX 1080 Ti

**Issue description:**
When an Area (or its parent node) gets its transform updated "enough", and if said Area contains a CollisionShape which contains a ConvexPolygonShape that has an array of zero points, then Godot crashes with the following backtrace:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] operator* (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\linearmath\btvector3.h:788)
[1] operator* (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\linearmath\btvector3.h:788)
[2] convexHullSupport (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\bulletcollision\collisionshapes\btconvexshape.cpp:125)
[3] btConvexShape::localGetSupportVertexWithoutMarginNonVirtual (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\bulletcollision\collisionshapes\btconvexshape.cpp:282)
[4] btGjkPairDetector::getClosestPointsNonVirtual (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\bulletcollision\narrowphasecollision\btgjkpairdetector.cpp:150)
[5] btGjkPairDetector::getClosestPoints (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\bulletcollision\narrowphasecollision\btgjkpairdetector.cpp:84)
[6] SpaceBullet::check_ghost_overlaps (c:\users\florian\desktop\godot-build\godot\modules\bullet\space_bullet.cpp:694)
[7] onBulletTickCallback (c:\users\florian\desktop\godot-build\godot\modules\bullet\space_bullet.cpp:544)
[8] btDiscreteDynamicsWorld::internalSingleStepSimulation (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:519)
[9] btDiscreteDynamicsWorld::stepSimulation (c:\users\florian\desktop\godot-build\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:456)
[10] SpaceBullet::step (c:\users\florian\desktop\godot-build\godot\modules\bullet\space_bullet.cpp:359)
[11] BulletPhysicsServer::step (c:\users\florian\desktop\godot-build\godot\modules\bullet\bullet_physics_server.cpp:1334)
[12] Main::iteration (c:\users\florian\desktop\godot-build\godot\main\main.cpp:1793)
[13] OS_Windows::run (c:\users\florian\desktop\godot-build\godot\platform\windows\os_windows.cpp:2364)
[14] widechar_main (c:\users\florian\desktop\godot-build\godot\platform\windows\godot_win.cpp:150)
[15] _main (c:\users\florian\desktop\godot-build\godot\platform\windows\godot_win.cpp:172)
[16] main (c:\users\florian\desktop\godot-build\godot\platform\windows\godot_win.cpp:184)
[17] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
[18] BaseThreadInitThunk
-- END OF BACKTRACE --
Nothing read: No such file or directory
ERROR: StreamPeerTCPWinsock::read: Server disconnected!

   At: drivers\windows\stream_peer_tcp_winsock.cpp:203
```

This does not happen if the difference between the new transform and the original transform was "small" enough (really tiny, in fact). The "original" transform means the transform at frame 0; not the transform in the previous frame.

Expected Behaviour: no crash

**Steps to reproduce:**
**Minimal reproduction project:**
Unfortunately, this happens in a huge project; I was not able yet to find a small subset that triggers the bug, and trying to build a new project that triggers this was unsuccessful, too. I'll update this if I manage to strip it.

**Comment by akien-mga** [comment]
Does it also crash if you run your project in the master branch? (test on a copy so that it does not auto-upgrade your actual 3.0 project).

**Comment by akien-mga** [comment]
That's weird, as `thirdparty/glad` should be in the include path and it's the folder that contains the mentioned header. It works exactly the same in the 3.0 branch so I'm surprised you're able to build 3.0 but not master.

**Comment by Windfisch** [comment]
I managed to build it now after re-cloning it.

Yes, the bug persists with the current master, the stacktrace seems to be the same, but for the sake of completeness:
<details>
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] operator* (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\linearmath\btvector3.h:788)
[1] operator* (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\linearmath\btvector3.h:788)
[2] convexHullSupport (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletcollision\collisionshapes\btconvexshape.cpp:125)
[3] btConvexShape::localGetSupportVertexWithoutMarginNonVirtual (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletcollision\collisionshapes\btconvexshape.cpp:282)
[4] btGjkPairDetector::getClosestPointsNonVirtual (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletcollision\narrowphasecollision\btgjkpairdetector.cpp:150)
[5] btGjkPairDetector::getClosestPoints (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletcollision\narrowphasecollision\btgjkpairdetector.cpp:84)
[6] SpaceBullet::check_ghost_overlaps (c:\users\florian\desktop\gd-master\godot\modules\bullet\space_bullet.cpp:707)
[7] onBulletTickCallback (c:\users\florian\desktop\gd-master\godot\modules\bullet\space_bullet.cpp:550)
[8] btDiscreteDynamicsWorld::internalSingleStepSimulation (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:519)
[9] btSoftRigidDynamicsWorld::internalSingleStepSimulation (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletsoftbody\btsoftrigiddynamicsworld.cpp:97)
[10] btDiscreteDynamicsWorld::stepSimulation (c:\users\florian\desktop\gd-master\godot\thirdparty\bullet\bulletdynamics\dynamics\btdiscretedynamicsworld.cpp:456)
[11] SpaceBullet::step (c:\users\florian\desktop\gd-master\godot\modules\bullet\space_bullet.cpp:363)
[12] BulletPhysicsServer::step (c:\users\florian\desktop\gd-master\godot\modules\bullet\bullet_physics_server.cpp:1561)
[13] Main::iteration (c:\users\florian\desktop\gd-master\godot\main\main.cpp:1786)
[14] OS_Windows::run (c:\users\florian\desktop\gd-master\godot\platform\windows\os_windows.cpp:2725)
[15] widechar_main (c:\users\florian\desktop\gd-master\godot\platform\windows\godot_win.cpp:150)
[16] _main (c:\users\florian\desktop\gd-master\godot\platform\windows\godot_win.cpp:172)
[17] main (c:\users\florian\desktop\gd-master\godot\platform\windows\godot_win.cpp:184)
[18] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
[19] BaseThreadInitThunk
-- END OF BACKTRACE --
Nothing read: No such file or directory
Running: C:\Users\Florian\Desktop\gd-master\godot\bin\godot.windows.tools.64.exe --path C:/Users/Florian/Documents/wsl/godot-bulletbug --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 15536 --position 448,300
ERROR: StreamPeerTCPWinsock::read: Server disconnected!

   At: drivers\windows\stream_peer_tcp_winsock.cpp:203
</details>

I'll try to reduce my project later to provide you with an example. That might turn difficult, because it's a VR project and this only happens when grabbing something with the controller ;)

**Comment by Windfisch** [comment]
I've shrunk it down to a demo project that crashes. Find the project attached:
[godot-bulletbug.zip](https://github.com/godotengine/godot/files/2332189/godot-bulletbug.zip)

It contains two Areas, one with a capsule shape, and one with both a Box shape and an empty ConvexPolygonShape (whose array of points has size zero).

Updating the transform of the World is done in CrashScript (Camera.gd) triggers the crash.

Removing or disabling either the ConvexPolygonShape or the CapsuleShape prevent it from crashing.

**Comment by akien-mga** [comment]
Thanks, I could reproduce the crash with the provided project. CC @AndreaCatania 

gdb backtrace:
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x000000000134f9f9 in operator* (v1=..., v2=...) at thirdparty/bullet/LinearMath/btVector3.h:791
791                             v1.m_floats[2] * v2.m_floats[2]);

(gdb) bt
#0  0x000000000134f9f9 in operator* (v1=..., v2=...) at thirdparty/bullet/LinearMath/btVector3.h:791
#1  0x000000000165221c in convexHullSupport (localDirOrg=..., points=0x0, numPoints=0, localScaling=...) at thirdparty/bullet/BulletCollision/CollisionShapes/btConvexShape.cpp:124
#2  0x0000000001652ea7 in btConvexShape::localGetSupportVertexWithoutMarginNonVirtual (this=0x748b110, localDir=...)
    at thirdparty/bullet/BulletCollision/CollisionShapes/btConvexShape.cpp:282
#3  0x000000000166336d in btGjkPairDetector::getClosestPointsNonVirtual (this=0x7fffffffcc40, input=..., output=..., debugDraw=0x0)
    at thirdparty/bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp:148
#4  0x0000000001662f58 in btGjkPairDetector::getClosestPoints (this=0x7fffffffcc40, input=..., output=..., debugDraw=0x0, swapResults=false)
    at thirdparty/bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp:83
#5  0x00000000013952dc in SpaceBullet::check_ghost_overlaps (this=0x6e40410) at modules/bullet/space_bullet.cpp:705
#6  0x000000000139420e in onBulletTickCallback (p_dynamicsWorld=0x6e3a590, timeStep=0.0166666675) at modules/bullet/space_bullet.cpp:549
#7  0x000000000168bd5d in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x6e3a590, timeStep=0.0166666675)
    at thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:519
#8  0x00000000016be8de in btSoftRigidDynamicsWorld::internalSingleStepSimulation (this=0x6e3a590, timeStep=0.0166666675) at thirdparty/bullet/BulletSoftBody/btSoftRigidDynamicsWorld.cpp:94
#9  0x000000000168bb25 in btDiscreteDynamicsWorld::stepSimulation (this=0x6e3a590, timeStep=0.0166666675, maxSubSteps=1, fixedTimeStep=0.0166666675)
    at thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:455
#10 0x000000000139344b in SpaceBullet::step (this=0x6e40410, p_delta_time=0.0166666675) at modules/bullet/space_bullet.cpp:362
#11 0x000000000136798a in BulletPhysicsServer::step (this=0x6ddf9d0, p_deltaTime=0.0166666675) at modules/bullet/bullet_physics_server.cpp:1560
#12 0x0000000000f63d37 in Main::iteration () at main/main.cpp:1784
#13 0x0000000000f34ed3 in OS_X11::run (this=0x7fffffffd2c0) at platform/x11/os_x11.cpp:2785
#14 0x0000000000f2678b in main (argc=1, argv=0x7fffffffda28) at platform/x11/godot_x11.cpp:55

(gdb) bt full
#0  0x000000000134f9f9 in operator* (v1=..., v2=...) at thirdparty/bullet/LinearMath/btVector3.h:791
No locals.
#1  0x000000000165221c in convexHullSupport (localDirOrg=..., points=0x0, numPoints=0, localScaling=...) at thirdparty/bullet/BulletCollision/CollisionShapes/btConvexShape.cpp:124
        vec = {m_floats = {0.48281756, 0.680521786, -0.551160276, 0}}
        maxDot = -3.40282347e+38
        ptIndex = -1
        supVec = {m_floats = {0, 0, 0, 0}}
#2  0x0000000001652ea7 in btConvexShape::localGetSupportVertexWithoutMarginNonVirtual (this=0x748b110, localDir=...)
    at thirdparty/bullet/BulletCollision/CollisionShapes/btConvexShape.cpp:282
        convexPointCloudShape = 0x748b110
        points = 0x0
        numPoints = 0
#3  0x000000000166336d in btGjkPairDetector::getClosestPointsNonVirtual (this=0x7fffffffcc40, input=..., output=..., debugDraw=0x0)
    at thirdparty/bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp:148
        seperatingAxisInA = {m_floats = {0, -0.944851041, -0.327500582, 0}}
        pInA = {m_floats = {0, 0, -0.506190002, 0}}
        w = {m_floats = {0, 0, 8.56320084e-35, 1.40129846e-45}}
        f0 = -nan(0x7fcbb8)
        check = false
        seperatingAxisInB = {m_floats = {0.48281756, 0.680521786, -0.551160276, 0}}
        f1 = 4.59163468e-41
        newCachedSeparatingAxis = {m_floats = {-nan(0x7fc910), 4.59163468e-41, -1.0371708e+34, 4.59163468e-41}}
        qInB = {m_floats = {-nan(0x7fc950), 4.59163468e-41, 4.35475498e-38, 0}}
        pWorld = {m_floats = {-nan(0x7fc930), 4.59163468e-41, 8.56320084e-35, 0}}
        qWorld = {m_floats = {-nan(0x7fc930), 4.59163468e-41, 4.26711077e-38, 0}}
        previousSquaredDistance = -nan(0x7fcbb4)
        squaredDistance = 9.99999984e+17
        delta = 0
        margin = 1.05246997
        catchDegeneratePenetrationCase = 62
---Type <return> to continue, or q <return> to quit---
        distance = 0
        normalInB = {m_floats = {0, 0, 0, 0}}
        pointOnA = {m_floats = {-nan(0x7fce80), 4.59163468e-41, -2.43286166e+32, 4.59163468e-41}}
        pointOnB = {m_floats = {0, 0, -nan(0x7fcb3f), 4.59163468e-41}}
        localTransA = {m_basis = {m_el = {{m_floats = {-0.569220483, -0.269266039, 0.776842356, 0}}, {m_floats = {0, 0.944851041, 0.327500582, 0}}, {m_floats = {-0.82218492, 0.186420023, 
                  -0.537828565, 0}}}}, m_origin = {m_floats = {0.873463631, 1.49094975, -1.37198865, 0}}}
        localTransB = {m_basis = {m_el = {{m_floats = {0.00904083252, 0.62547189, 0.780194283, 0}}, {m_floats = {0.48281756, 0.680521786, -0.551160276, 0}}, {m_floats = {-0.875674367, 
                  0.381674051, -0.295836747, 0}}}}, m_origin = {m_floats = {-0.873463392, -1.49094975, 1.37198865, 0}}}
        positionOffset = {m_floats = {3.15034533, 1.49094975, 1.91675103, 0}}
        check2d = false
        marginA = 1.01247001
        marginB = 0.0399999991
        gGjkMaxIter = 1000
        isValid = false
        checkSimplex = false
        checkPenetration = true
#4  0x0000000001662f58 in btGjkPairDetector::getClosestPoints (this=0x7fffffffcc40, input=..., output=..., debugDraw=0x0, swapResults=false)
    at thirdparty/bullet/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp:83
No locals.
#5  0x00000000013952dc in SpaceBullet::check_ghost_overlaps (this=0x6e40410) at modules/bullet/space_bullet.cpp:705
        result = {<btDiscreteCollisionDetectorInterface::Result> = {_vptr.Result = 0x44ac7c0 <vtable for btPointCollector+16>}, m_normalOnBInWorld = {m_floats = {0, 0, 0, 0}}, 
          m_pointInWorld = {m_floats = {0, 0, 0, 0}}, m_distance = 9.99999984e+17, m_hasResult = false}
        gjk_pair_detector = {<btDiscreteCollisionDetectorInterface> = {_vptr.btDiscreteCollisionDetectorInterface = 0x44e4118 <vtable for btGjkPairDetector+16>}, m_cachedSeparatingAxis = {
            m_floats = {0, 1, 0, 0}}, m_penetrationDepthSolver = 0x6e401d0, m_simplexSolver = 0x6e3a410, m_minkowskiA = 0x71502c0, m_minkowskiB = 0x748b110, m_shapeTypeA = 10, 
          m_shapeTypeB = 5, m_marginA = 1.01247001, m_marginB = 0.0399999991, m_ignoreMargin = false, m_cachedSeparatingDistance = 0, m_lastUsedMethod = -1, m_curIter = 0, 
          m_degenerateSimplex = 0, m_catchDegeneracies = 1, m_fixContactNormalDirection = 1}
        hasOverlap = false
        ghostOverlaps = {m_allocator = {<No data fields>}, m_size = 1, m_capacity = 1, m_data = 0x6db67e0, m_ownsMemory = true}
        other_body_shape = 0x748b110
        area_shape = 0x71502c0
---Type <return> to continue, or q <return> to quit---
        gjk_input = {m_transformA = {m_basis = {m_el = {{m_floats = {-0.569220483, -0.269266039, 0.776842356, 0}}, {m_floats = {0, 0.944851041, 0.327500582, 0}}, {m_floats = {-0.82218492, 
                    0.186420023, -0.537828565, 0}}}}, m_origin = {m_floats = {4.02380896, 2.9818995, 0.544762373, 0}}}, m_transformB = {m_basis = {m_el = {{m_floats = {0.00904083252, 
                    0.62547189, 0.780194283, 0}}, {m_floats = {0.48281756, 0.680521786, -0.551160276, 0}}, {m_floats = {-0.875674367, 0.381674051, -0.295836747, 0}}}}, m_origin = {
              m_floats = {2.27688193, 0, 3.28873968, 0}}}, m_maximumDistanceSquared = 9.99999984e+17}
        area = 0x7153500
        otherObject = 0x72e60b0
        x = 1
        i = 0
        y = 0
        z = 1
        indexOverlap = -1
#6  0x000000000139420e in onBulletTickCallback (p_dynamicsWorld=0x6e3a590, timeStep=0.0166666675) at modules/bullet/space_bullet.cpp:549
        colObjArray = @0x6e3a598: {m_allocator = {<No data fields>}, m_size = 2, m_capacity = 2, m_data = 0x6db68c0, m_ownsMemory = true}
        __PRETTY_FUNCTION__ = "void onBulletTickCallback(btDynamicsWorld*, btScalar)"
        sb = 0x6e40410
#7  0x000000000168bd5d in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x6e3a590, timeStep=0.0166666675)
    at thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:519
        __profile = {<No data fields>}
        dispatchInfo = @0x6e3a5c0: {m_timeStep = 0.0166666675, m_stepCount = 0, m_dispatchFunc = 1, m_timeOfImpact = 1, m_useContinuous = true, m_debugDraw = 0x0, 
          m_enableSatConvex = false, m_enableSPU = true, m_useEpa = true, m_allowedCcdPenetration = 0.0399999991, m_useConvexConservativeDistanceUtil = false, 
          m_convexConservativeDistanceThreshold = 0}
#8  0x00000000016be8de in btSoftRigidDynamicsWorld::internalSingleStepSimulation (this=0x6e3a590, timeStep=0.0166666675) at thirdparty/bullet/BulletSoftBody/btSoftRigidDynamicsWorld.cpp:94
No locals.
#9  0x000000000168bb25 in btDiscreteDynamicsWorld::stepSimulation (this=0x6e3a590, timeStep=0.0166666675, maxSubSteps=1, fixedTimeStep=0.0166666675)
    at thirdparty/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:455
        i = 0
        clampedSimulationSteps = 1
        numSimulationSubSteps = 1
#10 0x000000000139344b in SpaceBullet::step (this=0x6e40410, p_delta_time=0.0166666675) at modules/bullet/space_bullet.cpp:362
No locals.
---Type <return> to continue, or q <return> to quit---
#11 0x000000000136798a in BulletPhysicsServer::step (this=0x6ddf9d0, p_deltaTime=0.0166666675) at modules/bullet/bullet_physics_server.cpp:1560
        i = 0
<snip>
```

**Comment by AndreaCatania** [comment]
Thanks you for this accurate bug report <3

**Comment by Windfisch** [comment]
thank you two for the great and fast response <3
