### ISSUE TITLE
Godot segfaults in a specific resource loading configuration

### ISSUE THREAD

**Issue by groud** [godotengine/godot#22673]
**Godot version:**master 3c62aa778df82806c94abd9c614c4fc7865127ea

**OS/device including version:**archlinux

**Issue description:** 
I have three scenes: A, B and C. A references B (via exported var), B references A (via exported var), C references A (via preload). Godot crashes with a segfault at startup. Or with these errors in loop if ran from the editor :
```
ERROR: poll: res://node1.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://node2.tscn
   At: scene/resources/scene_format_text.cpp:439.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:155.
ERROR: _load: Failed loading resource: res://node1.tscn
```

**Minimal reproduction project:**
[resource_loading_error.zip](https://github.com/godotengine/godot/files/2442048/resource_loading_error.zip)

Ping @vnen, according to @reduz you modified this part of the code.

**Comment by akien-mga** [comment]
Still reproducible in the current master branch. Seems to be looping:
```
(gdb) bt
#0  0x00000000031c6dac in Variant::reference (this=0x0, p_variant=...) at core/variant.cpp:905
#1  0x00000000031ce0aa in Variant::operator= (this=0x7ffff6e21b70, p_variant=...) at core/variant.cpp:2515
#2  0x0000000003244e09 in VariantParser::parse_value (token=..., value=..., p_stream=0x7fffc00cfd48, line=@0x7fffc00cfdc0: 1, r_err_str=..., p_res_parser=0x0)
    at core/variant_parser.cpp:1245
#3  0x0000000003246078 in VariantParser::_parse_tag (token=..., p_stream=0x7fffc00cfd48, line=@0x7fffc00cfdc0: 1, r_err_str=..., r_tag=..., p_res_parser=0x0, p_simple_tag=false)
    at core/variant_parser.cpp:1460
#4  0x0000000003246247 in VariantParser::parse_tag (p_stream=0x7fffc00cfd48, line=@0x7fffc00cfdc0: 1, r_err_str=..., r_tag=..., p_res_parser=0x0, p_simple_tag=false)
    at core/variant_parser.cpp:1484
#5  0x0000000002c49d5a in ResourceInteractiveLoaderText::open (this=0x7fffc00cfc20, p_f=0x7fffc00cf740, p_skip_first_tag=false) at scene/resources/scene_format_text.cpp:833
#6  0x0000000002c4ec72 in ResourceFormatLoaderText::load_interactive (this=0x5959360, p_path=..., p_original_path=..., r_error=0x0) at scene/resources/scene_format_text.cpp:1233
#7  0x0000000003330773 in ResourceFormatLoader::load (this=0x5959360, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_loader.cpp:184
#8  0x0000000003332022 in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:266
#9  0x000000000333255f in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:328
#10 0x0000000002c44134 in ResourceInteractiveLoaderText::poll (this=0x7fffc00cdec0) at scene/resources/scene_format_text.cpp:432
#11 0x00000000033307e9 in ResourceFormatLoader::load (this=0x5959360, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_loader.cpp:191
#12 0x0000000003332022 in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:266
#13 0x000000000333255f in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:328
#14 0x0000000002c44134 in ResourceInteractiveLoaderText::poll (this=0x7fffc00cc160) at scene/resources/scene_format_text.cpp:432
#15 0x00000000033307e9 in ResourceFormatLoader::load (this=0x5959360, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_loader.cpp:191
#16 0x0000000003332022 in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:266
#17 0x000000000333255f in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:328
#18 0x0000000002c44134 in ResourceInteractiveLoaderText::poll (this=0x7fffc00ca400) at scene/resources/scene_format_text.cpp:432
#19 0x00000000033307e9 in ResourceFormatLoader::load (this=0x5959360, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_loader.cpp:191
#20 0x0000000003332022 in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:266
#21 0x000000000333255f in ResourceLoader::load (p_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:328
#22 0x0000000002c44134 in ResourceInteractiveLoaderText::poll (this=0x7fffc00c86a0) at scene/resources/scene_format_text.cpp:432
#23 0x00000000033307e9 in ResourceFormatLoader::load (this=0x5959360, p_path=..., p_original_path=..., r_error=0x0) at core/io/resource_loader.cpp:191
#24 0x0000000003332022 in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_no_cache=false, r_error=0x0) at core/io/resource_loader.cpp:266
[...]
```

**Comment by akien-mga** [comment]
#22758 seems related.

**Comment by reduz** [comment]
I don' t have the slightest clue on how to fix this, sorry.

**Comment by reduz** [comment]
@vnen can you check this? sounds like some sort of check in gdscript that the resource did not load well could help

**Comment by vnen** [comment]
I didn't particularly touch this part of the code. This behavior is not new, I bumped into it a long time ago. If you use exports or preloads that creates circular dependencies make it crash.

I don't know if a check in GDScript would help, I'm not sure if this ever returns to GDScript before crashing.
