### ISSUE TITLE
Create physical skeleton crash in TPS demo

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#22907]
**Godot version:**
master branch

**OS/device including version:**
Windows 7

**Issue description:**
In TPS demo, when I click "Create physical skeleton" in the "player.tscn", Godot crash

**Steps to reproduce:**
In TPS demo, click "Create physical skeleton" in the "player.tscn", Godot crash

**Comment by spongeboburu** [comment]
I get a crash in a test project where I import an armature from collada (exported using better collada), then inherit the scene, click armature in tree and finally click create physical skeleton.

#0  0x000000000261671c in memdelete<PhysicalBone::JointData> (p_class=0x0) at ./core/os/memory.h:119
#1  0x000000000260fc0d in PhysicalBone::set_joint_type (this=0x16bf2550, p_joint_type=PhysicalBone::JOINT_TYPE_PIN) at scene/3d/physics_body.cpp:2329
#2  0x0000000001f8de49 in SkeletonEditor::create_physical_skeleton (this=0xa2aa730) at editor/plugins/skeleton_editor_plugin.cpp:96
#3  0x0000000001f8d805 in SkeletonEditor::_on_click_option (this=0xa2aa730, p_option=0) at editor/plugins/skeleton_editor_plugin.cpp:47
#4  0x00000000011a0835 in MethodBind1<int>::call (this=0xa2ace70, p_object=0xa2aa730, p_args=0x7fffffffb370, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#5  0x0000000002f3f801 in Object::call (this=0xa2aa730, p_method=..., p_args=0x7fffffffb370, p_argcount=1, r_error=...) at core/object.cpp:968
#6  0x0000000002f4103c in Object::emit_signal (this=0xa2ab1b0, p_name=..., p_args=0x7fffffffb370, p_argcount=1) at core/object.cpp:1254
#7  0x0000000002f416a3 in Object::emit_signal (this=0xa2ab1b0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1310
#8  0x0000000002430ed8 in PopupMenu::activate_item (this=0xa2ab1b0, p_item=0) at scene/gui/popup_menu.cpp:1088
#9  0x000000000242a656 in PopupMenu::_gui_input (this=0xa2ab1b0, p_event=...) at scene/gui/popup_menu.cpp:330
#10 0x000000000134acaf in MethodBind1<Ref<InputEvent> const&>::call (this=0x57e2570, p_object=0xa2ab1b0, p_args=0x7fffffffb9e0, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#11 0x0000000002f3ebb8 in Object::call_multilevel (this=0xa2ab1b0, p_method=..., p_args=0x7fffffffb9e0, p_argcount=1) at core/object.cpp:802
#12 0x0000000002f3f3e9 in Object::call_multilevel (this=0xa2ab1b0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:908
#13 0x00000000023140c5 in Viewport::_gui_call_input (this=0x5da8c80, p_control=0xa2ab1b0, p_input=...) at scene/main/viewport.cpp:1422
#14 0x00000000023156b8 in Viewport::_gui_input_event (this=0x5da8c80, p_event=...) at scene/main/viewport.cpp:1760
#15 0x00000000023196cf in Viewport::input (this=0x5da8c80, p_event=...) at scene/main/viewport.cpp:2456
#16 0x0000000002312ffa in Viewport::_vp_input (this=0x5da8c80, p_ev=...) at scene/main/viewport.cpp:1204
#17 0x000000000134acaf in MethodBind1<Ref<InputEvent> const&>::call (this=0x5739d80, p_object=0x5da8c80, p_args=0x7fffffffc6b0, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#18 0x0000000002f3f801 in Object::call (this=0x5da8c80, p_method=..., p_args=0x7fffffffc6b0, p_argcount=1, r_error=...) at core/object.cpp:968
#19 0x0000000002f3f340 in Object::call (this=0x5da8c80, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:892
#20 0x00000000022e98a3 in SceneTree::call_group_flags (this=0x5c142f0, p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at scene/main/scene_tree.cpp:262
#21 0x00000000022ea583 in SceneTree::input_event (this=0x5c142f0, p_event=...) at scene/main/scene_tree.cpp:418
#22 0x00000000011261ba in InputDefault::_parse_input_event_impl (this=0x560d050, p_event=..., p_is_emulated=false) at main/input_default.cpp:414
#23 0x00000000011251ee in InputDefault::parse_input_event (this=0x560d050, p_event=...) at main/input_default.cpp:259
#24 0x0000000001114569 in OS_X11::process_xevents (this=0x7fffffffd080) at platform/x11/os_x11.cpp:1993
#25 0x0000000001118a11 in OS_X11::run (this=0x7fffffffd080) at platform/x11/os_x11.cpp:2813
#26 0x000000000110b67f in main (argc=3, argv=0x7fffffffd7c8) at platform/x11/godot_x11.cpp:55

**Comment by hedgehog90** [comment]
Same here, entire editor crashes.
It seems to have trouble with the root bone which has a parent index of -1.
This is what I get:

```
ERROR: Skeleton::get_bone_parent: Index p_bone=-1 out of size (bones.size()=8)
   At: scene\3d\skeleton.cpp:481
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] CallWindowProcW
[25] CallWindowProcW
[26] glDebugEntry
[27] CallWindowProcW
[28] DispatchMessageW
[29] <couldn't map PC to fn name>
[30] <couldn't map PC to fn name>
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by nagasawamaki** [comment]
@AndreaCatania Hope it is ok to tag you

**Comment by AndreaCatania** [comment]
I think that this problem was fixed, can you please tell us if this is solved?

**Comment by akien-mga** [comment]
I still get this error in the TPS demo:
```
ERROR: get_bone_parent: Index p_bone=-1 out of size (bones.size()=112)
   At: scene/3d/skeleton.cpp:481.
ERROR: erase: Condition ' !p_I ' is true. returned: false
   At: ./core/list.h:157.
```
But no crash.
