### ISSUE TITLE
Derived apk from google android console and original apk crashes on start, but works from editor

### ISSUE THREAD

**Issue by theblockhouse** [godotengine/godot#23067]
**Godot version:**
3.06-stable

**OS/device including version:**
Windows 10

**Issue description:**
running game from editor (to android device) works, but "derived apk" from android console and original apk crashes at start

**Steps to reproduce:**
Compile with google play services module and export to android then upload apk to google console, finally download derived apk back from google or install exported apk manually

ERROR:
10-16 16:26:08.437 E/AndroidRuntime(19246): FATAL EXCEPTION: main
10-16 16:26:08.437 E/AndroidRuntime(19246): Process: org.godotengine.albatross, PID: 19246
10-16 16:26:08.437 E/AndroidRuntime(19246): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.godotengine.albatross-1/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.albatross-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libgodot_android.so"
10-16 16:26:08.437 E/AndroidRuntime(19246):     at java.lang.Runtime.loadLibrary0(Runtime.java:984)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at java.lang.System.loadLibrary(System.java:1567)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:40)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at org.godotengine.godot.Godot.initializeGodot(Godot.java:414)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at org.godotengine.godot.Godot.onCreate(Godot.java:596)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.Activity.performCreate(Activity.java:6977)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.ActivityThread.-wrap14(ActivityThread.java)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.os.Looper.loop(Looper.java:154)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at android.app.ActivityThread.main(ActivityThread.java:6816)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at java.lang.reflect.Method.invoke(Native Method)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
10-16 16:26:08.437 E/AndroidRuntime(19246):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by theblockhouse** [comment]
Okay I had not properly targeted release for compiling the android module that seemed to be the issue
