### ISSUE TITLE
Export to Android 8.0: java.lang.IllegalArgumentException: Unknown package - during installation

### ISSUE THREAD

**Issue by aplut** [godotengine/godot#23111]
Hi,

probably found some issue. I'm trying to export empty project and run on android device.

My setup:
Android 8.0.0
Ubuntu 16.04
Java 1.8.0_181
Android SDK 26

My editor was configured as described in docs adb, jarsigner and keystore. I was trying one click installation and manual installation but always the same. The installation process never ends itself.

Found in logs something like this:

> jar verified. Warning: This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2047-04-14) or after any future revocation date. Re-run with the -verbose and -certs options for more details. Uninstalling previous version: Honor LLD-L31 Exception occurred while executing: java.lang.IllegalArgumentException: Unknown package: org.godotengine.test at com.android.server.pm.Settings.isOrphaned(Settings.java:4580) at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:23318) at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:20042) at com.android.server.pm.HwPackageManagerService.deletePackageVersioned(HwPackageManagerService.java:5798) at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913) at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:920) at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:136) at android.os.ShellCommand.exec(ShellCommand.java:96) at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23624) at android.os.Binder.shellCommand(Binder.java:574) at android.os.Binder.onTransact(Binder.java:474) at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2652) at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3921) at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:943) at android.os.Binder.execTransact(Binder.java:675) Installing into device (please wait..): Honor LLD-L31

For Android **6.0.1** works as expected.

Best regards,
Adrian

**Comment by GrandFunkR** [comment]
I have same issue using device with android 8.0
Using one click deploy:

`Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: org.godotengine.FantaAsta
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4437)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21994)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:19015)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:918)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:934)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:135)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22293)
	at android.os.Binder.shellCommand(Binder.java:573)
	at android.os.Binder.onTransact(Binder.java:473)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2654)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3647)
	at android.os.Binder.execTransact(Binder.java:674)
Installing to device (please wait...): Sony F5321
adb: failed to install /home/dario/.cache/godot/tmpexport.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1442233067.tmp/base.apk: AndroidManifest.xml]`

using adb
adb install -r myfile.apk

`adb: failed to install org.godotengine.FantaAsta.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl20025429.tmp/base.apk: AndroidManifest.xml]`

**Comment by akien-mga** [comment]
What Godot version(s) are you using?

Maybe @volzhs or @RandomShaper can help debug? I have no Android 8.0 device to test.

**Comment by akien-mga** [comment]
Well now I do have a recent enough device, so I'll try.

**Comment by akien-mga** [comment]
Couldn't reproduce the issue, I've exported various projects to Android 8 and Android 9 without problem.

**Comment by Icelimo** [comment]
Also had this Big, while trying to open an Android Studio Project at another PC.
Used at the Main PC Android Studio 3.4.1. And at the PC, where the Bug occurres 1.4.0.

Unknown failure: Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.pokemon.projekt1
at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21529)
at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:18603)
at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:913)
at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
at android.os.ShellCommand.exec(ShellCommand.java:96)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21828)
at android.os.Binder.shellCommand(Binder.java:573)
at android.os.Binder.onTransact(Binder.java:473)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2644)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3486)
at android.os.Binder.execTransact(Binder.java:674)
Error while Installing APKs

**Comment by SinghRupesh** [comment]
Just Invalidate caches and restart your project.

Go To-> File ->Invalidate Caches / Restart

**Comment by micfan** [comment]
This is not an error during "Export" action.

I got this error when click the fast deploy to Andriod Emulator...
