### ISSUE TITLE
Crash opening Pong c# 3.1 alpha 2

### ISSUE THREAD

**Issue by skarmiglione** [godotengine/godot#23592]
**Godot version:**

3.1 alpha2 oficial
**OS/device including version:**
Linux mint

**Steps to reproduce:**
Triying to open Pong Demo c# and it just crash.

**Minimal reproduction project:**

[0xb298be]

Debug info from gdb:
```
[Nuevo LWP 9503]
[Nuevo LWP 9506]
[Nuevo LWP 9507]
[Nuevo LWP 9508]
[Nuevo LWP 9509]
[Nuevo LWP 9510]
[Nuevo LWP 9511]
[Nuevo LWP 9512]
[Nuevo LWP 9513]
[Nuevo LWP 9514]
[Nuevo LWP 9515]
[setting tty state failed in terminal_inferior: Error de entrada/salida]
[Depuración de hilo usando libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x0000003000810f7b in __waitpid (pid=9520, stat_loc=0x7ffe509f01ac, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: No existe el archivo o el directorio.
  Id   Target Id         Frame 
* 1    Thread 0x7fb05dd7c940 (LWP 9502) "Godot_v3.1-alph" 0x0000003000810f7b in __waitpid (pid=9520, stat_loc=0x7ffe509f01ac, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7fb05ab03700 (LWP 9503) "Godot_v3.1-alph" 0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5ff4158) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fb05930b700 (LWP 9506) "Godot_v3.1-alph" 0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x6523cb8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7fb04b336700 (LWP 9507) "Godot_v3.1-alph" 0x0000003000810c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  5    Thread 0x7fb04b2f5700 (LWP 9508) "Godot_v3.1-alph" 0x00000030004cc30d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  6    Thread 0x7fb04ad0a700 (LWP 9509) "Godot_v3.1-alph" 0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x6477128) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  7    Thread 0x7fb04a509700 (LWP 9510) "Godot_v3.1-alph" 0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x64770d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  8    Thread 0x7fb03abff700 (LWP 9511) "SGen worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7fb03b3ff700 (LWP 9512) "Finalizer" 0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x4268160 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  10   Thread 0x7fb04b2b4700 (LWP 9513) "Godot_v3.1-alph" 0x0000003000810c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
  11   Thread 0x7fb04b273700 (LWP 9514) "Godot_v3.1-alph" 0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x6520bf8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  12   Thread 0x7fb04b232700 (LWP 9515) "Godot_v3.1-alph" 0x0000003000810c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84

Thread 12 (Thread 0x7fb04b232700 (LWP 9515)):
#0  0x0000003000810c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000002bed0db in OS_Unix::delay_usec(unsigned int) const [clone .constprop.11526] ()
#2  0x0000000000000000 in ?? ()

Thread 11 (Thread 0x7fb04b273700 (LWP 9514)):
#0  0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x6520bf8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x6520bf8, abstime=0x0) at sem_waitcommon.c:111
#2  0x000000300080f8d4 in __new_sem_wait_slow (sem=0x6520bf8, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000300080f97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000001384c3d in SemaphorePosix::wait() [clone .part.0] ()
#5  0x0000000006580bb0 in ?? ()
#6  0x00000000025e480b in VisualServerWrapMT::texture_get_data(RID, int) const ()
#7  0x00000000065c0cd8 in ?? ()
#8  0x00000000064daec0 in ?? ()
#9  0x00007fb04b272b70 in ?? ()
#10 0x0000000000000000 in ?? ()

Thread 10 (Thread 0x7fb04b2b4700 (LWP 9513)):
#0  0x0000003000810c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000002bed0db in OS_Unix::delay_usec(unsigned int) const [clone .constprop.11526] ()
#2  0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7fb03b3ff700 (LWP 9512)):
#0  0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x4268160 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x4268160 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:111
#2  0x000000300080f8d4 in __new_sem_wait_slow (sem=0x4268160 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000300080f97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000caa8cc in finalizer_thread ()
#5  0x0000000000d568e3 in start_wrapper ()
#6  0x00000030008076ba in start_thread (arg=0x7fb03b3ff700) at pthread_create.c:333
#7  0x000000300050741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7fb03abff700 (LWP 9511)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000dc0493 in thread_func ()
#2  0x00000030008076ba in start_thread (arg=0x7fb03abff700) at pthread_create.c:333
#3  0x000000300050741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7fb04a509700 (LWP 9510)):
#0  0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x64770d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x64770d8, abstime=0x0) at sem_waitcommon.c:111
#2  0x000000300080f8d4 in __new_sem_wait_slow (sem=0x64770d8, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000300080f97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x00007fb05de36652 in ?? () from /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
#5  0x00000030008076ba in start_thread (arg=0x7fb04a509700) at pthread_create.c:333
#6  0x000000300050741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7fb04ad0a700 (LWP 9509)):
#0  0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x6477128) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x6477128, abstime=0x0) at sem_waitcommon.c:111
#2  0x000000300080f8d4 in __new_sem_wait_slow (sem=0x6477128, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000300080f97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x00007fb05de37752 in ?? () from /usr/lib/x86_64-linux-gnu/primus/libGL.so.1
#5  0x00000030008076ba in start_thread (arg=0x7fb04ad0a700) at pthread_create.c:333
#6  0x000000300050741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7fb04b2f5700 (LWP 9508)):
#0  0x00000030004cc30d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00000030004fdd94 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x000000000286dfdf in JoypadLinux::monitor_joypads() ()
#3  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7fb04b336700 (LWP 9507)):
#0  0x0000003000810c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000002bed0db in OS_Unix::delay_usec(unsigned int) const [clone .constprop.11526] ()
#2  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7fb05930b700 (LWP 9506)):
#0  0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x6523cb8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x6523cb8, abstime=0x0) at sem_waitcommon.c:111
#2  0x000000300080f8d4 in __new_sem_wait_slow (sem=0x6523cb8, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000300080f97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000001384c3d in SemaphorePosix::wait() [clone .part.0] ()
#5  0x00007fb05930c020 in ?? ()
#6  0x0000000002610c9c in VisualServerScene::_gi_probe_bake_thread() ()
#7  0x0000000006523d40 in ?? ()
#8  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7fb05ab03700 (LWP 9503)):
#0  0x000000300080f827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5ff4158) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x5ff4158, abstime=0x0) at sem_waitcommon.c:111
#2  0x000000300080f8d4 in __new_sem_wait_slow (sem=0x5ff4158, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000300080f97a in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000001384c3d in SemaphorePosix::wait() [clone .part.0] ()
#5  0x0000000005ff4190 in ?? ()
#6  0x00000000028c9286 in _IP_ResolverPrivate::_thread_function(void*) ()
#7  0x0000000000000003 in ?? ()
#8  0x00007fb05ab03700 in ?? ()
#9  0x00007fb05ab03700 in ?? ()
#10 0x94a2bc0f6af58a00 in ?? ()
#11 0x00007fb05ab02d30 in ?? ()
#12 0x0000000005ff4190 in ?? ()
#13 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7fb05dd7c940 (LWP 9502)):
#0  0x0000003000810f7b in __waitpid (pid=9520, stat_loc=0x7ffe509f01ac, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x0000000000c0998c in mono_handle_native_crash ()
#2  <signal handler called>
#3  0x0000003000435428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x000000300043702a in __GI_abort () at abort.c:89
#5  0x000000000106fe9e in GDMonoInternals::unhandled_exception(_MonoException*) ()
#6  0x0000000000000001 in ?? ()
#7  0x0000000000e82393 in GDMonoUtils::debug_unhandled_exception(_MonoException*) ()
#8  0x00007ffe509f1250 in ?? ()
#9  0x00000000011202b0 in GodotSharpBuilds::BuildProcess::start(bool) ()
#10 0x0000000000000000 in ?? ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
================================================================
```

**Comment by akien-mga** [comment]
Please fill the requested information of the issue template.

**Comment by skarmiglione** [comment]
> Please fill the requested information of the issue template.

Done

**Comment by aaronfranke** [comment]
Does the problem occur with 3.0.6? Are you using Mono 5.12 exactly?

**Comment by akien-mga** [comment]
The demo seems to work fine against 3.1 beta 6.
