### ISSUE TITLE
Using the screen texture in a visual shader and trying to preview it crashes the engine

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#24353]
**Godot version:**

Godot 3.1 alpha 3

**OS/device including version:**

Windows 10 Nvidia 1070

**Issue description:**

When trying to preview the texture of a `Screen` texture or any node connected to its output makes the editor crash.

**Steps to reproduce:**
1. Add a `ColorRect`
2. Add a visual shader to that node with `CanvasItem` mode
3. Add a constant texture node and set it to `Screen`
4. Try to preview the `rgb` data of that texture node

**Comment by bojidar-bg** [comment]
A backtrace might be useful.

**Comment by akien-mga** [comment]
Confirmed in the current master branch (6e60070), for me it's even crashing on step 3 (when setting the `Texture` node to `Screen`):
```
free(): invalid next size (fast)

(gdb) bt
#0  0x0000003405e3a0aa in raise () from /lib64/libc.so.6
#1  0x0000003405e22524 in abort () from /lib64/libc.so.6
#2  0x0000003405e7cad8 in __libc_message () from /lib64/libc.so.6
#3  0x0000003405e8337a in malloc_printerr () from /lib64/libc.so.6
#4  0x0000003405e848d8 in _int_free () from /lib64/libc.so.6
#5  0x000000000327c7ad in Memory::free_static (p_ptr=0x11a01590, p_pad_align=false) at core/os/memory.cpp:181
#6  0x00000000011aeb1a in DefaultAllocator::free (p_ptr=0x11a01590) at ./core/os/memory.h:69
#7  0x00000000011ec0e6 in memdelete_allocator<List<Node*, DefaultAllocator>::Element, DefaultAllocator> (p_class=0x11a01590) at ./core/os/memory.h:133
#8  0x00000000011eb923 in List<Node*, DefaultAllocator>::_Data::erase (this=0x15e9d860, p_I=0x11a01590) at ./core/list.h:173
#9  0x00000000011eac02 in List<Node*, DefaultAllocator>::erase (this=0x612ad18, p_I=0x11a01590) at ./core/list.h:368
#10 0x00000000011ea0e4 in List<Node*, DefaultAllocator>::clear (this=0x612ad18) at ./core/list.h:404
#11 0x0000000001bcde45 in EditorSelection::_update_nl (this=0x612ac00) at editor/editor_data.cpp:1082
#12 0x0000000001bcdf44 in EditorSelection::update (this=0x612ac00) at editor/editor_data.cpp:1107
#13 0x0000000001c6ba15 in EditorNode::_notification (this=0x66292e0, p_what=17) at editor/editor_node.cpp:278
#14 0x0000000001cace74 in EditorNode::_notificationv (this=0x66292e0, p_notification=17, p_reversed=false) at editor/editor_node.h:100
#15 0x0000000003151be8 in Object::notification (this=0x66292e0, p_notification=17, p_reversed=false) at core/object.cpp:955
#16 0x00000000024ca1c0 in SceneTree::_notify_group_pause (this=0x5e203e0, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:967
#17 0x00000000024c7f3e in SceneTree::idle (this=0x5e203e0, p_time=0.00833333377) at scene/main/scene_tree.cpp:510
#18 0x00000000011e7834 in Main::iteration () at main/main.cpp:1876
#19 0x00000000011bcc9b in OS_X11::run (this=0x7fffffffd350) at platform/x11/os_x11.cpp:2986
#20 0x00000000011aea8d in main (argc=2, argv=0x7fffffffdad8) at platform/x11/godot_x11.cpp:55
```

**Comment by akien-mga** [comment]
Well my reproduction steps are 1, 2, 3 from the OP, so it's quite similar. But I'll open a new report :)

**Comment by akien-mga** [comment]
I can't reproduce the crash anymore in 45a400d9 using the same steps I used two days ago.
