### ISSUE TITLE
crashed: Nexus 7 (2012) (grouper)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#2443]
prj: https://play.google.com/store/apps/details?id=com.dyadchenko.ss4km
os: Android 4.4
java.lang.IllegalArgumentException
at com.google.android.gles_jni.EGLImpl._eglCreateContext(Native Method)
at com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
at com.android.godot.GodotView$ContextFactory.createContext(GodotView.java:397)
at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1030)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by reduz** [comment]
Hmm I have a Nexus 7 2012 and never had any issues with it, but will give
it a test

**Comment by kubecz3k** [comment]
I think this bug might be related to OUYA crash bug (https://github.com/okamstudio/godot/issues/1608) since both these devices have Tegra 3 cpu.

**Comment by akien-mga** [comment]
@ret80 Can you test the solution described in https://github.com/godotengine/godot/issues/1608#issuecomment-158626872?

**Comment by akien-mga** [comment]
We believe this issue might be fixed by #2862. Feel free to reopen (or ask me to reopen) if it's not the case.
