### ISSUE TITLE
Unable to export C# project on Ubuntu

### ISSUE THREAD

**Issue by tnibert** [godotengine/godot#24930]
**Godot version:**
commit 1b5b27430f36440c9f54f675d823c696f8eb3908

**OS/device including version:**
```
tim@komodo:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
```
tim@komodo:~$ mono --version
Mono JIT compiler version 5.16.0.220 (tarball Wed Jan  2 21:11:00 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)
```

**Issue description:**

I am unable to export a C# project on Linux.  I have compiled Godot with the following commands:
```
scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no
bin/godot.x11.tools.64.mono --generate-mono-glue modules/mono/glue
scons p=x11 target=release_debug tools=yes module_mono_enabled=yes mono_glue=yes
scons p=x11 target=debug tools=no module_mono_enabled=yes
scons p=x11 target=release tools=no module_mono_enabled=yes
```
This leaves me with a bin directory like so:
```
tim@komodo:~/code/godot/godot/bin$ ls
data.mono.x11.64.debug  data.mono.x11.64.release  GodotSharp  godot.x11.debug.64.mono  godot.x11.opt.64.mono  godot.x11.opt.tools.64.mono  godot.x11.tools.64.mono  libmonosgen-2.0.so
```
Per issue #24234 (which specifies one of the same error messages I am seeing), I copied data.mono folders to templates folder.
`tim@komodo:~/code/godot/godot/bin$ cp -r data.mono.x11.64.* ~/.local/share/godot/templates/`

I downloaded the export templates from https://downloads.tuxfamily.org/godotengine/3.1/beta1/mono/Godot_v3.1-beta1_mono_export_templates.tpz dated 2019-Jan-08 09:01:06.
Loading this package via Manage Export Templates shows "No export template found" in export dialog.
I specified the file in the Release field under Custom Template and received the following output from Godot Editor in the bash window:
```
tim@komodo:~/code/godot/godot/bin$ ./godot.x11.opt.tools.64.mono 
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
Editing project: /home/tim/code/godot-3d-learn (::home::tim::code::godot-3d-learn)
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
tim@komodo:~/code/godot/godot/bin$ ERROR: initialize: The loaded Core API assembly is out of sync
   At: modules/mono/mono_gd/gd_mono.cpp:288.
Mono: Proceeding to unload scripts domain because of invalid API assemblies.
Running: /home/tim/code/godot/godot/bin/godot.x11.opt.tools.64.mono --path /home/tim/code/godot-3d-learn --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 24705 --position 448,240
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
end ready
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Godot.Object.godot_icall_Reference_Disposed (Godot.Object,intptr,bool) [0x00009] in <a895e94b9f334247b5a34bcf09036102>:0
  at Godot.Object.Dispose (bool) [0x0002a] in /home/tim/.local/share/godot/mono/solutions/81959457763721399_5_1546052277/GodotSharp/Core/Object.base.cs:57
  at Godot.Object.Finalize () [0x00000] in /home/tim/.local/share/godot/mono/solutions/81959457763721399_5_1546052277/GodotSharp/Core/Object.base.cs:38
  at (wrapper runtime-invoke) object.runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr) [0x0001f] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
/proc/self/maps:
00400000-04199000 r-xp 00000000 08:0a 7252530                            /home/tim/code/godot/godot/bin/godot.x11.opt.tools.64.mono
04399000-04454000 r--p 03d99000 08:0a 7252530                            /home/tim/code/godot/godot/bin/godot.x11.opt.tools.64.mono
04454000-0446b000 rw-p 03e54000 08:0a 7252530                            /home/tim/code/godot/godot/bin/godot.x11.opt.tools.64.mono
0446b000-04482000 rw-p 00000000 00:00 0 
04d74000-0aa52000 rw-p 00000000 00:00 0                                  [heap]
407e0000-407e2000 r-xs 00000000 08:08 8519689                            /tmp/.glvBG0eK (deleted)
40b64000-40b74000 rwxp 00000000 00:00 0 
40ebd000-40eed000 rwxp 00000000 00:00 0 
41117000-411b8000 rw-p 00000000 00:00 0 
411ec000-411fc000 rwxp 00000000 00:00 0 
41873000-41883000 rwxp 00000000 00:00 0 
7f43f0000000-7f43f0021000 rw-p 00000000 00:00 0 
7f43f0021000-7f43f4000000 ---p 00000000 00:00 0 
7f43f49fd000-7f43f4dfd000 rw-s 00000000 00:06 521                        /dev/nvidiactl
7f43f4dfd000-7f43f51fd000 rw-s 00000000 00:06 521                        /dev/nvidiactl
7f43f51fd000-7f43f55fd000 rw-s 00000000 00:06 521                        /dev/nvidiactl
7f43f55fd000-7f43f59fd000 rw-s 00000000 00:06 521                        /dev/nvidiactl
7f43f8000000-7f43f8021000 rw-p 00000000 00:00 0 
7f43f8021000-7f43fc000000 ---p 00000000 00:00 0 
7f43fc000000-7f43fc021000 rw-p 00000000 00:00 0 
7f43fc021000-7f4400000000 ---p 00000000 00:00 0 
7f44001fd000-7f44005fd000 rw-s 00000000 00:06 521                        /dev/nvidiactl
7f44005fd000-7f44007fd000 rw-s 00000000 00:06 521                        /dev/nvidiactl
7f44027fe000-7f4402bfe000 rw-p 00000000 00:00 0 
7f4402bff000-7f4402fff000 rw-s 00000000 00:06 521                        /dev/nvidiactl

Unhandled Exception:
System.IO.FileNotFoundException: Data template directory not found
  at GodotSharpTools.Editor.GodotSharpExport._ExportBegin (System.String[] features, System.Boolean debug, System.String path, System.Int32 flags) [0x000c3] in <f2a82256952b40019b74cec7788fed45>:0 
ERROR: _export_begin: Method/Function Failed.
   At: modules/mono/editor/godotsharp_export.cpp:161.
ERROR: copy: Failed to open 
   At: core/os/dir_access.cpp:300.
ERROR: _export_project_to_path: Failed to export project
   At: editor/project_export.cpp:978.
```
I then tricked the Godot export manager into taking the downloaded tpz file:
```
tim@komodo:~/.local/share/godot/templates$ ls
3.1.beta1.mono  data.mono.x11.64.debug  data.mono.x11.64.release
tim@komodo:~/.local/share/godot/templates$ ln -s 3.1.beta1.mono 3.1.beta.mono
tim@komodo:~/.local/share/godot/templates$ ls
3.1.beta1.mono  3.1.beta.mono  data.mono.x11.64.debug  data.mono.x11.64.release
```
I then export project, progress bar does not seem to exceed zero percent before progress window closes.
From Godot Editor in bash console:
```
Unhandled Exception:
System.IO.FileNotFoundException: Data template directory not found
  at GodotSharpTools.Editor.GodotSharpExport._ExportBegin (System.String[] features, System.Boolean debug, System.String path, System.Int32 flags) [0x000c3] in <f2a82256952b40019b74cec7788fed45>:0 
ERROR: _export_begin: Method/Function Failed.
   At: modules/mono/editor/godotsharp_export.cpp:161.
```
From running the exported binary:
```
tim@komodo:~/code/godot-3d-learn$ ./firstbuild.x86_64 
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
ERROR: initialize: The loaded API assembly is invalid
   At: modules/mono/mono_gd/gd_mono.cpp:307.
ERROR: initialize: FATAL: Method/Function Failed.
   At: modules/mono/mono_gd/gd_mono.cpp:308.
Stacktrace:

/proc/self/maps:
00400000-02aba000 r-xp 00000000 08:0a 7507315                            /home/tim/code/godot-3d-learn/firstbuild.x86_64
02cb9000-02d4f000 r--p 026b9000 08:0a 7507315                            /home/tim/code/godot-3d-learn/firstbuild.x86_64
02d4f000-02d5b000 rw-p 0274f000 08:0a 7507315                            /home/tim/code/godot-3d-learn/firstbuild.x86_64
02d5b000-02d86000 rw-p 00000000 00:00 0 
02fe9000-04a3f000 rw-p 00000000 00:00 0                                  [heap]
40024000-40026000 r-xs 00000000 08:08 8519689                            /tmp/.gllGXUQP (deleted)
40883000-40893000 rwxp 00000000 00:00 0 
41474000-41484000 rwxp 00000000 00:00 0 
41aad000-41abd000 rwxp 00000000 00:00 0 
41e54000-41ef5000 rw-p 00000000 00:00 0 
7fd7d0000000-7fd7d0021000 rw-p 00000000 00:00 0 
7fd7d0021000-7fd7d4000000 ---p 00000000 00:00 0 
7fd7d8000000-7fd7d8021000 rw-p 00000000 00:00 0 
7fd7d8021000-7fd7dc000000 ---p 00000000 00:00 0 
7fd7dc000000-7fd7dc021000 rw-p 00000000 00:00 0 
7fd7dc021000-7fd7e0000000 ---p 00000000 00:00 0 
7fd7e3c00000-7fd7e4000000 rw-p 00000000 00:00 0 
7fd7e4000000-7fd7e4021000 rw-p 00000000 00:00 0 
7fd7e4021000-7fd7e8000000 ---p 00000000 00:00 0 
7fd7e87ff000-7fd7e97ff000 rw-p 00000000 00:00 0 
7fd7e97ff000-7fd7e9800000 ---p 00000000 00:00 0 
7fd7e9800000-7fd7ea400000 rw-p 00000000 00:00 0 
7fd7ea57b000-7fd7ea57c000 ---p 00000000 00:00 0 
7fd7ea57c000-7fd7ea57d000 rw-p 00000000 00:00 0 
7fd7ea57d000-7fd7ea585000 ---p 00000000 00:00 0 
Memory around native instruction pointer (0xd8bfa7):
0xd8bf97  2d 5c 67 01 48 8d 3d 56 38 67 01 e8 99 71 36 01  -\g.H.=V8g...q6.
0xd8bfa7  0f 0b 49 89 c6 e9 87 b5 94 ff 49 89 c6 e9 e5 b5  ..I.......I.....
0xd8bfb7  94 ff 48 89 c3 e9 13 b6 94 ff 49 89 c6 e9 1f b6  ..H.......I.....
0xd8bfc7  94 ff 49 89 c6 e9 26 b6 94 ff 49 89 c6 e9 5b b6  ..I...&...I...[.

Native stacktrace:

	./firstbuild.x86_64() [0x9bcc07]
	./firstbuild.x86_64() [0x9d1c48]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7fd809618890]
	./firstbuild.x86_64(_ZN6GDMono10initializeEv+0x1067) [0xd8bfa7]
	./firstbuild.x86_64(_ZN12ScriptServer14init_languagesEv+0x16f) [0x22dd75f]
	./firstbuild.x86_64(_ZN4Main6setup2Em+0xc31) [0xcde3a1]
	./firstbuild.x86_64(_ZN4Main5setupEPKciPPcb+0x3d13) [0xce28a3]
	./firstbuild.x86_64(main+0x5f) [0x8f306f]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fd808a8cb97]
	./firstbuild.x86_64() [0x8f4dbe]

Debug info from gdb:

[New LWP 25077]
[New LWP 25078]
[New LWP 25079]
[New LWP 25080]
[New LWP 25081]
[New LWP 25082]
[New LWP 25083]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fd80961823a in __waitpid (pid=pid@entry=25084, stat_loc=stat_loc@entry=0x7ffe26cc350c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7fd809a0ef40 (LWP 25076) "firstbuild.x86_" 0x00007fd80961823a in __waitpid (pid=pid@entry=25084, stat_loc=stat_loc@entry=0x7ffe26cc350c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7fd809a0d700 (LWP 25077) "firstbuild.x86_" 0x00007fd8096166d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x308c158) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fd800dfa700 (LWP 25078) "firstbuild.x86_" 0x00007fd8096166d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x330a648) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7fd7eada7700 (LWP 25079) "firstbuild.x86_" 0x00007fd809617c60 in __GI___nanosleep (requested_time=0x7fd7eada6d80, remaining=0x7fd7eada6d80) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  5    Thread 0x7fd7ead66700 (LWP 25080) "firstbuild.x86_" 0x00007fd808b4f9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fd7ead65d60, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  6    Thread 0x7fd7e9fff700 (LWP 25081) "SGen worker" 0x00007fd8096139f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x2d6f808 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7fd7eac43700 (LWP 25082) "Finalizer" 0x00007fd8096166d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x2d5d880 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  8    Thread 0x7fd7ea77b700 (LWP 25083) "Debugger agent" 0x00007fd8096176d7 in __libc_accept (fd=fd@entry=19, addr=addr@entry=..., len=len@entry=0x0) at ../sysdeps/unix/sysv/linux/accept.c:26

Thread 8 (Thread 0x7fd7ea77b700 (LWP 25083)):
#0  0x00007fd8096176d7 in __libc_accept (fd=fd@entry=19, addr=addr@entry=..., len=len@entry=0x0) at ../sysdeps/unix/sysv/linux/accept.c:26
#1  0x0000000000a2a823 in socket_transport_accept (socket_fd=19) at debugger-agent.c:1095
#2  0x0000000000a3f1b4 in wait_for_attach () at debugger-agent.c:10392
#3  debugger_thread (arg=arg@entry=0x0) at debugger-agent.c:10446
#4  0x0000000000b39c65 in start_wrapper_internal (stack_ptr=0x7fd7ea77c000, start_info=0x0) at threads.c:1127
#5  start_wrapper (data=0x44addc0) at threads.c:1187
#6  0x00007fd80960d6db in start_thread (arg=0x7fd7ea77b700) at pthread_create.c:463
#7  0x00007fd808b8c88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fd7eac43700 (LWP 25082)):
#0  0x00007fd8096166d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x2d5d880 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x2d5d880 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fd8096167c8 in __new_sem_wait_slow (sem=sem@entry=0x2d5d880 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007fd809616839 in __new_sem_wait (sem=sem@entry=0x2d5d880 <finalizer_sem>) at sem_wait.c:42
#4  0x0000000000a82117 in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x2d5d880 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:209
#5  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x2d5d880 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:43
#6  finalizer_thread (unused=unused@entry=0x0) at gc.c:903
#7  0x0000000000b39c65 in start_wrapper_internal (stack_ptr=0x7fd7eac44000, start_info=0x0) at threads.c:1127
#8  start_wrapper (data=0x44acd40) at threads.c:1187
#9  0x00007fd80960d6db in start_thread (arg=0x7fd7eac43700) at pthread_create.c:463
#10 0x00007fd808b8c88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fd7e9fff700 (LWP 25081)):
#0  0x00007fd8096139f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x2d6f808 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x2d6f820 <lock>, cond=0x2d6f7e0 <work_cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x2d6f7e0 <work_cond>, mutex=mutex@entry=0x2d6f820 <lock>) at pthread_cond_wait.c:655
#3  0x0000000000ba337b in mono_os_cond_wait (mutex=0x2d6f820 <lock>, cond=0x2d6f7e0 <work_cond>) at ../../mono/utils/mono-os-mutex.h:173
#4  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#5  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#6  0x00007fd80960d6db in start_thread (arg=0x7fd7e9fff700) at pthread_create.c:463
#7  0x00007fd808b8c88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fd7ead66700 (LWP 25080)):
#0  0x00007fd808b4f9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fd7ead65d60, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007fd808b82877 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x0000000000c37a42 in JoypadLinux::monitor_joypads() ()
#3  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7fd7eada7700 (LWP 25079)):
#0  0x00007fd809617c60 in __GI___nanosleep (requested_time=0x7fd7eada6d80, remaining=0x7fd7eada6d80) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00000000022199eb in OS_Unix::delay_usec(unsigned int) const [clone .constprop.9425] ()
#2  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7fd800dfa700 (LWP 25078)):
#0  0x00007fd8096166d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x330a648) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x330a648, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fd8096167c8 in __new_sem_wait_slow (sem=0x330a648, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000191d31d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x00007fd800dfb020 in ?? ()
#5  0x0000000001e3c4dc in VisualServerScene::_gi_probe_bake_thread() ()
#6  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7fd809a0d700 (LWP 25077)):
#0  0x00007fd8096166d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x308c158) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x308c158, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fd8096167c8 in __new_sem_wait_slow (sem=0x308c158, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000191d31d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x000000000308c190 in ?? ()
#5  0x0000000002197254 in _IP_ResolverPrivate::_thread_function(void*) ()
#6  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7fd809a0ef40 (LWP 25076)):
#0  0x00007fd80961823a in __waitpid (pid=pid@entry=25084, stat_loc=stat_loc@entry=0x7ffe26cc350c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00000000009bccab in mono_handle_native_crash () at mini-exceptions.c:3312
#2  0x00000000009d1c48 in mono_sigill_signal_handler (_dummy=4, _info=0x7ffe26cc3fb0, context=0x7ffe26cc3e80) at mini-runtime.c:3374
#3  <signal handler called>
#4  0x0000000000d8bfa7 in GDMono::initialize() ()
#5  0x00000000022dd75f in ScriptServer::init_languages() ()
#6  0x00007ffe26cc46f0 in ?? ()
#7  0x00007ffe26cc46f8 in ?? ()
#8  0x00007ffe26cc4740 in ?? ()
#9  0x00007ffe26cc4710 in ?? ()
#10 0x00007ffe26cc4780 in ?? ()
#11 0x0100000000000000 in ?? ()
#12 0x00000000043be8b0 in ?? ()
#13 0x00000000043bef30 in ?? ()
#14 0x00007ffe26cc47a0 in ?? ()
#15 0x00000000022a13b1 in StringName::operator=(StringName const&) [clone .part.2] ()
#16 0x0000000000000000 in ?? ()

=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted (core dumped)

```
I then moved the data.mono folders to the templates/3.1.beta.mono folder:
```
tim@komodo:~/.local/share/godot/templates$ ls
3.1.beta1.mono  3.1.beta.mono  data.mono.x11.64.debug  data.mono.x11.64.release
tim@komodo:~/.local/share/godot/templates$ mv data.mono.x11.64.* 3.1.beta.mono/
tim@komodo:~/.local/share/godot/templates$ ls 3.1.beta.mono
browscap.ini    config.xml                DefaultWsdlHelpGenerator.aspx  linux_x11_32_debug    linux_x11_64_release  osx.zip       web.config              windows_64_debug.exe
Compat.browser  data.mono.x11.64.debug    libmono-btls-shared.so         linux_x11_32_release  machine.config        settings.map  windows_32_debug.exe    windows_64_release.exe
config          data.mono.x11.64.release  libMonoPosixHelper.so          linux_x11_64_debug    MonoPosixHelper.dll   version.txt   windows_32_release.exe
```
I received the same errors as previously.

Previously to this, all exports were to Linux/X11 (Runnable).  I then tried to export to Windows Desktop (Runnable).
```
Unhandled Exception:
System.IO.FileNotFoundException: Data template directory not found
  at GodotSharpTools.Editor.GodotSharpExport._ExportBegin (System.String[] features, System.Boolean debug, System.String path, System.Int32 flags) [0x000c3] in <f2a82256952b40019b74cec7788fed45>:0 
ERROR: _export_begin: Method/Function Failed.
   At: modules/mono/editor/godotsharp_export.cpp:161.
```

```
tim@komodo:~/code/godot-3d-learn$ wine winbuild.exe 
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
ERROR: initialize: The loaded API assembly is invalid
   At: modules/mono/mono_gd/gd_mono.cpp:307
ERROR: initialize: FATAL: Method/Function Failed.
   At: modules/mono/mono_gd/gd_mono.cpp:308
Stacktrace:

Memory around native instruction pointer (0000000001CF78BF):
0000000001CF78AF  00 00 00 00 48 8d 0d 7e 1e 58 00 e8 81 2f e0 fe  ....H..~.X.../..
0000000001CF78BF  0f 0b 0f 1f 44 00 00 66 2e 0f 1f 84 00 00 00 00  ....D..f........
0000000001CF78CF  00 e8 9b 78 ff ff e9 3e 8d ff ff 66 0f 1f 44 00  ...x...>...f..D.
0000000001CF78DF  00 48 8b 05 e9 bb 5b 00 48 8d 15 59 bc 57 00 48  .H....[.H..Y.W.H

=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================


abnormal program termination
```
Also, some additional information about my file paths:
```
tim@komodo:~/.config/godot$ ls
editor_settings-3.tres  projects  script_templates  text_editor_themes
tim@komodo:~/.config/godot$ ls ~/.godot
ls: cannot access '/home/tim/.godot': No such file or directory
```

As a last ditch effort, I did:
`tim@komodo:~/code/godot/godot/bin$ cp -r * ~/.local/share/godot/templates/3.1.beta.mono/`
The same errors appeared when I executed the binary, but they did not appear in the console that I had started godot from:
```
tim@komodo:~/code/godot/godot/bin$ ./godot.x11.opt.tools.64.mono 
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
Editing project: /home/tim/code/godot-3d-learn (::home::tim::code::godot-3d-learn)
OpenGL ES 3.0 Renderer: GeForce 940MX/PCIe/SSE2
tim@komodo:~/code/godot/godot/bin$ 
```

**Steps to reproduce:**
1. Compile Godot on Linux with:
```
scons p=x11 tools=yes module_mono_enabled=yes mono_glue=no
bin/godot.x11.tools.64.mono --generate-mono-glue modules/mono/glue
scons p=x11 target=release_debug tools=yes module_mono_enabled=yes mono_glue=yes
scons p=x11 target=debug tools=no module_mono_enabled=yes
scons p=x11 target=release tools=no module_mono_enabled=yes
```
2. Create a project with C# scripts.
3. Export the project with project template https://downloads.tuxfamily.org/godotengine/3.1/beta1/mono/Godot_v3.1-beta1_mono_export_templates.tpz. 

**Minimal reproduction project:**

I will make an attempt to find out if this happens with all C# scripted projects and come back with a minimum reproduction.  The project I am currently attempting to export is https://github.com/tnibert/Panzer-Deathmatch-3D-Godot.

**Comment by akien-mga** [comment]
You can't use beta1 templates with a self-compiled binary from a different commit. Editor and templates have to be built from the same source.

**Comment by tnibert** [comment]
Ah that makes sense, thank you.

For anyone with this issue in the future, I clarified looking at https://docs.godotengine.org/en/3.0/development/compiling/compiling_for_x11.html in the Building Export Templates section.  Then I ran:
```
tim@komodo:~/.local/share/godot/templates$ unlink 3.1.beta.mono
tim@komodo:~/.local/share/godot/templates$ mkdir 3.1.beta.mono/
tim@komodo:~/.local/share/godot/templates$ cp -r ~/code/godot/godot/bin/* ~/.local/share/godot/templates/3.1.beta.mono/
tim@komodo:~/.local/share/godot/templates$ cd 3.1.beta.mono/
tim@komodo:~/.local/share/godot/templates/3.1.beta.mono$ ls
data.mono.x11.64.debug    godot.x11.debug.64.mono      godot.x11.tools.64.mono
data.mono.x11.64.release  godot.x11.opt.64.mono        libmonosgen-2.0.so
GodotSharp                godot.x11.opt.tools.64.mono
tim@komodo:~/.local/share/godot/templates/3.1.beta.mono$ ln -s godot.x11.debug.64.mono linux_x11_64_debug
tim@komodo:~/.local/share/godot/templates/3.1.beta.mono$ ls
data.mono.x11.64.debug    godot.x11.debug.64.mono      godot.x11.tools.64.mono
data.mono.x11.64.release  godot.x11.opt.64.mono        libmonosgen-2.0.so
GodotSharp                godot.x11.opt.tools.64.mono  linux_x11_64_debug
tim@komodo:~/.local/share/godot/templates/3.1.beta.mono$ ln -s godot.x11.opt.64.mono linux_x11_64_release
```
All is working now :)
