### ISSUE TITLE
-fsanitize=undefined errors reported by GCC

### ISSUE THREAD

**Issue by marxin** [godotengine/godot#25218]
Building current trunk with #25178 I see following UBSAN errors when running a random godot project:
```
$ scons progress=yes verbose=yes -j8 platform=x11 target=release_debug tools=yes use_ubsan=1

UBSAN_OPTIONS="print_stacktrace=1" bin/godot.x11.opt.64s /home/marxin/Programming/godot-demo-projects/3d/truck_town/project.godot
OpenGL ES 3.0 Renderer: AMD CAICOS (DRM 2.50.0 / 4.19.12-1-default, LLVM 7.0.0)
core/pair.h:35:8: runtime error: load of value 325680032, which is not a valid value for type 'Type'
    #0 0xd8ef05 in Pair<Variant::Type, MethodInfo>::operator=(Pair<Variant::Type, MethodInfo> const&) core/pair.h:35
    #1 0xd8ef05 in Map<String, Pair<Variant::Type, MethodInfo>, Comparator<String>, DefaultAllocator>::_insert(String const&, Pair<Variant::Type, MethodInfo> const&) core/map.h:355
    #2 0xd8ef05 in Map<String, Pair<Variant::Type, MethodInfo>, Comparator<String>, DefaultAllocator>::insert(String const&, Pair<Variant::Type, MethodInfo> const&) core/map.h:567
    #3 0xd8ef05 in Map<String, Pair<Variant::Type, MethodInfo>, Comparator<String>, DefaultAllocator>::operator[](String const&) core/map.h:610
    #4 0xce5a8e in register_visual_script_nodes() modules/visual_script/visual_script_nodes.cpp:3727
    #5 0x9ce602 in register_visual_script_types() modules/visual_script/register_types.cpp:107
    #6 0x860aa0 in register_module_types() modules/register_module_types.gen.cpp:135
    #7 0x838748 in Main::setup2(unsigned long) main/main.cpp:1227
    #8 0x847aed in Main::setup(char const*, int, char**, bool) main/main.cpp:1036
    #9 0x73bce4 in main platform/x11/godot_x11.cpp:48
    #10 0x7ffff58ecfea in __libc_start_main ../csu/libc-start.c:308
    #11 0x73df89 in _start (/home/marxin/Programming/godot/bin/godot.x11.opt.64s+0x73df89)

modules/gdscript/gdscript_parser.h:47:9: runtime error: load of value 4294954432, which is not a valid value for type '._120'
    #0 0x188e3d1 in GDScriptParser::DataType::operator=(GDScriptParser::DataType const&) modules/gdscript/gdscript_parser.h:47
    #1 0x188e3d1 in GDScriptParser::ClassNode::Member::operator=(GDScriptParser::ClassNode::Member const&) modules/gdscript/gdscript_parser.h:156
    #2 0x188e3d1 in CowData<GDScriptParser::ClassNode::Member>::set(int, GDScriptParser::ClassNode::Member const&) core/cowdata.h:139
    #3 0x188e3d1 in Vector<GDScriptParser::ClassNode::Member>::set(int, GDScriptParser::ClassNode::Member const&) core/vector.h:82
    #4 0x188e3d1 in Vector<GDScriptParser::ClassNode::Member>::push_back(GDScriptParser::ClassNode::Member const&) core/vector.h:154
    #5 0x17ab3f3 in GDScriptParser::_parse_class(GDScriptParser::ClassNode*) modules/gdscript/gdscript_parser.cpp:4759
    #6 0x17d2e80 in GDScriptParser::_parse(String const&) modules/gdscript/gdscript_parser.cpp:8080
    #7 0x17d3f31 in GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*) modules/gdscript/gdscript_parser.cpp:8182
    #8 0x1521cd1 in GDScript::reload(bool) modules/gdscript/gdscript.cpp:568
    #9 0x15280c2 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2151
    #10 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #11 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #12 0x73ee3bf in ResourceInteractiveLoaderText::poll() scene/resources/scene_format_text.cpp:432
    #13 0xb16bbec in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:191
    #14 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #15 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #16 0x83e51d in Main::start() main/main.cpp:1725
    #17 0x73bcf8 in main platform/x11/godot_x11.cpp:54
    #18 0x7ffff58ecfea in __libc_start_main ../csu/libc-start.c:308
    #19 0x73df89 in _start (/home/marxin/Programming/godot/bin/godot.x11.opt.64s+0x73df89)

modules/gdscript/gdscript_function.h:45:8: runtime error: load of value 4294954320, which is not a valid value for type 'Type'
    #0 0x15d2698 in GDScriptDataType::operator=(GDScriptDataType&&) modules/gdscript/gdscript_function.h:45
    #1 0x15b87eb in GDScriptCompiler::_parse_class_level(GDScript*, GDScript*, GDScriptParser::ClassNode const*, bool) modules/gdscript/gdscript_compiler.cpp:1945
    #2 0x15c8922 in GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) modules/gdscript/gdscript_compiler.cpp:2203
    #3 0x152209e in GDScript::reload(bool) modules/gdscript/gdscript.cpp:580
    #4 0x15280c2 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2151
    #5 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #6 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #7 0x73ee3bf in ResourceInteractiveLoaderText::poll() scene/resources/scene_format_text.cpp:432
    #8 0xb16bbec in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:191
    #9 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #10 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #11 0x83e51d in Main::start() main/main.cpp:1725
    #12 0x73bcf8 in main platform/x11/godot_x11.cpp:54
    #13 0x7ffff58ecfea in __libc_start_main ../csu/libc-start.c:308
    #14 0x73df89 in _start (/home/marxin/Programming/godot/bin/godot.x11.opt.64s+0x73df89)

modules/gdscript/gdscript_function.h:45:8: runtime error: load of value 4294954320, which is not a valid value for type 'Type'
    #0 0x15d3783 in GDScriptDataType::operator=(GDScriptDataType const&) modules/gdscript/gdscript_function.h:45
    #1 0x15d3783 in GDScript::MemberInfo::operator=(GDScript::MemberInfo const&) modules/gdscript/gdscript.h:62
    #2 0x15b9239 in GDScriptCompiler::_parse_class_level(GDScript*, GDScript*, GDScriptParser::ClassNode const*, bool) modules/gdscript/gdscript_compiler.cpp:1970
    #3 0x15c8922 in GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) modules/gdscript/gdscript_compiler.cpp:2203
    #4 0x152209e in GDScript::reload(bool) modules/gdscript/gdscript.cpp:580
    #5 0x15280c2 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2151
    #6 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #7 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #8 0x73ee3bf in ResourceInteractiveLoaderText::poll() scene/resources/scene_format_text.cpp:432
    #9 0xb16bbec in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:191
    #10 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #11 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #12 0x83e51d in Main::start() main/main.cpp:1725
    #13 0x73bcf8 in main platform/x11/godot_x11.cpp:54
    #14 0x7ffff58ecfea in __libc_start_main ../csu/libc-start.c:308
    #15 0x73df89 in _start (/home/marxin/Programming/godot/bin/godot.x11.opt.64s+0x73df89)

modules/gdscript/gdscript_parser.h:47:9: runtime error: load of value 1230262853, which is not a valid value for type '._124'
    #0 0x15d2e62 in GDScriptParser::DataType::DataType(GDScriptParser::DataType const&) modules/gdscript/gdscript_parser.h:47
    #1 0x15d3554 in GDScriptParser::IdentifierNode::get_datatype() const modules/gdscript/gdscript_parser.h:270
    #2 0x1572a61 in GDScriptCompiler::_parse_expression(GDScriptCompiler::CodeGen&, GDScriptParser::Node const*, int, bool, bool) modules/gdscript/gdscript_compiler.cpp:1152
    #3 0x159b94a in GDScriptCompiler::_parse_block(GDScriptCompiler::CodeGen&, GDScriptParser::BlockNode const*, int, int, int) modules/gdscript/gdscript_compiler.cpp:1596
    #4 0x15a774e in GDScriptCompiler::_parse_function(GDScript*, GDScriptParser::ClassNode const*, GDScriptParser::FunctionNode const*, bool) modules/gdscript/gdscript_compiler.cpp:1690
    #5 0x15af67c in GDScriptCompiler::_parse_class_blocks(GDScript*, GDScriptParser::ClassNode const*, bool) modules/gdscript/gdscript_compiler.cpp:2069
    #6 0x15c8969 in GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) modules/gdscript/gdscript_compiler.cpp:2208
    #7 0x152209e in GDScript::reload(bool) modules/gdscript/gdscript.cpp:580
    #8 0x15280c2 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2151
    #9 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #10 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #11 0x73ee3bf in ResourceInteractiveLoaderText::poll() scene/resources/scene_format_text.cpp:432
    #12 0xb16bbec in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:191
    #13 0xb168646 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:266
    #14 0xb168646 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:328
    #15 0x83e51d in Main::start() main/main.cpp:1725
    #16 0x73bcf8 in main platform/x11/godot_x11.cpp:54
    #17 0x7ffff58ecfea in __libc_start_main ../csu/libc-start.c:308
    #18 0x73df89 in _start (/home/marxin/Programming/godot/bin/godot.x11.opt.64s+0x73df89)
```

**Comment by hpvb** [comment]
```core/pair.h:35:8: runtime error: load of value 325680032, which is not a valid value for type 'Type'```
is a false positive really. The issue is that for Map<key, value> on Map[key] we create an entry in the map with a default-constructed value which we then return for overwriting. The value never actually gets used its just not initialized. Not sure if that's worth fixing. We can probably do something a bit better though.
