### ISSUE TITLE
update_bitmask_area function will cause game randomly crash

### ISSUE THREAD

**Issue by Jackn1fe** [godotengine/godot#25504]
**Godot version:**

Godot v3.0.6-stable and 3.1 beta3

**OS/device including version:**

Microsoft Windows 10  10.0.17134 Build 17134

**Issue description:**

when call the update_bitmask_area() function a few times(even nothing has changed), the game will freeze and crash without any error in editor's console, but error in console:
ERROR: operator[]: FATAL: Index p_index=1 out of size (size()=1)
   At: core/list.h:454
Nothing read: No such file or directory

**Steps to reproduce:**
Open the project below and run it, the problem will appear in few mintues.

**Minimal reproduction project:**

[crash.zip](https://github.com/godotengine/godot/files/2816294/crash.zip)

**Comment by qarmin** [comment]
Backtrace:
```
[0] List<Vector2,DefaultAllocator>::operator[] (c:\pr\godot\core\list.h:454)
[1] List<Vector2,DefaultAllocator>::operator[] (c:\pr\godot\core\list.h:454)
[2] TileSet::autotile_get_subtile_for_bitmask (c:\pr\godot\scene\resources\tile_set.cpp:617)
[3] TileMap::update_cell_bitmask (c:\pr\godot\scene\2d\tile_map.cpp:900)
[4] TileMap::update_bitmask_area (c:\pr\godot\scene\2d\tile_map.cpp:812)
[5] MethodBind1<TileMap,Vector2 const &>::call (c:\pr\godot\core\method_bind.gen.inc:815)
[6] Object::call (c:\pr\godot\core\object.cpp:945)
[7] Variant::call_ptr (c:\pr\godot\core\variant_call.cpp:1049)
[8] GDScriptFunction::call (c:\pr\godot\modules\gdscript\gdscript_function.cpp:1073)
[9] GDScriptInstance::call_multilevel (c:\pr\godot\modules\gdscript\gdscript.cpp:1190)
[10] Node::_notification (c:\pr\godot\scene\main\node.cpp:54)
[11] Node::_notificationv (c:\pr\godot\scene\main\node.h:46)
[12] CanvasItem::_notificationv (c:\pr\godot\scene\2d\canvas_item.h:166)
[13] Node2D::_notificationv (c:\pr\godot\scene\2d\node_2d.h:38)
[14] TileMap::_notificationv (c:\pr\godot\scene\2d\tile_map.h:42)
[15] Object::notification (c:\pr\godot\core\object.cpp:957)
[16] SceneTree::_notify_group_pause (c:\pr\godot\scene\main\scene_tree.cpp:971)
[17] SceneTree::idle (c:\pr\godot\scene\main\scene_tree.cpp:518)
[18] Main::iteration (c:\pr\godot\main\main.cpp:1877)
[19] OS_Windows::run (c:\pr\godot\platform\windows\os_windows.cpp:2780)
[20] widechar_main (c:\pr\godot\platform\windows\godot_win.cpp:150)
[21] _main (c:\pr\godot\platform\windows\godot_win.cpp:172)
[22] main (c:\pr\godot\platform\windows\godot_win.cpp:184)
[23] __scrt_common_main_seh (d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[24] BaseThreadInitThunk
```

**Comment by bojidar-bg** [comment]
(Meh, fastest gun in the west problem)
Could reproduce on 35bb52011a4cbcd8ca3779ab1761244f06a33127, after ~6 minutes.

Backtrace from GDB:
```
#0  0x00000000025f6e4e in List<Vector2, DefaultAllocator>::operator[] (this=0x7fffffffaef0, p_index=1) at ./core/list.h:454
#1  0x000000000380e9e3 in TileSet::autotile_get_subtile_for_bitmask (this=0x6531c20, p_id=0, p_bitmask=511, p_tilemap_node=0x65a4970, 
    p_tile_location=...) at scene/resources/tile_set.cpp:617
#2  0x000000000339ba41 in TileMap::update_cell_bitmask (this=0x65a4970, p_x=6, p_y=1) at scene/2d/tile_map.cpp:899
#3  0x000000000339acbf in TileMap::update_bitmask_area (this=0x65a4970, p_pos=...) at scene/2d/tile_map.cpp:811
#4  0x00000000033bdf90 in MethodBind1<TileMap, Vector2 const&>::call (this=0x60396a0, p_object=0x65a4970, p_args=0x7fffffffb6a8, p_arg_count=1, 
    r_error=...) at ./core/method_bind.gen.inc:815
#5  0x0000000003da718e in Object::call (this=0x65a4970, p_method=..., p_args=0x7fffffffb6a8, p_argcount=1, r_error=...) at core/object.cpp:945
#6  0x0000000003e6f3c7 in Variant::call_ptr (this=0x7fffffffd1c0, p_method=..., p_args=0x7fffffffb6a8, p_argcount=1, r_ret=0x0, r_error=...) at core/variant_call.cpp:1049
#7  0x00000000015d6880 in GDScriptFunction::call (this=0x5b61c40, p_instance=0x65360f0, p_args=0x7fffffffd438, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:1070
#8  0x00000000015706aa in GDScriptInstance::call_multilevel (this=0x65360f0, p_method=..., p_args=0x7fffffffd438, p_argcount=1) at modules/gdscript/gdscript.cpp:1190
#9  0x0000000002bf68c6 in Node::_notification (this=0x65a4970, p_notification=17) at scene/main/node.cpp:54
#10 0x000000000152dc17 in Node::_notificationv (this=0x65a4970, p_notification=17, p_reversed=false) at ./scene/main/node.h:46
#11 0x000000000152dae0 in CanvasItem::_notificationv (this=0x65a4970, p_notification=17, p_reversed=false) at ./scene/2d/canvas_item.h:166
#12 0x00000000031e5060 in Node2D::_notificationv (this=0x65a4970, p_notification=17, p_reversed=false) at ./scene/2d/node_2d.h:38
#13 0x00000000033a86e0 in TileMap::_notificationv (this=0x65a4970, p_notification=17, p_reversed=false) at scene/2d/tile_map.h:42
#14 0x0000000003da320f in Object::notification (this=0x65a4970, p_notification=17, p_reversed=false) at core/object.cpp:955
#15 0x0000000002c36b15 in SceneTree::_notify_group_pause (this=0x63b6390, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:969
#16 0x0000000002c36f24 in SceneTree::idle (this=0x63b6390, p_time=0.038333334) at scene/main/scene_tree.cpp:518
#17 0x00000000014cb591 in Main::iteration () at main/main.cpp:1876
#18 0x00000000014931ae in OS_X11::run (this=0x7fffffffdce8) at platform/x11/os_x11.cpp:2975
#19 0x0000000001482471 in main (argc=1, argv=0x7fffffffe448) at platform/x11/godot_x11.cpp:55
```
