### ISSUE TITLE
scene/gui/graph_edit.cpp:265:26: runtime error: member call on address 0x00001fa01660 which does not point to an object of type 'Object' with use_ubsan=1

### ISSUE THREAD

**Issue by marxin** [godotengine/godot#25644]
Using latest master, one can see an error during closing of a project:

```
$ godot.x11.tools.64s ./2d/physics_platformer/*.godot
...
[close the editor]
scene/gui/graph_edit.cpp:265:26: runtime error: member call on address 0x00001fa01660 which does not point to an object of type 'Object'
0x00001fa01660: note: object has invalid vptr
 84 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x82902b7 in GraphEdit::remove_child_notify(Node*) scene/gui/graph_edit.cpp:265
    #1 0x7d0444c in Node::remove_child(Node*) scene/main/node.cpp:1264
    #2 0x7d0696f in Node::_notification(int) scene/main/node.cpp:161
    #3 0x8307f18 in Node::_notificationv(int, bool) scene/main/node.h:46
    #4 0x8307f18 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #5 0x8307f18 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #6 0x8307f18 in GraphEdit::_notificationv(int, bool) scene/gui/graph_edit.h:58
    #7 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #8 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #9 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #10 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #11 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #12 0x5b6a978 in Node::_notificationv(int, bool) scene/main/node.h:46
    #13 0x5b6a978 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #14 0x5b6a978 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #15 0x5b6a978 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #16 0x5b6a978 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #17 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #18 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #19 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #20 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #21 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #22 0x853936e in Node::_notificationv(int, bool) scene/main/node.h:46
    #23 0x853936e in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #24 0x853936e in Control::_notificationv(int, bool) scene/gui/control.h:51
    #25 0x853936e in Container::_notificationv(int, bool) scene/gui/container.h:38
    #26 0x853936e in PanelContainer::_notificationv(int, bool) scene/gui/panel_container.h:38
    #27 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #28 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #29 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #30 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #31 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #32 0x5b6a978 in Node::_notificationv(int, bool) scene/main/node.h:46
    #33 0x5b6a978 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #34 0x5b6a978 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #35 0x5b6a978 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #36 0x5b6a978 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #37 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #38 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #39 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #40 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #41 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #42 0xd12a67 in Node::_notificationv(int, bool) scene/main/node.h:46
    #43 0xd12a67 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #44 0xd12a67 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #45 0xd12a67 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #46 0xd12a67 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #47 0xd12a67 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:81
    #48 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #49 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #50 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #51 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #52 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #53 0x853936e in Node::_notificationv(int, bool) scene/main/node.h:46
    #54 0x853936e in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #55 0x853936e in Control::_notificationv(int, bool) scene/gui/control.h:51
    #56 0x853936e in Container::_notificationv(int, bool) scene/gui/container.h:38
    #57 0x853936e in PanelContainer::_notificationv(int, bool) scene/gui/panel_container.h:38
    #58 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #59 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #60 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #61 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #62 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #63 0x17d3907 in Node::_notificationv(int, bool) scene/main/node.h:46
    #64 0x17d3907 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #65 0x17d3907 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #66 0x17d3907 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #67 0x17d3907 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #68 0x17d3907 in VSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:99
    #69 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #70 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #71 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #72 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #73 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #74 0xd12a67 in Node::_notificationv(int, bool) scene/main/node.h:46
    #75 0xd12a67 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #76 0xd12a67 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #77 0xd12a67 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #78 0xd12a67 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #79 0xd12a67 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:81
    #80 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #81 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #82 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #83 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #84 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #85 0x519dea7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #86 0x519dea7 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #87 0x519dea7 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #88 0x519dea7 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #89 0x519dea7 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #90 0x519dea7 in HSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:90
    #91 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #92 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #93 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #94 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #95 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #96 0x519dea7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #97 0x519dea7 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #98 0x519dea7 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #99 0x519dea7 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #100 0x519dea7 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #101 0x519dea7 in HSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:90
    #102 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #103 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #104 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #105 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #106 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #107 0x519dea7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #108 0x519dea7 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #109 0x519dea7 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #110 0x519dea7 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #111 0x519dea7 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #112 0x519dea7 in HSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:90
    #113 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #114 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #115 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #116 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #117 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #118 0xd12a67 in Node::_notificationv(int, bool) scene/main/node.h:46
    #119 0xd12a67 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #120 0xd12a67 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #121 0xd12a67 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #122 0xd12a67 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #123 0xd12a67 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:81
    #124 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #125 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #126 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #127 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #128 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #129 0x8533e98 in Node::_notificationv(int, bool) scene/main/node.h:46
    #130 0x8533e98 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #131 0x8533e98 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #132 0x8533e98 in Panel::_notificationv(int, bool) scene/gui/panel.h:40
    #133 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #134 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #135 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #136 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #137 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #138 0xd3a992 in Node::_notificationv(int, bool) scene/main/node.h:46
    #139 0xd3a992 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #140 0xd3a992 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #141 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #142 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #143 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #144 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #145 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #146 0x5732735 in Node::_notificationv(int, bool) scene/main/node.h:46
    #147 0x5732735 in EditorNode::_notificationv(int, bool) editor/editor_node.h:100
    #148 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #149 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #150 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #151 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #152 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #153 0x7fcf4b5 in Node::_notificationv(int, bool) scene/main/node.h:46
    #154 0x7fcf4b5 in Viewport::_notificationv(int, bool) scene/main/viewport.h:94
    #155 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #156 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #157 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #158 0x7e30140 in void memdelete<Viewport>(Viewport*) core/os/memory.h:117
    #159 0x7e30140 in SceneTree::finish() scene/main/scene_tree.cpp:612
    #160 0x9ae040 in main platform/x11/godot_x11.cpp:55
    #161 0x7f8416012fea in __libc_start_main (/lib64/libc.so.6+0x22fea)
    #162 0x9b0499 in _start (/tmp/godot.x11.tools.64s+0x9b0499)

core/message_queue.cpp:157:44: runtime error: member call on address 0x00001fa01660 which does not point to an object of type 'Object'
0x00001fa01660: note: object has invalid vptr
 84 7f 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0xdfea27f in MessageQueue::push_call(Object*, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/message_queue.cpp:157
    #1 0xe014e1a in Object::call_deferred(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1785
    #2 0x828fffe in GraphEdit::remove_child_notify(Node*) scene/gui/graph_edit.cpp:265
    #3 0x7d0444c in Node::remove_child(Node*) scene/main/node.cpp:1264
    #4 0x7d0696f in Node::_notification(int) scene/main/node.cpp:161
    #5 0x8307f18 in Node::_notificationv(int, bool) scene/main/node.h:46
    #6 0x8307f18 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #7 0x8307f18 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #8 0x8307f18 in GraphEdit::_notificationv(int, bool) scene/gui/graph_edit.h:58
    #9 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #10 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #11 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #12 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #13 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #14 0x5b6a978 in Node::_notificationv(int, bool) scene/main/node.h:46
    #15 0x5b6a978 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #16 0x5b6a978 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #17 0x5b6a978 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #18 0x5b6a978 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #19 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #20 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #21 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #22 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #23 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #24 0x853936e in Node::_notificationv(int, bool) scene/main/node.h:46
    #25 0x853936e in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #26 0x853936e in Control::_notificationv(int, bool) scene/gui/control.h:51
    #27 0x853936e in Container::_notificationv(int, bool) scene/gui/container.h:38
    #28 0x853936e in PanelContainer::_notificationv(int, bool) scene/gui/panel_container.h:38
    #29 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #30 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #31 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #32 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #33 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #34 0x5b6a978 in Node::_notificationv(int, bool) scene/main/node.h:46
    #35 0x5b6a978 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #36 0x5b6a978 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #37 0x5b6a978 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #38 0x5b6a978 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #39 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #40 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #41 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #42 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #43 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #44 0xd12a67 in Node::_notificationv(int, bool) scene/main/node.h:46
    #45 0xd12a67 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #46 0xd12a67 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #47 0xd12a67 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #48 0xd12a67 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #49 0xd12a67 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:81
    #50 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #51 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #52 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #53 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #54 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #55 0x853936e in Node::_notificationv(int, bool) scene/main/node.h:46
    #56 0x853936e in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #57 0x853936e in Control::_notificationv(int, bool) scene/gui/control.h:51
    #58 0x853936e in Container::_notificationv(int, bool) scene/gui/container.h:38
    #59 0x853936e in PanelContainer::_notificationv(int, bool) scene/gui/panel_container.h:38
    #60 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #61 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #62 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #63 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #64 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #65 0x17d3907 in Node::_notificationv(int, bool) scene/main/node.h:46
    #66 0x17d3907 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #67 0x17d3907 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #68 0x17d3907 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #69 0x17d3907 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #70 0x17d3907 in VSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:99
    #71 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #72 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #73 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #74 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #75 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #76 0xd12a67 in Node::_notificationv(int, bool) scene/main/node.h:46
    #77 0xd12a67 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #78 0xd12a67 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #79 0xd12a67 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #80 0xd12a67 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #81 0xd12a67 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:81
    #82 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #83 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #84 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #85 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #86 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #87 0x519dea7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #88 0x519dea7 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #89 0x519dea7 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #90 0x519dea7 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #91 0x519dea7 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #92 0x519dea7 in HSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:90
    #93 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #94 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #95 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #96 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #97 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #98 0x519dea7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #99 0x519dea7 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #100 0x519dea7 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #101 0x519dea7 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #102 0x519dea7 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #103 0x519dea7 in HSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:90
    #104 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #105 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #106 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #107 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #108 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #109 0x519dea7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #110 0x519dea7 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #111 0x519dea7 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #112 0x519dea7 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #113 0x519dea7 in SplitContainer::_notificationv(int, bool) scene/gui/split_container.h:38
    #114 0x519dea7 in HSplitContainer::_notificationv(int, bool) scene/gui/split_container.h:90
    #115 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #116 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #117 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #118 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #119 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #120 0xd12a67 in Node::_notificationv(int, bool) scene/main/node.h:46
    #121 0xd12a67 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #122 0xd12a67 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #123 0xd12a67 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #124 0xd12a67 in BoxContainer::_notificationv(int, bool) scene/gui/box_container.h:38
    #125 0xd12a67 in VBoxContainer::_notificationv(int, bool) scene/gui/box_container.h:81
    #126 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #127 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #128 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #129 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #130 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #131 0x8533e98 in Node::_notificationv(int, bool) scene/main/node.h:46
    #132 0x8533e98 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #133 0x8533e98 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #134 0x8533e98 in Panel::_notificationv(int, bool) scene/gui/panel.h:40
    #135 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #136 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #137 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #138 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #139 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #140 0xd3a992 in Node::_notificationv(int, bool) scene/main/node.h:46
    #141 0xd3a992 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #142 0xd3a992 in Control::_notificationv(int, bool) scene/gui/control.h:51
    #143 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #144 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #145 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #146 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #147 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #148 0x5732735 in Node::_notificationv(int, bool) scene/main/node.h:46
    #149 0x5732735 in EditorNode::_notificationv(int, bool) editor/editor_node.h:100
    #150 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #151 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #152 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #153 0x17d5c4b in void memdelete<Node>(Node*) core/os/memory.h:117
    #154 0x7d06977 in Node::_notification(int) scene/main/node.cpp:162
    #155 0x7fcf4b5 in Node::_notificationv(int, bool) scene/main/node.h:46
    #156 0x7fcf4b5 in Viewport::_notificationv(int, bool) scene/main/viewport.h:94
    #157 0xe00781c in Object::notification(int, bool) core/object.cpp:955
    #158 0xe016ca0 in Object::_predelete() core/object.cpp:386
    #159 0xe016ca0 in predelete_handler(Object*) core/object.cpp:1999
    #160 0x7e30140 in void memdelete<Viewport>(Viewport*) core/os/memory.h:117
    #161 0x7e30140 in SceneTree::finish() scene/main/scene_tree.cpp:612
    #162 0x9ae040 in main platform/x11/godot_x11.cpp:55
    #163 0x7f8416012fea in __libc_start_main (/lib64/libc.so.6+0x22fea)
    #164 0x9b0499 in _start (/tmp/godot.x11.tools.64s+0x9b0499)
````

**Comment by qarmin** [comment]
I can't reproduce this on master with ubsan

**Comment by marxin** [comment]
Yes, I can confirm that it's fixed.
