### ISSUE TITLE
3D meshes do not render on Samsung Galaxy S3 (Mali-400) with GLES2 unless a Sprite3D is in the scene

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#26303]
**Godot version:**
84b3d44 (from #26299) (applications don't even render anything on this phone prior to this PR)

**OS/device including version:**
Samsung Galaxy S3
GPU ARM Mali-400 MP4
Running LineageOS 14.1 / Android 7.1.2

**Issue description:**
When running the attached demo using GLES2, I see only text and not the 3D untextured meshes.
Here's how it looks like on desktop or on my higher end phone:
![screenshot_20190226_122256](https://user-images.githubusercontent.com/4701338/53409472-41fbc080-39c1-11e9-8f0a-8bdbe744af6b.png)

Note: I haven't investigated yet whether the issue is with any 3D mesh, or due to the combination of 3D in 2D via subviewports.

**Steps to reproduce:**
- Download attached demo
- Export it on an affected Android device (debug build), run it

**Minimal reproduction project:**
[multitouch_cubes.zip](https://github.com/godotengine/godot/files/2905175/multitouch_cubes.zip)

**Comment by akien-mga** [comment]
> Note: I haven't investigated yet whether the issue is with any 3D mesh, or due to the combination of 3D in 2D via subviewports.

Confirmed that it seems to be with anything 3D, if I modify the attached project to use `CubeScene.tscn` as the main scene, I get a black screen on the Samsung Galaxy S3. Even if I remove the WorldEnvironment completely.

**Comment by akien-mga** [comment]
Nothing relevant in `adb logcat`:
```
02-26 12:32:33.238 21232 21248 I godot   : Android modules: Nothing to load, aborting
02-26 12:32:33.243 21232 21249 E         : Device driver API match
02-26 12:32:33.243 21232 21249 E         : Device driver API version: 29
02-26 12:32:33.243 21232 21249 E         : User space API version: 29 
02-26 12:32:33.243 21232 21249 E         : mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Tue Jul 22 19:59:34 KST 2014 
02-26 12:32:33.250 21232 21249 I OpenGLRenderer: Initialized EGL, version 1.4
02-26 12:32:33.250 21232 21249 D OpenGLRenderer: Swap behavior 1
02-26 12:32:33.310 21232 21248 W GodotView: creating OpenGL ES 2.0 context :
02-26 12:32:33.373  2362  2396 I ActivityManager: Displayed org.godotengine.interactivecubes/org.godotengine.godot.Godot: +1s394ms
02-26 12:32:33.464 21282 21282 W IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
02-26 12:32:33.609  2503  2503 I Choreographer: Skipped 69 frames!  The application may be doing too much work on its main thread.
02-26 12:32:33.633 21232 21243 I art     : Background sticky concurrent mark sweep GC freed 18869(802KB) AllocSpace objects, 0(0B) LOS objects, 54% free, 3MB/6MB, paused 1.638ms total 265.715ms
02-26 12:32:33.756 21232 21248 I godot   : OpenGL ES 2.0 Renderer: Mali-400 MP
02-26 12:32:34.229 21232 21248 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
02-26 12:32:34.233  2016  1078 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000104) and output flags (00000002)
02-26 12:32:34.240 21232 21248 D AudioTrack: Client defaulted notificationFrames to 1056 for frameCount 6348
02-26 12:32:34.244  2016  2145 D audio_hw_primary: select_output_device: AUDIO_DEVICE_OUT_SPEAKER
02-26 12:32:34.523  2362  2396 I art     : Starting a blocking GC Explicit
02-26 12:32:34.709  2362  2396 I art     : Explicit concurrent mark sweep GC freed 50119(3MB) AllocSpace objects, 3(60KB) LOS objects, 33% free, 16MB/24MB, paused 2.493ms total 177.462ms
02-26 12:32:34.828  2016  2145 I AudioFlinger: BUFFER TIMEOUT: remove(4096) from active list on thread 0x414031c0
02-26 12:32:34.879 21232 21265 E AudioTrack: did not receive expected priority boost on time
02-26 12:32:34.879 21232 21265 W AudioTrack: releaseBuffer() track 0x42c2e400 disabled due to previous underrun, restarting
```

**Comment by akien-mga** [comment]
Still running `CubeScene.tscn` directly, I enabled "Debug OpenGL" in the preset, and now the game crashes instantly on start, with this `adb logcat` output:
```
02-26 12:36:32.112  2362  2758 I ActivityManager: Start proc 21491:org.godotengine.interactivecubes/u0a104 for activity org.godotengine.interactivecubes/org.godotengine.godot.Godot
02-26 12:36:32.136 21491 21491 I art     : Late-enabling -Xcheck:jni
02-26 12:36:32.481  2362 30888 I ActivityManager: Config changes=480 {1.0 238mcc6mnc [en_GB,da_DK,de_DE,fr_FR] ldltr sw360dp w640dp h336dp 320dpi nrml long land finger -keyb/v/h -nav/h s.51}
02-26 12:36:32.588  2362 30888 W ActivityManager: Slow operation: 417ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
02-26 12:36:32.588  2362  2396 W art     : Long monitor contention with owner Binder:2362_1C (30888) at void com.android.server.am.ActivityManagerService.attachApplication(android.app.IApplicationThread)(ActivityManagerService.java:6882) waiters=0 in void com.android.server.am.ActivityManagerService$LocalService.notifyAppTransitionCancelled() for 406ms
02-26 12:36:32.600  2362  2443 I InputReader: Reconfiguring input devices.  changes=0x00000004
02-26 12:36:32.601  2362  2443 I InputReader: Device reconfigured: id=11, name='sec_touchscreen', size 720x1280, orientation 1, mode 1, display id 0
02-26 12:36:32.602  2362  2443 I InputReader: Reconfiguring input devices.  changes=0x00000004
02-26 12:36:32.647 21491 21506 D libEGL  : loaded /system/lib/egl/libEGL_mali.so
02-26 12:36:32.664 21491 21506 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_mali.so
02-26 12:36:32.800 21491 21506 D libEGL  : loaded /system/lib/egl/libGLESv2_mali.so
02-26 12:36:32.928 21491 21510 E         : Device driver API match
02-26 12:36:32.928 21491 21510 E         : Device driver API version: 29
02-26 12:36:32.928 21491 21510 E         : User space API version: 29 
02-26 12:36:32.928 21491 21510 E         : mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Tue Jul 22 19:59:34 KST 2014 
02-26 12:36:32.954 21491 21510 I OpenGLRenderer: Initialized EGL, version 1.4
02-26 12:36:32.954 21491 21510 D OpenGLRenderer: Swap behavior 1
02-26 12:36:33.006  2362  2536 I WindowManager: setAppOrientation token: Token{73e01e6 ActivityRecord{6e28841 u0 org.godotengine.interactivecubes/org.godotengine.godot.Godot t1513}} requestedOrientation: 0
02-26 12:36:33.009 21491 21509 I godot   : Android modules: Nothing to load, aborting
02-26 12:36:33.013 21491 21509 W GodotView: creating OpenGL ES 2.0 context :
02-26 12:36:33.014 21491 21509 E GodotView: After eglCreateContext: EGL error: 0x3004
02-26 12:36:33.017 21491 21509 E AndroidRuntime: FATAL EXCEPTION: GLThread 2615
02-26 12:36:33.017 21491 21509 E AndroidRuntime: Process: org.godotengine.interactivecubes, PID: 21491
02-26 12:36:33.017 21491 21509 E AndroidRuntime: java.lang.RuntimeException: createContext failed: EGL_SUCCESS
02-26 12:36:33.017 21491 21509 E AndroidRuntime: 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1211)
02-26 12:36:33.017 21491 21509 E AndroidRuntime: 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1202)
02-26 12:36:33.017 21491 21509 E AndroidRuntime: 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1052)
02-26 12:36:33.017 21491 21509 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1412)
02-26 12:36:33.017 21491 21509 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
02-26 12:36:33.029  2362 32284 W ActivityManager:   Force finishing activity org.godotengine.interactivecubes/org.godotengine.godot.Godot
02-26 12:36:33.129  2362  2396 I WindowManager: Screen frozen for +952ms due to Window{41efe79 u0 Starting org.godotengine.interactivecubes}
02-26 12:36:33.197  2362 11564 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@21a74da (uid=10104 pid=21491)
02-26 12:36:33.200  2362 20095 I OpenGLRenderer: Initialized EGL, version 1.4
02-26 12:36:33.200  2362 20095 D OpenGLRenderer: Swap behavior 1
```

**Comment by hpvb** [comment]
That is `EGL_BAD_ATTRIBUTE 0x3004`

**Comment by akien-mga** [comment]
Thanks!

For the reference, it's still valid in 8889089c (to rule out a potential issue in my own unmerged patch 84b3d44).

**Comment by reduz** [comment]
does it still happen?

**Comment by akien-mga** [comment]
Tested on 41708eb8 and it's worse now, I get a black screen again.

057d3e87 regressed and #24952 is broken again.

**Comment by akien-mga** [comment]
I tested with 41708eb + a local revert of 057d3e8 that broke rendering, and I can confirm that this issue is still valid (text and clear color work, 3D meshes don't).

**Comment by akien-mga** [comment]
Still reproducible in 834a984b with the project in OP.

**Comment by akien-mga** [comment]
Did some more testing by focusing on the `CubeScene.tscn`. In the OP's MRP, it doesn't render at all on my Samsung S3.

I tried to modify it a bit, changing/removing the WorldEnvironment, but that didn't fix it.

Then I added a Sprite3D to the scene and tadaa... both the Sprite3D and the MeshInstance become visible. So it sounds like Sprite3D triggers a code branch that makes the MeshInstance visible.

Updated MRP: [multitouch_cubes.zip](https://github.com/godotengine/godot/files/2921347/multitouch_cubes.zip)
Exported as is, the main scene renders fine. Delete the Sprite3D, reexport and then the cube doesn't render anymore.

**Comment by clayjohn** [comment]
Can you still reproduce this given all the changes to the GLES2 backend since this was made?

**Comment by akien-mga** [comment]
Mixed results... by default I get a black screen, but toying a bit with the WorldEnvironment I can now get the cubes to display without having to add a Sprite3D.

It seems like Background Mode "Clear Color" and "Custom Color" trigger a black screen (even with non-black custom color) which hampers testing this issue, but if I use a ProceduralSky or Canvas mode it seems to work fine.

I'll do more tests and open a new issue for the Bg Mode bugs.
