### ISSUE TITLE
windows 10 build error - [mingw gcc]

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#2690]
There is a build error as well using the mingw on windows. It stops on a module error. Using the current source code.

```
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.
- gcc detected.
scons: done reading SConscript files.
scons: Building targets ...
g++ -o platform\windows\godot_win.windows.tools.32.o -c -g -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DWINDOWS_ENABLED -mwindows -DGLES2_ENABLED -DGLEW_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DRTAUDIO_ENABLED -DMINGW_ENABLED -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math -Itools -Idrivers -I. -Iplatform\windows -Itools\freetype -Itools\freetype\freetype\include -Idrivers\builtin_openssl2 -Idrivers\builtin_zlib\zlib -Iplatform\windows\vorbis -Idrivers\builtin_openssl2\crypto -Idrivers\builtin_openssl2\openssl -Idrivers\builtin_openssl2\crypto\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_openssl2\crypto\modes -Idrivers\opus\silk\float -Idrivers\opus -Idrivers\opus\celt -Idrivers\opus\silk -Idrivers\opus\silk\float platform\windows\godot_win.cpp
scons: *** [platform\windows\godot_win.windows.tools.32.o] AttributeError : 'module' object has no attribute 'STARTF_USESHOWWINDOW'
Traceback (most recent call last):
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Taskmaster.py", line 248, in execute
    self.targets[0].build()
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Node\__init__.py", line 739, in build
    self.get_executor()(self, **kw)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Action.py", line 907, in __call__
    show, execute, chdir, executor)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Action.py", line 975, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Action.py", line 584, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.4.0\SCons\Action.py", line 807, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "./platform/windows\detect.py", line 283, in mySpawn
    rv = mySubProcess( cmdline, env )
  File "./platform/windows\detect.py", line 259, in mySubProcess
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Can someone else reproduce this issue on Windows 10 with mingw?

**Comment by vnen** [comment]
I was never able to install Mingw on Windows. I might try this later.

**Comment by reduz** [comment]
There are plenty of different errors using mingw on Win10. I honestly don't know what to do about it as they all seem really strange. I'm used to MSVC on Windows which works well, so not sure how to fix these..

**Comment by carlosmarti** [comment]
Why not remove mingw for Win10 and continue to use MSVC since that is working best for windows?

**Comment by reduz** [comment]
this is fixed now, but to avoid the error in the OP, upgrade python 2.7 version
