### ISSUE TITLE
[Android] deploys empy project but no current game project

### ISSUE THREAD

**Issue by gggiiia** [godotengine/godot#27691]
**Godot version:**
3.1

**OS/device including version:**

OS: Android 8.1.0
Device: Xiaomi MI A2

**Issue description:**
when deploing an empty scene to the device all works.
Whit my project there is some issue and the procedure do not work properly, log:

``` 
ADDING: AndroidManifest.xml
ADDING: META-INF/MANIFEST.MF
ADDING: META-INF/android.arch.core_runtime.version
ADDING: META-INF/android.arch.lifecycle_livedata-core.version
ADDING: META-INF/android.arch.lifecycle_livedata.version
ADDING: META-INF/android.arch.lifecycle_runtime.version
ADDING: META-INF/android.arch.lifecycle_viewmodel.version
ADDING: META-INF/androidx.core_core.version
ADDING: META-INF/androidx.documentfile_documentfile.version
ADDING: META-INF/androidx.legacy_legacy-support-core-utils.version
ADDING: META-INF/androidx.loader_loader.version
ADDING: META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version
ADDING: META-INF/androidx.print_print.version
ADDING: META-INF/androidx.versionedparcelable_versionedparcelable.version
ADDING: META-INF/proguard/androidx-annotations.pro
ADDING: classes.dex
ADDING: lib/arm64-v8a/libc++_shared.so
ADDING: lib/arm64-v8a/libgodot_android.so
ADDING: lib/armeabi-v7a/libc++_shared.so
ADDING: lib/armeabi-v7a/libgodot_android.so
ADDING: res/drawable-hdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-hdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-mdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-nodpi-v4/icon.png
ADDING: res/drawable-v21/notification_action_background.xml
ADDING: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal.9.png
ADDING: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png
ADDING: res/drawable-xhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable-xxhdpi-v4/notify_panel_notification_icon_bg.png
ADDING: res/drawable/notification_bg.xml
ADDING: res/drawable/notification_bg_low.xml
ADDING: res/drawable/notification_icon_background.xml
ADDING: res/drawable/notification_tile_bg.xml
ADDING: res/layout-v16/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_action.xml
ADDING: res/layout-v21/notification_action_tombstone.xml
ADDING: res/layout-v21/notification_template_custom_big.xml
ADDING: res/layout-v21/notification_template_icon_group.xml
ADDING: res/layout/downloading_expansion.xml
ADDING: res/layout/notification_action.xml
ADDING: res/layout/notification_action_tombstone.xml
ADDING: res/layout/notification_template_icon_group.xml
ADDING: res/layout/notification_template_part_chronometer.xml
ADDING: res/layout/notification_template_part_time.xml
ADDING: res/layout/status_bar_ongoing_event_progress_bar.xml
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: invalid skip
Unicode error: no space left
ADDING: resources.arsc
0 param: --use_depth_32
1 param: --use_immersive
Uninstalling previous version: Xiaomi Mi A2

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.test.richgame
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4409)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:22431)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:19350)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:757)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:929)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:22731)
        at android.os.Binder.shellCommand(Binder.java:594)
        at android.os.Binder.onTransact(Binder.java:492)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2658)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3859)
        at android.os.Binder.execTransact(Binder.java:697)
Installing to device (please wait...): Xiaomi Mi A2
adb: failed to install C:\Users\gggii\AppData\Local\Temp/Godot/tmpexport.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to collect certificates from /data/app/vmdl1255005611.tmp/base.apk: Package /data/app/vmdl1255005611.tmp/base.apk has no certificates at entry res/layout-v21/notification_action.xml]
Starting: Intent { act=android.intent.action.MAIN cmp=com.test.richgame/org.godotengine.godot.Godot }
Error type 3
Error: Activity class {com.test.richgame/org.godotengine.godot.Godot} does not exist.
``` 
to note that the procedure stops before the sign process that normally occure on the empy project after:
``` 
0 param: --use_depth_32
1 param: --use_immersive
```

**Steps to reproduce:**
don't really know

**Comment by akien-mga** [comment]
Is this a release or debug build? If it's a release build, did you set up your release keystore?

**Comment by gggiiia** [comment]
> Is this a release or debug build? If it's a release build, did you set up your release keystore?

it was a debug release using the instant deploy, making a new project and reimporting all the nodes/scripts lets the project to run and install, don't really know what went wrong on the old project.

**Comment by akien-mga** [comment]
You can compare the `export_presets.cfg` of both folders and see if there was a misconfiguration in the original one.

**Comment by micfan** [comment]
Hi, I got the same problem with you

**Comment by Calinou** [comment]
@gggiiia Can you (or anyone else)still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by akien-mga** [comment]
No answer, and most users seem to be able to export Android games without issue, so assuming fixe.d
