### ISSUE TITLE
Android: error exporting in release mode

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#2777]
exporting android apk in release mode I have this error:
```
0 param: -use_depth_32
1 param: -use_immersive
Enter key password for xxxxx: Exception in thread "main" java.io.IOError: java.io.IOException: Errore di input/output
        at java.io.Console.readPassword(Console.java:312)
        at java.io.Console.readPassword(Console.java:350)
        at sun.security.util.Password.readPassword(Password.java:56)
        at sun.security.util.Password.readPassword(Password.java:40)
        at sun.security.tools.JarSigner.getPass(JarSigner.java:1947)
        at sun.security.tools.JarSigner.getAliasInfo(JarSigner.java:1888)
        at sun.security.tools.JarSigner.run(JarSigner.java:230)
        at sun.security.tools.JarSigner.main(JarSigner.java:102)
Caused by: java.io.IOException: Errore di input/output
        at java.io.Console.echo(Native Method)
        at java.io.Console.readPassword(Console.java:310)
        ... 7 more
returned: 12066, waiting for: 12066
TextureButton: 16,-4
Label: 146,63
HBoxContainer: 53,25
ERROR: export_platform: Exporting failed!
   At: tools/editor/project_export.cpp:498.
TextureButton: 16,-4
Label: 146,63
HBoxContainer: 53,25
```

**Comment by GrandFunkR** [comment]
please delete this issue, it was my mistake in creating the keystore
