### ISSUE TITLE
godot server build crash at export

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#30661]
That is on Linux. I tried to export project. The cresh is due to CameraServer not available.

The backtrace:

```Starting program: /home/slapin/godot/bin/godot_server.x11.tools.64 --path /home/slapin/godot-projects/kicking-high/proto1 --export linux /home/slapin/godot-projects/kicking-high/proto1-linux
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7fcf700 (LWP 1405)]
Godot Engine v3.2.dev.custom_build.364fbe89e - https://godotengine.org
[New Thread 0x7ffff75c9700 (LWP 1406)]
[New Thread 0x7ffff7588700 (LWP 1407)]
 

Thread 1 "godot_server.x1" received signal SIGSEGV, Segmentation fault.
0x000055555844a458 in CowData<Ref<CameraFeed> >::_get_size (this=0x100) at ./core/cowdata.h:70
70			if (!_ptr)
(gdb) bt
#0  0x000055555844a458 in CowData<Ref<CameraFeed> >::_get_size (this=0x100) at ./core/cowdata.h:70
#1  0x0000555558449f66 in CowData<Ref<CameraFeed> >::size (this=0x100) at ./core/cowdata.h:125
#2  0x000055555844994a in Vector<Ref<CameraFeed> >::size (this=0xf8) at ./core/vector.h:83
#3  0x0000555558447f50 in CameraServer::get_free_id (this=0x0) at servers/camera_server.cpp:69
#4  0x000055555855ce9f in CameraFeed::CameraFeed (this=0x55555ae43960) at servers/camera/camera_feed.cpp:138
#5  0x00005555584d6dc4 in ClassDB::creator<CameraFeed> () at ./core/class_db.h:146
#6  0x000055555879260e in ClassDB::instance (p_class=...) at core/class_db.cpp:540
#7  0x0000555558797136 in ClassDB::class_get_default_property_value (p_class=..., p_property=..., r_valid=0x7fffffff97cf) at core/class_db.cpp:1415
#8  0x000055555749a90c in DocData::generate (this=0x55555acbb120, p_basic_types=true) at editor/doc/doc_data.cpp:255
#9  0x00005555571afca0 in EditorHelp::generate_doc () at editor/editor_help.cpp:1421
#10 0x00005555572185a3 in EditorNode::EditorNode (this=0x55555acba520) at editor/editor_node.cpp:5306
#11 0x00005555566a5239 in Main::start () at main/main.cpp:1624
#12 0x0000555556679cf2 in main (argc=6, argv=0x7fffffffe168) at platform/server/godot_server.cpp:42
```

**Comment by fire** [comment]
See https://github.com/godotengine/godot/commit/e30a137548dce0fe1f5eda223b900fcbdd2631b8

**Comment by slapin** [comment]
Thanks, this is resolved now via https://github.com/godotengine/godot/commit/e30a137548dce0fe1f5eda223b900fcbdd2631b8

**Comment by Calinou** [comment]
(For the record, this issue was a duplicate of #30630.)
