### ISSUE TITLE
Crash when cursor shape texture is being released at exit

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#30795]
Similar to #29197.

**Godot version:**
v3.2.dev.custom_build adae2b073

~~Doesn't seem to be reproducible in d087a9e3283528792634de84b55a607d9b9b5137.~~
Regression from a9a0d0f.

**OS/device including version:**
Windows 10

**Issue description:**
The project crashes at application exit when a custom cursor shape is set.

According to the crash log it seems like something prevents the cursor texture to be released (got this when run tests with GUT, again)

```
Tests finished, exit manually
ERROR: SelfList<class GDScriptFunction>::List::~List: Condition ' _first != 0 ' is true.
   At: engine\core/self_list.h:111
ERROR: SelfList<class GDScript>::List::~List: Condition ' _first != 0 ' is true.
   At: engine\core/self_list.h:111
ERROR: SelfList<class DynamicFont>::List::~List: Condition ' _first != 0 ' is true.
   At: engine\core/self_list.h:111
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:2098
ERROR: ResourceCache::clear: Resources Still in use at Exit!
   At: core\resource.cpp:445
ERROR: There are still MemoryPool allocs in use at exit!
   At: core\pool_vector.cpp:70
CrashHandlerException: Program crashed
Dumping the backtrace.
[0] StreamTexture::~StreamTexture (engine\scene\resources\texture.cpp:872)
[1] StreamTexture::`scalar deleting destructor'
[2] memdelete<Reference> (engine\core\os\memory.h:122)
[3] Ref<Reference>::unref (engine\core\reference.h:284)
[4] RefPtr::unref (engine\core\ref_ptr.cpp:83)
[5] Variant::clear (engine\core\variant.cpp:1111)
[6] Variant::~Variant (engine\core\variant.h:422)
[7] Variant::`scalar deleting destructor'
[8] CowData<Variant>::_unref (engine\core\cowdata.h:208)
[9] CowData<Variant>::~CowData<Variant> (engine\core\cowdata.h:369)
[10] Vector<Variant>::~Vector<Variant> (engine\core\vector.h:126)
[11] Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator>::Element::~Element
[12] Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator>::Element::`scalar deleting destructor'
[13] memdelete_allocator<Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator>::Element,DefaultAllocator> (engine\core\os\memory.h:133)
[14] Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator>::_cleanup_tree (engine\core\map.h:509)
[15] Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator>::clear (engine\core\map.h:664)
[16] Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator>::~Map<enum OS::CursorShape,Vector<Variant>,Comparator<enum OS::CursorShape>,DefaultAllocator> (engine\core\map.h:684)
[17] OS_Windows::~OS_Windows (engine\platform\windows\os_windows.cpp:3294)
[18] widechar_main (engine\platform\windows\godot_windows.cpp:169)
[19] _main (engine\platform\windows\godot_windows.cpp:184)
[20] main (engine\platform\windows\godot_windows.cpp:196)
[21] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[22] BaseThreadInitThunk
-- END OF BACKTRACE --
```
This causes the project to exit with non-zero status even if all tests pass which prevents using GUT in CI-like manner. A quick fix is not using custom cursor shapes.

Doesn't seem to be caused by cursor dimension limitation on Windows as described in #12814 because it was working just fine before.

**Steps to reproduce:**
1. Create a texture to override custom arrow cursor with a texture:
`Input.set_custom_mouse_cursor(preload("res://arrow.png"), Input.CURSOR_ARROW)`
2. Run the project and exit manually via `get_tree().quit()`

**Minimal reproduction project:**
[cursor-shape-crash.zip](https://github.com/godotengine/godot/files/3426965/cursor-shape-crash.zip)

Note that I couldn't get the crash log with minimal project, was only able to get it via running tests with GUT (command line), it only shows that a segfault occurred (`debug symbols=yes`).

**Comment by akien-mga** [comment]
Stacktrace from MRP running in `gdb` (with `run --verbose`):
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2098.
Leaked instance: StreamTexture:1150 - Resource name:  Path: res://arrow.png
[Thread 0x7fffeb762700 (LWP 18329) exited]
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:445.
Orphan StringName: StreamTexture
StringName: 1 unclaimed string names at exit.

Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
StreamTexture::~StreamTexture (this=0x5a4a5a0, __in_chrg=<optimized out>) at scene/resources/texture.cpp:872
872             VS::get_singleton()->free(texture);

(gdb) bt
#0  StreamTexture::~StreamTexture (this=0x5a4a5a0, __in_chrg=<optimized out>) at scene/resources/texture.cpp:872
#1  0x00000000013fb8b6 in memdelete<Reference> (p_class=0x5a4a5a0) at ./core/os/memory.h:120
#2  0x00000000013f9676 in Ref<Reference>::unref (this=0x631a9e0) at ./core/reference.h:282
#3  0x00000000036f6e38 in RefPtr::unref (this=0x631a9e0) at core/ref_ptr.cpp:82
#4  0x000000000374dc59 in Variant::clear (this=0x631a9d0) at core/variant.cpp:1110
#5  0x00000000013e579a in Variant::~Variant (this=0x631a9d0, __in_chrg=<optimized out>) at ./core/variant.h:422
#6  0x00000000013e5aff in CowData<Variant>::_unref (this=0x631ca70, p_data=0x631a9d0) at ./core/cowdata.h:207
#7  0x00000000013e5956 in CowData<Variant>::~CowData (this=0x631ca70, __in_chrg=<optimized out>) at ./core/cowdata.h:369
#8  0x00000000013e5800 in Vector<Variant>::~Vector (this=0x631ca68, __in_chrg=<optimized out>) at ./core/vector.h:126
#9  0x00000000013e61ca in Map<OS::CursorShape, Vector<Variant>, Comparator<OS::CursorShape>, DefaultAllocator>::Element::~Element (this=0x631ca30, __in_chrg=<optimized out>) at ./core/map.h:53
#10 0x00000000013e61f9 in memdelete_allocator<Map<OS::CursorShape, Vector<Variant>, Comparator<OS::CursorShape>, DefaultAllocator>::Element, DefaultAllocator> (p_class=0x631ca30) at ./core/os/memory.h:131
#11 0x00000000013e6178 in Map<OS::CursorShape, Vector<Variant>, Comparator<OS::CursorShape>, DefaultAllocator>::_cleanup_tree (this=0x7fffffffd420, p_element=0x631ca30) at ./core/map.h:508
#12 0x00000000013e6026 in Map<OS::CursorShape, Vector<Variant>, Comparator<OS::CursorShape>, DefaultAllocator>::clear (this=0x7fffffffd420) at ./core/map.h:663
#13 0x00000000013e5f4a in Map<OS::CursorShape, Vector<Variant>, Comparator<OS::CursorShape>, DefaultAllocator>::~Map (this=0x7fffffffd420, __in_chrg=<optimized out>) at ./core/map.h:684
#14 0x00000000013e5eb0 in OS_X11::~OS_X11 (this=0x7fffffffd0b0, __in_chrg=<optimized out>) at platform/x11/os_x11.h:84
#15 0x00000000013e5710 in main (argc=2, argv=0x7fffffffd868) at platform/x11/godot_x11.cpp:41
```

**Comment by akien-mga** [comment]
I had an old build laying around, it seems the bug was already there at f03c1c8d. Bisecting between d087a9e and f03c1c8d now.

**Comment by akien-mga** [comment]
Actually it segfaults at d087a9e for me...

**Comment by Xrayez** [comment]
Hmm I might have confused it with some other version or a segfault couldn't be detected under some circumstances, but the issue wasn't present like a month ago for sure.

#30269 is the reason why I stopped running GUT tests so I wasn't able to detect this regression from the moment I created that bug report.

**Comment by akien-mga** [comment]
```
a9a0d0fb15cc5e028dbf8dab8b46d3dc197c4678 is the first bad commit
commit a9a0d0fb15cc5e028dbf8dab8b46d3dc197c4678
Author: Guilherme Felipe <guilhermefelipecgs@gmail.com>
Date:   Mon Jul 8 17:37:18 2019 -0300

    Fix cursor blinking in integrated GPUs
    
    Optimization for Input::set_custom_mouse_cursor when used inside
    _process function. (Avoids cursor blinking in low end devices)

:040000 040000 5d79f0eeea4f9fd2146838939d8998638a4b839f fd40890e448615398800ea16c107406e3e747e82 M      platform
```

a9a0d0fb @guilhermefelipecgs
