### ISSUE TITLE
Crash SIGSEGV in 3.1.1 and nightly, Linux

### ISSUE THREAD

**Issue by payload** [godotengine/godot#30819]
**Godot version:** 3.1.1 and nightly from 25th July
**OS/device including version:** Ubuntu 18.10
**Issue description:**
SIGSEGV on load of a project specific project. Other projects work. The specific project used to work yesterday, before I closed Godot and restartet my machine.

The project uses CSG Shapes in tool scripts, queue_free() sometimes, removing stuff from the scene, setting owners.

**Steps to reproduce:** I try to get a zip from my project uploaded. Meanwhile maybe the stacktrace is enough to debug it?

**Trace:**

```
~$ ERROR: get_node: Node not found: /root/Events
   At: scene/main/node.cpp:1382.
ERROR: get_node: Node not found: /root/Events
   At: scene/main/node.cpp:1382.
ERROR: get_node: Node not found: /root/Events
   At: scene/main/node.cpp:1382.
ERROR: get_node: Node not found: /root/Events
   At: scene/main/node.cpp:1382.
ERROR: get_node: Node not found: /root/Events
   At: scene/main/node.cpp:1382.
ERROR: get_node: Node not found: /root/Events
   At: scene/main/node.cpp:1382.
ERROR: mesh_add_surface_from_arrays: Condition ' array_len == 0 ' is true.
   At: servers/visual_server.cpp:969.
ERROR: add_surface_from_arrays: Condition ' len == 0 ' is true.
   At: scene/resources/mesh.cpp:796.
ERROR: surface_set_material: Index p_idx=0 out of size (surfaces.size()=0)
   At: scene/resources/mesh.cpp:928.
ERROR: _update_shape: Condition ' !n ' is true.
   At: modules/csg/csg_shape.cpp:285.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00400000-042a0000 r-xp 00000000 fd:01 16909409                           /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64
0449f000-0456e000 r--p 03e9f000 fd:01 16909409                           /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64
0456e000-04588000 rw-p 03f6e000 fd:01 16909409                           /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64
04588000-045ba000 rw-p 00000000 00:00 0 
0569c000-0cc00000 rw-p 00000000 00:00 0                                  [heap]
404a1000-40536000 rwxp 00000000 00:00 0 
40b3a000-40b4a000 rwxp 00000000 00:00 0 
415c1000-415d1000 rwxp 00000000 00:00 0 
41c77000-41c87000 rwxp 00000000 00:00 0 
7fdf98000000-7fdf980e6000 rw-p 00000000 00:00 0 
7fdf980e6000-7fdf9c000000 ---p 00000000 00:00 0 
7fdfa0000000-7fdfa0021000 rw-p 00000000 00:00 0 
7fdfa0021000-7fdfa4000000 ---p 00000000 00:00 0 
7fdfa4000000-7fdfa4021000 rw-p 00000000 00:00 0 
7fdfa4021000-7fdfa8000000 ---p 00000000 00:00 0 
7fdfa8000000-7fdfa8021000 rw-p 00000000 00:00 0 
7fdfa8021000-7fdfac000000 ---p 00000000 00:00 0 
7fdfac000000-7fdfac021000 rw-p 00000000 00:00 0 
7fdfac021000-7fdfb0000000 ---p 00000000 00:00 0 
7fdfb0ba6000-7fdfb2fff000 rw-p 00000000 00:00 0 
7fdfb32d3000-7fdfb32d4000 rw-s 00000000 00:19 262                        /i915 (deleted)
7fdfb32d4000-7fdfb32d5000 rw-s 00000000 00:19 261                        /i915 (deleted)
7fdfb32d5000-7fdfb32d6000 rw-s 00000000 00:19 179                        /i915 (deleted)
7fdfb32d6000-7fdfb32d7000 rw-s 00000000 00:19 92                         /i915 (deleted)
7fdfb32d7000-7fdfb32dd000 rw-s 00000000 00:19 3522                       /i915 (deleted)

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x2eae22a):0x2eae21a  41 55 41 54 55 53 48 89 fb 48 83 ec 28 48 8b 3f  AUATUSH..H..(H.?
0x2eae22a  4c 8b 47 f0 48 8b 7f f8 48 c7 04 24 00 00 00 00  L.G.H...H..$....
0x2eae23a  48 c7 44 24 08 00 00 00 00 49 01 d8 48 89 44 24  H.D$.....I..H.D$
0x2eae24a  10 4d 8b 08 49 39 79 f8 75 6c 48 8b 07 48 89 cd  .M..I9y.ulH..H..

=================================================================
	Native stacktrace:
=================================================================
	0xc2b075 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : (null)
	0xc1ea09 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : (null)
	0xc33b0e - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : (null)
	0x7fdfdc813dd0 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
	0x2eae22a - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : __dynamic_cast
	0x1aab433 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN13SpatialEditor14_request_gizmoEP6Object
	0x19f2620 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : (null)
	0x2dab0d3 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE
	0x29f9e2d - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN12MessageQueue14_call_functionEP6ObjectRK10StringNamePK7Variantib
	0x29fa0e3 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN12MessageQueue5flushEv
	0x1dfc4d0 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN9SceneTree4idleEf
	0x1a1b03e - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN4Main9iterationEv
	0x1a59c39 - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : _ZN6OS_X113runEv
	0xb5a5ec - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : main
	0x7fdfdc49e09b - /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main
	0xb5bd9e - /home/payload/utils/godot/Godot_v3.1.1-stable_mono_x11_64/Godot_v3.1.1-stable_mono_x11.64 : (null)

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7fdfd1b43700 from 0x7fdfd94c4480
Entering thread summarizer pause from 0x7fdfd94c4480
Finished thread summarizer pause from 0x7fdfd94c4480.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
	External Debugger Dump:
=================================================================
[New LWP 6394]
[New LWP 6401]
[New LWP 6402]
[New LWP 6403]
[New LWP 6404]
[New LWP 6406]
[New LWP 6407]
[New LWP 6408]
[New LWP 6410]
[New LWP 6413]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fdfdc8137aa in __waitpid (pid=pid@entry=6416, stat_loc=stat_loc@entry=0x7fdfd1bf6c40, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id                                          Frame 
* 1    Thread 0x7fdfd94c4480 (LWP 6393) "Godot_v3.1.1-st" 0x00007fdfdc8137aa in __waitpid (pid=pid@entry=6416, stat_loc=stat_loc@entry=0x7fdfd1bf6c40, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7fdfd8464700 (LWP 6394) "Godot_v3.1.1-st" futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5744da8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fdfd2a58700 (LWP 6401) "Godot_v:disk$0"  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5917a38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  4    Thread 0x7fdfd213e700 (LWP 6402) "Godot_v3.1.1-st" futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5970888) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  5    Thread 0x7fdfd1db3700 (LWP 6403) "Godot_v3.1.1-st" 0x00007fdfdc8132d0 in __GI___nanosleep (requested_time=0x7fdfd1db2d40, remaining=0x7fdfd1db2d40) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  6    Thread 0x7fdfd1d72700 (LWP 6404) "Godot_v3.1.1-st" 0x00007fdfdc5586a0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fdfd1d71d20, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  7    Thread 0x7fdfd13ff700 (LWP 6406) "SGen worker"     futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x459d048 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  8    Thread 0x7fdfd1b43700 (LWP 6407) "Finalizer"       futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x458a840 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  9    Thread 0x7fdfd1bed700 (LWP 6408) "Godot_v3.1.1-st" 0x00007fdfdc8132d0 in __GI___nanosleep (requested_time=0x7fdfd1becbb0, remaining=0x7fdfd1becbb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  10   Thread 0x7fdfd01c7700 (LWP 6410) "Godot_v3.1.1-st" 0x00007fdfdc8132d0 in __GI___nanosleep (requested_time=0x7fdfd01c6d40, remaining=0x7fdfd01c6d40) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  11   Thread 0x7fdfd008d700 (LWP 6413) "Godot_v3.1.1-st" futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x59d68a8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 11 (Thread 0x7fdfd008d700 (LWP 6413)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x59d68a8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x59d68a8, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fdfdc812048 in __new_sem_wait_slow (sem=0x59d68a8, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000141af3d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x00000000059d63d0 in ?? ()
#5  0x0000000002e73eab in void CommandQueueMT::push_and_ret<VisualServerWrapMT, int (VisualServerWrapMT::*)(), int>(VisualServerWrapMT*, int (VisualServerWrapMT::*)(), int*) [clone .constprop.340] ()
#6  0x00007fdfd008cd18 in ?? ()
#7  0x00000000059d62a0 in ?? ()
#8  0x0000000000000000 in ?? ()

Thread 10 (Thread 0x7fdfd01c7700 (LWP 6410)):
#0  0x00007fdfdc8132d0 in __GI___nanosleep (requested_time=0x7fdfd01c6d40, remaining=0x7fdfd01c6d40) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000002dff7db in OS_Unix::delay_usec(unsigned int) const [clone .constprop.11903] ()
#2  0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7fdfd1bed700 (LWP 6408)):
#0  0x00007fdfdc8132d0 in __GI___nanosleep (requested_time=0x7fdfd1becbb0, remaining=0x7fdfd1becbb0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000002dff7db in OS_Unix::delay_usec(unsigned int) const [clone .constprop.11903] ()
#2  0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7fdfd1b43700 (LWP 6407)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x458a840 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x458a840 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fdfdc812048 in __new_sem_wait_slow (sem=sem@entry=0x458a840 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007fdfdc8120b9 in __new_sem_wait (sem=sem@entry=0x458a840 <finalizer_sem>) at sem_wait.c:42
#4  0x0000000000ce7ff4 in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x458a840 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:209
#5  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x458a840 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:43
#6  finalizer_thread (unused=unused@entry=0x0) at gc.c:918
#7  0x0000000000d9b70b in start_wrapper_internal (stack_ptr=<optimized out>, start_info=0x0) at threads.c:1155
#8  start_wrapper (data=0x62a9850) at threads.c:1215
#9  0x00007fdfdc809164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007fdfdc594def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fdfd13ff700 (LWP 6406)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x459d048 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x459d060 <lock>, cond=0x459d020 <work_cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x459d020 <work_cond>, mutex=mutex@entry=0x459d060 <lock>) at pthread_cond_wait.c:655
#3  0x0000000000e06cf3 in mono_os_cond_wait (mutex=0x459d060 <lock>, cond=0x459d020 <work_cond>) at ../../mono/utils/mono-os-mutex.h:173
#4  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#5  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#6  0x00007fdfdc809164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007fdfdc594def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fdfd1d72700 (LWP 6404)):
#0  0x00007fdfdc5586a0 in __GI___nanosleep (requested_time=requested_time@entry=0x7fdfd1d71d20, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007fdfdc58b7d4 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x00000000019e8872 in JoypadLinux::monitor_joypads() ()
#3  0xffffffffffffff48 in ?? ()
#4  0x0000000005b68580 in ?? ()
#5  0x0000000000000018 in ?? ()
#6  0x00007fdfac000b50 in ?? ()
#7  0x706e692f7665642f in ?? ()
#8  0x746e6576652f7475 in ?? ()
#9  0xffffffffff003133 in ?? ()
#10 0x0000000005b79660 in ?? ()
#11 0x00007fdfd1d71ec0 in ?? ()
#12 0x00007fdfdc50fdea in __GI___libc_malloc (bytes=140599274970472) at malloc.c:3049
#13 0x00007ffc4e17feae in ?? ()
#14 0x00007ffc4e17feaf in ?? ()
#15 0x0000000005b79660 in ?? ()
#16 0x00007fdfd1d71ec0 in ?? ()
#17 0x00000000014940c5 in ThreadPosix::thread_callback(void*) ()
#18 0x0000000000000000 in ?? ()

Thread 5 (Thread 0x7fdfd1db3700 (LWP 6403)):
#0  0x00007fdfdc8132d0 in __GI___nanosleep (requested_time=0x7fdfd1db2d40, remaining=0x7fdfd1db2d40) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000002dff7db in OS_Unix::delay_usec(unsigned int) const [clone .constprop.11903] ()
#2  0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7fdfd213e700 (LWP 6402)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5970888) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x5970888, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fdfdc812048 in __new_sem_wait_slow (sem=0x5970888, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000141af3d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x00007fdfd213f020 in ?? ()
#5  0x0000000002701eec in VisualServerScene::_gi_probe_bake_thread() ()
#6  0x0000000000000008 in ?? ()
#7  0x000000000597ecd0 in ?? ()
#8  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7fdfd2a58700 (LWP 6401)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5917a38) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x59179e8, cond=0x5917a10) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x5917a10, mutex=0x59179e8) at pthread_cond_wait.c:655
#3  0x00007fdfd32b0ebb in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fdfd32b0c27 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007fdfdc809164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007fdfdc594def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fdfd8464700 (LWP 6394)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5744da8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x5744da8, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fdfdc812048 in __new_sem_wait_slow (sem=0x5744da8, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000141af3d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x0000000005744de0 in ?? ()
#5  0x0000000002ba20f4 in _IP_ResolverPrivate::_thread_function(void*) ()
#6  0x00007fdfd8463ec0 in ?? ()
#7  0x00007fdfdc50fdea in __GI___libc_malloc (bytes=91506688) at malloc.c:3049
#8  0x00007ffc4e18013e in ?? ()
#9  0x00007ffc4e18013f in ?? ()
#10 0x0000000005744df0 in ?? ()
#11 0x00007fdfd8463ec0 in ?? ()
#12 0x00000000014940c5 in ThreadPosix::thread_callback(void*) ()
#13 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7fdfd94c4480 (LWP 6393)):
#0  0x00007fdfdc8137aa in __waitpid (pid=pid@entry=6416, stat_loc=stat_loc@entry=0x7fdfd1bf6c40, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000000000c2b1da in dump_native_stacktrace (ctx=ctx@entry=0x7fdfd1bf79c0, signal=0x2f1651b "SIGSEGV") at mini-posix.c:1112
#2  0x0000000000c2b38a in mono_dump_native_crash_info (signal=signal@entry=0x2f1651b "SIGSEGV", ctx=ctx@entry=0x7fdfd1bf79c0, info=info@entry=0x7fdfd1bf7af0) at mini-posix.c:1149
#3  0x0000000000c1ea09 in mono_handle_native_crash (signal=signal@entry=0x2f1651b "SIGSEGV", ctx=ctx@entry=0x7fdfd1bf79c0, info=info@entry=0x7fdfd1bf7af0) at mini-exceptions.c:3290
#4  0x0000000000c33b0e in mono_sigsegv_signal_handler (_dummy=11, _info=0x7fdfd1bf7af0, context=0x7fdfd1bf79c0) at mini-runtime.c:3488
#5  <signal handler called>
#6  0x0000000002eae22a in __dynamic_cast ()
#7  0x0000000000000000 in ?? ()
[Inferior 1 (process 6393) detached]

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================


```

**Comment by qarmin** [comment]
Seems like mono version of this crash #26394

**Comment by payload** [comment]
> Seems like mono version of this crash #26394

Looks like it, yes.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.
