### ISSUE TITLE
Invalid write and  Condition ' alloc->lock > 0 ' is true. returned: ERR_LOCKED and crash after exit when changing Pinned Points in SoftBody

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31293]
**Godot version:**
3.2.dev.custom_build. 3ea33c0e4

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Changing pinned points in Softbody cause showing this error and sometimes corruption of memory crash editor. 
```
 ./core/pool_vector.h:545 - Condition ' alloc->lock > 0 ' is true. returned: ERR_LOCKED
```
```
==28562==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61900171e6b0 at pc 0x000003c10bc2 bp 0x7fffb4de21a0 sp 0x7fffb4de2190
WRITE of size 4 at 0x61900171e6b0 thread T0
    #0 0x3c10bc1 in btSoftBody::setMass(int, float) thirdparty/bullet/BulletSoftBody/btSoftBody.cpp:689
    #1 0x2b66d1a in SoftBodyBullet::set_node_mass(int, float) modules/bullet/soft_body_bullet.cpp:206
    #2 0x2a4ba51 in BulletPhysicsServer::soft_body_pin_point(RID, int, bool) modules/bullet/bullet_physics_server.cpp:1173
    #3 0xa695542 in SoftBody::_pin_point_on_physics_server(int, bool) scene/3d/soft_body.cpp:743
    #4 0xa6911af in SoftBody::pin_point(int, bool, NodePath const&) scene/3d/soft_body.cpp:672
    #5 0xa676879 in SoftBody::_set_property_pinned_points_indices(Array const&) scene/3d/soft_body.cpp:205
    #6 0xa672e5c in SoftBody::_set(StringName const&, Variant const&) scene/3d/soft_body.cpp:128
    #7 0xa69b80a in SoftBody::_setv(StringName const&, Variant const&) scene/3d/soft_body.h:67
    #8 0xe094e68 in Object::set(StringName const&, Variant const&, bool*) core/object.cpp:446
    #9 0xe2a5462 in UndoRedo::_process_operation_list(List<UndoRedo::Operation, DefaultAllocator>::Element*) core/undo_redo.cpp:311
    #10 0xe2a6998 in UndoRedo::redo() core/undo_redo.cpp:337
    #11 0xe2a31e8 in UndoRedo::commit_action() core/undo_redo.cpp:259
    #12 0x59fb946 in EditorInspector::_edit_set(String const&, Variant const&, bool, String const&) editor/editor_inspector.cpp:2026
    #13 0x59fd355 in EditorInspector::_property_changed(String const&, Variant const&, String const&, bool) editor/editor_inspector.cpp:2043
    #14 0x5a75209 in MethodBind4<String const&, Variant const&, String const&, bool>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:3115
    #15 0xe0a4666 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:933
    #16 0xe0add12 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1233
    #17 0x598eb39 in EditorProperty::emit_changed(StringName const&, Variant const&, StringName const&, bool) editor/editor_inspector.cpp:88
    #18 0x5f13a1f in EditorPropertyArray::_property_changed(String const&, Variant, String const&, bool) editor/editor_properties_array_dict.cpp:174
    #19 0x5f63478 in MethodBind4<String const&, Variant, String const&, bool>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/bin/godot.x11.tools.64s+0x5f63478)
    #20 0xe0a4666 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:933
    #21 0xe0add12 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1233
    #22 0x598eb39 in EditorProperty::emit_changed(StringName const&, Variant const&, StringName const&, bool) editor/editor_inspector.cpp:88
    #23 0x5dd8c88 in EditorPropertyInteger::_value_changed(double) editor/editor_properties.cpp:822
    #24 0x5a5eace in MethodBind1<double>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #25 0xe0a4666 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:933
    #26 0xe0add12 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1233
    #27 0xe0afa7a in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1289
    #28 0x98df578 in Range::_value_changed_notify() scene/gui/range.cpp:49
    #29 0x98dfdbd in Range::Shared::emit_value_changed() scene/gui/range.cpp:60
    #30 0x98e23a6 in Range::set_value(double) scene/gui/range.cpp:100
    #31 0x606734a in EditorSpinSlider::_gui_input(Ref<InputEvent> const&) editor/editor_spin_slider.cpp:109
    #32 0x215a905 in MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #33 0xe09fef3 in Object::call_multilevel(StringName const&, Variant const**, int) core/object.cpp:772
    #34 0xe0a3092 in Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:873
    #35 0x91742f9 in Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) scene/main/viewport.cpp:1524
    #36 0x918c9a7 in Viewport::_gui_input_event(Ref<InputEvent>) scene/main/viewport.cpp:2114
    #37 0x91a6887 in Viewport::input(Ref<InputEvent> const&) scene/main/viewport.cpp:2672
    #38 0x9168fba in Viewport::_vp_input(Ref<InputEvent> const&) scene/main/viewport.cpp:1302
    #39 0x215a905 in MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #40 0xe0a4666 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:933
    #41 0xe0a2ae6 in Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:857
    #42 0x905cd77 in SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) scene/main/scene_tree.cpp:263
    #43 0x906227f in SceneTree::input_event(Ref<InputEvent> const&) scene/main/scene_tree.cpp:418
    #44 0x14900b0 in InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) main/input_default.cpp:442
    #45 0x1485502 in InputDefault::parse_input_event(Ref<InputEvent> const&) main/input_default.cpp:259
    #46 0x149850a in InputDefault::flush_accumulated_events() main/input_default.cpp:674
    #47 0x141b124 in OS_X11::process_xevents() platform/x11/os_x11.cpp:2612
    #48 0x142dbc0 in OS_X11::run() platform/x11/os_x11.cpp:3174
    #49 0x13aab93 in main platform/x11/godot_x11.cpp:56
    #50 0x7fe905856b6a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26b6a)
    #51 0x13aa799 in _start (/home/rafal/Pulpit/godot/bin/godot.x11.tools.64s+0x13aa799)

0x61900171e6b0 is located 89 bytes to the right of 983-byte region [0x61900171e280,0x61900171e657)
allocated by thread T0 here:
    #0 0x7fe907152448 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10c448)
    #1 0x2a2129c in btAllocDefault thirdparty/bullet/LinearMath/btAlignedAllocator.cpp:26
    #2 0x2a2130c in btAlignedAllocDefault thirdparty/bullet/LinearMath/btAlignedAllocator.cpp:66
    #3 0x2a21531 in btAlignedAllocInternal(unsigned long, int) thirdparty/bullet/LinearMath/btAlignedAllocator.cpp:247
    #4 0x3ceb261 in btAlignedAllocator<btSoftBody::Node, 16u>::allocate(int, btSoftBody::Node const**) (/home/rafal/Pulpit/godot/bin/godot.x11.tools.64s+0x3ceb261)
    #5 0x3ce1956 in btAlignedObjectArray<btSoftBody::Node>::allocate(int) (/home/rafal/Pulpit/godot/bin/godot.x11.tools.64s+0x3ce1956)
    #6 0x3cd279b in btAlignedObjectArray<btSoftBody::Node>::reserve(int) thirdparty/bullet/LinearMath/btAlignedObjectArray.h:284
    #7 0x3cd13a3 in btAlignedObjectArray<btSoftBody::Node>::resize(int, btSoftBody::Node const&) (/home/rafal/Pulpit/godot/bin/godot.x11.tools.64s+0x3cd13a3)
    #8 0x3bf2661 in btSoftBody::btSoftBody(btSoftBodyWorldInfo*, int, btVector3 const*, float const*) thirdparty/bullet/BulletSoftBody/btSoftBody.cpp:40
    #9 0x3d145ed in btSoftBodyHelpers::CreateFromTriMesh(btSoftBodyWorldInfo&, float const*, int const*, int, bool) thirdparty/bullet/BulletSoftBody/btSoftBodyHelpers.cpp:1054
    #10 0x2b70151 in SoftBodyBullet::set_trimesh_body_shape(PoolVector<int>, PoolVector<Vector3>) modules/bullet/soft_body_bullet.cpp:394
    #11 0x2b643ee in SoftBodyBullet::set_soft_mesh(Ref<Mesh> const&) modules/bullet/soft_body_bullet.cpp:133
    #12 0x2a4234c in BulletPhysicsServer::soft_body_set_mesh(RID, Ref<Reference> const&) modules/bullet/bullet_physics_server.cpp:930
    #13 0xa686aa0 in SoftBody::update_physics_server() scene/3d/soft_body.cpp:448
    #14 0xa6787bd in SoftBody::_changed_callback(Object*, char const*) scene/3d/soft_body.cpp:250
    #15 0x17578f9 in Object::_change_notify(char const*) core/object.h:580
    #16 0x8f66f3a in Node::set_process(bool) scene/main/node.cpp:807
    #17 0x8f4eaae in Node::_notification(int) scene/main/node.cpp:142
    #18 0x16ae481 in Node::_notificationv(int, bool) scene/main/node.h:46
    #19 0x16dda13 in Spatial::_notificationv(int, bool) scene/3d/spatial.h:58
    #20 0x16e01d3 in VisualInstance::_notificationv(int, bool) scene/3d/visual_instance.h:43
    #21 0x16e2993 in GeometryInstance::_notificationv(int, bool) scene/3d/visual_instance.h:87
    #22 0xa2d2a39 in MeshInstance::_notificationv(int, bool) scene/3d/mesh_instance.h:42
    #23 0xa69ca9b in SoftBody::_notificationv(int, bool) scene/3d/soft_body.h:67
    #24 0xe0a4bd1 in Object::notification(int, bool) core/object.cpp:943
    #25 0x8f510fb in Node::_propagate_ready() scene/main/node.cpp:196
    #26 0x8f50952 in Node::_propagate_ready() scene/main/node.cpp:188
    #27 0x8f9fb7a in Node::_set_tree(SceneTree*) scene/main/node.cpp:2534
    #28 0x8f72fab in Node::_add_child_nocheck(Node*, StringName const&) scene/main/node.cpp:1151
    #29 0x8f74b88 in Node::add_child(Node*, bool) scene/main/node.cpp:1170

SUMMARY: AddressSanitizer: heap-buffer-overflow thirdparty/bullet/BulletSoftBody/btSoftBody.cpp:689 in btSoftBody::setMass(int, float)

```
**Steps to reproduce:**
![file](https://user-images.githubusercontent.com/41945903/62834982-8e774780-bc53-11e9-97ea-3aa3bf4dd76e.gif)

**Comment by KoBeWi** [comment]
In 3.2.3 the error is different, but everything else seems fine (no crash etc). Should be fine to close.
