### ISSUE TITLE
A lot of leaks when close Godot after importing project in GDScriptParser(?)

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#32044]
**Godot version:**
3.2.alpha.custom_build. 4ee8ecd3e

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
A lot of leaks happens when importing open rpg, like:
```
Indirect leak of 1200 byte(s) in 10 object(s) allocated from:
    #0 0x7fd886a4b448 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10c448)
    #1 0xe94a238 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:85
    #2 0x13f0a6a in DefaultAllocator::alloc(unsigned long) core/os/memory.h:64
    #3 0xe94a153 in operator new(unsigned long, void* (*)(unsigned long)) core/os/memory.cpp:47
    #4 0x193e9b1 in Map<StringName, PropertyInfo, Comparator<StringName>, DefaultAllocator>::_insert(StringName const&, PropertyInfo const&) core/map.h:346
    #5 0x1932aa5 in Map<StringName, PropertyInfo, Comparator<StringName>, DefaultAllocator>::insert(StringName const&, PropertyInfo const&) core/map.h:563
    #6 0x1929e0b in Map<StringName, PropertyInfo, Comparator<StringName>, DefaultAllocator>::operator[](StringName const&) core/map.h:606
    #7 0x1912f52 in GDScriptCompiler::_parse_class_level(GDScript*, GDScriptParser::ClassNode const*, bool) modules/gdscript/gdscript_compiler.cpp:1915
    #8 0x191a69f in GDScriptCompiler::compile(GDScriptParser const*, GDScript*, bool) modules/gdscript/gdscript_compiler.cpp:2146
    #9 0x181d0fc in GDScript::reload(bool) modules/gdscript/gdscript.cpp:582
    #10 0x1856c08 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2189
    #11 0xede55ce in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #12 0xede8374 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #13 0x1bab5c0 in GDScriptParser::_resolve_type(GDScriptParser::DataType const&, int) modules/gdscript/gdscript_parser.cpp:5608
    #14 0x1bf8aac in GDScriptParser::_check_function_types(GDScriptParser::FunctionNode*) modules/gdscript/gdscript_parser.cpp:7732
    #15 0x1bee20b in GDScriptParser::_check_class_level_types(GDScriptParser::ClassNode*) modules/gdscript/gdscript_parser.cpp:7572
    #16 0x1c18936 in GDScriptParser::_parse(String const&) modules/gdscript/gdscript_parser.cpp:8382
    #17 0x1c1a411 in GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*, bool) modules/gdscript/gdscript_parser.cpp:8459
    #18 0x181c8ed in GDScript::reload(bool) modules/gdscript/gdscript.cpp:570
    #19 0x1856c08 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2189
    #20 0xede55ce in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #21 0xede8374 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #22 0x1be7fb9 in GDScriptParser::_reduce_identifier_type(GDScriptParser::DataType const*, StringName const&, int, bool) modules/gdscript/gdscript_parser.cpp:7443
    #23 0x1bb9fa3 in GDScriptParser::_reduce_node_type(GDScriptParser::Node*) modules/gdscript/gdscript_parser.cpp:6207
    #24 0x1bbd0ba in GDScriptParser::_reduce_node_type(GDScriptParser::Node*) modules/gdscript/gdscript_parser.cpp:6277
    #25 0x1c1244a in GDScriptParser::_check_block_types(GDScriptParser::BlockNode*) modules/gdscript/gdscript_parser.cpp:8214
    #26 0x1c12ef9 in GDScriptParser::_check_block_types(GDScriptParser::BlockNode*) modules/gdscript/gdscript_parser.cpp:8240
    #27 0x1c00c0a in GDScriptParser::_check_class_blocks_types(GDScriptParser::ClassNode*) modules/gdscript/gdscript_parser.cpp:7880
    #28 0x1c18a16 in GDScriptParser::_parse(String const&) modules/gdscript/gdscript_parser.cpp:8389
    #29 0x1c1a411 in GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*, bool) modules/gdscript/gdscript_parser.cpp:8459

Indirect leak of 1040 byte(s) in 1 object(s) allocated from:
    #0 0x7fd886a4b448 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10c448)
    #1 0xe94a238 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:85
    #2 0x32ce6e4 in CowData<wchar_t>::resize(int) core/cowdata.h:274
    #3 0x54f506d in String::resize(int) core/ustring.h:154
    #4 0xe5ff07d in String::parse_utf8(char const*, int) core/ustring.cpp:1457
    #5 0x182491f in GDScript::load_source_code(String const&) modules/gdscript/gdscript.cpp:819
    #6 0x1856680 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2183
    #7 0xede55ce in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #8 0xede8374 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #9 0x1bab5c0 in GDScriptParser::_resolve_type(GDScriptParser::DataType const&, int) modules/gdscript/gdscript_parser.cpp:5608
    #10 0x1bf9017 in GDScriptParser::_check_function_types(GDScriptParser::FunctionNode*) modules/gdscript/gdscript_parser.cpp:7738
    #11 0x1bee20b in GDScriptParser::_check_class_level_types(GDScriptParser::ClassNode*) modules/gdscript/gdscript_parser.cpp:7572
    #12 0x1c18936 in GDScriptParser::_parse(String const&) modules/gdscript/gdscript_parser.cpp:8382
    #13 0x1c1a411 in GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*, bool) modules/gdscript/gdscript_parser.cpp:8459
    #14 0x181c8ed in GDScript::reload(bool) modules/gdscript/gdscript.cpp:570
    #15 0x1856c08 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2189
    #16 0xede55ce in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #17 0xede8374 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #18 0x1bab5c0 in GDScriptParser::_resolve_type(GDScriptParser::DataType const&, int) modules/gdscript/gdscript_parser.cpp:5608
    #19 0x1bf8aac in GDScriptParser::_check_function_types(GDScriptParser::FunctionNode*) modules/gdscript/gdscript_parser.cpp:7732
    #20 0x1bee20b in GDScriptParser::_check_class_level_types(GDScriptParser::ClassNode*) modules/gdscript/gdscript_parser.cpp:7572
    #21 0x1c18936 in GDScriptParser::_parse(String const&) modules/gdscript/gdscript_parser.cpp:8382
    #22 0x1c1a411 in GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*, bool) modules/gdscript/gdscript_parser.cpp:8459
    #23 0x181c8ed in GDScript::reload(bool) modules/gdscript/gdscript.cpp:570
    #24 0x1856c08 in ResourceFormatLoaderGDScript::load(String const&, String const&, Error*) modules/gdscript/gdscript.cpp:2189
    #25 0xede55ce in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #26 0xede8374 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #27 0x1be7fb9 in GDScriptParser::_reduce_identifier_type(GDScriptParser::DataType const*, StringName const&, int, bool) modules/gdscript/gdscript_parser.cpp:7443
    #28 0x1bb9fa3 in GDScriptParser::_reduce_node_type(GDScriptParser::Node*) modules/gdscript/gdscript_parser.cpp:6207
    #29 0x1bbd0ba in GDScriptParser::_reduce_node_type(GDScriptParser::Node*) modules/gdscript/gdscript_parser.cpp:6277
```

Full log - [Open.txt](https://github.com/godotengine/godot/files/3587812/Open.txt)

**Minimal reproduction project:**
https://github.com/GDquest/godot-open-rpg/archive/cacfa2d05d75d8967e8fb1e00e457b2537976824.zip

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by qarmin** [comment]
Yes, but it seems to be a duplicate of #30668

**Comment by Sslaxx** [comment]
Going to give #30668 the 3.2 milestone tag?
