### ISSUE TITLE
[Android] Apk crash when i use a module

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#32772]
**Godot version:** 3.2 alpha2 

**OS/device including version:**
win10, android 9
**Issue description:**
Without module the apk runs fine but with module the apk crashes at start during run.
I even removed the plugin folder but it still crashes I guess it has something to do with
Project Settings -> Android -> Modules

```
 Loading Android module: org/godotengine/godot/GodotAdMob
10-12 16:36:13.265  9005  9036 I godot   : Godot Engine v3.2.alpha.custom_build - https://godotengine.org
10-12 16:36:13.272  9005  9036 I godot   : OpenGL ES 2.0 Renderer: Adreno (TM) 512
10-12 16:36:13.316  9005  9036 I godot   :
10-12 16:36:13.670  9005  9036 D godot   : AdMob: init with content rating options
10-12 16:36:13.684  9005  9005 D AndroidRuntime: Shutting down VM
10-12 16:36:13.686  9005  9005 E AndroidRuntime: FATAL EXCEPTION: main
10-12 16:36:13.686  9005  9005 E AndroidRuntime: Process: org.godotengine.admobplugintest, PID: 9005
10-12 16:36:13.686  9005  9005 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View, android.view.ViewGroup$LayoutParams)' on a null object reference
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at org.godotengine.godot.GodotAdMob$4.run(GodotAdMob.java:276)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6692)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-12 16:36:13.686  9005  9005 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by gamergamesz** [comment]
```
Loading Android module: org/godotengine/godot/GodotAdMob
10-12 16:41:52.769  9868  9898 E godot   : **ERROR**: Condition ' !singletonClass ' is true. Continuing..:
10-12 16:41:52.769  9868  9898 E godot   :    At: platform\android\java_godot_lib_jni.cpp:689:_initialize_java_modules() - Condition ' !singletonClass ' is true. Continuing..:
10-12 16:41:52.770  9868  9898 E AndroidRuntime: FATAL EXCEPTION: GLThread 8488
10-12 16:41:52.770  9868  9898 E AndroidRuntime: Process: org.godotengine.admobplugintest, PID: 9868
10-12 16:41:52.770  9868  9898 E AndroidRuntime: java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/GodotAdMob" on path: DexPathList[[zip file "/data/app/org.godotengine.admobplugintest-5eIdmnihYDFdoEaQ2cahnQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.admobplugintest-5eIdmnihYDFdoEaQ2cahnQ==/lib/arm, /data/app/org.godotengine.admobplugintest-5eIdmnihYDFdoEaQ2cahnQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at org.godotengine.godot.GodotLib.setup(Native Method)
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at org.godotengine.godot.Godot$2.run(Godot.java:307)
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
10-12 16:41:52.770  9868  9898 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
10-12 16:41:53.750  9868  9868 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
```

**Comment by volzhs** [comment]
where did you get that plugin?
is it correct GodotAdMob package name, starts with org.godotengine.godot?

**Comment by gamergamesz** [comment]
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin

**Comment by akien-mga** [comment]
> Godot version: 3.2 latest

Please be more explicit.

**Comment by gamergamesz** [comment]
3.2alpha

**Comment by akien-mga** [comment]
> 3.2alpha2

Did it work in previous versions? Does the demo from that plugin work?

**Comment by gamergamesz** [comment]
Nope, as the previous version of 3.2 were crashing during the apk compiling process though vinny in mobile-dev section of discord has confirmed that it works like charm (linux and macos) and the plugin's previous version for 3.1 works in android.

**Comment by gamergamesz** [comment]
Closing this issue as it has something to do with plugin itself, sorry for wasting time
