### ISSUE TITLE
Memory leak when using Gridmap  in  xatlas::internal::ArrayBase::~ArrayBase() 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33071]
**Godot version:**
3.2.alpha.custom_build. 40a25c1e8

**OS/device including version:**
Ubuntu 19.04
**Issue description:**
```
Direct leak of 240 byte(s) in 240 object(s) allocated from:
    #0 0x7f2691deff1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
    #1 0x3653ece in Realloc thirdparty/xatlas/xatlas.cpp:315
    #2 0x368b149 in xatlas::internal::ArrayBase::~ArrayBase() thirdparty/xatlas/xatlas.cpp:986
    #3 0x36b648d in xatlas::internal::Array<xatlas::internal::Task>::~Array() thirdparty/xatlas/xatlas.cpp:1099
    #4 0x36b83b6 in xatlas::internal::TaskScheduler::TaskGroup::~TaskGroup() thirdparty/xatlas/xatlas.cpp:3585
    #5 0x36b8a33 in xatlas::internal::TaskScheduler::~TaskScheduler() thirdparty/xatlas/xatlas.cpp:3516
    #6 0x366f19a in xatlas::Destroy(xatlas::Atlas*) thirdparty/xatlas/xatlas.cpp:7741
    #7 0x2865887 in xatlas_mesh_lightmap_unwrap_callback(float, float const*, float const*, int, int const*, int const*, int, float**, int**, int*, int**, int*, int*, int*) modules/xatlas_unwrap/register_types.cpp:109
    #8 0xbf7082e in ArrayMesh::lightmap_unwrap(Transform const&, float) scene/resources/mesh.cpp:1196
    #9 0x317a014 in GridMap::make_baked_meshes(bool, float) modules/gridmap/grid_map.cpp:1082
    #10 0x317a896 in GridMap::get_bake_meshes() modules/gridmap/grid_map.cpp:1093
    #11 0x31d79c1 in MethodBind0R<Array>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:237
    #12 0xe5fc60e in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #13 0xe8ea39e in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1096
    #14 0x1a2ff32 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1082
    #15 0x1867ff7 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1164
    #16 0xe5fc17b in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:900
    #17 0xe8ea39e in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1096
    #18 0x1a2ff32 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1082
    #19 0x1867ff7 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1164
    #20 0xe5fc17b in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:900
    #21 0xe8ea39e in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1096
    #22 0x1a2ff32 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1082
    #23 0x1868510 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1180
    #24 0x93911f3 in Node::_notification(int) scene/main/node.cpp:60
    #25 0x17218eb in Node::_notificationv(int, bool) scene/main/node.h:46
    #26 0x17518af in Spatial::_notificationv(int, bool) scene/3d/spatial.h:54
    #27 0xe5fcb78 in Object::notification(int, bool) core/object.cpp:931
    #28 0x94c1a01 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:980
    #29 0x94b2290 in SceneTree::idle(float) scene/main/scene_tree.cpp:526
```
**Steps to reproduce:**
1. Read Project README - https://github.com/qarmin/The-worst-Godot-test-project#the-worst-godot-test-project
2. Run Project

**Minimal reproduction project:**
[The-worst-Godot-test-project.tar.gz](https://github.com/godotengine/godot/files/3773025/The-worst-Godot-test-project.tar.gz)

**Comment by qarmin** [comment]
This issue can be closed when Godot update Xatlas module
