### ISSUE TITLE
Duplicating node throws error

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33749]
**Godot version:**
cc3b7d2

**Issue description:**
```
func _ready() -> void:
	var a = Node.new()
	var b = a.duplicate()
```
![image](https://user-images.githubusercontent.com/2223172/69182799-0afea980-0b12-11ea-91e7-4b7c90b2b081.png)

Obviously, happens also with nodes on scene.

**Comment by capnm** [comment]
I didn't looked closely at the circumstances, but this fixes that:
```diff
diff --git a/scene/main/node.cpp b/scene/main/node.cpp
index 2a2a6bb41..b221e0fda 100644
--- a/scene/main/node.cpp
+++ b/scene/main/node.cpp
@@ -835,7 +835,8 @@ bool Node::is_processing_internal() const {
 void Node::set_process_priority(int p_priority) {
        data.process_priority = p_priority;
 
-       ERR_FAIL_COND(!data.tree);
+       if (!is_inside_tree())
+               return;
 
        if (is_processing())
                data.tree->make_group_changed("idle_process");
```

**Comment by KoBeWi** [comment]
Weird, because this PR seems to have been merged in July, but the error isn't happening in 3.2 beta. It might be something different.

**Comment by capnm** [comment]
In any case, it makes no sense for me to notify groups if the node is outside the tree. 
Here came the priority stuff  in #19888

**Comment by capnm** [comment]
Interesting. If I just add a print statement
```
		if (is_processing())
			if (!data.tree) printf("XXX IP\n");
			data.tree->make_group_changed("idle_process");

```
it later crashes
```
#0  make_group_changed () at scene/main/scene_tree.cpp:149
#1  0x000000000376439d in set_process_priority () at scene/main/node.cpp:844
#2  0x000000000378a973 in call () at ./core/method_bind.gen.inc:867
#3  0x0000000004876812 in call () at core/object.cpp:921
#4  0x0000000004931900 in call_ptr () at core/variant_call.cpp:1112
#5  0x0000000002401987 in call () at modules/gdscript/gdscript_function.cpp:1081
#6  0x0000000002395af7 in _ml_call_reversed () at modules/gdscript/gdscript.cpp:1195
#7  0x00000000048733ce in Object::notification(int, bool) () at core/object.cpp:931
#8  0x0000000003761c9c in _propagate_ready () at scene/main/node.cpp:196
#9  0x0000000003761c29 in _propagate_ready () at scene/main/node.cpp:188
#10 0x0000000003766daa in Node::_set_tree(SceneTree*) () at scene/main/node.cpp:2561
#11 0x00000000037994aa in SceneTree::init() () at scene/main/scene_tree.cpp:465
#12 0x0000000002020260 in OS_X11::run() () at platform/x11/os_x11.cpp:3247
#13 0x000000000201217b in main () at platform/x11/godot_x11.cpp:56

(gdb) l
144		if (E->get().nodes.empty())
145			group_map.erase(E);
146	}
147	
148	void SceneTree::make_group_changed(const StringName &p_group) {
149		Map<StringName, Group>::Element *E = group_map.find(p_group);
150		if (E)
151			E->get().changed = true;
152	}
153
