### ISSUE TITLE
Error spam and invalid read when opening visual script project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34493]
**Godot version:**
Godot 3.2 Beta 4
**OS/device including version:**
Ubuntu 19.10
**Issue description:**
When I open project in editor, then I see this errors
```
ERROR: _disconnect: Disconnecting nonexistent signal 'ports_changed', slot: 19699:_node_ports_changed.
   At: core/object.cpp:1526.
```
and when I open editor with project with Godot with sanitizers support, then I got this errors
```
modules/visual_script/visual_script_nodes.cpp:207:30: runtime error: load of value 3200171710, which is not a valid value for type 'PropertyHint'
core/object.h:138:8: runtime error: load of value 3200171710, which is not a valid value for type 'PropertyHint'
    #0 0x149aaa1 in CowData<Variant>::_ref(CowData<Variant> const&) core/cowdata.h:357
    #1 0x14b1d4f in Vector<Variant>::operator=(Vector<Variant> const&) core/vector.h:122
    #2 0x7b26a0b in Object::Connection::operator=(Object::Connection const&) core/object.h:412
    #3 0xe557e8f in Object::Signal::Slot::operator=(Object::Signal::Slot const&) core/object.h:458
    #4 0xe53cd73 in Object::connect(StringName const&, Object*, StringName const&, Vector<Variant> const&, unsigned int) core/object.cpp:1485
    #5 0x1f08f02 in VisualScript::add_node(StringName const&, int, Ref<VisualScriptNode> const&, Vector2 const&) modules/visual_script/visual_script.cpp:341
    #6 0x1f20991 in VisualScript::_set_data(Dictionary const&) modules/visual_script/visual_script.cpp:1182
    #7 0x2006b7f in MethodBind1<Dictionary const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #8 0xe2d2022 in ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) core/class_db.cpp:1031
    #9 0xe51abdc in Object::set(StringName const&, Variant const&, bool*) core/object.cpp:422
    #10 0xee79800 in ResourceInteractiveLoaderBinary::poll() core/io/resource_format_binary.cpp:745
    #11 0xeee4c3e in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:197
    #12 0xeeea918 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #13 0xeeed0fc in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #14 0x61a6666 in EditorResourcePreviewGenerator::generate_from_path(String const&, Vector2 const&) const editor/editor_resource_preview.cpp:66
    #15 0x61adf9f in EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) editor/editor_resource_preview.cpp:167
    #16 0x61b4761 in EditorResourcePreview::_thread() editor/editor_resource_preview.cpp:270
    #17 0x61ab0d6 in EditorResourcePreview::_thread_func(void*) editor/editor_resource_preview.cpp:107
    #18 0x4f821a5 in ThreadPosix::thread_callback(void*) drivers/unix/thread_posix.cpp:74
    #19 0x7fa2a60f5668 in start_thread /build/glibc-4WA41p/glibc-2.30/nptl/pthread_create.c:479
    #20 0x7fa2a5356322 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x122322)

0x60d001b92e28 is located 88 bytes inside of 144-byte region [0x60d001b92dd0,0x60d001b92e60)
freed by thread T0 here:
    #0 0x7fa2a677ff1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
    #1 0xea53d97 in Memory::realloc_static(void*, unsigned long, bool) core/os/memory.cpp:137
    #2 0xe574c70 in CowData<VMap<Object::Signal::Target, Object::Signal::Slot>::Pair>::resize(int) core/cowdata.h:283
    #3 0xe5744ed in CowData<VMap<Object::Signal::Target, Object::Signal::Slot>::Pair>::insert(int, VMap<Object::Signal::Target, Object::Signal::Slot>::Pair const&) core/cowdata.h:175
    #4 0xe56555c in VMap<Object::Signal::Target, Object::Signal::Slot>::insert(Object::Signal::Target const&, Object::Signal::Slot const&) core/vmap.h:125
    #5 0xe55baf7 in VMap<Object::Signal::Target, Object::Signal::Slot>::operator[](Object::Signal::Target const&) core/vmap.h:199
    #6 0xe53cd3c in Object::connect(StringName const&, Object*, StringName const&, Vector<Variant> const&, unsigned int) core/object.cpp:1485
    #7 0x1f08f02 in VisualScript::add_node(StringName const&, int, Ref<VisualScriptNode> const&, Vector2 const&) modules/visual_script/visual_script.cpp:341
    #8 0x1f20991 in VisualScript::_set_data(Dictionary const&) modules/visual_script/visual_script.cpp:1182
    #9 0x2006b7f in MethodBind1<Dictionary const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #10 0xe2d2022 in ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) core/class_db.cpp:1031
    #11 0xe51abdc in Object::set(StringName const&, Variant const&, bool*) core/object.cpp:422
    #12 0xee79800 in ResourceInteractiveLoaderBinary::poll() core/io/resource_format_binary.cpp:745
    #13 0xeee4c3e in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:197
    #14 0xeeea918 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #15 0xeeed0fc in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #16 0xc14f95c in ResourceInteractiveLoaderText::poll() scene/resources/resource_format_text.cpp:433
    #17 0xeee4c3e in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:197
    #18 0xeeea918 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #19 0xeeed0fc in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #20 0x5d7aebe in EditorNode::load_scene(String const&, bool, bool, bool, bool) editor/editor_node.cpp:3274
    #21 0x5db6fa1 in EditorNode::_load_open_scenes_from_config(Ref<ConfigFile>, String const&) editor/editor_node.cpp:4391
    #22 0x5da96c8 in EditorNode::_load_docks() editor/editor_node.cpp:4186
    #23 0x5ced245 in EditorNode::_sources_changed(bool) editor/editor_node.cpp:604
    #24 0x1eaaf81 in MethodBind1<bool>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #25 0xe52a5cc in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #26 0xe533fc4 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1219
    #27 0xe535f8b in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1276
    #28 0x5a9212e in EditorFileSystem::_notification(int) editor/editor_file_system.cpp:1146
    #29 0x5acc1e5 in EditorFileSystem::_notificationv(int, bool) (/usr/bin/godots+0x5acc1e5)

previously allocated by thread T10 here:
    #0 0x7fa2a677fae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0xea532ff in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0xe574a0e in CowData<VMap<Object::Signal::Target, Object::Signal::Slot>::Pair>::resize(int) core/cowdata.h:275
    #3 0xe5744ed in CowData<VMap<Object::Signal::Target, Object::Signal::Slot>::Pair>::insert(int, VMap<Object::Signal::Target, Object::Signal::Slot>::Pair const&) core/cowdata.h:175
    #4 0xe56555c in VMap<Object::Signal::Target, Object::Signal::Slot>::insert(Object::Signal::Target const&, Object::Signal::Slot const&) core/vmap.h:125
    #5 0xe55baf7 in VMap<Object::Signal::Target, Object::Signal::Slot>::operator[](Object::Signal::Target const&) core/vmap.h:199
    #6 0xe53cd3c in Object::connect(StringName const&, Object*, StringName const&, Vector<Variant> const&, unsigned int) core/object.cpp:1485
    #7 0x1f08f02 in VisualScript::add_node(StringName const&, int, Ref<VisualScriptNode> const&, Vector2 const&) modules/visual_script/visual_script.cpp:341
    #8 0x1f20991 in VisualScript::_set_data(Dictionary const&) modules/visual_script/visual_script.cpp:1182
    #9 0x2006b7f in MethodBind1<Dictionary const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #10 0xe2d2022 in ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) core/class_db.cpp:1031
    #11 0xe51abdc in Object::set(StringName const&, Variant const&, bool*) core/object.cpp:422
    #12 0xee79800 in ResourceInteractiveLoaderBinary::poll() core/io/resource_format_binary.cpp:745
    #13 0xeee4c3e in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:197
    #14 0xeeea918 in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:270
    #15 0xeeed0fc in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:396
    #16 0x61a6666 in EditorResourcePreviewGenerator::generate_from_path(String const&, Vector2 const&) const editor/editor_resource_preview.cpp:66
    #17 0x61adf9f in EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) editor/editor_resource_preview.cpp:167
    #18 0x61b4761 in EditorResourcePreview::_thread() editor/editor_resource_preview.cpp:270
    #19 0x61ab0d6 in EditorResourcePreview::_thread_func(void*) editor/editor_resource_preview.cpp:107
    #20 0x4f821a5 in ThreadPosix::thread_callback(void*) drivers/unix/thread_posix.cpp:74
    #21 0x7fa2a60f5668 in start_thread /build/glibc-4WA41p/glibc-2.30/nptl/pthread_create.c:479

Thread T10 created by T0 here:
    #0 0x7fa2a66ac805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x4f826a0 in ThreadPosix::create_func_posix(void (*)(void*), void*, Thread::Settings const&) drivers/unix/thread_posix.cpp:90
    #2 0xea676b1 in Thread::create(void (*)(void*), void*, Thread::Settings const&) core/os/thread.cpp:51
    #3 0x61bea02 in EditorResourcePreview::start() editor/editor_resource_preview.cpp:460
    #4 0x5ced13c in EditorNode::_sources_changed(bool) editor/editor_node.cpp:602
    #5 0x1eaaf81 in MethodBind1<bool>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #6 0xe52a5cc in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #7 0xe533fc4 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1219
    #8 0xe535f8b in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1276
    #9 0x5a9212e in EditorFileSystem::_notification(int) editor/editor_file_system.cpp:1146
    #10 0x5acc1e5 in EditorFileSystem::_notificationv(int, bool) (/usr/bin/godots+0x5acc1e5)
    #11 0xe52aa5e in Object::notification(int, bool) core/object.cpp:931
    #12 0x940a08d in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:981
    #13 0x93fa91c in SceneTree::idle(float) scene/main/scene_tree.cpp:527
    #14 0x1589ce8 in Main::iteration() main/main.cpp:2010
    #15 0x1483056 in OS_X11::run() platform/x11/os_x11.cpp:3255
    #16 0x13fe299 in main platform/x11/godot_x11.cpp:56
    #17 0x7fa2a525b1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
```

**Steps to reproduce:**
1. Just open project
**Minimal reproduction project:**
https://github.com/godotengine/godot-demo-projects/tree/master/visual_script/multitouch_view

**Comment by qarmin** [comment]
Seems that is fixed in master
