### ISSUE TITLE
Android Crash (No implementation found for void org.godotengine.godot.GodotLib.initialize)

### ISSUE THREAD

**Issue by mpatraw** [godotengine/godot#3478]
I'm running: `Linux zork 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux`

I built Godot from HEAD and also downloaded 2.0 BETA from http://www.godotengine.org/projects/godot-engine/documents just to be sure. I used export templates from the same place (2.0 BETA) and when exporting to Android it crashes and I get this error message visible through `adb catlog` http://sprunge.us/KWLh

```
/art     (30376): No implementation found for void org.godotengine.godot.GodotLib.initialize(org.godotengine.godot.Godot, boolean, java.lang.String[], java.lang.Object) (tried Java_org_godotengine_godot_GodotLib_initialize and Java_org_godotengine_godot_GodotLib_initialize__Lorg_godotengine_godot_Godot_2Z_3Ljava_lang_String_2Ljava_lang_Object_2)
E/AndroidRuntime(30376): FATAL EXCEPTION: main
E/AndroidRuntime(30376): Process: org.godotengine.sandbox, PID: 30376
E/AndroidRuntime(30376): java.lang.UnsatisfiedLinkError: No implementation found for void org.godotengine.godot.GodotLib.initialize(org.godotengine.godot.Godot, boolean, java.lang.String[], java.lang.Object) (tried Java_org_godotengine_godot_GodotLib_initialize and Java_org_godotengine_godot_GodotLib_initialize__Lorg_godotengine_godot_Godot_2Z_3Ljava_lang_String_2Ljava_lang_Object_2)
E/AndroidRuntime(30376): 	at org.godotengine.godot.GodotLib.initialize(Native Method)
E/AndroidRuntime(30376): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:373)
E/AndroidRuntime(30376): 	at org.godotengine.godot.Godot.onCreate(Godot.java:545)
E/AndroidRuntime(30376): 	at android.app.Activity.performCreate(Activity.java:6500)
E/AndroidRuntime(30376): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
E/AndroidRuntime(30376): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3078)
E/AndroidRuntime(30376): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3224)
E/AndroidRuntime(30376): 	at android.app.ActivityThread.access$1000(ActivityThread.java:198)
E/AndroidRuntime(30376): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
E/AndroidRuntime(30376): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30376): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(30376): 	at android.app.ActivityThread.main(ActivityThread.java:6843)
E/AndroidRuntime(30376): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30376): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(30376): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(30376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by mcanders** [comment]
I get the same error

**Comment by ShyPixie** [comment]
Same here

**Comment by vinimtex** [comment]
Same error too..

**Comment by rubenwardy** [comment]
I get this same issue. What platforms is every one using? I'm currently on Windows 10 64bit, i5-5200U.

**Comment by reduz** [comment]
sound like the package is broken, will have to fix it

**Comment by akien-mga** [comment]
> sound like the package is broken, will have to fix it

Yeah we'll have to do test all export templates before we make 2.0-stable official, 1.1-stable also came with some broken templates like the Win32.opt which was fixed a few days ago.

**Comment by reduz** [comment]
I fixed this already in the builder process, so next build should be ok
