### ISSUE TITLE
Invalid read when selecting fill tool in empty tilemap

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34854]
**Godot version:**
3.2 beta 5

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
Sanitizer log
```
==29496==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200073bad3 at pc 0x000007488bae bp 0x7ffe01e9e2a0 sp 0x7ffe01e9e290
READ of size 1 at 0x60200073bad3 thread T0
    #0 0x7488bad in TileMapEditor::_bucket_fill(Vector2i const&, bool, bool) editor/plugins/tile_map_editor_plugin.cpp:636
    #1 0x749322e in TileMapEditor::_draw_fill_preview(Control*, int, Vector2i const&, bool, bool, bool, Vector2i const&, Transform2D const&) editor/plugins/tile_map_editor_plugin.cpp:884
    #2 0x74c342f in TileMapEditor::forward_canvas_draw_over_viewport(Control*) editor/plugins/tile_map_editor_plugin.cpp:1740
    #3 0x74fd676 in TileMapEditorPlugin::forward_canvas_draw_over_viewport(Control*) editor/plugins/tile_map_editor_plugin.h:242
    #4 0x56c1e03 in EditorPluginList::forward_canvas_draw_over_viewport(Control*) editor/editor_node.cpp:6883
    #5 0x69059d5 in CanvasItemEditor::_draw_viewport() editor/plugins/canvas_item_editor_plugin.cpp:3650
    #6 0x1729e97 in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #7 0xcd90f1a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #8 0xcd99822 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1219
    #9 0xcd9b4e5 in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1276
    #10 0x9ca9aa0 in CanvasItem::_update_callback() scene/2d/canvas_item.cpp:459
    #11 0x1729e97 in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #12 0xcd90f1a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #13 0xcd673d4 in MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) core/message_queue.cpp:250
    #14 0xcd67fb3 in MessageQueue::flush() core/message_queue.cpp:297
    #15 0x85887f0 in SceneTree::iteration(float) scene/main/scene_tree.cpp:485
    #16 0x1560344 in Main::iteration() main/main.cpp:1988
    #17 0x1478368 in OS_X11::run() platform/x11/os_x11.cpp:3255
    #18 0x13fe2e9 in main platform/x11/godot_x11.cpp:56
    #19 0x7f6c9cfda1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #20 0x13fdf0d in _start (/usr/bin/godots+0x13fdf0d)

0x60200073bad3 is located 2 bytes to the right of 1-byte region [0x60200073bad0,0x60200073bad1)
allocated by thread T0 here:
    #0 0x7f6c9e500a67 in operator new[](unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10fa67)
    #1 0x74885b0 in TileMapEditor::_bucket_fill(Vector2i const&, bool, bool) editor/plugins/tile_map_editor_plugin.cpp:631
    #2 0x749322e in TileMapEditor::_draw_fill_preview(Control*, int, Vector2i const&, bool, bool, bool, Vector2i const&, Transform2D const&) editor/plugins/tile_map_editor_plugin.cpp:884
    #3 0x74c342f in TileMapEditor::forward_canvas_draw_over_viewport(Control*) editor/plugins/tile_map_editor_plugin.cpp:1740
    #4 0x74fd676 in TileMapEditorPlugin::forward_canvas_draw_over_viewport(Control*) editor/plugins/tile_map_editor_plugin.h:242
    #5 0x56c1e03 in EditorPluginList::forward_canvas_draw_over_viewport(Control*) editor/editor_node.cpp:6883
    #6 0x69059d5 in CanvasItemEditor::_draw_viewport() editor/plugins/canvas_item_editor_plugin.cpp:3650
    #7 0x1729e97 in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #8 0xcd90f1a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #9 0xcd99822 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1219
    #10 0xcd9b4e5 in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1276
    #11 0x9ca9aa0 in CanvasItem::_update_callback() scene/2d/canvas_item.cpp:459
    #12 0x1729e97 in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #13 0xcd90f1a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:921
    #14 0xcd673d4 in MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) core/message_queue.cpp:250
    #15 0xcd67fb3 in MessageQueue::flush() core/message_queue.cpp:297
    #16 0x85887f0 in SceneTree::iteration(float) scene/main/scene_tree.cpp:485
    #17 0x1560344 in Main::iteration() main/main.cpp:1988
    #18 0x1478368 in OS_X11::run() platform/x11/os_x11.cpp:3255
    #19 0x13fe2e9 in main platform/x11/godot_x11.cpp:56
    #20 0x7f6c9cfda1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)

SUMMARY: AddressSanitizer: heap-buffer-overflow editor/plugins/tile_map_editor_plugin.cpp:636 in TileMapEditor::_bucket_fill(Vector2i const&, bool, bool)
```
**Steps to reproduce:**
1. Compile Godot with sanitizer support `scons p=x11 -j6 use_asan=yes use_ubsan=yes`
2. 
![jfile](https://user-images.githubusercontent.com/41945903/71809172-cc945e00-306f-11ea-9a26-552a3a871744.gif)

**Minimal reproduction project:**
[GGG.zip](https://github.com/godotengine/godot/files/4025477/GGG.zip)

**Comment by YeldhamDev** [comment]
Does this only happens with the bucket tool?

**Comment by qarmin** [comment]
Nope, invalid read still happens and only with bucket tool.
