### ISSUE TITLE
Double-Tap Unimplemented in Android Template

### ISSUE THREAD

**Issue by JosephCatrambone** [godotengine/godot#35110]
**Godot version:**
3.2 beta 6

**OS/device including version:**
Android 10, K4.14.117, Samsung S10+

**Issue description:**
After building and installing an Android game with the templates for 3.2 beta 6, any sequence of more than one tap on the screen will crash the application.

```
01-13 22:26:13.921  1332  1332 D GamePkgDataHelper: getGamePkgData(). io.xoana.horror2d
01-13 22:26:13.921  1332  1332 D GameManagerService: identifyGamePackage. io.xoana.horror2d, mCurrentUserId: 0, callerUserId: 0
01-13 22:26:13.921 11069 11156 E AndroidRuntime: FATAL EXCEPTION: GLThread 59741
01-13 22:26:13.921 11069 11156 E AndroidRuntime: Process: io.xoana.horror2d, PID: 11069
01-13 22:26:13.921 11069 11156 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void org.godotengine.godot.GodotLib.double_tap(int, int) (tried Java_org_godotengine_godot_GodotLib_double_1tap and Java_org_godotengine_godot_GodotLib_double_1tap__II)
01-13 22:26:13.921 11069 11156 E AndroidRuntime:        at org.godotengine.godot.GodotLib.double_tap(Native Method)
01-13 22:26:13.921 11069 11156 E AndroidRuntime:        at org.godotengine.godot.input.GodotGestureHandler$1.run(GodotGestureHandler.java:81)
01-13 22:26:13.921 11069 11156 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
01-13 22:26:13.921 11069 11156 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
01-13 22:26:13.921  1332  1332 D GamePkgDataHelper: getGamePkgData(). io.xoana.horror2d
01-13 22:26:13.926  1332  7060 W ActivityManager: crash : io.xoana.horror2d,0
01-13 22:26:13.928  1332  7060 W ActivityTaskManager:   Force finishing activity io.xoana.horror2d/com.godot.game.GodotApp
```

**Steps to reproduce:**

1. Create an empty project.
2. Export for Android.
3. Upload to device.
4. Run.
5. Double tap on screen.
6. 

**Minimal reproduction project:**

Attached, along with signed APK (using default debug keystore).

[AndroidBuildTest_project_only.zip](https://github.com/godotengine/godot/files/4057668/AndroidBuildTest.zip)

[AndroidBuildTest_with_apk.zip](https://github.com/godotengine/godot/files/4057669/AndroidBuildTest.zip)

**Comment by JosephCatrambone** [comment]
Disregard.  Fixed 18 hours ago.  You lot work fast.
#35049
