### ISSUE TITLE
Mono: ProceduralSky crash on quit

### ISSUE THREAD

**Issue by ForLoveOfCats** [godotengine/godot#35557]
**Godot version:**
Godot Mono 3.2 RC 3

**OS/device including version:**
Manjaro Linux x86_64

**Issue description:**
When there is a live node with a C# script which modifies the active `ProceduralSky` from the `_Process` function the engine will segfault on game quit.
![image](https://user-images.githubusercontent.com/30666851/73125959-e80dcd00-3f7a-11ea-8f6b-ea21b023c3e5.png)

**Steps to reproduce:**
See reproduction project

**Minimal reproduction project:**
[SkyCrash.zip](https://github.com/godotengine/godot/files/4112481/SkyCrash.zip)
The node MainScene has identical C# and GDScript versions of its script. Only the C# version causes the segfault.

**Comment by akien-mga** [comment]
It's reproducible in the current master branch (f67814116), though not all the time (but often enough, after 3 attempts I got it twice in a row).

`gdb` backtrace:
```
Thread 16 "godot-mono" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe88a2700 (LWP 24362)]
0x00000000014b7cc6 in ThreadSafe::lock (this=0x0) at ./core/os/thread_safe.h:42
42                      if (mutex) mutex->lock();

(gdb) bt
#0  0x00000000014b7cc6 in ThreadSafe::lock (this=0x0) at ./core/os/thread_safe.h:42
#1  0x00000000014b7d4c in ThreadSafeMethod::ThreadSafeMethod (this=0x7fffe88a1ae8, p_ts=0x0) at ./core/os/thread_safe.h:60
#2  0x0000000003986aad in MessageQueue::push_call (this=0x0, p_id=1164, p_method=..., p_args=0x7fffe88a1c10, p_argcount=1, p_show_error=false) at core/message_queue.cpp:45
#3  0x00000000039870ae in MessageQueue::push_call (this=0x0, p_id=1164, p_method=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/message_queue.cpp:90
#4  0x000000000398793a in MessageQueue::push_call (this=0x0, p_object=0x76370b0, p_method=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/message_queue.cpp:151
#5  0x00000000039997d3 in Object::call_deferred (this=0x76370b0, p_method=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1760
#6  0x00000000033f98a7 in ProceduralSky::_thread_function (p_ud=0x76370b0) at scene/resources/sky.cpp:450
#7  0x000000000207e83d in ThreadPosix::thread_callback (userdata=0x7ced720) at drivers/unix/thread_posix.cpp:74
#8  0x00000033a440904c in start_thread () from /lib64/libpthread.so.0
#9  0x00000033a430458f in clone () from /lib64/libc.so.6
```

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
