### ISSUE TITLE
Project exported to Android crashes on startup when run in an emulator

### ISSUE THREAD

**Issue by atari83** [godotengine/godot#36306]
Godot version: 3.2
OS: FreeBSD 12.1

So, I just created a simple project (GLES2 and literally a Label on screen)
I've downloaded the latest 3.2-stable export template, and successfully exported .apk file. 
Then I've installed the apk file on my android emulation with no issue, but when i execute the app the app is crashes and exited at begging with famous messages: "Unfortunately ... "

Full android logcat :
```
I/ActivityManager(  374): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.godotengine.bookgame/com.godot.game.GodotApp} from pid 533
E/SoundPool(  374): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/Effect_Tick.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/Effect_Tick.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/KeypressStandard.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/KeypressStandard.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/KeypressSpacebar.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/KeypressSpacebar.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/KeypressDelete.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/KeypressDelete.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/KeypressReturn.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/KeypressReturn.ogg
E/SoundPool(  374): error loading /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService(  374): Soundpool could not load file: /system/media/audio/ui/KeypressInvalid.ogg
W/AudioService(  374): onLoadSoundEffects(), Error -1 while loading samples
D/gralloc (   50): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/SurfaceFlinger(   50): glCheckFramebufferStatusOES error -664017793
E/SurfaceFlinger(   50): got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
W/WindowManager(  374): Screenshot failure taking screenshot for (492x874) to layer 21005
I/Choreographer(  533): Skipped 56 frames!  The application may be doing too much work on its main thread.
W/ActivityManager(  374): Activity pause timeout for ActivityRecord{960b5e70 u0 com.android.launcher/com.android.launcher2.Launcher t1}
I/ActivityManager(  374): Start proc org.godotengine.bookgame for activity org.godotengine.bookgame/com.godot.game.GodotApp: pid=1145 uid=10052 gids={50052}
D/dalvikvm( 1145): Not late-enabling CheckJNI (already on)
D/gralloc (   50): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/SurfaceFlinger(   50): glCheckFramebufferStatusOES error -664017793
E/SurfaceFlinger(   50): got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
I/ActivityManager(  374): Config changes=480 {1.0 310mcc260mnc en_US ldltr sw360dp w598dp h335dp 480dpi nrml land finger qwerty/v/v -nav/h s.10}
I/InputReader(  374): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  374): Device reconfigured: id=0, name='qwerty2', size 1080x1920, orientation 1, mode 1, display id 0
I/InputReader(  374): Reconfiguring input devices.  changes=0x00000004
D/PhoneStatusBar(  627): mSettingsPanelGravity = 55
W/WindowManager(  374): Window freeze timeout expired.
W/WindowManager(  374): Force clearing orientation change: Window{960f1690 u0 NavigationBar}
W/WindowManager(  374): Force clearing orientation change: Window{96149408 u0 StatusBar}
W/WindowManager(  374): Force clearing orientation change: Window{960a9d20 u0 Starting org.godotengine.bookgame}
W/WindowManager(  374): Force clearing orientation change: Window{9619aea8 u0 com.android.launcher/com.android.launcher2.Launcher}
W/WindowManager(  374): Force clearing orientation change: Window{96170040 u0 com.android.systemui.ImageWallpaper}
I/Choreographer(  627): Skipped 144 frames!  The application may be doing too much work on its main thread.
W/WindowManager(  374): App freeze timeout expired.
W/WindowManager(  374): Force clearing freeze: AppWindowToken{9619a9b8 token=Token{95ef3408 ActivityRecord{9612f2c8 u0 org.godotengine.bookgame/com.godot.game.GodotApp t4}}}
I/WindowManager(  374): Screen frozen for +7s573ms due to Window{960a9d20 u0 Starting org.godotengine.bookgame}
I/dalvikvm( 1145): Could not find method android.os.VibrationEffect.createOneShot, referenced from method org.godotengine.godot.Godot.vibrate
W/dalvikvm( 1145): VFY: unable to resolve static method 1286: Landroid/os/VibrationEffect;.createOneShot (JI)Landroid/os/VibrationEffect;
D/dalvikvm( 1145): VFY: replacing opcode 0x71 at 0x001a
D/dalvikvm(  627): GC_FOR_ALLOC freed 18146K, 54% free 10504K/22412K, paused 750ms, total 771ms
I/dalvikvm-heap(  627): Grow heap (frag case) to 13.459MB for 3072016-byte allocation
W/ActivityManager(  374): Launch timeout has expired, giving up wake lock!
D/dalvikvm(  627): GC_FOR_ALLOC freed 53K, 40% free 13450K/22412K, paused 740ms, total 740ms
W/ActivityManager(  374): Activity stop timeout for ActivityRecord{960b5e70 u0 com.android.launcher/com.android.launcher2.Launcher t1}
D/dalvikvm(  627): GC_CONCURRENT freed 1K, 40% free 13448K/22412K, paused 58ms+79ms, total 789ms
D/dalvikvm( 1145): Trying to load lib /data/app-lib/org.godotengine.bookgame-1/libgodot_android.so 0x95dd8038
E/WindowManager(  374): Starting window AppWindowToken{9619a9b8 token=Token{95ef3408 ActivityRecord{9612f2c8 u0 org.godotengine.bookgame/com.godot.game.GodotApp t4}}} timed out
D/dalvikvm(  627): GC_FOR_ALLOC freed <1K, 40% free 13449K/22412K, paused 693ms, total 693ms
D/dalvikvm( 1145): Added shared lib /data/app-lib/org.godotengine.bookgame-1/libgodot_android.so 0x95dd8038
D/dalvikvm( 1145): No JNI_OnLoad found in /data/app-lib/org.godotengine.bookgame-1/libgodot_android.so 0x95dd8038, skipping init
I/dalvikvm( 1145): Could not find method android.content.pm.PermissionInfo.getProtection, referenced from method org.godotengine.godot.utils.PermissionsUtil.getGrantedPermissions
W/dalvikvm( 1145): VFY: unable to resolve virtual method 708: Landroid/content/pm/PermissionInfo;.getProtection ()I
D/dalvikvm( 1145): VFY: replacing opcode 0x6e at 0x001f
I/dalvikvm( 1145): Could not find method android.content.pm.PermissionInfo.getProtection, referenced from method org.godotengine.godot.utils.PermissionsUtil.requestManifestPermissions
W/dalvikvm( 1145): VFY: unable to resolve virtual method 708: Landroid/content/pm/PermissionInfo;.getProtection ()I
D/dalvikvm( 1145): VFY: replacing opcode 0x6e at 0x0027
I/dalvikvm( 1145): Could not find method org.godotengine.godot.Godot.requestPermissions, referenced from method org.godotengine.godot.utils.PermissionsUtil.requestManifestPermissions
W/dalvikvm( 1145): VFY: unable to resolve virtual method 7434: Lorg/godotengine/godot/Godot;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm( 1145): VFY: replacing opcode 0x6e at 0x0053
I/dalvikvm( 1145): Could not find method org.godotengine.godot.Godot.requestPermissions, referenced from method org.godotengine.godot.utils.PermissionsUtil.requestPermission
W/dalvikvm( 1145): VFY: unable to resolve virtual method 7434: Lorg/godotengine/godot/Godot;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm( 1145): VFY: replacing opcode 0x6e at 0x001d
I/dalvikvm( 1145): Could not find method org.godotengine.godot.Godot.requestPermissions, referenced from method org.godotengine.godot.utils.PermissionsUtil.requestPermission
W/dalvikvm( 1145): VFY: unable to resolve virtual method 7434: Lorg/godotengine/godot/Godot;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm( 1145): VFY: replacing opcode 0x6e at 0x0036
I/dalvikvm( 1145): Could not find method org.godotengine.godot.Godot.requestPermissions, referenced from method org.godotengine.godot.utils.PermissionsUtil.requestPermission
W/dalvikvm( 1145): VFY: unable to resolve virtual method 7434: Lorg/godotengine/godot/Godot;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm( 1145): VFY: replacing opcode 0x6e at 0x004f
E/SensorManager( 1145): sensor or listener is null
E/SensorManager( 1145): sensor or listener is null
I/Choreographer(  374): Skipped 56 frames!  The application may be doing too much work on its main thread.
I/dalvikvm-heap(  627): Grow heap (frag case) to 28.126MB for 15436816-byte allocation
I/Choreographer(  374): Skipped 35 frames!  The application may be doing too much work on its main thread.
W/ActivityManager(  374): Unable to start service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending } U=0: not found
E/SensorManager( 1145): sensor or listener is null
E/SensorManager( 1145): sensor or listener is null
D/dalvikvm(  627): GC_CONCURRENT freed 0K, 24% free 28524K/37488K, paused 52ms+179ms, total 1148ms
D/dalvikvm(  627): WAIT_FOR_CONCURRENT_GC blocked 1097ms
D/dalvikvm(  374): GC_EXPLICIT freed 398K, 14% free 9259K/10688K, paused 36ms+32ms, total 467ms
I/Choreographer(  627): Skipped 539 frames!  The application may be doing too much work on its main thread.
I/ActivityManager(  374): Activity reported stop, but no longer stopping: ActivityRecord{960b5e70 u0 com.android.launcher/com.android.launcher2.Launcher t1}
I/Choreographer(  627): Skipped 30 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 1145): Skipped 128 frames!  The application may be doing too much work on its main thread.
W/dalvikvm( 1145): threadid=11: thread exiting with uncaught exception (group=0x95a7fba8)
E/AndroidRuntime( 1145): FATAL EXCEPTION: GLThread 84
E/AndroidRuntime( 1145): Process: org.godotengine.bookgame, PID: 1145
E/AndroidRuntime( 1145): java.lang.IllegalArgumentException: No configs match configSpec
E/AndroidRuntime( 1145):        at org.godotengine.godot.xr.regular.RegularConfigChooser.chooseConfig(RegularConfigChooser.java:91)
E/AndroidRuntime( 1145):        at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
E/AndroidRuntime( 1145):        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
E/AndroidRuntime( 1145):        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
W/ActivityManager(  374):   Force finishing activity org.godotengine.bookgame/com.godot.game.GodotApp
I/Choreographer( 1145): Skipped 62 frames!  The application may be doing too much work on its main thread.
D/gralloc (   50): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
E/SurfaceFlinger(   50): glCheckFramebufferStatusOES error -664017793
E/SurfaceFlinger(   50): got GL_FRAMEBUFFER_COMPLETE_OES error while taking screenshot
E/libEGL  (   50): called unimplemented OpenGL ES API
E/libEGL  (   50): called unimplemented OpenGL ES API
I/WindowManager(  374): Screenshot max retries 4 of Token{95ef3408 ActivityRecord{9612f2c8 u0 org.godotengine.bookgame/com.godot.game.GodotApp t4 f}} appWin=Window{9612b168 u0 org.godotengine.bookgame/com.godot.game.GodotApp} drawState=1
W/WindowManager(  374): Screenshot failure taking screenshot for (1080x1920) to layer 21015
I/InputReader(  374): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  374): Device reconfigured: id=0, name='qwerty2', size 1080x1920, orientation 0, mode 1, display id 0
I/ActivityManager(  374): Config changes=480 {1.0 310mcc260mnc en_US ldltr sw360dp w360dp h567dp 480dpi nrml port finger qwerty/v/v -nav/h s.11}
D/PhoneStatusBar(  627): mSettingsPanelGravity = 55
W/WindowManager(  374): Window freeze timeout expired.
W/WindowManager(  374): Force clearing orientation change: Window{960f1690 u0 NavigationBar}
W/WindowManager(  374): Force clearing orientation change: Window{96149408 u0 StatusBar}
W/WindowManager(  374): Force clearing orientation change: Window{9612b168 u0 org.godotengine.bookgame/com.godot.game.GodotApp}
W/WindowManager(  374): Force clearing orientation change: Window{96070570 u0 SurfaceView}
W/WindowManager(  374): Force clearing orientation change: Window{96170040 u0 com.android.systemui.ImageWallpaper}
I/WindowManager(  374): Screen frozen for +2s315ms due to Window{960a9d20 u0 Starting org.godotengine.bookgame}
W/ActivityManager(  374): Activity pause timeout for ActivityRecord{9612f2c8 u0 org.godotengine.bookgame/com.godot.game.GodotApp t4 f}
D/gralloc_goldfish( 1145): Emulator without host-side GPU emulation detected.
I/Choreographer(  374): Skipped 68 frames!  The application may be doing too much work on its main thread.
I/Choreographer(  627): Skipped 171 frames!  The application may be doing too much work on its main thread.
I/Choreographer(  374): Skipped 151 frames!  The application may be doing too much work on its main thread.
I/LatinIME:LogUtils(  492): Dictionary info: dictionary = contacts.en_US.dict ; version = ? ; date = ?
W/InputMethodManagerService(  374): Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@95f7b7f0 (uid=10052 pid=1145)
I/Choreographer(  533): Skipped 39 frames!  The application may be doing too much work on its main thread.
I/Choreographer(  374): Skipped 59 frames!  The application may be doing too much work on its main thread.
D/dalvikvm( 1145): GC_CONCURRENT freed 127K, 11% free 3420K/3832K, paused 8ms+48ms, total 1170ms
I/Choreographer(  627): Skipped 100 frames!  The application may be doing too much work on its main thread.
I/Choreographer(  374): Skipped 100 frames!  The application may be doing too much work on its main thread.
I/Choreographer(  374): Skipped 30 frames!  The application may be doing too much work on its main thread.
W/ActivityManager(  374): Launch timeout has expired, giving up wake lock!
D/dalvikvm(  374): GC_EXPLICIT freed 151K, 13% free 9310K/10688K, paused 38ms+25ms, total 941ms
D/dalvikvm(  627): GC_FOR_ALLOC freed 18167K, 50% free 11328K/22412K, paused 615ms, total 621ms
I/dalvikvm-heap(  627): Grow heap (frag case) to 14.264MB for 3072016-byte allocation
D/dalvikvm(  627): GC_CONCURRENT freed 875K, 40% free 13452K/22412K, paused 89ms+26ms, total 321ms
D/dalvikvm(  627): GC_FOR_ALLOC freed <1K, 40% free 13452K/22412K, paused 95ms, total 98ms
I/dalvikvm-heap(  627): Grow heap (frag case) to 28.130MB for 15436816-byte allocation
D/dalvikvm(  627): GC_FOR_ALLOC freed <1K, 24% free 28527K/37488K, paused 90ms, total 90ms
D/dalvikvm(  627): GC_CONCURRENT freed 0K, 24% free 28528K/37488K, paused 33ms+39ms, total 242ms
I/Choreographer(  627): Skipped 160 frames!  The application may be doing too much work on its main thread.
I/AndroidRuntime( 1145): VM exiting with result code 0, cleanup skipped.
I/ActivityManager(  374): Process org.godotengine.bookgame (pid 1145) has died.
I/WindowState(  374): WIN DEATH: Window{9612b168 u0 org.godotengine.bookgame/com.godot.game.GodotApp}
W/WindowManager(  374): Force-removing child win Window{96070570 u0 SurfaceView} from container Window{9612b168 u0 org.godotengine.bookgame/com.godot.game.GodotApp}
W/WindowManager(  374): Failed looking up window
W/WindowManager(  374): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@960850f8 does not exist
W/WindowManager(  374):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7923)
W/WindowManager(  374):         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:7914)
W/WindowManager(  374):         at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1047)
W/WindowManager(  374):         at android.os.BinderProxy.sendDeathNotice(Binder.java:493)
W/WindowManager(  374):         at dalvik.system.NativeStart.run(Native Method)
I/WindowState(  374): WIN DEATH: null
W/InputMethodManagerService(  374): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@96149d28 attribute=null, token = android.os.BinderProxy@9619ac00
D/dalvikvm(  522): GC_CONCURRENT freed 476K, 19% free 3716K/4556K, paused 7ms+8ms, total 68ms
```

**Comment by atari83** [comment]
Well, the app just run fine on a physical device with no issue .. 
So, I guess it is just the matter of emulation and its configuration.

Can anybody share their experience about testing on Emulation (ADV configuration - such as OS Version, ...)

**Comment by Calinou** [comment]
@atari83 Is your project configured to use the GLES2 renderer? Is hardware acceleration enabled in the emulator?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
