### ISSUE TITLE
Editor hang when syncing bones to polygons in 2D IK

### ISSUE THREAD

**Issue by lszl84** [godotengine/godot#36617]
**Godot version:** master (947a6636f70ea5a051efd6e470147072f2bc7f13)

**OS/device including version:** mac OS 10.15.2

**Issue description:** Editor hangs when syncing bones to polygons in 2D IK. Seems to be stuck in infinite loop at `rasterizer_canvas_rd.cpp`:888

```
   at: _render_item (servers/visual/rasterizer_rd/rasterizer_canvas_rd.cpp:888)
2020-02-27 22:07:29.922442+0100 godot.osx.tools.64[31375:1025108] ERROR: Condition "!pb" is true. Continuing.
at: _render_item (servers/visual/rasterizer_rd/rasterizer_canvas_rd.cpp:888)
ERROR: Condition "!pb" is true. Continuing.
```

**Steps to reproduce:**
1. Open attached project
2. Open `Person` scene
3. Select ArmRR polygon
4. Open the `uv` dialog
5. Go to `Bones` and click `Sync Bones to Polygons`
6. Select the bone for the arm
7. Select the add influence icon (white circle) and start drawing over the polygon

**Minimal reproduction project:**
[ik2d.zip](https://github.com/godotengine/godot/files/4264088/ik2d.zip)

**Comment by mrushyendra** [comment]
Encountered this same issue when attempting to paint bones in the Polygon2D UV Editor. The editor freezes when I click anywhere in the canvas after syncing the bones.

![uvEditorFreeze](https://user-images.githubusercontent.com/22248849/85810828-d67d5b00-b78e-11ea-909b-e9985d050118.png)

Gets stuck in an infinite loop issuing the following error:
```
ERROR: Condition "!pb" is true. Continuing.
   at: _render_item (servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:871)
```

Backtrace from GDB in case it helps:
```
#0  0x000000000198e45b in CowData<wchar_t>::size (this=0x7fffffffc1c8) at ./core/cowdata.h:126
#1  0x000000000198e352 in String::size (this=0x7fffffffc1c8) at ./core/ustring.h:152
#2  0x000000000198e36c in String::length (this=0x7fffffffc1c8) at ./core/ustring.h:196
#3  0x00000000046f873f in String::operator+= (this=0x7fffffffc1d0, p_str=...) at core/ustring.cpp:269
#4  0x00000000046f85fa in String::operator+ (this=0x7fffffffc1c0, p_str=...) at core/ustring.cpp:246
#5  0x0000000002bd4b34 in EditorLog::_error_handler (p_self=0xe14ab80, p_func=0x5aec625 "_render_item", 
    p_file=0x5aec3a8 "servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp", p_line=871, 
    p_error=0x5aec638 "Condition \"!pb\" is true. Continuing.", p_errorexp=0x5b302d0 "", p_type=ERR_HANDLER_ERROR) at editor/editor_log.cpp:50
#6  0x00000000046350b0 in _err_print_error (p_function=0x5aec625 "_render_item", 
    p_file=0x5aec3a8 "servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp", p_line=871, 
    p_error=0x5aec638 "Condition \"!pb\" is true. Continuing.", p_message=0x5b302d0 "", p_type=ERR_HANDLER_ERROR) at core/error_macros.cpp:82
#7  0x0000000004634f67 in _err_print_error (p_function=0x5aec625 "_render_item", 
    p_file=0x5aec3a8 "servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp", p_line=871, 
    p_error=0x5aec638 "Condition \"!pb\" is true. Continuing.", p_type=ERR_HANDLER_ERROR) at core/error_macros.cpp:69
#8  0x000000000451bd57 in RasterizerCanvasRD::_render_item (this=0x7b98aa0, p_draw_list=2, p_item=0x14f554e0, p_framebuffer_format=3, 
    p_canvas_transform_inverse=..., current_clip=@0x7fffffffc688: 0x0, p_lights=0x0, p_pipeline_variants=0x7b98bf0)
    at servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:871
#9  0x000000000451d699 in RasterizerCanvasRD::_render_items (this=0x7b98aa0, p_to_render_target=..., p_item_count=1, 
    p_canvas_transform_inverse=..., p_lights=0x0, p_screen_uniform_set=...) at servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:1362
#10 0x000000000451e3e2 in RasterizerCanvasRD::canvas_render_items (this=0x7b98aa0, p_to_render_target=..., p_item_list=0x14f554e0, 
    p_modulate=..., p_light_list=0x0, p_canvas_transform=...) at servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:1524
#11 0x00000000045014ee in RenderingServerCanvas::_render_canvas_item_tree (this=0x74c2d70, p_to_render_target=..., p_child_items=0x1078bfa0, 
    p_child_item_count=1, p_canvas_item=0x0, p_transform=..., p_clip_rect=..., p_modulate=..., p_lights=0x0)
    at servers/rendering/rendering_server_canvas.cpp:71
#12 0x000000000450267b in RenderingServerCanvas::render_canvas (this=0x74c2d70, p_render_target=..., p_canvas=0x8ab3640, p_transform=..., 
    p_lights=0x0, p_masked_lights=0x0, p_clip_rect=...) at servers/rendering/rendering_server_canvas.cpp:265
#13 0x00000000043470d8 in RenderingServerViewport::_draw_viewport (this=0x74c2ab0, p_viewport=0x94959f0, p_eye=XRInterface::EYE_MONO)
    at servers/rendering/rendering_server_viewport.cpp:257
#14 0x00000000043479d5 in RenderingServerViewport::draw_viewports (this=0x74c2ab0) at servers/rendering/rendering_server_viewport.cpp:413
#15 0x000000000431b43f in RenderingServerRaster::draw (this=0x74b7a80, p_swap_buffers=true, frame_step=0.050000004470348358)
    at servers/rendering/rendering_server_raster.cpp:112
#16 0x0000000004351004 in RenderingServerWrapMT::draw (this=0x79b0b50, p_swap_buffers=true, frame_step=0.050000004470348358)
    at servers/rendering/rendering_server_wrap_mt.cpp:91
#17 0x00000000019c71e7 in Main::iteration () at main/main.cpp:2217
#18 0x000000000198fa34 in OS_LinuxBSD::run (this=0x7fffffffd0e0) at platform/linuxbsd/os_linuxbsd.cpp:241
#19 0x000000000198d5a3 in main (argc=4, argv=0x7fffffffd5c8) at platform/linuxbsd/godot_linuxbsd.cpp:55
```
