### ISSUE TITLE
Godot crash when using TabContainer.*_popup functions

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#36904]
**Godot version:**
4.0.dev.custom_build. d4b31c698

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
Backtrace:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46470) [0x7fb2df5fd470] (??:0)
[2] Reference::reference() (/mnt/KubuntuWolne/godot/core/reference.cpp:73)
[3] Reference::init_ref() (/mnt/KubuntuWolne/godot/core/reference.cpp:37)
[4] Variant::Variant(Object const*) (/mnt/KubuntuWolne/godot/core/variant.cpp:2737)
[5] MethodBind0RC<Popup*>::call(Object*, Variant const**, int, Callable::CallError&) (/mnt/KubuntuWolne/godot/./core/method_bind.gen.inc:594 (discriminator 4))
[6] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/KubuntuWolne/godot/core/object.cpp:903 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Callable::CallError&) (/mnt/KubuntuWolne/godot/core/variant_call.cpp:1222 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/KubuntuWolne/godot/modules/gdscript/gdscript_function.cpp:1105)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/mnt/KubuntuWolne/godot/modules/gdscript/gdscript.cpp:1299)
[10] Node::_notification(int) (/mnt/KubuntuWolne/godot/scene/main/node.cpp:61)
[11] Node::_notificationv(int, bool) (/mnt/KubuntuWolne/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/mnt/KubuntuWolne/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Control::_notificationv(int, bool) (/mnt/KubuntuWolne/godot/./scene/gui/control.h:48 (discriminator 3))
[14] Container::_notificationv(int, bool) (/mnt/KubuntuWolne/godot/./scene/gui/container.h:38 (discriminator 3))
[15] TabContainer::_notificationv(int, bool) (/mnt/KubuntuWolne/godot/scene/gui/tab_container.h:38 (discriminator 3))
[16] Object::notification(int, bool) (/mnt/KubuntuWolne/godot/core/object.cpp:915)
[17] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/KubuntuWolne/godot/scene/main/scene_tree.cpp:988)
[18] SceneTree::idle(float) (/mnt/KubuntuWolne/godot/scene/main/scene_tree.cpp:527 (discriminator 3))
[19] Main::iteration() (/mnt/KubuntuWolne/godot/main/main.cpp:2062)
[20] OS_X11::run() (/mnt/KubuntuWolne/godot/platform/x11/os_x11.cpp:3335)
[21] godot(main+0x125) [0x16f7f3b] (/mnt/KubuntuWolne/godot/platform/x11/godot_x11.cpp:57)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fb2df5de1e3] (??:0)
[23] godot(_start+0x2e) [0x16f7d5e] (??:?)
```
Address Sanitizer Log
```
READ of size 8 at 0x61a000192c90 thread T0
    #0 0xfc0fe8a in Variant::Variant(Object const*) core/variant.cpp:2735
    #1 0xafd465c in MethodBind0RC<Popup*>::call(Object*, Variant const**, int, Callable::CallError&) core/method_bind.gen.inc:593
    #2 0xf987504 in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object.cpp:903
    #3 0xfc70097 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Callable::CallError&) core/variant_call.cpp:1222
    #4 0x41ca1d9 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1102
    #5 0x402f7f2 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1299
    #6 0xa3cb493 in Node::_notification(int) scene/main/node.cpp:63
    #7 0x19f524f in Node::_notificationv(int, bool) scene/main/node.h:46
    #8 0x19f76f9 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #9 0x19f9e1f in Control::_notificationv(int, bool) scene/gui/control.h:48
    #10 0x2565ab1 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #11 0xafc9969 in TabContainer::_notificationv(int, bool) scene/gui/tab_container.h:38
    #12 0xf987996 in Object::notification(int, bool) core/object.cpp:913
    #13 0xa4e9db3 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:988
    #14 0xa4d9fde in SceneTree::idle(float) scene/main/scene_tree.cpp:527
    #15 0x1888644 in Main::iteration() main/main.cpp:2062
    #16 0x179100c in OS_X11::run() platform/x11/os_x11.cpp:3335
    #17 0x170c869 in main platform/x11/godot_x11.cpp:56
    #18 0x7f8fe2f3f1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #19 0x170c47d in _start (/usr/bin/godots+0x170c47d)

0x61a000192c90 is located 16 bytes inside of 1272-byte region [0x61a000192c80,0x61a000193178)
freed by thread T0 here:
    #0 0x7f8fe41c56ef in __interceptor_free (/lib/x86_64-linux-gnu/libasan.so.5+0x10d6ef)
    #1 0xff8efc5 in Memory::free_static(void*, bool) core/os/memory.cpp:178
    #2 0x18935d6 in void memdelete<Object>(Object*) core/os/memory.h:119
    #3 0xa4ed286 in SceneTree::_flush_delete_queue() scene/main/scene_tree.cpp:1113
    #4 0xa4db5a9 in SceneTree::idle(float) scene/main/scene_tree.cpp:545
    #5 0x1888644 in Main::iteration() main/main.cpp:2062
    #6 0x179100c in OS_X11::run() platform/x11/os_x11.cpp:3335
    #7 0x170c869 in main platform/x11/godot_x11.cpp:56
    #8 0x7f8fe2f3f1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)

previously allocated by thread T0 here:
    #0 0x7f8fe41c5ae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0xff8e0b7 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0xff8dfb6 in operator new(unsigned long, char const*) core/os/memory.cpp:42
    #3 0xa333cbd in Object* ClassDB::creator<PopupMenu>() core/class_db.h:145
    #4 0xf71f902 in ClassDB::instance(StringName const&) core/class_db.cpp:561
    #5 0x4007436 in GDScriptNativeClass::instance() modules/gdscript/gdscript.cpp:84
    #6 0x4006e29 in GDScriptNativeClass::_new() modules/gdscript/gdscript.cpp:71
    #7 0x40bcd3f in MethodBind0R<Variant>::call(Object*, Variant const**, int, Callable::CallError&) core/method_bind.gen.inc:237
    #8 0xf987504 in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object.cpp:903
    #9 0xfc70097 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Callable::CallError&) core/variant_call.cpp:1222
    #10 0x41ca158 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1099
    #11 0x402f7f2 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1299
    #12 0xa3cb493 in Node::_notification(int) scene/main/node.cpp:63
    #13 0x19f524f in Node::_notificationv(int, bool) scene/main/node.h:46
    #14 0x19f76f9 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #15 0x19f9e1f in Control::_notificationv(int, bool) scene/gui/control.h:48
    #16 0x2565ab1 in Container::_notificationv(int, bool) scene/gui/container.h:38
    #17 0xafc9969 in TabContainer::_notificationv(int, bool) scene/gui/tab_container.h:38
    #18 0xf987996 in Object::notification(int, bool) core/object.cpp:913
    #19 0xa4e9db3 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:988
    #20 0xa4d9fde in SceneTree::idle(float) scene/main/scene_tree.cpp:527
    #21 0x1888644 in Main::iteration() main/main.cpp:2062
    #22 0x179100c in OS_X11::run() platform/x11/os_x11.cpp:3335
    #23 0x170c869 in main platform/x11/godot_x11.cpp:56
    #24 0x7f8fe2f3f1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
```
**Steps to reproduce:**
Run Project

**Minimal reproduction project:**
[The-worst-Godot-test-project.zip](https://github.com/godotengine/godot/files/4303104/The-worst-Godot-test-project.zip)

**Comment by PucklaMotzer09** [comment]
If you change the code to this:
`
extends TabContainer

func _process(_delta) -> void:
	if randi() % 2 == 1:
		var temp_PopupMenu : PopupMenu = PopupMenu.new()
		set_popup(temp_PopupMenu)
	if randi() % 2 == 1:
		get_popup()
`

It doesn't crash.

**Comment by qarmin** [comment]
Fixed in master
