### ISSUE TITLE
Godot segfaults on `get_tree().quit()`

### ISSUE THREAD

**Issue by ndarilek** [godotengine/godot#37127]
3.2.1. Whenever I quit, my game segfaults. It only happens after I launch, then pause, a game. I'm wondering if I'm not correctly freeing resources, but I never see errors to that effect. Here is a gdb backtrace:

```
#0  0x00000000038d6359 in Variant::call_ptr (this=0x7fffffffba30, p_method=..., p_args=0x0, p_argcount=0, r_ret=0x0, r_error=...) at core/variant_call.cpp:1112
#1  0x00000000015181a0 in GDScriptFunction::call (this=0x62531a0, p_instance=0x626f370, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:1088
#2  0x00000000014c1a37 in GDScriptInstance::call_multilevel (this=0x626f370, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gdscript.cpp:1218
#3  0x0000000002a6c720 in Node::_propagate_exit_tree (this=0x6286dd0) at scene/main/node.cpp:301
#4  0x0000000002a6c6aa in Node::_propagate_exit_tree (this=0x601c5a0) at scene/main/node.cpp:294
#5  0x0000000002a77d12 in Node::_set_tree (this=0x601c5a0, p_tree=0x0) at scene/main/node.cpp:2551
#6  0x0000000002a9cc6f in SceneTree::finish (this=0x5e06db0) at scene/main/scene_tree.cpp:619
#7  0x00000000014081f3 in OS_X11::run (this=0x7fffffffd030) at platform/x11/os_x11.cpp:3247
#8  0x00000000013f86b0 in main (argc=1, argv=0x7fffffffd818) at platform/x11/godot_x11.cpp:56
```

And again, I no longer get logged warnings about failing to free resources.

Please let me know what else to provide to help in debugging this. Thanks!

**Comment by akien-mga** [comment]
Can you provide a project that triggers the bug?

**Comment by qarmin** [comment]
Closing due no response since half year
