### ISSUE TITLE
android build template fails

### ISSUE THREAD

**Issue by eminvergil** [godotengine/godot#37439]
**Godot version**: 3.2-stable

**OS/device including version**: windows 10

**Issue description**:

> Task :Godot:lib:compileDebugAidl FAILED                                                                
> Task :generateGodotTemplates FAILED                                                                    
                                                                                                         
FAILURE: Build failed with an exception.                                                                 
                                                                                                         
* What went wrong:                                                                                       
Execution failed for task ':Godot:lib:compileDebugAidl'.                                                 
> com.android.ide.common.workers.WorkerExecutorException: 1 exception was raised by workers:             
  java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1               
                                                                                                         

![Untitled](https://user-images.githubusercontent.com/17277419/77950554-52bbeb80-72d1-11ea-91e3-5408fdc6cf35.jpeg)

                                                                                                         
**java version**:
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK Server VM (build 25.232-b09, mixed mode)

any response would be appreciated.

**Comment by akien-mga** [comment]
Given the error, I wonder if it's related to the fancy `λ` in your screenshot. Is that your prompt?

**Comment by eminvergil** [comment]
yes this is console emulator.it gives the same error on normal cmd.

**Comment by akien-mga** [comment]
Could you run:
```
.\gradlew generateGodotTemplates --stacktrace
```
and
```
.\gradlew generateGodotTemplates --debug
```
and paste the output here?

**Comment by eminvergil** [comment]
### this is output of **.\gradlew generateGodotTemplates --stacktrace** :

> Task :Godot:lib:compileDebugAidl FAILED
> Task :generateGodotTemplates FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Godot:lib:compileDebugAidl'.
> com.android.ide.common.workers.WorkerExecutorException: 1 exception was raised by workers:
  java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1


* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Godot:lib:compileDebugAidl'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
        at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.ide.common.workers.WorkerExecutorException: 1 exception was raised by workers:
java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1

        at com.android.build.gradle.tasks.AidlCompile.doFullTaskAction(AidlCompile.java:159)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
        ... 32 more
Caused by: com.android.ide.common.workers.WorkerExecutorException: 1 exception was raised by workers:
java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1

        at com.android.ide.common.workers.ExecutorServiceAdapter.await(ExecutorServiceAdapter.kt:62)
        at com.android.ide.common.workers.ExecutorServiceAdapter.close(ExecutorServiceAdapter.kt:69)
        at com.android.build.gradle.tasks.AidlCompile.doFullTaskAction(AidlCompile.java:157)
        ... 69 more
Caused by: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at com.android.ide.common.workers.ExecutorServiceAdapter.await(ExecutorServiceAdapter.kt:56)
        ... 71 more
Caused by: java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1
        at com.android.builder.internal.incremental.DependencyData.processDependencyData(DependencyData.java:118)
        at com.android.builder.internal.incremental.DependencyData.parseDependencyFile(DependencyData.java:97)
        at com.android.build.gradle.tasks.AidlCompile$DepFileProcessor.processFile(AidlCompile.java:111)
        at com.android.builder.internal.compiler.AidlProcessor.call(AidlProcessor.java:115)
        at com.android.builder.internal.compiler.DirectoryWalker$1.visitFile(DirectoryWalker.java:313)
        at com.android.builder.internal.compiler.DirectoryWalker$1.visitFile(DirectoryWalker.java:308)
        at com.android.builder.internal.compiler.DirectoryWalker.walk(DirectoryWalker.java:304)
        at com.android.build.gradle.tasks.AidlCompile$AidlCompileRunnable.run(AidlCompile.java:287)
        at com.android.ide.common.workers.ExecutorServiceAdapter$submit$submission$1.run(ExecutorServiceAdapter.kt:40)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        ... 9 more


* Get more help at https://help.gradle.org

BU¦LD FAILED in 2s
1 actionable task: 1 executed

**Comment by eminvergil** [comment]
### result of .\gradlew generateGodotTemplates --scan :

https://scans.gradle.com/s/cfqs5txljewv6

**Comment by m4gr3d** [comment]
@eminvergil Can you switch the character set to `UTF-8` by adding `org.gradle.jvmargs='-Dfile.encoding=UTF-8'` to the [gradle.properties file](https://github.com/godotengine/godot/blob/3.2-stable/platform/android/java/gradle.properties).
The fact that your character set is set to Turkish may be the cause of the issue.

**Comment by eminvergil** [comment]
@m4gr3d i tried that and it gives the same error.

**Comment by eminvergil** [comment]
i fixed this issue . if you come accross with this problem you can send me message so i can help you

**Comment by m4gr3d** [comment]
@eminvergil what was the cause of the issue, and how did you fix it?

**Comment by akien-mga** [comment]
![XKCD wisdom of the ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by eminvergil** [comment]
i dont know what was the cause of the issue but i followed these steps to fix it:

1 - **change the gradle version to latest versions in gradle-wrapper.properties.**
     i changed it from gradle-5.1.1-all to gradle-6.3-all. this fixes the issue

2 - **.\gradlew build**  
     
3 - **.\gradlew generateGodotTemplates**

when you use only ".\gradlew generateGodotTemplates" it will produce apk but when you try to export  it will give you error so 2.step is important you cant skip it.

**Comment by m4gr3d** [comment]
@eminvergil The second step is only needed because you didn't generate the shared libraries ahead of time. `.\gradlew build` does it because the shared library are also needed for Android Studio support, but by using that command, you lack the flexibility to specify the targeted architecture and the target type.

If you're only interested in generated the templates (and not Android Studio support), then you can use the [Android release build script](https://github.com/godotengine/godot-build-scripts/blob/ee823e51770abe04aef4e3c5ae66686f9bc8c1b6/build-android/build.sh#L21) as reference for the proper command sequence.
