### ISSUE TITLE
Unable to generate Mono Glue after core refactoring

### ISSUE THREAD

**Issue by NutmegStudio** [godotengine/godot#37494]
I'm using linux mint 19.3 cinnamon
#### Godot version
e53cbba36

building godot mono with `scons p=linuxbsd tools=yes module_mono_enabled=yes mono_glue=no -j16 CXX=g++-9 CC=gcc-9; bin/godot.linuxbsd.tools.64.mono --generate-mono-glue modules/mono/glue; scons p=linuxbsd target=debug tools=yes module_mono_enabled=yes -j16 CXX=g++-9 CC=gcc-9` Would give the error
```
...
Generating GradientTexture.cs...
Generating GraphEdit.cs...
Generating GraphNode.cs...
Generating GridContainer.cs...
Generating GridMap.cs...
Generating GrooveJoint2D.cs...
Generating HBoxContainer.cs...
Generating HScrollBar.cs...
Generating HSeparator.cs...
Generating HSlider.cs...
Generating HSplitContainer.cs...
Generating HTTPClient.cs...
Generating HTTPRequest.cs...
Generating HashingContext.cs...
Generating HeightMapShape3D.cs...
Generating HingeJoint3D.cs...
Generating IP.cs...
Generating Image.cs...
Generating ImageTexture.cs...
Generating ImmediateGeometry3D.cs...
Generating InputEvent.cs...
Generating InputEventAction.cs...
Generating InputEventGesture.cs...
Generating InputEventJoypadButton.cs...
Generating InputEventJoypadMotion.cs...
Generating InputEventKey.cs...
ERROR: Condition "!base_match" is true. returned: ERR_BUG
   at: _generate_cs_property (modules/mono/editor/bindings_generator.cpp:1420)
ERROR: Failed to generate property 'pressed' for class 'InputEventKey'.
   at: _generate_cs_type (modules/mono/editor/bindings_generator.cpp:1301)
ERROR: Generation of the Core API C# project failed.
   at: generate_cs_api (modules/mono/editor/bindings_generator.cpp:1119)
ERROR: --generate-mono-glue: Failed to generate the C# API.
   at: handle_cmdline_args (modules/mono/editor/bindings_generator.cpp:3454)
```
The last successful godot build was at 35e700e93

**Comment by LinuxUserGD** [comment]
See https://github.com/godotengine/godot/issues/36442

**Comment by neikeq** [comment]
I cannot reproduce with e53cbba36cf6cbf4f42621a0650ca8e57989379e nor with b50387c8bf2737e7f100c6c32350d97301a6f2a3.
It's weird, because that error shouldn't really happen. In fact, it should be an assertion instead.

**Comment by LinuxUserGD** [comment]
@neikeq This is the other part of the error after the glue generation fails:
```Swift
[  5%] Compiling ==> main/tests/test_main.cpp
platform/linuxbsd/display_server_x11.cpp:659:2: warning: Need to get from proper window [-W#warnings]
#warning Need to get from proper window
 ^
platform/linuxbsd/display_server_x11.cpp:3525:2: warning: Forcing vulkan rendering driver because OpenGL not implemented yet [-W#warnings]
#warning Forcing vulkan rendering driver because OpenGL not implemented yet
 ^
[  5%] Compiling ==> main/tests/test_math.cpp
Generated/GodotObjects/ARVRAnchor.cs(14,39): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ARVRCamera.cs(13,39): error CS0246: The type or namespace name 'Camera3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ARVRController.cs(14,43): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/PathFollow2D.cs(94,21): warning CS0108: 'PathFollow2D.Rotate' hides inherited member 'Node2D.Rotate(float)'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ARVROrigin.cs(15,39): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ARVRPositionalTracker.cs(68,39): warning CS0108: 'ARVRPositionalTracker.GetType()' hides inherited member 'object.GetType()'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/AcceptDialog.cs(12,41): error CS0246: The type or namespace name 'Window' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ArrayMesh.cs(144,36): warning CS0108: 'ArrayMesh.BlendShapeMode' hides inherited member 'Mesh.BlendShapeMode'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ArrayMesh.cs(40,21): warning CS0108: 'ArrayMesh.ArrayFormat' hides inherited member 'Mesh.ArrayFormat'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/ArrayMesh.cs(80,21): warning CS0108: 'ArrayMesh.ArrayType' hides inherited member 'Mesh.ArrayType'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/AudioStreamPlayer3D.cs(12,48): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/GIProbe.cs(13,36): error CS0246: The type or namespace name 'VisualInstance3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/GridMap.cs(15,36): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/CPUParticles.cs(15,21): warning CS0108: 'CPUParticles.Flags' hides inherited member 'GeometryInstance.Flags'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Generated/GodotObjects/LightOccluder2D.cs(36,20): warning CS0108: 'LightOccluder2D.LightMask' hides inherited member 'CanvasItem.LightMask'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
Die Erstellung des Projekts "/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" ist abgeschlossen (Standardziele) -- FEHLER.
Die Erstellung des Projekts "/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" ist abgeschlossen (Standardziele) -- FEHLER.

Fehler beim Buildvorgang.

"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (Standardziel) (1) ->
"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (Standardziel) (2) ->
(CoreCompile Ziel) -> 
  Generated/GodotObjects/PathFollow2D.cs(94,21): warning CS0108: 'PathFollow2D.Rotate' hides inherited member 'Node2D.Rotate(float)'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ARVRPositionalTracker.cs(68,39): warning CS0108: 'ARVRPositionalTracker.GetType()' hides inherited member 'object.GetType()'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ArrayMesh.cs(144,36): warning CS0108: 'ArrayMesh.BlendShapeMode' hides inherited member 'Mesh.BlendShapeMode'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ArrayMesh.cs(40,21): warning CS0108: 'ArrayMesh.ArrayFormat' hides inherited member 'Mesh.ArrayFormat'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ArrayMesh.cs(80,21): warning CS0108: 'ArrayMesh.ArrayType' hides inherited member 'Mesh.ArrayType'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/CPUParticles.cs(15,21): warning CS0108: 'CPUParticles.Flags' hides inherited member 'GeometryInstance.Flags'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/LightOccluder2D.cs(36,20): warning CS0108: 'LightOccluder2D.LightMask' hides inherited member 'CanvasItem.LightMask'. Use the new keyword if hiding was intended. [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]


"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln" (Standardziel) (1) ->
"/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj" (Standardziel) (2) ->
(CoreCompile Ziel) -> 
  Generated/GodotObjects/ARVRAnchor.cs(14,39): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ARVRCamera.cs(13,39): error CS0246: The type or namespace name 'Camera3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ARVRController.cs(14,43): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/ARVROrigin.cs(15,39): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/AcceptDialog.cs(12,41): error CS0246: The type or namespace name 'Window' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/AudioStreamPlayer3D.cs(12,48): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/GIProbe.cs(13,36): error CS0246: The type or namespace name 'VisualInstance3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
  Generated/GodotObjects/GridMap.cs(15,36): error CS0246: The type or namespace name 'Node3D' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]

    7 Warnung(en)
    8 Fehler

Verstrichene Zeit 00:00:12.65
scons: *** [bin/GodotSharp/Api/Debug/GodotSharp.dll] RuntimeError : 'msbuild' exited with error code: 1
Traceback (most recent call last):
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/solution_builder.py", line 156, in run_command
    subprocess.check_call(args, env=env_override)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/msbuild', '/run/media/user/user/git/godot/modules/mono/glue/GodotSharp/GodotSharp.sln', '/p:Configuration=Debug', '/p:NoWarn=1591']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/SCons/Action.py", line 1209, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/api_solution_build.py", line 21, in build_api_solution
    build_solution(env, solution_path, build_config, extra_msbuild_args=extra_msbuild_args)
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/solution_builder.py", line 220, in build_solution
    run_command(msbuild_path, msbuild_args, env_override=msbuild_env, name="msbuild")
  File "/run/media/user/user/git/godot/modules/mono/build_scripts/solution_builder.py", line 158, in run_command
    raise RuntimeError("'%s' exited with error code: %s" % (name, e.returncode))
RuntimeError: 'msbuild' exited with error code: 1
2 warnings generated.
scons: building terminated because of errors.
[user@archlinux git]$ 
```
when running
```
echo 'Build temporary linuxbsd server binary' && \
scons p=linuxbsd tools=yes module_mono_enabled=yes copy_mono_root=yes mono_glue=no -j 8 && \
echo 'Generate glue sources for linuxbsd' && \
bin/godot.linuxbsd.tools.64.mono --generate-mono-glue modules/mono/glue verbose=yes && \
echo 'linuxbsd' && \
scons p=linuxbsd bits=64 target=release_debug tools=yes use_llvm=yes use_lld=yes use_thinlto=yes module_mono_enabled=yes copy_mono_root=yes -j 8 && \
scons p=linuxbsd bits=64 target=release_debug tools=no use_llvm=yes use_lld=yes use_thinlto=yes module_mono_enabled=yes copy_mono_root=yes -j 8 && \
```

**Comment by neikeq** [comment]
Never mind, I was running an outdated godot binary (forgot to update my config after the rename from `x11` to `linuxbsd`). I can reproduce now.
