### ISSUE TITLE
"Couldn't find singleton for class" for custom Android plugin

### ISSUE THREAD

**Issue by Tooniis** [godotengine/godot#37658]
**Godot version:**
`v3.2.1.stable`

**OS/device including version:**
PC: Arch Linux
Phone: LineageOS `16.0-20200310-NIGHTLY-scorpio` on Xiaomi Mi Note 2

**Issue description:**
I'm trying to make a custom Android plugin to use the camera for object tracking. I've followed [this documentation page](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html), and using Android Studio, I created an empty project to get all the directories and gradle files set up. I named the package `org.godotengine.godot.tracker`, and the singleton class is in `res://android/Tracker/app/src/main/java/org/godotengine/godot/tracker/`.
This is my modules field in project settings:
![Screenshot from 2020-04-07 18-30-39](https://user-images.githubusercontent.com/36982494/78681547-f1fa6780-78fd-11ea-91df-e916f70e04af.png)
The game gets built and installed successfully, but it crashes instantly after launch, and this gets thrown in `logcat`:

    04-07 18:17:16.153 22109 22141 I godot   : Loading Android module: org/godotengine/godot/tracker
    04-07 18:17:16.154 22109 22141 E godot   : **ERROR**: Couldn't find singleton for class: org/godotengine/godot/tracker.
    04-07 18:17:16.154 22109 22141 E godot   :    At: platform/android/java_godot_lib_jni.cpp:691:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
    04-07 18:17:16.156 22109 22141 E AndroidRuntime: Process: org.godotengine.dworld, PID: 22109
    04-07 18:17:16.156 22109 22141 E AndroidRuntime: java.lang.ClassNotFoundException: Didn't find class "org/godotengine/godot/tracker" on path: DexPathList[[zip file "/data/app/org.godotengine.dworld-QP5s14wnF1xaey9qqG1iyQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.dworld-QP5s14wnF1xaey9qqG1iyQ==/lib/arm64, /data/app/org.godotengine.dworld-QP5s14wnF1xaey9qqG1iyQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
    04-07 18:17:16.156 22109 22141 E AndroidRuntime: 	at org.godotengine.godot.GodotLib.setup(Native Method)
    04-07 18:17:16.156 22109 22141 E AndroidRuntime: 	at org.godotengine.godot.Godot$2.run(Godot.java:325)

**Comment by Tooniis** [comment]
I was able to get the example plugin to work by copying the AdMob plugin, and specifically its file structure, which turned out to be mainly no more than a `src/` directory with the class in it.

I think the documentation on this subject is quite unclear; as I was able to achieve by copying an existing plugin what I couldn't by reading documentation several times.

It gives the directories that can be used used as "examples", while a suitable example should follow the `MySingleton` class example given later in the documentation page and show how the files of that plugin are organized. Something like this:

        res://
        └── android   
            └── tracker
                └── src
                    └── MySingleton.java
which imitates an output of `tree`.  This example can be put right before the code for the `MySingleton` class, while the current examples of directories should instead be listed similar to the chunk files section, not as examples.

Also, those directories aren't quite the same, or at least not organized in the same way of an Android project. Here's the `tree` of an empty Android project generated with Android Studio:

    .
    ├── app
    │   ├── app.iml
    │   ├── build.gradle
    │   ├── libs
    │   ├── proguard-rules.pro
    │   └── src
    │       ├── androidTest
    │       │   └── java
    │       │       └── org
    │       │           └── godotengine
    │       │               └── godot
    │       │                   └── example
    │       │                       └── ExampleInstrumentedTest.java
    │       ├── main
    │       │   ├── AndroidManifest.xml
    │       │   ├── java
    │       │   │   └── org
    │       │   │       └── godotengine
    │       │   │           └── godot
    │       │   │               └── example
    │       │   └── res
    │       │       ├── drawable
    │       │       │   └── ic_launcher_background.xml
    │       │       ├── drawable-v24
    │       │       │   └── ic_launcher_foreground.xml
    │       │       ├── mipmap-anydpi-v26
    │       │       │   ├── ic_launcher_round.xml
    │       │       │   └── ic_launcher.xml
    │       │       ├── mipmap-hdpi
    │       │       │   ├── ic_launcher.png
    │       │       │   └── ic_launcher_round.png
    │       │       ├── mipmap-mdpi
    │       │       │   ├── ic_launcher.png
    │       │       │   └── ic_launcher_round.png
    │       │       ├── mipmap-xhdpi
    │       │       │   ├── ic_launcher.png
    │       │       │   └── ic_launcher_round.png
    │       │       ├── mipmap-xxhdpi
    │       │       │   ├── ic_launcher.png
    │       │       │   └── ic_launcher_round.png
    │       │       ├── mipmap-xxxhdpi
    │       │       │   ├── ic_launcher.png
    │       │       │   └── ic_launcher_round.png
    │       │       └── values
    │       │           ├── colors.xml
    │       │           ├── strings.xml
    │       │           └── styles.xml
    │       └── test
    │           └── java
    │               └── org
    │                   └── godotengine
    │                       └── godot
    │                           └── example
    │                               └── ExampleUnitTest.java
    ├── build.gradle
    ├── Example.iml
    ├── gradle
    │   └── wrapper
    │       ├── gradle-wrapper.jar
    │       └── gradle-wrapper.properties
    ├── gradle.properties
    ├── gradlew
    ├── gradlew.bat
    ├── local.properties
    └── settings.gradle
