### ISSUE TITLE
Leak? when closing even empty editor or project manager 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#37664]
**Godot version:**
4.0.dev.custom_build. 1222541c9

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
When I close even empty project manager I see error
```
ERROR: Some texture bindings were not properly freed (leaked canvasitems?
   at: ~RasterizerCanvasRD (servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:2534)
```
but leak sanitizer and valgrind doesn't show this leak.

To see memory leak 
```
Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x7ffa78739ae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
    #1 0x101393ad in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0x101392ac in operator new(unsigned long, char const*) core/os/memory.cpp:42
    #3 0xf3a7e46 in RasterizerCanvasRD::request_texture_binding(RID, RID, RID, RenderingServer::CanvasItemTextureFilter, RenderingServer::CanvasItemTextureRepeat, RID) servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:197
    #4 0xf3fa2c1 in RasterizerCanvasRD::RasterizerCanvasRD(RasterizerStorageRD*) servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp:2421
    #5 0xeb8bcc4 in RasterizerRD::RasterizerRD() servers/rendering/rasterizer_rd/rasterizer_rd.cpp:175
    #6 0x17f90ae in RasterizerRD::_create_current() servers/rendering/rasterizer_rd/rasterizer_rd.h:81
    #7 0xe635c76 in Rasterizer::create() servers/rendering/rasterizer.cpp:67
    #8 0xe643b64 in RenderingServerRaster::RenderingServerRaster() servers/rendering/rendering_server_raster.cpp:252
    #9 0x185e6c1 in Main::setup2(unsigned long) main/main.cpp:1276
    #10 0x18592c3 in Main::setup(char const*, int, char**, bool) main/main.cpp:1177
    #11 0x17547e0 in main platform/linuxbsd/godot_linuxbsd.cpp:49
    #12 0x7ffa774b31e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
```
this patch must be applied
```
diff --git a/servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp b/servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp
index ba4f4c4acb..8ffc110309 100644
--- a/servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp
+++ b/servers/rendering/rasterizer_rd/rasterizer_canvas_rd.cpp
@@ -2531,15 +2531,15 @@ RasterizerCanvasRD::~RasterizerCanvasRD() {
                _dispose_bindings();
                //anything remains?
                if (bindings.texture_bindings.size()) {
-                       ERR_PRINT("Some texture bindings were not properly freed (leaked canvasitems?");
-                       const TextureBindingID *key = nullptr;
-                       while ((key = bindings.texture_bindings.next(key))) {
-                               TextureBinding *tb = bindings.texture_bindings[*key];
-                               tb->reference_count = 1;
-                               free_texture_binding(*key);
-                       }
-                       //dispose pending
-                       _dispose_bindings();
+//                     ERR_PRINT("Some texture bindings were not properly freed (leaked canvasitems?");
+//                     const TextureBindingID *key = nullptr;
+//                     while ((key = bindings.texture_bindings.next(key))) {
+//                             TextureBinding *tb = bindings.texture_bindings[*key];
+//                             tb->reference_count = 1;
+//                             free_texture_binding(*key);
+//                     }
+//                     //dispose pending
+//                     _dispose_bindings();
                }
        }
```
**Steps to reproduce:**
1.  Run and close any project or project manager

**Comment by qarmin** [comment]
Looks that leaks are fixed already
