### ISSUE TITLE
Invalid public key for Apk Expansion

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#38758]
**Godot version:**
3.2
**OS/device including version:**
Windows 10 - 64 Bit

**Issue description:**
I am exporting for Android, when I checked Enable in Apk Expansion, there is an error displayed: **"Invalid public key for Apk Expansion"**

Where can I get the SALT and Public Key?
What is the details for these two fields, there is no info in the Godot's documentation.

I also get this Error when I put
Salt: "asd"
Public Key: "zxc"

`2020-05-15 23:00:44.556 1419-1419/? E/libc: Access denied finding property "persist.vendor.sys.activitylog"
2020-05-15 23:00:46.822 1419-1584/app.mygame E/ion: ioctl c0044901 failed with code -1: Invalid argument
2020-05-15 23:00:47.127 1419-1419/app.mygame E/LicenseChecker: Invalid key specification.
2020-05-15 23:00:47.139 1419-1419/app.mygame E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.mygame, PID: 1419
    java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
        at com.google.android.vending.licensing.LicenseChecker.generatePublicKey(LicenseChecker.java:123)
        at com.google.android.vending.licensing.LicenseChecker.<init>(LicenseChecker.java:95)
        at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:771)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
     Caused by: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
        at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:281)
        at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:54)
        at java.security.KeyFactory.generatePublic(KeyFactory.java:361)
        at com.google.android.vending.licensing.LicenseChecker.generatePublicKey(LicenseChecker.java:114)
        at com.google.android.vending.licensing.LicenseChecker.<init>(LicenseChecker.java:95) 
        at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:771) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6820) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922) 
     Caused by: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
        at com.android.org.conscrypt.NativeCrypto.EVP_parse_public_key(Native Method)
        at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:279)
        at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:54) 
        at java.security.KeyFactory.generatePublic(KeyFactory.java:361) 
        at com.google.android.vending.licensing.LicenseChecker.generatePublicKey(LicenseChecker.java:114) 
        at com.google.android.vending.licensing.LicenseChecker.<init>(LicenseChecker.java:95) 
        at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:771) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6820) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922) `

**Steps to reproduce:**

1. Click Project.
2. Click Export.
3. Select the Android Template. (I am using the default template from godot's website).
4. Scroll down to Apk Expansion section.
5. Check the Enable.

**Minimal reproduction project:**
- Not needed.

**Comment by volzhs** [comment]
You need the public key from google play console.
It's located at play console > your app > development tools > services & apis.
`Salt` can be any string.

**Comment by nightrobin** [comment]
I see. Thanks @volzhs

**Comment by Tobi-La** [comment]
@volzhs Thanks! Can you give me some hints on how to get the public key exactly? I can download a .der certificate from the google play console under "Play App Signing" and there are some fingerprints shown to me (md5, sha-1 and sha-256)

**Comment by nightrobin** [comment]
> @volzhs Thanks! Can you give me some hints on how to get the public key exactly? I can download a .der certificate from the google play console under "Play App Signing" and there are some fingerprints shown to me (md5, sha-1 and sha-256)
> 
> Also I can choose between app key and upload key

I'm not sure with this, but you can also check: play console > your app > monetisation setup > licensing (Base64-encoded RSA public key), if it is the thing that you need.

**Comment by SnailRabbids** [comment]
Hi all,
can you please explain, which permissions and which key I have to set to make it works? My application works fine when I exporting it as 1 apk/aab file. But when I use Apk Expansion, my application just crashes at start.

And what is "Salt"? What is it expect me set here?

@nightrobin @Tobi-La @volzhs help me please, I'm totally confused :(

**Comment by phil-hudson** [comment]
> Hi all, can you please explain, which permissions and which key I have to set to make it works? My application works fine when I exporting it as 1 apk/aab file. But when I use Apk Expansion, my application just crashes at start.
> 
> And what is "Salt"? What is it expects me set here?
> 
> @nightrobin @Tobi-La @volzhs help me please, I'm totally confused :(

Hey, did you ever get this resolved - I'm having a similar issue with my app crashing on start using APK expansion, currently getting an error:

`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

**Comment by nightrobin** [comment]
> > Hi all, can you please explain, which permissions and which key I have to set to make it works? My application works fine when I exporting it as 1 apk/aab file. But when I use Apk Expansion, my application just crashes at start.
> > 
> > And what is "Salt"? What is it expects me set here?
> > 
> > @nightrobin @Tobi-La @volzhs help me please, I'm totally confused :(
> 
> Hey, did you ever get this resolved - I'm having a similar issue with my app crashing on start using APK expansion, currently getting an error:
> 
> `Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

I think this is unrelated to the salt issue.

Have you tried exporting with custom Android Build? (where your project has an "android" folder)

I think you have to modify the code inside the android folder with this.
[https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a](https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a)

**Comment by phil-hudson** [comment]
Yep tried that too - I'm wondering if it should be filed as a separate issue? I don't think users should have to manually update the gradle.build deps for compatibility when using pretty vanilla godot export features?

Additionally I built a repo project, using custom build templates, pck encryption with APK expansion and was able to reproduce - I'm not sure if others are also having issues, but if you think it can warrant a seperate issue, I'm happy to file one. Thanks!

**Comment by SnailRabbids** [comment]
> 

No, I didn't :(

**Comment by phil-hudson** [comment]
> @phil-hudson
> 
> > Hey, did you ever get this resolved...
> 
> No, I didn't :(

I filed a new issue here, not sure if it is directly related - but thought it might be of interest
