### ISSUE TITLE
startup crash with older (4 months) projects

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#3967]
Well, the backtrace is this: I dunno about anything accepting this,
just testing a new update after some delay.

[New Thread 0x7fffe91a1700 (LWP 31109)]
[New Thread 0x7fffe89a0700 (LWP 31146)]
[New Thread 0x7fffe895f700 (LWP 31147)]
BOOT SPLASH: 
BOOT SPLASH IS : 

Program received signal SIGSEGV, Segmentation fault.
0x0000000001387b85 in StringName::StringName (this=0x7fffffffd190, p_name=...) at core/string_db.cpp:174
warning: Source file is more recent than executable.
174		if (p_name._data && p_name._data->refcount.ref()) {
(gdb) bt
#0  0x0000000001387b85 in StringName::StringName (this=0x7fffffffd190, p_name=...) at core/string_db.cpp:174
#1  0x0000000000fb1b09 in PackedScene::instance (this=0x464bd00, p_gen_edit_state=false) at scene/resources/packed_scene.cpp:67
#2  0x000000000041c99d in Main::start () at main/main.cpp:1331
#3  0x000000000040c3ed in main (argc=1, argv=0x7fffffffe438) at platform/x11/godot_x11.cpp:40

I don't have any test project at hands at the moment though (I test on https://github.com/slapin/simple-rpg, subdir godot, but it is not fully complete there, and I'm not really sure
it is a good idea to update now).

**Comment by slapin** [comment]
After a few subsequent runs problem resolved itself and I can't reproduce it anymore.
Sorry for the noise.
