### ISSUE TITLE
Editor crashes when importing node from scene

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#4048]
**Operating system or device:** Linux

**Issue description**: Importing a second node from another scene, will crash the editor.

**Steps to reproduce:** In a scene, import a node from another scene. It will work correctly. Then import a second node from that same scene again, the editor will crash.

**Comment by neikeq** [comment]
I can confirm this bug in the current HEAD with Ubuntu 15.10 64bits. If you browse the same scene again, before importing the second node, the editor **won't** crash. Back trace:

```
#0  0x00007ffff5b98293 in __dynamic_cast ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000430fad in Object::cast_to<Node> (this=0x832b930)
    at core/object.h:493
#2  0x00000000015fc026 in Variant::operator Node* (this=0x7fffffffc2b0)
    at core/variant.cpp:1809
#3  0x0000000000c42e10 in EditorSubScene::ok_pressed (this=0x3d75d90)
    at tools/editor/editor_sub_scene.cpp:115
#4  0x0000000000db86e4 in AcceptDialog::_ok_pressed (this=0x3d75d90)
    at scene/gui/dialogs.cpp:212
#5  0x00000000004a5d1c in MethodBind0::call (this=0x2d3ecc0, 
    p_object=0x3d75d90, p_args=0x7fffffffc6d0, p_arg_count=0, r_error=...)
    at core/method_bind.inc:47
#6  0x00000000015ce1ea in Object::call (this=0x3d75d90, p_method=..., 
    p_args=0x7fffffffc6d0, p_argcount=0, r_error=...) at core/object.cpp:891
#7  0x00000000015cfea0 in Object::emit_signal (this=0x3d80990, p_name=..., 
    p_args=0x7fffffffc6d0, p_argcount=0) at core/object.cpp:1204
#8  0x00000000015d0346 in Object::emit_signal (this=0x3d80990, p_name=..., 
    p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at core/object.cpp:1247
#9  0x0000000000dd77e3 in Tree::propagate_mouse_event (this=0x3d80990, 
    p_pos=..., x_ofs=12, y_ofs=48, p_doubleclick=true, p_item=0x8382150, 
    p_button=1, p_mod=...) at scene/gui/tree.cpp:1519
```

**Comment by TheHX** [comment]
I can confirm this bug too, one thing i noticed is when using the "Ok" button the dialog works fine, but when i double-click a item, next time i use the dialog it crashes. And i get this error in the console:
```
ERROR: clear: Condition ' blocked>0 ' is true.
   At: scene/gui/tree.cpp:2750.
```
