### ISSUE TITLE
Crash when trying to create/modify image when locked

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#40888]
**Godot version:**
Godot 3.2.3 rc 2

**Issue description:**
Address Sanitizer log
```
ERROR: resize: Can't resize PoolVector if locked.
   At: ./core/pool_vector.h:546.
=================================================================
==95889==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6280000479c8 at pc 0x7ff0b5e8bf36 bp 0x7fffe26f9070 sp 0x7fffe26f8818
WRITE of size 2032800 at 0x6280000479c8 thread T0
    #0 0x7ff0b5e8bf35 in __interceptor_memset (/lib/x86_64-linux-gnu/libasan.so.6+0x39f35)
    #1 0xe63637c in Image::create(int, int, bool, Image::Format) core/image.cpp:1595
    #2 0xe6c859e in Image::_create_empty(int, int, bool, Image::Format) (/usr/bin/godots+0xe6c859e)
    #3 0xe70c5f7 in MethodBind4<int, int, bool, Image::Format>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:3115
    #4 0xe7729a1 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #5 0xe9e932f in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1128
    #6 0x1a773df in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1088
    #7 0x18ad042 in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1268
    #8 0x18ad2ee in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1275
    #9 0x9522e08 in Node::_notification(int) scene/main/node.cpp:149
    #10 0x1761b5b in Node::_notificationv(int, bool) scene/main/node.h:46
    #11 0x1763fc6 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #12 0xaf47732 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #13 0xe772e31 in Object::notification(int, bool) core/object.cpp:932
    #14 0x9524d7b in Node::_propagate_ready() scene/main/node.cpp:196
    #15 0x95245e1 in Node::_propagate_ready() scene/main/node.cpp:188
    #16 0x957145e in Node::_set_tree(SceneTree*) scene/main/node.cpp:2571
    #17 0x96355de in SceneTree::init() scene/main/scene_tree.cpp:463
    #18 0x14c12c4 in OS_X11::run() platform/x11/os_x11.cpp:3220
    #19 0x143c4e5 in main platform/x11/godot_x11.cpp:56
    #20 0x7ff0b4a560b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #21 0x143c0ed in _start (/usr/bin/godots+0x143c0ed)

0x6280000479c8 is located 0 bytes to the right of 14536-byte region [0x628000044100,0x6280000479c8)
allocated by thread T0 here:
    #0 0x7ff0b5f02517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0xeca394b in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0x169fb6e in PoolVector<unsigned char>::resize(int) core/pool_vector.h:582
    #3 0xe6361c0 in Image::create(int, int, bool, Image::Format) core/image.cpp:1592
    #4 0xe6c859e in Image::_create_empty(int, int, bool, Image::Format) (/usr/bin/godots+0xe6c859e)
    #5 0xe70c5f7 in MethodBind4<int, int, bool, Image::Format>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:3115
    #6 0xe7729a1 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #7 0xe9e932f in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1128
    #8 0x1a773df in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1088
    #9 0x18ad042 in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1268
    #10 0x18ad2ee in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1275
    #11 0x9522e08 in Node::_notification(int) scene/main/node.cpp:149
    #12 0x1761b5b in Node::_notificationv(int, bool) scene/main/node.h:46
    #13 0x1763fc6 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #14 0xaf47732 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #15 0xe772e31 in Object::notification(int, bool) core/object.cpp:932
    #16 0x9524d7b in Node::_propagate_ready() scene/main/node.cpp:196
    #17 0x95245e1 in Node::_propagate_ready() scene/main/node.cpp:188
    #18 0x957145e in Node::_set_tree(SceneTree*) scene/main/node.cpp:2571
    #19 0x96355de in SceneTree::init() scene/main/scene_tree.cpp:463
    #20 0x14c12c4 in OS_X11::run() platform/x11/os_x11.cpp:3220
    #21 0x143c4e5 in main platform/x11/godot_x11.cpp:56
    #22 0x7ff0b4a560b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)


```

**Example of code(reproduction project have more examples of usage of invalid memory):**
```
extends Node2D

func _ready() -> void:
	var img : Image = Image.new()
	img.create(66, 55, false, Image.FORMAT_RGBA8)
	img.lock()
	img.create(770, 660, false, Image.FORMAT_RGBA8)
	img.unlock()
```

**Reproduction project:**
[TheWorstGodotTestProject.zip](https://github.com/godotengine/godot/files/5005502/TheWorstGodotTestProject.zip)

**Comment by akien-mga** [comment]
Fixed by #41029.
