### ISSUE TITLE
Leaks when using plugin dialog

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#41284]
**Godot version:**
Godot 3.2.3 rc 3

**Issue description:**
```
Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f5896160517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0xee45b9d in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0xee45a9c in operator new(unsigned long, char const*) core/os/memory.cpp:42
    #3 0x51dc2c4 in DirAccess* DirAccess::_create_builtin<DirAccessUnix>() core/os/dir_access.h:65
    #4 0xed60250 in DirAccess::create(DirAccess::AccessType) core/os/dir_access.cpp:271
    #5 0x6822fb9 in PluginConfigDialog::_on_confirmed() editor/plugin_config_dialog.cpp:55
    #6 0x17e9f1b in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #7 0xe911237 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #8 0xe91aff2 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1249
    #9 0xe91d01e in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1306
    #10 0x9bf5602 in AcceptDialog::_ok_pressed() scene/gui/dialogs.cpp:410
    #11 0x17e9f1b in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #12 0xe911237 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #13 0xe91aff2 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1249
    #14 0xe91d01e in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1306
    #15 0x999247f in BaseButton::_pressed() scene/gui/base_button.cpp:135
    #16 0x999627d in BaseButton::on_action_event(Ref<InputEvent>) scene/gui/base_button.cpp:169
    #17 0x998edbf in BaseButton::_gui_input(Ref<InputEvent>) scene/gui/base_button.cpp:64
    #18 0x677c32c in MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #19 0xe90ce9c in Object::call_multilevel(StringName const&, Variant const**, int) core/object.cpp:764
    #20 0xe90ff64 in Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:864
    #21 0x9893be8 in Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) scene/main/viewport.cpp:1669
    #22 0x98a324b in Viewport::_gui_input_event(Ref<InputEvent>) scene/main/viewport.cpp:2049
    #23 0x98c722c in Viewport::input(Ref<InputEvent> const&) scene/main/viewport.cpp:2825
    #24 0x9887683 in Viewport::_vp_input(Ref<InputEvent> const&) scene/main/viewport.cpp:1446
    #25 0x23d11fa in MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #26 0xe911237 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #27 0xe90f99f in Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:848
    #28 0x977578b in SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) scene/main/scene_tree.cpp:275
    #29 0x977ac0f in SceneTree::input_event(Ref<InputEvent> const&) scene/main/scene_tree.cpp:431

Indirect leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f5896160517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0xee45b9d in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0x34d9ae7 in CowData<wchar_t>::resize(int) core/cowdata.h:279
    #3 0x583ed4b in String::resize(int) core/ustring.h:154
    #4 0xeae63c8 in String::parse_utf8(char const*, int) core/ustring.cpp:1471
    #5 0x58761c0 in DirAccessUnix::DirAccessUnix() drivers/unix/dir_access_unix.cpp:421
    #6 0x51dc2f1 in DirAccess* DirAccess::_create_builtin<DirAccessUnix>() core/os/dir_access.h:65
    #7 0xed60250 in DirAccess::create(DirAccess::AccessType) core/os/dir_access.cpp:271
    #8 0x6822fb9 in PluginConfigDialog::_on_confirmed() editor/plugin_config_dialog.cpp:55
    #9 0x17e9f1b in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #10 0xe911237 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #11 0xe91aff2 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1249
    #12 0xe91d01e in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1306
    #13 0x9bf5602 in AcceptDialog::_ok_pressed() scene/gui/dialogs.cpp:410
    #14 0x17e9f1b in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #15 0xe911237 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922
    #16 0xe91aff2 in Object::emit_signal(StringName const&, Variant const**, int) core/object.cpp:1249
    #17 0xe91d01e in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:1306
    #18 0x999247f in BaseButton::_pressed() scene/gui/base_button.cpp:135
    #19 0x999627d in BaseButton::on_action_event(Ref<InputEvent>) scene/gui/base_button.cpp:169
    #20 0x998edbf in BaseButton::_gui_input(Ref<InputEvent>) scene/gui/base_button.cpp:64
    #21 0x677c32c in MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #22 0xe90ce9c in Object::call_multilevel(StringName const&, Variant const**, int) core/object.cpp:764
    #23 0xe90ff64 in Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) core/object.cpp:864
    #24 0x9893be8 in Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) scene/main/viewport.cpp:1669
    #25 0x98a324b in Viewport::_gui_input_event(Ref<InputEvent>) scene/main/viewport.cpp:2049
    #26 0x98c722c in Viewport::input(Ref<InputEvent> const&) scene/main/viewport.cpp:2825
    #27 0x9887683 in Viewport::_vp_input(Ref<InputEvent> const&) scene/main/viewport.cpp:1446
    #28 0x23d11fa in MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #29 0xe911237 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:922

```

**Steps to reproduce:**
Not sure, but still it can be fixed easy

**Comment by qarmin** [comment]
It is fixed in 4.0
