### ISSUE TITLE
[2.1] Test reports for 2.1.7 pre-release builds

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#41300]
I'm working on a 2.1.7 release to solve two main issues for users who have games released with 2.1.x which they need to update. Namely:
- iOS App Store requires SDK 13 as of June 30, 2020: #41186
- Android Play Store requires API level 29 as of August 3, 2020: #41279

Additionally, 2.1.7 will include some more fixes, notably for proper support of macOS Mojave and Catalina. macOS binaries now build against a more recent SDK, with no 32-bit support, so the 32-bit/fat binaries have been deprecated, so macOS is x86_64 only now (no arm64 support yet for Big Sur).

This issue is to gather direct test reports on pre-release builds of 2.1.7, to ensure that we get all main platforms tested before labeling it stable.

**Important:** If you are interested in the 2.1.7 release for one or more projects that you mention, please make yourself known to me here, or by email (`remi@godotengine.org`). I don't expect a lot of remaining 2.1.x users, so I need to know who will need this release (and hopefully you'll be able to help test it).

## Current build

2.1.7 RC **20200815**
https://downloads.tuxfamily.org/godotengine/2.1.7/rc/20200815/

Changelog: https://downloads.tuxfamily.org/godotengine/2.1.7/rc/20200815/Godot_v2.1.7-rc_20200815_changelog.txt

## Test matrix

I need at least one, ideally more, tests for each platform port (possibly with an exception for WinRT as I doubt anyone really uses it on 2.1.x).

Please test your projects on all the platforms you can, and of course especially on the platforms you support for your released projects.

Report back here with the following information:
- Project tested (if it's not public, you can simply give some details about how big it is, 2D or 3D, etc.)
- Platforms tested (including the OS version, if relevant the GPU and drivers, and for export templates whether you tested Release or Debug)
- Everything should work as it used to in 2.1.6 (or better :)). Any unplanned behavior change might be a regression and is worth mentioning here.
- In particular, please test thoroughly the Android, iOS and macOS ports, which got the most changes from their vendor, and adequately the most changes in 2.1.7 too.
- If you can, please check that platform stores (e.g. Android Play Store and Apple App Store) where you use to ship your game are happy with the new update to fulfill platform requirements.

I'll fill the test matrix below with your results:

| Platform | Editor | Release Template | Debug Template |
|---|---|---|---|
| Android | n/a | - | - |
| HTML5 | n/a | - | - |
| iOS | n/a | - | - |
| Linux | - | - | - |
| macOS | - | - | - |
| Server (Linux) | - | n/a | n/a |
| Windows | - | - | - |
| WinRT (UWP) | n/a | - | - |

**Comment by qarmin** [comment]
When running project manager compiled with flags `scons p=x11 -j8  CCFLAGS="-fsanitize=address,undefined" LINKFLAGS="-fsanitize=address,undefined" use_llvm=yes`, I have this invalid read
```
==128292==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f132a07fad4 at pc 0x0000010652c9 bp 0x7ffd795c97a0 sp 0x7ffd795c8f60
READ of size 205489 at 0x7f132a07fad4 thread T0
    #0 0x10652c8 in strlen (/mnt/Miecz/godot2.1/bin/godot.x11.tools.64.llvm+0x10652c8)
    #1 0x1dbf5ec in mem_puts /mnt/Miecz/godot2.1/thirdparty/openssl/crypto/bio/bss_mem.c:311:9
    #2 0x1daeafe in BIO_puts /mnt/Miecz/godot2.1/thirdparty/openssl/crypto/bio/bio_lib.c:273:9
    #3 0x19d0441 in StreamPeerOpenSSL::_load_certs(DVector<unsigned char> const&) /mnt/Miecz/godot2.1/modules/openssl/stream_peer_openssl.cpp:578:2
    #4 0xb423120 in StreamPeerSSL::load_certs_from_memory(DVector<unsigned char> const&) /mnt/Miecz/godot2.1/core/io/stream_peer_ssl.cpp:46:3
    #5 0x3f62e81 in editor_initialize_certificates() /mnt/Miecz/godot2.1/editor/editor_initialize_ssl.cpp:45:2
    #6 0x44c0655 in ProjectListFilter::ProjectListFilter() /mnt/Miecz/godot2.1/editor/project_manager.cpp:1494:2
    #7 0x44af16e in ProjectManager::ProjectManager() /mnt/Miecz/godot2.1/editor/project_manager.cpp:1289:19
    #8 0x11c3c1b in Main::start() /mnt/Miecz/godot2.1/main/main.cpp:1468:31
    #9 0x10fd1d5 in main /mnt/Miecz/godot2.1/platform/x11/godot_x11.cpp:51:6
    #10 0x7f13311ba0b2 in __libc_start_main /build/glibc-YYA7BZ/glibc-2.31/csu/../csu/libc-start.c:308:16
    #11 0x105269d in _start (/mnt/Miecz/godot2.1/bin/godot.x11.tools.64.llvm+0x105269d)

0x7f132a07fad4 is located 0 bytes to the right of 205524-byte region [0x7f132a04d800,0x7f132a07fad4)
allocated by thread T0 here:
    #0 0x10caddd in malloc (/mnt/Miecz/godot2.1/bin/godot.x11.tools.64.llvm+0x10caddd)
    #1 0x369547b in MemoryPoolStaticMalloc::_alloc(unsigned long, char const*) /mnt/Miecz/godot2.1/drivers/unix/memory_pool_static_malloc.cpp:81:14
    #2 0x3695131 in MemoryPoolStaticMalloc::alloc(unsigned long, char const*) /mnt/Miecz/godot2.1/drivers/unix/memory_pool_static_malloc.cpp:49:9
    #3 0xb13a959 in Memory::alloc_static(unsigned long, char const*) /mnt/Miecz/godot2.1/core/os/memory.cpp:50:44
    #4 0xb133203 in MemoryPoolDynamicStatic::alloc(unsigned long, char const*) /mnt/Miecz/godot2.1/core/os/memory_pool_dynamic_static.cpp:86:19
    #5 0xb13b6b4 in Memory::alloc_dynamic(unsigned long, char const*) /mnt/Miecz/godot2.1/core/os/memory.cpp:89:65
    #6 0x1285911 in DVector<unsigned char>::resize(int) /mnt/Miecz/godot2.1/core/dvector.h:354:10
    #7 0x3f62e0f in editor_initialize_certificates() /mnt/Miecz/godot2.1/editor/editor_initialize_ssl.cpp:39:7
    #8 0x44c0655 in ProjectListFilter::ProjectListFilter() /mnt/Miecz/godot2.1/editor/project_manager.cpp:1494:2
    #9 0x44af16e in ProjectManager::ProjectManager() /mnt/Miecz/godot2.1/editor/project_manager.cpp:1289:19
    #10 0x11c3c1b in Main::start() /mnt/Miecz/godot2.1/main/main.cpp:1468:31
    #11 0x10fd1d5 in main /mnt/Miecz/godot2.1/platform/x11/godot_x11.cpp:51:6
    #12 0x7f13311ba0b2 in __libc_start_main /build/glibc-YYA7BZ/glibc-2.31/csu/../csu/libc-start.c:308:16
```
It seems to read certificates, but doesn't properly set memory.
Data is readed from const char* `_certs_uncompressed_size` with size 205488 but requested element 205489 is out of range.

**Comment by zoiba** [comment]
OSX export is broken.
I'm getting this error on the console:
```
ERROR: export_project: Requested template binary 'godot_osx_release.' not found. It might be missing from your template archive.
   At: platform/osx/export/export.cpp:532.
ERROR: export_platform: Exporting failed!
   At: editor/project_export.cpp:532.
```

**Comment by akien-mga** [comment]
Thanks for the update, I'll fix the OSX issue next week.

**Comment by anandHobbyGameDev** [comment]
hello, is this working for Android??
My game also contains Google Admob too!

I did not know that Android had security updates. I worked on godot 2.1.6 on a Hobby Game for past 4 months. While Uploading to playstore yesterday, the Android requirements came up!  

With 2.1.7 and this export template, even my debug game is not starting.

Error as below:

Starting: Intent { act=android.intent.action.MAIN cmp=org.godotengine.IDY/org.godotengine.godot.Godot }
ERROR: OS_Windows::kill: Condition ' !process_map->has(p_pid) ' is true. returned: FAILED
   At: platform\windows\os_windows.cpp:2232


Awaiting reply in anticipation. 
Regards,
Anand

**Comment by akien-mga** [comment]
> Starting: Intent { act=android.intent.action.MAIN cmp=org.godotengine.IDY/org.godotengine.godot.Godot }
ERROR: OS_Windows::kill: Condition ' !process_map->has(p_pid) ' is true. returned: FAILED
At: platform\windows\os_windows.cpp:2232

Is this something that you see in the Godot console while running the game on Android?

Can you use `adb logcat` to retrieve logs after running the game, to see if there's any error or crash message?
The error above is just about the Windows version of the editor not being able to terminate a process (possibly `adb`).

**Comment by akien-mga** [comment]
From https://github.com/godotengine/godot/issues/41186#issuecomment-681998255:

> tested the html5 export and it seems it's not working anymore
this is the project I exported
http://www.officinepixel.com/test/cosmogas/cosmodidactic/
I remember it was functioning in some version of 2.x series
