### ISSUE TITLE
Uncaught RuntimeError: unreachable + Uncaught RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by Thaina** [godotengine/godot#41400]
**Godot version:**
Godot Engine v3.2.2.stable.mono.custom_build.6a9fbafcb

**OS/device including version:**
Windows 10 use GLES2

**Issue description:**
I try to build HTML with including this package

```C#
    <PackageReference Include="System.Reactive.Linq">
      <Version>4.4.1</Version>
    </PackageReference>
```

Which can build as windows standalone. But cannot exported as HTML5. It thrown error as below

```
Uncaught RuntimeError: unreachable
    at GDMono::_load_api_assemblies() (<anonymous>:wasm-function[22791]:0x3faa2d)
    at GDMono::initialize_load_assemblies() (<anonymous>:wasm-function[64857]:0xd57256)
    at CSharpLanguage::init() (<anonymous>:wasm-function[66902]:0xde26f0)
```

```
Uncaught RuntimeError: function signature mismatch
    at Object::notification(int, bool) (<anonymous>:wasm-function[1068]:0x485d4)
    at send_notification (<anonymous>:wasm-function[27837]:0x6556ee)
    at RuntimeEnvironment.Module._send_notification (http://localhost:8060/tmp_js_export.js:7:374979)
```

```
Uncaught RuntimeError: function signature mismatch
    at Object::notification(int, bool) (<anonymous>:wasm-function[1068]:0x485d4)
    at send_notification (<anonymous>:wasm-function[27837]:0x6556ee)
    at RuntimeEnvironment.Module._send_notification (http://localhost:8060/tmp_js_export.js:7:374979)
    at RuntimeEnvironment.ASM_CONSTS (http://localhost:8060/tmp_js_export.js:7:20293)
    at _emscripten_asm_const_iii (http://localhost:8060/tmp_js_export.js:7:32118)
    at focus_canvas() (<anonymous>:wasm-function[14541]:0x2c0d7d)
```

**Steps to reproduce:**
- Create project normally
- Add `System.Reactive.Linq` as above into `.csproj`
- Run `msbuild /t:restore`
- Add export HTML5

![image](https://user-images.githubusercontent.com/1042507/90790179-fade5980-e331-11ea-96ee-54a08f123740.png)

- Run from here

![image](https://user-images.githubusercontent.com/1042507/90790356-26f9da80-e332-11ea-8ae4-902036a707ad.png)

It give me black void screen in chrome, then I try to see console log and it has error like I have pasted above

**Minimal reproduction project:**

[TTTT.zip](https://github.com/godotengine/godot/files/5103921/TTTT.zip)

**Comment by Thaina** [comment]
More log

```
Assembly GodotSharp[0x2583958] added to domain GodotEngine.Domain.Scripts, ref_count=1
tmp_js_export.js:8 Loading reference 0 of .mono/assemblies/Debug/GodotSharp.dll asmctx DEFAULT, looking for netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
tmp_js_export.js:8 Config attempting to parse: ''.
tmp_js_export.js:8 Image addref netstandard[0x2579750] (asmctx DEFAULT) -> .mono/assemblies/Debug/netstandard.dll[0x2585518]: 2
tmp_js_export.js:8 Prepared to set up assembly 'netstandard' (.mono/assemblies/Debug/netstandard.dll)
tmp_js_export.js:8 Assembly netstandard[0x2579750] added to domain GodotEngine.Domain.Scripts, ref_count=1
tmp_js_export.js:8 Assembly Ref addref GodotSharp[0x2583958] -> netstandard[0x2579750]: 2
tmp_js_export.js:8 Loading reference 0 of .mono/assemblies/Debug/netstandard.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
tmp_js_export.js:8 Assembly Ref addref netstandard[0x2579750] -> mscorlib[0x146f310]: 3
tmp_js_export.js:8 **ERROR**: The assembly 'GodotSharp' is out of sync.
put_char @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/mono/mono_gd/gd_mono.cpp:954:_load_api_assemblies() - The assembly 'GodotSharp' is out of sync.
put_char @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: FATAL: Method failed.
put_char @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/mono/mono_gd/gd_mono.cpp:965:_load_api_assemblies() - FATAL: Method failed.
put_char @ tmp_js_export.js:8
wasm://wasm/058492da:1 Uncaught RuntimeError: unreachable
```

**Comment by Thaina** [comment]
@neikeq I think I have solve this. It was just out of sync, I just need to build export template myself
