### ISSUE TITLE
Pressing "Play button" in SampleLibrary crashes the engine

### ISSUE THREAD

**Issue by batmanasb** [godotengine/godot#4343]
Sorry if this is rushed, I'm mid way into Ludum Dare 35!

**Operating system or device:**
Linux Mint 17.3 x64
Using the Godot 2.0.2 official release for x11

**Issue description** (what happened, and what was expected):
When I [press the "Play button" on this screen](http://i.imgur.com/rrqouOD.png) the engine just crashes.

**Steps to reproduce:**
Make a SamplePlayer node
In the inspector, make a new SampleLibrary
Go into SampleLibrary (> arrow)
Open any .smp or .wav file
Press play button
Crash occurs

**Link to minimal example project** (optional but very welcome):
[test.zip](https://github.com/godotengine/godot/files/222424/test.zip)

**Comment by neikeq** [comment]
I can reproduce the same crash in c04b3ed, but only when building the editor with `release_debug` target. It does not seem to happen with debug builds. Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5b98293 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) backtrace
#0  0x00007ffff5b98293 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000826826 in SampleLibraryEditor::_button_pressed(Object*, int, int) ()
#2  0x000000000076a372 in MethodBind3<Object*, int, int>::call(Object*, Variant const**, int, Variant::CallError&) ()
#3  0x000000000144e247 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#4  0x000000000145581c in Object::emit_signal(StringName const&, Variant const**, int) ()
#5  0x0000000001455fa0 in Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) ()
#6  0x0000000000cacf88 in Tree::_input_event(InputEvent) ()
#7  0x00000000007cab07 in MethodBind1<InputEvent>::call(Object*, Variant const**, int, Variant::CallError&) ()
#8  0x000000000144fe99 in Object::call_multilevel(StringName const&, Variant const**, int) ()
#9  0x000000000144d9e1 in Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) ()
#10 0x0000000000bf3e08 in Viewport::_gui_call_input(Control*, InputEvent const&) ()
#11 0x0000000000bfe1ab in Viewport::_gui_input_event(InputEvent) ()
#12 0x0000000000bff1b1 in Viewport::input(InputEvent const&) ()
#13 0x0000000000bff33a in Viewport::_vp_input(InputEvent const&) ()
#14 0x000000000072cf68 in MethodBind1<InputEvent const&>::call(Object*, Variant const**, int, Variant::CallError&) ()
#15 0x000000000144e247 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#16 0x000000000144d961 in Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) ()
#17 0x0000000000bc4c84 in SceneTree::call_group(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) ()
#18 0x0000000000bc6618 in SceneTree::input_event(InputEvent const&) ()
#19 0x000000000041a718 in InputDefault::parse_input_event(InputEvent const&) ()
#20 0x0000000000414594 in OS_X11::process_xevents() ()
#21 0x0000000000414d20 in OS_X11::run() ()
#22 0x00000000004111b0 in main ()
```

**Comment by reduz** [comment]
this was fixed a while ago, closing
