### ISSUE TITLE
Unexpected quit when calling the 'find' method in 'RegEx' class.

### ISSUE THREAD

**Issue by mownier** [godotengine/godot#4346]
**Operating system or device:**
Ubuntu 15.10

**Issue description** (what happened, and what was expected):
The program quits when trying to invoke the `find` method of an instance of a `RegEx` class.
You can check the regex demo. The demo quits unexpectedly.

**Steps to reproduce:**
1. Create a scene.
2. Add a `Node` as the root.
3. Create a script for the root node.
4. Incorporate the snippet below.
5. Run the current scene (press F6). _(expectation: program quits)_
6. Comment `regex.find("test")`.
7. Press F6. _(expectation: program ok)_

```gdscript
func _ready():
    var pattern = "[a-z][a-z0-9]+"
    var regex = RegEx.new()
    regex.compile(pattern)
    if regex.is_valid():
        print("Regex valid")
    else:
        print("Regex not valid")
    regex.find("test")
```

**Comment by akien-mga** [comment]
I can confirm that in the master branch, but not in 2.0.2. It looks like nrex 0.2 broke something @leezh.

**Comment by akien-mga** [comment]
Backtrace:
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x000000000052f06b in memdelete_arr<int> (p_class=0x0) at core/os/memory.h:343
343             for (unsigned int i=0;i<*elems;i++) {
(gdb) bt
#0  0x000000000052f06b in memdelete_arr<int> (p_class=0x0) at core/os/memory.h:343
#1  0x00000000006e3169 in nrex_array<int>::~nrex_array (this=0x7fffffffbcb8, __in_chrg=<optimized out>) at drivers/nrex/nrex.cpp:80
#2  0x00000000006e310c in nrex_search::~nrex_search (this=0x7fffffffbca0, __in_chrg=<optimized out>) at drivers/nrex/nrex.cpp:193
#3  0x00000000006e1a54 in nrex::match (this=0x34a7d88, str=0x34bb278 L"test", captures=0x34b5e48, offset=0, end=-1) at drivers/nrex/nrex.cpp:1468
#4  0x00000000005bfe57 in RegEx::find (this=0x34a7ce0, p_text=..., p_start=0, p_end=-1) at drivers/nrex/regex.cpp:100
#5  0x00000000005c3ce7 in MethodBind3RC<int, String const&, int, int>::call (this=0x24bf490, p_object=0x34a7ce0, p_args=0x7fffffffc0d0, p_arg_count=1, r_error=...)
    at ./core/method_bind.inc:2237
#6  0x00000000016f4025 in Object::call (this=0x34a7ce0, p_method=..., p_args=0x7fffffffc0d0, p_argcount=1, r_error=...) at core/object.cpp:891
#7  0x0000000001685885 in Variant::call (this=0x7fffffffbff8, p_method=..., p_args=0x7fffffffc0d0, p_argcount=1, r_error=...) at core/variant_call.cpp:949
#8  0x000000000043caac in GDFunction::call (this=0x34591c8, p_instance=0x34199d0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gd_script.cpp:672
#9  0x0000000000447521 in GDInstance::_ml_call_reversed (this=0x34199d0, sptr=0x33698d0, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gd_script.cpp:2527
#10 0x0000000000447595 in GDInstance::call_multilevel_reversed (this=0x34199d0, p_method=..., p_args=0x0, p_argcount=0) at modules/gdscript/gd_script.cpp:2535
#11 0x0000000000de0121 in Node::_notification (this=0x3420230, p_notification=13) at scene/main/node.cpp:106
#12 0x000000000049c070 in Node::_notificationv (this=0x3420230, p_notification=13, p_reversed=false) at ./scene/main/node.h:44
#13 0x00000000004cfbdd in CanvasItem::_notificationv (this=0x3420230, p_notification=13, p_reversed=false) at ./scene/2d/canvas_item.h:89
#14 0x00000000004d01ed in Control::_notificationv (this=0x3420230, p_notification=13, p_reversed=false) at ./scene/gui/control.h:49
#15 0x00000000016f41a4 in Object::notification (this=0x3420230, p_notification=13, p_reversed=false) at core/object.cpp:903
#16 0x0000000000de04ba in Node::_propagate_ready (this=0x3420230) at scene/main/node.cpp:149
#17 0x0000000000de0487 in Node::_propagate_ready (this=0x32b4660) at scene/main/node.cpp:146
#18 0x0000000000de824c in Node::_set_tree (this=0x32b4660, p_tree=0x32b5e60) at scene/main/node.cpp:1891
#19 0x0000000000dfc217 in SceneTree::init (this=0x32b5e60) at scene/main/scene_main_loop.cpp:478
#20 0x00000000004141d0 in OS_X11::run (this=0x7fffffffd640) at platform/x11/os_x11.cpp:1762
#21 0x000000000040dfd0 in main (argc=1, argv=0x7fffffffdad8) at platform/x11/godot_x11.cpp:41
```

**Comment by leezh** [comment]
Yeah. Apparently it was a pretty obvious bug. I've pushed out a fix.

https://github.com/godotengine/godot/pull/4364
