### ISSUE TITLE
[FBX] Memory leak when importing fbx model

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43819]
**Godot version:**
3.2.4.beta.custom_build. 7dfd4ced5

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When I import minimal project then I got this leak
```
Direct leak of 200192 byte(s) in 3128 object(s) allocated from:
    #0 0x7f3cc5ccaf17 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
    #1 0x3e5244f in FBXDocParser::FbxPose::FbxPose(unsigned long, FBXDocParser::Element*, FBXDocParser::Document const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) modules/fbx/fbx_parser/FBXPose.cpp:94
    #2 0x3d542f0 in FBXDocParser::LazyObject::LoadObject() modules/fbx/fbx_parser/FBXDocument.cpp:156
    #3 0x2ccea22 in FBXDocParser::FbxPose const* FBXDocParser::LazyObject::Get<FBXDocParser::FbxPose>() modules/fbx/fbx_parser/FBXDocument.h:94
    #4 0x2c8d509 in EditorSceneImporterFBX::_generate_scene(String const&, FBXDocParser::Document const*, unsigned int, int, int) modules/fbx/editor_scene_importer_fbx.cpp:539
    #5 0x2c863b4 in EditorSceneImporterFBX::import_scene(String const&, unsigned int, int, List<String, DefaultAllocator>*, Error*) modules/fbx/editor_scene_importer_fbx.cpp:154
    #6 0x7027da4 in ResourceImporterScene::import(String const&, String const&, Map<StringName, Variant, Comparator<StringName>, DefaultAllocator> const&, List<String, DefaultAllocator>*, List<String, DefaultAllocator>*, Variant*) editor/import/resource_importer_scene.cpp:1320
    #7 0x5b0b18e in EditorFileSystem::_reimport_file(String const&) editor/editor_file_system.cpp:1798
    #8 0x5b16786 in EditorFileSystem::reimport_files(Vector<String> const&) editor/editor_file_system.cpp:1996
    #9 0x5ad34ac in EditorFileSystem::_update_scan_actions() editor/editor_file_system.cpp:589
    #10 0x5aed26d in EditorFileSystem::_notification(int) editor/editor_file_system.cpp:1174
    #11 0x5b268d5 in EditorFileSystem::_notificationv(int, bool) (/usr/bin/godots+0x5b268d5)
    #12 0xe78b563 in Object::notification(int, bool) core/object.cpp:929
    #13 0x9577333 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:985
    #14 0x9567bf5 in SceneTree::idle(float) scene/main/scene_tree.cpp:525
    #15 0x1539ba4 in Main::iteration() main/main.cpp:2103
    #16 0x142d3ac in OS_X11::run() platform/x11/os_x11.cpp:3410
    #17 0x139eb56 in main platform/x11/godot_x11.cpp:56
    #18 0x7f3cc48040b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

```

**Steps to reproduce:**
Compile Godot with sanitizers support
```
scons p=x11 use_asan=yes -j8
```
run with it help minimal project

**Minimal reproduction project:**
https://github.com/godotengine/godot/files/5590346/fbx_bug_project.zip

**Comment by RevoluPowered** [comment]
My plan is to move all FBX objects to an explicit cleanup step. The existing parser has some weird edge cases like this where it can leak in some cases due to the poor ownership of data in the assimp parser.

This is on my list already to sort but it most likely will be next week.

**Comment by RevoluPowered** [comment]
Leak is gone in latest release but the files are blocked by:
"We can't import blender FBX files, they're not implemented correctly at export time and would require several hacks in the FBX importer which could break Maya imports."

**Comment by RevoluPowered** [comment]
#44402 blender support tracker
