### ISSUE TITLE
print_line causing lockups in Godot 4

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#44065]
**Godot version:**

Godot 4.0 master latest version df4fe11

**OS/device including version:**
Linux Mint 20
Intel Core i5-7500T
Intel HD graphics 630

**Issue description:**

Issuing a large amount of `print_line`s causes freezes and lockups when running in a debugger from QT creator.

**Steps to reproduce:**
I tried spamming `print` from gd script but it doesn't appear to cause it, I've only got it to work from c++.
e.g. In vulkan_context.cpp, add this spamming to the start of `swap_buffers`:
```
Error VulkanContext::swap_buffers() {
	for (int n=0; n<128; n++)
		print_line("swapbuffers?");
	
	if (!queues_initialized) {
		return OK;
	}
```
Now I start debugging the project manager from QT creator, choose a project, and it starts doing a swap_buffers every frame, and pretty soon freezes once you start opening menus (opening lots of menus (OS windows)) seems to be associated, I'll put more info as I find it.

Also relevant, I set it this project to `log_to_file` in the project settings. I'll try turning that off and report back.

**Minimal reproduction project:**

**Comment by lawnjelly** [comment]
@akien-mga managed to reproduce and get a call stack with gdb:

```
0x00007ffff7815f4f in write () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7815f4f in write () from /lib64/libc.so.6
#1  0x00007ffff77aa455 in _IO_file_write@@GLIBC_2.2.5 () from /lib64/libc.so.6
#2  0x00007ffff77a9876 in new_do_write () from /lib64/libc.so.6
#3  0x00007ffff77ab4b9 in __GI__IO_do_write () from /lib64/libc.so.6
#4  0x00007ffff77a96a8 in __GI__IO_file_sync () from /lib64/libc.so.6
#5  0x00007ffff779eed2 in fflush () from /lib64/libc.so.6
#6  0x0000000004f6b204 in StdLogger::logv (this=0x919b460, p_format=0x7b83d8c "%s\n", p_list=0x7fffffffc940, p_err=false) at core/io/logger.cpp:232
#7  0x0000000004f6b30f in CompositeLogger::logv (this=0x919b4a0, p_format=0x7b83d8c "%s\n", p_list=0x7fffffffc988, p_err=false) at core/io/logger.cpp:249
#8  0x0000000004e94319 in OS::print (this=0x7fffffffd060, p_format=0x7b83d8c "%s\n") at core/os/os.cpp:116
#9  0x000000000529cc55 in print_line (p_string=...) at core/string/print_string.cpp:77
#10 0x00000000030f3bd1 in VulkanContext::swap_buffers (this=0x93b4630) at drivers/vulkan/vulkan_context.cpp:1247
#11 0x00000000030b5f61 in RenderingDeviceVulkan::swap_buffers (this=0x9706cd0) at drivers/vulkan/rendering_device_vulkan.cpp:7030
#12 0x0000000004bb495c in RasterizerRD::end_frame (this=0x9ae2a90, p_swap_buffers=true) at servers/rendering/rasterizer_rd/rasterizer_rd.cpp:95
#13 0x0000000004adf30d in RenderingServerRaster::draw (this=0x994b600, p_swap_buffers=true, frame_step=0.050000004470348358) at servers/rendering/rendering_server_raster.cpp:119
#14 0x0000000004b16f74 in RenderingServerWrapMT::draw (this=0x9efc970, p_swap_buffers=true, frame_step=0.050000004470348358) at servers/rendering/rendering_server_wrap_mt.cpp:91
#15 0x0000000001f92464 in Main::iteration () at main/main.cpp:2509
#16 0x0000000001f5a0e2 in OS_LinuxBSD::run (this=0x7fffffffd060) at platform/linuxbsd/os_linuxbsd.cpp:261
#17 0x0000000001f57b07 in main (argc=4, argv=0x7fffffffd568) at platform/linuxbsd/godot_linuxbsd.cpp:58
```
