### ISSUE TITLE
Crash when using set_mode and _update_shader methods in VisualShader

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#46062]
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
extends Node2D

var q_VisualShader : VisualShader = VisualShader.new()

func _process(_delta : float) -> void:
	if randi() % 2 == 0:
		q_VisualShader.set_mode((randi() % int(100)) - int(100 / 2.0))
	if randi() % 2 == 0:
		q_VisualShader._update_shader()
	pass
```

crashes with backtrace
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fa355026210] (??:0)
[2] String::copy_from(char const*) (/mnt/Miecz/godot3.2/core/ustring.cpp:164)
[3] String::String(char const*) (/mnt/Miecz/godot3.2/core/ustring.cpp:1657)
[4] VisualShader::_update_shader() const (/mnt/Miecz/godot3.2/scene/resources/visual_shader.cpp:1291 (discriminator 3))
[5] MethodBind0C::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:417 (discriminator 4))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1254)
[10] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:988)
[16] SceneTree::idle(float) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:528 (discriminator 3))
[17] Main::iteration() (/mnt/Miecz/godot3.2/main/main.cpp:2108)
[18] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3634)
[19] /usr/bin/godot(main+0x125) [0x16d2e6b] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fa3550070b3] (??:0)
[21] /usr/bin/godot(_start+0x2e) [0x16d2c8e] (??:?)

```
Address sanitizer log
```
scene/resources/visual_shader.cpp:625:25: runtime error: load of value 4294967279, which is not a valid value for type 'Mode'
scene/resources/visual_shader.cpp:1291:61: runtime error: load of value 4294967279, which is not a valid value for type 'Mode'
scene/resources/visual_shader.cpp:1291:72: runtime error: index -17 out of bounds for type 'char *[3]'
scene/resources/visual_shader.cpp:1291:61: runtime error: load of value 4294967279, which is not a valid value for type 'Mode'
=================================================================
==99131==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00003a728af8 at pc 0x00000f2ba228 bp 0x7ffd04c36800 sp 0x7ffd04c367f0
READ of size 8 at 0x00003a728af8 thread T0
    #0 0xf2ba227 in VisualShader::_update_shader() const scene/resources/visual_shader.cpp:1291
    #1 0x8a5a40b in MethodBind0C::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:415
    #2 0x1131a1fb in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #3 0x1159b1d7 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1129
    #4 0x1d4c957 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #5 0x1b7cbc2 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1254
    #6 0xbef2a07 in Node::_notification(int) scene/main/node.cpp:60
    #7 0x1a29b69 in Node::_notificationv(int, bool) scene/main/node.h:46
    #8 0x1a2bfde in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #9 0xd9c78e4 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #10 0x1131a695 in Object::notification(int, bool) core/object.cpp:929
    #11 0xc01d9b3 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:988
    #12 0xc00e275 in SceneTree::idle(float) scene/main/scene_tree.cpp:528
    #13 0x189006a in Main::iteration() main/main.cpp:2108
    #14 0x1780816 in OS_X11::run() platform/x11/os_x11.cpp:3634
    #15 0x16ee466 in main platform/x11/godot_x11.cpp:56
    #16 0x7f18551b80b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #17 0x16ee07d in _start (/usr/bin/godots+0x16ee07d)
```

**Comment by akien-mga** [comment]
Fixed by #46097.
