### ISSUE TITLE
Crash when using thread waiting for itself to finish

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#46412]
This is probably a regression from https://github.com/godotengine/godot/pull/45618

**Godot version:**
Godot Engine v3.2.4.rc3.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 960/PCIe/SSE2
OpenGL ES Batching: ON

**Issue description:**
Hey guys!
After `Godot Engine v3.2.4.rc3.mono.official` the game (desktop application in my case) seems to be crashing when using threads.
Unfortunately i was not able to replicate the issue with a smaller project so I'll just provide all the info i have for now.
- It crashes when `thread.wait_to_finish()` is called. Although this is the case for my application, when i try to replicate this with a smaller method (same project) it does not crash.
- The method that is being run by the thread takes about 1:30 minutes to complete and it also calls some methods from c# classes. Again, i tried replicating this by creating a thread and running some methods from the c# libraries but it did not crash.
- The `thread.wait_to_finish()` so far was being called when the method finishes processing. I have now moved it to `_exit_tree() ` and it does not crash anymore. 
- The only error i get in the console when the crash happens is :
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
```
![image](https://user-images.githubusercontent.com/1850856/109134666-9247bd80-7756-11eb-967f-590490ec1ccc.png)

@RandomShaper I saw there was some changes in threading recently so this might be related. Please let me know if there is any additional info i can provide.

EDIT: After playing around with it a little it seems that the crash is not related to my method. Also i was able to reproduce it so here is a small project:
[ThreadCrashTest.zip](https://github.com/godotengine/godot/files/6042161/ThreadCrashTest.zip)

**Comment by akien-mga** [comment]
I can reproduce the issue on Linux with the MRP. GDB backtrace:
```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided

Thread 23 "thread_method" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff8f28d640 (LWP 1993136)]
0x00007ffff7a984b0 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7a984b0 in raise () from /lib64/libc.so.6
#1  0x00007ffff7a83526 in abort () from /lib64/libc.so.6
#2  0x00000000016ffe2b in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00000000046de516 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00000000046de581 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00000000046de6d4 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fff7c000c10, tinfo=tinfo@entry=0x60b94e8 <typeinfo for std::system_error>, dest=dest@entry=0x47576a0 <std::system_error::~system_error()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x0000000001701c2f in std::__throw_system_error (__i=35) at ../../../../../libstdc++-v3/src/c++11/system_error.cc:338
#7  0x0000000004757b8c in std::thread::join (this=0x6aa0498) at ../../../../../libstdc++-v3/src/c++11/thread.cc:113
#8  0x00000000043bd8c2 in Thread::wait_to_finish (this=0x6aa0490) at core/os/thread.cpp:95
#9  0x00000000044e5664 in _Thread::wait_to_finish (this=0x6aa0340) at core/bind/core_bind.cpp:2813
#10 0x00000000017fe3af in MethodBind0R<Variant>::call (this=0x671c140, p_object=0x6aa0340, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:237
#11 0x0000000004282d20 in Object::call (this=0x6aa0340, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at core/object.cpp:919
#12 0x0000000004313138 in Variant::call_ptr (this=0x7e3d5b0, p_method=..., p_args=0x0, p_argcount=0, r_ret=0x0, r_error=...) at core/variant_call.cpp:1130
#13 0x00000000018369f0 in GDScriptFunction::call (this=0x7e3e300, p_instance=0x7e38430, p_args=0x7fff8f28cb78, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:1086
#14 0x00000000017dce66 in GDScriptInstance::call (this=0x7e38430, p_method=..., p_args=0x7fff8f28cb78, p_argcount=1, r_error=...) at modules/gdscript/gdscript.cpp:1208
#15 0x0000000004282bfc in Object::call (this=0x7b6cee0, p_method=..., p_args=0x7fff8f28cb78, p_argcount=1, r_error=...) at core/object.cpp:898
#16 0x00000000044e4dfd in _Thread::_start_func (ud=0x7e40ac0) at core/bind/core_bind.cpp:2750
#17 0x00000000043bd74a in Thread::callback (p_self=0x6aa0490, p_settings=..., p_callback=0x44e4cf6 <_Thread::_start_func(void*)>, p_userdata=0x7e40ac0) at core/os/thread.cpp:68
#18 0x00000000043be477 in std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __f=@0x7e28e48: 0x43bd6de <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>) at /usr/include/c++/10/bits/invoke.h:60
#19 0x00000000043be2fa in std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __fn=@0x7e28e48: 0x43bd6de <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>) at /usr/include/c++/10/bits/invoke.h:95
#20 0x00000000043be1b5 in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x7e28e28) at /usr/include/c++/10/thread:264
#21 0x00000000043be11a in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator() (this=0x7e28e28)
    at /usr/include/c++/10/thread:271
#22 0x00000000043be0fe in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_--Type <RET> for more, q to quit, c to continue without paging--
run (this=0x7e28e20) at /usr/include/c++/10/thread:215
#23 0x0000000004757940 in std::execute_native_thread_routine (__p=0x7e28e20) at ../../../../../libstdc++-v3/src/c++11/thread.cc:80
#24 0x00007ffff7d67dea in start_thread () from /lib64/libpthread.so.0
#25 0x00007ffff7b52fff in clone () from /lib64/libc.so.6
```
