### ISSUE TITLE
Usage of invalid memory when using Image.bumpmap_to_normalmap function

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#46484]
**Godot version:**
3.2.4.rc.custom_build. 8385a0d8a

**OS**
Ubuntu 20.04 - Ubuntu 3.36 X11

**Issue description:**
Executing
```
var q_Image : Image = Image.new()

func _process(_delta : float) -> void:
	q_Image = Image.new()
	q_Image.create(1, 1, 1,1)
	q_Image.lock()
	q_Image.bumpmap_to_normalmap(1)
```

address sanitizer shows this info
```
Executing Image.bumpmap_to_normalmap
ERROR: convert: Cannot convert image when it is locked.
   At: core/image.cpp:427.
=================================================================
==215296==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300027cefc at pc 0x00001142e795 bp 0x7ffe881ff850 sp 0x7ffe881ff840
READ of size 4 at 0x60300027cefc thread T0
    #0 0x1142e794 in Image::bumpmap_to_normalmap(float) core/image.cpp:2943
    #1 0x29f3d81 in MethodBind1<float>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #2 0x1153558d in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #3 0x117baa25 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1148
    #4 0x1d9958d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #5 0x1bca1a0 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1224
    #6 0xc032ccd in Node::_notification(int) scene/main/node.cpp:60
    #7 0x1a787ad in Node::_notificationv(int, bool) scene/main/node.h:46
    #8 0x1a7ac22 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #9 0xdb23a38 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #10 0x11535a27 in Object::notification(int, bool) core/object.cpp:929
    #11 0xc161d39 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:992
    #12 0xc1522c7 in SceneTree::idle(float) scene/main/scene_tree.cpp:529
    #13 0x18dcd08 in Main::iteration() main/main.cpp:2115
    #14 0x17c08fc in OS_X11::run() platform/x11/os_x11.cpp:3628
    #15 0x172cefb in main platform/x11/godot_x11.cpp:56
    #16 0x7ff0fca720b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #17 0x172cb1d in _start (/usr/bin/godots+0x172cb1d)

0x60300027cefc is located 2 bytes to the right of 26-byte region [0x60300027cee0,0x60300027cefa)
allocated by thread T0 here:
    #0 0x7ff0fdbeb517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0x11a774db in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:82
    #2 0x19b741d in PoolVector<unsigned char>::resize(int) core/pool_vector.h:583
    #3 0x113e5408 in Image::create(int, int, bool, Image::Format) core/image.cpp:1593
    #4 0x11485abc in Image::_create_empty(int, int, bool, Image::Format) core/image.h:162
    #5 0x114ca741 in MethodBind4<int, int, bool, Image::Format>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:3115
    #6 0x1153558d in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #7 0x117baa25 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1148
    #8 0x1d9958d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #9 0x1bca1a0 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1224
    #10 0xc032ccd in Node::_notification(int) scene/main/node.cpp:60
    #11 0x1a787ad in Node::_notificationv(int, bool) scene/main/node.h:46
    #12 0x1a7ac22 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #13 0xdb23a38 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #14 0x11535a27 in Object::notification(int, bool) core/object.cpp:929
    #15 0xc161d39 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:992
    #16 0xc1522c7 in SceneTree::idle(float) scene/main/scene_tree.cpp:529
    #17 0x18dcd08 in Main::iteration() main/main.cpp:2115
    #18 0x17c08fc in OS_X11::run() platform/x11/os_x11.cpp:3628
    #19 0x172cefb in main platform/x11/godot_x11.cpp:56
    #20 0x7ff0fca720b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow core/image.cpp:2943 in Image::bumpmap_to_normalmap(float)

```

**Comment by qarmin** [comment]
Fixed by #47045
