### ISSUE TITLE
Godot crashes in exported project when using Skin::get_bind_pose

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#47358]
**Godot version:**
3.3.rc.custom_build. 7696f8854

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
Very rarely some checks are disabled in release build, which may be needed sometimes in situations where the biggest performance is required, but users usually don't fix all errors before exporting project(from experience it is almost impossible in a little bigger project) and they may spend a lot of time tracking place where game crashes and understanding why this happens.

If checks in this place are required, I will add exceptions in my test project, but if are not required, then this should be fixed by removing `#ifdef`

```
==27610==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000290 (pc 0x0000070a0516 bp 0x7ffe98825350 sp 0x7ffe98825320 T0)
==27610==The signal is caused by a READ memory access.
==27610==Hint: address points to the zero page.
    #0 0x70a0515 in Skin::get_bind_pose(int) const scene/resources/skin.h:86
    #1 0x70dd967 in MethodBind1RC<Transform, int>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1333
    #2 0xf5c24da in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #3 0xf5c018d in Object::callv(StringName const&, Array const&) core/object.cpp:825
    #4 0xf653edc in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1717
    #5 0xf5c24da in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #6 0xf9e5b42 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1149
    #7 0x1a1dc39 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #8 0x189444e in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1208
    #9 0xf5c1b21 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:898
    #10 0xf9e5b42 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1149
    #11 0x1a1dc39 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #12 0x18952dd in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1239
    #13 0x189567e in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1246
    #14 0x4c983af in Node::_notification(int) scene/main/node.cpp:149
    #15 0x68de36 in Node::_notificationv(int, bool) scene/main/node.h:46
    #16 0x4a0f213 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #17 0x74a9fe9 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:38
    #18 0xf5c2b2e in Object::notification(int, bool) core/object.cpp:929
    #19 0x4c9baf9 in Node::_propagate_ready() scene/main/node.cpp:196
    #20 0x4d083fc in Node::_set_tree(SceneTree*) scene/main/node.cpp:2623
    #21 0x4ccee1f in Node::_add_child_nocheck(Node*, StringName const&) scene/main/node.cpp:1149
    #22 0x4ccf8ff in Node::add_child(Node*, bool) scene/main/node.cpp:1168
    #23 0x4dcaf3b in MethodBind2<Node*, bool>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1523
    #24 0xf5c24da in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:919
    #25 0xf9e5b42 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1149
    #26 0x1a1dc39 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1086
    #27 0x18952dd in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1239
    #28 0x189567e in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1246
    #29 0x4c983af in Node::_notification(int) scene/main/node.cpp:149
    #30 0x68de36 in Node::_notificationv(int, bool) scene/main/node.h:46
    #31 0x4a0f213 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:166
    #32 0x4a21c49 in Control::_notificationv(int, bool) scene/gui/control.h:48
    #33 0xf5c2b2e in Object::notification(int, bool) core/object.cpp:929
    #34 0x4c9baf9 in Node::_propagate_ready() scene/main/node.cpp:196
    #35 0x4c9b350 in Node::_propagate_ready() scene/main/node.cpp:188
    #36 0x4d083fc in Node::_set_tree(SceneTree*) scene/main/node.cpp:2623
    #37 0x4e10526 in SceneTree::init() scene/main/scene_tree.cpp:465
    #38 0x509339 in OS_X11::run() platform/x11/os_x11.cpp:3628
    #39 0x466ece in main platform/x11/godot_x11.cpp:56
    #40 0x7f658300f0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #41 0x466aed in _start (/home/runner/work/RegressionTestProject/RegressionTestProject/test_project+0x466aed)
```

https://github.com/godotengine/godot/blob/49122588391b5159fada6d33f136d169b5a01ae5/scene/resources/skin.h#L69-L88
https://github.com/qarmin/RegressionTestProject/pull/32/checks?check_run_id=2191278292

**Comment by fire** [comment]
The skins api calls get bind pose and developers are expected to give it random integer input. So we need the checks.
