### ISSUE TITLE
Editor may freeze after using "find_next_valid_focus()" in the script in specific situation

### ISSUE THREAD

**Issue by DrRevert** [godotengine/godot#49975]
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

When writting the script the built-in script editor may freeze when using find_next_valid_focus(). Editor attempts to calls that function and falls into endless loop.
For the problem to occur there needs to be a parent Control node with visibility set to false.
For example:
![image](https://user-images.githubusercontent.com/69091976/123704436-ecbc6c00-d865-11eb-98df-9c3163e84f76.png)

### Steps to reproduce

1. Create a scene with Popup as the root (this is the most common as Popups hide automatically, but any other node should also work)
2. Create a Button as a child
3. Attach new script to the Popup
4. Make sure that popup is hidden! (eye is closed)
5. Inside _ready() function type `$Button.find_next_valid_focus()`
6. As soon as you type the "." or attempt to use the result of the find_next_valid_focus() in any way the editor will freeze

### Minimal reproduction project

[next_focus_freeze.zip](https://github.com/godotengine/godot/files/6729324/next_focus_freeze.zip)

**Comment by KoBeWi** [comment]
Still valid in 26dd474

**Comment by qarmin** [comment]
Freeze here
```
#0  0x000000000308788e in Object::cast_to<CanvasItem> (p_object=0xfbb5c60) at ./core/object.h:603
#1  0x0000000003ef560e in CanvasItem::get_parent_item (this=0x11090e20) at scene/2d/canvas_item.cpp:667
#2  0x0000000003ef3670 in CanvasItem::is_visible_in_tree (this=0x11090e20) at scene/2d/canvas_item.cpp:363
#3  0x0000000003a63183 in Control::find_next_valid_focus (this=0x11090e20) at scene/gui/control.cpp:1877
#4  0x0000000003a14d6c in MethodBind0RC<Control*>::call (this=0x7ca6470, p_object=0x11090e20, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:581
#5  0x00000000019684df in _guess_expression_type (p_context=..., p_expression=0x116d47b0, r_type=...) at modules/gdscript/gdscript_editor.cpp:886
#6  0x0000000001975e57 in GDScriptLanguage::complete_code (this=0x749d9f0, p_code=..., p_path=..., p_owner=0xfbb5c60, r_options=0x7fffffffc9b8, 
    r_forced=@0x7fffffffc9b7: false, r_call_hint=...) at modules/gdscript/gdscript_editor.cpp:2666
#7  0x00000000033d75c9 in ScriptTextEditor::_code_complete_script (this=0x113114f0, p_code=..., r_options=0x7fffffffc9b8, r_force=@0x7fffffffc9b7: false)
    at editor/plugins/script_text_editor.cpp:818
#8  0x00000000033d74ac in ScriptTextEditor::_code_complete_scripts (p_ud=0x113114f0, p_code=..., r_options=0x7fffffffc9b8, r_force=@0x7fffffffc9b7: false)
    at editor/plugins/script_text_editor.cpp:806
#9  0x0000000003761be3 in CodeTextEditor::_complete_request (this=0x11311ad0) at editor/code_editor.cpp:834
#10 0x0000000001904eae in MethodBind0::call (this=0xd6ee3d0, p_object=0x11311ad0, p_args=0x7fffffffccc0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:59
#11 0x0000000004a1de6e in Object::call (this=0x11311ad0, p_method=..., p_args=0x7fffffffccc0, p_argcount=0, r_error=...) at core/object.cpp:918
#12 0x0000000004a20136 in Object::emit_signal (this=0x115559b0, p_name=..., p_args=0x7fffffffccc0, p_argcount=0) at core/object.cpp:1231
#13 0x0000000004a208db in Object::emit_signal (this=0x115559b0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=..., p_arg6=..., p_arg7=..., p_arg8=...)
    at core/object.cpp:1286
#14 0x0000000003c0a076 in TextEdit::query_code_comple (this=0x115559b0) at scene/gui/text_edit.cpp:7016
#15 0x0000000003761b36 in CodeTextEditor::_code_complete_timer_timeout (this=0x11311ad0) at editor/code_editor.cpp:825
#16 0x0000000001904eae in MethodBind0::call (this=0xd6ee2b0, p_object=0x11311ad0, p_args=0x7fffffffd1b0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:59
#17 0x0000000004a1de6e in Object::call (this=0x11311ad0, p_method=..., p_args=0x7fffffffd1b0, p_argcount=0, r_error=...) at core/object.cpp:918
#18 0x0000000004a20136 in Object::emit_signal (this=0x1155cec0, p_name=..., p_args=0x7fffffffd1b0, p_argcount=0) at core/object.cpp:1231
#19 0x0000000004a208db in Object::emit_signal (this=0x1155cec0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=..., p_arg6=..., p_arg7=..., p_arg8=...)
    at core/object.cpp:1286
#20 0x00000000039dfb3d in Timer::_notification (this=0x1155cec0, p_what=25) at scene/main/timer.cpp:61
#21 0x00000000039e268e in Timer::_notificationv (this=0x1155cec0, p_notification=25, p_reversed=false) at scene/main/timer.h:37
#22 0x0000000004a1dfb1 in Object::notification (this=0x1155cec0, p_notification=25, p_reversed=false) at core/object.cpp:927
#23 0x00000000039bf129 in SceneTree::_notify_group_pause (this=0x759cdc0, p_group=..., p_notification=25) at scene/main/scene_tree.cpp:1057
#24 0x00000000039bc8c1 in SceneTree::idle (this=0x759cdc0, p_time=0.00666666729) at scene/main/scene_tree.cpp:595
#25 0x00000000018855a6 in Main::iteration () at main/main.cpp:2271
#26 0x0000000001845f5a in OS_X11::run (this=0x7fffffffd7a0) at platform/x11/os_x11.cpp:3842
#27 0x0000000001831b0b in main (argc=2, argv=0x7fffffffe0c8) at platform/x11/godot_x11.cpp:55
```
