### ISSUE TITLE
Godot can't create device on GTX 1060 (Laptop)

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#49987]
### Godot version

master - eb318d3e04ac6d3bb01b0f2a8311d06ba55c3a2b

### System information

Windows 10

### Issue description

Godot can't create Vulkan device on this hardware. I'm checking drivers to see if this is a local issue but reporting this as to not loose the log and just in case someone else has run into this too :)

See following startup log:
```
Godot Engine v4.0.dev.custom_build.eb318d3e0 - https://godotengine.org
Vulkan API 1.2.162
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1484825947616
     at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:154)
Using Vulkan Device #1: NVIDIA - GeForce GTX 1060
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        terminator_CreateDevice: Failed in ICD C:\WINDOWS\System32\DriverStore\FileRepository\nvcvi.inf_amd64_8248dd6d7254db0c\.\nvoglv64.dll vkCreateDevicecall
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1484825947616
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        vkCreateDevice:  Failed to create device chain.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1484825947616
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::_create_device (drivers\vulkan\vulkan_context.cpp:1011)
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] vkGetDeviceProcAddr (D:\Godot\godot4-git\thirdparty\vulkan\loader\trampoline.c:88)
[1] VulkanContext::_initialize_queues (D:\Godot\godot4-git\drivers\vulkan\vulkan_context.cpp:1074)
[2] VulkanContext::_window_create (D:\Godot\godot4-git\drivers\vulkan\vulkan_context.cpp:1200)
[3] VulkanContextWindows::window_create (D:\Godot\godot4-git\platform\windows\vulkan_context_win.cpp:50)
[4] DisplayServerWindows::_create_window (D:\Godot\godot4-git\platform\windows\display_server_windows.cpp:3033)
[5] DisplayServerWindows::DisplayServerWindows (D:\Godot\godot4-git\platform\windows\display_server_windows.cpp:3289)
[6] DisplayServerWindows::create_func (D:\Godot\godot4-git\platform\windows\display_server_windows.cpp:3351)
[7] Main::setup2 (D:\Godot\godot4-git\main\main.cpp:1553)
[8] Main::setup (D:\Godot\godot4-git\main\main.cpp:1405)
[9] widechar_main (D:\Godot\godot4-git\platform\windows\godot_windows.cpp:153)
[10] _main (D:\Godot\godot4-git\platform\windows\godot_windows.cpp:187)
[11] main (D:\Godot\godot4-git\platform\windows\godot_windows.cpp:199)
[12] __scrt_common_main_seh (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[13] BaseThreadInitThunk
-- END OF BACKTRACE --
```

### Steps to reproduce

Just compile Godot and start :)

### Minimal reproduction project

n/a

**Comment by Chaosus** [comment]
Strange, I have Windows 10 / GTX 1060 and it runs correctly - however, I have a PC instead of a laptop

**Comment by insomniacUNDERSCORElemon** [comment]
There's also #49656 for someone else having an issue w/a laptop GPU(765M) but their backtrace doesn't mention creating device. Unless the recent pull request `Fix Context Validation Layer Errors` changed it?

**Comment by BastiaanOlij** [comment]
Yeah it was a friggen driver issue... Geforce had stopped updating and for some reason whenever NVidea releases a new driver the old one mysteriously breaks..

**Comment by akien-mga** [comment]
Can we handle the init failure gracefully to prevent the segfault, and throw an explicit error instead?

**Comment by rcorre** [comment]
I got a similar stacktrace on 4.0.3 Linux. I was running Godot and `SimpleScreenRecorder` (I don't remember if I was actively recording). I moved/resized the editor window, and Godot slowed down, then hung for ~10s. After that, I got a crash in the console, but the editor appeared to keep running. I closed the editor, and now every time I try to reopen it crashes with this stacktrace. My driver versions should not have changed between when it was working and not (it happened all within the same boot, and I didn't upgrade during that time).

```
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080                                                                                                                                                                                         
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _create_device (drivers/vulkan/vulkan_context.cpp:1476)

Thread 1 "godot.linuxbsd." received signal SIGSEGV, Segmentation fault.
vkGetDeviceProcAddr (pName=0x55555ad45f11 "vkCreateSwapchainKHR", device=0x0) at /usr/src/debug/vulkan-icd-loader/Vulkan-Loader-1.3.255/loader/trampoline.c:133
Downloading source file /usr/src/debug/vulkan-icd-loader/Vulkan-Loader-1.3.255/loader/trampoline.c
133         const VkLayerDispatchTable *disp_table = *(VkLayerDispatchTable **)device;                                                                                                                                                                                           
(gdb) bt
#0  vkGetDeviceProcAddr (pName=0x55555ad45f11 "vkCreateSwapchainKHR", device=0x0) at /usr/src/debug/vulkan-icd-loader/Vulkan-Loader-1.3.255/loader/trampoline.c:133
#1  vkGetDeviceProcAddr (device=0x0, pName=0x55555ad45f11 "vkCreateSwapchainKHR") at /usr/include/vulkan/vulkan_core.h:4089
#2  0x00005555571b1feb in VulkanContext::_initialize_queues (this=this@entry=0x55555d7ebd10, p_surface=p_surface@entry=0x55555d9682e0) at drivers/vulkan/vulkan_context.cpp:1540
#3  0x00005555571be193 in VulkanContext::_window_create (this=0x55555d7ebd10, p_window_id=<optimized out>, p_vsync_mode=DisplayServer::VSYNC_ENABLED, p_surface=<optimized out>, p_width=1152, p_height=648) at drivers/vulkan/vulkan_context.cpp:1688
#4  0x000055555619a5bd in VulkanContextX11::window_create (this=0x55555d7ebd10, p_window_id=p_window_id@entry=0, p_vsync_mode=p_vsync_mode@entry=DisplayServer::VSYNC_ENABLED, p_window=<optimized out>, p_display=<optimized out>, p_width=p_width@entry=1152, p_height=648)
    at platform/linuxbsd/x11/vulkan_context_x11.cpp:56
#5  0x000055555616f602 in DisplayServerX11::_create_window (this=this@entry=0x55555d799920, p_mode=p_mode@entry=DisplayServer::WINDOW_MODE_MAXIMIZED, p_vsync_mode=p_vsync_mode@entry=DisplayServer::VSYNC_ENABLED, p_flags=p_flags@entry=0, p_rect=...)
    at platform/linuxbsd/x11/display_server_x11.cpp:5144
#6  0x00005555561707fd in DisplayServerX11::DisplayServerX11 (this=0x55555d799920, p_rendering_driver=..., p_mode=<optimized out>, p_vsync_mode=<optimized out>, p_flags=0, p_position=<optimized out>, p_resolution=..., p_screen=<optimized out>, r_error=<optimized out>)
    at platform/linuxbsd/x11/display_server_x11.cpp:5551
#7  0x0000555556171b6b in DisplayServerX11::create_func (p_rendering_driver=..., p_mode=DisplayServer::WINDOW_MODE_MAXIMIZED, p_vsync_mode=DisplayServer::VSYNC_ENABLED, p_flags=0, p_position=0x0, p_resolution=..., p_screen=-2, r_error=@0x7fffffffd2f0: OK)
    at platform/linuxbsd/x11/display_server_x11.cpp:4845
#8  0x00005555561b3c45 in Main::setup2 (p_main_tid_override=p_main_tid_override@entry=0) at main/main.cpp:2001
#9  0x00005555561bbe94 in Main::setup (execpath=0x7fffffffde54 "/home/rcorre/src/godot/godot/bin/godot.linuxbsd.editor.x86_64", argc=argc@entry=1, argv=argv@entry=0x7fffffffdb30, p_second_phase=p_second_phase@entry=true) at main/main.cpp:1879
#10 0x00005555561399eb in main (argc=2, argv=0x7fffffffdb28) at platform/linuxbsd/godot_linuxbsd.cpp:61
```
