### ISSUE TITLE
Switching ttys on Linux freezes Godot

### ISSUE THREAD

**Issue by Yiannis128** [godotengine/godot#50550]
### Godot version

v4.0.dev.custom_build [60add98a4]

### System information

Linux manjaro 5.12.16-1-MANJARO x86_64 GNU/Linux

### Issue description

Godot freezes when switching tty. This means it needs to be killed.

### Steps to reproduce

1. Open Godot.
2. Switch to another tty.
3. Switch back to the tty with Godot.
4. Godot is now frozen.

**Comment by qarmin** [comment]
Confirmed on Ubuntu 21.04, Nvidia 970 - 465

GDB backtrace
```
0x00007ffff7b7922f in __GI___poll (fds=0x20b83140, nfds=1, timeout=10) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff7b7922f in __GI___poll (fds=0x20b83140, nfds=1, timeout=10) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fffee46114f in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.465.27
#2  0x00007fffee82ad9e in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.465.27
#3  0x00007fffee82c11c in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.465.27
#4  0x00007fffee82c53c in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.465.27
#5  0x00000000037da348 in vkWaitForFences (device=0xa8d30f8, fenceCount=1, pFences=0xa4c0048, waitAll=1, timeout=18446744073709551615)
    at thirdparty/vulkan/loader/trampoline.c:1064
#6  0x0000000003779eeb in VulkanContext::prepare_buffers (this=0xa4bfc40) at drivers/vulkan/vulkan_context.cpp:1750
#7  0x000000000372385d in RenderingDeviceVulkan::prepare_screen_for_drawing (this=0xa7e9610) at drivers/vulkan/rendering_device_vulkan.cpp:8308
#8  0x000000000575899f in RendererCompositorRD::prepare_for_blitting_render_targets (this=0xac2a220) at servers/rendering/renderer_rd/renderer_compositor_rd.cpp:37
#9  0x000000000590f30b in RendererViewport::draw_viewports (this=0xac182e0) at servers/rendering/renderer_viewport.cpp:622
#10 0x00000000056b5341 in RenderingServerDefault::_draw (this=0xabe70f0, p_swap_buffers=true, frame_step=0.0069444444961845875)
    at servers/rendering/rendering_server_default.cpp:94
#11 0x00000000056b6ff8 in RenderingServerDefault::draw (this=0xabe70f0, p_swap_buffers=true, frame_step=0.0069444444961845875)
    at servers/rendering/rendering_server_default.cpp:376
#12 0x0000000002129002 in Main::iteration () at main/main.cpp:2531
#13 0x00000000020e6848 in OS_LinuxBSD::run (this=0x7fffffffdac0) at platform/linuxbsd/os_linuxbsd.cpp:278
#14 0x00000000020e365c in main (argc=2, argv=0x7fffffffdfb8) at platform/linuxbsd/godot_linuxbsd.cpp:58

```

**Comment by autofool** [comment]
Can confirm same problem with Arch linux - Nvidia 1650 ti
