### ISSUE TITLE
Crash when dragging CSGBox center handle in Right Orthogonal view

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#50995]
### Godot version

3.3.2, 3.4.beta2, 3.x (5d4352fad4), 4.0 (48857194b3)

### System information

macOS 11.4

### Issue description

Godot editor crashes when I was trying to drag the center handle of CSGBox, which is perpendicular to the screen:

![view](https://user-images.githubusercontent.com/372476/127433232-94abd630-5f62-4d5d-8d6d-352cd7ff1610.png)

This only happens in Right view. Editor won't crash if you do this in Top view, the box disappears with height set to `NAN` instead.

### Steps to reproduce

1. Add a CSGBox in your scene
2. Switch to Right Orthogonal view
3. Select the CSGBox and try to drag the handle in the center

**Comment by qarmin** [comment]
Looks like infinite recursion
```
Thread 1 "godot" received signal SIGSEGV, Segmentation fault.
0x0000000003dd2a72 in MergeVertsFast (piTriList_in_and_out=<error reading variable: Cannot access memory at address 0x7fffff7fefe8>, 
    pTmpVert=<error reading variable: Cannot access memory at address 0x7fffff7fefe0>, pContext=<error reading variable: Cannot access memory at address 0x7fffff7fefd8>, 
    iL_in=<error reading variable: Cannot access memory at address 0x7fffff7fefd4>, iR_in=<error reading variable: Cannot access memory at address 0x7fffff7fefd0>)
    at thirdparty/misc/mikktspace.c:577
577	{
(gdb) backtrace
#0  0x0000000003dd2a72 in MergeVertsFast (piTriList_in_and_out=<error reading variable: Cannot access memory at address 0x7fffff7fefe8>, 
    pTmpVert=<error reading variable: Cannot access memory at address 0x7fffff7fefe0>, pContext=<error reading variable: Cannot access memory at address 0x7fffff7fefd8>, 
    iL_in=<error reading variable: Cannot access memory at address 0x7fffff7fefd4>, iR_in=<error reading variable: Cannot access memory at address 0x7fffff7fefd0>)
    at thirdparty/misc/mikktspace.c:577
#1  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#2  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#3  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#4  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#5  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#6  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#7  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#8  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#9  0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#10 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#11 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#12 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#13 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#14 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
    at thirdparty/misc/mikktspace.c:682
#15 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35)
................................
................................
................................
................................

#32735 0x0000000003dd34a0 in MergeVertsFast (piTriList_in_and_out=0x7fffcc00b090, pTmpVert=0xc89cc60, pContext=0x7fffffffd230, iL_in=0, iR_in=35) at thirdparty/misc/mikktspace.c:682
#32736 0x0000000003dd29ed in GenerateSharedVerticesIndexList (piTriList_in_and_out=0x7fffcc00b090, pContext=0x7fffffffd230, iNrTrianglesIn=12) at thirdparty/misc/mikktspace.c:564
#32737 0x0000000003dd1832 in genTangSpace (pContext=0x7fffffffd230, fAngularThreshold=180) at thirdparty/misc/mikktspace.c:275
#32738 0x0000000003dd1566 in genTangSpaceDefault (pContext=0x7fffffffd230) at thirdparty/misc/mikktspace.c:226
#32739 0x0000000001c0d3a0 in CSGShape::_update_shape (this=0x8af0270) at modules/csg/csg_shape.cpp:431
#32740 0x00000000018457d8 in MethodBind0::call (this=0x7a82840, p_object=0x8af0270, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:59
#32741 0x0000000004667fb8 in Object::call (this=0x8af0270, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at core/object.cpp:918
#32742 0x000000000465e60b in MessageQueue::_call_function (this=0x6c908b0, p_target=0x8af0270, p_func=..., p_args=0x7ffff5a19038, p_argcount=0, p_show_error=false) at core/message_queue.cpp:241
#32743 0x000000000465e90b in MessageQueue::flush (this=0x6c908b0) at core/message_queue.cpp:284
#32744 0x00000000036a4bd0 in SceneTree::idle (this=0x7c41c60, p_time=0.0069444445) at scene/main/scene_tree.cpp:519
#32745 0x00000000017caf47 in Main::iteration () at main/main.cpp:2105
#32746 0x000000000178e5c4 in OS_X11::run (this=0x7fffffffd830) at platform/x11/os_x11.cpp:3638
#32747 0x000000000177b33b in main (argc=2, argv=0x7fffffffe128) at platform/x11/godot_x11.cpp:55

```

**Comment by Calinou** [comment]
Ideally, when using a fixed view, the perpendicular handle should disappear and be non-draggable.
