### ISSUE TITLE
Tween memory leak

### ISSUE THREAD

**Issue by duongvituan** [godotengine/godot#51231]
### Godot version

4.0

### System information

Mac mini 2018, Mac OS catalina 10.15.7, i5, 8gb ram

### Issue description

https://user-images.githubusercontent.com/30470869/128121306-a0316aca-9a2d-45ea-948a-f78c3758de7a.mov

The number of objects always increases every time tween is used in Godot 4 (see number objects in debug -> monitor)

I don't have this case in Godot 3.2.3 so I think it is memory leak.

### Steps to reproduce

Project contains 1 Node2D and 1 Sprite2D

```
extends Node2D

@onready var sprite := $Sprite2D

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("click"):
		move_node_to_click(get_global_mouse_position())

func move_node_to_click(target_position: Vector2) -> void:
	print(target_position)
	var tween: Tween = get_tree().create_tween()
	tween.tween_property(sprite, "position", target_position, 0.5)
	tween.tween_interval(0.5)
```

Run and click on screen.
Check Debugger -> Monitors - > Object -> Objects: increase by 3 per click

### Minimal reproduction project

[TestGD4.zip](https://github.com/godotengine/godot/files/6928606/TestGD4.zip)

**Comment by qarmin** [comment]
```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2004)
Leaked instance: Tween:-9222408864668843549
Leaked instance: PropertyTweener:-9222408314913029660
Leaked instance: IntervalTweener:-9222407765157215761
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
Orphan StringName: Tween
Orphan StringName: IntervalTweener
Orphan StringName: position
Orphan StringName: PropertyTweener
StringName: 26 unclaimed string names at exit.


Indirect leak of 432 byte(s) in 1 object(s) allocated from:
    #0 0x7ff941fcac47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x16113909 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x1611381a in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x11a97960 in Tween::tween_property(Object*, NodePath, Variant, float) scene/animation/tween.cpp:59
    #4 0x11b28d52 in void call_with_variant_args_ret_helper<__UnexistingClass, Ref<PropertyTweener>, Object*, NodePath, Variant, float, 0ul, 1ul, 2ul, 3ul>(__UnexistingClass*, Ref<PropertyTweener> (__UnexistingClass::*)(Object*, NodePath, Variant, float), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul, 3ul>) core/variant/binder_common.h:644
    #5 0x11b17cc8 in void call_with_variant_args_ret_dv<__UnexistingClass, Ref<PropertyTweener>, Object*, NodePath, Variant, float>(__UnexistingClass*, Ref<PropertyTweener> (__UnexistingClass::*)(Object*, NodePath, Variant, float), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:449
    #6 0x11b0769f in MethodBindTR<Ref<PropertyTweener>, Object*, NodePath, Variant, float>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:454
    #7 0x7889d00 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1579
    #8 0x7377aad in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1486
    #9 0x17440861 in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:811
    #10 0x16bb9007 in Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1017
    #11 0x7887411 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1471
    #12 0x7377aad in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1486
    #13 0xf28f290 in SceneTree::_call_input_pause(StringName const&, StringName const&, Ref<InputEvent> const&, Viewport*) scene/main/scene_tree.cpp:911
    #14 0xf3c39f3 in Viewport::unhandled_input(Ref<InputEvent> const&, bool) scene/main/viewport.cpp:3119
    #15 0xf4fc556 in Window::_window_input(Ref<InputEvent> const&) scene/main/window.cpp:923
    #16 0xf5832a6 in void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:218
    #17 0xf572f66 in void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) core/variant/binder_common.h:332
    #18 0xf560c38 in CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const core/object/callable_method_pointer.h:96
    #19 0x16b18ad4 in Callable::call(Variant const**, int, Variant&, Callable::CallError&) const core/variant/callable.cpp:50
    #20 0x21e0dfe in DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) platform/linuxbsd/display_server_x11.cpp:2602
    #21 0x21e04ca in DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) platform/linuxbsd/display_server_x11.cpp:2585
    #22 0x1699e665 in Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) core/input/input.cpp:642
    #23 0x16994965 in Input::parse_input_event(Ref<InputEvent> const&) core/input/input.cpp:464
    #24 0x169a6bba in Input::accumulate_input_event(Ref<InputEvent> const&) core/input/input.cpp:845
    #25 0x21f4367 in DisplayServerX11::process_events() platform/linuxbsd/display_server_x11.cpp:3167
    #26 0x21707eb in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:401
    #27 0x215e150 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #28 0x7ff940ffb564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

```
