### ISSUE TITLE
[3.x] LSP Server crashes Editor on autocompletion of Scene-less scripts

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#51331]
### Godot version

3.x branch at commit 8db0bd44249e9cac56cf24c7c192bc782c118638

### System information

Arch Linux

### Issue description

Whilst working on a malformed GDScript, attempting autocompletion using the LSP Server crashes the Editor.

Backtrace:

```gdscript
(gdb) bt
#0  0x000000000042d53a in Ref<Reference>::ref (this=0x7fff137fd240, p_from=...) at ./core/reference.h:64
#1  0x000000000054c9d9 in Ref<Reference>::operator= (this=0x7fff137fd240, p_from=...) at ./core/reference.h:138
#2  0x0000000004736590 in RefPtr::RefPtr (this=0x7fff137fd240, p_other=...) at core/ref_ptr.cpp:63
#3  0x00000000046fca84 in Object::get_script (this=0x0) at core/object.cpp:1050
#4  0x000000000071161e in GDScriptWorkspace::completion (this=0xc7116e0, p_params=..., r_options=0x7fff137fd2c0) at modules/gdscript/language_server/gdscript_workspace.cpp:524
#5  0x00000000006f3d64 in GDScriptTextDocument::completion (this=0xc711930, p_params=...) at modules/gdscript/language_server/gdscript_text_document.cpp:163
#6  0x000000000070699b in MethodBind1R<Array, Dictionary const&>::call (this=0xc70f380, p_object=0xc711930, p_args=0x7fff137fd750, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:961
#7  0x00000000046fbca2 in Object::call (this=0xc711930, p_method=..., p_args=0x7fff137fd750, p_argcount=1, r_error=...) at core/object.cpp:918
#8  0x00000000046fb4c8 in Object::callv (this=0xc711930, p_method=..., p_args=...) at core/object.cpp:827
#9  0x0000000000738aa6 in JSONRPC::process_action (this=0xc6078b8, p_action=..., p_process_arr_elements=true) at modules/jsonrpc/jsonrpc.cpp:129
#10 0x00000000007394ab in JSONRPC::process_string (this=0xc6078b8, p_input=...) at modules/jsonrpc/jsonrpc.cpp:165
#11 0x00000000006d9308 in GDScriptLanguageProtocol::process_message (this=0xc6078b8, p_text=...) at modules/gdscript/language_server/gdscript_language_protocol.cpp:141
#12 0x00000000006d89be in GDScriptLanguageProtocol::LSPeer::handle_data (this=0x7fff040011d0) at modules/gdscript/language_server/gdscript_language_protocol.cpp:96
#13 0x00000000006dcfb2 in GDScriptLanguageProtocol::poll (this=0xc6078b8) at modules/gdscript/language_server/gdscript_language_protocol.cpp:242
#14 0x00000000006ed776 in GDScriptLanguageServer::thread_main (p_userdata=0xc607690) at modules/gdscript/language_server/gdscript_language_server.cpp:78
#15 0x00000000048bd5cf in Thread::callback (p_self=0xc607a08, p_settings=..., p_callback=0x6ed74e <GDScriptLanguageServer::thread_main(void*)>, p_userdata=0xc60
#16 0x00000000048be517 in std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*
#17 0x00000000048be39a in std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
#18 0x00000000048be255 in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (
#19 0x00000000048be1ba in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (
#20 0x00000000048be19e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*,
#21 0x0000000004dce844 in execute_native_thread_routine ()
#22 0x00007ffff7d6a259 in start_thread () from /usr/lib/libpthread.so.0
#23 0x00007ffff7b485e3 in clone () from /usr/lib/libc.so.6
```

[Full bracktrace here.](https://github.com/godotengine/godot/files/6947350/LSP_autocompletion_crash_full_bt.txt)

### Steps to reproduce

1. Create a new empty GDScript file. (*.gd) in a brand new project.
2. Open it with an external editor.
3. On the first line, start typing "class_na" and attempt to autocomplete.

If the above doesn't work, attempting to autocomplete other classes whilst keeping the GDScript malformed should work.
The following GDScript should also trigger the crash when attempting autocompletion within it and whilst keeping the mistyped GDScript keywords:

```gdscript
class_nme AnAwesomeClass
extens Reference

func _int() -> void:
    pass

func attempt_your_autocompletions_here()  -> void:
    pass
```

### Minimal reproduction project

Creating an empty gdscript in brand new project and following the steps above suffices.

**Comment by Rubonnek** [comment]
cc @Razoric480

**Comment by Razoric480** [comment]
The bug arises not because the script is malformed, but because it's not attached to any scenes, so the completion call attempts to parse a null script. Will push a fix.
