### ISSUE TITLE
Windows MSVC x64 Debug Mono build fails due to "Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=2.1.0.0"

### ISSUE THREAD

**Issue by CinchBlue** [godotengine/godot#52427]
### Godot version

3.3.3-stable

### System information

Windows 10

### Issue description

I am trying to build Godot within Mono x64 Command Prompt with Visual Studio 2019 installed:

It seems like [this](https://github.com/dotnet/Nerdbank.GitVersioning/issues/466#issuecomment-620615064) might be relevant?

```powershell
F:\GodotBuild\godot>mono --version
Mono JIT compiler version 6.12.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

F:\GodotBuild\godot>dotnet --version
5.0.400

F:\GodotBuild\godot>scons --version
SCons by Steven Knight et al.:
        SCons: v4.2.0.fcdadeef19fe5fead09fa7544a27502be65312be, Sat, 31 Jul 2021 18:12:46 -0700, by bdbaddog on ProDog2020
        SCons path: ['c:\\users\\aytas\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\SCons']
Copyright (c) 2001 - 2021 The SCons Foundation

F:\GodotBuild\godot>scons p=windows target=debug tools=yes module_mono_enabled=yes copy_mono_root=yes -j8
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
Checking for `thread_local` support... supported
Found Mono root directory: C:\Program Files\Mono\
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 96%] build_api_solution(["bin\GodotSharp\Api\Debug\GodotSharp.dll", "bin\GodotSharp\Api\Debug\GodotSharp.pdb", "bin\GodotSharp\Api\Debug\GodotSharp.xml", "bin\GodotSharp\Api\Debug\GodotSharpEditor.dll", "bin\GodotSharp\Api\Debug\GodotSharpEditor.pdb", "bin\GodotSharp\Api\Debug\GodotSharpEditor.xml"], [])
[ 97%] MSBuild path: C:\Program Files\dotnet\dotnet.exe
[ 99%] progress_finish(["progress_finish"], [])
[100%] Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018: File name: 'Microsoft.DotNet.PlatformAbstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FrameworkReferenceResolver.GetDefaultReferenceAssembliesPath() [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
scons: *** [bin\GodotSharp\Api\Debug\GodotSharp.dll] RuntimeError : 'msbuild' exited with error code: 1
Traceback (most recent call last):
  File "F:\GodotBuild\godot\modules\mono\build_scripts\solution_builder.py", line 106, in run_command
    subprocess.check_call(args, env=env_override)
  File "c:\users\aytas\appdata\local\programs\python\python37-32\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\dotnet\\dotnet.exe', 'msbuild', 'F:\\GodotBuild\\godot\\modules\\mono\\glue/GodotSharp/GodotSharp.sln', '/restore', '/t:Build', '/p:Configuration=Debug', '/p:NoWarn=1591']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\aytas\appdata\local\programs\python\python37-32\lib\site-packages\SCons\Action.py", line 1279, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "F:\GodotBuild\godot\modules\mono\build_scripts\api_solution_build.py", line 21, in build_api_solution
    build_solution(env, solution_path, build_config, extra_msbuild_args=extra_msbuild_args)
  File "F:\GodotBuild\godot\modules\mono\build_scripts\solution_builder.py", line 148, in build_solution
    run_command(msbuild_path, msbuild_args, env_override=msbuild_env, name="msbuild")
  File "F:\GodotBuild\godot\modules\mono\build_scripts\solution_builder.py", line 108, in run_command
    raise RuntimeError("'%s' exited with error code: %s" % (name, e.returncode))
RuntimeError: 'msbuild' exited with error code: 1
scons: building terminated because of errors.
```

### Steps to reproduce

Follow the official documentation for 3.3.3-stable for [Compiling with Mono](https://docs.godotengine.org/en/3.3.3/development/compiling/compiling_with_mono.html#doc-compiling-with-mono), except with `target=debug` and **multithreading enabled**:

```powershell
# Build temporary binary
scons p=windows target=debug tools=yes module_mono_enabled=yes mono_glue=no -j4
# Generate glue sources
bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue 

### Build binaries normally
# Editor
scons p=windows target=debug tools=yes module_mono_enabled=yes -j4
# Export templates
scons p=windows target=debug tools=no module_mono_enabled=yes -j4
scons p=windows target=release_debug tools=no module_mono_enabled=yes -j4
scons p=windows target=release tools=no module_mono_enabled=yes -j4
```

**Comment by CinchBlue** [comment]
I see that the official build of v3.3.3-stable is currently on what seems to be Mono 4.0 or Mono 4.5? Is this correct?

![image](https://user-images.githubusercontent.com/844699/132148842-0c6fcef7-122e-4138-be70-9fc617358864.png)

**Comment by aaronfranke** [comment]
@CinchBlue It's a bit confusing, but the folder is called 4.5 because of the .NET Framework 4.5 API level, not the Mono version. The Mono version that Godot uses is actually the latest 6.12.0.x. And Godot supports features from C# 7 (and some C# 8 features), which is similar to what's available in .NET Framework 4.7.

**Comment by CinchBlue** [comment]
I see. Well, based on this error:

`
C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(192,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. [F:\GodotBuild\godot\modules\mono\glue\GodotSharp\GodotSharp\GodotSharp.csproj]
`

it seems like there is something to track down with SDK targets and project building breaking with regards to Mono. We'll have to see if we can track someone down to take a look at this.
