### ISSUE TITLE
Godot 4.0: Crash if script contains certain invalid syntax [] =

### ISSUE THREAD

**Issue by Racinettee** [godotengine/godot#52617]
### Godot version

4.0.dev 5f69218edc

### System information

Linux Mint 20 - Lenovo Thinkpad & Kubuntu 21.0 - Ideapad

### Issue description

If a script contains the invalid syntax [] = (a guess someone was taking at array append syntax) and then is saved, the godot editor crashes. Attempting to load the project again will cause the editor to crash promptly.
Correcting the syntax back to .append(..) corrects the problem and the project can be loaded.

Additionally the editor does not identify the offending code as invalid by marking it in a red line.

Here is a sample of the offending code:
```
class DialogNode:
	var page_id: int
	var language: String
	
class DialogContents:
	var content : Array
	
	func add_content(content: DialogContent):
		self.content[] = content

class DialogContent:
	var type : String
	var text : String
	
	func _init(text: String, type: String = 'dialog'):
		self.set_text(text)
		self.set_type(type)
	
	func get_type():
		return type
	
	func get_text():
		return text
	
	func set_type(type: String):
		self.type = type
	
	func set_text(text: String):
		self.text = text
```
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (5f69218edc4f4af574c7a65f077e2e0bf1f28365)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7f38c3d12040] (??:0)
[2] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c72b8a] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:207)
[3] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c77eda] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:946)
[4] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c81cb4] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:1831)
[5] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c7c94c] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:?)
[6] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c895e9] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:2439)
[7] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c89b3f] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:?)
[8] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c8a54b] (/home/steve/proj/godot/modules/gdscript/gdscript_compiler.cpp:2607)
[9] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c143aa] (/home/steve/proj/godot/modules/gdscript/gdscript.cpp:?)
[10] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c1e3b3] (/home/steve/proj/godot/modules/gdscript/gdscript.cpp:?)
[11] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3c21c8a] (/home/steve/proj/godot/./core/object/ref_counted.h:220)
[12] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x6bedd5f] (/home/steve/proj/godot/core/io/resource_saver.cpp:?)
[13] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x43ab7ae] (/home/steve/proj/godot/editor/editor_node.cpp:1135)
[14] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x43ac326] (/home/steve/proj/godot/./core/templates/cowdata.h:380)
[15] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x4fcd7e8] (/home/steve/proj/godot/editor/plugins/script_editor_plugin.cpp:?)
[16] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x423fdff] (/home/steve/proj/godot/editor/editor_data.cpp:381)
[17] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x43b4300] (/home/steve/proj/godot/./core/templates/list.h:262)
[18] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x43b321d] (/home/steve/proj/godot/./core/templates/cowdata.h:380)
[19] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x439e2f9] (/home/steve/proj/godot/./core/templates/cowdata.h:380)
[20] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x4417cc0] (/home/steve/proj/godot/./core/variant/binder_common.h:227)
[21] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x6fc1046] (/home/steve/proj/godot/core/object/object.cpp:?)
[22] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x6fbf398] (/home/steve/proj/godot/core/object/object.cpp:1154)
[23] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x56a8159] (/home/steve/proj/godot/scene/gui/popup_menu.cpp:1381)
[24] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x56b6d0b] (/home/steve/proj/godot/scene/gui/popup_menu.cpp:1307)
[25] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x568ab0d] (/home/steve/proj/godot/scene/gui/menu_button.cpp:52)
[26] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x54532fd] (/home/steve/proj/godot/scene/main/node.cpp:2639)
[27] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x547a900] (/home/steve/proj/godot/scene/main/scene_tree.cpp:?)
[28] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x54ab8bf] (/home/steve/proj/godot/scene/main/viewport.cpp:2709)
[29] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x54dd897] (/home/steve/proj/godot/scene/main/window.cpp:923)
[30] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x54f2ca9] (/home/steve/proj/godot/./core/object/ref_counted.h:220)
[31] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x315a336] (/home/steve/proj/godot/platform/linuxbsd/display_server_x11.cpp:?)
[32] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x6c74e1c] (/home/steve/proj/godot/./core/object/ref_counted.h:220)
[33] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x6c75f0a] (/home/steve/proj/godot/./core/templates/list.h:351)
[34] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x315aaa3] (/home/steve/proj/godot/./core/templates/local_vector.h:253)
[35] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3147992] (/home/steve/proj/godot/platform/linuxbsd/os_linuxbsd.cpp:340)
[36] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x3143402] (/home/steve/proj/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[37] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7f38c3cf9565] (??:0)
[38] /home/steve/proj/godot/bin/godot.linuxbsd.opt.tools.64.llvm() [0x314328e] (??:?)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Using the minimal reproduction project:

1. Open Node2D.gd
2. Change line 11: `self.content.append(content)` into `self.content[] = content`
3. Save
4. The editor should crash
5. Subsequently attempting to load the project now will also crash
6. Reverting the change from a different editor will enable the project to load

### Minimal reproduction project

[ScriptBug.zip](https://github.com/godotengine/godot/files/7150356/ScriptBug.zip)

**Comment by Ev1lbl0w** [comment]
Stacktrace:
```
#0  0x00007f42eb0dbd22 in raise () from /usr/lib/libc.so.6
#1  0x00007f42eb0c5862 in abort () from /usr/lib/libc.so.6
#2  0x0000000003dac704 in handle_crash (sig=11) at platform/linuxbsd/crash_handler_linuxbsd.cpp:120
#3  <signal handler called>
#4  0x000000000427f4f1 in GDScriptCompiler::_parse_expression (this=0x7f427effbb48, codegen=..., r_error=@0x7f427effa2a4: OK, p_expression=0x0, p_root=false, p_initializer=false, p_index_addr=...)
    at modules/gdscript/gdscript_compiler.cpp:208
#5  0x00000000042868b4 in GDScriptCompiler::_parse_expression (this=0x7f427effbb48, codegen=..., r_error=@0x7f427effa2a4: OK, p_expression=0x7f427400ac40, p_root=true, p_initializer=false, p_index_addr=...)
    at modules/gdscript/gdscript_compiler.cpp:942
#6  0x000000000428d4c9 in GDScriptCompiler::_parse_block (this=0x7f427effbb48, codegen=..., p_block=0x7f4274009b40, p_add_locals=true) at modules/gdscript/gdscript_compiler.cpp:1789
#7  0x000000000428eb29 in GDScriptCompiler::_parse_function (this=0x7f427effbb48, p_script=0x7f4274013ed0, p_class=0x7f4274008e30, p_func=0x7f4274009840, p_for_ready=false)
    at modules/gdscript/gdscript_compiler.cpp:1931
#8  0x0000000004293e40 in GDScriptCompiler::_parse_class_blocks (this=0x7f427effbb48, p_script=0x7f4274013ed0, p_class=0x7f4274008e30, p_keep_state=false) at modules/gdscript/gdscript_compiler.cpp:2394
#9  0x00000000042943f9 in GDScriptCompiler::_parse_class_blocks (this=0x7f427effbb48, p_script=0x7f4274003cf0, p_class=0x7f4274007a20, p_keep_state=false) at modules/gdscript/gdscript_compiler.cpp:2490
#10 0x0000000004294b62 in GDScriptCompiler::compile (this=0x7f427effbb48, p_parser=0x7f427effbba8, p_script=0x7f4274003cf0, p_keep_state=false) at modules/gdscript/gdscript_compiler.cpp:2561
#11 0x000000000420e299 in GDScript::reload (this=0x7f4274003cf0, p_keep_state=false) at modules/gdscript/gdscript.cpp:842
#12 0x00000000041a0a9b in GDScriptCache::get_full_script (p_path=..., r_error=@0x7f427effbff4: OK, p_owner=...) at modules/gdscript/gdscript_cache.cpp:211
#13 0x000000000421b0f6 in ResourceFormatLoaderGDScript::load (this=0x9293b60, p_path=..., p_original_path=..., r_error=0x7f42740019f4, p_use_sub_threads=false, r_progress=0x7f42740019e8, 
    p_cache_mode=ResourceFormatLoader::CACHE_MODE_REUSE) at modules/gdscript/gdscript.cpp:2341
#14 0x0000000006f68c1c in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_cache_mode=ResourceFormatLoader::CACHE_MODE_REUSE, r_error=0x7f42740019f4, p_use_sub_threads=false, 
    r_progress=0x7f42740019e8) at core/io/resource_loader.cpp:194
#15 0x0000000006f693c6 in ResourceLoader::_thread_load_function (p_userdata=0x7f42740019b8) at core/io/resource_loader.cpp:221
#16 0x0000000006f6c7c7 in ResourceLoader::load (p_path=..., p_type_hint=..., p_cache_mode=ResourceFormatLoader::CACHE_MODE_REUSE, r_error=0x0) at core/io/resource_loader.cpp:576
#17 0x00000000045844c9 in EditorFileSystem::_scan_new_dir (this=0x9b51440, p_dir=0x7f4274001660, da=0x7f4274002e60, p_progress=...) at editor/editor_file_system.cpp:818
#18 0x00000000045828c8 in EditorFileSystem::_scan_filesystem (this=0x9b51440) at editor/editor_file_system.cpp:294
#19 0x00000000045859bd in EditorFileSystem::_thread_func (_userdata=0x9b51440) at editor/editor_file_system.cpp:324
#20 0x0000000006cc84c8 in Thread::callback (p_self=0x9b51660, p_settings=..., p_callback=0x45859a0 <EditorFileSystem::_thread_func(void*)>, p_userdata=0x9b51440) at core/os/thread.cpp:72
#21 0x0000000006cc979a in std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __f=@0x2117d988: 0x6cc8440 <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>, __args=@0x2117d968: 0x9b51440, __args=@0x2117d968: 0x9b51440, __args=@0x2117d968: 0x9b51440, 
    __args=@0x2117d968: 0x9b51440) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/invoke.h:61
#22 0x0000000006cc9611 in std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __fn=@0x2117d988: 0x6cc8440 <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>, __args=@0x2117d968: 0x9b51440, __args=@0x2117d968: 0x9b51440, __args=@0x2117d968: 0x9b51440, 
    __args=@0x2117d968: 0x9b51440) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/invoke.h:96
#23 0x0000000006cc958d in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x2117d968) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/std_thread.h:253
#24 0x0000000006cc94f5 in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator() (
    this=0x2117d968) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/std_thread.h:260
#25 0x0000000006cc9169 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run (this=0x2117d960) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/std_thread.h:211
#26 0x00007f42eb49f3c4 in std::execute_native_thread_routine (__p=0x2117d960) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#27 0x00007f42eb5fc259 in start_thread () from /usr/lib/libpthread.so.0
#28 0x00007f42eb19d5e3 in clone () from /usr/lib/libc.so.6
```
Bisected to c6e66a43b0eae569b60c85d3f26009ed52f97861 (https://github.com/godotengine/godot/pull/47454)
