### ISSUE TITLE
4.0: Freeze if programatically created node + signals are not connected to tree when changing scene

### ISSUE THREAD

**Issue by Racinettee** [godotengine/godot#52640]
### Godot version

4.0.dev 0c2ab55a58

### System information

Kubuntu 21.04 - Lenovo Ideapad S145

### Issue description

If I programatically create a node and attach signals to it, then attempt to change the scene, the running game will freeze with the message
```
ERROR: Disconnecting nonexistent signal '<signal name>', callable: Object(Node2D.gd)::on_item_activated.
   at: _disconnect (core/object/object.cpp:1406)
```
if the node was not attached to the tree. If the node was attached to the tree, then the scene will change successfully.

I reproduced the issue using an item list, and a node2d just to be sure that the type of the node is not a factor.

### Steps to reproduce

Using the minimal reproduction project:

1. Open Node2D.tscn
2. Run the project
3. Click the button "Click"
4. Observe that the game is now stuck, while in the console the `Error: Disconnecting nonexistent` message is being logged repeatedly
5. Kill the running game using the stop button in the editor
6. Open Node2D.gd
7. Uncomment line 27: `call_deferred("add_child", inventory_menu)`
8. Run the project
9. Click the button
10. The scene successfully changes to Control.tscn

### Minimal reproduction project

[SceneChangeSignalBug.zip](https://github.com/godotengine/godot/files/7156844/SceneChangeSignalBug.zip)

**Comment by Calinou** [comment]
@Racinettee Does this occur when following the same steps in 3.3.3?

**Comment by Racinettee** [comment]
@Calinou I recreated the test in 3.3.3 and the problem didn't occur

**Comment by Racinettee** [comment]
Just wanted to add another detail so it doesn't fly under the radar: the same freeze happens when you try to close the game via its X button

**Comment by qarmin** [comment]
Backtrace
```
#0  __GI___tcgetattr (fd=1, termios_p=termios_p@entry=0x7fffffffcd80) at ../sysdeps/unix/sysv/linux/tcgetattr.c:38
#1  0x00007ffff7b765c0 in __isatty (fd=<optimized out>) at ../sysdeps/posix/isatty.c:27
#2  0x0000000003846e9e in UnixTerminalLogger::log_error (this=0xab5ca10, p_function=0x92593a2 "_disconnect", p_file=0x9258b45 "core/object/object.cpp", p_line=1406, 
    p_code=0x92594f8 "Condition \"!s->slot_map.has(*p_callable.get_base_comparator())\" is true.", 
    p_rationale=0xd8f2e90 "Disconnecting nonexistent signal 'item_activated', callable: Object(Node2D.gd)::on_item_activated.", p_type=Logger::ERR_ERROR) at drivers/unix/os_unix.cpp:546
#3  0x0000000006183423 in CompositeLogger::log_error (this=0xab5ca50, p_function=0x92593a2 "_disconnect", p_file=0x9258b45 "core/object/object.cpp", p_line=1406, 
    p_code=0x92594f8 "Condition \"!s->slot_map.has(*p_callable.get_base_comparator())\" is true.", 
    p_rationale=0xd8f2e90 "Disconnecting nonexistent signal 'item_activated', callable: Object(Node2D.gd)::on_item_activated.", p_type=Logger::ERR_ERROR) at core/io/logger.cpp:265
#4  0x000000000607141b in OS::print_error (this=0x7fffffffd9e0, p_function=0x92593a2 "_disconnect", p_file=0x9258b45 "core/object/object.cpp", p_line=1406, 
    p_code=0x92594f8 "Condition \"!s->slot_map.has(*p_callable.get_base_comparator())\" is true.", 
    p_rationale=0xd8f2e90 "Disconnecting nonexistent signal 'item_activated', callable: Object(Node2D.gd)::on_item_activated.", p_type=Logger::ERR_ERROR) at core/os/os.cpp:84
#5  0x00000000065e8b3b in _err_print_error (p_function=0x92593a2 "_disconnect", p_file=0x9258b45 "core/object/object.cpp", p_line=1406, 
    p_error=0x92594f8 "Condition \"!s->slot_map.has(*p_callable.get_base_comparator())\" is true.", 
    p_message=0xd8f2e90 "Disconnecting nonexistent signal 'item_activated', callable: Object(Node2D.gd)::on_item_activated.", p_type=ERR_HANDLER_ERROR) at core/error/error_macros.cpp:77
#6  0x00000000065e8cd3 in _err_print_error (p_function=0x92593a2 "_disconnect", p_file=0x9258b45 "core/object/object.cpp", p_line=1406, 
    p_error=0x92594f8 "Condition \"!s->slot_map.has(*p_callable.get_base_comparator())\" is true.", p_message=..., p_type=ERR_HANDLER_ERROR) at core/error/error_macros.cpp:94
#7  0x0000000006570075 in Object::_disconnect (this=0xd7513c0, p_signal=..., p_callable=..., p_force=true) at core/object/object.cpp:1406
#8  0x0000000006575a26 in Object::~Object (this=0xd75e740, __in_chrg=<optimized out>) at core/object/object.cpp:1887
#9  0x0000000004a0f720 in Node::~Node (this=0xd75e740, __in_chrg=<optimized out>) at scene/main/node.cpp:2878
#10 0x00000000049bc683 in CanvasItem::~CanvasItem (this=0xd75e740, __in_chrg=<optimized out>) at scene/main/canvas_item.cpp:1152
#11 0x000000000271f884 in Control::~Control (this=0xd75e740, __in_chrg=<optimized out>) at ./scene/gui/control.h:47
#12 0x000000000271f8f4 in Container::~Container (this=0xd75e740, __in_chrg=<optimized out>) at ./scene/gui/container.h:36
#13 0x000000000272c159 in memdelete<Node> (p_class=0xd75e740) at ./core/os/memory.h:109
#14 0x0000000004a32917 in SceneTree::_change_scene (this=0xca97090, p_to=0xd88bea0) at scene/main/scene_tree.cpp:1068
#15 0x00000000039c2abb in call_with_variant_args_helper<__UnexistingClass, Node*, 0ul> (p_instance=0xca97090, p_method=
    (void (__UnexistingClass::*)(__UnexistingClass * const, Node *)) 0x4a328e0 <SceneTree::_change_scene(Node*)>, p_args=0x7fffffffd370, r_error=...) at ./core/variant/binder_common.h:222
#16 0x00000000039c2701 in call_with_variant_args_dv<__UnexistingClass, Node*> (p_instance=0xca97090, p_method=
    (void (__UnexistingClass::*)(__UnexistingClass * const, Node *)) 0x4a328e0 <SceneTree::_change_scene(Node*)>, p_args=0x7fffffffd580, p_argcount=1, r_error=..., default_values=...)
    at ./core/variant/binder_common.h:369
#17 0x00000000039c1c7a in MethodBindT<Node*>::call (this=0xd14b2b0, p_object=0xca97090, p_args=0x7fffffffd580, p_arg_count=1, r_error=...) at ./core/object/method_bind.h:286
#18 0x000000000656af2c in Object::call (this=0xca97090, p_method=..., p_args=0x7fffffffd580, p_argcount=1, r_error=...) at core/object/object.cpp:832
#19 0x00000000062b9ee7 in Callable::call (this=0x7ffff5a67020, p_arguments=0x7fffffffd580, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:62
#20 0x0000000006563822 in MessageQueue::_call_function (this=0xacd8d00, p_callable=..., p_args=0x7ffff5a67038, p_argcount=1, p_show_error=false) at core/object/message_queue.cpp:258
#21 0x0000000006563b76 in MessageQueue::flush (this=0xacd8d00) at core/object/message_queue.cpp:304
#22 0x0000000004a2ed43 in SceneTree::physics_process (this=0xca97090, p_time=0.01666666753590107) at scene/main/scene_tree.cpp:422
#23 0x000000000224f677 in Main::iteration () at main/main.cpp:2514
#24 0x000000000220d214 in OS_LinuxBSD::run (this=0x7fffffffd9e0) at platform/linuxbsd/os_linuxbsd.cpp:342
#25 0x00000000022095bc in main (argc=1, argv=0x7fffffffded8) at platform/linuxbsd/godot_linuxbsd.cpp:58
```
