### ISSUE TITLE
Freeze when trying to run `Skeleton::unparent_bone_and_rest`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#52875]
### Godot version

3.4.beta.custom_build. 7c1ee0488

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When trying to execute this code found by fuzzer
```
	var temp_variable20763 = Skeleton.new()
	temp_variable20763.add_bone("1737308484")
	temp_variable20763.set_bone_rest(-13, Transform(Basis(Vector3(-27.588329, -27.052244, -43.629082), Vector3(-0.315412, -0.04932, -0.947672), Vector3(-0.68459, -0.455983, 0.568696)), Vector3(-48.127342, 39.633404, -35.498764)))
	temp_variable20763.get_bone_custom_pose(14)
	temp_variable20763.physical_bones_add_collision_exception(RID())
	temp_variable20763.get_bone_name(23)
	temp_variable20763.unbind_child_node_from_bone(-23, SliderJoint.new())
	temp_variable20763.set_bone_parent(-14, 31)
	temp_variable20763.set_bone_pose(-24, Transform(Basis(Vector3(0.620706, 0.703816, 0.345495), Vector3(-0.094666, -0.88936, -0.4473), Vector3(0.501806, 0.076871, 0.861558)), Vector3(3.71843, -33.890644, -2.770305)))
	temp_variable20763.bind_child_node_to_bone(-13, null)
	temp_variable20763.physical_bones_stop_simulation()
	temp_variable20763.get_bone_pose(-34)
	temp_variable20763.physical_bones_start_simulation(Array([]))
	temp_variable20763.set_bone_name(-10, ".")
	temp_variable20763.get_bone_count()
	temp_variable20763.add_bone("2234016700")
	temp_variable20763.register_skin(null)
	temp_variable20763.physical_bones_add_collision_exception(RID())
	temp_variable20763.unbind_child_node_from_bone(-21, ARVROrigin.new())
	temp_variable20763.set_bone_parent(1, 1)
	temp_variable20763.get_bone_global_pose_no_override(-49)
	temp_variable20763.bind_child_node_to_bone(14, VehicleWheel.new())
	temp_variable20763.physical_bones_remove_collision_exception(RID())
	temp_variable20763.get_bone_parent(11)
	temp_variable20763.is_bone_rest_disabled(-41)
	temp_variable20763.unparent_bone_and_rest(1)
```
then Godot freeze here(in infinite loop)
```
Thread 1 "godot" received signal SIGINT, Interrupt.
CowData<Skeleton::Bone>::_get_data (this=0xc902660) at ./core/cowdata.h:82
82			if (!_ptr) {
(gdb) backtrace
#0  CowData<Skeleton::Bone>::_get_data (this=0xc902660) at ./core/cowdata.h:82
#1  0x0000000003b5d9bb in CowData<Skeleton::Bone>::get (this=0xc902660, p_index=1) at ./core/cowdata.h:158
#2  0x0000000003b5c55c in Vector<Skeleton::Bone>::operator[] (this=0xc902658, p_index=1) at ./core/vector.h:87
#3  0x0000000003b57313 in Skeleton::unparent_bone_and_rest (this=0xc902350, p_bone=1) at scene/3d/skeleton.cpp:473
#4  0x0000000001875101 in MethodBind1<int>::call (this=0x99abef0, p_object=0xc902350, p_args=0x7fffffffca70, p_arg_count=1, r_error=...)
    at ./core/method_bind.gen.inc:775
#5  0x00000000046cc79c in Object::call (this=0xc902350, p_method=..., p_args=0x7fffffffca70, p_argcount=1, r_error=...) at core/object.cpp:918
#6  0x0000000004769547 in Variant::call_ptr (this=0x7fffffffca10, p_method=..., p_args=0x7fffffffca70, p_argcount=1, r_ret=0x0, r_error=...)
    at core/variant_call.cpp:1175
#7  0x00000000018e9881 in GDScriptFunction::call (this=0xc903730, p_instance=0x9f45ae0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0)
    at modules/gdscript/gdscript_function.cpp:1046
#8  0x000000000188abab in GDScriptInstance::_ml_call_reversed (this=0x9f45ae0, sptr=0xc912590, p_method=..., p_args=0x0, p_argcount=0)
    at modules/gdscript/gdscript.cpp:1199
#9  0x000000000188ac34 in GDScriptInstance::call_multilevel_reversed (this=0x9f45ae0, p_method=..., p_args=0x0, p_argcount=0)
    at modules/gdscript/gdscript.cpp:1205
#10 0x00000000036b14c4 in Node::_notification (this=0x9798450, p_notification=13) at scene/main/node.cpp:146
#11 0x0000000001847e54 in Node::_notificationv (this=0x9798450, p_notification=13, p_reversed=false) at ./scene/main/node.h:45
#12 0x0000000001848511 in CanvasItem::_notificationv (this=0x9798450, p_notification=13, p_reversed=false) at ./scene/2d/canvas_item.h:162
#13 0x0000000003bd0917 in Node2D::_notificationv (this=0x9798450, p_notification=13, p_reversed=false) at ./scene/2d/node_2d.h:37
#14 0x00000000046cc8db in Object::notification (this=0x9798450, p_notification=13, p_reversed=false) at core/object.cpp:927
#15 0x00000000036b1906 in Node::_propagate_ready (this=0x9798450) at scene/main/node.cpp:187
#16 0x00000000036b188a in Node::_propagate_ready (this=0xa04a2f0) at scene/main/node.cpp:179
#17 0x00000000036bfa54 in Node::_set_tree (this=0xa04a2f0, p_tree=0x9de4410) at scene/main/node.cpp:2557
#18 0x00000000036e71f2 in SceneTree::init (this=0x9de4410) at scene/main/scene_tree.cpp:464
#19 0x00000000017aa671 in OS_X11::run (this=0x7fffffffd6a0) at platform/x11/os_x11.cpp:3629
#20 0x000000000179733b in main (argc=1, argv=0x7fffffffdf98) at platform/x11/godot_x11.cpp:55
```

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Looks that now it is allowed set self bone as parent, but this should be prohibited.
