### ISSUE TITLE
Freeze when multiple times trying to use `light_unwrap` on ArrayMesh

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#52929]
### Godot version

v3.4.beta.custom_build [40b57319e]

### System information

Ubuntu 21.04, Intel HD 3000

### Issue description

When executing this code
```
func _process(delta):
	for i in range(10):
		var temp_variable20998 = ArrayMesh.new()
		temp_variable20998.lightmap_unwrap(Transform(Basis(Vector3(-27.728373, -13.912577, -18.400038), Vector3(-49.337036, -41.084751, -36.448166), Vector3(-0.635621, 0.725294, 0.264451)), Vector3(0.002048, 0.727567, -0.686034)), 26.292253)
	print(delta)
```
app freeze
```
__futex_abstimed_wait_common64 (cancel=true, private=128, abstime=0x0, clockid=0, expected=83947, futex_word=0x7fffd2ffd910) at ../sysdeps/nptl/futex-internal.c:74
74	../sysdeps/nptl/futex-internal.c: Nie ma takiego pliku ani katalogu.
(gdb) backtrace
#0  __futex_abstimed_wait_common64 (cancel=true, private=128, abstime=0x0, clockid=0, expected=83947, futex_word=0x7fffd2ffd910) at ../sysdeps/nptl/futex-internal.c:74
#1  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7fffd2ffd910, expected=83947, clockid=clockid@entry=0, abstime=abstime@entry=0x0, 
    private=private@entry=128) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007ffff7d8d984 in __pthread_clockjoin_ex (threadid=140736733369920, thread_return=0x0, clockid=0, abstime=0x0, block=<optimized out>) at pthread_join_common.c:102
#3  0x0000000004ba9c07 in std::thread::join() ()
#4  0x0000000001ee31e5 in xatlas::internal::TaskScheduler::~TaskScheduler (this=0x7dac010, __in_chrg=<optimized out>) at thirdparty/xatlas/xatlas.cpp:2989
#5  0x0000000001ed4505 in xatlas::Destroy (atlas=0x7dc2720) at thirdparty/xatlas/xatlas.cpp:8535
#6  0x0000000001bbb120 in xatlas_mesh_lightmap_unwrap_callback (p_texel_size=26.2922535, p_vertices=0x0, p_normals=0x0, p_vertex_count=0, p_indices=0x0, p_face_materials=0x0, 
    p_index_count=0, r_uv=0x7fffffffc4d8, r_vertex=0x7fffffffc4e0, r_vertex_count=0x7fffffffc46c, r_index=0x7fffffffc570, r_index_count=0x7fffffffc470, 
    r_size_hint_x=0x7fffffffc474, r_size_hint_y=0x7fffffffc4c8) at modules/xatlas_unwrap/register_types.cpp:80
#7  0x0000000003ef547b in ArrayMesh::lightmap_unwrap_cached (this=0x7daf500, r_cache_data=@0x7fffffffc7d0: 0x0, r_cache_size=@0x7fffffffc7cc: 0, 
    r_used_cache=@0x7fffffffc7cb: false, p_base_transform=..., p_texel_size=26.2922535) at scene/resources/mesh.cpp:1312
#8  0x0000000003ef3edc in ArrayMesh::lightmap_unwrap (this=0x7daf500, p_base_transform=..., p_texel_size=26.2922535) at scene/resources/mesh.cpp:1121
#9  0x0000000003f075cf in MethodBind2R<Error, Transform const&, float>::call (this=0x7866f70, p_object=0x7daf500, p_args=0x7fffffffcb40, p_arg_count=2, r_error=...)
    at ./core/method_bind.gen.inc:1717
#10 0x0000000004667fb8 in Object::call (this=0x7daf500, p_method=..., p_args=0x7fffffffcb40, p_argcount=2, r_error=...) at core/object.cpp:918
#11 0x0000000004704a33 in Variant::call_ptr (this=0x7fffffffcae0, p_method=..., p_args=0x7fffffffcb40, p_argcount=2, r_ret=0x0, r_error=...) at core/variant_call.cpp:1173
#12 0x00000000018c92b2 in GDScriptFunction::call (this=0x7d9d2e0, p_instance=0x7a322b0, p_args=0x7fffffffd3a8, p_argcount=1, r_err=..., p_state=0x0)
    at modules/gdscript/gdscript_function.cpp:1034
#13 0x000000000186a634 in GDScriptInstance::call_multilevel (this=0x7a322b0, p_method=..., p_args=0x7fffffffd3a8, p_argcount=1) at modules/gdscript/gdscript.cpp:1166
#14 0x000000000366dcc2 in Node::_notification (this=0x6eac1e0, p_notification=17) at scene/main/node.cpp:56
#15 0x0000000001827a7e in Node::_notificationv (this=0x6eac1e0, p_notification=17, p_reversed=false) at ./scene/main/node.h:45
#16 0x000000000182813b in CanvasItem::_notificationv (this=0x6eac1e0, p_notification=17, p_reversed=false) at ./scene/2d/canvas_item.h:162
#17 0x0000000003b7f015 in Node2D::_notificationv (this=0x6eac1e0, p_notification=17, p_reversed=false) at ./scene/2d/node_2d.h:37
#18 0x00000000046680f7 in Object::notification (this=0x6eac1e0, p_notification=17, p_reversed=false) at core/object.cpp:927
#19 0x00000000036a7151 in SceneTree::_notify_group_pause (this=0x7c3b820, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:969
#20 0x00000000036a4c56 in SceneTree::idle (this=0x7c3b820, p_time=0.0166666675) at scene/main/scene_tree.cpp:524
#21 0x00000000017caf47 in Main::iteration () at main/main.cpp:2105
#22 0x000000000178e5c4 in OS_X11::run (this=0x7fffffffd830) at platform/x11/os_x11.cpp:3638
#23 0x000000000177b33b in main (argc=1, argv=0x7fffffffe128) at platform/x11/godot_x11.cpp:55
```

looks that this may be caused by caching mechanism

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Fixed in master
