### ISSUE TITLE
Executing `RichTextLabel.set_language` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53218]
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var temp_variable52540 = RichTextLabel.new()
	temp_variable52540.set_structured_text_bidi_override(1)
	temp_variable52540.push_font_size(0)
	temp_variable52540.add_image(CurveTexture.new(), -45, 43, Color(-10.731050491333, 12.697940826416, -40.8050727844238, 1), -46)
	temp_variable52540.add_text(".")
	temp_variable52540.append_text(".")
	temp_variable52540.set_language("2775164943")
```

Address sanitizer shows this info
```
ERROR: Condition "p_size <= 0" is true. Returning: false
   at: shaped_text_add_string (modules/text_server_adv/text_server_adv.cpp:2986)
=================================================================
==49223==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030005d1854 at pc 0x56067e86e8ac bp 0x7ffdc0b15e10 sp 0x7ffdc0b15e00
READ of size 2 at 0x6030005d1854 thread T0
    #0 0x56067e86e8ab in ubidi_getBaseDirection_69 thirdparty/icu4c/common/ubidi.cpp:357
    #1 0x56066958b417 in TextServerAdvanced::shaped_text_shape(RID) modules/text_server_adv/text_server_adv.cpp:4303
    #2 0x56066956fd41 in TextServerAdvanced::shaped_text_tab_align(RID, Vector<float> const&) modules/text_server_adv/text_server_adv.cpp:3523
    #3 0x560678938e4e in TextParagraph::_shape_lines() scene/resources/text_paragraph.cpp:143
    #4 0x56067894bbf6 in TextParagraph::get_size() const scene/resources/text_paragraph.cpp:438
    #5 0x560675dba705 in RichTextLabel::_validate_line_caches(RichTextLabel::ItemFrame*) scene/gui/rich_text_label.cpp:2210
    #6 0x560675e02b48 in RichTextLabel::set_language(String const&) scene/gui/rich_text_label.cpp:3976
    #7 0x5606681d626e in void call_with_variant_args_helper<__UnexistingClass, String const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:222
    #8 0x5606681d2955 in void call_with_variant_args_dv<__UnexistingClass, String const&>(__UnexistingClass*, void (__UnexistingClass::*)(String const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:369
    #9 0x5606681ceeda in MethodBindT<String const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:286
    #10 0x56067d8678e9 in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:832
    #11 0x56067cf4ff8b in Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1017
    #12 0x56066d37637e in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1487
    #13 0x56066ce58071 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #14 0x560674fe9846 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #15 0x560674f619aa in Node::_notification(int) scene/main/node.cpp:58
    #16 0x560667e44f4d in Node::_notificationv(int, bool) scene/main/node.h:48
    #17 0x560668cc6f80 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #18 0x560674ca5060 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #19 0x56067d867cf8 in Object::notification(int, bool) core/object/object.cpp:841
    #20 0x560675090589 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #21 0x560675082c22 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #22 0x56066753a331 in Main::iteration() main/main.cpp:2563
    #23 0x5606673d601c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #24 0x5606673c46b3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #25 0x7f4cb9e09564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #26 0x5606673c41ed in _start (/usr/bin/godot4s+0x2ff3d1ed)

0x6030005d1854 is located 0 bytes to the right of 20-byte region [0x6030005d1840,0x6030005d1854)
allocated by thread T0 here:
    #0 0x7f4cbadd8c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x56067c3bfbc7 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x56067da0750f in CowData<char16_t>::resize(int) core/templates/cowdata.h:292
    #3 0x56067da06bd7 in Char16String::resize(int) core/string/ustring.h:92
    #4 0x56067d9dd1a2 in String::utf16() const core/string/ustring.cpp:2074
    #5 0x56066958a221 in TextServerAdvanced::shaped_text_shape(RID) modules/text_server_adv/text_server_adv.cpp:4270
    #6 0x56066956fd41 in TextServerAdvanced::shaped_text_tab_align(RID, Vector<float> const&) modules/text_server_adv/text_server_adv.cpp:3523
    #7 0x560678938e4e in TextParagraph::_shape_lines() scene/resources/text_paragraph.cpp:143
    #8 0x56067894bbf6 in TextParagraph::get_size() const scene/resources/text_paragraph.cpp:438
    #9 0x560675dba705 in RichTextLabel::_validate_line_caches(RichTextLabel::ItemFrame*) scene/gui/rich_text_label.cpp:2210
    #10 0x560675e02b48 in RichTextLabel::set_language(String const&) scene/gui/rich_text_label.cpp:3976
    #11 0x5606681d626e in void call_with_variant_args_helper<__UnexistingClass, String const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:222
    #12 0x5606681d2955 in void call_with_variant_args_dv<__UnexistingClass, String const&>(__UnexistingClass*, void (__UnexistingClass::*)(String const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:369
    #13 0x5606681ceeda in MethodBindT<String const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:286
    #14 0x56067d8678e9 in Object::call(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:832
    #15 0x56067cf4ff8b in Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1017
    #16 0x56066d37637e in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1487
    #17 0x56066ce58071 in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #18 0x560674fe9846 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #19 0x560674f619aa in Node::_notification(int) scene/main/node.cpp:58
    #20 0x560667e44f4d in Node::_notificationv(int, bool) scene/main/node.h:48
    #21 0x560668cc6f80 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #22 0x560674ca5060 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #23 0x56067d867cf8 in Object::notification(int, bool) core/object/object.cpp:841
    #24 0x560675090589 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #25 0x560675082c22 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #26 0x56066753a331 in Main::iteration() main/main.cpp:2563
    #27 0x5606673d601c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #28 0x5606673c46b3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #29 0x7f4cb9e09564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: heap-buffer-overflow thirdparty/icu4c/common/ubidi.cpp:357 in ubidi_getBaseDirection_69

```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

**Comment by bruvzg** [comment]
Probably related to the `set_structured_text_bidi_override` call not a `set_language`.

**Comment by KoBeWi** [comment]
Doesn't seem to crash anymore in a007102
