### ISSUE TITLE
Executing SoftBody.set_physics_enabled crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53367]
### Godot version

3.4.beta.custom_build. dbe0e4613

### System information

Ubuntu 21.04, Intel HD 3000

### Issue description

When executing
```
func _process(delta):
	var temp_variable10275 = SoftBody.new()
	add_child(temp_variable10275)
	temp_variable10275.set_mesh(PrismMesh.new())
	temp_variable10275.set_physics_enabled(false)
	temp_variable10275.set_point_pinned(randi()%1000 - 500, true, NodePath("."))
	temp_variable10275.set_physics_enabled(true)
```

Godot crashes with this info
```
=================================================================
==5414==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61900016e3f0 at pc 0x0000042cdc44 bp 0x7ffc97fcb760 sp 0x7ffc97fcb750
WRITE of size 4 at 0x61900016e3f0 thread T0
    #0 0x42cdc43 in btSoftBody::setMass(int, float) thirdparty/bullet/BulletSoftBody/btSoftBody.cpp:791
    #1 0x2fb3073 in SoftBodyBullet::setup_soft_body() modules/bullet/soft_body_bullet.cpp:452
    #2 0x2fae253 in SoftBodyBullet::set_trimesh_body_shape(PoolVector<int>, PoolVector<Vector3>) modules/bullet/soft_body_bullet.cpp:397
    #3 0x2fa22a3 in SoftBodyBullet::set_soft_mesh(Ref<Mesh> const&) modules/bullet/soft_body_bullet.cpp:133
    #4 0x2e83adf in BulletPhysicsServer::soft_body_set_mesh(RID, Ref<Reference> const&) modules/bullet/bullet_physics_server.cpp:924
    #5 0xdebcd34 in SoftBody::prepare_physics_server() scene/3d/soft_body.cpp:471
    #6 0xdec10c5 in SoftBody::set_physics_enabled(bool) scene/3d/soft_body.cpp:580
    #7 0x23c1564 in MethodBind1<bool>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #8 0x11d2941f in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #9 0x11fb1898 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1175
    #10 0x1e60f19 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1046
    #11 0x1c92bc5 in GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1199
    #12 0x1c92e78 in GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1205
    #13 0xc4b409c in Node::_notification(int) scene/main/node.cpp:146
    #14 0x1b3d991 in Node::_notificationv(int, bool) scene/main/node.h:45
    #15 0x1b3fe06 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:163
    #16 0xe0eff8a in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #17 0x11d298b9 in Object::notification(int, bool) core/object.cpp:927
    #18 0xc4b6019 in Node::_propagate_ready() scene/main/node.cpp:187
    #19 0xc4b587f in Node::_propagate_ready() scene/main/node.cpp:179
    #20 0xc507812 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2557
    #21 0xc5cd4bc in SceneTree::init() scene/main/scene_tree.cpp:464
    #22 0x185a8a3 in OS_X11::run() platform/x11/os_x11.cpp:3629
    #23 0x17c5d8b in main platform/x11/godot_x11.cpp:55
    #24 0x7fda8e874564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #25 0x17c59ad in _start (/usr/bin/godots+0x17c59ad)

0x61900016e3f0 is located 76 bytes to the right of 1060-byte region [0x61900016df80,0x61900016e3a4)
freed by thread T0 here:
    #0 0x7fda8f7dc8f7 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:127
    #1 0x4af52ba in mbedtls_pem_free thirdparty/mbedtls/library/pem.c:454
    #2 0x38bc425 in mbedtls_x509_crt_parse thirdparty/mbedtls/library/x509_crt.c:1264
    #3 0x38cc93a in X509CertificateMbedTLS::load_from_memory(unsigned char const*, int) modules/mbedtls/crypto_mbedtls.cpp:170
    #4 0x38d1c26 in CryptoMbedTLS::load_default_certificates(String) modules/mbedtls/crypto_mbedtls.cpp:334
    #5 0x124f663b in Crypto::load_default_certificates(String) core/crypto/crypto.cpp:97
    #6 0x197b0df in Main::start() main/main.cpp:1984
    #7 0x17c5cbe in main platform/x11/godot_x11.cpp:54
    #8 0x7fda8e874564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

previously allocated by thread T0 here:
    #0 0x7fda8f7dce17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x4af4af3 in mbedtls_pem_read_buffer thirdparty/mbedtls/library/pem.c:378
    #2 0x38bc216 in mbedtls_x509_crt_parse thirdparty/mbedtls/library/x509_crt.c:1226
    #3 0x38cc93a in X509CertificateMbedTLS::load_from_memory(unsigned char const*, int) modules/mbedtls/crypto_mbedtls.cpp:170
    #4 0x38d1c26 in CryptoMbedTLS::load_default_certificates(String) modules/mbedtls/crypto_mbedtls.cpp:334
    #5 0x124f663b in Crypto::load_default_certificates(String) core/crypto/crypto.cpp:97
    #6 0x197b0df in Main::start() main/main.cpp:1984
    #7 0x17c5cbe in main platform/x11/godot_x11.cpp:54
    #8 0x7fda8e874564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: heap-buffer-overflow thirdparty/bullet/BulletSoftBody/btSoftBody.cpp:791 in btSoftBody::setMass(int, float)


```

### Steps to reproduce

Above

**Comment by akien-mga** [comment]
Fixed by #53380.
