### ISSUE TITLE
Executing `SoftBody._draw_soft_mesh` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53437]
### Godot version

3.4.beta.custom_build. 01ae4888e

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
func _process(delta) -> void:
#func _ready() -> void:
	var temp_variable10262 = SoftBody.new()
	add_child(temp_variable10262)
	temp_variable10262.set_mesh(PrismMesh.new())
	temp_variable10262._draw_soft_mesh()
	temp_variable10262.set_physics_enabled(false)
	temp_variable10262.set_mesh(CubeMesh.new())
	temp_variable10262.set_physics_enabled(true)
	temp_variable10262._draw_soft_mesh()
```

Godot crashes with backtrace
```
==32250==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6140000199e0 at pc 0x7f37333b52d3 bp 0x7ffd2c128c10 sp 0x7ffd2c1283b8
WRITE of size 12 at 0x6140000199e0 thread T0
    #0 0x7f37333b52d2 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827
    #1 0xdf1e531 in SoftBodyVisualServerHandler::set_vertex(int, void const*) scene/3d/soft_body.cpp:86
    #2 0x2fae99c in SoftBodyBullet::update_visual_server(SoftBodyVisualServerHandler*) modules/bullet/soft_body_bullet.cpp:100
    #3 0x2e90479 in BulletPhysicsServer::soft_body_update_visual_server(RID, SoftBodyVisualServerHandler*) modules/bullet/bullet_physics_server.cpp:889
    #4 0xdf349bd in SoftBody::_draw_soft_mesh() scene/3d/soft_body.cpp:452
    #5 0x1bd20cf in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #6 0x11da5e5b in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #7 0x1202f4e8 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1175
    #8 0x1e68b3d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1046
    #9 0x1c99fb2 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1184
    #10 0xc526a63 in Node::_notification(int) scene/main/node.cpp:56
    #11 0x1b455b5 in Node::_notificationv(int, bool) scene/main/node.h:45
    #12 0x1b47a2a in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:163
    #13 0xe16938e in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #14 0x11da62f5 in Object::notification(int, bool) core/object.cpp:927
    #15 0xc659cc7 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:973
    #16 0xc64a255 in SceneTree::idle(float) scene/main/scene_tree.cpp:528
    #17 0x198a735 in Main::iteration() main/main.cpp:2185
    #18 0x1861c8a in OS_X11::run() platform/x11/os_x11.cpp:3641
    #19 0x17ccd8b in main platform/x11/godot_x11.cpp:55
    #20 0x7f37324b2564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #21 0x17cc9ad in _start (/usr/bin/godots+0x17cc9ad)

0x6140000199e0 is located 0 bytes to the right of 416-byte region [0x614000019840,0x6140000199e0)
allocated by thread T0 here:
    #0 0x7f373342fc47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x12306983 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x1a6b433 in PoolVector<unsigned char>::resize(int) core/pool_vector.h:563
    #3 0x7e4c0b1 in RasterizerStorageGLES3::mesh_surface_get_array(RID, int) const drivers/gles3/rasterizer_storage_gles3.cpp:3932
    #4 0x10af65f9 in VisualServerRaster::mesh_surface_get_array(RID, int) const servers/visual/visual_server_raster.h:230
    #5 0x10d3c9c4 in VisualServerWrapMT::mesh_surface_get_array(RID, int) const servers/visual/visual_server_wrap_mt.h:168
    #6 0xdf1cfd6 in SoftBodyVisualServerHandler::prepare(RID, int) scene/3d/soft_body.cpp:57
    #7 0xdf339ac in SoftBody::_draw_soft_mesh() scene/3d/soft_body.cpp:441
    #8 0x1bd20cf in MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:59
    #9 0x11da5e5b in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #10 0x1202f4e8 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1175
    #11 0x1e68b3d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1046
    #12 0x1c99fb2 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1184
    #13 0xc526a63 in Node::_notification(int) scene/main/node.cpp:56
    #14 0x1b455b5 in Node::_notificationv(int, bool) scene/main/node.h:45
    #15 0x1b47a2a in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:163
    #16 0xe16938e in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #17 0x11da62f5 in Object::notification(int, bool) core/object.cpp:927
    #18 0xc659cc7 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:973
    #19 0xc64a255 in SceneTree::idle(float) scene/main/scene_tree.cpp:528
    #20 0x198a735 in Main::iteration() main/main.cpp:2185
    #21 0x1861c8a in OS_X11::run() platform/x11/os_x11.cpp:3641
    #22 0x17ccd8b in main platform/x11/godot_x11.cpp:55
    #23 0x7f37324b2564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827 in __interceptor_memcpy

```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

**Comment by timothyqiu** [comment]
Fixed in #53481
