### ISSUE TITLE
Editor sometimes freeze after running project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53556]
### Godot version

4.0.dev.custom_build. ba0a103e2

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When I run test project, then after running, project freeze for a long time in
```
#0  std::__atomic_base<unsigned int>::load (__m=std::memory_order_acquire, this=0x55557c320e18) at /usr/include/c++/10/bits/atomic_base.h:426
#1  SafeNumeric<unsigned int>::conditional_increment (this=0x55557c320e18) at ./core/templates/safe_refcount.h:122
#2  CowData<TextEdit::Text::Gutter>::_ref (this=0x55557a3c64a8, p_from=...) at ./core/templates/cowdata.h:379
#3  0x000055555a09012f in Vector<TextEdit::Text::Gutter>::operator= (this=0x55557a3c64a0, p_from=...) at ./core/templates/vector.h:136
#4  0x000055555a09327d in TextEdit::Text::Line::operator= (this=0x55557a3c64a0) at scene/gui/text_edit.h:138
#5  0x000055555a09343e in CowData<TextEdit::Text::Line>::remove (this=0x555571c88e38, p_index=1) at ./core/templates/cowdata.h:175
#6  0x000055555a090006 in Vector<TextEdit::Text::Line>::remove (this=0x555571c88e30, p_index=1) at ./core/templates/vector.h:71
#7  0x000055555a054fa8 in TextEdit::Text::remove (this=0x555571c88e28, p_at=1) at scene/gui/text_edit.cpp:307
#8  0x000055555a08bb78 in TextEdit::_base_remove_text (this=0x555571c888d0, p_from_line=0, p_from_column=0, p_to_line=11233, p_to_column=0) at scene/gui/text_edit.cpp:6087
#9  0x000055555a089cd7 in TextEdit::_remove_text (this=0x555571c888d0, p_from_line=0, p_from_column=0, p_to_line=11233, p_to_column=0) at scene/gui/text_edit.cpp:5953
#10 0x000055555a067ce6 in TextEdit::set_text (this=0x555571c888d0, p_text=...) at scene/gui/text_edit.cpp:2632
#11 0x0000555559633458 in TextEditor::reload_text (this=0x555571c7aa10) at editor/plugins/text_editor.cpp:140
#12 0x0000555559569e83 in ScriptEditor::_reload_scripts (this=0x5555697b0b00) at editor/plugins/script_editor_plugin.cpp:933
#13 0x000055555956ac65 in ScriptEditor::_test_script_times_on_disk (this=0x5555697b0b00, p_for_script=...) at editor/plugins/script_editor_plugin.cpp:1012
#14 0x00005555595719d4 in ScriptEditor::_notification (this=0x5555697b0b00, p_what=1004) at editor/plugins/script_editor_plugin.cpp:1539
#15 0x000055555959034c in ScriptEditor::_notificationv (this=0x5555697b0b00, p_notification=1004, p_reversed=false) at editor/plugins/script_editor_plugin.h:187
#16 0x000055555b950125 in Object::notification (this=0x5555697b0b00, p_notification=1004, p_reversed=false) at core/object/object.cpp:841
#17 0x0000555559db48f1 in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x5555697b0b00, p_notification=1004) at scene/main/window.cpp:298
#18 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555563d96620, p_notification=1004) at scene/main/window.cpp:305
#19 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555564541800, p_notification=1004) at scene/main/window.cpp:305
#20 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x55556476e690, p_notification=1004) at scene/main/window.cpp:305
#21 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x55556421c3c0, p_notification=1004) at scene/main/window.cpp:305
#22 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555564aca570, p_notification=1004) at scene/main/window.cpp:305
#23 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x5555645e1480, p_notification=1004) at scene/main/window.cpp:305
#24 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555564884730, p_notification=1004) at scene/main/window.cpp:305
#25 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x5555646c82d0, p_notification=1004) at scene/main/window.cpp:305
#26 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x5555634f2360, p_notification=1004) at scene/main/window.cpp:305
#27 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x5555644656e0, p_notification=1004) at scene/main/window.cpp:305
#28 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555564b5d1a0, p_notification=1004) at scene/main/window.cpp:305
#29 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x5555644879e0, p_notification=1004) at scene/main/window.cpp:305
#30 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555562c29fb0, p_notification=1004) at scene/main/window.cpp:305
#31 0x0000555559db495a in Window::_propagate_window_notification (this=0x555562a735b0, p_node=0x555562a735b0, p_notification=1004) at scene/main/window.cpp:305
#32 0x0000555559db52a2 in Window::_event_callback (this=0x555562a735b0, p_event=DisplayServer::WINDOW_EVENT_FOCUS_IN) at scene/main/window.cpp:322
#33 0x0000555559dd6faa in call_with_variant_args_helper<Window, DisplayServer::WindowEvent, 0ul> (p_instance=0x555562a735b0, p_method=
    (void (Window::*)(Window * const, DisplayServer::WindowEvent)) 0x555559db4f32 <Window::_event_callback(DisplayServer::WindowEvent)>, p_args=0x7fffffffd678, r_error=...) at ./core/variant/binder_common.h:222
#34 0x0000555559dd3e78 in call_with_variant_args<Window, DisplayServer::WindowEvent> (p_instance=0x555562a735b0, p_method=
    (void (Window::*)(Window * const, DisplayServer::WindowEvent)) 0x555559db4f32 <Window::_event_callback(DisplayServer::WindowEvent)>, p_args=0x7fffffffd678, p_argcount=1, r_error=...)
    at ./core/variant/binder_common.h:336
#35 0x0000555559dd05b0 in CallableCustomMethodPointer<Window, DisplayServer::WindowEvent>::call (this=0x55556c91e4c0, p_arguments=0x7fffffffd678, p_argcount=1, r_return_value=..., r_call_error=...)
    at ./core/object/callable_method_pointer.h:96
#36 0x000055555b67ce23 in Callable::call (this=0x555560612bd8, p_arguments=0x7fffffffd678, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#37 0x00005555576d65f6 in DisplayServerX11::_send_window_event (this=0x55556027b380, wd=..., p_event=DisplayServer::WINDOW_EVENT_FOCUS_IN) at platform/linuxbsd/display_server_x11.cpp:2639
#38 0x00005555576d7de7 in DisplayServerX11::process_events (this=0x55556027b380) at platform/linuxbsd/display_server_x11.cpp:3006
#39 0x00005555576c1d70 in OS_LinuxBSD::run (this=0x7fffffffda60) at platform/linuxbsd/os_linuxbsd.cpp:338
#40 0x00005555576be12f in main (argc=2, argv=0x7fffffffdf58) at platform/linuxbsd/godot_linuxbsd.cpp:58
```

I think that this is caused by opening `results.txt` file instide editor and later running project which opens and save again data to it.

### Steps to reproduce

1. Run minimal project

### Minimal reproduction project

https://github.com/qarmin/Qarminer/tree/4.0

**Comment by KoBeWi** [comment]
I tried the project and it seems to be doing lots of things at once, so freezes are expected. Not sure what is the issue about.

**Comment by qarmin** [comment]
Cannot reproduce issue anymore
