### ISSUE TITLE
Instancing `VideoPlayer` creates memory leak

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53568]
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

```
func _process(delta) -> void:
	for i in get_children():
		i.queue_free()
	var temp_variable320 = VideoPlayer.new()
	add_child(temp_variable320)
```
creates this memory leak
```
Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f87a28005a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55bb12911e00 in AudioServer::add_mix_callback(void (*)(void*), void*) servers/audio_server.cpp:1533
    #2 0x55bb0f8f5523 in VideoPlayer::_notification(int) scene/gui/video_player.cpp:132
    #3 0x55bb0f90f07b in VideoPlayer::_notificationv(int, bool) scene/gui/video_player.h:40
    #4 0x55bb16ffb33e in Object::notification(int, bool) core/object/object.cpp:841
    #5 0x55bb0e3ee981 in Node::_propagate_enter_tree() scene/main/node.cpp:214
    #6 0x55bb0e43df26 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2449
    #7 0x55bb0e40f90d in Node::_add_child_nocheck(Node*, StringName const&) scene/main/node.cpp:1102
    #8 0x55bb0e4116b6 in Node::add_child(Node*, bool, Node::InternalMode) scene/main/node.cpp:1121
    #9 0x55bb0e4da0fc in void call_with_variant_args_helper<__UnexistingClass, Node*, bool, Node::InternalMode, 0ul, 1ul, 2ul>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>) core/variant/binder_common.h:222
    #10 0x55bb0e4c9759 in void call_with_variant_args_dv<__UnexistingClass, Node*, bool, Node::InternalMode>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:369
    #11 0x55bb0e4b98ac in MethodBindT<Node*, bool, Node::InternalMode>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:286
    #12 0x55bb0687fdde in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1595
    #13 0x55bb06359bcb in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #14 0x55bb0e46cad8 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #15 0x55bb0e3e4648 in Node::_notification(int) scene/main/node.cpp:54
    #16 0x55bb012fa023 in Node::_notificationv(int, bool) scene/main/node.h:48
    #17 0x55bb021abd96 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #18 0x55bb0e128066 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #19 0x55bb16ffb33e in Object::notification(int, bool) core/object/object.cpp:841
    #20 0x55bb0e514b5f in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #21 0x55bb0e5071f8 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #22 0x55bb00a1f143 in Main::iteration() main/main.cpp:2570
    #23 0x55bb008b735c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #24 0x55bb008a59f3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #25 0x7f87a182f564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f87a27fec47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55bb15b34155 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x55bb008a9ae8 in DefaultAllocator::alloc(unsigned long) core/os/memory.h:65
    #3 0x55bb15b34089 in operator new(unsigned long, void* (*)(unsigned long)) core/os/memory.cpp:44
    #4 0x55bb1293da71 in SafeList<AudioServer::CallbackItem*, DefaultAllocator>::insert(AudioServer::CallbackItem*) core/templates/safe_list.h:128
    #5 0x55bb12912009 in AudioServer::add_mix_callback(void (*)(void*), void*) servers/audio_server.cpp:1536
    #6 0x55bb0f8f5523 in VideoPlayer::_notification(int) scene/gui/video_player.cpp:132
    #7 0x55bb0f90f07b in VideoPlayer::_notificationv(int, bool) scene/gui/video_player.h:40
    #8 0x55bb16ffb33e in Object::notification(int, bool) core/object/object.cpp:841
    #9 0x55bb0e3ee981 in Node::_propagate_enter_tree() scene/main/node.cpp:214
    #10 0x55bb0e43df26 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2449
    #11 0x55bb0e40f90d in Node::_add_child_nocheck(Node*, StringName const&) scene/main/node.cpp:1102
    #12 0x55bb0e4116b6 in Node::add_child(Node*, bool, Node::InternalMode) scene/main/node.cpp:1121
    #13 0x55bb0e4da0fc in void call_with_variant_args_helper<__UnexistingClass, Node*, bool, Node::InternalMode, 0ul, 1ul, 2ul>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>) core/variant/binder_common.h:222
    #14 0x55bb0e4c9759 in void call_with_variant_args_dv<__UnexistingClass, Node*, bool, Node::InternalMode>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:369
    #15 0x55bb0e4b98ac in MethodBindT<Node*, bool, Node::InternalMode>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:286
    #16 0x55bb0687fdde in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1595
    #17 0x55bb06359bcb in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #18 0x55bb0e46cad8 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #19 0x55bb0e3e4648 in Node::_notification(int) scene/main/node.cpp:54
    #20 0x55bb012fa023 in Node::_notificationv(int, bool) scene/main/node.h:48
    #21 0x55bb021abd96 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #22 0x55bb0e128066 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #23 0x55bb16ffb33e in Object::notification(int, bool) core/object/object.cpp:841
    #24 0x55bb0e514b5f in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #25 0x55bb0e5071f8 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #26 0x55bb00a1f143 in Main::iteration() main/main.cpp:2570
    #27 0x55bb008b735c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #28 0x55bb008a59f3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #29 0x7f87a182f564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
```

### Steps to reproduce

Above

**Comment by akien-mga** [comment]
Fixed by #53573.
