### ISSUE TITLE
Executing `AcceptDialog.set_input_as_handled` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53560]
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var temp_variable1 = AcceptDialog.new()
	add_child(temp_variable1)
	temp_variable1.set_handle_input_locally(false)
	temp_variable1.set_input_as_handled()
```

Godot crashes with infinite recursion
```
#174254 0x0000555559d78a6b in Viewport::set_input_as_handled (this=0x555560980fb0) at scene/main/viewport.cpp:2895
#174255 0x0000555559d78a6b in Viewport::set_input_as_handled (this=0x555560980fb0) at scene/main/viewport.cpp:2895
#174256 0x0000555559d78a6b in Viewport::set_input_as_handled (this=0x555560980fb0) at scene/main/viewport.cpp:2895
#174257 0x0000555559d78a6b in Viewport::set_input_as_handled (this=0x555560980fb0) at scene/main/viewport.cpp:2895
#174258 0x00005555579bd0b7 in call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0x555560980fb0, p_method=(void (__UnexistingClass::*)(__UnexistingClass * const)) 0x555559d7898a <Viewport::set_input_as_handled()>, p_args=0x7fffffff9310, r_error=...) at ./core/variant/binder_common.h:222
#174259 0x00005555579bc413 in call_with_variant_args_dv<__UnexistingClass> (p_instance=0x555560980fb0, p_method=(void (__UnexistingClass::*)(__UnexistingClass * const)) 0x555559d7898a <Viewport::set_input_as_handled()>, p_args=0x0, p_argcount=0, r_error=..., default_values=...) at ./core/variant/binder_common.h:369
#174260 0x00005555579b9c24 in MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) (this=0x555562082000, p_object=0x555560980fb0, p_args=0x0, p_arg_count=0, r_error=...) at ./core/object/method_bind.h:286
#174261 0x000055555b950018 in Object::call (this=0x555560980fb0, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at core/object/object.cpp:832
#174262 0x000055555b94f9b3 in Object::callv (this=0x555560980fb0, p_method=..., p_args=...) at core/object/object.cpp:753
#174263 0x000055555b96695e in call_with_variant_args_ret_helper<__UnexistingClass, Variant, StringName const&, Array const&, 0ul, 1ul> (p_instance=0x555560980fb0, p_method=(Variant (__UnexistingClass::*)(__UnexistingClass * const, const StringName &, const Array &)) 0x55555b94f818 <Object::callv(StringName const&, Array const&)>, p_args=0x7fffffff95b0, r_ret=..., r_error=...) at ./core/variant/binder_common.h:648
#174264 0x000055555b965335 in call_with_variant_args_ret_dv<__UnexistingClass, Variant, StringName const&, Array const&> (p_instance=0x555560980fb0, p_method=(Variant (__UnexistingClass::*)(__UnexistingClass * const, const StringName &, const Array &)) 0x55555b94f818 <Object::callv(StringName const&, Array const&)>, p_args=0x7fffffff9a98, p_argcount=2, r_ret=..., r_error=..., default_values=...) at ./core/variant/binder_common.h:453
#174265 0x000055555b963d6a in MethodBindTR<Variant, StringName const&, Array const&>::call (this=0x55556005b590, p_object=0x555560980fb0, p_args=0x7fffffff9a98, p_arg_count=2, r_error=...) at ./core/object/method_bind.h:455
#174266 0x00005555585eb704 in GDScriptFunction::call (this=0x555562c43ea0, p_instance=0x555562c9ab20, p_args=0x7fffffffb920, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1595
#174267 0x00005555584f0f41 in GDScriptInstance::call (this=0x555562c9ab20, p_method=..., p_args=0x7fffffffb920, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:1501
#174268 0x000055555b94ff3b in Object::call (this=0x555562e09770, p_method=..., p_args=0x7fffffffb920, p_argcount=0, r_error=...) at core/object/object.cpp:811
#174269 0x000055555b6a132a in Variant::call (this=0x7fffffffb860, p_method=..., p_args=0x7fffffffb920, p_argcount=0, r_ret=..., r_error=...) at core/variant/variant_call.cpp:1017
#174270 0x00005555585ead28 in GDScriptFunction::call (this=0x555562ca5000, p_instance=0x555562c9ab20, p_args=0x7fffffffd558, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1487
#174271 0x00005555584f0f41 in GDScriptInstance::call (this=0x555562c9ab20, p_method=..., p_args=0x7fffffffd558, p_argcount=1, r_error=...) at modules/gdscript/gdscript.cpp:1501
#174272 0x0000555559d24c2d in Node::_gdvirtual__process_call (this=0x555562e09770, arg1=0.14827860308837892) at scene/main/node.h:232
#174273 0x0000555559d0a07f in Node::_notification (this=0x555562e09770, p_notification=17) at scene/main/node.cpp:54
#174274 0x000055555795204c in Node::_notificationv (this=0x555562e09770, p_notification=17, p_reversed=false) at ./scene/main/node.h:48
#174275 0x000055555b950125 in Object::notification (this=0x555562e09770, p_notification=17, p_reversed=false) at core/object/object.cpp:841
#174276 0x0000555559d460ed in SceneTree::_notify_group_pause (this=0x555562260bb0, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:851
#174277 0x0000555559d44120 in SceneTree::process (this=0x555562260bb0, p_time=0.14827860308837892) at scene/main/scene_tree.cpp:453
#174278 0x0000555557705436 in Main::iteration () at main/main.cpp:2570
#174279 0x00005555576c1d88 in OS_LinuxBSD::run (this=0x7fffffffda70) at platform/linuxbsd/os_linuxbsd.cpp:342
#174280 0x00005555576be12f in main (argc=1, argv=0x7fffffffdf68) at platform/linuxbsd/godot_linuxbsd.cpp:58

```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

**Comment by Sauermann** [comment]
duplicate of  #53600
