### ISSUE TITLE
Instancing `AudioStreamPlayer3D` creates memory leak

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53567]
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

```
func _process(delta) -> void:
	for i in get_children():
		i.queue_free()
	var temp_variable320 = AudioStreamPlayer3D.new()
	add_child(temp_variable320)
```
creates this memory leak
```
Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fab380a45a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x563e43b015a0 in AudioServer::add_listener_changed_callback(void (*)(void*), void*) servers/audio_server.cpp:1548
    #2 0x563e40b94361 in AudioStreamPlayer3D::_notification(int) scene/3d/audio_stream_player_3d.cpp:244
    #3 0x563e40bbf759 in AudioStreamPlayer3D::_notificationv(int, bool) scene/3d/audio_stream_player_3d.h:44
    #4 0x563e481ea33e in Object::notification(int, bool) core/object/object.cpp:841
    #5 0x563e3f5dd981 in Node::_propagate_enter_tree() scene/main/node.cpp:214
    #6 0x563e3f62cf26 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2449
    #7 0x563e3f5fe90d in Node::_add_child_nocheck(Node*, StringName const&) scene/main/node.cpp:1102
    #8 0x563e3f6006b6 in Node::add_child(Node*, bool, Node::InternalMode) scene/main/node.cpp:1121
    #9 0x563e3f6c90fc in void call_with_variant_args_helper<__UnexistingClass, Node*, bool, Node::InternalMode, 0ul, 1ul, 2ul>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>) core/variant/binder_common.h:222
    #10 0x563e3f6b8759 in void call_with_variant_args_dv<__UnexistingClass, Node*, bool, Node::InternalMode>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:369
    #11 0x563e3f6a88ac in MethodBindT<Node*, bool, Node::InternalMode>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:286
    #12 0x563e37a6edde in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1595
    #13 0x563e37548bcb in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #14 0x563e3f65bad8 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #15 0x563e3f5d3648 in Node::_notification(int) scene/main/node.cpp:54
    #16 0x563e324e9023 in Node::_notificationv(int, bool) scene/main/node.h:48
    #17 0x563e3339ad96 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #18 0x563e3f317066 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #19 0x563e481ea33e in Object::notification(int, bool) core/object/object.cpp:841
    #20 0x563e3f703b5f in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #21 0x563e3f6f61f8 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #22 0x563e31c0e143 in Main::iteration() main/main.cpp:2570
    #23 0x563e31aa635c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #24 0x563e31a949f3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #25 0x7fab370d3564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fab380a2c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x563e46d23155 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x563e31a98ae8 in DefaultAllocator::alloc(unsigned long) core/os/memory.h:65
    #3 0x563e46d23089 in operator new(unsigned long, void* (*)(unsigned long)) core/os/memory.cpp:44
    #4 0x563e43b2ca71 in SafeList<AudioServer::CallbackItem*, DefaultAllocator>::insert(AudioServer::CallbackItem*) core/templates/safe_list.h:128
    #5 0x563e43b017a9 in AudioServer::add_listener_changed_callback(void (*)(void*), void*) servers/audio_server.cpp:1551
    #6 0x563e40b94361 in AudioStreamPlayer3D::_notification(int) scene/3d/audio_stream_player_3d.cpp:244
    #7 0x563e40bbf759 in AudioStreamPlayer3D::_notificationv(int, bool) scene/3d/audio_stream_player_3d.h:44
    #8 0x563e481ea33e in Object::notification(int, bool) core/object/object.cpp:841
    #9 0x563e3f5dd981 in Node::_propagate_enter_tree() scene/main/node.cpp:214
    #10 0x563e3f62cf26 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2449
    #11 0x563e3f5fe90d in Node::_add_child_nocheck(Node*, StringName const&) scene/main/node.cpp:1102
    #12 0x563e3f6006b6 in Node::add_child(Node*, bool, Node::InternalMode) scene/main/node.cpp:1121
    #13 0x563e3f6c90fc in void call_with_variant_args_helper<__UnexistingClass, Node*, bool, Node::InternalMode, 0ul, 1ul, 2ul>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>) core/variant/binder_common.h:222
    #14 0x563e3f6b8759 in void call_with_variant_args_dv<__UnexistingClass, Node*, bool, Node::InternalMode>(__UnexistingClass*, void (__UnexistingClass::*)(Node*, bool, Node::InternalMode), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:369
    #15 0x563e3f6a88ac in MethodBindT<Node*, bool, Node::InternalMode>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:286
    #16 0x563e37a6edde in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1595
    #17 0x563e37548bcb in GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1501
    #18 0x563e3f65bad8 in Node::_gdvirtual__process_call(double) scene/main/node.h:232
    #19 0x563e3f5d3648 in Node::_notification(int) scene/main/node.cpp:54
    #20 0x563e324e9023 in Node::_notificationv(int, bool) scene/main/node.h:48
    #21 0x563e3339ad96 in CanvasItem::_notificationv(int, bool) scene/main/canvas_item.h:47
    #22 0x563e3f317066 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #23 0x563e481ea33e in Object::notification(int, bool) core/object/object.cpp:841
    #24 0x563e3f703b5f in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:851
    #25 0x563e3f6f61f8 in SceneTree::process(double) scene/main/scene_tree.cpp:453
    #26 0x563e31c0e143 in Main::iteration() main/main.cpp:2570
    #27 0x563e31aa635c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:342
    #28 0x563e31a949f3 in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #29 0x7fab370d3564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

```

### Steps to reproduce

Above

**Comment by akien-mga** [comment]
Fixed by #53573.
