### ISSUE TITLE
Executing `TextServerExtension.shaped_text_draw_outline` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53562]
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var temp_variable410 = TextServerExtension.new()
	temp_variable410.shaped_text_draw_outline(RID(), RID(), Vector2(-44.0985527038574, -48.3818702697754), 34.218168258667, 3.17324995994568, 0, Color(8.25155353546143, 13.8878583908081, -8.92721366882324, 1))
```

Godot crashes with backtrace(infinite recursion)
```
#25910 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25911 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25912 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25913 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25914 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25915 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25916 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25917 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25918 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25919 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25920 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25921 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25922 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25923 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25924 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25925 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25926 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25927 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25928 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25929 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232
#25930 0x000055555b0d2a28 in TextServerExtension::shaped_text_draw_outline (this=0x555562d8a900, p_shaped=..., p_canvas=..., p_pos=..., p_clip_l=34.2181702, p_clip_r=3.17324996, p_outline_size=0, p_color=...) at servers/text/text_server_extension.cpp:1232

```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Fixed in master branch
