### ISSUE TITLE
Executing `ImmediateGeometry.set_extra_cull_margin` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53623]
### Godot version

3.4.beta.custom_build. 512211b61

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
func _process(delta) -> void:

	for i in get_children():
		i.queue_free()
	var temp_variable8521 = ImmediateGeometry.new()
	add_child(temp_variable8521)
	temp_variable8521.set_extra_cull_margin(16.134185)
	var temp_variable8534 = InterpolatedCamera.new()
	add_child(temp_variable8534)
```

Godot crashes with this backtrace
```
drivers/gles3/rasterizer_scene_gles3.cpp:2117:34: runtime error: downcast of address 0x60c000203150 which does not point to an object of type 'Surface'
0x60c000203150: note: object is of type 'RasterizerStorageGLES3::Immediate'
 be be be be  a8 ae 6d 1c 00 00 00 00  9a 00 00 00 be be be be  c8 21 0a 00 50 61 00 00  c8 21 0a 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'RasterizerStorageGLES3::Immediate'
drivers/gles3/rasterizer_scene_gles3.cpp:2117:83: runtime error: member access within address 0x60c000203150 which does not point to an object of type 'Surface'
0x60c000203150: note: object is of type 'RasterizerStorageGLES3::Immediate'
 be be be be  a8 ae 6d 1c 00 00 00 00  9a 00 00 00 be be be be  c8 21 0a 00 50 61 00 00  c8 21 0a 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'RasterizerStorageGLES3::Immediate'
=================================================================
==19302==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c000203290 at pc 0x000007c8e64b bp 0x7ffe18709160 sp 0x7ffe18709150
READ of size 4 at 0x60c000203290 thread T0
    #0 0x7c8e64a in RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, RasterizerStorageGLES3::Sky*, bool, bool, bool, bool, bool) drivers/gles3/rasterizer_scene_gles3.cpp:2117
    #1 0x7d11f76 in RasterizerSceneGLES3::render_scene(Transform const&, CameraMatrix const&, int, bool, RasterizerScene::InstanceBase**, int, RID*, int, RID*, int, RID, RID, RID, RID, int) drivers/gles3/rasterizer_scene_gles3.cpp:4116
    #2 0x10bbdb0b in VisualServerScene::_render_scene(Transform, CameraMatrix const&, int, bool, RID, RID, RID, RID, int) servers/visual/visual_server_scene.cpp:2803
    #3 0x10baa995 in VisualServerScene::render_camera(RID, RID, Vector2, RID) servers/visual/visual_server_scene.cpp:2382
    #4 0x10cfd8b6 in VisualServerViewport::_draw_3d(VisualServerViewport::Viewport*, ARVRInterface::Eyes) servers/visual/visual_server_viewport.cpp:76
    #5 0x10cffb11 in VisualServerViewport::_draw_viewport(VisualServerViewport::Viewport*, ARVRInterface::Eyes) servers/visual/visual_server_viewport.cpp:106
    #6 0x10d0bd63 in VisualServerViewport::draw_viewports() servers/visual/visual_server_viewport.cpp:340
    #7 0x10b1b65b in VisualServerRaster::draw(bool, double) servers/visual/visual_server_raster.cpp:107
    #8 0x10d3e41a in VisualServerWrapMT::draw(bool, double) servers/visual/visual_server_wrap_mt.cpp:90
    #9 0x198f4f2 in Main::iteration() main/main.cpp:2201
    #10 0x1865caa in OS_X11::run() platform/x11/os_x11.cpp:3641
    #11 0x17d0dab in main platform/x11/godot_x11.cpp:55
    #12 0x7f18fc099564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #13 0x17d09cd in _start (/usr/bin/godots+0x17d09cd)

0x60c000203290 is located 16 bytes to the right of 128-byte region [0x60c000203200,0x60c000203280)
allocated by thread T0 here:
    #0 0x7f18fd016c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x123411b5 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x123410c6 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x10b6527f in VisualServerScene::camera_create() servers/visual/visual_server_scene.cpp:42
    #4 0x10b44af6 in VisualServerRaster::camera_create() servers/visual/visual_server_raster.h:436
    #5 0x10dd979b in VisualServerWrapMT::camera_create() servers/visual/visual_server_wrap_mt.h:367
    #6 0xd803015 in Camera::Camera() scene/3d/camera.cpp:648
    #7 0xda015a8 in InterpolatedCamera::InterpolatedCamera() scene/3d/interpolated_camera.cpp:140
    #8 0xc4b4550 in Object* ClassDB::creator<InterpolatedCamera>() core/class_db.h:140
    #9 0x11b5f326 in ClassDB::instance(StringName const&) core/class_db.cpp:520
    #10 0x1c7866e in GDScriptNativeClass::instance() modules/gdscript/gdscript.cpp:77
    #11 0x1c78056 in GDScriptNativeClass::_new() modules/gdscript/gdscript.cpp:65
    #12 0x1d5309f in MethodBind0R<Variant>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:237
    #13 0x11ddeb87 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #14 0x120691d4 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1175
    #15 0x1e6c698 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1044
    #16 0x1c9dad4 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1184
    #17 0xc54d7e7 in Node::_notification(int) scene/main/node.cpp:56
    #18 0x1b490d3 in Node::_notificationv(int, bool) scene/main/node.h:45
    #19 0x1b4b548 in CanvasItem::_notificationv(int, bool) scene/2d/canvas_item.h:163
    #20 0xc3c5040 in Node2D::_notificationv(int, bool) scene/2d/node_2d.h:37
    #21 0x11ddf021 in Object::notification(int, bool) core/object.cpp:927
    #22 0xc680b51 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:977
    #23 0xc670fd9 in SceneTree::idle(float) scene/main/scene_tree.cpp:528
    #24 0x198e755 in Main::iteration() main/main.cpp:2186
    #25 0x1865caa in OS_X11::run() platform/x11/os_x11.cpp:3641
    #26 0x17d0dab in main platform/x11/godot_x11.cpp:55
    #27 0x7f18fc099564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

SUMMARY: AddressSanitizer: heap-buffer-overflow drivers/gles3/rasterizer_scene_gles3.cpp:2117 in RasterizerSceneGLES3::_render_list(RasterizerSceneGLES3::RenderList::Element**, int, Transform const&, CameraMatrix const&, RasterizerStorageGLES3::Sky*, bool, bool, bool, bool, bool)


```

This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Fixed in 3.x branch
