### ISSUE TITLE
Freeze when opening `SkeletonModificationStack3D.set_modification_count`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#54234]
### Godot version

4.0.dev.custom_build. b2ab5cb50

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
	var temp_variable85 = SkeletonModificationStack3D.new()
	temp_variable85.set_modification_count(-35)
```
GDB
```
#0  LocalVector<Ref<SkeletonModification3D>, unsigned int, false>::resize (this=0x5555624c8ec8, p_size=4294967261) at ./core/templates/local_vector.h:144
#1  0x000055555a8de2d5 in SkeletonModificationStack3D::set_modification_count (this=0x5555624c8d40, p_count=-35) at scene/resources/skeleton_modification_stack_3d.cpp:151
#2  0x00005555579b0916 in call_with_variant_args_helper<__UnexistingClass, int, 0ul> (p_instance=0x5555624c8d40, p_method=
    (void (__UnexistingClass::*)(__UnexistingClass * const, int)) 0x55555a8de2aa <SkeletonModificationStack3D::set_modification_count(int)>, p_args=0x7fffffffb610, r_error=...)
    at ./core/variant/binder_common.h:222
#3  0x00005555579afbdf in call_with_variant_args_dv<__UnexistingClass, int> (p_instance=0x5555624c8d40, p_method=
    (void (__UnexistingClass::*)(__UnexistingClass * const, int)) 0x55555a8de2aa <SkeletonModificationStack3D::set_modification_count(int)>, p_args=0x7fffffffb8d0, p_argcount=1, r_error=..., default_values=...)
    at ./core/variant/binder_common.h:369
#4  0x00005555579ad380 in MethodBindT<int>::call (this=0x555561d7f430, p_object=0x5555624c8d40, p_args=0x7fffffffb8d0, p_arg_count=1, r_error=...) at ./core/object/method_bind.h:280
#5  0x000055555ba02ec0 in Object::call (this=0x5555624c8d40, p_method=..., p_args=0x7fffffffb8d0, p_argcount=1, r_error=...) at core/object/object.cpp:832
#6  0x000055555b749606 in Variant::call (this=0x7fffffffb888, p_method=..., p_args=0x7fffffffb8d0, p_argcount=1, r_ret=..., r_error=...) at core/variant/variant_call.cpp:1017
#7  0x000055555856fe26 in GDScriptFunction::call (this=0x555562561b20, p_instance=0x5555624e84f0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1506
#8  0x0000555558472ab6 in GDScriptInstance::call (this=0x5555624e84f0, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:1501
#9  0x0000555559d47f36 in Node::_gdvirtual__ready_call (this=0x55556254a620) at scene/main/node.h:236
#10 0x0000555559d2c969 in Node::_notification (this=0x55556254a620, p_notification=13) at scene/main/node.cpp:143
#11 0x0000555557949c10 in Node::_notificationv (this=0x55556254a620, p_notification=13, p_reversed=false) at ./scene/main/node.h:48
#12 0x0000555557c075cd in CanvasItem::_notificationv (this=0x55556254a620, p_notification=13, p_reversed=false) at ./scene/main/canvas_item.h:47
#13 0x0000555559c71ed1 in Node2D::_notificationv (this=0x55556254a620, p_notification=13, p_reversed=false) at scene/2d/node_2d.h:37
#14 0x000055555ba02fcd in Object::notification (this=0x55556254a620, p_notification=13, p_reversed=false) at core/object/object.cpp:841
#15 0x0000555559d2ce60 in Node::_propagate_ready (this=0x55556254a620) at scene/main/node.cpp:188
#16 0x0000555559d2cdc4 in Node::_propagate_ready (this=0x5555622ff4c0) at scene/main/node.cpp:180
#17 0x0000555559d3ae48 in Node::_set_tree (this=0x5555622ff4c0, p_tree=0x5555617d5eb0) at scene/main/node.cpp:2453
#18 0x0000555559d65f43 in SceneTree::initialize (this=0x5555617d5eb0) at scene/main/scene_tree.cpp:402
#19 0x00005555576b5d83 in OS_LinuxBSD::run (this=0x7fffffffd990) at platform/linuxbsd/os_linuxbsd.cpp:330
#20 0x00005555576b1fe1 in main (argc=2, argv=0x7fffffffdeb8) at platform/linuxbsd/godot_linuxbsd.cpp:58
```

### Steps to reproduce

Above

**Comment by TokageItLab** [comment]
Closed by #63588.
