### ISSUE TITLE
[Bullet] Large ConcavePolygonShape causes crashes upon collision

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#56094]
### Godot version

3.4.1.stable

### System information

Windows 10

### Issue description

I'm writing a Minecraft map importer for Godot and although most things seem to work well, there's a weird issue I'm having with collision. Basically, it seems whenever anything touches the Minecraft world's StaticBody, there's a high chance of a crash occurring. It seems some triangles consistently cause crashes, but others don't.

The StaticBody contains a optimized ConcavePolygonShape, representing a 512x512x512 chunk of the Minecraft world, which contains about 6-7 million triangles. That sounds like a lot, and it is, but I think Godot should be able to handle it, since the game easily hits 144 FPS on my modest gaming PC (CPU is 4th gen Intel i5, GPU is GTX 1060) up to the point it crashes.

Additionally, I've noticed it only seems to happen with the Bullet physics engine, not GodotPhysics. I've done a little bit of debugging myself and the crash seems to be originating from the `processAllTriangles()` function in Bullet's internal code.

(Also, just noticed a second bug, which may need a second bug report? Basically enabling "Smooth Trimesh Collision" in the options makes the project unable to be opened at all. It instantly crashes Godot when you try to open the project)

### Steps to reproduce

1. Download and extract both reproduction zip files into the same folder.
2. Open the sample project and run it. (NOTE: due to the high amount of triangles, this may take a while to load)
3. Press W to walk forward until you hit the river bank
4. Notice how it instantly crashes
![crash](https://user-images.githubusercontent.com/31383123/146760755-db41efb6-0111-4f16-919c-85b171512bae.gif)

(note: in the included project, the colors are missing due to Github's size limitations, but the collision mesh is identical)

### Minimal reproduction project

Note: the reproduction project is split into two parts, you need to extract both zip files into the same folder due to size limitations.

Part 1: [bugreport_trimesh1.zip](https://github.com/godotengine/godot/files/7745049/bugreport_trimesh1.zip)
Part 2: [bugreport_trimesh2.zip](https://github.com/godotengine/godot/files/7745051/bugreport_trimesh2.zip)

**Comment by qarmin** [comment]
Address sanitizer log
```
=================================================================
==15730==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60700005b0e4 at pc 0x00000653fa23 bp 0x7ffecd71abd0 sp 0x7ffecd71abc0
READ of size 4 at 0x60700005b0e4 thread T0
    #0 0x653fa22 in btTriangleIndexVertexArray::getLockedReadOnlyVertexIndexBase(unsigned char const**, int&, PHY_ScalarType&, int&, unsigned char const**, int&, int&, PHY_ScalarType&, int) const thirdparty/bullet/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp:61
    #1 0x3f196b6 in processNode thirdparty/bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp:274
    #2 0x647ad0a in btQuantizedBvh::walkStacklessQuantizedTree(btNodeOverlapCallback*, unsigned short*, unsigned short*, int, int) const thirdparty/bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:697
    #3 0x6475b0a in btQuantizedBvh::reportAabbOverlappingNodex(btNodeOverlapCallback*, btVector3 const&, btVector3 const&) const thirdparty/bullet/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp:327
    #4 0x3f1bfe1 in btBvhTriangleMeshShape::processAllTriangles(btTriangleCallback*, btVector3 const&, btVector3 const&) const thirdparty/bullet/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp:326
    #5 0x3fd07ba in btScaledBvhTriangleMeshShape::processAllTriangles(btTriangleCallback*, btVector3 const&, btVector3 const&) const thirdparty/bullet/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp:69
    #6 0x3e78c2e in btCollisionWorld::objectQuerySingleInternal(btConvexShape const*, btTransform const&, btTransform const&, btCollisionObjectWrapper const*, btCollisionWorld::ConvexResultCallback&, float) thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:804
    #7 0x3e6e0ec in btCollisionWorld::objectQuerySingle(btConvexShape const*, btTransform const&, btTransform const&, btCollisionObject*, btCollisionShape const*, btTransform const&, btCollisionWorld::ConvexResultCallback&, float) thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:609
    #8 0x3ea3c82 in btSingleSweepCallback::process(btBroadphaseProxy const*) thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:1064
    #9 0x3e2e167 in BroadphaseRayTester::Process(btDbvtNode const*) thirdparty/bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp:236
    #10 0x3e2b36f in btDbvt::rayTestInternal(btDbvtNode const*, btVector3 const&, btVector3 const&, btVector3 const&, unsigned int*, float, btVector3 const&, btVector3 const&, btAlignedObjectArray<btDbvtNode const*>&, btDbvt::ICollide&) const thirdparty/bullet/BulletCollision/BroadphaseCollision/btDbvt.h:1267
    #11 0x3e14b67 in btDbvtBroadphase::rayTest(btVector3 const&, btVector3 const&, btBroadphaseRayCallback&, btVector3 const&, btVector3 const&) thirdparty/bullet/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp:263
    #12 0x3e7c95b in btCollisionWorld::convexSweepTest(btConvexShape const*, btTransform const&, btTransform const&, btCollisionWorld::ConvexResultCallback&, float) const thirdparty/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:1103
    #13 0x303dd79 in SpaceBullet::test_body_motion(RigidBodyBullet*, Transform const&, Vector3 const&, bool, PhysicsServer::MotionResult*, bool, Set<RID, Comparator<RID>, DefaultAllocator> const&) modules/bullet/space_bullet.cpp:988
    #14 0x2ec9a11 in BulletPhysicsServer::body_test_motion(RID, Transform const&, Vector3 const&, bool, PhysicsServer::MotionResult*, bool, Set<RID, Comparator<RID>, DefaultAllocator> const&) modules/bullet/bullet_physics_server.cpp:873
    #15 0xdf708cf in KinematicBody::move_and_collide(Vector3 const&, bool, KinematicBody::Collision&, bool, bool, bool, Set<RID, Comparator<RID>, DefaultAllocator> const&) scene/3d/physics_body.cpp:984
    #16 0xdf75c80 in KinematicBody::_move_and_slide_internal(Vector3 const&, Vector3 const&, Vector3 const&, bool, int, float, bool) scene/3d/physics_body.cpp:1114
    #17 0xdf7951c in KinematicBody::move_and_slide(Vector3 const&, Vector3 const&, bool, int, float, bool) scene/3d/physics_body.cpp:1210
    #18 0xe05d3de in MethodBind6R<Vector3, Vector3 const&, Vector3 const&, bool, int, float, bool>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind_ext.gen.inc:309
    #19 0x121bc5aa in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #20 0x1244e226 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1182
    #21 0x1e8674e in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1044
    #22 0x1cb4e53 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1194
    #23 0xc8550ba in Node::_notification(int) scene/main/node.cpp:63
    #24 0x1b5c547 in Node::_notificationv(int, bool) scene/main/node.h:45
    #25 0x1b86bef in Spatial::_notificationv(int, bool) scene/3d/spatial.h:52
    #26 0xd98e689 in CollisionObject::_notificationv(int, bool) scene/3d/collision_object.h:38
    #27 0xdff5483 in PhysicsBody::_notificationv(int, bool) scene/3d/physics_body.h:41
    #28 0xdffe2f7 in KinematicBody::_notificationv(int, bool) scene/3d/physics_body.h:262
    #29 0x121bca46 in Object::notification(int, bool) core/object.cpp:927
    #30 0xc98c57d in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:990
    #31 0xc979e21 in SceneTree::iteration(float) scene/main/scene_tree.cpp:492
    #32 0x199c5c6 in Main::iteration() main/main.cpp:2212
    #33 0x186de7b in OS_X11::run() platform/x11/os_x11.cpp:3705
    #34 0x17d70ae in main platform/x11/godot_x11.cpp:55
    #35 0x7f87e1946fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #36 0x7f87e194707c in __libc_start_main_impl ../csu/libc-start.c:409
    #37 0x17d6ccd in _start (/usr/bin/godots+0x17d6ccd)

0x60700005b0e4 is located 13 bytes to the right of 71-byte region [0x60700005b090,0x60700005b0d7)
allocated by thread T0 here:
    #0 0x7f87e28c9808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x2eabe6c in btAllocDefault thirdparty/bullet/LinearMath/btAlignedAllocator.cpp:26
    #2 0x2eabee4 in btAlignedAllocDefault thirdparty/bullet/LinearMath/btAlignedAllocator.cpp:66
    #3 0x2eac119 in btAlignedAllocInternal(unsigned long, int) thirdparty/bullet/LinearMath/btAlignedAllocator.cpp:247
    #4 0x3ff6b16 in btAlignedAllocator<btIndexedMesh, 16u>::allocate(int, btIndexedMesh const**) thirdparty/bullet/LinearMath/btAlignedAllocator.h:92
    #5 0x3ff66cc in btAlignedObjectArray<btIndexedMesh>::allocate(int) thirdparty/bullet/LinearMath/btAlignedObjectArray.h:103
    #6 0x3ff4bf5 in btAlignedObjectArray<btIndexedMesh>::reserve(int) thirdparty/bullet/LinearMath/btAlignedObjectArray.h:284
    #7 0x3ff2b62 in btAlignedObjectArray<btIndexedMesh>::push_back(btIndexedMesh const&) thirdparty/bullet/LinearMath/btAlignedObjectArray.h:262
    #8 0x3fed225 in btTriangleMesh::btTriangleMesh(bool, bool) thirdparty/bullet/BulletCollision/CollisionShapes/btTriangleMesh.cpp:31
    #9 0x2fb674e in ConcavePolygonShapeBullet::setup(PoolVector<Vector3>) modules/bullet/shape_bullet.cpp:404
    #10 0x2fb5531 in ConcavePolygonShapeBullet::set_data(Variant const&) modules/bullet/shape_bullet.cpp:380
    #11 0x2eaec69 in BulletPhysicsServer::shape_set_data(RID, Variant const&) modules/bullet/bullet_physics_server.cpp:131
    #12 0xf2c9535 in ConcavePolygonShape::set_faces(PoolVector<Vector3> const&) scene/resources/concave_polygon_shape.cpp:68
    #13 0xdcc25e5 in MethodBind1<PoolVector<Vector3> const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:775
    #14 0x11f42486 in ClassDB::set_property(Object*, StringName const&, Variant const&, bool*) core/class_db.cpp:1007
    #15 0x121acc92 in Object::set(StringName const&, Variant const&, bool*) core/object.cpp:422
    #16 0x12ca2eaa in ResourceInteractiveLoaderBinary::poll() core/io/resource_format_binary.cpp:699
    #17 0x12d130a1 in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:193
    #18 0x12d18e3a in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:262
    #19 0x12d1afe2 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:376
    #20 0x12c9edc4 in ResourceInteractiveLoaderBinary::poll() core/io/resource_format_binary.cpp:605
    #21 0x12d130a1 in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:193
    #22 0x12d18e3a in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:262
    #23 0x12d1afe2 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:376
    #24 0xf9e422e in ResourceInteractiveLoaderText::poll() scene/resources/resource_format_text.cpp:406
    #25 0x12d130a1 in ResourceFormatLoader::load(String const&, String const&, Error*) core/io/resource_loader.cpp:193
    #26 0x12d18e3a in ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) core/io/resource_loader.cpp:262
    #27 0x12d1afe2 in ResourceLoader::load(String const&, String const&, bool, Error*) core/io/resource_loader.cpp:376
    #28 0x199582c in Main::start() main/main.cpp:2044
    #29 0x17d6fde in main platform/x11/godot_x11.cpp:54

```
