### ISSUE TITLE
Crash when attempting to import `.ogg` OGG Theora video as OGG Vorbis

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#56904]
### Godot version

4.0.dev (fd5fb7d64)

### System information

Linux, Mageia 9 x86_64

### Issue description

Godot matches files to resource loaders based on their extension, and `.ogg` files are matched with the OGG Vorbis loader.
But `.ogg` is also a valid extension for OGG Theora video files (next to `.ogv` which we support) and therefore users can attempting importing `.ogg` video files in Godot, which goes through `ResourceImporterOGGVorbis` (see #56895).

The current error reporting in such situation is subpar, and in `master` it's actually even crashing:

```
WARNING: Found a non-vorbis-header packet in a header position
     at: import (modules/vorbis/resource_importer_ogg_vorbis.cpp:163)
free(): invalid pointer

Thread 1 "godot-git" received signal SIGABRT, Aborted.
0x00007ffff7aebc0c in __pthread_kill_implementation () from /lib64/libc.so.6

(gdb) bt
#0  0x00007ffff7aebc0c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff7aa2102 in raise () from /lib64/libc.so.6
#2  0x00007ffff7a8e43b in abort () from /lib64/libc.so.6
#3  0x00007ffff7ae0700 in __libc_message () from /lib64/libc.so.6
#4  0x00007ffff7af4dfa in malloc_printerr () from /lib64/libc.so.6
#5  0x00007ffff7af6464 in _int_free () from /lib64/libc.so.6
#6  0x00007ffff7af8b91 in free () from /lib64/libc.so.6
#7  0x0000000002cc10a9 in ogg_stream_destroy (os=0x7fffffffb430) at thirdparty/libogg/framing.c:176
#8  0x00000000027ba516 in ResourceImporterOGGVorbis::import (this=0xcc43150, p_source_file=..., p_save_path=..., p_options=..., r_platform_variants=0x7fffffffb8a8, r_gen_files=0x7fffffffb8a0, 
    r_metadata=0x7fffffffb880) at modules/vorbis/resource_importer_ogg_vorbis.cpp:165
#9  0x00000000038a0882 in EditorFileSystem::_reimport_file (this=0xdbc7f20, p_file=..., p_custom_options=0x0, p_custom_importer=...) at editor/editor_file_system.cpp:1882
#10 0x00000000038a3b35 in EditorFileSystem::reimport_files (this=0xdbc7f20, p_files=...) at editor/editor_file_system.cpp:2099
#11 0x00000000038942fc in EditorFileSystem::_update_scan_actions (this=0xdbc7f20) at editor/editor_file_system.cpp:626
#12 0x0000000003899273 in EditorFileSystem::_notification (this=0xdbc7f20, p_what=17) at editor/editor_file_system.cpp:1214
#13 0x00000000038a838e in EditorFileSystem::_notificationv (this=0xdbc7f20, p_notification=17, p_reversed=false) at editor/editor_file_system.h:113
#14 0x00000000062bce03 in Object::notification (this=0xdbc7f20, p_notification=17, p_reversed=false) at core/object/object.cpp:846
#15 0x00000000047fb67b in SceneTree::_notify_group_pause (this=0xcd5afa0, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:855
#16 0x00000000047f9904 in SceneTree::process (this=0xcd5afa0, p_time=0.14221099999999964) at scene/main/scene_tree.cpp:453
#17 0x00000000023ab7a6 in Main::iteration () at main/main.cpp:2691
#18 0x0000000002366e6d in OS_LinuxBSD::run (this=0x7fffffffd180) at platform/linuxbsd/os_linuxbsd.cpp:342
#19 0x00000000023634cc in main (argc=2, argv=0x7fffffffd6e8) at platform/linuxbsd/godot_linuxbsd.cpp:58
```

Two things need to be done:
- The crash should be fixed
- The error reporting for the whole `vorbis` module could use some love as it seems to overly depend on `WARN_PRINT` to report things which are actually fatal bugs. Most importantly, errors which can be triggered by end users under reasonable use conditions should be given explicit and helpful messages (see e.g. #56903).

### Steps to reproduce

- Load MRP, or any (?) OGG Theora file with `.ogg` extension (an `.ogv` OGG Theora file can be renamed to trigger the issue)

### Minimal reproduction project

[OggTheoraCrashesVorbis.zip](https://github.com/godotengine/godot/files/7889640/OggTheoraCrashesVorbis.zip)

**Comment by Riteo** [comment]
Oh I think I stumbled on this when testing an ogg from the web some time ago. If you want I can find it.
