### ISSUE TITLE
HTML5: "Could not open" blank tscn, "indirect call to null"

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#57391]
### Godot version

3.4.stable.mono.official

### System information

Windows 10, GLES2, Vulkan

### Issue description

For some reason, when I change the Main Scene to anything else but my old title screen, the HTML5 export refuses to run the game at all.

![image](https://user-images.githubusercontent.com/8707990/151655361-e05a17e8-3520-4eed-b7f7-0708a7963b42.png)

Here is the console output on Firefox:
```
Godot Engine v3.4.stable.mono.official.206ba70f4 - https://godotengine.org tmp_js_export.js:347:16
OpenGL ES 2.0 Renderer: ANGLE (Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664) tmp_js_export.js:347:16
OpenGL ES Batching: ON tmp_js_export.js:347:16
 tmp_js_export.js:347:16
ERROR: Mono: Core API hash mismatch. tmp_js_export.js:362:18
   at: _init_godot_api_hashes (modules/mono/mono_gd/gd_mono.cpp:490) - Mono: Core API hash mismatch. tmp_js_export.js:362:18
Mono: Config attempting to parse: '/root/mono-installs/wasm-runtime-release/etc/mono/config'. tmp_js_export.js:347:16
Mono: Config attempting to parse: '/home/web_user/.mono/config'. tmp_js_export.js:347:16
ERROR: Cannot open file 'res://SplashScreen.tscn'. tmp_js_export.js:362:18
   at: load_interactive (scene/resources/resource_format_text.cpp:1183) - Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>() tmp_js_export.js:362:18
ERROR: Failed loading resource: res://SplashScreen.tscn. Make sure resources have been imported by opening the project in the editor at least once. tmp_js_export.js:362:18
   at: _load (core/io/resource_loader.cpp:271) - Condition "found" is true. Returned: RES() tmp_js_export.js:362:18
ERROR: Failed loading scene: res://SplashScreen.tscn tmp_js_export.js:362:18
   at: start (main/main.cpp:1998) - Condition "!scene" is true. Returned: false tmp_js_export.js:362:18
exception thrown: RuntimeError: indirect call to null,godot_js_main(int, char**)@:wasm-function[15324]:0x2ca1c5
main@:wasm-function[31565]:0x73169e
Godot/Module._main@http://localhost:8060/tmp_js_export.js:9:403120
callMain@http://localhost:8060/tmp_js_export.js:9:415259
SafeEngine/start/Engine</</<@http://localhost:8060/tmp_js_export.js:694:17
SafeEngine/start/Engine</<@http://localhost:8060/tmp_js_export.js:689:14
tmp_js_export.js:362:18
indirect call to null tmp_js_export.html:213:13
```

Here is the console output on Chromium, with a slightly different ending:
```
ERROR: Cannot open file 'res://SplashScreen.tscn'.
onPrintError @ tmp_js_export.js:362
tmp_js_export.js:362    at: load_interactive (scene/resources/resource_format_text.cpp:1183) - Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
onPrintError @ tmp_js_export.js:362
tmp_js_export.js:362 ERROR: Failed loading resource: res://SplashScreen.tscn. Make sure resources have been imported by opening the project in the editor at least once.
onPrintError @ tmp_js_export.js:362
tmp_js_export.js:362    at: _load (core/io/resource_loader.cpp:271) - Condition "found" is true. Returned: RES()
onPrintError @ tmp_js_export.js:362
tmp_js_export.js:362 ERROR: Failed loading scene: res://SplashScreen.tscn
onPrintError @ tmp_js_export.js:362
tmp_js_export.js:362    at: start (main/main.cpp:1998) - Condition "!scene" is true. Returned: false
onPrintError @ tmp_js_export.js:362
tmp_js_export.js:362 exception thrown: RuntimeError: function signature mismatch,RuntimeError: function signature mismatch
    at godot_js_main(int, char**) (<anonymous>:wasm-function[15324]:0x2ca1c5)
    at main (<anonymous>:wasm-function[31565]:0x73169e)
    at Module._main (http://localhost:8060/tmp_js_export.js:9:403120)
    at Object.callMain (http://localhost:8060/tmp_js_export.js:9:415246)
    at http://localhost:8060/tmp_js_export.js:694:28
    at new Promise (<anonymous>)
    at http://localhost:8060/tmp_js_export.js:689:14
onPrintError @ tmp_js_export.js:362
tmp_js_export.html:213 function signature mismatch
```

### Steps to reproduce

I can't reproduce this bug on any other project that I have.

### Minimal reproduction project

[Only happens on here.](https://github.com/JapanYoshi/salty)

**Comment by akien-mga** [comment]
I'm not able to reproduce the issue, this `salty` project exports and runs fine for me with:
- 3.4.stable.mono
- 3.4.2.stable (there's no C# script so no need to use the Mono build which adds unnecessary libraries)

**Comment by JapanYoshi** [comment]
> I'm not able to reproduce the issue, this `salty` project exports and runs fine for me with:
> 
>     * 3.4.stable.mono
> 
>     * 3.4.2.stable (there's no C# script so no need to use the Mono build which adds unnecessary libraries)

Out of options, I've tried deleting my local repo and re-cloning the online repo, and for some reason, the bug is gone on 3.4.stable.mono. Maybe it was some aggressive caching had gone awry?

I'll try an export with 3.4.2.stable as well. Thanks for the tip.
