### ISSUE TITLE
Freeze in core/map.h when zooming out too much in the 2D viewport

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5820]
**Operating system or device - Godot version:**
Mageia 6 x86, git master HEAD

**Issue description** (what happened, and what was expected):
When zooming out with the mouse wheel until everything in the 2D viewport becomes super tiny, the editor freezes.
GDB reports it as a SIGINT and gives the following backtrace:
```
Thread 1 "godot-git" received signal SIGINT, Interrupt.
0x000000000139ea7d in Map<SpatialIndexer2D::CellKey, SpatialIndexer2D::CellData, Comparator<SpatialIndexer2D::CellKey>, DefaultAllocator>::find (this=0x4e7ed90, p_key=...)
    at core/map.h:562
562             }
(gdb) bt
#0  0x000000000139ea7d in Map<SpatialIndexer2D::CellKey, SpatialIndexer2D::CellData, Comparator<SpatialIndexer2D::CellKey>, DefaultAllocator>::find (this=0x4e7ed90, p_key=...)
    at core/map.h:562
#1  0x000000000139e6df in SpatialIndexer2D::_update (this=0x4e7ed90) at scene/resources/world_2d.cpp:246
#2  0x000000000139c719 in World2D::_update (this=0x4e6c050) at scene/resources/world_2d.cpp:331
#3  0x0000000000f1bbe8 in Viewport::update_worlds (this=0x4e6bb60) at scene/main/viewport.cpp:282
#4  0x00000000004aa664 in MethodBind0::call (this=0x35e4cb0, p_object=0x4e6bb60, p_args=0x7fffffffd280, p_arg_count=0, r_error=...) at core/method_bind.inc:47
#5  0x0000000001857c73 in Object::call (this=0x4e6bb60, p_method=..., p_args=0x7fffffffd280, p_argcount=0, r_error=...) at core/object.cpp:896
#6  0x00000000018577aa in Object::call (this=0x4e6bb60, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:770
#7  0x0000000000f06006 in SceneTree::call_group (this=0x38e4730, p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at scene/main/scene_main_loop.cpp:215
#8  0x0000000000f07358 in SceneTree::iteration (this=0x38e4730, p_time=0.0166666675) at scene/main/scene_main_loop.cpp:503
#9  0x00000000004317bf in Main::iteration () at main/main.cpp:1573
#10 0x000000000041485b in OS_X11::run (this=0x7fffffffd760) at platform/x11/os_x11.cpp:2016
#11 0x000000000040cf20 in main (argc=4, argv=0x7fffffffdc68) at platform/x11/godot_x11.cpp:41
```

**Steps to reproduce:**
- Zoom out, way too much

**Comment by akien-mga** [comment]
Does not see to freeze on zoom in, and no issues either on zoom in/out in the 3D viewport.

The most obvious fix would be to put a max value for zoom out (and maybe for zoom in too, do we want to support zooming by a factor 100K? :D)
