### ISSUE TITLE
Android export on Google play crash

### ISSUE THREAD

**Issue by wangdong20** [godotengine/godot#59128]
### Godot version

3.4.3

### System information

MacOS 12.1, Mac Pro, GLES2

### Issue description

I just released game on Google play which is exported from Godot. In order to support low end device, I choose to support GLES2. It does work on my Android phone and passes the alpha test on Google play console but got crashes from Google play console statistics.
Here is the crash log and device information:
`java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
  at java.lang.System.loadLibrary (System.java:1667)
  at org.godotengine.godot.GodotLib.<clinit> (GodotLib.java:45)
  at org.godotengine.godot.Godot.initializeGodot (Godot.java:563)
  at org.godotengine.godot.Godot.onCreate (Godot.java:716)
  at androidx.fragment.app.Fragment.performCreate (Fragment.java:2949)
  at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:475)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:278)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2189)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2100)
  at androidx.fragment.app.FragmentManager.execSingleAction (FragmentManager.java:1971)
  at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:311)
  at org.godotengine.godot.FullScreenGodotApp.onCreate (FullScreenGodotApp.java:72)
  at com.godot.game.GodotApp.onCreate (GodotApp.java:45)`

Device infos: Lenovo Tab M10 (HD), TB-X505X
ABI: arm64-v8a, armeabi-v7a, armeabi
Device size: 800x1280
DPI: 160 (mdpi)
Android version: API28, API 29
OpenGL ES version: 3.2
GPU: Qualcomm Adreno 504 (320 Mhz)

### Steps to reproduce

Export as aab from Godot support GLES2.
Upload to Google play store.
Get crash log on the Google play console.

**Comment by akien-mga** [comment]
```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
  at java.lang.System.loadLibrary (System.java:1667)
  at org.godotengine.godot.GodotLib.<clinit> (GodotLib.java:45)
  at org.godotengine.godot.Godot.initializeGodot (Godot.java:563)
  at org.godotengine.godot.Godot.onCreate (Godot.java:716)
```

It seems to fail loading `libgodot_android.so` here:
https://github.com/godotengine/godot/blob/0ae6150d8eed297497544c007405720c7307792a/platform/android/java/lib/src/org/godotengine/godot/GodotLib.java#L44-L46

Can you check that your AAB properly contains the `libgodot_android.so` library for all the ABIs that you support?

> ABI: arm64-v8a, armeabi-v7a, armeabi

Seems like `armeabi` is still reported as a supported secondary ABI even though it's no longer supported by Google Play: https://developer.android.com/ndk/guides/abis

I wonder if for some reason this device would wrongly attempt to load the `armeabi` library (which we don't provide, and can't even build anymore) instead of `arm64-v8a`?

**Comment by wangdong20** [comment]
> ```
> java.lang.UnsatisfiedLinkError: 
>   at java.lang.Runtime.loadLibrary0 (Runtime.java:1067)
>   at java.lang.Runtime.loadLibrary0 (Runtime.java:1007)
>   at java.lang.System.loadLibrary (System.java:1667)
>   at org.godotengine.godot.GodotLib.<clinit> (GodotLib.java:45)
>   at org.godotengine.godot.Godot.initializeGodot (Godot.java:563)
>   at org.godotengine.godot.Godot.onCreate (Godot.java:716)
> ```
> 
> It seems to fail loading `libgodot_android.so` here:
> 
> https://github.com/godotengine/godot/blob/0ae6150d8eed297497544c007405720c7307792a/platform/android/java/lib/src/org/godotengine/godot/GodotLib.java#L44-L46
> 
> Can you check that your AAB properly contains the `libgodot_android.so` library for all the ABIs that you support?
> 
> > ABI: arm64-v8a, armeabi-v7a, armeabi
> 
> Seems like `armeabi` is still reported as a supported secondary ABI even though it's no longer supported by Google Play: https://developer.android.com/ndk/guides/abis
> 
> I wonder if for some reason this device would wrongly attempt to load the `armeabi` library (which we don't provide, and can't even build anymore) instead of `arm64-v8a`?

How can I check the AAB properly contains the libgodot_android.so library for all the ABIs that I support?

I just set the arm64-v8a, armeabi-v7a true on Godot android export setting.

**Comment by akien-mga** [comment]
Another user (Dan_SCE) reported the same issue last week on the contributors chat:
![image](https://user-images.githubusercontent.com/4701338/158129402-ed5b1641-1ca5-4734-8c61-6744899e41d3.png)
![image](https://user-images.githubusercontent.com/4701338/158129477-51e6ceba-3118-426e-a7b0-532f5c6bfb6f.png)

@wangdong20 Do you do a custom build with additional plugins?

---

I'm not familiar with Java and Android lib loading but it's worth noting that `UnsatisfiedLinkError` may also mean that even though `libgodot_android.so` is present, one of its dependencies cannot be loaded (and then `libgodot_android.so` cannot be loaded either). I.e. this may not be a "file not found" error but an actual dependency issue.

Here are the dependencies for `lib/arm64-v8a/libgodot_android.so` in 3.4.3:
```
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libOpenSLES.so]
 0x0000000000000001 (NEEDED)             Shared library: [libEGL.so]
 0x0000000000000001 (NEEDED)             Shared library: [libGLESv3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libGLESv2.so]
 0x0000000000000001 (NEEDED)             Shared library: [libandroid.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
```

Which are the ones we set there:
https://github.com/godotengine/godot/blob/0ae6150d8eed297497544c007405720c7307792a/platform/android/detect.py#L362

Worth noting, `libGLESv3.so` as a hard dependency might seem weird, but AFAIR it's provided as a stub on all Android devices even if OpenGL ES 3.0 is not supported.

---

> How can I check the AAB properly contains the libgodot_android.so library for all the ABIs that I support?

You can unzip the generated AAB and inspect the contents to see if both `libgodot_android.so` and `libc++_shared.so` are present in the `lib/<abi>/` folders.

**Comment by wangdong20** [comment]
I made a custom build with admob plugin.

Just unziped the AAB file and both `libgodot_android.so` and `libc++_shared.so` are presented in the `lib/<abi>/` folders.

**Comment by DmitriySalnikov** [comment]
Same issue:
```
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1087)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1008)
  at java.lang.System.loadLibrary (System.java:1664)
  at org.godotengine.godot.GodotLib.<clinit> (GodotLib.java:45)
  at org.godotengine.godot.Godot.initializeGodot (Godot.java:563)
  at org.godotengine.godot.Godot.onCreate (Godot.java:716)
  at androidx.fragment.app.Fragment.performCreate (Fragment.java:2949)
  at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:475)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:278)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2189)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2100)
  at androidx.fragment.app.FragmentManager.execSingleAction (FragmentManager.java:1971)
  at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:311)
  at org.godotengine.godot.FullScreenGodotApp.onCreate (FullScreenGodotApp.java:72)
  at com.godot.game.GodotApp.onCreate (GodotApp.java:45)
  at android.app.Activity.performCreate (Activity.java:8215)
  at android.app.Activity.performCreate (Activity.java:8199)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1309)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3824)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4027)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2336)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:247)
  at android.app.ActivityThread.main (ActivityThread.java:8676)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

Samsung Galaxy Tab A7
ABI: arm64-v8a armeabi-v7a armeabi
Device size: 1200x2000
DPI: 240 (hdpi)
Android version: Android 10 (SDK 29), Android 11 (SDK 30), Android 12 (SDK 31)
OpenGL ES version: 3.2
System on Chip (SOC): Qualcomm SM6115
GPU: Qualcomm Adreno 610 (950 MHz)

Godot: v3.4.4.stable.custom_build [419e713a2]
All 4 ABIs are included

--------------

And only after I wrote everything above, I noticed that the error report came from a version downloaded from a third-party resource, not from Google play... And now I do not know how reliable this report is at all.

![image](https://user-images.githubusercontent.com/7782218/173843034-ceafa91c-4b40-4180-8221-ad0b09cf6613.png)

**Comment by KYRYAMBA** [comment]
one year later
project target SDK 32
uses custom build and custom export template with encryption key.
on my testing devices works good..

google crosshatch (Pixel 3 XL) Android 12 (SDK 31)
both lib/<abi>/ contains libc++_shared.so and libgodot_android.so
> java.lang.UnsatisfiedLinkError
> Exception java.lang.UnsatisfiedLinkError: dlopen failed: library "libgodot_android.so" not found
>   at java.lang.Runtime.loadLibrary0 (Runtime.java:1077)
>   at java.lang.Runtime.loadLibrary0 (Runtime.java:998)
>   at java.lang.System.loadLibrary (System.java:1661)
>   at org.godotengine.godot.GodotLib.<clinit> (GodotLib.java:49)
>   at org.godotengine.godot.Godot.initializeGodot (Godot.java:587)
>   at org.godotengine.godot.Godot.onCreate (Godot.java:723)
>   at androidx.fragment.app.Fragment.performCreate (Fragment.java:2949)
>   at androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:475)
>   at androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:278)
>   at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2189)
>   at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2100)
>   at androidx.fragment.app.FragmentManager.execSingleAction (FragmentManager.java:1971)
>   at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java:311)
>   at org.godotengine.godot.FullScreenGodotApp.onCreate (FullScreenGodotApp.java:69)
>   at com.godot.game.GodotApp.onCreate (GodotApp.java:45)
>   at android.app.Activity.performCreate (Activity.java:8051)
>   at android.app.Activity.performCreate (Activity.java:8031)
>   at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1329)
>   at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3612)
>   at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3796)
>   at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
>   at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
>   at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
>   at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2214)
>   at android.os.Handler.dispatchMessage (Handler.java:106)
>   at android.os.Looper.loopOnce (Looper.java:201)
>   at android.os.Looper.loop (Looper.java:288)
>   at android.app.ActivityThread.main (ActivityThread.java:7842)
>   at java.lang.reflect.Method.invoke
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)

**Comment by Gromph** [comment]
We still see a burst of these reported to sentry.io everytime after we release an update to our Godot 4.3 games. Then once everyone has updated the reports go away.

I'm Dan_SCE in the screen shot of chat above

The .aab contains libs for arm64-v8a, armeabi-v7a, x86, x86_64

The most reports come from Pixel 6 Pro running Android 12. 

But there's  reports from a wide range of android versions (9, 10, 11, 12, 13, 14)  and both arm and x86

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libgodot_android.so" not found
    at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
    at java.lang.Runtime.loadLibrary0(Runtime.java:998)
    at java.lang.System.loadLibrary(System.java:1656)
    at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:51)
    at org.godotengine.godot.GodotLib.initialize(GodotLib.java)
    at org.godotengine.godot.Godot.onInitNativeLayer(Godot.kt:346)
    at org.godotengine.godot.GodotFragment.performEngineInitialization(GodotFragment.java:204)
    at org.godotengine.godot.GodotFragment.onCreate(GodotFragment.java:196)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:3095)
    at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:516)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:274)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2103)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1998)
    at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1910)
    at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
    at org.godotengine.godot.GodotActivity.onCreate(GodotActivity.kt:80)
    at com.godot.game.GodotApp.onCreate(GodotApp.java:47)
    at android.app.Activity.performCreate(Activity.java:8054)
    at android.app.Activity.performCreate(Activity.java:8034)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

**Comment by akien-mga** [comment]
CC @m4gr3d 

This is pretty puzzling.

> We still see a burst of these reported to sentry.io everytime after we release an update to our Godot 4.3 games. Then once everyone has updated the reports go away.

This sounds unlikely to be the case, but this description and the error make me wonder if that's something that happens when the game is bring updated while it's running in the background, and Android removes the .so lib before the old instance terminates. Or the other way around, that it attempts to restart the game after update when it's not fully setup yet.

This sounds a bit silly but I figured I'd mention this weird hypothesis anyway :D
