### ISSUE TITLE
GDScript 2.0: Can't extend inner class

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#59508]
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

Windows 10

### Issue description

I coding a built-in GDScript like this:

```
extends Node2D

class A:
	func test():
		prints("A test")

class B extends A: # error here
	func test():
		prints("B test")

func _ready():
	var b = B.new()
	b.test()
```

when I run this scene, App will freeze a moment then crash, and print nothing.
If I change code like this:
```
extends Node2D

class A:
	func test():
		prints("A test")

class B:
	func test():
		prints("B test")

func _ready():
	var b = B.new()
	b.test()
```
There was no error.

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[InnerClsExtendsTest.zip](https://github.com/godotengine/godot/files/8348601/InnerClsExtendsTest.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/59014 (possible duplicate?).

**Comment by strank** [comment]
Just a quick note: Running the following with `--headless -s` does not crash, prints "B test" as expected.

```
extends SceneTree #extends Node2D

class A:
        func test():
                prints("A test")

class B extends A:
        func test():
                prints("B test")

func _init():
        var b = B.new()
        b.test()
```

**Comment by akien-mga** [comment]
I can reproduce the crash in the current `master` branch (0a158d772):

```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x0000000005a4c10b in GDScriptFunction::call (this=0x0, p_instance=0xb640be0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:463
463             if (!_code_ptr) {

(gdb) bt
#0  0x0000000005a4c10b in GDScriptFunction::call (this=0x0, p_instance=0xb640be0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:463
#1  0x000000000591885f in GDScript::_super_implicit_constructor (this=0xbea1520, p_script=0xbea1a60, p_instance=0xb640be0, r_error=...) at modules/gdscript/gdscript.cpp:131
#2  0x0000000005918822 in GDScript::_super_implicit_constructor (this=0xbea1520, p_script=0xbea1520, p_instance=0xb640be0, r_error=...) at modules/gdscript/gdscript.cpp:126
#3  0x0000000005918abb in GDScript::_create_instance (this=0xbea1520, p_args=0x7fffffff9760, p_argcount=0, p_owner=0xa717bf0, p_is_ref_counted=true, r_error=...) at modules/gdscript/gdscript.cpp:157
#4  0x0000000005919070 in GDScript::_new (this=0xbea1520, p_args=0x7fffffff9760, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:219
#5  0x0000000005942765 in MethodBindVarArgTR<GDScript, Variant>::call (this=0xba948a0, p_object=0xbea1520, p_args=0x7fffffff9760, p_arg_count=0, r_error=...) at ./core/object/method_bind.h:259
#6  0x0000000005a5371f in GDScriptFunction::call (this=0xbf00ae0, p_instance=0xbf37aa0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1633
#7  0x0000000005922dd1 in GDScriptInstance::callp (this=0xbf37aa0, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:1537
#8  0x0000000006fe33f4 in Node::_gdvirtual__ready_call<false> (this=0xbe99d90) at scene/main/node.h:233
#9  0x0000000006fc8e16 in Node::_notification (this=0xbe99d90, p_notification=13) at scene/main/node.cpp:154
#10 0x0000000004da689c in Node::_notificationv (this=0xbe99d90, p_notification=13, p_reversed=false) at ./scene/main/node.h:45
#11 0x0000000005080ca1 in CanvasItem::_notificationv (this=0xbe99d90, p_notification=13, p_reversed=false) at ./scene/main/canvas_item.h:45
#12 0x0000000006f22909 in Node2D::_notificationv (this=0xbe99d90, p_notification=13, p_reversed=false) at ./scene/2d/node_2d.h:37
#13 0x0000000008cdbc3f in Object::notification (this=0xbe99d90, p_notification=13, p_reversed=false) at core/object/object.cpp:848
#14 0x0000000006fc91bc in Node::_propagate_ready (this=0xbe99d90) at scene/main/node.cpp:187
#15 0x0000000006fc913f in Node::_propagate_ready (this=0xbd62730) at scene/main/node.cpp:179
#16 0x0000000006fd601e in Node::_set_tree (this=0xbd62730, p_tree=0xb0ff430) at scene/main/node.cpp:2478
#17 0x0000000006ffed00 in SceneTree::initialize (this=0xb0ff430) at scene/main/scene_tree.cpp:399
#18 0x0000000004aa8c2c in OS_LinuxBSD::run (this=0x7fffffffd200) at platform/linuxbsd/os_linuxbsd.cpp:344
#19 0x0000000004aa4f5c in main (argc=1, argv=0x7fffffffd738) at platform/linuxbsd/godot_linuxbsd.cpp:68
```
