### ISSUE TITLE
Executing `CSGCylinder.set_radius` crashes Godot due cyclic recursion

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#60325]
### Godot version

3.5.beta.custom_build. 20b08185f

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When executing
```
	var temp_variable14293 = CSGCylinder.new()
	temp_variable14293.set_radius(-INF)
	temp_variable14293.queue_free()
```

Godot crashes with this backtrace
```
thirdparty/misc/mikktspace.c:443:2: runtime error: -nan is outside the range of representable values of type 'int'
Segmentation fault (core dumped)

#0  0x0000000004122c51 in MergeVertsFast (piTriList_in_and_out=<error reading variable: Cannot access memory at address 0x7fffff7fef88>, 
    pTmpVert=<error reading variable: Cannot access memory at address 0x7fffff7fef80>, 
    pContext=<error reading variable: Cannot access memory at address 0x7fffff7fef78>, 
    iL_in=<error reading variable: Cannot access memory at address 0x7fffff7fef74>, 
    iR_in=<error reading variable: Cannot access memory at address 0x7fffff7fef70>) at thirdparty/misc/mikktspace.c:577
#1  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#2  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#3  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#4  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#5  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#6  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#7  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#8  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#9  0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#10 0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#11 0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#12 0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)
    at thirdparty/misc/mikktspace.c:682
#13 0x000000000412367f in MergeVertsFast (piTriList_in_and_out=0xeb518d0, pTmpVert=0xeb50820, pContext=0x7fffffffced0, iL_in=0, iR_in=95)


```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Similar crash with 
```
	var temp_variable17979 = CSGTorus.new()
	temp_variable17979.set_inner_radius(-NAN)
	temp_variable17979.queue_free()
```

**Comment by qarmin** [comment]
```
CSGBox.new().set_depth(-INF)
```
also have problems

**Comment by qarmin** [comment]
Also
```
	var temp_variable10021 = CSGPolygon.new()
	temp_variable10021.set_polygon(PoolVector2Array([Vector2(-0.930431, -0.366467), Vector2(-53.417389, -80.766953), Vector2(-0.511454, 0.859311), Vector2(0.995835, -0.091179), Vector2(-0.560087, 0.828434), Vector2(-0.369554, 0.929209), Vector2(-97.775208, -5.518908), Vector2(-97.55407, -95.434593), Vector2(-NAN, -0), Vector2(55.902515, 31.858027), Vector2(-14.406729, 89.91468), Vector2(-0.93724, 0.348685), Vector2(0.658174, -0.752866), Vector2(0.413492, -0.910508), Vector2(-0.284307, -0.958733), Vector2(0.81128, -0.584657), Vector2(89.5522, 22.327923), Vector2(4.508603, 81.189857), Vector2(-0.057189, -0.998363), Vector2(70.945694, -NAN), Vector2(-0, -NAN), Vector2(-NAN, 0), Vector2(16.387867, -12.063819), Vector2(-0.775829, -0.630943), Vector2(-71.695091, 37.838818)]))
```

**Comment by qarmin** [comment]
And
```
set_outer_radius
```

**Comment by qarmin** [comment]
Same crash with 
```
extends Node
func _process(delta):

	var temp_variable3043 = CSGCylinder3D.new()
	add_child(temp_variable3043)
	temp_variable3043.set_height(-INF)
	temp_variable3043.queue_free()
```
