### ISSUE TITLE
`OS.get_screen_size` causes memory leak

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#60468]
### Godot version

3.5 beta 4

### System information

Ubuntu 22.04, Intel HD 3000

### Issue description

```
	var temp_variable1 = ClassDB.instance("_OS")
	temp_variable1.get_screen_size(12)
	temp_variable1.get_screen_size(8)
	temp_variable1.free()
```
```
Direct leak of 24 byte(s) in 2 object(s) allocated from:
    #0 0x7fc6ad58c868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7fc6ad46fa7d in XineramaQueryScreens (/lib/x86_64-linux-gnu/libXinerama.so.1+0x1a7d)
    #2 0x1373132d in _OS::get_screen_size(int) const core/bind/core_bind.cpp:299
    #3 0xefd8e03 in MethodBind1RC<Vector2, int>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1305
    #4 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #5 0x12aae1a3 in Object::callv(StringName const&, Array const&) core/object.cpp:827
    #6 0x12b17f86 in MethodBind2R<Variant, StringName const&, Array const&>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:1681
    #7 0x12ab065a in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #8 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #9 0x1f0b241 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1048
    #10 0x1d399f3 in GDScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) modules/gdscript/gdscript.cpp:1196
    #11 0x12ab01c7 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:899
    #12 0x12d53970 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1185
    #13 0x1f0b2c2 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1050
    #14 0x1d39f09 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1211
    #15 0xcf19d65 in Node::_notification(int) scene/main/node.cpp:56
    #16 0x1bdfc0f in Node::_notificationv(int, bool) scene/main/node.h:45
    #17 0x12ab0af6 in Object::notification(int, bool) core/object.cpp:927
    #18 0xd0596df in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:1057
    #19 0xd048a62 in SceneTree::idle(float) scene/main/scene_tree.cpp:596
    #20 0x1a18d22 in Main::iteration() main/main.cpp:2271
    #21 0x18e7b7b in OS_X11::run() platform/x11/os_x11.cpp:3842
    #22 0x184b109 in main platform/x11/godot_x11.cpp:55
    #23 0x7fc6ac93bd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

```

Looks like pointer is not freed in case of error
https://github.com/godotengine/godot/blob/3ba980379dfb72f5d238640835d8e77c76cf3c99/platform/x11/os_x11.cpp#L1273-L1279

### Steps to reproduce

Above

**Comment by akien-mga** [comment]
Fixed by #60484.
