### ISSUE TITLE
Segmentation fault when setting exported value to self in imported resource

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#60590]
### Godot version

3.4.4

### System information

Linux

### Issue description

When writing a custom importer plugin that imports a resource which sets a member to `self` Godot crashes with a segmentation fault. This happens when the value is set to `self` directly, or when used inside another datatype like a dictionary or array.

This is expected to fail, but should not lead to a segfault.

### Steps to reproduce

Write a resource importer and set a member to `self` in the imported resource.

```gdscript
extends Resource

export var value: Resource

func _init() -> void:
	value = self
	# segfault
```

### Minimal reproduction project

This project crashes when trying to import `test.json`.

[Dictionary Crash.zip](https://github.com/godotengine/godot/files/8584820/Dictionary.Crash.zip)

**Comment by Calinou** [comment]
I can confirm this on 3.5.beta https://github.com/godotengine/godot/commit/59e84be9b5137877b415d1c57349f4fa5a67897a.

The crash handler fails to kick in, so I don't get a backtrace automatically. Running the editor binary through GDB reveals the following backtrace:

```
(gdb) bt
#0  0x0000000006261ad3 in Memory::alloc_static (p_bytes=64, p_pad_align=true) at core/os/memory.cpp:75
#1  0x0000000002f2bad6 in CowData<wchar_t>::resize (this=0x7fffff7ff4d0, p_size=10) at ./core/cowdata.h:278
#2  0x0000000003e6d07b in String::resize (this=0x7fffff7ff4d0, p_size=10) at ./core/ustring.h:157
#3  0x000000000616a3be in String::copy_from (this=0x7fffff7ff4d0, p_cstr=0x27fe3e5 "Reference") at core/ustring.cpp:230
#4  0x000000000617031a in String::String (this=0x7fffff7ff4d0, p_str=0x27fe3e5 "Reference") at core/ustring.cpp:1691
#5  0x000000000297b1e2 in Reference::get_class_static () at ./core/reference.h:40
#6  0x000000000297b4db in Reference::_get_property_listv (this=0x12c2c3a0, p_list=0x7fffff7ff988, p_reversed=false) at ./core/reference.h:40
#7  0x0000000002b6d8c7 in Resource::_get_property_listv (this=0x12c2c3a0, p_list=0x7fffff7ff988, p_reversed=false) at ./core/resource.h:49
#8  0x00000000060e44e1 in Object::get_property_list (this=0x12c2c3a0, p_list=0x7fffff7ff988, p_reversed=false) at core/object.cpp:646
#9  0x00000000063918aa in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1566
#10 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#11 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#12 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#13 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#14 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#15 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#16 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#17 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#18 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#19 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#20 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#21 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#22 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#23 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#24 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#25 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#26 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#27 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#28 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#29 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#30 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#31 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#32 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#33 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#34 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#35 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#36 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#37 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#38 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#39 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#40 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#41 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#42 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#43 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#44 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#45 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#46 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#47 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#48 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#49 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
#50 0x0000000006391be4 in ResourceFormatSaverBinaryInstance::_find_resources (this=0x7fffffff7cb8, p_variant=..., p_main=false) at core/io/resource_format_binary.cpp:1582
[ ... infinite recursion ... ]
```

**Comment by maximkulkin** [comment]
I ran into similar issue of trying to save Resource graph with cycles:
```swift
class_name MyResource
extends Resource

export var other: Resource
```
When having resources like this
```swift
var a = MyResource.new()
var b = MyResource.new()
a.other = b
b.other = a
ResourceSaver.save("res://saved.tres", a)
```
It crashes. It also crashes if there is a longer loop: "A -> B -> C -> A".

If you pass a ResourceSaver.FLAG_CHANGE_PATH and the loop is full, it will not crash, will print error about circular references in console, will break the loop by replacing one of the references with null and save successfully:
```swift
var a = MyResource.new()
var b = MyResource.new()
var c = MyResource.new()
a.other = b
b.other = c
c.other = a
ResourceSaver.save("res://saved.tres", a, ResourceSaver.FLAG_CHANGE_PATH)
```

However, if the loop is not full, it just crashes:
```swift
var a = MyResource.new()
var b = MyResource.new()
var c = MyResource.new()
a.other = b
b.other = c
c.other = b
ResourceSaver.save("res://saved.tres", a, ResourceSaver.FLAG_CHANGE_PATH)
```

The bug reproduces on both text (.tres) and binary (.res) resources, in Godot 3.5 [991bb6ac7] and in Godot 4.0.beta3 [01ae26d31].

Expected behavior: it dumps all resources as if there were no loops (and does a better job of tracking which resources were already saved to avoid infinite recursion and eventual crash). Some resource might have references to other resources that are found later in the resource file. When loading, it instantiates and initializes resources as usual, except for references to resources that haven't been seen yet are postponed until all resources are initialized.

**Comment by maximkulkin** [comment]
I am working on a fix that will a) stop Godot from crashing when saving resources with circular references; b) allow saving and loading resources with circular references. So far I have successfully implemented fix on text format saver (ResourceFormatSaverText). Will need to do more tests (especially regarding saving/loading packed scenes) and then make the same change to binary format.
