### ISSUE TITLE
Crash when selecting background mode "Canvas" on the Environment of a WorldEnvironment node in 2D 

### ISSUE THREAD

**Issue by floere** [godotengine/godot#62079]
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

macOS 12.3.1 (21E258), Metal GPUFamily Apple 7, Vulkan

### Issue description

I expected Godot to not crash when selecting background mode "Canvas" on the Environment of a WorldEnvironment node in 2D. Instead, Godot crashes.

### Steps to reproduce

1. Open the `world.tscn` node.
2. Select the `WorldEnvironment` node in the tree.
3. Open the `Environment` in the inspector.
4. Switch `background_mode` to `Canvas`.
5. This results in a crash.

### Minimal reproduction project

[EnvironmentCanvasCrash.zip](https://github.com/godotengine/godot/files/8912512/EnvironmentCanvasCrash.zip)

**Comment by timothyqiu** [comment]
Removed `platform:macos` as I can also reproduce this on Arch Linux.

<details><summary>Backtrace</summary>

```
(gdb) bt
#0  0x0000555562580a32 in RendererSceneRenderRD::render_scene (this=0x629000258210, p_render_buffers=..., p_camera_data=0x7fffffffc100, p_prev_camera_data=0x0, p_instances=..., p_lights=..., p_reflection_probes=..., 
    p_voxel_gi_instances=..., p_decals=..., p_lightmaps=..., p_fog_volumes=..., p_environment=..., p_camera_effects=..., p_shadow_atlas=..., p_occluder_debug_tex=..., p_reflection_atlas=..., p_reflection_probe=..., 
    p_reflection_probe_pass=0, p_screen_mesh_lod_threshold=0, p_render_shadows=0x0, p_render_shadow_count=0, p_render_sdfgi_regions=0x0, p_render_sdfgi_region_count=0, p_sdfgi_update_data=0x0, r_render_info=0x0)
    at servers/rendering/renderer_rd/renderer_scene_render_rd.cpp:5127
#1  0x0000555562f3c405 in RendererSceneCull::render_empty_scene (this=0x62e000000410, p_render_buffers=..., p_scenario=..., p_shadow_atlas=...) at servers/rendering/renderer_scene_cull.cpp:3285
#2  0x0000555562fa0858 in RendererViewport::_draw_viewport (this=0x610000001150, p_viewport=0x6310012adb50) at servers/rendering/renderer_viewport.cpp:499
#3  0x0000555562fa30f2 in RendererViewport::draw_viewports (this=0x610000001150) at servers/rendering/renderer_viewport.cpp:660
#4  0x00005555622f490c in RenderingServerDefault::_draw (this=0x61b000012690, p_swap_buffers=true, frame_step=0.0069444444444444449) at servers/rendering/rendering_server_default.cpp:91
#5  0x00005555622f8399 in RenderingServerDefault::draw (this=0x61b000012690, p_swap_buffers=true, frame_step=0.0069444444444444449) at servers/rendering/rendering_server_default.cpp:385
#6  0x0000555558d9b165 in Main::iteration () at main/main.cpp:2775
#7  0x0000555558ce8a04 in OS_LinuxBSD::run (this=0x7fffffffe0c0) at platform/linuxbsd/os_linuxbsd.cpp:441
#8  0x0000555558cdd8da in main (argc=4, argv=0x7fffffffe698) at platform/linuxbsd/godot_linuxbsd.cpp:68
```

</details>

**Comment by akien-mga** [comment]
Seems related to TAA implementation, CC @JFonS @clayjohn

**Comment by mutater** [comment]
Also happens on Windows 10, don't know if this is relevant :)

**Comment by kayomn** [comment]
Just confirmed on Linux as well with the latest published alpha build.
