### ISSUE TITLE
Android crashes can't load "libgodot_android.so" (fails to access storage on Android 5.1)

### ISSUE THREAD

**Issue by AbanoubNassem** [godotengine/godot#63945]
### Godot version

4.0.alpha13

### System information

(Android Device)Oppo Mirror 5 Android 5.1 (Lollipop), ColorOS 2.1

### Issue description

App crashes on launch due to this:

```
E/QCOMSysDaemon( 5284): Can't find/open bootselect node: (No such file or directory)
E/Diag_Lib( 5284):  Diag_LSM_Init: Failed to open handle to diag driver, error = 2
E/QCOMSysDaemon( 5284):  Diag_LSM_Init failed : 0
E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
E/art     ( 5289): dlopen("/data/app/org.godotengine.godot4-1/lib/arm/libgodot_android.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "libgodot_android.so" (built with --hash-style=gnu?)
E/AndroidRuntime( 5289): FATAL EXCEPTION: main
E/AndroidRuntime( 5289): Process: org.godotengine.godot4, PID: 5289
E/AndroidRuntime( 5289): java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libgodot_android.so" (built with --hash-style=gnu?)
E/AndroidRuntime( 5289): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime( 5289): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:51)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:474)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.Godot.onCreate(Godot.java:614)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
E/AndroidRuntime( 5289): 	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
E/AndroidRuntime( 5289): 	at android.app.Activity.performCreate(Activity.java:6085)
E/AndroidRuntime( 5289): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.access$900(ActivityThread.java:164)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
E/AndroidRuntime( 5289): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5289): 	at android.os.Looper.loop(Looper.java:150)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.main(ActivityThread.java:5408)
E/AndroidRuntime( 5289): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5289): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5289): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime( 5289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
E/PhoneStatusBar(14116): updateNotificationTitleText  preIsInsidePanelCanSlide =true,misInsidePanelCanSlide = true,misInsidePanelOpen = false
E/WindowState(  915): getStack: Window{2f68804 u0 Starting org.godotengine.godot4} couldn't find taskId=16 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowState.getWindowList:1517 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2934 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 
E/WindowState(  915): getStack: Window{2f68804 u0 Starting org.godotengine.godot4} couldn't find taskId=16 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2939 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 com.android.server.wm.WindowManagerService.removeWindowLocked:2739 
E/PhoneStatusBar(14116): updateNotificationTitleText  preIsInsidePanelCanSlide =true,misInsidePanelCanSlide = true,misInsidePanelOpen = false
E/LocSvc_LBSApiV02(  915): E/virtual int lbs_core::LBSApiV02::wifiAttachmentStatusInject(const WifiSupplicantInfo&):688]: Error : st = 11, ind.status = 0
```

### Steps to reproduce

Just making a new Project and export it to Android Lollipop(5.1) device.

**Comment by akien-mga** [comment]
CC @m4gr3d. Sounds like it might be related to scoped storage?

**Comment by AbanoubNassem** [comment]
@akien-mga 

after digging a bit , it looks like Godot trying to load the lib from a wrong directory :
`.../lib/arm/libgodot_android.so"` that's incorrect  , since arm is missing the architecture, it should be :

`.../lib/arm64-v8a/libgodot_android.so"` ,  `.../lib/armeabi-v7a/libgodot_android.so"` etc...
and that's actually how the apk is exported , but currently Godot assume arm folder without the architecture.

**Comment by akien-mga** [comment]
Ah this might be a regression from recent changes to architecture handling then, CC @aaronfranke.

**Comment by aaronfranke** [comment]
@akien-mga Out of the architecture handling PRs that have been merged, Android has not been significantly touched yet.

**Comment by AbanoubNassem** [comment]
@akien-mga @aaronfranke 

sorry for the late reply , this issue also still present in Beta1

**Comment by m4gr3d** [comment]
> Just making a new Project and export it to Android Lollipop(5.1) device.

@AbanoubNassem How do you export the project to the Android device? Are you using `custom build`?

**Comment by AbanoubNassem** [comment]
> > Just making a new Project and export it to Android Lollipop(5.1) device.
> 
> @AbanoubNassem How do you export the project to the Android device? Are you using `custom build`?

I tried both ways, custom build and normal build , same issue.

**Comment by AbanoubNassem** [comment]
@m4gr3d 

thank you , now the only issue that still exist is this :

```
E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
```

and I have a black screen , not sure if it's because of this issue or something else

tested on Lollipop 5.1.1 API Level 21 , using normal export and custom export , same issue, should I open a new issue ?

**Comment by m4gr3d** [comment]
@AbanoubNassem yeah that should be a separate issue.
Are you also able to validate if a 3.5 project works on your device?

**Comment by AbanoubNassem** [comment]
@m4gr3d yup 3.5 works totally fine , no issue

**Comment by m4gr3d** [comment]
> @m4gr3d
> 
> thank you , now the only issue that still exist is this :
> 
> ```
> E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
> E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
> ```
> 
> and I have a black screen , not sure if it's because of this issue or something else
> 
> tested on Lollipop 5.1.1 API Level 21 , using normal export and custom export , same issue, should I open a new issue ?

@AbanoubNassem Did you open a new issue for the `Vold` error you reported above?

**Comment by AbanoubNassem** [comment]
@m4gr3d 

sorry for the late reply, no I didn't, please open a new issue, if you didn't yet.

**Comment by Trasd** [comment]
I cannot open or download a project on my Lollipop (5.1.1).  It crashes every time.

Samsung Galaxy TabPRO SM-T900 12.2" with Android Lollipop (v5.1.1) rooted.

Logcat attached.
[Log_2023-02-14_11-38-23.txt](https://github.com/godotengine/godot/files/10736893/Log_2023-02-14_11-38-23.txt)
