### ISSUE TITLE
Executing `SystemFont.set_font_names` cause memory leak

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#64118]
### Godot version

4.0.alpha.custom_build. 836fe9adc

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

Executing
```
	var temp_variable27 = SystemFont.new()
	temp_variable27.set_font_names(PackedStringArray(["", "127.0.0.1", "", "", "127.0.0.1", ".", "5555", "", ".", ".", "5555", "", "", "", "5555", "127.0.0.1", "2666393042", "127.0.0.1", "", "", "5555", "3550749558", ".", "127.0.0.1", ""]))
```

cause memory leak
```
Direct leak of 103320 byte(s) in 615 object(s) allocated from:
    #0 0x7f085d27b868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f0851b95fab in FcConfigCreate (/lib/x86_64-linux-gnu/libfontconfig.so+0x9fab)
    #2 0x152fecab in SystemFont::_update_base_font() scene/resources/font.cpp:2770
    #3 0x1530b11c in SystemFont::set_font_names(Vector<String> const&) scene/resources/font.cpp:2989
    #4 0x7650a43 in void call_with_variant_args_helper<__UnexistingClass, Vector<String> const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<String> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:262
    #5 0x764d9ac in void call_with_variant_args_dv<__UnexistingClass, Vector<String> const&>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<String> const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:409
    #6 0x7648040 in MethodBindT<Vector<String> const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:320
    #7 0x1c11c1e2 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:678
    #8 0x1b70b019 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #9 0x5ab5d5a in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #10 0x54f5a3b in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1584
    #11 0x11d1064b in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #12 0x11c75fb4 in Node::_notification(int) scene/main/node.cpp:56
    #13 0x42c8dbb in Node::_notificationv(int, bool) scene/main/node.h:45
    #14 0x1c11d6bf in Object::notification(int, bool) core/object/object.cpp:735
    #15 0x11dc5754 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:904
    #16 0x11db686b in SceneTree::process(double) scene/main/scene_tree.cpp:454
    #17 0x27547df in Main::iteration() main/main.cpp:2886
    #18 0x2594a2e in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:537
    #19 0x257bb8f in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #20 0x7f085c62ad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by bruvzg** [comment]
I guess the result of `FcInitLoadConfigAndFonts` should be destroyed, since it's not `Create` function I assumed it's returning a pointer to some global state, but apparently not (or at least it's increasing internal reference count).

```diff
diff --git a/platform/linuxbsd/os_linuxbsd.cpp b/platform/linuxbsd/os_linuxbsd.cpp
index e306c1054b..197d31dc81 100644
--- a/platform/linuxbsd/os_linuxbsd.cpp
+++ b/platform/linuxbsd/os_linuxbsd.cpp
@@ -368,6 +368,7 @@ Vector<String> OS_LinuxBSD::get_system_fonts() const {
 		FcPatternDestroy(pattern);
 	}
 	FcObjectSetDestroy(object_set);
+	FcConfigDestroy(config);
 
 	for (const String &E : font_names) {
 		ret.push_back(E);
@@ -417,6 +418,8 @@ String OS_LinuxBSD::get_system_font_path(const String &p_font_name, bool p_bold,
 		FcPatternDestroy(pattern);
 	}
 	FcObjectSetDestroy(object_set);
+	FcConfigDestroy(config);
+
 	return ret;
 #else
 	ERR_FAIL_V_MSG(String(), "Godot was compiled without fontconfig, system font support is disabled.");
```
Will test it tomorrow.
