### ISSUE TITLE
3.5 + C# crashes(Closes) constantly: WARNING: ObjectDB instances leaked at exit (run with --verbose for details).

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#64201]
### Godot version

3.5 stable

### System information

Linux Fedora, GLES3, NVIDIA GeForce MX150

### Issue description

Constantly crashes (Closes) if there is a problem:

```sh
=================================================================
	External Debugger Dump:
=================================================================
[New LWP 106359]
[New LWP 106388]
[New LWP 106389]
[New LWP 106390]
[New LWP 106391]
[New LWP 106392]
[New LWP 106393]
[New LWP 106394]
[New LWP 106395]
[New LWP 106396]
[New LWP 106397]
[New LWP 106398]
[New LWP 106399]
[New LWP 106400]
[New LWP 106401]
[New LWP 106402]
[New LWP 106403]
[New LWP 106404]
[New LWP 106405]
[New LWP 106406]
[New LWP 106409]
[New LWP 106411]
[New LWP 106419]
[New LWP 110930]
[New LWP 110931]
[New LWP 110932]
[New LWP 110933]
[New LWP 110934]
[New LWP 110944]
[New LWP 110961]

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.fedoraproject.org/ 
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f42b6adcbdf in wait4 () from /lib64/libc.so.6
  Id   Target Id                                            Frame 
* 1    Thread 0x7f42b693e7c0 (LWP 106358) "Godot_v3.5-stab" 0x00007f42b6adcbdf in wait4 () from /lib64/libc.so.6
  2    Thread 0x7f42a8f7e640 (LWP 106359) "Godot_v3.5-stab" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  3    Thread 0x7f429fbff640 (LWP 106388) "Godot_v:disk$0"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  4    Thread 0x7f429f3fe640 (LWP 106389) "Godot_v3.5:sh0"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  5    Thread 0x7f429ebfd640 (LWP 106390) "Godot_v3.5:sh1"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  6    Thread 0x7f429e3fc640 (LWP 106391) "Godot_v3.5:sh2"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  7    Thread 0x7f429dbfb640 (LWP 106392) "Godot_v3.5:sh3"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  8    Thread 0x7f429d3fa640 (LWP 106393) "Godot_v3.5:sh4"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  9    Thread 0x7f429cbf9640 (LWP 106394) "Godot_v3.5:sh5"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  10   Thread 0x7f427ffff640 (LWP 106395) "Godot_v3:gdrv0"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  11   Thread 0x7f427f7fe640 (LWP 106396) "Godot_v3:gdrv0"  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  12   Thread 0x7f427eee4640 (LWP 106397) "Godot_v3.5-stab" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  13   Thread 0x7f4277733640 (LWP 106398) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  14   Thread 0x7f4276f05640 (LWP 106399) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  15   Thread 0x7f4276704640 (LWP 106400) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  16   Thread 0x7f4275f03640 (LWP 106401) "Godot_v3.5-stab" 0x00007f42b6b080dc in select () from /lib64/libc.so.6
  17   Thread 0x7f42667ff640 (LWP 106402) "SGen worker"     0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  18   Thread 0x7f4266fff640 (LWP 106403) "Finalizer"       0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  19   Thread 0x7f422a1ff640 (LWP 106404) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  20   Thread 0x7f42299fe640 (LWP 106405) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  21   Thread 0x7f42291fd640 (LWP 106406) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  22   Thread 0x7f42289fc640 (LWP 106409) "Godot_v3.5-stab" 0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
  23   Thread 0x7f420c4ff640 (LWP 106411) "Thread Pool I/O" 0x00007f42b6b0588f in poll () from /lib64/libc.so.6
  24   Thread 0x7f423c93f640 (LWP 106419) "Godot_v3.5-stab" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  25   Thread 0x7f4249fff640 (LWP 110930) "Godot_v3.5-stab" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  26   Thread 0x7f420c2fe640 (LWP 110931) "Thread Pool Wor" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  27   Thread 0x7f4244b7d640 (LWP 110932) "Thread Pool Wor" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  28   Thread 0x7f4242a7f640 (LWP 110933) "Thread Pool Wor" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  29   Thread 0x7f429c3c8640 (LWP 110934) "Thread Pool Wor" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  30   Thread 0x7f4207bfd640 (LWP 110944) "Thread Pool Wor" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
  31   Thread 0x7f4207fff640 (LWP 110961) "Thread Pool Wor" 0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6

Thread 31 (Thread 0x7f4207fff640 (LWP 110961) "Thread Pool Wor"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94a3b in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000011852d6 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 30 (Thread 0x7f4207bfd640 (LWP 110944) "Thread Pool Wor"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94a3b in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000011852d6 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 29 (Thread 0x7f429c3c8640 (LWP 110934) "Thread Pool Wor"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94a3b in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000011852d6 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 28 (Thread 0x7f4242a7f640 (LWP 110933) "Thread Pool Wor"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94a3b in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000011852d6 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 27 (Thread 0x7f4244b7d640 (LWP 110932) "Thread Pool Wor"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94a3b in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000011852d6 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 26 (Thread 0x7f420c2fe640 (LWP 110931) "Thread Pool Wor"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94a3b in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000011852d6 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 25 (Thread 0x7f4249fff640 (LWP 110930) "Godot_v3.5-stab"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c504 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x000000000120550a in ?? ()
#3  0x0000000001211d01 in ?? ()
#4  0x0000000001185fc3 in ?? ()
#5  0x0000000001191ad7 in ?? ()
#6  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#7  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 24 (Thread 0x7f423c93f640 (LWP 106419) "Godot_v3.5-stab"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x0000000004041bfc in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#3  0x000000000224933b in EditorResourcePreview::_thread() ()
#4  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#5  0x00000000040ab9d0 in ?? ()
#6  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#7  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 23 (Thread 0x7f420c4ff640 (LWP 106411) "Thread Pool I/O"):
#0  0x00007f42b6b0588f in poll () from /lib64/libc.so.6
#1  0x0000000001182700 in ?? ()
#2  0x0000000001183620 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 22 (Thread 0x7f42289fc640 (LWP 106409) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x000000000246a7e1 in EditorFileServer::_thread_start(void*) ()
#3  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#4  0x00000000040ab9d0 in ?? ()
#5  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#6  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 21 (Thread 0x7f42291fd640 (LWP 106406) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x00000000028f4141 in EditorExportPlatformJavaScript::_server_thread_poll(void*) ()
#3  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#4  0x00000000040ab9d0 in ?? ()
#5  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#6  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 20 (Thread 0x7f42299fe640 (LWP 106405) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x00000000028b18a6 in EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) ()
#3  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#4  0x00000000040ab9d0 in ?? ()
#5  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#6  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 19 (Thread 0x7f422a1ff640 (LWP 106404) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x000000000284bd5d in EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) ()
#3  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#4  0x00000000040ab9d0 in ?? ()
#5  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#6  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 18 (Thread 0x7f4266fff640 (LWP 106403) "Finalizer"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a94c50 in __new_sem_wait_slow64.constprop.0 () from /lib64/libc.so.6
#2  0x00000000010bf408 in ?? ()
#3  0x0000000001191ad7 in ?? ()
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 17 (Thread 0x7f42667ff640 (LWP 106402) "SGen worker"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00000000011f386b in ?? ()
#3  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#4  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 16 (Thread 0x7f4275f03640 (LWP 106401) "Godot_v3.5-stab"):
#0  0x00007f42b6b080dc in select () from /lib64/libc.so.6
#1  0x000000000124e8da in OS_X11::_wait_for_events() const ()
#2  0x000000000124ea45 in OS_X11::_poll_events_thread(void*) ()
#3  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#4  0x00000000040ab9d0 in ?? ()
#5  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#6  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 15 (Thread 0x7f4276704640 (LWP 106400) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x00007f42b6b089b9 in usleep () from /lib64/libc.so.6
#3  0x000000000124b29d in JoypadLinux::joypad_events_thread_run() ()
#4  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#5  0x00000000040ab9d0 in ?? ()
#6  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#7  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 14 (Thread 0x7f4276f05640 (LWP 106399) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x00007f42b6b089b9 in usleep () from /lib64/libc.so.6
#3  0x0000000001253fe2 in JoypadLinux::monitor_joypads(udev*) ()
#4  0x0000000001254253 in JoypadLinux::monitor_joypads_thread_run() ()
#5  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#6  0x00000000040ab9d0 in ?? ()
#7  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#8  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 13 (Thread 0x7f4277733640 (LWP 106398) "Godot_v3.5-stab"):
#0  0x00007f42b6ad85b5 in clock_nanosleep@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x00007f42b6adce27 in nanosleep () from /lib64/libc.so.6
#2  0x0000000003ef7a38 in ?? ()
#3  0x0000000001f23783 in AudioDriverPulseAudio::thread_func(void*) ()
#4  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#5  0x00000000040ab9d0 in ?? ()
#6  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#7  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 12 (Thread 0x7f427eee4640 (LWP 106397) "Godot_v3.5-stab"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x0000000004041bfc in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#3  0x0000000003755d9b in VisualServerScene::_gi_probe_bake_thread() ()
#4  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#5  0x00000000040ab9d0 in ?? ()
#6  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#7  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 11 (Thread 0x7f427f7fe640 (LWP 106396) "Godot_v3:gdrv0"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 10 (Thread 0x7f427ffff640 (LWP 106395) "Godot_v3:gdrv0"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 9 (Thread 0x7f429cbf9640 (LWP 106394) "Godot_v3.5:sh5"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 8 (Thread 0x7f429d3fa640 (LWP 106393) "Godot_v3.5:sh4"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 7 (Thread 0x7f429dbfb640 (LWP 106392) "Godot_v3.5:sh3"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 6 (Thread 0x7f429e3fc640 (LWP 106391) "Godot_v3.5:sh2"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 5 (Thread 0x7f429ebfd640 (LWP 106390) "Godot_v3.5:sh1"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 4 (Thread 0x7f429f3fe640 (LWP 106389) "Godot_v3.5:sh0"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 3 (Thread 0x7f429fbff640 (LWP 106388) "Godot_v:disk$0"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x00007f42a68c2c4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#3  0x00007f42a68c289b in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#4  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#5  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 2 (Thread 0x7f42a8f7e640 (LWP 106359) "Godot_v3.5-stab"):
#0  0x00007f42b6a89a19 in __futex_abstimed_wait_common () from /lib64/libc.so.6
#1  0x00007f42b6a8c210 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libc.so.6
#2  0x0000000004041bfc in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
#3  0x0000000003c8d63b in _IP_ResolverPrivate::_thread_function(void*) ()
#4  0x0000000003b97898 in Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*) ()
#5  0x00000000040ab9d0 in ?? ()
#6  0x00007f42b6a8ce2d in start_thread () from /lib64/libc.so.6
#7  0x00007f42b6b121b0 in clone3 () from /lib64/libc.so.6

Thread 1 (Thread 0x7f42b693e7c0 (LWP 106358) "Godot_v3.5-stab"):
#0  0x00007f42b6adcbdf in wait4 () from /lib64/libc.so.6
#1  0x00000000010034ba in ?? ()
#2  0x00000000010035b9 in ?? ()
#3  0x0000000000ff5c6f in ?? ()
#4  0x0000000000f6cad0 in ?? ()
#5  0x000000000100c57b in ?? ()
#6  0x000000000113b4ae in ?? ()
#7  0x000000000113e245 in mono_runtime_invoke ()
#8  0x00000000014900ad in GDMonoMarshal::system_generic_list_to_Array_variant(_MonoObject*, GDMonoClass*, _MonoReflectionType*) ()
#9  0x000000000148f90b in GDMonoMarshal::mono_object_to_variant_impl(_MonoObject*, ManagedType const&, bool) ()
#10 0x000000000148fe8d in GDMonoMarshal::mono_object_to_variant(_MonoObject*) ()
#11 0x00000000017f839e in CSharpScript::_update_exports(PlaceHolderScriptInstance*) ()
#12 0x0000000001800e49 in CSharpScript::reload(bool) ()
#13 0x00000000017faf9a in CSharpLanguage::reload_assemblies(bool) ()
#14 0x0000000001464600 in ?? ()
#15 0x0000000003abbbc9 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#16 0x0000000003ab4c8b in MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) ()
#17 0x0000000003adac80 in MessageQueue::flush() ()
#18 0x0000000002beaa6a in SceneTree::idle(float) ()
#19 0x000000000126010a in Main::iteration() ()
#20 0x0000000001274941 in OS_X11::run() ()
#21 0x0000000000f2597e in main ()
[Inferior 1 (process 106358) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x100c57b):0x100c56b  15 00 83 f8 01 0f 84 0a 07 00 00 49 8b 44 24 08  ...........I.D$.
0x100c57b  80 78 1a 00 0f 84 73 04 00 00 41 0f b7 44 24 02  .x....s...A..D$.
0x100c58b  4d 89 e2 66 25 01 10 66 3d 01 10 0f 84 8c 08 00  M..f%..f=.......
0x100c59b  00 8b 35 0a 10 cf 04 4c 89 d7 4c 89 95 98 fe ff  ..5....L..L.....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
debugger-agent: Unable to listen on 29
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2070)

```

### Steps to reproduce

Run the C# Godot version. If has some issues with C# crashes all program.

**Comment by akien-mga** [comment]
The steps to reproduce aren't very clear, how do you run Godot exactly? Does it crash when you open the project manager? Or when you create and start editing an empty project? Or does it crash on a specific project once you have compiled C# code?

Which Mono version do you have installed and from where?

**Comment by derkork** [comment]
I am seeing the same. The editor crashes when building the project or starting the game. I have this in the console when i try to build:

```
ERROR: Attempted to convert a managed array of unmarshallable element type to Variant.
   at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1032)
ERROR: Attempted to convert a managed array of unmarshallable element type to Variant.
   at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1032)
ERROR: Attempted to convert a managed array of unmarshallable element type to Variant.
   at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1032)
ERROR: Attempted to convert an unmarshallable managed type to Variant. Name: 'StorageType' Encoding: 17.
   at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1124)
ERROR: Attempted to convert a managed array of unmarshallable element type to Variant.
   at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1032)
ERROR: Attempted to convert an unmarshallable managed type to Variant. Name: 'StorageType' Encoding: 17.
   at: (modules/mono/mono_gd/gd_mono_marshal.cpp:1124)

Unhandled Exception:
System.ArgumentException: An element with the same key already exists
Parameter name: key
  at (wrapper managed-to-native) Godot.Collections.Dictionary.godot_icall_Dictionary_Add(intptr,object,object)
  at Godot.Collections.Dictionary`2[TKey,TValue]..ctor (System.Collections.Generic.IDictionary`2[TKey,TValue] dictionary) [0x00053] in <8c99985ff12947baa88b379583357ac3>:0
ERROR: System.ArgumentException: An element with the same key already exists
Parameter name: key
   at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)
ERROR: FATAL: Condition "godot_dict_ctor == nullptr" is true.
   at: system_generic_dict_to_Dictionary (modules/mono/mono_gd/gd_mono_marshal.cpp:1204)
```

**Comment by raulsntos** [comment]
> I am using block-less namespaces in the project. Godot 3.4.4 also complains about not being able to parse them but doesn't crash.

That should no longer be a problem in 3.5, the parser now considers file-scoped namespaces to be valid (implemented by #56427). The crash must be related to something else, it would be more helpful if you could upload a minimal reproduction project.

Judging from the error you posted, it seems to crash because when trying to marshal a Dictionary it can't find the constructor. This is why an MRP would be very useful as I'd like to know what specific type Godot was trying to marshal to try and figure out why it resulted in not finding the constructor and crashing instead of failing and showing an error.

Also, it would've been better to open a new issue instead since OP didn't give many details and we can't know if yours is the same issue they are having.
