### ISSUE TITLE
Unable to close warning popup "Unable to load addon script from path ... This might be due to a code error in that script"

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#65153]
### Godot version

Engine v4.0.alpha.custom_build.736632ee7

### System information

Xubuntu 22.04

### Issue description

Used the --covert-3to4 tool on Zylann's heighmap plugin. Tried to open it in the editor, got warning popup but not able to close it.

![image](https://user-images.githubusercontent.com/4918549/187728369-4baf1848-76cd-4a24-b32f-db0f8e657e2e.png)

Console output:
[g4_warn_console_out.html.txt](https://github.com/godotengine/godot/files/9463259/g4_warn_console_out.html.txt)

Not sure if the backtrace from the main process helps, but here it is:

```
(gdb) bt
#0  futex_wait (private=0, expected=2, futex_word=0x5629eb32c510) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x5629eb32c510, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007fe7322650dd in lll_mutex_lock_optimized (mutex=0x5629eb32c510) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x5629eb32c510) at ./nptl/pthread_mutex_lock.c:128
#4  0x00005629e3a5731c in __gthread_mutex_lock (__mutex=0x5629eb32c510) at /usr/include/x86_64-linux-gnu/c++/11/bits/gthr-default.h:749
#5  __gthread_recursive_mutex_lock (__mutex=0x5629eb32c510) at /usr/include/x86_64-linux-gnu/c++/11/bits/gthr-default.h:811
#6  std::recursive_mutex::lock (this=<optimized out>) at /usr/include/c++/11/mutex:108
#7  MutexImpl<std::recursive_mutex>::lock (this=<optimized out>) at ./core/os/mutex.h:47
#8  MutexLock<MutexImpl<std::recursive_mutex> >::MutexLock (p_mutex=..., this=<optimized out>) at ./core/os/mutex.h:66
#9  GDScriptCache::get_full_script (p_path=..., r_error=@0x7ffd1f737404: 22057, p_owner=...) at modules/gdscript/gdscript_cache.cpp:189
#10 0x00005629e39f5788 in ResourceFormatLoaderGDScript::load (this=<optimized out>, p_path=..., p_original_path=..., r_error=0x562a0c97cb84, p_use_sub_threads=<optimized out>, r_progress=0x562a0c97cb78, 
    p_cache_mode=ResourceFormatLoader::CACHE_MODE_REUSE) at modules/gdscript/gdscript.cpp:2391
#11 0x00005629e7402c80 in ResourceLoader::_load (p_path=..., p_original_path=..., p_type_hint=..., p_cache_mode=ResourceFormatLoader::CACHE_MODE_REUSE, r_error=0x562a0c97cb84, p_use_sub_threads=false, 
    r_progress=0x562a0c97cb78) at core/io/resource_loader.cpp:213
#12 0x00005629e74032d8 in ResourceLoader::_thread_load_function (p_userdata=0x562a0c97cb48) at core/io/resource_loader.cpp:240
#13 0x00005629e740b033 in ResourceLoader::load (p_path=..., p_type_hint=..., p_cache_mode=p_cache_mode@entry=ResourceFormatLoader::CACHE_MODE_REUSE, r_error=r_error@entry=0x0) at core/io/resource_loader.cpp:568
#14 0x00005629e4f47385 in ScriptEditor::set_window_layout (this=0x5629f716a320, p_layout=...) at editor/plugins/script_editor_plugin.cpp:3170
#15 0x00005629e4f48119 in ScriptEditorPlugin::set_window_layout (this=<optimized out>, p_layout=...) at editor/plugins/script_editor_plugin.cpp:4035
#16 0x00005629e53cb547 in EditorData::set_plugin_window_layout (this=this@entry=0x5629edc73170, p_layout=...) at editor/editor_data.cpp:880
#17 0x00005629e47d189d in EditorNode::_load_docks (this=0x5629edc72d80) at editor/editor_node.cpp:4847
#18 0x00005629e47d1ab1 in EditorNode::_sources_changed (this=0x5629edc72d80, p_exist=128) at editor/editor_node.cpp:1080
#19 0x00005629e7783b5d in Object::emit_signalp (this=this@entry=0x5629eea1b3c0, p_name=..., p_args=p_args@entry=0x7ffd1f737b40, p_argcount=p_argcount@entry=1) at core/object/object.cpp:1045
#20 0x00005629e470b361 in Object::emit_signal<bool> (p_name=..., this=0x5629eea1b3c0) at ./core/object/object.h:870
#21 EditorFileSystem::_notification (this=0x5629eea1b3c0, p_what=<optimized out>) at editor/editor_file_system.cpp:1245
#22 0x00005629e77794f8 in Object::notification (this=0x5629eea1b3c0, p_notification=17, p_reversed=<optimized out>) at core/object/object.cpp:790
#23 0x00005629e58090df in SceneTree::_notify_group_pause (this=<optimized out>, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:904
#24 0x00005629e580b3c5 in SceneTree::process (this=0x5629eda03680, p_time=0.14905633333333368) at scene/main/scene_tree.cpp:454
#25 0x00005629e3695607 in Main::iteration () at main/main.cpp:2998
#26 0x00005629e365a791 in OS_LinuxBSD::run (this=this@entry=0x7ffd1f737ee0) at platform/linuxbsd/os_linuxbsd.cpp:538
#27 0x00005629e364c719 in main (argc=<optimized out>, argv=0x7ffd1f738428) at platform/linuxbsd/godot_linuxbsd.cpp:72

```

### Steps to reproduce

Download Zylann's heighmap plugin
Run --convert-3to4 on it
Open the project with Godot 4

**Comment by Calinou** [comment]
I remember encountering this issue last week on a project of mine. I don't remember the exact commit I was running nor the project in question though.

**Comment by KoBeWi** [comment]
Can't reproduce in 4.0 rc3.
The popup *can* be closed.
