### ISSUE TITLE
Executing `MultiMesh.set_buffer` crashes Godot 4 with GLES 3

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#65964]
### Godot version

4.0.alpha.custom_build. 4b164b8e4

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
	var temp_variable1568 = MultiMesh.new()
	temp_variable1568.set_use_custom_data(true)
	temp_variable1568.set_instance_count(63)
	temp_variable1568.set_buffer(PackedFloat32Array([-34.0615577697754, 16.3072357177734, 72.6118927001953, 23.3701820373535, 36.1846084594727, 52.9697532653809, 80.0455932617188, -60.7722778320312, -75.6709136962891, 0, -88.4446563720703, -95.5857696533203, 57.1156387329102, -72.9740600585938, 47.3331680297852, 57.8901901245117, -61.8709106445312, 53.0345916748047, 98.7736358642578, -71.5628433227539, -88.2134552001953, -97.6910247802734, -25.4826774597168, -2.17281579971313, 15.4755830764771]))
```

Godot crashes with this backtrace
```
=================================================================
==23986==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d0008a2750 at pc 0x00000b38f84f bp 0x7fff07283b20 sp 0x7fff07283b10
READ of size 4 at 0x60d0008a2750 thread T0
    #0 0xb38f84e in GLES3::MeshStorage::multimesh_set_buffer(RID, Vector<float> const&) drivers/gles3/storage/mesh_storage.cpp:1321
    #1 0x1840bb23 in RenderingServerDefault::multimesh_set_buffer(RID, Vector<float> const&) servers/rendering/rendering_server_default.h:334
    #2 0x15b3b7fb in MultiMesh::set_buffer(Vector<float> const&) scene/resources/multimesh.cpp:198
    #3 0x15799d0c in void call_with_variant_args_helper<__UnexistingClass, Vector<float> const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:262
    #4 0x1579689a in void call_with_variant_args_dv<__UnexistingClass, Vector<float> const&>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:409
    #5 0x15793648 in MethodBindT<Vector<float> const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:320
    #6 0x1ca93fb0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #7 0x1c05d78d in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #8 0x5c76974 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #9 0x56ae799 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1627
    #10 0x11e04887 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #11 0x11d6a350 in Node::_notification(int) scene/main/node.cpp:56
    #12 0x445ea1f in Node::_notificationv(int, bool) scene/main/node.h:45
    #13 0x1ca9548d in Object::notification(int, bool) core/object/object.cpp:790
    #14 0x11ec4df8 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:917
    #15 0x11eb5ad5 in SceneTree::process(double) scene/main/scene_tree.cpp:465
    #16 0x282bf39 in Main::iteration() main/main.cpp:2992
    #17 0x265ddef in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:538
    #18 0x2644b8f in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #19 0x7f876b3c3d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #20 0x7f876b3c3e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #21 0x264462d in _start (/usr/bin/godot4s+0x264462d)

0x60d0008a2750 is located 0 bytes to the right of 144-byte region [0x60d0008a26c0,0x60d0008a2750)
allocated by thread T0 here:
    #0 0x7f876c014868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x1b46ee35 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x3c91f51 in CowData<float>::_copy_on_write() core/templates/cowdata.h:236
    #3 0x4544450 in CowData<float>::ptrw() core/templates/cowdata.h:124
    #4 0x4532460 in Vector<float>::ptrw() core/templates/vector.h:82
    #5 0xb38d5cf in GLES3::MeshStorage::multimesh_set_buffer(RID, Vector<float> const&) drivers/gles3/storage/mesh_storage.cpp:1293
    #6 0x1840bb23 in RenderingServerDefault::multimesh_set_buffer(RID, Vector<float> const&) servers/rendering/rendering_server_default.h:334
    #7 0x15b3b7fb in MultiMesh::set_buffer(Vector<float> const&) scene/resources/multimesh.cpp:198
    #8 0x15799d0c in void call_with_variant_args_helper<__UnexistingClass, Vector<float> const&, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:262
    #9 0x1579689a in void call_with_variant_args_dv<__UnexistingClass, Vector<float> const&>(__UnexistingClass*, void (__UnexistingClass::*)(Vector<float> const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:409
    #10 0x15793648 in MethodBindT<Vector<float> const&>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:320
    #11 0x1ca93fb0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #12 0x1c05d78d in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #13 0x5c76974 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #14 0x56ae799 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1627
    #15 0x11e04887 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #16 0x11d6a350 in Node::_notification(int) scene/main/node.cpp:56
    #17 0x445ea1f in Node::_notificationv(int, bool) scene/main/node.h:45
    #18 0x1ca9548d in Object::notification(int, bool) core/object/object.cpp:790
    #19 0x11ec4df8 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:917
    #20 0x11eb5ad5 in SceneTree::process(double) scene/main/scene_tree.cpp:465
    #21 0x282bf39 in Main::iteration() main/main.cpp:2992
    #22 0x265ddef in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:538
    #23 0x2644b8f in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #24 0x7f876b3c3d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: heap-buffer-overflow drivers/gles3/storage/mesh_storage.cpp:1321 in GLES3::MeshStorage::multimesh_set_buffer(RID, Vector<float> const&)


```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Run Godot 4 with GLES 3 
```
godot4s --rendering-driver opengl3
```

**Comment by clayjohn** [comment]
Looks like we are missing a proper check to ensure that the input buffer is the right length given the MultiMesh format and the number of instances. 

Such a check should be added here:
https://github.com/godotengine/godot/blob/57bdddce02370af3d13e6edc583afdc17264147d/drivers/gles3/storage/mesh_storage.cpp#L1309-L1313
