### ISSUE TITLE
Executing `MultiMesh.reset_instance_physics_interpolation` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#66749]
### Godot version

3.6.beta.custom_build. 4d4c6c187

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
	var temp_variable45589 = MultiMesh.new()
	temp_variable45589.set_as_bulk_array(PoolRealArray([]))
	temp_variable45589.set_instance_count(65)
	temp_variable45589.set_as_bulk_array_interpolated(PoolRealArray([-85.850731, 15.831614, 49.982857, 74.428024, -8.936996, -38.674648, 68.873062, 82.670914, 10.01687, 79.24881, 82.419228, 17.418909, 49.140095, -38.522045, -31.046564, -11.189342, 69.360329, 52.344704, 2.4876, -50.571735, 90.629234, -95.271378, 77.914093, 76.317169, 42.609619]), PoolRealArray([29.597496, 67.418861, -67.671776, 53.721214, 53.322994, 87.615166, 0, -41.23661, 22.938526, 69.21077, 48.068081, -58.908367, -49.80204, -48.2248, 67.800209, -99.123322, -42.481464, 61.809193, 47.419022, -15.119356, -38.915146, 2.220047, 58.063911, -59.513809, 77.960876]))
	temp_variable45589.reset_instance_physics_interpolation(58)
```

Godot crashes with backtrace
```
ERROR: Condition "!multimesh->data.ptr()" is true.
   at: _multimesh_set_as_bulk_array (drivers/gles3/rasterizer_storage_gles3.cpp:4876)
=================================================================
==49202==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60c000270850 at pc 0x000011a5c79e bp 0x7fff0bf03e50 sp 0x7fff0bf03e40
READ of size 4 at 0x60c000270850 thread T0
    #0 0x11a5c79d in RasterizerStorage::multimesh_instance_reset_physics_interpolation(RID, int) servers/visual/rasterizer.cpp:488
    #1 0x11bafe78 in VisualServerRaster::multimesh_instance_reset_physics_interpolation(RID, int) servers/visual/visual_server_raster.h:290
    #2 0x11e2c44b in VisualServerWrapMT::multimesh_instance_reset_physics_interpolation(RID, int) servers/visual/visual_server_wrap_mt.h:213
    #3 0x102c7d83 in MultiMesh::reset_instance_physics_interpolation(int) scene/resources/multimesh.cpp:230
    #4 0x1d24e46 in MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) core/method_bind.gen.inc:759
    #5 0x12ef7222 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) core/object.cpp:918
    #6 0x131b0576 in Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) core/variant_call.cpp:1236
    #7 0x1f6a04e in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_function.cpp:1050
    #8 0x1d98f27 in GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) modules/gdscript/gdscript.cpp:1211
    #9 0xd09b063 in Node::_notification(int) scene/main/node.cpp:58
    #10 0x1c3f8f9 in Node::_notificationv(int, bool) scene/main/node.h:47
    #11 0x12ef76be in Object::notification(int, bool) core/object.cpp:927
    #12 0xd1f3a3d in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:1105
    #13 0xd1e208a in SceneTree::idle(float) scene/main/scene_tree.cpp:608
    #14 0x1a65065 in Main::iteration() main/main.cpp:2337
    #15 0x192cc57 in OS_X11::run() platform/x11/os_x11.cpp:4035
    #16 0x188812c in main platform/x11/godot_x11.cpp:59
    #17 0x7ff6173a3d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #18 0x7ff6173a3e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #19 0x1887d1d in _start (/usr/bin/godots+0x1887d1d)

Address 0x60c000270850 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow servers/visual/rasterizer.cpp:488 in RasterizerStorage::multimesh_instance_reset_physics_interpolation(RID, int)

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by akien-mga** [comment]
Fixed by #66752.
