### ISSUE TITLE
Executing `TextEdit` functions freeze Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#66937]
### Godot version

4.0.beta.custom_build. b809b6d97

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
func _process(delta: float):
	print(delta)
	var temp_variable115684 = TextEdit.new()
	add_child(temp_variable115684)
	temp_variable115684.set_line_wrapping_mode(49)
	temp_variable115684.set_text("127.0.0.1")
	temp_variable115684.copy()
	temp_variable115684.set_fit_content_height_enabled(true)
	temp_variable115684.paste()
	temp_variable115684.set_scroll_past_end_of_file_enabled(true)
	temp_variable115684.queue_free()
```
Godot freeze inside `CanvasItem::_redraw_callback` function
Gdb backtraces:
```
#0  0x000000000264cb1a in SafeNumeric<unsigned int>::get (this=0x166178d8) at ./core/templates/safe_refcount.h:67
#1  CowData<int>::_copy_on_write (this=0x7fffffffd028) at ./core/templates/cowdata.h:229
#2  0x000000000264a4af in CowData<int>::resize<false> (this=0x7fffffffd028, p_size=15) at ./core/templates/cowdata.h:278
#3  0x00000000026462b8 in Vector<int>::resize (this=0x7fffffffd020, p_size=15) at ./core/templates/vector.h:91
#4  0x00000000026415fa in Vector<int>::push_back (this=0x7fffffffd020, p_elem=5) at ./core/templates/vector.h:313
#5  0x0000000006413007 in draw_ring (verts=..., indices=..., colors=..., style_rect=..., corner_radius=0x7fffffffd0c0, ring_rect=..., inner_rect=..., inner_color=..., outer_color=..., corner_detail=6, 
    skew=..., fill_center=true) at scene/resources/style_box.cpp:653
#6  0x00000000064093d1 in StyleBoxFlat::draw (this=0xf823f40, p_canvas_item=..., p_rect=...) at scene/resources/style_box.cpp:787
#7  0x00000000059a90c7 in ScrollBar::_notification (this=0xfaa6300, p_what=30) at scene/gui/scroll_bar.cpp:313
#8  0x000000000493c240 in ScrollBar::_notificationv (this=0xfaa6300, p_notification=30, p_reversed=false) at scene/gui/scroll_bar.h:37
#9  0x0000000004af24e3 in VScrollBar::_notificationv (this=0xfaa6300, p_notification=30, p_reversed=false) at ./scene/gui/scroll_bar.h:141
#10 0x000000000783bb91 in Object::notification (this=0xfaa6300, p_notification=30, p_reversed=false) at core/object/object.cpp:790
#11 0x00000000055fb67b in CanvasItem::_redraw_callback (this=0xfaa6300) at scene/main/canvas_item.cpp:135
#12 0x00000000044925e9 in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0xfaa6300, 
    p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x55fb5e0 <CanvasItem::_redraw_callback()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:262
#13 0x000000000448fb91 in call_with_variant_args<CanvasItem> (p_instance=0xfaa6300, p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x55fb5e0 <CanvasItem::_redraw_callback()>, p_args=0x0, p_argcount=0, 
    r_error=...) at ./core/variant/binder_common.h:376
#14 0x000000000448c59c in CallableCustomMethodPointer<CanvasItem>::call (this=0xfc4c0b0, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#15 0x00000000074e6eb5 in Callable::callp (this=0x7fffe29772b8, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#16 0x0000000007835417 in MessageQueue::_call_function (this=0xc221ac0, p_callable=..., p_args=0x7fffe29772d0, p_argcount=0, p_show_error=false) at core/object/message_queue.cpp:229
#17 0x0000000007835778 in MessageQueue::flush (this=0xc221ac0) at core/object/message_queue.cpp:275
#18 0x00000000056a4de1 in SceneTree::process (this=0xf887b10, p_time=0.14925633333333335) at scene/main/scene_tree.cpp:468
#19 0x000000000267100f in Main::iteration () at main/main.cpp:3135
#20 0x0000000002614248 in OS_LinuxBSD::run (this=0x7fffffffd8f0) at platform/linuxbsd/os_linuxbsd.cpp:575
#21 0x000000000260dc55 in main (argc=2, argv=0x7fffffffde38) at platform/linuxbsd/godot_linuxbsd.cpp:72

```
```
#0  0x0000000005a33b81 in TextEdit::Text::size (this=0xfd68bb8) at scene/gui/text_edit.h:211
#1  0x00000000059fce83 in TextEdit::_notification (this=0xfd68280, p_what=30) at scene/gui/text_edit.cpp:885
#2  0x000000000579c900 in TextEdit::_notificationv (this=0xfd68280, p_notification=30, p_reversed=false) at scene/gui/text_edit.h:42
#3  0x000000000783bb91 in Object::notification (this=0xfd68280, p_notification=30, p_reversed=false) at core/object/object.cpp:790
#4  0x00000000055fb67b in CanvasItem::_redraw_callback (this=0xfd68280) at scene/main/canvas_item.cpp:135
#5  0x00000000044925e9 in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0xfd68280, 
    p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x55fb5e0 <CanvasItem::_redraw_callback()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:262
#6  0x000000000448fb91 in call_with_variant_args<CanvasItem> (p_instance=0xfd68280, p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x55fb5e0 <CanvasItem::_redraw_callback()>, p_args=0x0, p_argcount=0, 
    r_error=...) at ./core/variant/binder_common.h:376
#7  0x000000000448c59c in CallableCustomMethodPointer<CanvasItem>::call (this=0x156a4a70, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#8  0x00000000074e6eb5 in Callable::callp (this=0x7fffe28f9240, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#9  0x0000000007835417 in MessageQueue::_call_function (this=0xc221ac0, p_callable=..., p_args=0x7fffe28f9258, p_argcount=0, p_show_error=false) at core/object/message_queue.cpp:229
#10 0x0000000007835778 in MessageQueue::flush (this=0xc221ac0) at core/object/message_queue.cpp:275
#11 0x00000000056a4de1 in SceneTree::process (this=0xf887b10, p_time=0.14925633333333335) at scene/main/scene_tree.cpp:468
#12 0x000000000267100f in Main::iteration () at main/main.cpp:3135
#13 0x0000000002614248 in OS_LinuxBSD::run (this=0x7fffffffd8f0) at platform/linuxbsd/os_linuxbsd.cpp:575
#14 0x000000000260dc55 in main (argc=2, argv=0x7fffffffde38) at platform/linuxbsd/godot_linuxbsd.cpp:72
```
```
#0  CowData<char32_t>::_get_refcount (this=0x12bb0768) at ./core/templates/cowdata.h:73
#1  0x000000000260f425 in CowData<char32_t>::_ref (this=0x7fffffffd0b8, p_from=...) at ./core/templates/cowdata.h:405
#2  0x000000000260f26d in String::operator= (this=0x7fffffffd0b8, p_str=...) at ./core/string/ustring.h:451
#3  0x0000000004212219 in RenderingDeviceVulkan::_free_internal (this=0xcab5340, p_id=...) at drivers/vulkan/rendering_device_vulkan.cpp:8763
#4  0x0000000004212ddc in RenderingDeviceVulkan::free (this=0xcab5340, p_id=...) at drivers/vulkan/rendering_device_vulkan.cpp:8849
#5  0x00000000070c8672 in RendererCanvasRenderRD::free_polygon (this=0xd34b8b0, p_polygon=55170) at servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:340
#6  0x0000000007069479 in RendererCanvasRender::Polygon::~Polygon (this=0x1401a4e8, __in_chrg=<optimized out>) at ./servers/rendering/renderer_canvas_render.h:154
#7  0x000000000707b868 in RendererCanvasRender::Item::CommandPolygon::~CommandPolygon (this=0x1401a4d0, __in_chrg=<optimized out>) at ./servers/rendering/renderer_canvas_render.h:228
#8  0x000000000706af2e in memdelete<RendererCanvasRender::Item::Command> (p_class=0x1401a4d0) at ./core/os/memory.h:109
#9  0x0000000007069a5c in RendererCanvasRender::Item::clear (this=0xfd4f690) at ./servers/rendering/renderer_canvas_render.h:415
#10 0x000000000706614f in RendererCanvasCull::canvas_item_clear (this=0xcd75df0, p_item=...) at servers/rendering/renderer_canvas_cull.cpp:1502
#11 0x0000000006b25af4 in RenderingServerDefault::canvas_item_clear (this=0xcd63100, p1=...) at servers/rendering/rendering_server_default.h:862
#12 0x00000000055fb63f in CanvasItem::_redraw_callback (this=0xfaa6300) at scene/main/canvas_item.cpp:130
#13 0x00000000044925e9 in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0xfaa6300, 
    p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x55fb5e0 <CanvasItem::_redraw_callback()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:262
#14 0x000000000448fb91 in call_with_variant_args<CanvasItem> (p_instance=0xfaa6300, p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x55fb5e0 <CanvasItem::_redraw_callback()>, p_args=0x0, p_argcount=0, 
    r_error=...) at ./core/variant/binder_common.h:376
#15 0x000000000448c59c in CallableCustomMethodPointer<CanvasItem>::call (this=0xfc4c0b0, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#16 0x00000000074e6eb5 in Callable::callp (this=0x7fffe2849530, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#17 0x0000000007835417 in MessageQueue::_call_function (this=0xc221ac0, p_callable=..., p_args=0x7fffe2849548, p_argcount=0, p_show_error=false) at core/object/message_queue.cpp:229
#18 0x0000000007835778 in MessageQueue::flush (this=0xc221ac0) at core/object/message_queue.cpp:275
#19 0x00000000056a4de1 in SceneTree::process (this=0xf887b10, p_time=0.14925633333333335) at scene/main/scene_tree.cpp:468
#20 0x000000000267100f in Main::iteration () at main/main.cpp:3135
#21 0x0000000002614248 in OS_LinuxBSD::run (this=0x7fffffffd8f0) at platform/linuxbsd/os_linuxbsd.cpp:575
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by Mickeon** [comment]
Interestingly, a workaround to this is by waiting with an "`await get_tree().process`" before `temp_variable115684.set_scroll_past_end_of_file_enabled(true)`. The Textedit's Scrollbar may be fully loaded a bit too late.

**Comment by qarmin** [comment]
Cannot reproduce
