### ISSUE TITLE
Executing `GPUParticlesCollisionHeightField3D.set_follow_camera_enabled` freeze Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#66986]
### Godot version

4.0.beta.custom_build. b809b6d97

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
func _process(delta) -> void:
	print("AAAAA")
	
	var temp_variable377464 = Camera3D.new()
	add_child(temp_variable377464)

	var temp_variable377558 = GPUParticlesCollisionHeightField3D.new()
	add_child(temp_variable377558)
	temp_variable377558.set_basis(Basis(Vector3(0.27226126194, -0.77507317066193, -0.57020646333694), Vector3(-0.58526027202606, -0.62486499547958, 0.51673418283463), Vector3(81.6701049804688, -90.2818756103516, 68.8228759765625)))
	temp_variable377558.set_follow_camera_enabled(true)
```

Godot freezes here
```
Thread 1 "godot4" received signal SIGINT, Interrupt.
0x0000000002afaea7 in Vector3::operator- (this=0x7fffffffd548, p_v=...) at ./core/math/vector3.h:325
325	./core/math/vector3.h: No such file or directory.
(gdb) backtrace
#0  0x0000000002afaea7 in Vector3::operator- (this=0x7fffffffd548, p_v=...) at ./core/math/vector3.h:325
#1  0x0000000005b86072 in GPUParticlesCollisionHeightField3D::_notification (this=0xfb62440, p_what=25)
    at scene/3d/gpu_particles_collision_3d.cpp:648
#2  0x0000000005b8dd9e in GPUParticlesCollisionHeightField3D::_notificationv (this=0xfb62440, 
    p_notification=25, p_reversed=false) at scene/3d/gpu_particles_collision_3d.h:201
#3  0x000000000783bb91 in Object::notification (this=0xfb62440, p_notification=25, p_reversed=false)
    at core/object/object.cpp:790
#4  0x00000000056a6a8b in SceneTree::_notify_group_pause (this=0xf89e700, p_group=..., 
    p_notification=25) at scene/main/scene_tree.cpp:867
#5  0x00000000056a4da5 in SceneTree::process (this=0xf89e700, p_time=0.0075493333333333575)
    at scene/main/scene_tree.cpp:464
#6  0x000000000267100f in Main::iteration () at main/main.cpp:3135
#7  0x0000000002614248 in OS_LinuxBSD::run (this=0x7fffffffd8d0)
    at platform/linuxbsd/os_linuxbsd.cpp:575
#8  0x000000000260dc55 in main (argc=2, argv=0x7fffffffde18) at platform/linuxbsd/godot_linuxbsd.cpp:72
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Not crashes
