### ISSUE TITLE
[.NET] The editor crashes when using generic subclasses of RefCounted as the signal parameters

### ISSUE THREAD

**Issue by wizcas** [godotengine/godot#67537]
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

Windows11, Forward+, 3080 Ti

### Issue description

I was programming in C# and wanted to bundle the signal context in a custom class for both simplicity and extensibility. So I defined a generic class that inherits `RefCounted`, for the data will be temporary and I don't mean to manage freeing its memory manually.

But such implementation will crash Godot editor, saying `Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true`. The crash happens when loading the project and it's silent.

It is also weird that after I removed the signal, reloaded the project, and added the signal back, the issue seemed gone. So I had to create another demo project for this issue submission. 

Another potential error is that using generic signal parameters will likely to crash the game nevertheless because of some memory freeing issue. I'm not sure if it's relevant to the error described in this issue, but the problem was gone after I removed all the generic signal parameters.

---

The core code is basically like:

```csharp
public partial class Data<T> : RefCounted {...}

public partial class MyNode : Node {
  [Signal] public delegate void Foo(Data<string> data);

  ...
}
```

### Steps to reproduce

1. Open Godot 4.0 beta 3 via CLI with arguments `--editor --verbose`.
2. Import and select the attached project.
3. The editor crashes with this error printed in the terminal:
  ```
ERROR: System.InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Godot.Bridge.ScriptManagerBridge.GetMethodListForType(Type type) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 761
   at Godot.Bridge.ScriptManagerBridge.UpdateScriptClassInfo(IntPtr scriptPtr, godot_bool* outTool, godot_array* outMethodsDest, godot_dictionary* outRpcFunctionsDest, godot_dictionary* outEventSignalsDest, godot_ref* outBaseScript) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 593
   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1234)

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(IntPtr)
   at Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string*, Godot.NativeInterop.godot_ref*)
  ```

### Minimal reproduction project

[bug-dotnet-generic-param.zip](https://github.com/godotengine/godot/files/9801351/bug-dotnet-generic-param.zip)

**Comment by MrZak-dev** [comment]
Is there any way to know which type or script is causing the editor to crash ,

```pws
Found .NET Sdk version '6.0.402': C:\Program Files\dotnet\sdk\6.0.402
Loaded builtin certs
Creating VMA small objects pool for memory type index 3
EditorSettings: Save OK!
ERROR: System.InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Godot.Bridge.ScriptManagerBridge.GetMethodListForType(Type type) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 761
   at Godot.Bridge.ScriptManagerBridge.UpdateScriptClassInfo(IntPtr scriptPtr, godot_bool* outTool, godot_array* outMethodsDest, godot_dictionary* outRpcFunctionsDest, godot_dictionary* outEventSignalsDest, godot_ref* outBaseScript) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 593
   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1240)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(IntPtr)
   at Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string*, Godot.NativeInterop.godot_ref*)
  ```

i am having the same issue and i am using Generics with Godot nodes as well .
it was working the first time then suddenly stopped after implementing a class that receives 2 Generics types .

i've tried to comment out the whole class script but its still crashing .

any idea how to know where the issue is coming from ?

**Comment by MrZak-dev** [comment]
Note : Sometimes CLEAN SOLUTION -> REBUILD SOLUTION and then opening the editor silents this issue .

**Comment by MrZak-dev** [comment]
@Calinou i suggest changing the issue name cause it seems this is happening for all godot types being inherited to uses generics and not only `RefCounted`  .

**Comment by valkyrienyanko** [comment]
Try switching to Godot 4 Beta 8 as that's what fixed it for me although might not be 100% related to your issue. Who knows give it a try :)

**Comment by KokeBlacksmith** [comment]
I am in beta 10 and keeps happening
