### ISSUE TITLE
Executing `Image.save_jpg_to_buffer` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#67586]
### Godot version

4.0.beta.custom_build. 39534a7ae

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
	var temp_variable9 = Image.new()
	temp_variable9.crop(81, 47)
	temp_variable9.save_jpg_to_buffer(-55.1558017730713)
```
Godot crashes with this backtrace

```
=================================================================
==263411==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62100052e110 at pc 0x0000074a3a9a bp 0x7ffd092fa850 sp 0x7ffd092fa840
READ of size 1 at 0x62100052e110 thread T0
    #0 0x74a3a99 in RGB_to_YCC thirdparty/jpeg-compressor/jpge.cpp:96
    #1 0x74bbc92 in jpge::jpeg_encoder::load_mcu(void const*) thirdparty/jpeg-compressor/jpge.cpp:861
    #2 0x74bd4fc in jpge::jpeg_encoder::process_scanline(void const*) thirdparty/jpeg-compressor/jpge.cpp:929
    #3 0x74a2669 in _jpgd_buffer_save_func modules/jpg/image_loader_jpegd.cpp:178
    #4 0x1c630e45 in Image::save_jpg_to_buffer(float) const core/io/image.cpp:2449
    #5 0x1c722516 in void call_with_variant_args_retc_helper<__UnexistingClass, Vector<unsigned char>, float, 0ul>(__UnexistingClass*, Vector<unsigned char> (__UnexistingClass::*)(float) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:731
    #6 0x1c70cff1 in void call_with_variant_args_retc_dv<__UnexistingClass, Vector<unsigned char>, float>(__UnexistingClass*, Vector<unsigned char> (__UnexistingClass::*)(float) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:526
    #7 0x1c6fb044 in MethodBindTRC<Vector<unsigned char>, float>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:544
    #8 0x1d7d9334 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #9 0x1cd93cdd in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #10 0x5d846b2 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #11 0x57bd7c5 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1629
    #12 0x12b53839 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #13 0x12abe920 in Node::_notification(int) scene/main/node.cpp:56
    #14 0x4568455 in Node::_notificationv(int, bool) scene/main/node.h:45
    #15 0x1d7da811 in Object::notification(int, bool) core/object/object.cpp:790
    #16 0x12c13e76 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:868
    #17 0x12c06b5d in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #18 0x283ff52 in Main::iteration() main/main.cpp:3137
    #19 0x266707b in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:772
    #20 0x26453f3 in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #21 0x7f6bf60dad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #22 0x7f6bf60dae3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #23 0x2644e9d in _start (/usr/bin/godot4s+0x2644e9d)

0x62100052e110 is located 0 bytes to the right of 4112-byte region [0x62100052d100,0x62100052e110)
allocated by thread T0 here:
    #0 0x7f6bf6d2b868 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x1c123199 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x3cc90d3 in Error CowData<unsigned char>::resize<false>(int) core/templates/cowdata.h:288
    #3 0x3bcfc82 in Vector<unsigned char>::resize(int) core/templates/vector.h:91
    #4 0x1c6282c0 in Image::initialize_data(int, int, bool, Image::Format) core/io/image.cpp:2083
    #5 0x1c6354b6 in Image::Image(int, int, bool, Image::Format) core/io/image.cpp:2587
    #6 0x1c60f70b in Image::crop_from_point(int, int, int, int) core/io/image.cpp:1309
    #7 0x1c610787 in Image::crop(int, int) core/io/image.cpp:1339
    #8 0x5654d37 in void call_with_variant_args_helper<__UnexistingClass, int, int, 0ul, 1ul>(__UnexistingClass*, void (__UnexistingClass::*)(int, int), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul>) core/variant/binder_common.h:262
    #9 0x564ac76 in void call_with_variant_args_dv<__UnexistingClass, int, int>(__UnexistingClass*, void (__UnexistingClass::*)(int, int), Variant const**, int, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:409
    #10 0x5642a20 in MethodBindT<int, int>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:320
    #11 0x1d7d9334 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #12 0x1cd93cdd in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #13 0x5d846b2 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #14 0x57bd7c5 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1629
    #15 0x12b53839 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #16 0x12abe920 in Node::_notification(int) scene/main/node.cpp:56
    #17 0x4568455 in Node::_notificationv(int, bool) scene/main/node.h:45
    #18 0x1d7da811 in Object::notification(int, bool) core/object/object.cpp:790
    #19 0x12c13e76 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:868
    #20 0x12c06b5d in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #21 0x283ff52 in Main::iteration() main/main.cpp:3137
    #22 0x266707b in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:772
    #23 0x26453f3 in main platform/linuxbsd/godot_linuxbsd.cpp:72
    #24 0x7f6bf60dad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: heap-buffer-overflow thirdparty/jpeg-compressor/jpge.cpp:96 in RGB_to_YCC

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by qarmin** [comment]
This should be visible with Godot compiled with Address Sanitizer(LLVM for windows or MSVC should have option to do this)

**Comment by qarmin** [comment]
No longer crashes
