### ISSUE TITLE
AnimationNodeBlendTreeEditor crash on _node_renamed_focus_out

### ISSUE THREAD

**Issue by Begah** [godotengine/godot#67941]
### Godot version

4.0 dev

### System information

Linux mint, vulkan, mobile renderer

### Issue description

The crash doesn't happen 100% of the time, but when using an animation blend tree, when adding different nodes and renaming them, there is a high likelihood of a crash.

### Steps to reproduce

Create a new project.
In the main scene, add a animation tree, no need to link it to a player, create a blend tree as root and add a node, or some, and rename them and validate by pressing enter.
On average it crashes after rename 1-2, so very high crash rate.

I did some debugging, first of all here is the stacktrace :
``` cpp
(gdb) backtrace
#0  0x000055555b8a4706 in __dynamic_cast ()
#1  0x0000555558db2755 in Object::cast_to<Node> (p_object=<optimized out>) at ./core/object/object.h:737
#2  VariantObjectClassChecker<Node*>::check (p_variant=...) at ./core/variant/binder_common.h:189
#3  VariantCasterAndValidate<Node*>::cast (r_error=..., p_arg_idx=0, p_args=0x7fffffffd4d0) at ./core/variant/binder_common.h:215
#4  call_with_variant_args_helper<AnimationNodeBlendTreeEditor, Node*, Ref<AnimationNode>, 0ul, 1ul> (p_instance=<optimized out>, p_method=<optimized out>, p_args=p_args@entry=0x7fffffffd4d0, r_error=...)
    at ./core/variant/binder_common.h:262
#5  0x0000555558db281a in call_with_variant_args<AnimationNodeBlendTreeEditor, Node*, Ref<AnimationNode> > (p_instance=<optimized out>, p_method=<optimized out>, p_args=p_args@entry=0x7fffffffd4d0, p_argcount=p_argcount@entry=2, 
    r_error=...) at ./core/variant/binder_common.h:362
#6  0x0000555558db28e1 in CallableCustomMethodPointer<AnimationNodeBlendTreeEditor, Node*, Ref<AnimationNode> >::call (this=0x5555735f5ff0, p_arguments=0x7fffffffd4d0, p_argcount=2, r_return_value=..., r_call_error=...)
    at ./core/object/object.h:973
#7  0x000055555b2035dc in Callable::callp (this=<optimized out>, p_arguments=p_arguments@entry=0x7fffffffd4d0, p_argcount=<optimized out>, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#8  0x000055555b205dd1 in CallableCustomBind::call (this=<optimized out>, p_arguments=<optimized out>, p_argcount=<optimized out>, r_return_value=..., r_call_error=...) at ./core/templates/cowdata.h:130
#9  0x000055555b2035dc in Callable::callp (this=this@entry=0x7ffff233c290, p_arguments=p_arguments@entry=0x0, p_argcount=p_argcount@entry=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#10 0x000055555b503181 in MessageQueue::_call_function (this=this@entry=0x55555e4ea0a0, p_callable=..., p_args=p_args@entry=0x7ffff233c2a8, p_argcount=0, p_show_error=<optimized out>) at core/object/message_queue.cpp:229
#11 0x000055555b50348e in MessageQueue::flush (this=0x55555e4ea0a0) at core/object/message_queue.cpp:275
#12 0x00005555590c23a5 in SceneTree::process (this=0x555560906af0, p_time=0.0069444444444444449) at scene/main/scene_tree.cpp:461
#13 0x0000555556b914b0 in Main::iteration () at main/main.cpp:3137
#14 0x0000555556b4cf44 in OS_LinuxBSD::run (this=0x7fffffffd7d0) at platform/linuxbsd/os_linuxbsd.cpp:772
#15 0x0000555556b4ac0f in main (argc=<optimized out>, argv=0x7fffffffdd08) at platform/linuxbsd/godot_linuxbsd.cpp:72
```
After a bit of time and trying to understand why and why, i discovered that the problem was with line 156 of `editor/plugins/animation_blend_tree_editor_plugin.cpp`

``` cpp
name->connect("focus_exited", callable_mp(this, &AnimationNodeBlendTreeEditor::_node_renamed_focus_out).bind(name, agnode), CONNECT_DEFERRED);
```

Parameter 'name' is a LineEdit node, and adding a `std::cout` during a `LineEdit` predelete notification and using gdb, i found out that the crash was happening because when the callable was invoked, the parameter name was already deleted.

I may try and correct the bug later, but i am not yet familiar enough with the animationodeblendertreeeditor to presume why it is delete and then invoked.

### Minimal reproduction project

None

**Comment by Begah** [comment]
I don't know if it's related, but it seems a lineedit can be delete(predeleted notification) multiple times:
```
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
Deleting ledit :0x5652501e9110
```

I observed this, not sure why it's even possible but could be related to the issue
