### ISSUE TITLE
Executing `TextParagraph.get_line_width` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#68156]
### Godot version

4.0.beta.custom_build. 0a0e99cad

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
extends Node
func _process(delta):
	for i in get_children():
		i.queue_free()

	var temp_variable30062 = TextParagraph.new()
	temp_variable30062.add_object(Array([Array([]), 95, Array([]), Array([]), Array([]), 41, Array([]), Array([]), Array([]), 23, Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), 90, 91, Array([]), 32, Array([])]), Vector2(0.51662921905518, 97.6063690185547), -92, 99)
	temp_variable30062.set_break_flags(-47)
	temp_variable30062.add_string("4168385474", SystemFont.new(), 41, "434091636", null)
	temp_variable30062.get_line_underline_thickness(-90)
	temp_variable30062.tab_align(PackedFloat32Array([-16.4931602478027, 57.6517448425293, -48.517505645752, -45.9478492736816, 57.1488723754883, 86.8194961547852, -13.2323265075684, -12.3681964874268, -58.3446044921875, 78.6202926635742, -26.5594596862793, 76.9443511962891, -75.6126937866211, -43.1199073791504, 21.5534687042236, 79.8407897949219, 47.1968154907227, -96.3269195556641, 56.7427024841309, 41.7922019958496, -62.6574592590332, -34.444206237793, -29.2343444824219, -75.437255859375, 72.4658126831055]))
	temp_variable30062.get_line_object_rect(-76, Array([Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([])]))
	temp_variable30062.set_orientation(84)
	temp_variable30062.add_object(Array([Array([]), Array([]), 97, Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([]), Array([])]), Vector2(0.70393037796021, 0.7102689743042), 60, -69)
	temp_variable30062.get_line_width(-52)


```
Godot crashes with this backtrace

```
==28130==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x612000dd3900 at pc 0x00000b498dec bp 0x7fff97eccd10 sp 0x7fff97eccd00
READ of size 4 at 0x612000dd3900 thread T0
    #0 0xb498deb in TextServerAdvanced::_shaped_text_update_breaks(RID const&) modules/text_server_adv/text_server_adv.cpp:4668
    #1 0xb48edca in TextServerAdvanced::_shaped_text_tab_align(RID const&, Vector<float> const&) modules/text_server_adv/text_server_adv.cpp:4331
    #2 0xb4ecc06 in TextServerAdvanced::shaped_text_tab_align(RID const&, Vector<float> const&) (/usr/bin/godot4s+0xb4ecc06)
    #3 0x17c08a02 in TextParagraph::_shape_lines() scene/resources/text_paragraph.cpp:184
    #4 0x17c2b3bc in TextParagraph::get_line_width(int) const scene/resources/text_paragraph.cpp:668
    #5 0x152da857 in void call_with_variant_args_retc_helper<__UnexistingClass, float, int, 0ul>(__UnexistingClass*, float (__UnexistingClass::*)(int) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:731
    #6 0x152d5dc4 in void call_with_variant_args_retc_dv<__UnexistingClass, float, int>(__UnexistingClass*, float (__UnexistingClass::*)(int) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:526
    #7 0x152d0ae7 in MethodBindTRC<float, int>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:544
    #8 0x1e503fd6 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #9 0x1d9ccbd6 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #10 0x5f8310c in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #11 0x5981e40 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1634
    #12 0x13315600 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #13 0x1327c0fa in Node::_notification(int) scene/main/node.cpp:56
    #14 0x46a2ba7 in Node::_notificationv(int, bool) scene/main/node.h:45
    #15 0x1e50552a in Object::notification(int, bool) core/object/object.cpp:790
    #16 0x133daa9d in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:868
    #17 0x133cd259 in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #18 0x288f570 in Main::iteration() main/main.cpp:3170
    #19 0x26a7029 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:776
    #20 0x2684278 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #21 0x7f6098058d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #22 0x7f6098058e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #23 0x2683c34 in _start (/usr/bin/godot4s+0x2683c34)

0x612000dd3900 is located 176 bytes to the right of 272-byte region [0x612000dd3740,0x612000dd3850)
allocated by thread T0 here:
    #0 0x7f6098c44867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x1cd036df in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0xaf4ff6a in Error CowData<char32_t>::resize<false>(int) core/templates/cowdata.h:288
    #3 0xbcf9933 in String::resize(int) core/string/ustring.h:216
    #4 0x1e73055f in String::copy_from_unchecked(char32_t const*, int) core/string/ustring.cpp:454
    #5 0x1e74b4f1 in String::substr(int, int) const core/string/ustring.cpp:2820
    #6 0xb483800 in TextServerAdvanced::_shape_substr(TextServerAdvanced::ShapedTextDataAdvanced*, TextServerAdvanced::ShapedTextDataAdvanced const*, long, long) const modules/text_server_adv/text_server_adv.cpp:4062
    #7 0xb48294e in TextServerAdvanced::_shaped_text_substr(RID const&, long, long) const modules/text_server_adv/text_server_adv.cpp:4041
    #8 0xb4ec4e3 in TextServerAdvanced::shaped_text_substr(RID const&, long, long) const (/usr/bin/godot4s+0xb4ec4e3)
    #9 0x17c08647 in TextParagraph::_shape_lines() scene/resources/text_paragraph.cpp:182
    #10 0x17c2b3bc in TextParagraph::get_line_width(int) const scene/resources/text_paragraph.cpp:668
    #11 0x152da857 in void call_with_variant_args_retc_helper<__UnexistingClass, float, int, 0ul>(__UnexistingClass*, float (__UnexistingClass::*)(int) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:731
    #12 0x152d5dc4 in void call_with_variant_args_retc_dv<__UnexistingClass, float, int>(__UnexistingClass*, float (__UnexistingClass::*)(int) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:526
    #13 0x152d0ae7 in MethodBindTRC<float, int>::call(Object*, Variant const**, int, Callable::CallError&) core/object/method_bind.h:544
    #14 0x1e503fd6 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #15 0x1d9ccbd6 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1048
    #16 0x5f8310c in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #17 0x5981e40 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1634
    #18 0x13315600 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #19 0x1327c0fa in Node::_notification(int) scene/main/node.cpp:56
    #20 0x46a2ba7 in Node::_notificationv(int, bool) scene/main/node.h:45
    #21 0x1e50552a in Object::notification(int, bool) core/object/object.cpp:790
    #22 0x133daa9d in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:868
    #23 0x133cd259 in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #24 0x288f570 in Main::iteration() main/main.cpp:3170
    #25 0x26a7029 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:776
    #26 0x2684278 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #27 0x7f6098058d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: heap-buffer-overflow modules/text_server_adv/text_server_adv.cpp:4668 in TextServerAdvanced::_shaped_text_update_breaks(RID const&)

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Cannot reproduce
