### ISSUE TITLE
Material import regression in 4.0 beta 6

### ISSUE THREAD

**Issue by fire** [godotengine/godot#69094]
### Godot version

fa270c2456df5ad12f51584c4ff891e2cf728cec

### System information

Windows 11, Nvidia 3000

### Issue description

Launch project as a game template from github actions for windows.

```
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
     at: _get (core/config/project_settings.cpp:348)
WARNING: Property not found: debug/gdscript/warnings/enable
Exception thrown: read access violation.
**this** was nullptr.
```

![image](https://user-images.githubusercontent.com/32321/203699998-578a6349-2cd1-4608-a36c-33421bdbbba9.png)

(Custom build photo).
### Steps to reproduce

1. Launch the project as a game
2. drag .vrm file into the game window
3. crash

### Minimal reproduction project

https://github.com/V-Sekai-fire/VSK_model_explorer/commit/a1d418645f45b15959ab9cc533d71c60b5b89d7c

[AliciaSolid_vrm-0.51.zip](https://github.com/godotengine/godot/files/10080996/AliciaSolid_vrm-0.51.zip)

**Comment by akien-mga** [comment]
I can reproduce the crash, but it's not related at all to this GDScript warning.

I can confirm that it's reproducible in 4.0 beta 6 and current `master`, and not in 4.0 beta 5, so it's a recent regression.

gdb stacktrace in plain text:
```
0x0000000005229b45 in Object::get (this=0x0, p_name=..., r_valid=0x0) at core/object/object.cpp:309
309             if (script_instance) {
(gdb) bt
#0  0x0000000005229b45 in Object::get (this=0x0, p_name=..., r_valid=0x0) at core/object/object.cpp:309
#1  0x000000000522fe05 in Object::_get_bind (this=0x0, p_name=...) at core/object/object.cpp:1356
#2  0x0000000003ad165b in call_with_variant_args_retc_helper<__UnexistingClass, Variant, StringName const&, 0ul> (p_instance=0x0, 
    p_method=(Variant (__UnexistingClass::*)(const __UnexistingClass * const, const StringName &)) 0x522fdd8 <Object::_get_bind(StringName const&) const>, p_args=0x7fffd57f6088, r_ret=..., r_error=...)
    at ./core/variant/binder_common.h:733
#3  0x0000000003ad0804 in call_with_variant_args_retc_dv<__UnexistingClass, Variant, StringName const&> (p_instance=0x0, 
    p_method=(Variant (__UnexistingClass::*)(const __UnexistingClass * const, const StringName &)) 0x522fdd8 <Object::_get_bind(StringName const&) const>, p_args=0x7fffd57f6230, p_argcount=1, r_ret=..., r_error=..., 
    default_values=...) at ./core/variant/binder_common.h:526
#4  0x0000000003acfa9a in MethodBindTRC<Variant, StringName const&>::call (this=0x772b310, p_object=0x0, p_args=0x7fffd57f6230, p_arg_count=1, r_error=...) at ./core/object/method_bind.h:544
#5  0x000000000236bb1e in GDScriptFunction::call (this=0x9f64ed0, p_instance=0x0, p_args=0x7fffb06a1010, p_argcount=3, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1644
#6  0x0000000002312ba3 in GDScriptLambdaCallable::call (this=0x7fffb06a0880, p_arguments=0x7fffd57f8b18, p_argcount=2, r_return_value=..., r_call_error=...) at modules/gdscript/gdscript_lambda_callable.cpp:82
#7  0x0000000004f65feb in Callable::callp (this=0x7fffd57f8898, p_arguments=0x7fffd57f8b18, p_argcount=2, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#8  0x000000000509566d in _VariantCall::func_Callable_call (v=0x7fffd57f8890, p_args=0x7fffd57f8b18, p_argcount=2, r_ret=..., r_error=...) at core/variant/variant_call.cpp:898
#9  0x0000000004fbaf49 in Method_Callable_call::call (base=0x7fffd57f8890, p_args=0x7fffd57f8b18, p_argcount=2, r_ret=..., p_defvals=..., r_error=...) at core/variant/variant_call.cpp:1876
#10 0x0000000004f88527 in Variant::callp (this=0x7fffd57f8890, p_method=..., p_args=0x7fffd57f8b18, p_argcount=2, r_ret=..., r_error=...) at core/variant/variant_call.cpp:1060
#11 0x000000000236b98e in GDScriptFunction::call (this=0xa2ef070, p_instance=0xa004f70, p_args=0x7fffd57fb3f8, p_argcount=2, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1555
#12 0x000000000227a8c1 in GDScriptInstance::callp (this=0xa004f70, p_method=..., p_args=0x7fffd57fb3f8, p_argcount=2, r_error=...) at modules/gdscript/gdscript.cpp:1827
#13 0x000000000522b4d1 in Object::callp (this=0x9e5f130, p_method=..., p_args=0x7fffd57fb3f8, p_argcount=2, r_error=...) at core/object/object.cpp:711
#14 0x0000000004f66267 in Callable::callp (this=0x9f54a08, p_arguments=0x7fffd57fb3f8, p_argcount=2, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:62
#15 0x000000000522d0c9 in Object::emit_signalp (this=0xa5a35d0, p_name=..., p_args=0x7fffd57fb3f8, p_argcount=2) at core/object/object.cpp:1046
#16 0x0000000004f688f2 in Signal::emit (this=0x7fffd57fb3e8, p_arguments=0x7fffd57fb3f8, p_argcount=2) at core/variant/callable.cpp:401
#17 0x00000000050958d1 in _VariantCall::func_Signal_emit (v=0x7fffd57fb3e0, p_args=0x7fffd57fb3f8, p_argcount=2, r_ret=..., r_error=...) at core/variant/variant_call.cpp:934
#18 0x0000000004fbd42e in Method_Signal_emit::call (base=0x7fffd57fb3e0, p_args=0x7fffd57fb3f8, p_argcount=2, r_ret=..., p_defvals=..., r_error=...) at core/variant/variant_call.cpp:1894
#19 0x0000000004f88527 in Variant::callp (this=0x7fffd57fb3e0, p_method=..., p_args=0x7fffd57fb3f8, p_argcount=2, r_ret=..., r_error=...) at core/variant/variant_call.cpp:1060
#20 0x000000000236b98e in GDScriptFunction::call (this=0x9e07af0, p_instance=0xa306380, p_args=0x7fffd57fd8a0, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:1555
#21 0x000000000227a8c1 in GDScriptInstance::callp (this=0xa306380, p_method=..., p_args=0x7fffd57fd8a0, p_argcount=1, r_error=...) at modules/gdscript/gdscript.cpp:1827
#22 0x000000000522b4d1 in Object::callp (this=0xa5a35d0, p_method=..., p_args=0x7fffd57fd8a0, p_argcount=1, r_error=...) at core/object/object.cpp:711
#23 0x0000000004f66267 in Callable::callp (this=0x9e150b0, p_arguments=0x7fffd57fd8a0, p_argcount=1, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:62
#24 0x0000000004f691ee in CallableCustomBind::call (this=0x9e150a0, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable_bind.cpp:99
#25 0x0000000004f65feb in Callable::callp (this=0x7fffac003bf8, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#26 0x0000000004cb6bb5 in core_bind::Thread::_start_func (ud=0x7fffb8001fc0) at core/core_bind.cpp:1170
#27 0x0000000004d42006 in Thread::callback (p_self=0x7fffac003c08, p_settings=..., p_callback=0x4cb68ec <core_bind::Thread::_start_func(void*)>, p_userdata=0x7fffb8001fc0) at core/os/thread.cpp:65
#28 0x0000000004d42e4d in std::__invoke_impl<void, void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __f=@0x81c6ab8: 0x4d41f5c <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>) at /usr/include/c++/12/bits/invoke.h:61
#29 0x0000000004d42d16 in std::__invoke<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> (
    __fn=@0x81c6ab8: 0x4d41f5c <Thread::callback(Thread*, Thread::Settings const&, void (*)(void*), void*)>) at /usr/include/c++/12/bits/invoke.h:96
#30 0x0000000004d42bd1 in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x81c6a98) at /usr/include/c++/12/bits/std_thread.h:258
#31 0x0000000004d42b36 in std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> >::operator() (this=0x81c6a98)
    at /usr/include/c++/12/bits/std_thread.h:265
#32 0x0000000004d42b1a in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(Thread*, Thread::Settings const&, void (*)(void*), void*), Thread*, Thread::Settings, void (*)(void*), void*> > >::_M_run (this=0x81c6a90) at /usr/include/c++/12/bits/std_thread.h:210
#33 0x000000000568e353 in std::execute_native_thread_routine (__p=0x81c6a90) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#34 0x00007ffff7bd988a in start_thread () from /lib64/libc.so.6
#35 0x00007ffff7c5551c in clone3 () from /lib64/libc.so.6
```

**Comment by akien-mga** [comment]
The crash only happens in release builds, as noted by fire.

In a debug build, the reason for the crash is made clear:
```
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Trying to call a function on a null value.
          at: <anonymous lambda> (res://scene/UIController.gd:72)
SCRIPT ERROR: Invalid get index 'resource_name' (on base: 'Nil').
          at: _on_root_gltf_is_loaded (res://scene/UIController.gd:132)
```

The crash can be worked around with this diff:
```diff
@@ -91,5 +91,8 @@
                        # Gather material
                        for si in mesh.mesh.get_surface_count():
                                var mat = mesh.get_active_material(si) as StandardMaterial3D
+                               if not mat:
+                                       print("invalid mat")
+                                       return
                                if not material_array.has(mat):
                                        material_array.append(mat)
```

So the problem is that the material is now invalid and your code doesn't properly handle it.

Why the material became invalid is likely related to changes in the glTF module more than GDScript, the GDScript crash is a red herring for the issue raised in a debug build.

**Comment by akien-mga** [comment]
Please try to extract a MRP, or check if the issue is not that your project needs to be ported after intentional upstream changes.

**Comment by fire** [comment]
May be related https://github.com/godotengine/godot/pull/69083

**Comment by fire** [comment]
I haven't been affected by this issue in a while.
