### ISSUE TITLE
Executing `BakedLightmap.bake` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#69229]
### Godot version

3.6.beta.custom_build. 71f5bb391

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
extends Node
func _process(delta):

	var temp_variable2388 = BakedLightmap.new()
	add_child(temp_variable2388)
	var temp_argument2388_f85_0 = Sprite.new()
	temp_variable2388.bake(temp_argument2388_f85_0, "4223850674")
```
Godot crashes with this backtrace

```
#0  0x0000000000000000 in ?? ()
#1  0x0000000003d5c558 in BakedLightmap::bake (this=0xb97b3d0, p_from_node=0xb93d8b0, p_data_save_path=...) at scene/3d/baked_lightmap.cpp:636
#2  0x0000000003d78160 in MethodBind2R<BakedLightmap::BakeError, Node*, String>::call (this=0xa1e34f0, p_object=0xb97b3d0, p_args=0x7fffffffc650, p_arg_count=2, r_error=...) at ./core/method_bind.gen.inc:1681
#3  0x0000000004b366be in Object::call (this=0xb97b3d0, p_method=..., p_args=0x7fffffffc650, p_argcount=2, r_error=...) at core/object.cpp:918
#4  0x0000000004bde47b in Variant::call_ptr (this=0x7fffffffc5d8, p_method=..., p_args=0x7fffffffc650, p_argcount=2, r_ret=0x0, r_error=...) at core/variant_call.cpp:1237
#5  0x00000000019d4b3b in GDScriptFunction::call (this=0xb9aaab0, p_instance=0xb922460, p_args=0x7fffffffced8, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gdscript_function.cpp:1050
#6  0x0000000001975d10 in GDScriptInstance::call_multilevel (this=0xb922460, p_method=..., p_args=0x7fffffffced8, p_argcount=1) at modules/gdscript/gdscript.cpp:1211
#7  0x0000000003a11478 in Node::_notification (this=0xb985300, p_notification=17) at scene/main/node.cpp:58
#8  0x0000000001932720 in Node::_notificationv (this=0xb985300, p_notification=17, p_reversed=false) at scene/main/node.h:47
#9  0x0000000004b36801 in Object::notification (this=0xb985300, p_notification=17, p_reversed=false) at core/object.cpp:927
#10 0x0000000003a519cb in SceneTree::_notify_group_pause (this=0xa709e00, p_group=..., p_notification=17) at scene/main/scene_tree.cpp:1133
#11 0x0000000003a4efe0 in SceneTree::idle (this=0xa709e00, p_time=0.133286998) at scene/main/scene_tree.cpp:636
#12 0x00000000018c8f5b in Main::iteration () at main/main.cpp:2337
#13 0x00000000018886a8 in OS_X11::run (this=0x7fffffffd350) at platform/x11/os_x11.cpp:4035
#14 0x0000000001872b1e in main (argc=2, argv=0x7fffffffdcc8) at platform/x11/godot_x11.cpp:59
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.
Memory leaks or asan backtraces are visibe when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

### Steps to reproduce

Above

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Fixed by #69285.
