### ISSUE TITLE
Unable to use custom resources with the @tool hint.

### ISSUE THREAD

**Issue by HungryProton** [godotengine/godot#69356]
### Godot version

4.0-dev(cdd99e9bec16db60efd894a06826f6fea139d00d)

### System information

Archlinux stable

### Issue description

Selecting a custom resource from the inspector fails with this error message:
```editor/editor_resource_picker.cpp:445 - Condition "!resp" is true. Breaking.```

### Steps to reproduce

- Create a script extending `Resource`, add a `class_name` and the `@tool` keyword.
- Create a script exporting the custom resource from previous step
- Instantiate it in a scene and try to assign a resource from the inspector.

### Minimal reproduction project

Minimal reproduction project: [debug_4.zip](https://github.com/godotengine/godot/files/10117319/debug_4.zip)

Open the test.tscn scene, select the node and try to assign it a resource from the inspector.

**Comment by RedMser** [comment]
For some reason, the refcount of the custom resource's instance drops from 1 to 0 at the following method call:

```
GDScript::_super_implicit_constructor(GDScript *p_script, GDScriptInstance *p_instance, Callable::CallError &r_error) Line 132
GDScript::_create_instance(const Variant * * p_args, int p_argcount, Object * p_owner, bool p_is_ref_counted, Callable::CallError & r_error) Line 159
GDScript::instance_create(Object * p_this) Line 407
Object::set_script(const Variant & p_script) Line 844
EditorData::script_class_instance(const String & p_class) Line 952
EditorResourcePicker::_edit_menu_cbk(int p_which) Line 435
```

**Comment by ObsidianBlk** [comment]
I have encountered the same issue.
I have a custom node script that has an export for a custom resource. When I attempt to set my custom resource, the inspector does _not_ add the new resource. It stays blank and I get the same message:
```
editor/editor_resource_picker.cpp:445 - Condition "!resp" is true. Breaking.
```
However, my custom resource is set as a @tool ... and I noticed that if I remove @tool from the custom resource script, I _can_ set my custom resource within my custom node. In editor, removing the @tool throws a lot of errors as my custom node is also a tool attempting to use the custom resource, but at runtime things still work.

**Comment by vaartis** [comment]
Same thing, but when creating a resource with "New resource" the error is different:

```
  editor/editor_data.cpp:551 - Parameter "p_object" is null.
  editor/filesystem_dock.cpp:2082 - Condition "!c" is true.
```

**Comment by vaartis** [comment]
I ran a bisect since 4.0 beta 1 where this problem was not present, and according to the log the first bad commit is 847c9bd24832d51b1bbf763d445d2d57806486fe. 

<details>
  <summary>Bisect log</summary>
  
  ```
# bad: [0bb94df247a0a0c22333e2e99744fc3fd184601a] Merge pull request #70230 from DarkKilauea/nav-experimental
# good: [f8745f2f71c79972df66f17a3da75f6e328bc55d] Merge pull request #66103 from Zylann/bind_property_usage_read_only
git bisect start 'master' 'f8745f2f71c79972df66f17a3da75f6e328bc55d'
# good: [038ee04b8fdf595274ddc520ff70f671cfece627] Merge pull request #67975 from BastiaanOlij/implement_uv2_on_primitives
git bisect good 038ee04b8fdf595274ddc520ff70f671cfece627
# bad: [60750a1b693a8a7b8ac8914c5f7b12f6bbd3644a] Merge pull request #69403 from KoBeWi/gdrequiredvirutalcallnoif
git bisect bad 60750a1b693a8a7b8ac8914c5f7b12f6bbd3644a
# good: [28039094b384b32226f06e7d7ed7441bc1171cf3] Merge pull request #68911 from souplamp/return-value-discarded-error
git bisect good 28039094b384b32226f06e7d7ed7441bc1171cf3
# good: [5b3d07cc0232215bcdc901369862da50a7e89b3b] Merge pull request #69165 from timothyqiu/capitalization
git bisect good 5b3d07cc0232215bcdc901369862da50a7e89b3b
# bad: [ef090ee6eac429e51b26ea31e7882cc8cdfa2093] Merge pull request #68874 from TokageItLab/fix-unique-path-keying
git bisect bad ef090ee6eac429e51b26ea31e7882cc8cdfa2093
# good: [8253c28200cf01f62e2489ff1d799a6473e199c9] Merge pull request #67031 from raulsntos/dotnet/string-extensions
git bisect good 8253c28200cf01f62e2489ff1d799a6473e199c9
# bad: [c3920936681b68dc42e259a206dac726fd240d10] Merge pull request #69272 from rune-scape/rune-avoid-global-base
git bisect bad c3920936681b68dc42e259a206dac726fd240d10
# good: [5eeb6e5906ebf303ba695bc26f87b41ab1b85200] Merge pull request #68532 from Calinou/cmdline-user-args-add-alternative-separator
git bisect good 5eeb6e5906ebf303ba695bc26f87b41ab1b85200
# good: [2fadc1299d8e4db338322f5a19640207d46d475b] Merge pull request #67871 from Calinou/editor-theme-add-oled-preset
git bisect good 2fadc1299d8e4db338322f5a19640207d46d475b
# good: [4a459a8c52732f056f0a4a928051bade75d4846f] Merge pull request #69138 from Calinou/doc-light2d
git bisect good 4a459a8c52732f056f0a4a928051bade75d4846f
# good: [be0923b1d98cec6605baca0be8c9bf65c1ed996f] Merge pull request #69277 from pkdawson/construct-joypad-first
git bisect good be0923b1d98cec6605baca0be8c9bf65c1ed996f
# bad: [847c9bd24832d51b1bbf763d445d2d57806486fe] GDScript: Avoid using `get_global_class_native_base`
git bisect bad 847c9bd24832d51b1bbf763d445d2d57806486fe
# first bad commit: [847c9bd24832d51b1bbf763d445d2d57806486fe] GDScript: Avoid using `get_global_class_native_base`
```
</details>

**Comment by kleonc** [comment]
cc @rune-scape: https://github.com/godotengine/godot/issues/69356#issuecomment-1356802361

**Comment by rune-scape** [comment]
@vaartis thank you for the investigation, i think i see my mistake, making a PR

**Comment by difof** [comment]
I still have this issue on beta 10.

Node script:
```gdscript
@tool
extends Node2D
@export var my_resource: MyResource
```

Resource script (without a resource file):
```gdscript
@tool
extends Resource
class_name MyResource
@export var value: FastNoiseLite
```

Whenever I click on "New MyResource" in the inspector, I get "editor/editor_resource_picker.cpp:445 - Condition "!resp" is true. Breaking."

I can use `Resource` type as the node's exported field but then I'll get all kinds of resources in the dropdown and need to scroll to the bottom for resource actions everytime.

**Comment by vaartis** [comment]
Might be related, but I've also found that custom resources embedded into another resources reset if you expand the embedded resource inspector and then switch to the other resource of the same type. I cannot easily reproduce it in a new project, but it happens in an existing project.

**Comment by michaeltintiuc** [comment]
Looks similar to #66698

**Comment by Dinozor** [comment]
Not fixed. Or broken again.

Created custom resource with @tool and class_name=TwitchIRCClient. I need it to be a tool, to have special @export var token to be secret.

```gdscript
var _token: String
func _get_property_list() -> Array[Dictionary]:
	var properties: Array[Dictionary] = []
	properties.append({
		"name": "_token",
		"hint": PROPERTY_HINT_PASSWORD,
		"type": TYPE_STRING,
		"usage": PROPERTY_USAGE_SECRET | PROPERTY_USAGE_DEFAULT
	})
	return properties
```
After I create new scene with script (not a @tool) with `@export var messenger: TwitchIRCClient ` and create/assign it via Editor.
When scene is started `messenger` is Nil.
Also, when I create resource manually by right clicking on folder->create resource -> TwitchIRCClient I see new resource but it's Resource and RefCounted are empty:
![image](https://github.com/godotengine/godot/assets/1084354/c6875553-489f-4225-a614-cda6bb5f78e0)

When I remove @tool attribute from TwitchIRCClient resource script - it works fine, but then I need to expose my token visually like `@export var token: String` which is something I'm trying to prevent and also have some additional custom properties for future like that.

Just tested it on Godot 4.1.3 (latest for me). 
In addition, after Godot restart/project reload it shows this error in log:
```
  Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'TwitchIRCClient' and its derivatives.
  Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'TwitchIRCClient' and its derivatives.
  Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'TwitchIRCClient' and its derivatives.
  Failed to set a resource of the type 'Resource' because this EditorResourcePicker only accepts 'TwitchIRCClient' and its derivatives.
```

**Comment by MASTRIO** [comment]
I'm having the exact same issue as @Dinozor

**Comment by CharlieDelune** [comment]
I think I just ran into this issue in 4.4.stable

My repro steps are very simple...

Create a custom resource with very simple properties (strings, ints, enums)
Use ResourceSaver to save the resource.
All of the properties save to the file properly. They can successfully be deserialized. The inspector shows all the expected values when the resource is selected.

Add the [Tool] attribute to the same resource, make some changes to it, use ResourceSaver to save it again.
The properties save to the file properly, but they never come back out. The inspector values are all null and trying to load it out via code results in a whole bunch of nulls.

**Comment by srawls1** [comment]
Still an issue in 4.3.stable. When I add the [Tool] annotation to my node script, the resource references I had set in the editor get cleared and I get an error when I try to set them again.
The error message when I try to set the resource reference (`Graphic` is my resource type, `UnityStyleButton` is my Node script) is:
```
/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'Graphic'.
     at UnityStyleButton.RestoreGodotObjectData(GodotSerializationInfo info) in Godot.SourceGenerators\Godot.SourceGenerators.ScriptSerializationGenerator\UnityStyleButton_ScriptSerialization.generated.cs:line 28
     at Godot.Bridge.CSharpInstanceBridge.DeserializeState(IntPtr godotObjectGCHandle, godot_dictionary* propertiesState, godot_dictionary* signalEventsState) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 255
```

**Comment by Grkmus** [comment]
Still having the same problem on macos as well
