### ISSUE TITLE
Boxshape leaks at the end of program

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#69750]
### Godot version

4.0.beta.custom_build. cf093f8e4

### System information

Ubuntu 22.04 - Radeon RX 570, Gnome shell 42 X11

### Issue description

```
extends Node
func _process(delta):


	var temp_variable_f3092736 = RID()
	var temp_variable_f3092737 = null
	var temp_variable_f3092738 = StringName("")
	var temp_variable_f3092739 = {"roman" : 22, 22 : 25, BoxShape3D.new() : BoxShape3D.new()}
	NavigationServer3D.agent_set_callback(temp_variable_f3092736,temp_variable_f3092737,temp_variable_f3092738,temp_variable_f3092739)
```
cause this leak 
```
ERROR: 2 RID allocations of type 'P12GodotShape3D' were leaked at exit.
ERROR: Condition "agent == nullptr" is true.
   at: _cmd_agent_set_callback (modules/navigation/godot_navigation_server.cpp:681)
ERROR: Parameter "PhysicsServer3D::get_singleton()" is null.
   at: ~Shape3D (scene/resources/shape_3d.cpp:131)
ERROR: Parameter "PhysicsServer3D::get_singleton()" is null.
   at: ~Shape3D (scene/resources/shape_3d.cpp:131)

=================================================================
==15255==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 272 byte(s) in 2 object(s) allocated from:
    #0 0x7fade4eb4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x1d3aa49d in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x1d3aa3ae in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x19d88235 in GodotPhysicsServer3D::box_shape_create() servers/physics_3d/godot_physics_server_3d.cpp:66
    #4 0x1c0554d4 in PhysicsServer3DWrapMT::box_shape_create() servers/physics_server_3d_wrap_mt.h:82
    #5 0x19410fb4 in PhysicsServer3D::shape_create(PhysicsServer3D::ShapeType) servers/physics_server_3d.cpp:664
    #6 0x170e1aa4 in BoxShape3D::BoxShape3D() scene/resources/box_shape_3d.cpp:98
    #7 0x135adb24 in Object* ClassDB::creator<BoxShape3D>() core/object/class_db.h:140
    #8 0x1eb19a7d in ClassDB::instantiate(StringName const&) core/object/class_db.cpp:339
    #9 0x5bd0ab7 in GDScriptNativeClass::instantiate() modules/gdscript/gdscript.cpp:92
    #10 0x5bd046f in GDScriptNativeClass::_new() modules/gdscript/gdscript.cpp:80
    #11 0x5d37b67 in void call_with_variant_args_ret_helper<__UnexistingClass, Variant>(__UnexistingClass*, Variant (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:680
    #12 0x5d36bf8 in void call_with_variant_args_ret_dv<__UnexistingClass, Variant>(__UnexistingClass*, Variant (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:493
    #13 0x5d3596d in MethodBindTR<Variant>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:465
    #14 0x6260283 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1644
    #15 0x5c16d72 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1827
    #16 0x138c527c in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #17 0x1382a5f0 in Node::_notification(int) scene/main/node.cpp:56
    #18 0x492f4af in Node::_notificationv(int, bool) scene/main/node.h:45
    #19 0x1ebb2cd2 in Object::notification(int, bool) core/object/object.cpp:790
    #20 0x1398dbf3 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:868
    #21 0x139803af in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #22 0x2937b3a in Main::iteration() main/main.cpp:3192
    #23 0x2714b89 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:878
    #24 0x26f1b44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #25 0x7fade422350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 272 byte(s) leaked in 2 allocation(s).
```

### Steps to reproduce

Above

### Minimal reproduction project

[t.zip](https://github.com/godotengine/godot/files/10186850/t.zip)

**Comment by adamscott** [comment]
@qarmin Can you join your minimal project?

**Comment by smix8** [comment]
Related to https://github.com/godotengine/godot/issues/68013
