### ISSUE TITLE
Image compressed to unsupported format causes crash when OpenGL renderer is in use.

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#69787]
### Godot version

4.0.beta.custom_build f692b476869c14023b

### System information

arch linux
Intel® Core™ i7-10510U × 8
Mesa Intel® UHD Graphics (CML GT2)
NVIDIA GeForce GTX 1080

### Issue description

When using the OpenGL renderer loading of some scenes leads to crashes. Terminal shows this error before stacktrace:

```
ERROR: Image Format: 34 is not supported by the OpenGL3 Renderer
   at: _get_gl_image_and_format (drivers/gles3/storage/texture_storage.cpp:569)
ERROR: Condition "img.is_null()" is true.
   at: texture_set_data (drivers/gles3/storage/texture_storage.cpp:1084)
```

### Steps to reproduce

Unsure

### Minimal reproduction project

None yet

**Comment by clayjohn** [comment]
Can you please post the stack trace as well so we can see where it crashes?

**Comment by maiself** [comment]
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (486ff0437bb0c99f96ac98ee2ca51c431868157f)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7f82d249aa00] (??:0)
[2] /usr/lib/libc.so.6(+0x15384d) [0x7f82d25b584d] (??:0)
[3] /usr/lib/dri/iris_dri.so(+0x621eb8) [0x7f82c6421eb8] (??:0)
[4] /usr/lib/dri/iris_dri.so(+0x271332) [0x7f82c6071332] (??:0)
[5] /usr/lib/dri/iris_dri.so(+0x2730b3) [0x7f82c60730b3] (??:0)
[6] godot4-dev(+0x1a195e2) [0x5643537e85e2] (??:0)
[7] godot4-dev(+0x43a0fdc) [0x56435616ffdc] (??:0)
[8] godot4-dev(+0x43a576b) [0x56435617476b] (??:0)
[9] godot4-dev(+0x3ce941a) [0x564355ab841a] (??:0)
[10] godot4-dev(+0x3ceb4fa) [0x564355aba4fa] (??:0)
[11] godot4-dev(+0x3cede90) [0x564355abce90] (??:0)
[12] godot4-dev(+0x3d468cc) [0x564355b158cc] (??:0)
[13] godot4-dev(+0xae06fb) [0x5643528af6fb] (??:0)
[14] godot4-dev(+0xa830d1) [0x5643528520d1] (??:0)
[15] godot4-dev(+0xa75589) [0x564352844589] (??:0)
[16] /usr/lib/libc.so.6(+0x23290) [0x7f82d2485290] (??:0)
[17] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f82d248534a] (??:0)
[18] godot4-dev(+0xa813c5) [0x5643528503c5] (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

For some reason I'm unable to get debug symbols working, I'm not sure how the build system has changed recently. I'll keep trying to get debug symbols.

**Comment by maiself** [comment]
```
Thread 1 "godot4-dev" received signal SIGSEGV, Segmentation fault.
0x00007ffff7c78d41 in memcpy () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7c78d41 in memcpy () from /usr/lib/libc.so.6
#1  0x00007fffea9e91e9 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#2  0x00007fffea9fdad2 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#3  0x00007fffea64dba6 in ?? () from /usr/lib/libnvidia-glcore.so.525.60.11
#4  0x0000555556f6d5e2 in RasterizerSceneGLES3::_render_list_template<(PassMode)1> (p_alpha_pass=true, p_to_element=<optimized out>, p_from_element=0, p_render_data=0x7fffffffcb00, p_params=<synthetic pointer>, this=<optimized out>)
    at drivers/gles3/rasterizer_scene_gles3.cpp:2334
#5  RasterizerSceneGLES3::render_scene (this=<optimized out>, p_render_buffers=..., p_camera_data=<optimized out>, p_prev_camera_data=<optimized out>, p_instances=..., p_lights=..., p_reflection_probes=..., p_voxel_gi_instances=..., 
    p_decals=..., p_lightmaps=..., p_fog_volumes=..., p_environment=..., p_camera_attributes=..., p_shadow_atlas=..., p_occluder_debug_tex=..., p_reflection_atlas=..., p_reflection_probe=..., p_reflection_probe_pass=<optimized out>, 
    p_screen_mesh_lod_threshold=<optimized out>, p_render_shadows=<optimized out>, p_render_shadow_count=<optimized out>, p_render_sdfgi_regions=<optimized out>, p_render_sdfgi_region_count=<optimized out>, 
    p_sdfgi_update_data=<optimized out>, r_render_info=<optimized out>) at drivers/gles3/rasterizer_scene_gles3.cpp:1987
#6  0x00005555598f4fdc in RendererSceneCull::_render_scene (this=<optimized out>, p_camera_data=<optimized out>, p_render_buffers=..., p_environment=..., p_force_camera_attributes=..., p_visible_layers=<optimized out>, p_scenario=..., 
    p_viewport=..., p_shadow_atlas=..., p_reflection_probe=..., p_reflection_probe_pass=<optimized out>, p_screen_mesh_lod_threshold=<optimized out>, p_using_shadows=<optimized out>, r_render_info=<optimized out>)
    at servers/rendering/renderer_scene_cull.cpp:3270
#7  0x00005555598f976b in RendererSceneCull::render_camera (this=this@entry=0x55555da302b0, p_render_buffers=..., p_camera=..., p_scenario=..., p_viewport=..., p_viewport_size=..., p_use_taa=p_use_taa@entry=false, 
    p_screen_mesh_lod_threshold=p_screen_mesh_lod_threshold@entry=0.000892857148, p_shadow_atlas=..., p_xr_interface=..., r_render_info=<optimized out>) at servers/rendering/renderer_scene_cull.cpp:2551
#8  0x000055555923d41a in RendererViewport::_draw_3d (this=<optimized out>, p_viewport=0x55556a441d60) at servers/rendering/renderer_viewport.cpp:211
#9  0x000055555923f4fa in RendererViewport::_draw_viewport (this=0x55555da301d0, p_viewport=0x55556a441d60) at servers/rendering/renderer_viewport.cpp:266
#10 0x0000555559241e90 in RendererViewport::draw_viewports (this=<optimized out>) at servers/rendering/renderer_viewport.cpp:711
#11 0x000055555929a8cc in RenderingServerDefault::_draw (this=0x55555d9fd230, p_swap_buffers=<optimized out>, frame_step=0.30054199999999914) at servers/rendering/rendering_server_default.cpp:91
#12 0x00005555560346fb in Main::iteration () at main/main.cpp:3205
#13 0x0000555555fd70d1 in OS_LinuxBSD::run (this=this@entry=0x7fffffffdb90) at platform/linuxbsd/os_linuxbsd.cpp:878
#14 0x0000555555fc9589 in main (argc=<optimized out>, argv=0x7fffffffe0f8) at platform/linuxbsd/godot_linuxbsd.cpp:73
```

**Comment by clayjohn** [comment]
Looks like it is crashing when attempting to draw the mesh. 

Could you please share the model/texture that is causing the crash so we can look into it?

**Comment by maiself** [comment]
Due to licensing I'm unable to upload the assets. I've been trying to recreate a MRP, I've gotten as far as applying the just normal map to a plain sphere mesh and had the crash trigger, however it doesn't do so reliably in that case, which has me thinking there might be more than one thing going on...

**Comment by clayjohn** [comment]
https://github.com/godotengine/godot/issues/69836 could be related

**Comment by maiself** [comment]
Looks like duplicate of #69836, which contains a fix.
