### ISSUE TITLE
Executing `TabContainer._get_drag_data_fw` leaks memory

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#70005]
### Godot version

4.0.beta.custom_build. ae86d907e

### System information

Ubuntu 22.10 - AMD RX 470, Gnome shell 43 X11

### Issue description

When executing
```
extends Node
func _process(delta):
	var temp_variable14923 = TabContainer.new()
	add_child(temp_variable14923)
	temp_variable14923.set_drag_to_rearrange_enabled(true)
	temp_variable14923._get_drag_data_fw(Vector2(-NAN, -NAN), null)
	temp_variable14923.queue_free()

```
causes this leak

```
Direct leak of 19520 byte(s) in 40 object(s) allocated from:
    #0 0x7fe086cb4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x1d3e237d in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x1d3e228e in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0xb8cf8b3 in TextServerAdvanced::_create_shaped_text(TextServer::Direction, TextServer::Orientation) modules/text_server_adv/text_server_adv.cpp:3681
    #4 0xb95c611 in TextServerAdvanced::create_shaped_text(TextServer::Direction, TextServer::Orientation) (/usr/bin/godot4s+0xb95c611)
    #5 0x145bf297 in Label::Label(String const&) scene/gui/label.cpp:977
    #6 0x14c95e24 in TabContainer::_get_drag_data_fw(Vector2 const&, Control*) scene/gui/tab_container.cpp:377
    #7 0xd45bf99 in void call_with_variant_args_ret_helper<__UnexistingClass, Variant, Vector2 const&, Control*, 0ul, 1ul>(__UnexistingClass*, Variant (__UnexistingClass::*)(Vector2 const&, Control*), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul>) core/variant/binder_common.h:680
    #8 0xd45019c in void call_with_variant_args_ret_dv<__UnexistingClass, Variant, Vector2 const&, Control*>(__UnexistingClass*, Variant (__UnexistingClass::*)(Vector2 const&, Control*), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:493
    #9 0xd425917 in MethodBindTR<Variant, Vector2 const&, Control*>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:465
    #10 0x1ec76504 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #11 0x1e0a5ac4 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1159
    #12 0x626f2a0 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1555
    #13 0x5c25760 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1827
    #14 0x138e1d8c in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:237
    #15 0x13847100 in Node::_notification(int) scene/main/node.cpp:56
    #16 0x493de9d in Node::_notificationv(int, bool) scene/main/node.h:45
    #17 0x1ec77a58 in Object::notification(int, bool) core/object/object.cpp:790
    #18 0x139aa703 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:868
    #19 0x1399cebf in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #20 0x2940b3a in Main::iteration() main/main.cpp:3192
    #21 0x271db89 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:878
    #22 0x26fab44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #23 0x7fe08602350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.
Memory leaks or asan backtraces are visibe when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

### Steps to reproduce

Above

### Minimal reproduction project

N/A

**Comment by kitbdev** [comment]
The `_get_drag_data_fw` method is called when starting to drag and drop. The memory created seems to be the drag preview, which is passed off to the Viewport to handle. 
Viewport automatically destroys it when the drag and drop operation ends (in `_perform_drop`) but if Viewport is deleted during drag and drop, I'm not sure if it correctly frees the memory. 
This means this leak should also apply to everything that calls `set_drag_preview`.
It should be a simple fix in the Viewport deconstructor, but I don't know how to check memory leaks enough to test it.

**Comment by qarmin** [comment]
_get_drag_data_fw is no longer available from GDscript
