### ISSUE TITLE
randi() % a const pow(2, 32) that is cast to an int crashes Godot with no console output or errors

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#70861]
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

This is weird, but I was trying to make the personality value for a pokemon and it crashed with no console output or errors.

It doesn't crash if:
* randi() is not present
* % is not present
* MAX_PERSONALITY_VALUE is a variable not a constant
* I put `randi() % int(pow(2, 32))` instead

### Steps to reproduce

this code
```
extends Node2D

const MAX_PERSONALITY_VALUE: int = pow(2, 32) # Not inclusive

func _ready() -> void:
	print(randi() % MAX_PERSONALITY_VALUE)
```

### Minimal reproduction project

none

**Comment by ShatReal** [comment]
I just realized that I don't need to modulo since randi returns an unsigned 32 bit integer which is what personality value is. But it's still a bug.

**Comment by akien-mga** [comment]
Stacktrace:
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000005e97dbf in GDScriptFunction::call (this=0xd537b40, p_instance=0xe773d90, p_args=0x0, p_argcount=0, r_err=..., p_state=0x0) at modules/gdscript/gdscript_vm.cpp:703
#2  0x0000000005d48607 in GDScriptInstance::callp (this=0xe773d90, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at modules/gdscript/gdscript.cpp:1834
#3  0x00000000082a6d2c in Node::_gdvirtual__ready_call<false> (this=0xe7714f0) at scene/main/node.h:241
#4  0x000000000828c790 in Node::_notification (this=0xe7714f0, p_notification=13) at scene/main/node.cpp:154
#5  0x0000000005ac7b5e in Node::_notificationv (this=0xe7714f0, p_notification=13, p_reversed=false) at ./scene/main/node.h:45
#6  0x00000000061e8397 in CanvasItem::_notificationv (this=0xe7714f0, p_notification=13, p_reversed=false) at ./scene/main/canvas_item.h:45
#7  0x00000000081bb60f in Node2D::_notificationv (this=0xe7714f0, p_notification=13, p_reversed=false) at ./scene/2d/node_2d.h:37
#8  0x000000000a2e5915 in Object::notification (this=0xe7714f0, p_notification=13, p_reversed=false) at core/object/object.cpp:790
#9  0x000000000828cb36 in Node::_propagate_ready (this=0xe7714f0) at scene/main/node.cpp:187
#10 0x000000000828cab9 in Node::_propagate_ready (this=0xe5bc340) at scene/main/node.cpp:179
#11 0x0000000008299bec in Node::_set_tree (this=0xe5bc340, p_tree=0xe5da9c0) at scene/main/node.cpp:2571
#12 0x00000000082c432c in SceneTree::initialize (this=0xe5da9c0) at scene/main/scene_tree.cpp:410
#13 0x0000000005348c39 in OS_LinuxBSD::run (this=0x7fffffffd1b0) at platform/linuxbsd/os_linuxbsd.cpp:866
#14 0x00000000053406c0 in main (argc=1, argv=0x7fffffffd718) at platform/linuxbsd/godot_linuxbsd.cpp:73
```

Indeed as @dalexeev points it out `const MAX_PERSONALITY_VALUE: int = pow(2, 32)` ends up with `TYPE_FLOAT`.

Using a float operand for the modulo operator is not supported:
```
print(randi() % 1000.0)
```
![image](https://user-images.githubusercontent.com/4701338/210356030-9ac14278-bbc1-4dcb-aa95-4ca5e7afc627.png)

But here GDScript is getting confused.

I wondered if @vonagam's #70464 would happen to solve this, but I tested and it doesn't.

**Comment by Chaosus** [comment]
I've fixed it both for global and local constant.

**Comment by dalexeev** [comment]
> I've fixed it both for global and local constants in #70872.

Oops.
