### ISSUE TITLE
Crash due PackedVector2Array usage

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#71222]
### Godot version

v4.0.beta.custom_build [9c02bf1b1]

### System information

Ubuntu 22.10 LTS, GTX1060, Vulkan

### Issue description

```
(gdb) bt

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c3bc46 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c227fc in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7c850be in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7db95dc "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7c9c3fc in malloc_printerr (str=str@entry=0x7ffff7dbc790 "malloc(): unsorted double linked list corrupted") at ./malloc/malloc.c:5660
#7  0x00007ffff7c9f8ec in _int_malloc (av=av@entry=0x7ffff7df6c60 <main_arena>, bytes=bytes@entry=80) at ./malloc/malloc.c:4006
#8  0x00007ffff7ca06fd in __GI___libc_malloc (bytes=80) at ./malloc/malloc.c:3323
#9  0x0000555559c8b016 in Memory::alloc_static (p_bytes=64, p_pad_align=<optimized out>) at core/os/memory.cpp:75
#10 0x00005555589a633c in RBMap<Vector2i, Vector2i, TileMapQuadrant::CoordsWorldComparator, DefaultAllocator>::_insert (this=this@entry=0x7fffffffd310, p_key=..., p_value=...) at ./core/templates/rb_map.h:415
#11 0x00005555589a6558 in RBMap<Vector2i, Vector2i, TileMapQuadrant::CoordsWorldComparator, DefaultAllocator>::insert (p_value=..., p_key=..., this=0x7fffffffd310) at ./core/templates/rb_map.h:628
#12 RBMap<Vector2i, Vector2i, TileMapQuadrant::CoordsWorldComparator, DefaultAllocator>::operator[] (this=0x7fffffffd310, p_key=...) at ./core/templates/rb_map.h:677
#13 0x0000555558989f53 in TileMap::_rendering_update_dirty_quadrants (this=0x555560f5c980, r_dirty_quadrant_list=...) at scene/2d/tile_map.cpp:1262
#14 0x000055555898b88b in TileMap::_update_dirty_quadrants (this=<optimized out>) at scene/2d/tile_map.cpp:850
#15 0x000055555616b5bd in call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (
    p_args=<synthetic pointer>, r_error=..., p_method=<optimized out>, p_instance=<optimized out>) at ./core/variant/binder_common.h:293
#16 call_with_variant_args_dv<__UnexistingClass> (p_args=<optimized out>, default_values=..., r_error=..., p_argcount=<optimized out>, p_method=<optimized out>, p_instance=<optimized out>)
    at ./core/variant/binder_common.h:440
#17 MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) const (this=<optimized out>, p_object=<optimized out>, p_args=<optimized out>, p_arg_count=<optimized out>, r_error=...)
    at ./core/object/method_bind.h:320
#18 0x000055555a1dfa2e in Object::callp (this=0x555560f5c980, p_method=..., p_args=0x0, p_argcount=<optimized out>, r_error=...) at core/object/object.cpp:733
#19 0x0000555559efbd67 in Callable::callp (this=this@entry=0x7ffff01f2020, p_arguments=p_arguments@entry=0x0, p_argcount=p_argcount@entry=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:62
#20 0x000055555a1dafe9 in MessageQueue::_call_function (this=<optimized out>, p_callable=..., p_args=<optimized out>, p_argcount=0, p_show_error=<optimized out>) at core/object/message_queue.cpp:229
#21 0x000055555a1db34c in MessageQueue::flush (this=0x55555d456040) at core/object/message_queue.cpp:275
#22 0x0000555558220173 in SceneTree::physics_process (this=0x555560e199b0, p_time=0.016666666666666666) at scene/main/scene_tree.cpp:430
#23 0x0000555556045163 in Main::iteration () at main/main.cpp:3026
#24 0x0000555555ff8f11 in OS_LinuxBSD::run (this=this@entry=0x7fffffffd7b0) at platform/linuxbsd/os_linuxbsd.cpp:878
#25 0x0000555555feaa3d in main (argc=<optimized out>, argv=0x7fffffffdcf8) at platform/linuxbsd/godot_linuxbsd.cpp:73

```

here problematic lines, if you change `PackedVector2Array` to simple `Array` game doesn't crash
p.s. this for drawing debug tiles over existing tiles

```gdscript
func _on_debug_astar() -> void:
	# clear previous drawing
	if !tilemap.get_used_cells(2).is_empty():
		tilemap.clear_layer(2)
		return

	# draw
	var cells : PackedVector2Array
	for id in astar.get_point_ids():
		if astar.is_point_disabled(id):
			cells.append(astar.get_point_position(id))
	tilemap.set_cells_terrain_connect(2, cells, 0, 0)
```

### Steps to reproduce

1. run attachment
2. press space key to toggle drawing
3. continue step 2 till crash
4. change `PackedVector2Array` to `Array`
5. try press space key again

### Minimal reproduction project

[NewGameProject.zip](https://github.com/godotengine/godot/files/10393234/NewGameProject.zip)

**Comment by qarmin** [comment]
```
==315881==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6040011d5c08 at pc 0x00001e4c2939 bp 0x7ffcafdf0810 sp 0x7ffcafdf0800
READ of size 4 at 0x6040011d5c08 thread T0
    #0 0x1e4c2938 in std::__atomic_base<unsigned int>::load(std::memory_order) const /usr/include/c++/11/bits/atomic_base.h:481
    #1 0x1e4c2938 in SafeNumeric<unsigned int>::get() const core/templates/safe_refcount.h:71
    #2 0x1e4c2938 in SafeRefCount::_check_unref_sanity() core/templates/safe_refcount.h:173
    #3 0x1e4c2938 in SafeRefCount::unref() core/templates/safe_refcount.h:191
    #4 0x1e4c2938 in Variant::PackedArrayRefBase::destroy(Variant::PackedArrayRefBase*) core/variant/variant.h:199
    #5 0x1e476ec9 in Variant::_clear_internal() core/variant/variant.cpp:1387
    #6 0x2746c2c in Variant::clear() core/variant/variant.h:302
    #7 0x2746e43 in Variant::~Variant() core/variant/variant.h:780
    #8 0x64924a6 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:3540
    #9 0x5d5a94a in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1847
    #10 0x1f0e3b4f in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:711
    #11 0x1e4f4a86 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1161
    #12 0x63bef13 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1583
    #13 0x5d5a94a in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1847
    #14 0x13bfa32d in bool Node::_gdvirtual__input_call<false>(Ref<InputEvent>) scene/main/node.h:244
    #15 0x13bad97c in Node::_call_input(Ref<InputEvent> const&) scene/main/node.cpp:2745
    #16 0x13cac745 in SceneTree::_call_input_pause(StringName const&, SceneTree::CallInputType, Ref<InputEvent> const&, Viewport*) scene/main/scene_tree.cpp:923
    #17 0x13e00eeb in Viewport::push_input(Ref<InputEvent> const&, bool) scene/main/viewport.cpp:2797
    #18 0x13f8f54f in Window::_window_input(Ref<InputEvent> const&) scene/main/window.cpp:1330
    #19 0x1409884e in void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) core/variant/binder_common.h:293
    #20 0x14082d53 in void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) core/variant/binder_common.h:407
    #21 0x14068e14 in CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const core/object/callable_method_pointer.h:104
    #22 0x1e43f21e in Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const core/variant/callable.cpp:50
    #23 0x2803818 in DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) platform/linuxbsd/x11/display_server_x11.cpp:3347
    #24 0x2802ad1 in DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) platform/linuxbsd/x11/display_server_x11.cpp:3318
    #25 0x1e249295 in Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) core/input/input.cpp:672
    #26 0x1e2529e1 in Input::flush_buffered_events() core/input/input.cpp:896
    #27 0x282c54b in DisplayServerX11::process_events() platform/linuxbsd/x11/display_server_x11.cpp:4356
    #28 0x27669f9 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:874
    #29 0x2743b44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #30 0x7faebac2350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #31 0x7faebac235c8 in __libc_start_main_impl ../csu/libc-start.c:381
    #32 0x27434f4 in _start (/usr/bin/godot4s+0x27434f4)

0x6040011d5c08 is located 8 bytes to the left of 48-byte region [0x6040011d5c10,0x6040011d5c40)
allocated by thread T0 here:
    #0 0x7faebb8b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x1d80aa25 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x27464a5 in DefaultAllocator::alloc(unsigned long) core/os/memory.h:65
    #3 0x1d80a959 in operator new(unsigned long, void* (*)(unsigned long)) core/os/memory.cpp:44
    #4 0x403228e in List<Ref<InputEvent>, DefaultAllocator>::push_back(Ref<InputEvent> const&) core/templates/list.h:290
    #5 0x1e252077 in Input::parse_input_event(Ref<InputEvent> const&) core/input/input.cpp:883
    #6 0x27fa650 in DisplayServerX11::_handle_key_event(int, XKeyEvent*, LocalVector<_XEvent, unsigned int, false, false>&, unsigned int&, bool) platform/linuxbsd/x11/display_server_x11.cpp:3107
    #7 0x2825dc0 in DisplayServerX11::process_events() platform/linuxbsd/x11/display_server_x11.cpp:4235
    #8 0x27669f9 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:874
    #9 0x2743b44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #10 0x7faebac2350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/11/bits/atomic_base.h:481 in std::__atomic_base<unsigned int>::load(std::memory_order) const

```

**Comment by akien-mga** [comment]
Given the backtrace, it's a duplicate of #71177
