### ISSUE TITLE
GLTF Fatal error: Attempted to read or write protected memory. (C#)

### ISSUE THREAD

**Issue by derplayer** [godotengine/godot#72200]
### Godot version

4.0b16

### System information

Windows 11

### Issue description

Godot game (not the editor) crashes by loading a specific ".glb" model via `Godot.GltfDocument.AppendFromFile` (in C#, not tested in GDScript). The model is exported via Blender, and runs on Godot 4.0 Beta 15 without any problems.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication t.
   at Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr, IntPtr, Void**, Void*)
   at Godot.NativeCalls.godot_icall_4_467(IntPtr, IntPtr, System.String, IntPtr, UInt32, System.String)
   at Godot.GltfDocument.AppendFromFile(System.String, Godot.GltfState, UInt32, System.String)
   at dummy_scene._Ready()
   at Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPt)
   at Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariant)
   at dummy_scene.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantP)
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_v)
```

![image](https://user-images.githubusercontent.com/18738917/215181154-998d84b9-247b-4e8d-a1de-9bf400a1e567.png)

### Steps to reproduce

Run the dummy scene with affected GLTF code. (See MRP.)

### Minimal reproduction project

C# proj [Godot 4 b16 GLTF Crash.zip](https://github.com/godotengine/godot/files/10522482/Godot.4.b16.GLTF.Crash.zip)

GDScript proj [Godot.4.b16.GLTF.Crash.gdscript.zip](https://github.com/godotengine/godot/files/10543553/Godot.4.b16.GLTF.Crash.gdscript.zip)

**Comment by lyuma** [comment]
converted test proj to gdscript to make debugging easier. Crash still happens.
[Godot.4.b16.GLTF.Crash.gdscript.zip](https://github.com/godotengine/godot/files/10543553/Godot.4.b16.GLTF.Crash.gdscript.zip)

```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (551f5191e5dbc1d1a43f99b13d5dbbf7f598dc58)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] ???
[1] GLTFDocument::_parse_images (S:\repo\godot-fire\modules\gltf\gltf_document.cpp:3244)
[2] GLTFDocument::_parse_gltf_state (S:\repo\godot-fire\modules\gltf\gltf_document.cpp:7128)
[3] GLTFDocument::_parse (S:\repo\godot-fire\modules\gltf\gltf_document.cpp:6779)
[4] GLTFDocument::append_from_file (S:\repo\godot-fire\modules\gltf\gltf_document.cpp:7207)
[5] call_with_variant_args_ret_helper<GLTFDocument,enum Error,String,Ref<GLTFState>,unsigned int,String,0,1,2,3> (S:\repo\godot-fire\core\variant\binder_common.h:711)
[6] call_with_variant_args_ret_dv<GLTFDocument,enum Error,String,Ref<GLTFState>,unsigned int,String> (S:\repo\godot-fire\core\variant\binder_common.h:524)
[7] MethodBindTR<GLTFDocument,enum Error,String,Ref<GLTFState>,unsigned int,String>::call (S:\repo\godot-fire\core\object\method_bind.h:467)
[8] Object::callp (S:\repo\godot-fire\core\object\object.cpp:733)
[9] Variant::callp (S:\repo\godot-fire\core\variant\variant_call.cpp:1161)
[10] GDScriptFunction::call (S:\repo\godot-fire\modules\gdscript\gdscript_vm.cpp:1551)
[11] GDScriptInstance::callp (S:\repo\godot-fire\modules\gdscript\gdscript.cpp:1842)
[12] Node::_notification (S:\repo\godot-fire\scene\main\node.cpp:155)
[13] Node3D::_notificationv (S:\repo\godot-fire\scene\3d\node_3d.h:52)
[14] Object::notification (S:\repo\godot-fire\core\object\object.cpp:792)
[15] Node::_propagate_ready (S:\repo\godot-fire\scene\main\node.cpp:189)
[16] Node::_propagate_ready (S:\repo\godot-fire\scene\main\node.cpp:179)
[17] Node::_set_tree (S:\repo\godot-fire\scene\main\node.cpp:2608)
[18] SceneTree::initialize (S:\repo\godot-fire\scene\main\scene_tree.cpp:411)
[19] OS_Windows::run (S:\repo\godot-fire\platform\windows\os_windows.cpp:1292)
[20] widechar_main (S:\repo\godot-fire\platform\windows\godot_windows.cpp:181)
[21] _main (S:\repo\godot-fire\platform\windows\godot_windows.cpp:205)
[22] main (S:\repo\godot-fire\platform\windows\godot_windows.cpp:217)
[23] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[24] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```
