### ISSUE TITLE
Executing `RichTextLabel.add_image` use all available memory in Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#72232]
### Godot version

4.0.beta.custom_build. 3b086aa06

### System information

Ubuntu 22.10 - AMD RX 470, Gnome shell 43 X11

### Issue description

When executing
```
extends Node
func _process(delta):
	var temp_variable40250 = RichTextLabel.new()
	add_child(temp_variable40250)
	temp_variable40250.newline()
	temp_variable40250.scroll_to_line(37)
	temp_variable40250.clear()
	temp_variable40250.push_hint("1441747123")
	temp_variable40250.add_image(CurveTexture.new(), -56, 73, Color(-98.5438385009766, 21.4367141723633, 1.30602121353149, 1), -39, Rect2(Vector2(-22.0045146942139, 6.39376640319824), Vector2(-0.99382126331329, 0.1109923645854)))
```
Godot start to use all memory inside function:
```
0x0000000002d6fdb6 in Vector2::operator* (this=0x7fffffffc7f0, rvalue=@0x7fffffffc764: 0) at ./core/math/vector2.h:211
211	./core/math/vector2.h: Directory not empty.
(gdb) backtrace
#0  0x0000000002d6fdb6 in Vector2::operator* (this=0x7fffffffc7f0, rvalue=@0x7fffffffc764: 0) at ./core/math/vector2.h:211
#1  0x0000000007622322 in RendererCanvasCull::canvas_item_add_line (this=0xd02b1f0, p_item=..., p_from=..., p_to=..., p_color=..., p_width=0, p_antialiased=false)
    at servers/rendering/renderer_canvas_cull.cpp:593
#2  0x00000000070cec5a in RenderingServerDefault::canvas_item_add_line (this=0xd45ef10, p1=..., p2=..., p3=..., p4=..., p5=0, p6=false) at servers/rendering/rendering_server_default.h:847
#3  0x0000000005b0f012 in CanvasItem::draw_dashed_line (this=0xf6e5e50, p_from=..., p_to=..., p_color=..., p_width=0, p_dash=0, p_aligned=true) at scene/main/canvas_item.cpp:506
#4  0x0000000005ea90c0 in RichTextLabel::_draw_line (this=0xf6e5e50, p_frame=0xf43f460, p_line=0, p_ofs=..., p_width=1, p_base_color=..., p_outline_size=0, p_outline_color=..., p_font_shadow_color=..., 
    p_shadow_outline_size=1, p_shadow_ofs=..., r_processed_glyphs=@0x7fffffffcfe4: 1) at scene/gui/rich_text_label.cpp:1366
#5  0x0000000005eaf3da in RichTextLabel::_notification (this=0xf6e5e50, p_what=30) at scene/gui/rich_text_label.cpp:1859
#6  0x0000000005ed4d98 in RichTextLabel::_notificationv (this=0xf6e5e50, p_notification=30, p_reversed=false) at scene/gui/rich_text_label.h:40
#7  0x0000000007e78da9 in Object::notification (this=0xf6e5e50, p_notification=30, p_reversed=false) at core/object/object.cpp:790
#8  0x0000000005b0d361 in CanvasItem::_redraw_callback (this=0xf6e5e50) at scene/main/canvas_item.cpp:135
#9  0x00000000048c133b in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0xf6e5e50, 
    p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x5b0d2c6 <CanvasItem::_redraw_callback()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:293
#10 0x00000000048be7cd in call_with_variant_args<CanvasItem> (p_instance=0xf6e5e50, p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x5b0d2c6 <CanvasItem::_redraw_callback()>, p_args=0x0, p_argcount=0, 
    r_error=...) at ./core/variant/binder_common.h:407
#11 0x00000000048ba4ed in CallableCustomMethodPointer<CanvasItem>::call (this=0xf636130, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#12 0x0000000007acd405 in Callable::callp (this=0x7fffe25f6038, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#13 0x0000000007e725e0 in MessageQueue::_call_function (this=0xca669f0, p_callable=..., p_args=0x7fffe25f6050, p_argcount=0, p_show_error=false) at core/object/message_queue.cpp:229
#14 0x0000000007e72947 in MessageQueue::flush (this=0xca669f0) at core/object/message_queue.cpp:275
#15 0x0000000005bbed2f in SceneTree::process (this=0xf474b70, p_time=0.14999999999999991) at scene/main/scene_tree.cpp:469
#16 0x00000000027c738f in Main::iteration () at main/main.cpp:3125
#17 0x000000000273eac8 in OS_LinuxBSD::run (this=0x7fffffffd720) at platform/linuxbsd/os_linuxbsd.cpp:878
#18 0x00000000027352d5 in main (argc=2, argv=0x7fffffffdc68) at platform/linuxbsd/godot_linuxbsd.cpp:73
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visibe when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

### Steps to reproduce

Above

### Minimal reproduction project

N/A

**Comment by qarmin** [comment]
Cannot reproduce
