### ISSUE TITLE
Executing `Image.save_webp_to_buffer` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#72230]
### Godot version

4.0.beta.custom_build. 3b086aa06

### System information

Ubuntu 22.10 - AMD RX 470, Gnome shell 43 X11

### Issue description

When executing
```
extends Node
func _process(delta):

	var temp_variable20469 = Image.new()
	temp_variable20469.set_pixel(-2, 63, Color(53.7764778137207, 46.6460571289062, -89.9723129272461, 1))
	temp_variable20469.crop(7, 30)
	temp_variable20469.compress_from_channels(2, 38, 90.1475071907043, 49)
	temp_variable20469.save_webp_to_buffer(false, 38.4097218513489)

```
Godot crashes:
```
==7945==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6120008e76d0 at pc 0x00000c453515 bp 0x7ffe0a3ddb40 sp 0x7ffe0a3ddb30
READ of size 16 at 0x6120008e76d0 thread T0
    #0 0xc453514 in _mm_loadu_si128 /usr/lib/gcc/x86_64-linux-gnu/11/include/emmintrin.h:703
    #1 0xc453514 in ConvertBGRAToRGBA_SSE2 thirdparty/libwebp/src/dsp/lossless_sse2.c:539
    #2 0xc3635f0 in Import thirdparty/libwebp/src/enc/picture_csp_enc.c:785
    #3 0xc363bb9 in WebPPictureImportRGBA thirdparty/libwebp/src/enc/picture_csp_enc.c:843
    #4 0xc34c454 in WebPCommon::_webp_packer(Ref<Image> const&, float, bool) modules/webp/webp_common.cpp:97
    #5 0xc34b1fa in WebPCommon::_webp_lossless_pack(Ref<Image> const&) modules/webp/webp_common.cpp:53
    #6 0xc349bcc in ResourceSaverWebP::save_image_to_buffer(Ref<Image> const&, bool, float) modules/webp/resource_saver_webp.cpp:72
    #7 0x1e1397b5 in Image::save_webp_to_buffer(bool, float) const core/io/image.cpp:2561
    #8 0x1e231712 in void call_with_variant_args_retc_helper<__UnexistingClass, Vector<unsigned char>, bool, float, 0ul, 1ul>(__UnexistingClass*, Vector<unsigned char> (__UnexistingClass::*)(bool, float) const, Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul>) core/variant/binder_common.h:762
    #9 0x1e21b36d in void call_with_variant_args_retc_dv<__UnexistingClass, Vector<unsigned char>, bool, float>(__UnexistingClass*, Vector<unsigned char> (__UnexistingClass::*)(bool, float) const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:557
    #10 0x1e2097f7 in MethodBindTRC<Vector<unsigned char>, bool, float>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:544
    #11 0x1f4fcdb6 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #12 0x1e9042a8 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1161
    #13 0x66cc2b9 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1583
    #14 0x6051b34 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1842
    #15 0x1409ecb8 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #16 0x14003328 in Node::_notification(int) scene/main/node.cpp:57
    #17 0x4d6a2d7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #18 0x1f4fe30a in Object::notification(int, bool) core/object/object.cpp:790
    #19 0x14169343 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:874
    #20 0x1415b6f5 in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #21 0x2a4b819 in Main::iteration() main/main.cpp:3125
    #22 0x27a6277 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:878
    #23 0x2781b44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #24 0x7f977042350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #25 0x7f97704235c8 in __libc_start_main_impl ../csu/libc-start.c:381
    #26 0x27814f4 in _start (/usr/bin/godot4s+0x27814f4)

0x6120008e76d0 is located 0 bytes to the right of 272-byte region [0x6120008e75c0,0x6120008e76d0)
allocated by thread T0 here:
    #0 0x7f97710b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x1dc166a7 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x427de7e in Error CowData<unsigned char>::resize<false>(int) core/templates/cowdata.h:288
    #3 0x415fc67 in Vector<unsigned char>::resize(int) core/templates/vector.h:91
    #4 0x5fab00c in _compress_etcpak(EtcpakType, Image*, float) modules/etcpak/image_compress_etcpak.cpp:178
    #5 0x5fa9ad9 in _compress_etc2(Image*, float, Image::UsedChannels) modules/etcpak/image_compress_etcpak.cpp:83
    #6 0x1e13b75f in Image::compress_from_channels(Image::CompressMode, Image::UsedChannels, float, Image::ASTCFormat) core/io/image.cpp:2641
    #7 0x1e22e843 in void call_with_variant_args_ret_helper<__UnexistingClass, Error, Image::CompressMode, Image::UsedChannels, float, Image::ASTCFormat, 0ul, 1ul, 2ul, 3ul>(__UnexistingClass*, Error (__UnexistingClass::*)(Image::CompressMode, Image::UsedChannels, float, Image::ASTCFormat), Variant const**, Variant&, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul, 3ul>) core/variant/binder_common.h:711
    #8 0x1e2181d2 in void call_with_variant_args_ret_dv<__UnexistingClass, Error, Image::CompressMode, Image::UsedChannels, float, Image::ASTCFormat>(__UnexistingClass*, Error (__UnexistingClass::*)(Image::CompressMode, Image::UsedChannels, float, Image::ASTCFormat), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:524
    #9 0x1e207977 in MethodBindTR<Error, Image::CompressMode, Image::UsedChannels, float, Image::ASTCFormat>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:465
    #10 0x1f4fcdb6 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:733
    #11 0x1e9042a8 in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1161
    #12 0x66cc2b9 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1583
    #13 0x6051b34 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1842
    #14 0x1409ecb8 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:238
    #15 0x14003328 in Node::_notification(int) scene/main/node.cpp:57
    #16 0x4d6a2d7 in Node::_notificationv(int, bool) scene/main/node.h:46
    #17 0x1f4fe30a in Object::notification(int, bool) core/object/object.cpp:790
    #18 0x14169343 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:874
    #19 0x1415b6f5 in SceneTree::process(double) scene/main/scene_tree.cpp:466
    #20 0x2a4b819 in Main::iteration() main/main.cpp:3125
    #21 0x27a6277 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:878
    #22 0x2781b44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #23 0x7f977042350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/lib/gcc/x86_64-linux-gnu/11/include/emmintrin.h:703 in _mm_loadu_si128

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visibe when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

### Steps to reproduce

Above

### Minimal reproduction project

N/A

**Comment by qarmin** [comment]
Cannot reproduce
