### ISSUE TITLE
[C# Beta 16] Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.

### ISSUE THREAD

**Issue by valkyrienyanko** [godotengine/godot#72298]
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 10, RX 6600, 10400

### Issue description

Upon running the game, a popup comes up saying "Illegal Instruction An attempt was made to execute an illegal instruction", clicking "OK" closes the popup and game. The editor does not crash to the desktop when this happens.

![Preview](https://user-images.githubusercontent.com/6277739/215312384-ab68fdb0-9fbc-4dea-b953-cb4b8080d30c.PNG)

This issue does not happen on beta 12. I have not tested beta 13 through 15, but I know for sure it happens 100% of the time on beta 16.

Here are the full verbose editor logs.

[logs_full.txt](https://github.com/godotengine/godot/files/10529281/logs_full.txt)

And here is what I believe to be the relevant section of the verbose logs.

```cs
ERROR: Parameter "strong_gchandle.value" is null.
   at: setup_csharp_script_binding (modules/mono/csharp_script.cpp:1229)
ERROR: Condition "!script_binding.inited" is true. Returning: { nullptr }
   at: godotsharp_internal_unmanaged_get_instance_binding_managed (modules/mono/glue/runtime_interop.cpp:234)
ERROR: Parameter "strong_gchandle.value" is null.
   at: setup_csharp_script_binding (modules/mono/csharp_script.cpp:1229)
ERROR: Condition "!script_binding.inited" is true. Returning: { nullptr }
   at: godotsharp_internal_unmanaged_instance_binding_create_managed (modules/mono/glue/runtime_interop.cpp:247)
ERROR: FATAL: Condition "!rc_owner" is true.
   at: _instance_binding_reference_callback (modules/mono/csharp_script.cpp:1315)
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Godot.NativeInterop.NativeFuncs.godotsharp_ref_destroy(Godot.NativeInterop.godot_ref ByRef)
   at Godot.NativeInterop.godot_ref.Dispose()
   at Godot.NativeCalls.godot_icall_3_921(IntPtr, IntPtr, System.String, System.String, Int32)
   at Godot.ResourceLoader.Load(System.String, System.String, CacheMode)
   at Godot.ResourceLoader.Load[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String, System.String, CacheMode)
   at Sankari.Audio.LoadSFX(System.String, System.String)
   at Sankari.Audio.LoadSoundEffects()
   at Sankari.Audio.Init(Sankari.GAudioStreamPlayer, Godot.Node)
   at Sankari.GameManager..ctor(Sankari.Linker)
   at Sankari.Linker+<_Ready>d__54.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Sankari.Linker._Ready()
   at Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Sankari.Linker.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error*, Godot.NativeInterop.godot_variant*)
```

Note that no error is logged in the Godot console window in the editor. You must run Godot in verbose mode to see this.

The error points to `Sankari.Audio.LoadSFX(...)` which is this function in my game https://github.com/Valks-Games/sankari/blob/8b93b6f08a431ab1564e3d9bbc21d21d1bdacab8/Scripts/Static/Audio.cs#L136

Seems like something with `Godot.ResourceLoader.Load(...)` is acting up. Or maybe it's something to do with audio specifically?

### Steps to reproduce

1, Clone [https://github.com/Valks-Games/sankari](https://github.com/Valks-Games/sankari)
2. Make sure you are on C# beta 16
3. Run Godot editor in `--verbose` mode
4. Try to run the game
5. Notice the error popup and notice the logs from verbose console

### Minimal reproduction project

[sankari.zip](https://github.com/godotengine/godot/files/10529289/sankari.zip)

**Comment by valkyrienyanko** [comment]
Might be related to https://github.com/godotengine/godot/issues/72234 since all of my SFX are WAV files? After all my `LoadMusic(...)` function works just fine because all of my music are in MP3 format.

**Comment by valkyrienyanko** [comment]
~~Fixed in beta 17~~

Still happening in v4.5.stable.mono.official [876b29033]
