### ISSUE TITLE
Unhelpful error message when interpolating on a NaN transform

### ISSUE THREAD

**Issue by dominiks** [godotengine/godot#73299]
### Godot version

4.0.rc1 (custom build with double_precision)

### System information

Windows 10

### Issue description

In my project I'm interpolating moving mesh positions to their physics-body's location with the `get_physics_interpolation_fraction()` and `Transform3D::interpolate_with`. At some point I got this error message twice (this is taken from the provided example):

```
E 0:00:02:0117   InterpolationTest.gd:27 @ _ready(): Basis must be normalized in order to be casted to a Quaternion. Use get_rotation_quaternion() or call orthonormalized() if the Basis contains linearly independent vectors.
  <C++ Fehler>   Condition "!is_rotation()" is true. Returning: Quaternion()
  <C++ Source>   core\math\basis.cpp:702 @ Basis::get_quaternion()
  <Stacktrace>   InterpolationTest.gd:27 @ _ready()
```

followed by:

```
E 0:00:02:0127   RendererSceneCull::instance_set_transform: Condition "!v.is_finite()" is true.
  <C++ Source>   servers\rendering\renderer_scene_cull.cpp:906 @ RendererSceneCull::instance_set_transform()
```

`orthonormalized()` did not help, but in the end it turned out that I divided by zero at some point in my angles calculation and rotated the basis by `NaN`. This did not cause any issue (correctly?) but crashed when I tried to interpolate with a transform that resulted from that basis.

I feel like rotating the basis by `NaN` should have already resulted in an error or - if it is allowed to `move_and_slide` with a `NaN` transform - that the error message of `interpolate_with` should be more helpful here.

### Steps to reproduce

Run this scene to reproduce the issue

```gdscript
extends CharacterBody3D


var _mesh_instance := MeshInstance3D.new()
var _this_is_zero := 0.0

func _init() -> void:
    _mesh_instance.top_level = true
    add_child(_mesh_instance)


func _ready() -> void:
    # Set the rotation of this CharacterBody3D
    var new_basis := Basis()
    new_basis = new_basis.rotated(Vector3.UP, deg_to_rad(1 / _this_is_zero))
    # The basis now has NaN for all its values.
    transform.basis = new_basis
        
    # Move forward
    var old_transform = global_transform
    velocity = Vector3.FORWARD
    move_and_slide()
    var new_transform = global_transform
    
    # Interpolate the mesh half way to the physical position
    var current_transform = global_transform
    _mesh_instance.transform = old_transform.interpolate_with(new_transform, 0.5)

```

### Minimal reproduction project

N/A

**Comment by squk** [comment]
Dividing by 0 in a lerp caused the same error for me. Thanks!

**Comment by LautaroCepeda-Developer** [comment]
At the moment i find a temporal solution. Insert the animation key's trough the inspector (Godot 4.2)
![image](https://github.com/godotengine/godot/assets/123782531/4630ea17-4750-43c4-adc1-fcda33dd8c34)

**Comment by oxygen** [comment]
I'm only getting this which is unhelpful for debugging:

```
E 0:00:49:0960   instance_set_transform: Condition "!v.is_finite()" is true.
  <C++ Source>   servers/rendering/renderer_scene_cull.cpp:935 @ instance_set_transform()
```

Everything worked fine until I did some lookAt somewhere in some new code for one of the lights (I think, still debugging).

**Comment by RichardEllicott** [comment]
i get haunted by this bug when using animations

it plumpteds my frames in editor, can't dividing by zero just give back infinite? it would be some max value

**Comment by huttyblue** [comment]
The specific wording has changed but its not better so this bug is still present in 4.4-stable-mono. 

`ERROR: System.InvalidOperationException: Quaternion is not normalized.
   at Godot.Quaternion.Slerp(Quaternion to, Single weight) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs:line 394
   at Godot.Transform3D.InterpolateWith(Transform3D transform, Single weight) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Transform3D.cs:line 140
   at IronSirenGd4Csharp2.SCRIPTS.ENTITY_LOGIC.LOGIC_BOSS_02.<run_routines>g__face_towards_target|6_0(<>c__DisplayClass6_0&) in C:\Users\---project path---\SCRIPTS\ENTITY_LOGIC\LOGIC_BOSS_02.cs:line 800
`

line 800
`e.current_transform = e.current_transform.InterpolateWith(e.current_transform.LookingAt(e.xyz + face_direction.Normalized(), new Vector3(0, 1, 0)), delta * rotation_speed);`

e.current_transform was defined with `current_transform = new Transform3D(new Basis(), xyz);` in another file

Changing `new Basis()`, into `new Basis(new Vector3(0,1,0),0.0f)` in my code has fixed it on my end, but it took me 2 hours of troubleshooting because the error is misleading. I'm not directly interacting with quaternions here, and the solution to making the error go away does not involve normalizing anything.

**Comment by TokageItLab** [comment]
I don't think the warning is unhelpful.

It is true that an unnormalized Quaternion is being passed to `interpolate_with()`.

However, even if you normalize a non-normalizable matrix and then pass it to `interpolate_with()`, it will still pass an unnormalized matrix.

Therefore, the issue here is that the error does not indicate the passed matrix or quaternion is non-normalizable. I conclude that what is needed is for the normalization function to detect cases where the length is 0 or `is_finite`.

**Comment by huttyblue** [comment]
Error messages that talk about something going wrong in godot's internal hidden code are not helpful for user-side scripting errors, they need to show the user what they did wrong in the code they typed, without needing knowledge of how it works in godot's source. 

In the code I'm interpolating two transforms, if there is something wrong with the transform's compatibility with the function then the error should say that. 

Telling the user that the "matrix or quaternion is non-normalizable" isn't very helpful. 
- I didn't pass in a matrix, the type on the function input is Transform3D. You can't expect the user to know a transform is a matrix internally.
- quaternions are also not Transform3D objects, they aren't even mentioned on the Transfrom3D docs page. 
- non-normalizable? why does that matter? I'm not trying to normalize anything, I just want to interpolate my two transforms.

**Comment by TokageItLab** [comment]
Again, the warning already says "normalization is required for interpolation", so this should not be useless. If we were to improve the message here, it would only be to make it clearer, like adding some words `"The input values" must be normalized`. It's useless to say anything to users who ignore errors.

In this issue's case, the problem is that even though the user performed the normalization indicated by the error, the result was not normalized, and the user couldn't tell this from the error.

Simplified, the result of `Basis(INF).normalized()` is `Basis(NaN)`, and in either case, it is not normalized even if it is result of the normalization.

Therefore, the correct approach should be to indicate that the normalization result is not normalized and inform the user to correct the values before normalization.
