### ISSUE TITLE
Changing 3D collision shape when running physics on separate thread crashes

### ISSUE THREAD

**Issue by jivvy** [godotengine/godot#73573]
### Godot version

v4.0.rc.custom_build [aa6ec7631]

### System information

Arch Linux, Radeon RX 6700 XT, Ryzen 5 3600

### Issue description

Using the example of a crouching mechanic, changing the collision shape for the crouch on a CharacterBody3D will cause it to suddenly crash.

Sometimes it just says `realloc(): invalid next size` in the console, and no other error. Sometimes it gives a crash like this:
```
ERROR: FATAL: Index p_index = 4294967295 is out of bounds (count = 2).
   at: operator[] (./core/templates/local_vector.h:168)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.rc.custom_build (aa6ec763179e5bf1d1300aa72dc5f4172d810efa)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38f50) [0x7fa5c131df50] (??:0)
[2] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.editor.x86_64(+0x4382f17) [0x556db496bf17] (??:0)
[3] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.editor.x86_64(+0x43878e1) [0x556db49708e1] (??:0)
[4] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.editor.x86_64(+0xb5a787) [0x556db1143787] (??:0)
[5] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.editor.x86_64(+0x4352960) [0x556db493b960] (??:0)
[6] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.editor.x86_64(+0x46d9625) [0x556db4cc2625] (??:0)
[7] /mnt/data-drive/code/downloads/godot/bin/godot.linuxbsd.editor.x86_64(+0x4fb5b23) [0x556db559eb23] (??:0)
[8] /usr/lib/libc.so.6(+0x85bb5) [0x7fa5c136abb5] (??:0)
[9] /usr/lib/libc.so.6(+0x107d90) [0x7fa5c13ecd90] (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Have a character body with two collision shape, with one disabled
2. Add gravity, WASD, camera movement etc.
3. Use a e.g. crouch key to switch between the collision shapes
4. Turn on physics/3d/run_on_separate_thread
5. Especially common when standing on a pile of RigidBodies
6. Enjoy

### Minimal reproduction project

Relatively stripped away reproduction project:
https://drive.google.com/uc?export=download&id=1shYnp3GkVMfHOSKFQtUpA3YUW23QJBZY

**Comment by Calinou** [comment]
Backtrace

```
WARNING: Info : multithread BVH access detected (benign)
     at: BVHLockedFunction (./core/math/bvh.h:784)
ERROR: FATAL: Index p_index = 270437280 is out of bounds (count = 24).
   at: operator[] (./core/templates/local_vector.h:168)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.rc.custom_build (f2a2e470099c83ea8a5a1f78c910cbdd11ab4998)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x3cb20) [0x7fd6cb77fb20] (??:0)
[2] bin/godot.linuxbsd.editor.x86_64() [0x7567c39] (/home/hugo/Documents/Git/godotengine/godot/./core/templates/local_vector.h:168)
[3] bin/godot.linuxbsd.editor.x86_64() [0x75687cc] (/home/hugo/Documents/Git/godotengine/godot/./core/math/bvh_public.inc:305)
[4] bin/godot.linuxbsd.editor.x86_64() [0x7568986] (/home/hugo/Documents/Git/godotengine/godot/./core/math/bvh.h:549)
[5] bin/godot.linuxbsd.editor.x86_64() [0x756534f] (/home/hugo/Documents/Git/godotengine/godot/./core/math/bvh.h:585)
[6] bin/godot.linuxbsd.editor.x86_64() [0x7563a2f] (/home/hugo/Documents/Git/godotengine/godot/./core/math/bvh.h:459)
[7] bin/godot.linuxbsd.editor.x86_64() [0x75630f3] (/home/hugo/Documents/Git/godotengine/godot/./core/math/bvh.h:307)
[8] bin/godot.linuxbsd.editor.x86_64() [0x75620c0] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_3d/godot_broad_phase_3d_bvh.cpp:119)
[9] bin/godot.linuxbsd.editor.x86_64() [0x76e9205] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_3d/godot_space_3d.cpp:1183)
[10] bin/godot.linuxbsd.editor.x86_64() [0x76eec03] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_3d/godot_step_3d.cpp:228)
[11] bin/godot.linuxbsd.editor.x86_64() [0x768b768] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_3d/godot_physics_server_3d.cpp:1645)
[12] bin/godot.linuxbsd.editor.x86_64() [0x7287e47] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_server_3d_wrap_mt.cpp:41)
[13] bin/godot.linuxbsd.editor.x86_64() [0x72a1d41] (/home/hugo/Documents/Git/godotengine/godot/./core/templates/command_queue_mt.h:322 (discriminator 4))
[14] bin/godot.linuxbsd.editor.x86_64() [0x71fee46] (/home/hugo/Documents/Git/godotengine/godot/./core/templates/command_queue_mt.h:374)
[15] bin/godot.linuxbsd.editor.x86_64() [0x71fef8f] (/home/hugo/Documents/Git/godotengine/godot/./core/templates/command_queue_mt.h:414)
[16] bin/godot.linuxbsd.editor.x86_64() [0x7287f2c] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_server_3d_wrap_mt.cpp:57)
[17] bin/godot.linuxbsd.editor.x86_64() [0x7287eb8] (/home/hugo/Documents/Git/godotengine/godot/servers/physics_server_3d_wrap_mt.cpp:48)
[18] bin/godot.linuxbsd.editor.x86_64() [0x88d72ca] (/home/hugo/Documents/Git/godotengine/godot/core/os/thread.cpp:67)
[19] bin/godot.linuxbsd.editor.x86_64() [0x88d8135] (/usr/include/c++/12/bits/invoke.h:61)
[20] bin/godot.linuxbsd.editor.x86_64() [0x88d7ffe] (/usr/include/c++/12/bits/invoke.h:97)
[21] bin/godot.linuxbsd.editor.x86_64() [0x88d7eb9] (/usr/include/c++/12/bits/std_thread.h:258)
[22] bin/godot.linuxbsd.editor.x86_64() [0x88d7e1e] (/usr/include/c++/12/bits/std_thread.h:265)
[23] bin/godot.linuxbsd.editor.x86_64() [0x88d7e02] (/usr/include/c++/12/bits/std_thread.h:210)
[24] bin/godot.linuxbsd.editor.x86_64() [0x94661c3] (msdf-error-correction.cpp:?)
[25] /lib64/libc.so.6(+0x8b12d) [0x7fd6cb7ce12d] (??:0)
[26] /lib64/libc.so.6(+0x10cbc0) [0x7fd6cb84fbc0] (??:0)
-- END OF BACKTRACE --
================================================================
[1]    72661 IOT instruction (core dumped)  bin/godot.linuxbsd.editor.x86_64 --path ~/Downloads/CollisionChangeCrash/
```

Standing on top of all the cylinders without crouching also causes a heavy slowdown (noticeable if you rotate the camera while on the cylinders).

**Comment by qarmin** [comment]
```
==73423==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000fe12d0 at pc 0x00001cf3143e bp 0x7fff8d9ec5b0 sp 0x7fff8d9ec5a0
core/templates/local_vector.h:74:4: runtime error: store to null pointer of type 'struct Link'
WRITE of size 16 at 0x603000fe12d0 thread T0

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.rc.custom_build (8c7b98d4526c6ba66d7f1636abb71ccbe54727c6)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
    #0 0x1cf3143d in LocalVector<BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::Link, unsigned int, false, false>::push_back(BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::Link) (/usr/bin/godot4s+0x1cf3143d)
    #1 0x1cf21bf1 in BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::add_pair_to(BVHHandle, void*) (/usr/bin/godot4s+0x1cf21bf1)
    #2 0x1cf0d35f in BVH_Manager<GodotCollisionObject3D, 2, true, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, AABB, Vector3, true>::_collide(BVHHandle, BVHHandle) (/usr/bin/godot4s+0x1cf0d35f)
    #3 0x1cf02168 in BVH_Manager<GodotCollisionObject3D, 2, true, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, AABB, Vector3, true>::_check_for_collisions(bool) (/usr/bin/godot4s+0x1cf02168)
    #4 0x1cefc726 in BVH_Manager<GodotCollisionObject3D, 2, true, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, AABB, Vector3, true>::create(GodotCollisionObject3D*, bool, unsigned int, unsigned int, AABB const&, int) core/math/bvh.h:127
    #5 0x1cef8dce in GodotBroadPhase3DBVH::create(GodotCollisionObject3D*, int, AABB const&, bool) servers/physics_3d/godot_broad_phase_3d_bvh.cpp:38
    #6 0x1cf42032 in GodotCollisionObject3D::_update_shapes() servers/physics_3d/godot_collision_object_3d.cpp:177
    #7 0x1cf4579f in GodotCollisionObject3D::_shape_changed() servers/physics_3d/godot_collision_object_3d.cpp:234
    #8 0x1a9967f2 in GodotPhysicsServer3D::_update_shapes() servers/physics_3d/godot_physics_server_3d.cpp:1735
    #9 0x1a979e4b in GodotPhysicsServer3D::body_test_motion(RID, PhysicsServer3D::MotionParameters const&, PhysicsServer3D::MotionResult*) servers/physics_3d/godot_physics_server_3d.cpp:918
    #10 0x1cd563ed in PhysicsServer3DWrapMT::body_test_motion(RID, PhysicsServer3D::MotionParameters const&, PhysicsServer3D::MotionResult*) servers/physics_server_3d_wrap_mt.h:265
    #11 0x16577f11 in PhysicsBody3D::move_and_collide(PhysicsServer3D::MotionParameters const&, PhysicsServer3D::MotionResult&, bool, bool) scene/3d/physics_body_3d.cpp:117
    #12 0x165c4907 in CharacterBody3D::_move_and_slide_grounded(double, bool) scene/3d/physics_body_3d.cpp:1280
    #13 0x165c0bc7 in CharacterBody3D::move_and_slide() scene/3d/physics_body_3d.cpp:1228
    #14 0x4fe6ff5 in void call_with_ptr_args_ret_helper<__UnexistingClass, bool>(__UnexistingClass*, bool (__UnexistingClass::*)(), void const**, void*, IndexSequence<>) core/variant/binder_common.h:324
    #15 0x4fd2fcf in void call_with_ptr_args_ret<__UnexistingClass, bool>(__UnexistingClass*, bool (__UnexistingClass::*)(), void const**, void*) core/variant/binder_common.h:572
    #16 0x4fbf41b in MethodBindTR<bool>::ptrcall(Object*, void const**, void*) const core/object/method_bind.h:478
    #17 0x687fd21 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1894
    #18 0x618a4fc in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1826
    #19 0x142e8bf8 in bool Node::_gdvirtual__physics_process_call<false>(double) scene/main/node.h:239
    #20 0x1424a87b in Node::_notification(int) scene/main/node.cpp:61
    #21 0x42318d9 in Node::_notificationv(int, bool) scene/main/node.h:46
    #22 0x4f408c8 in Node3D::_notificationv(int, bool) scene/3d/node_3d.h:52
    #23 0x15c8d226 in CollisionObject3D::_notificationv(int, bool) scene/3d/collision_object_3d.h:38
    #24 0x16663fb2 in PhysicsBody3D::_notificationv(int, bool) scene/3d/physics_body_3d.h:43
    #25 0x1667a63c in CharacterBody3D::_notificationv(int, bool) scene/3d/physics_body_3d.h:344
    #26 0x1f911b62 in Object::notification(int, bool) core/object/object.cpp:790
    #27 0x143b0ec1 in SceneTree::_notify_group_pause(StringName const&, int) scene/main/scene_tree.cpp:874
    #28 0x143a1030 in SceneTree::physics_process(double) scene/main/scene_tree.cpp:428
    #29 0x2a8b091 in Main::iteration() main/main.cpp:3121
    #30 0x27e2277 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:880
    #31 0x27bdb44 in main platform/linuxbsd/godot_linuxbsd.cpp:73
    #32 0x7efec122350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #33 0x7efec12235c8 in __libc_start_main_impl ../csu/libc-start.c:381
    #34 0x27bd4f4 in _start (/usr/bin/godot4s+0x27bd4f4)

0x603000fe12d0 is located 0 bytes to the right of 32-byte region [0x603000fe12b0,0x603000fe12d0)
allocated by thread T0 here:
    #0 0x7efec1eb4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x1e007c4b in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x1e0082b2 in Memory::realloc_static(void*, unsigned long, bool) core/os/memory.cpp:99
    #3 0x1cf31133 in LocalVector<BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::Link, unsigned int, false, false>::push_back(BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::Link) (/usr/bin/godot4s+0x1cf31133)
    #4 0x1cf21bf1 in BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::add_pair_to(BVHHandle, void*) (/usr/bin/godot4s+0x1cf21bf1)
    #5 0x1cf0d35f in BVH_Manager<GodotCollisionObject3D, 2, true, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, AABB, Vector3, true>::_collide(BVHHandle, BVHHandle) (/usr/bin/godot4s+0x1cf0d35f)
    #6 0x1cf02168 in BVH_Manager<GodotCollisionObject3D, 2, true, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, AABB, Vector3, true>::_check_for_collisions(bool) (/usr/bin/godot4s+0x1cf02168)
    #7 0x1cefc726 in BVH_Manager<GodotCollisionObject3D, 2, true, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, AABB, Vector3, true>::create(GodotCollisionObject3D*, bool, unsigned int, unsigned int, AABB const&, int) core/math/bvh.h:127
    #8 0x1cef8dce in GodotBroadPhase3DBVH::create(GodotCollisionObject3D*, int, AABB const&, bool) servers/physics_3d/godot_broad_phase_3d_bvh.cpp:38
    #9 0x1cf42032 in GodotCollisionObject3D::_update_shapes() servers/physics_3d/godot_collision_object_3d.cpp:177
    #10 0x1cf4579f in GodotCollisionObject3D::_shape_changed() servers/physics_3d/godot_collision_object_3d.cpp:234
    #11 0x1a9967f2 in GodotPhysicsServer3D::_update_shapes() servers/physics_3d/godot_physics_server_3d.cpp:1735
    #12 0x1a979e4b in GodotPhysicsServer3D::body_test_motion(RID, PhysicsServer3D::MotionParameters const&, PhysicsServer3D::MotionResult*) servers/physics_3d/godot_physics_server_3d.cpp:918
    #13 0x1cd563ed in PhysicsServer3DWrapMT::body_test_motion(RID, PhysicsServer3D::MotionParameters const&, PhysicsServer3D::MotionResult*) servers/physics_server_3d_wrap_mt.h:265
    #14 0x16577f11 in PhysicsBody3D::move_and_collide(PhysicsServer3D::MotionParameters const&, PhysicsServer3D::MotionResult&, bool, bool) scene/3d/physics_body_3d.cpp:117
    #15 0x165c4907 in CharacterBody3D::_move_and_slide_grounded(double, bool) scene/3d/physics_body_3d.cpp:1280
    #16 0x165c0bc7 in CharacterBody3D::move_and_slide() scene/3d/physics_body_3d.cpp:1228
    #17 0x4fe6ff5 in void call_with_ptr_args_ret_helper<__UnexistingClass, bool>(__UnexistingClass*, bool (__UnexistingClass::*)(), void const**, void*, IndexSequence<>) core/variant/binder_common.h:324
    #18 0x4fd2fcf in void call_with_ptr_args_ret<__UnexistingClass, bool>(__UnexistingClass*, bool (__UnexistingClass::*)(), void const**, void*) core/variant/binder_common.h:572
    #19 0x4fbf41b in MethodBindTR<bool>::ptrcall(Object*, void const**, void*) const core/object/method_bind.h:478
    #20 0x687fd21 in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1894
    #21 0x618a4fc in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1826
    #22 0x142e8bf8 in bool Node::_gdvirtual__physics_process_call<false>(double) scene/main/node.h:239
    #23 0x1424a87b in Node::_notification(int) scene/main/node.cpp:61
    #24 0x42318d9 in Node::_notificationv(int, bool) scene/main/node.h:46
    #25 0x4f408c8 in Node3D::_notificationv(int, bool) scene/3d/node_3d.h:52
    #26 0x15c8d226 in CollisionObject3D::_notificationv(int, bool) scene/3d/collision_object_3d.h:38
    #27 0x16663fb2 in PhysicsBody3D::_notificationv(int, bool) scene/3d/physics_body_3d.h:43
    #28 0x1667a63c in CharacterBody3D::_notificationv(int, bool) scene/3d/physics_body_3d.h:344
    #29 0x1f911b62 in Object::notification(int, bool) core/object/object.cpp:790

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/bin/godot4s+0x1cf3143d) in LocalVector<BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::Link, unsigned int, false, false>::push_back(BVH_Tree<GodotCollisionObject3D, 2, 2, 128, GodotBroadPhase3DBVH::UserPairTestFunction<GodotCollisionObject3D>, GodotBroadPhase3DBVH::UserCullTestFunction<GodotCollisionObject3D>, true, AABB, Vector3>::ItemPairs::Link)

```

**Comment by akien-mga** [comment]
CC @lawnjelly

**Comment by lawnjelly** [comment]
Will take a look. :+1: 

This isn't entirely surprising, the BVH was originally designed as single threaded, I added a simple multithreaded mode later with a mutex to investigate whether threaded access was causing a bug in 3.x (which turned out to be unrelated I think) .. but historically the multithreaded BVH mode has never been fully tested, so may well contain a bug (maybe I missed a function that bypasses the mutex for example).
