### ISSUE TITLE
Editor crashes for no reason

### ISSUE THREAD

**Issue by xahon** [godotengine/godot#75131]
### Godot version

4.0-dev

### System information

Windows 10

### Issue description

Crashes randomly for no obvious reasons. The most likely when I stop the game
Logs from `%appdata%/Godot/app_userdata/<Project>` are as useless as that:
```
Godot Engine v4.0.stable.mono.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB
 
200
```

### Steps to reproduce

No clear steps known to me

### Minimal reproduction project

I can't send you my project. Tell me where to find more useful logs or how to track the issue down myself

**Comment by xahon** [comment]
I guess it's not a crash log. 200 is my variable printed into log. Where to find crash log?

**Comment by xahon** [comment]
Now it crashed when I clicked Stop button. The game was still playing

**Comment by dalexeev** [comment]
> Where to find crash log?

Launch Godot from the command line.

**Comment by xahon** [comment]
It's a very unpleasant way to get crash info to be honest

Here is the crash data:
```
Godot Engine v4.0.stable.mono.official.92bee43ad - https://godotengine.org
ERROR: FATAL: Condition "gchandle.is_released()" is true.
   at: mono_object_disposed_baseref (modules/mono/csharp_script.cpp:1771)
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_refcounted_disposed(IntPtr, IntPtr, Godot.NativeInterop.godot_bool)
E   at Godot.GodotObject.Dispose(Boolean)
R   at Godot.GodotObject.Finalize()
ROR: System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at Godot.Bridge.CSharpInstanceBridge.SerializeState(IntPtr godotObjectGCHandle, godVulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB
```

**Comment by dalexeev** [comment]
I'm unsure about C#, but a crash dump usually looks like:

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta.custom_build (7a0a3fea94e9fc70736ef93f2a024e023d53d6ed)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[...]
-- END OF BACKTRACE --
```

**Comment by xahon** [comment]
I don't know, it doesn't write anything else except what I posted above

**Comment by trudeaua-vividream-software** [comment]
Editor version: v4.0.1.stable.mono.official [cacf49999]

I'm hitting this issue as well pretty frequently (maybe once or twice per hour), with the following stack trace:

```
Running: C:/Users/UserNameRedacted/Documents/Programs/Godot_v4.0.1-stable_mono_win64/Godot_v4.0.1-stable_mono_win64.exe --path C:/Users/UserNameRedacted/ProjectNameRedacted --remote-debug tcp://127.0.0.1:6007 --editor-pid 9684 --position 680,75 res://Contexts/Game/Game.tscn
Godot Engine v4.0.1.stable.mono.official.cacf49999 - https://godotengine.org
Vulkan API 1.2.194 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050

ERROR: AttemCopying Godot Offline Packages...
ERROR: FATAL: Condition "gchandle.is_released()" is true.
   at: mono_object_disposed_baseref (modules/mono/csharp_script.cpp:1770)
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_refcounted_disposed(IntPtr, IntPtr, Godot.NativeInterop.godot_bool)
   at Godot.GodotObject.Dispose(Boolean)
   at Godot.GodotObject.Finalize()
ERROR: System.InvalidOperationException:
```

I've also gotten this crash/stack trace while doing things other than running a scene (saving, building, clicking on the "Node" tab, etc.

> For more information attach a mixed mode debugger (ie start the project from visual studio and enable native debugging) and possibly use a debug build of the engine.

Is [this repo](https://github.com/Calinou/godot-debug-builds) the official place to get such a build? I'd be willing to daily drive it for a little bit to try to get some more info on why these random crashes keep happening.

**Comment by Calinou** [comment]
> Is [this repo](https://github.com/Calinou/godot-debug-builds) the official place to get such a build? I'd be willing to daily drive it for a little bit to try to get some more info on why these random crashes keep happening.

It's not official, but it's a place to get debug builds from.

**Comment by RedworkDE** [comment]
[Instructions for building from source with .NET](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html), note that on the first build you will get a message box about an error, but you can just ignore that the build will work just fine.

If you can create an MRP / a fairly reliable set of instructions for this crash I can take a look as well.

If you want to try and narrow down you project: From what I can see from the code around the crash, likely relevant are:
1. Creating objects from C#
2. Creating objects elsewhere and passing them to C#
3. Disposing of objects from C#
4. Loosing all references to an object in C# so that it gets garbage collected
5. Possibly doing these things multi-threaded
6. The object in particular that has caused the crash was a RefCounted, eg not a node
7. Building the project likely helps triggering the crash because with the build every single managed object gets garbage collected and recreated afterwards

**Comment by trudeaua-vividream-software** [comment]
Thanks for the help! I haven't been able to encounter the crash in the debug build yet - however, I'm probably going to stop looking into this for now since I'm moving my project back to Godot 3 for the time being (due to 4 not having mobile support for Mono yet). I may kick around and try to narrow down what's needed for an MRP in my free time, but I can't really guarantee that will happen anytime soon. Sorry!

**Comment by trudeaua-vividream-software** [comment]
> @trudeaua-vividream-software @xahon by chance, were you using TileData objects in your project?

@germanbv No, I wasn't using TileData objects.

**Comment by ryynosaur** [comment]
I've had the same crash using 4.1.1.mono.stable

I've narrowed the cause down to the following code being used inside an abstract class. When this code is move out of the abstract class I no longer get the error:

```
    public abstract partial class BasePopup : MarginContainer
    {
        private Tween Tween;

        [Node]
        protected PanelContainer Background;

        [Node]
        protected MarginContainer TweenContainer;


        [Signal]
        public delegate void ClosedEventHandler();

        protected void StartDisplay()
        {
            Tween = GlobalTweenFactory.CreateTween();

            TweenContainer.AddThemeConstantOverride("margin_top", 700);
            TweenContainer.Modulate = new Color(1, 1, 1, 0);

            Tween.SetParallel();
            Tween.TweenProperty(Background, "modulate", new Color(1, 1, 1, 1), 0.50f);
            Tween.TweenProperty(TweenContainer, "modulate", new Color(1, 1, 1, 1), 0.30f);
            Tween.TweenProperty(TweenContainer, "theme_override_constants/margin_top", 0, 0.40f).SetTrans(Tween.TransitionType.Quart);
        }

        protected void StartDestroy()
        {
            GlobalTweenFactory.DisposeProperly(Tween);

            Tween = GlobalTweenFactory.CreateTween();

            Tween.SetParallel();
            Tween.TweenProperty(Background, "modulate", new Color(1, 1, 1, 0), 0.50f);
            Tween.TweenProperty(TweenContainer, "modulate", new Color(1, 1, 1, 0), 0.30f);
            Tween.TweenProperty(TweenContainer, "theme_override_constants/margin_top", 700, 0.40f).SetTrans(Tween.TransitionType.Quart);
            Tween.SetParallel(false);
            Tween.TweenCallback(Callable.From(Destroy));

            GlobalInputManager.SetInputHandler(GlobalCurrentRunManager.CurrentWorld.MainGameInputManager);
            EmitSignal(SignalName.Closed);
        }

        public void Destroy()
        {
            GlobalTweenFactory.DisposeProperly(Tween);
            QueueFree();
        }
    }
```

This only started to crash once I started using Tween in the abstract class. Moving the above code out of the abstract class into the classes that were inheriting from it caused the crash to go away. Hope this helps!

**Comment by dxdesjardins** [comment]
I used to have similar issues and found the reason to be related to methods being called in C# Constructors.

If I absolutely must perform a method call in a constructor, I always use a deferred call with the below extension method:

`    public static async void CallDeferred(this GodotObject node, Action action, int frames = 1) {
        for (int i = 0; i < frames; i++)
            await node.ToSignal(Engine.GetMainLoop() as SceneTree, SceneTree.SignalName.ProcessFrame);
        action.Invoke();
    }`

**Comment by warent** [comment]
> I used to have similar issues and found the reason to be related to methods being called in C# Constructors. It was difficult to troubleshoot due to the exception stack not yielding much useful information, even when using visual studio.
> 
> If I absolutely must perform a method call in a constructor (cant use entertree or ready), I often use a deferred call with the below extension method. This seems to have fixed my crashes
> 
> ```
>     public static async void CallDeferred(this GodotObject obj, Action action, int frames = 1) {
>         for (int i = 0; i < frames; i++)
>             await obj.ToSignal(Engine.GetMainLoop() as SceneTree, SceneTree.SignalName.ProcessFrame);
>         action.Invoke();
>     }
> ```

Thank you! Every time I ran or built my project, I would get 1000s of errors like:
```
System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at Godot.Bridge.CSharpInstanceBridge.SerializeState(IntPtr godotObjectGCHandle
```
I could usually ignore them but it was obviously slowing down the editor when it happened. You're right, it's because I had logic in the constructor of a C# `[Tool]` class. When I moved it to _EnterTree as you suggested, I no longer get the errors.

**Comment by shana** [comment]
From the stacktrace, this looks to be a GC crash due to premature disposal of objects during scene transition/shutting down. Closing it as a duplicate of https://github.com/godotengine/godot/issues/83762, which goes into more detail about similar crashes.
