### ISSUE TITLE
2D-View: "Use Grid Snap" - loop in thread in git-tip

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#75749]
### Godot version

current git tip..

### System information

Linux

### Issue description

![grafik](https://user-images.githubusercontent.com/4047289/230362157-86299b5d-4667-4634-bff6-1648270273e4.png)
![grafik](https://user-images.githubusercontent.com/4047289/230363134-7196d413-a7cd-43b4-83fe-b89b6d3b926f.png)

### Steps to reproduce

Hit in the 2D view the _Use Grid Snap_ button or press _sh+g_
@akien-mga I fist thought could be internally SVG/TVG related but bisected it to:

bad 44d539465acca7592e0c88748e231fe5f151da37
good 2a275b985ef8a2af9ad07a3572bcfe693f58b7c1

git bisect good
Binary search: after that 75 commits left to test (about 6 steps)
[e359eaf4517c306721ad5818111c94b52559f649] Merge pull request #74319 from jbuck3/script-file-menu

Does anyone involved have idea which commit could causing this?
The header changes purge the scons-cache, it takes long time to compile, so I have to cancel further searching.

### Minimal reproduction project

Build a tip dev version, start an empty project, in the 2D-view press _sh+g_

<details><summary>ctrl-c in gdb</summary>

```
^C
Thread 1 "godot.linuxbsd." received signal SIGINT, Interrupt.
__sqrtf (x=0) at w_sqrtf_compat.c:30
30	w_sqrtf_compat.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __sqrtf (x=0) at w_sqrtf_compat.c:30
#1  0x000055555b39ae06 in Math::sqrt (p_x=<optimized out>) at ./core/math/math_funcs.h:90
#2  Vector2::length (this=this@entry=0x7fffffffd1f0) at core/math/vector2.cpp:45
#3  0x000055555b3917b6 in Transform2D::get_scale (this=this@entry=0x7fffffffd1f0) at core/math/transform_2d.cpp:117
#4  0x0000555558637830 in CanvasItemEditor::_draw_rulers (this=this@entry=0x555560eed650)
    at editor/plugins/canvas_item_editor_plugin.cpp:2784
#5  0x000055555865e6b6 in CanvasItemEditor::_draw_viewport (this=0x555560eed650)
    at editor/plugins/canvas_item_editor_plugin.cpp:3797
#6  0x0000555558682744 in call_with_variant_args_helper<CanvasItemEditor>(CanvasItemEditor*, void (CanvasItemEditor::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=<optimized out>, p_method=<optimized out>, 
    p_args=<optimized out>, r_error=...) at ./core/variant/binder_common.h:289
#7  0x000055555868276e in call_with_variant_args<CanvasItemEditor> (p_instance=<optimized out>, p_method=<optimized out>, 
    p_args=p_args@entry=0x0, p_argcount=p_argcount@entry=0, r_error=...) at ./core/variant/binder_common.h:393
#8  0x0000555558682815 in CallableCustomMethodPointer<CanvasItemEditor>::call (this=0x55556a458b10, p_arguments=0x0, 
    p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/object.h:987
#9  0x000055555b5c9b4c in Callable::callp (this=this@entry=0x555576a314d8, p_arguments=p_arguments@entry=0x0, 
    p_argcount=p_argcount@entry=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#10 0x000055555b92470f in Object::emit_signalp (this=this@entry=0x555560edf4f0, p_name=..., p_args=p_args@entry=0x0, 
    p_argcount=p_argcount@entry=0) at core/object/object.cpp:1046
#11 0x00005555592d9a9c in Object::emit_signal<>(StringName const&) (p_name=..., this=0x555560edf4f0)
    at ./core/variant/variant.h:236
#12 CanvasItem::_redraw_callback (this=0x555560edf4f0) at scene/main/canvas_item.cpp:136
#13 0x0000555557f3edc0 in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=<optimized out>, p_method=<optimized out>, p_args=<optimized out>, r_error=...)
    at ./core/variant/binder_common.h:289
#14 0x0000555557f3edea in call_with_variant_args<CanvasItem> (p_instance=<optimized out>, p_method=<optimized out>, 
    p_args=p_args@entry=0x0, p_argcount=p_argcount@entry=0, r_error=...) at ./core/variant/binder_common.h:393
#15 0x0000555557f3ee91 in CallableCustomMethodPointer<CanvasItem>::call (this=0x555570de2100, p_arguments=0x0, p_argcount=0, 
    r_return_value=..., r_call_error=...) at ./core/object/object.h:987
#16 0x000055555b5c9b4c in Callable::callp (this=this@entry=0x7ffff525a020, p_arguments=p_arguments@entry=0x0, 
    p_argcount=p_argcount@entry=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:50
#17 0x000055555b9164a3 in MessageQueue::_call_function (this=this@entry=0x55555ea3a350, p_callable=..., 
    p_args=p_args@entry=0x7ffff525a038, p_argcount=0, p_show_error=<optimized out>) at core/object/message_queue.cpp:229
#18 0x000055555b9167b0 in MessageQueue::flush (this=0x55555ea3a350) at core/object/message_queue.cpp:275
#19 0x00005555593a72bd in SceneTree::process (this=0x5555611a8fd0, p_time=0.0069444444444444449)
    at scene/main/scene_tree.cpp:461
#20 0x0000555556c8bbae in Main::iteration () at main/main.cpp:3169
#21 0x0000555556c1e574 in OS_LinuxBSD::run (this=0x7fffffffd850) at platform/linuxbsd/os_linuxbsd.cpp:889
#22 0x0000555556c1c51e in main (argc=<optimized out>, argv=0x7fffffffdd88) at platform/linuxbsd/godot_linuxbsd.cpp:73

gdb) info threads 
  Id   Target Id                                           Frame 
* 1    Thread 0x7ffff7c37000 (LWP 72519) "godot.linuxbsd." __sqrtf (x=0) at w_sqrtf_compat.c:30
  2    Thread 0x7ffff6e5d700 (LWP 72525) "godot.linuxbsd." futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x55555e948b78) at ../sysdeps/nptl/futex-internal.h:183
  3    Thread 0x7ffff665c700 (LWP 72526) "godot.linuxbsd." futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x55555e79c938) at ../sysdeps/nptl/futex-internal.h:183
  4    Thread 0x7ffff5e5b700 (LWP 72527) "godot.linuxbsd." futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x55555e79c938) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7fffe3db2700 (LWP 72529) "godot.l:disk$0"  futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x55555e78aae8) at ../sysdeps/nptl/futex-internal.h:183
  8    Thread 0x7fffe2d70700 (LWP 72531) "godot.linuxbsd." 0x00007ffff7d4cfcb in __GI___select (nfds=nfds@entry=4, 
    readfds=readfds@entry=0x7fffe2d6fd00, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, 
    timeout=timeout@entry=0x7fffe2d6fcf0) at ../sysdeps/unix/sysv/linux/select.c:41
  9    Thread 0x7fffdbfff700 (LWP 72532) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffdbffec90, rem=rem@entry=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  10   Thread 0x7fffdb7fe700 (LWP 72533) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffdb7fdd30, rem=rem@entry=0x0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  11   Thread 0x7fffdaa4a700 (LWP 72534) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffdaa49d30, rem=rem@entry=0x7fffdaa49d40)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  12   Thread 0x7fffda249700 (LWP 72535) "godot.linuxbsd." futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x555560d6be94) at ../sysdeps/nptl/futex-internal.h:183
  14   Thread 0x7fffd9247700 (LWP 72537) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffd9246c20, rem=rem@entry=0x7fffd9246c30)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  15   Thread 0x7fffd8a46700 (LWP 72538) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffd8a45d50, rem=rem@entry=0x7fffd8a45d60)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  16   Thread 0x7fffb2ffe700 (LWP 72539) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffb2ffdd80, rem=rem@entry=0x7fffb2ffdd90)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  17   Thread 0x7fffd9a48700 (LWP 72540) "godot.linuxbsd." 0x00007ffff7d1523f in __GI___clock_nanosleep (
    clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffd9a47d20, rem=rem@entry=0x7fffd9a47d30)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  18   Thread 0x7fffb27fd700 (LWP 72541) "godot.linuxbsd." futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x55556e5fb390) at ../sysdeps/nptl/futex-internal.h:183
  20   Thread 0x7fffe3571700 (LWP 72543) "WSI swapchain q" futex_abstimed_wait_cancelable (private=<optimized out>, 
    abstime=0x7fffe3570de0, clockid=<optimized out>, expected=0, futex_word=0x55555f5cc234)
    at ../sysdeps/nptl/futex-internal.h:320
  22   Thread 0x7fffb1ffc700 (LWP 72545) "godot.linuxbsd." futex_wait_cancelable (private=<optimized out>, expected=0, 
    futex_word=0x555562f67bd8) at ../sysdeps/nptl/futex-internal.h:183


^C
Thread 1 "godot.linuxbsd." received signal SIGINT, Interrupt.
Transform2D::scale_basis (this=this@entry=0x7fffffffd150, p_scale=...) at ./core/math/vector2.h:65
65			return coord[p_idx];
(gdb) n
CanvasItemEditor::_draw_rulers (this=this@entry=0x555560eed650) at

 editor/plugins/canvas_item_editor_plugin.cpp:2784

2784			while ((transform * ruler_transform).get_scale().x < 50 || (transform * ruler_transform).get_scale().y < 50) {
(gdb) 
```
</details>

**Comment by YuriSizov** [comment]
Identified as a regression from https://github.com/godotengine/godot/pull/74682.
