### ISSUE TITLE
build android aab error. is this  a bug?

### ISSUE THREAD

**Issue by setwind** [godotengine/godot#75967]
### Godot version

3.5.2 stable 

### System information

windows 7 64bit

### Issue description

export to aab (google play) ,it shows errors :

Building Android Project (gradle)
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException:java.io.IOException:
at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
at org.gradle.util.internal.DisconnectableinputStream$1.run(DisconnectableinputStream.java:127)
at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.io.IOException：
at java.base/java.io.FileInputStream.readBytes(Native Method).
at java.base/java.lo.FileInputStream.read(FileInputStream.java:273)
at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
at org.gradle.util.internal.DisconnectableInputStream$1.run(DisconnectableInputStream.java:98)
... 1 more
Task :preBuild UP-TO-DATE

Task :preReleaseBuild UP-TO-DATE
Task :assetPacks:installTime:generateAssetPackManifest UP-TO-DATE
Task :processReleaseAssetPackManifests UP-TO-DATE
Task :linkReleaseManifestForAssetPacks UP-TO-DATE
Task :assetPackReleasePreBundleTask UP-TO-DATE
Task :compileReleaseRenderscript NO-SOURCE
Task :generateReleaseResValues UP-TO-DATE
Task :generateReleaseResources UP-TO-DATE
......

### Steps to reproduce

JDK version :11
android sdk: 32
OS: win7 64bit

but ,after these errors ,it's exported successfully.
can generate a aab file.

all steps are correct.

### Minimal reproduction project

any empty project or any offical demo project

**Comment by Chaosus** [comment]
Closed in favour of https://github.com/godotengine/godot/issues/77716 (since it has more clear description and attached MRP).
