### ISSUE TITLE
GDScript vector.h error with yield

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#7796]
**Operating system or device - Godot version:**
Godot 2.x, probably 3.x too

**Issue description:**
_(Issue found in collaboration with user Zhelvad on discord)_
Doing something except `print` or a call to something of the base class after `yield` leads to a `vector.h` error:
```
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:132.
```

**Steps to reproduce:**
Run this script on some node:

```gdscript
extends Control # For the set call

signal test()

var wait_function_frames = 10
var wait_signal_frames = 20

func _ready():
	assert(wait_function_frames < wait_signal_frames)
	set_process(true)

func _process(delta):
	wait_function_frames -= 1
	if wait_function_frames == 0:
		do_stuff()
	
	wait_signal_frames -= 1
	if wait_signal_frames == 0:
		set_process(false)
		emit_signal("test") # Error reported here, but actually below (non-issue)

func do_stuff():
	yield(self, "test") # Throws error
	
	# Any of the following 4 lead to no thrown error if uncommented
	#print(4)
	#set("position", Vector2(1,1))
	#get("position")
	# return print(4)
	
	# All of the next 5 lines don't change the error reported (comment any of them if you want to)
	do_nothing()
	do_something()
	max(5,4)
	pass
	return 1

func do_nothing(): pass

func do_something(): set("position", Vector2(2,2))
```

**Link to minimal example project:**
Script above + a scene is easy to prepare on your own, but, still...
[zhelvad-yield.zip](https://github.com/godotengine/godot/files/771285/zhelvad-yield.zip)

**Comment by bojidar-bg** [comment]
Here is a gdb backtrace of the event:
```
(gdb) break core/vector.h:132
Breakpoint 1 at 0x414428: core/vector.h:132. (240 locations)
(gdb) run
#....
Thread 1 "godot22.dbg" hit Breakpoint 1, Vector<unsigned char>::operator[] (this=0x3a53948, p_index=96) at core/vector.h:132
132                             ERR_FAIL_COND_V(p_index<0 || p_index>=size(),aux);
(gdb) bt
#0  Vector<unsigned char>::operator[] (this=0x3a53948, p_index=96) at core/vector.h:132
#1  0x000000000045121e in GDFunction::call (this=0x3a577f0, p_instance=0x0, p_args=0x0, p_argcount=0, r_err=..., p_state=0x3a53938) at modules/gdscript/gd_function.cpp:174
#2  0x00000000004593d7 in GDFunctionState::_signal_callback (this=0x3a53890, p_args=0x39ad698, p_argcount=1, r_error=...) at modules/gdscript/gd_function.cpp:1400
#3  0x00000000004621f7 in MethodBindVarArg<GDFunctionState>::call (this=0x3940a50, p_object=0x3a53890, p_args=0x39ad698, p_arg_count=1, r_error=...) at core/method_bind.h:297
#4  0x000000000196b7d3 in Object::call (this=0x3a53890, p_method=..., p_args=0x39ad698, p_argcount=1, r_error=...) at core/object.cpp:978
#5  0x000000000196cdf8 in Object::emit_signal (this=0x3a558d0, p_name=..., p_args=0x0, p_argcount=0) at core/object.cpp:1281
#6  0x000000000196c830 in Object::_emit_signal (this=0x3a558d0, p_args=0x7fffffffc5b8, p_argcount=1, r_error=...) at core/object.cpp:1204
#7  0x000000000197c9e3 in MethodBindVarArg<Object>::call (this=0x2b401a0, p_object=0x3a558d0, p_args=0x7fffffffc5b8, p_arg_count=1, r_error=...) at core/method_bind.h:297
#8  0x000000000196b7d3 in Object::call (this=0x3a558d0, p_method=..., p_args=0x7fffffffc5b8, p_argcount=1, r_error=...) at core/object.cpp:978
#9  0x00000000019215e6 in Variant::call_ptr (this=0x7fffffffc7a0, p_method=..., p_args=0x7fffffffc5b8, p_argcount=1, r_ret=0x0, r_error=...) at core/variant_call.cpp:1007
#10 0x0000000000454546 in GDFunction::call (this=0x3a573b0, p_instance=0x39f5100, p_args=0x7fffffffd7f0, p_argcount=1, r_err=..., p_state=0x0) at modules/gdscript/gd_function.cpp:659
#11 0x000000000048d571 in GDInstance::call_multilevel (this=0x39f5100, p_method=..., p_args=0x7fffffffd7f0, p_argcount=1) at modules/gdscript/gd_script.cpp:1284
#12 0x0000000000fd8cc6 in Node::_notification (this=0x3a558d0, p_notification=17) at scene/main/node.cpp:56
#13 0x00000000004c362c in Node::_notificationv (this=0x3a558d0, p_notification=17, p_reversed=false) at ./scene/main/node.h:45
#14 0x00000000004c3c53 in CanvasItem::_notificationv (this=0x3a558d0, p_notification=17, p_reversed=false) at ./scene/2d/canvas_item.h:88
#15 0x00000000004c4271 in Control::_notificationv (this=0x3a558d0, p_notification=17, p_reversed=false) at ./scene/gui/control.h:49
#16 0x000000000196b952 in Object::notification (this=0x3a558d0, p_notification=17, p_reversed=false) at core/object.cpp:990
#17 0x0000000000fb7936 in SceneTree::_notify_group_pause (this=0x3a36cd0, p_group=..., p_notification=17) at scene/main/scene_main_loop.cpp:943
#18 0x0000000000fb5ced in SceneTree::idle (this=0x3a36cd0, p_time=0.0167750008) at scene/main/scene_main_loop.cpp:554
#19 0x000000000042f8e2 in Main::iteration () at main/main.cpp:1612
#20 0x0000000000412fc7 in OS_X11::run (this=0x7fffffffdf90) at platform/x11/os_x11.cpp:1934
#21 0x000000000040b630 in main (argc=1, argv=0x7fffffffe4f8) at platform/x11/godot_x11.cpp:41
```
The main culprit seems to be: [`gd_function.cpp:174`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_function.cpp#L174) and thus [`gd_function.cpp:890`](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_function.cpp#L890):

```c++
	if (p_state) {
		//use existing (supplied) state (yielded)
		stack=(Variant*)p_state->stack.ptr(); 
# 174:
		call_args=(Variant**)&p_state->stack[sizeof(Variant)*p_state->stack_size];
		line=p_state->line;
		ip=p_state->ip;
```
```c++
				gdfs->state.stack.resize(alloca_size);
				//copy variant stack
				for(int i=0;i<_stack_size;i++) {
					memnew_placement(&gdfs->state.stack[sizeof(Variant)*i],Variant(stack[i]));
				}
# 890:
				gdfs->state.stack_size=_stack_size;
				gdfs->state.self=self;
				gdfs->state.alloca_size=alloca_size;
				gdfs->state._class=_class;
```
