### ISSUE TITLE
Exported Android apk insta-crashing with APK expansion and PCK encryption

### ISSUE THREAD

**Issue by phil-hudson** [godotengine/godot#78105]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, Android Samsung A14, Android SDK API 33

### Issue description

When using custom build export templates with Android, PCK encryption and APK expansion, the Android App is insta-crashing with:

```
 FATAL EXCEPTION: main
Process: org.philhudson.test_and_enc, PID: 23907
 java.lang.RuntimeException: Unable to start activity ComponentInfo{org.philhudson.test_and_enc/com.godot.game.GodotApp}: java.lang.IllegalArgumentException: org.philhudson.test_and_enc: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4169)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.IllegalArgumentException: org.philhudson.test_and_enc: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
                                                                                                    	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
                                                                                                    	at android.app.PendingIntent.getActivity(PendingIntent.java:477)
                                                                                                    	at android.app.PendingIntent.getActivity(PendingIntent.java:441)
                                                                                                    	at org.godotengine.godot.Godot.onCreate(Godot.java:688)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
                                                                                                    	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
                                                                                                    	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8591)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8570)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
                                                                                                    	... 12 more
                                                                                                    
```

There have been suggestions to turn on Gradle build and add the following dependency, as per: 

https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a

and

https://github.com/godotengine/godot/issues/38758

adding: ` implementation "androidx.work:work-runtime-ktx:2.7.1"`

does not resolve the issue.

Also note that for the reproduction project, I am not using gradle build to show the most basic form of the issue.

Please let me know if you have additional comments or requests for additional reproduction steps.

### Steps to reproduce

1. Open up example project
2. Attempt to run on Android device or simulator with one click deploy or exported APK
3. Observe logs in adb, see app crash instantly on device

### Minimal reproduction project

Adding shared url as the project includes export templates which are big, total download size around 150mb which exceeds the 25mb limit here:

https://drive.google.com/file/d/10_ZnggmkBl39KIhkSyiEQaNiRrwN3Lkc/view?usp=sharing

**Comment by bruvzg** [comment]
Is it working with non encrypted PCK? The error seems to be from the Java part, which is not related to PCK encryption.

**Comment by phil-hudson** [comment]
> Is it working with non encrypted PCK? The error seems to be from the Java part, which is not related to PCK encryption.

Correct, this is related to the Java part, I only experienced it when using APK expansion and PCK encryption.

I generally think that there are other issues with PCK encryption however, this resolved the insta-crash mentioned above, but instead has a different error 'Download failed because the resources could not be found'. Which I believe is still related to PCK encryption, but this PR above only addresses the first stage of the crash.

We can see the new error string is: `case IDownloaderClient.STATE_FAILED_FETCHING_URL:` which I'd need to debug but I'd assume it relates to asset resolution/loading?

**Comment by bruvzg** [comment]
> Download failed because the resources could not be found'. Which I believe is still related to PCK encryption

No it's unlikely related, it might be related to OBB downloading. PCK encryption is handled by platform independent C++ code and only works with the local filesystem.

**Comment by phil-hudson** [comment]
> 

I think you're right, it does look related to OBB downloading.
