### ISSUE TITLE
Crash when click on instance icon while editing the instanced name

### ISSUE THREAD

**Issue by genete** [godotengine/godot#7820]
**Operating system or device - Godot version:**
MacOS 10.12.2 Godot 2.1.1 stable official

**Issue description:**
While editing the name of an instanced node click on the edit instance icon on the right. Crash
I expect that clicking outside the name field would sets the current text to the node name and after that send  the click to the button.

**Steps to reproduce:**
Edit the name of a instanced node and without pressing enter or clicking outside anywhere, click the instance edit button.
**Link to minimal example project:**
![sample_bug](https://cloud.githubusercontent.com/assets/346755/22999918/411d549c-f3de-11e6-8112-c7aa66bfde38.png)

**Comment by hpvb** [comment]
I can't reproduce this on Linux on master. Would you be able to try it with 3.0?

**Comment by volzhs** [comment]
I can't reproduce with 2.1.1, 2.1.2 or 3.0 on Ubuntu 16.04.1

**Comment by akien-mga** [comment]
I've managed to reproduce on 2.1.2-stable and the current 2.1/HEAD branch. It doesn't happen systematically, but I could reproduce it most of the time this way:
- Instance a scene
- Click name to edit
- Change its name by adding a space in the middle of the name (do not validate with Return or a click)
- Click the "instance" icon

Sometimes it will work fine, sometimes it will crash.

Stacktrace from 2.1/HEAD:
```
(gdb) bt
#0  0x00007ffff559d130 in __dynamic_cast () from /lib64/libstdc++.so.6
#1  0x0000000000889f7f in Object::cast_to<TreeItem> (this=0x88c2a50) at core/object.h:502
#2  0x0000000000c7c533 in SceneTreeEditor::_cell_button_pressed (this=0x4f39cc0, p_item=0x88c2a50, p_column=0, p_id=0) at tools/editor/scene_tree_editor.cpp:160
#3  0x000000000088b72a in MethodBind3<Object*, int, int>::call (this=0x4f54090, p_object=0x4f39cc0, p_args=0x7fffffffb4b0, p_arg_count=3, r_error=...) at core/method_bind.inc:1913
#4  0x00000000017294ff in Object::call (this=0x4f39cc0, p_method=..., p_args=0x7fffffffb4b0, p_argcount=3, r_error=...) at core/object.cpp:896
#5  0x000000000172b24a in Object::emit_signal (this=0x4f3a270, p_name=..., p_args=0x7fffffffb4b0, p_argcount=3) at core/object.cpp:1218
#6  0x000000000172b7bf in Object::emit_signal (this=0x4f3a270, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1262
#7  0x0000000000e536ca in Tree::_input_event (this=0x4f3a270, p_event=...) at scene/gui/tree.cpp:2354
#8  0x0000000000878b7e in MethodBind1<InputEvent>::call (this=0x34d7690, p_object=0x4f3a270, p_args=0x7fffffffc080, p_arg_count=1, r_error=...) at core/method_bind.inc:653
#9  0x0000000001728881 in Object::call_multilevel (this=0x4f3a270, p_method=..., p_args=0x7fffffffc080, p_argcount=1) at core/object.cpp:622
#10 0x00000000017290df in Object::call_multilevel (this=0x4f3a270, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:830
#11 0x0000000000dd49fa in Viewport::_gui_call_input (this=0x3753bc0, p_control=0x4f3a270, p_input=...) at scene/main/viewport.cpp:1626
#12 0x0000000000dd5ecc in Viewport::_gui_input_event (this=0x3753bc0, p_event=...) at scene/main/viewport.cpp:1928
#13 0x0000000000dd8477 in Viewport::input (this=0x3753bc0, p_event=...) at scene/main/viewport.cpp:2455
#14 0x0000000000dd3d33 in Viewport::_vp_input (this=0x3753bc0, p_ev=...) at scene/main/viewport.cpp:1469
#15 0x000000000081392e in MethodBind1<InputEvent const&>::call (this=0x3447a50, p_object=0x3753bc0, p_args=0x7fffffffcc70, p_arg_count=1, r_error=...) at core/method_bind.inc:653
#16 0x00000000017294ff in Object::call (this=0x3753bc0, p_method=..., p_args=0x7fffffffcc70, p_argcount=1, r_error=...) at core/object.cpp:896
#17 0x0000000001729036 in Object::call (this=0x3753bc0, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:770
#18 0x0000000000db8b8c in SceneTree::call_group (this=0x3758400, p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at scene/main/scene_main_loop.cpp:215
#19 0x0000000000db97c5 in SceneTree::input_event (this=0x3758400, p_event=...) at scene/main/scene_main_loop.cpp:431
#20 0x000000000041958b in InputDefault::parse_input_event (this=0x32dcb10, p_event=...) at main/input_default.cpp:345
#21 0x0000000000410901 in OS_X11::process_xevents (this=0x7fffffffd590) at platform/x11/os_x11.cpp:1375
#22 0x0000000000412ad7 in OS_X11::run (this=0x7fffffffd590) at platform/x11/os_x11.cpp:1930
#23 0x000000000040b020 in main (argc=2, argv=0x7fffffffdae8) at platform/x11/godot_x11.cpp:41
```

**Comment by akien-mga** [comment]
I could also reproduce on master/HEAD (running on Mageia 6 x86_64):
```
(gdb) bt
#0  0x00007ffff559d130 in __dynamic_cast () from /lib64/libstdc++.so.6
#1  0x00000000005fe14f in Object::cast_to<TreeItem> (this=0x2983ff0) at core/object.h:526
#2  0x0000000000bd0297 in SceneTreeEditor::_cell_button_pressed (this=0x484e800, p_item=0x2983ff0, p_column=0, p_id=0) at tools/editor/scene_tree_editor.cpp:160
#3  0x0000000000611196 in MethodBind3<Object*, int, int>::call (this=0x4864c10, p_object=0x484e800, p_args=0x7fffffffb390, p_arg_count=3, r_error=...) at core/method_bind.inc:1973
#4  0x0000000001564482 in Object::call (this=0x484e800, p_method=..., p_args=0x7fffffffb390, p_argcount=3, r_error=...) at core/object.cpp:981
#5  0x0000000001565ac0 in Object::emit_signal (this=0x484ee00, p_name=..., p_args=0x7fffffffb390, p_argcount=3) at core/object.cpp:1284
#6  0x0000000001566035 in Object::emit_signal (this=0x484ee00, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1328
#7  0x0000000000d9b40e in Tree::_gui_input (this=0x484ee00, p_event=...) at scene/gui/tree.cpp:2393
#8  0x00000000008e2cac in MethodBind1<InputEvent>::call (this=0x3045a30, p_object=0x484ee00, p_args=0x7fffffffc060, p_arg_count=1, r_error=...) at core/method_bind.inc:673
#9  0x0000000001563804 in Object::call_multilevel (this=0x484ee00, p_method=..., p_args=0x7fffffffc060, p_argcount=1) at core/object.cpp:707
#10 0x0000000001564063 in Object::call_multilevel (this=0x484ee00, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:915
#11 0x0000000000d10f30 in Viewport::_gui_call_input (this=0x32a2c10, p_control=0x484ee00, p_input=...) at scene/main/viewport.cpp:1673
#12 0x0000000000d124a2 in Viewport::_gui_input_event (this=0x32a2c10, p_event=...) at scene/main/viewport.cpp:2032
#13 0x0000000000d14a63 in Viewport::input (this=0x32a2c10, p_event=...) at scene/main/viewport.cpp:2581
#14 0x0000000000d102f0 in Viewport::_vp_input (this=0x32a2c10, p_ev=...) at scene/main/viewport.cpp:1514
#15 0x000000000060dbce in MethodBind1<InputEvent const&>::call (this=0x2fcc390, p_object=0x32a2c10, p_args=0x7fffffffcca0, p_arg_count=1, r_error=...) at core/method_bind.inc:673
#16 0x0000000001564482 in Object::call (this=0x32a2c10, p_method=..., p_args=0x7fffffffcca0, p_argcount=1, r_error=...) at core/object.cpp:981
#17 0x0000000001563fba in Object::call (this=0x32a2c10, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:855
#18 0x0000000000ce9a5c in SceneTree::call_group_flags (this=0x32da640, p_call_flags=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., p_arg5=...)
    at scene/main/scene_main_loop.cpp:249
#19 0x0000000000cea7c5 in SceneTree::input_event (this=0x32da640, p_event=...) at scene/main/scene_main_loop.cpp:483
#20 0x00000000004168c2 in InputDefault::parse_input_event (this=0x2e82a10, p_event=...) at main/input_default.cpp:395
#21 0x000000000040dcfd in OS_X11::process_xevents (this=0x7fffffffd5f0) at platform/x11/os_x11.cpp:1401
#22 0x000000000040ff37 in OS_X11::run (this=0x7fffffffd5f0) at platform/x11/os_x11.cpp:1958
#23 0x0000000000408411 in main (argc=2, argv=0x7fffffffdaf8) at platform/x11/godot_x11.cpp:41
```

**Comment by hpvb** [comment]
Ah, I never tried actually editing the name before clicking outside of it. That makes sense, I also think I know what's causing the crash then. I'll investigate further.
