### ISSUE TITLE
"Open and close editor (Vulkan)" in GHA "Linux / Editor with doubles and GCC sanitizers" is unstable

### ISSUE THREAD

**Issue by heppocogne** [godotengine/godot#78927]
### Godot version

4.x (latest branch)

### System information

Windows 11, NVIDIA GeForce GTX 1650

### Issue description

When I update my fork repository, "Open and close editor (Vulkan)" in GHA "Linux / Editor with doubles and GCC sanitizers" randomly fails because of `runtime error: division by zero`.

Additionary, when I push some branches to my fork repository, the GHA also randomly fails even if I only changed a commit message (no code changes). And retried after the failure, it passed.

<details>
<summary>Error log</summary>

```console
xvfb-run ./bin/godot.linuxbsd.editor.dev.double.x86_64.san --audio-driver Dummy --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
  misc/scripts/check_ci_log.py sanitizers_log.txt
  shell: /usr/bin/bash -e {0}
  env:
    GODOT_BASE_BRANCH: master
    SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:3).11.[4](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:4)/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib
Godot Engine v4.1.rc.custom_build.46424488e - https://godotengine.org
/lib/x86_64-linux-gnu/libxkbcommon.so.0: undefined symbol: xkb_utf32_to_keysym
/lib/x86_64-linux-gnu/libxkbcommon.so.0: undefined symbol: xkb_keymap_key_get_mods_for_level
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	terminator_CreateInstance: Failed to CreateInstance in ICD 4.  Skipping ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 10837061[5](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:5)017984
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:2[6](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:6)4)
Vulkan API 1.3.246 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.[7](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:7), 256 bits)
servers/rendering/rendering_device.cpp:659:40: runtime error: load of value 4294967295, which is not a valid value for type 'SpvBuiltIn_'
drivers/unix/file_access_unix.cpp:271:2: runtime error: null pointer passed as argument 1, which is declared to never be null
thirdparty/spirv-reflect/spirv_reflect.c:30[8](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:8)8:5: runtime error: null pointer passed as argument 2, which is declared to never be null
 
core/math/vector3.h:3[9](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:9)5:4: runtime error: division by zero
core/math/vector3.h:396:4: runtime error: division by zero
core/math/vector3.h:397:4: runtime error: division by zero
servers/rendering_server.cpp:406:21: runtime error: nan is outside the range of representable values of type 'short int'
servers/rendering_server.cpp:407:21: runtime error: nan is outside the range of representable values of type 'short int'
servers/rendering_server.cpp:426:22: runtime error: nan is outside the range of representable values of type 'short int'
servers/rendering_server.cpp:427:22: runtime error: 32768.5 is outside the range of representable values of type 'short int'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 13 out of bounds for type 'TableRecord [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 13 out of bounds for type 'TableRecord [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 2 out of bounds for type 'Index [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 2 out of bounds for type 'Index [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:767:29: runtime error: index 9 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:767:29: runtime error: index 9 out of bounds for type 'OffsetTo [1]'
thirdparty/icu4c/common/rbbi.cpp:874:32: runtime error: index 11 out of bounds for type 'unsigned char [1]'
thirdparty/thorvg/src/lib/sw_engine/tvgSwFill.cpp:72:27: runtime error: division by zero
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'MarkRecord [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'MarkRecord [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:468:28: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:468:28: runtime error: index 2 out of bounds for type 'IntType [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'EntryExitRecord [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'EntryExitRecord [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/OT/Layout/GSUB/LigatureSet.hh:126:45: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/OT/Layout/GSUB/LigatureSet.hh:126:45: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
servers/rendering_server.cpp:442:22: runtime error: 32768.5 is outside the range of representable values of type 'short int'
servers/rendering_server.cpp:441:22: runtime error: 33798 is outside the range of representable values of type 'short int'
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (./modules/gltf/register_types.cpp:73)
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 3 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 3 out of bounds for type 'Record [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/OT/Layout/GPOS/../../../hb-ot-layout-gsubgpos.hh:4086:60: runtime error: index 1 out of bounds for type 'hb_applicable_t [1]'
thirdparty/harfbuzz/src/OT/Layout/GPOS/../../../hb-ot-layout-gsubgpos.hh:4086:21: runtime error: index 1 out of bounds for type 'hb_applicable_t [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 6 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 6 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/OT/Layout/GPOS/../../../hb-ot-layout-gsubgpos.hh:4086:60: runtime error: index 1 out of bounds for type 'hb_applicable_t [1]'
thirdparty/harfbuzz/src/OT/Layout/GPOS/../../../hb-ot-layout-gsubgpos.hh:4086:21: runtime error: index 1 out of bounds for type 'hb_applicable_t [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 20 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 20 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:731:11: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
editor/plugins/node_3d_editor_plugin.cpp:547:[10](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:10)5: runtime error: division by zero
editor/plugins/node_3d_editor_plugin.cpp:548:105: runtime error: division by zero
servers/rendering/renderer_geometry_instance.cpp:78:53: runtime error: division by zero
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: ../src/vulkan/runtime/vk_nir.c:56
	SPIR-V offset 21360: SPIR-V WARNING:
    Decoration not allowed on struct members: SpvDecorationInvariant
    21360 bytes into the SPIR-V binary
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 108714212246528
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: ../src/vulkan/runtime/vk_nir.c:56
	SPIR-V offset 21608: SPIR-V WARNING:
    Decoration not allowed on struct members: SpvDecorationInvariant
    21608 bytes into the SPIR-V binary
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 108714212246528
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: ../src/vulkan/runtime/vk_nir.c:56
	SPIR-V offset 20800: SPIR-V WARNING:
    Decoration not allowed on struct members: SpvDecorationInvariant
    20800 bytes into the SPIR-V binary
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 108714212246528
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
thirdparty/harfbuzz/src/hb-open-type.hh:632:18: runtime error: index 2 out of bounds for type 'OffsetTo [1]'
=================================================================
==12274==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x6040003b5710 in thread T0
    #0 0x7f3a4882440f in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x560ac44fbba2 in Memory::free_static(void*, bool) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4be39ba2)
    #2 0x560aa9404f84 in DefaultAllocator::free(void*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x30d42f84)
    #3 0x560aab1b1665 in void memdelete_allocator<List<StringName, DefaultAllocator>::Element, DefaultAllocator>(List<StringName, DefaultAllocator>::Element*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x32aef665)
    #4 0x560aab18061e in List<StringName, DefaultAllocator>::_Data::erase(List<StringName, DefaultAllocator>::Element const*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x32abe61e)
    #5 0x560aab0f9ba8 in List<StringName, DefaultAllocator>::erase(List<StringName, DefaultAllocator>::Element const*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x32a37ba8)
    #6 0x560aab012ae8 in List<StringName, DefaultAllocator>::clear() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x32950ae8)
    #7 0x560aaaf79841 in List<StringName, DefaultAllocator>::~List() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x328b7841)
    #8 0x560ac5d68758 in ClassDB::ClassInfo::~ClassInfo() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d6a6758)
    #9 0x560ac5df02d2 in KeyValue<StringName, ClassDB::ClassInfo>::~KeyValue() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d72e2d2)
    #10 0x560ac5df0404 in HashMapElement<StringName, ClassDB::ClassInfo>::~HashMapElement() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d72e404)
    #[11](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:11) 0x560ac5e3d825 in void memdelete<HashMapElement<StringName, ClassDB::ClassInfo> >(HashMapElement<StringName, ClassDB::ClassInfo>*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d77b825)
    #[12](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:12) 0x560ac5dff785 in DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> >::delete_allocation(HashMapElement<StringName, ClassDB::ClassInfo>*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d73d785)
    #[13](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:13) 0x560ac5dad87d in HashMap<StringName, ClassDB::ClassInfo, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> > >::clear() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d6eb87d)
    #[14](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:14) 0x560ac5c93994 in ClassDB::cleanup() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4d5d1994)
    #[15](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:15) 0x560ac41dcf6a in unregister_core_types() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x4bb1af6a)
    #[16](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:17) 0x560aa96e8fb4 in Main::cleanup(bool) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x31026fb4)
    #[17](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:18) 0x560aa9402269 in main (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x30d40269)
    #[18](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:19) 0x7f3a47a64082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    #[19](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:20) 0x560aa9401c2d in _start (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x30d3fc2d)

0x6040003b5710 is located 0 bytes inside of 48-byte region [0x6040003b5710,0x6040003b5740)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.rc.custom_build (46424488edc341b65467ee7fd3ac423e4d49ad34)
Dumping the backtrace. 
[1] ./bin/godot.linuxbsd.editor.dev.double.x86_64.san(+0x30d409c4) [0x560aa94029c4] (??:?)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f3a47a83090] (??:0)
[3] /lib/x86_64-linux-gnu/libasan.so.5(+0x11b913) [0x7f3a48832913] (??:0)
[4] /lib/x86_64-linux-gnu/libasan.so.5(+0x2f03a) [0x7f3a4874603a] (??:0)
[5] /lib/x86_64-linux-gnu/libasan.so.5(+0x2ff34) [0x7f3a48746f34] (??:0)
[6] /lib/x86_64-linux-gnu/libasan.so.5(+0x11774e) [0x7f3a4882e74e] (??:0)
[7] /lib/x86_64-linux-gnu/libasan.so.5(+0x115935) [0x7f3a4882c935] (??:0)
[8] /lib/x86_64-linux-gnu/libasan.so.5(__interceptor_free+0xa9) [0x7f3a488243d9] (??:0)
[9] Memory::free_static(void*, bool) (??:?)
[10] DefaultAllocator::free(void*) (??:?)
[11] void memdelete_allocator<List<StringName, DefaultAllocator>::Element, DefaultAllocator>(List<StringName, DefaultAllocator>::Element*) (??:?)
[12] List<StringName, DefaultAllocator>::_Data::erase(List<StringName, DefaultAllocator>::Element const*) (??:?)
[13] List<StringName, DefaultAllocator>::erase(List<StringName, DefaultAllocator>::Element const*) (??:?)
[14] List<StringName, DefaultAllocator>::clear() (??:?)
[15] List<StringName, DefaultAllocator>::~List() (??:?)
[16] ClassDB::ClassInfo::~ClassInfo() (??:?)
[17] KeyValue<StringName, ClassDB::ClassInfo>::~KeyValue() (??:?)
[18] HashMapElement<StringName, ClassDB::ClassInfo>::~HashMapElement() (??:?)
[19] void memdelete<HashMapElement<StringName, ClassDB::ClassInfo> >(HashMapElement<StringName, ClassDB::ClassInfo>*) (??:?)
[[20](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:21)] DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> >::delete_allocation(HashMapElement<StringName, ClassDB::ClassInfo>*) (??:?)
[[21](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:22)] HashMap<StringName, ClassDB::ClassInfo, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ClassDB::ClassInfo> > >::clear() (??:?)
[[22](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:23)] ClassDB::cleanup() (??:?)
[[23](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:24)] unregister_core_types() (??:?)
[[24](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:25)] Main::cleanup(bool) (??:?)
[[25](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:26)] ./bin/godot.linuxbsd.editor.dev.double.x86_64.san(main+0x581) [0x560aa9402[26](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:27)a] (??:?)
[26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f3a47a64083] (??:0)
[[27](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:28)] ./bin/godot.linuxbsd.editor.dev.double.x86_64.san(_start+0x2e) [0x560aa9[40](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:41)1c2e] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
FATAL ERROR: An incorrectly used memory was found.
Error: Process completed with exit code [51](https://github.com/heppocogne/godot/actions/runs/5427874342/jobs/9871554641#step:15:52).
```

</details>

### Steps to reproduce

Fork the master branch of godotengine/godot and run GHA.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/78749
