### ISSUE TITLE
Tooltip crashes the game

### ISSUE THREAD

**Issue by VirmaY-chr** [godotengine/godot#79116]
### Godot version

v4.0.2.stable.mono.official [7a0977ce2]

### System information

Windows 10

### Issue description

Instead of showing the tooltip, the game crashes. This happens if the tree contains AudioStreamPlayer2D. In other case, the tooltip shows properly.

### Steps to reproduce

1. Set the tooltip for any of controls.
2. Hover the cursor over the control with tooltip, the preview/build crashes.

In project, tooltip is set in "/root/editor/editorui/toppanel/close" button.

### Minimal reproduction project

[gd-sai-tooltip-issue.zip](https://github.com/godotengine/godot/files/11970170/gd-sai-tooltip-issue.zip)

**Comment by akien-mga** [comment]
This sounds like an issue fixed a few months ago but I can't find it right away. Could you test 4.0.3.stable and 4.1.stable?

Note that I tried 4.1.stable myself but it seems to crash when playing with this error, which is probably unrelated to this issue:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at Godot.DisposablesTracker.UnregisterGodotObject(GodotObject godotObject, WeakReference`1 weakReferenceToSelf) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DisposablesTracker.cs:line 85
   at Godot.GodotObject.Dispose(Boolean disposing) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 128
   at Godot.GodotObject.Finalize() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 80
```
(CC @godotengine/dotnet)

**Comment by VirmaY-chr** [comment]
> This sounds like an issue fixed a few months ago but I can't find it right away. Could you test 4.0.3.stable and 4.1.stable?


I came to my senses very late at the time of writing this issue, I didn't recieve any update notifications and yea, tooltips and AudioStreamPlayer 2d works fine in 4.1.stable, thx!
