### ISSUE TITLE
`Godot.DisposablesTracker.UnregisterGodotObject` when running .NET project ported from 4.0.x in 4.1

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#79148]
### Godot version

4.1.stable.mono

### System information

Godot v4.1.stable.mono - Mageia 9 - Vulkan (Forward+) - dedicated AMD Radeon RX Vega M GL Graphics (RADV VEGAM) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

While testing the (complex) MRP from #79116 I got this crash on Linux:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at Godot.DisposablesTracker.UnregisterGodotObject(GodotObject godotObject, WeakReference`1 weakReferenceToSelf) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DisposablesTracker.cs:line 85
   at Godot.GodotObject.Dispose(Boolean disposing) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 128
   at Godot.GodotObject.Finalize() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 80
```

[gd-sai-tooltip-issue.zip](https://github.com/godotengine/godot/files/11970170/gd-sai-tooltip-issue.zip)

I tried deleting the `.godot` folder to ensure it's not reusing old assemblies, but it still crashes.

### Steps to reproduce

- Open linked project in Godot 4.1.stable.mono
- Build
- Run (on Linux?) and it crashes after a couple seconds

### Minimal reproduction project

[gd-sai-tooltip-issue.zip](https://github.com/godotengine/godot/files/11970170/gd-sai-tooltip-issue.zip)

**Comment by akien-mga** [comment]
There are lots of errors prior to the crash which originate in one of this project's scripts:
```
E 0:00:00:0738   TrailLine2D.cs:33 @ void TrailLine2D._Process(Double ): System.NullReferenceException: Object reference not set to an instance of an object.
  <C# Error>     System.NullReferenceException
  <C# Source>    TrailLine2D.cs:33 @ void TrailLine2D._Process(Double )
  <Call Stack>   TrailLine2D.cs:33 @ void TrailLine2D._Process(Double )
                 Node.cs:2087 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CanvasItem.cs:1374 @ Boolean Godot.CanvasItem.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Node2D.cs:516 @ Boolean Godot.Node2D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Line2D.cs:555 @ Boolean Godot.Line2D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 TrailLine2D_ScriptMethods.generated.cs:31 @ Boolean TrailLine2D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )
```

**Comment by RedworkDE** [comment]
That project is weird, I don't get any errors (I don't think it works as it is supposed to as I don't get any tooltips and the menus don't work). But instead if I resize the window it crashes in the graphics driver and the crash handler fails to trigger.
