### ISSUE TITLE
As of 4.1, Adding an EditorSpinSlider to the scene crashes.

### ISSUE THREAD

**Issue by NateAustin** [godotengine/godot#79171]
### Godot version

4.1

### System information

Win10, .Net 6

### Issue description

Adding an EditorSpinSlider to the scene crashes. This seems to be new in 4.1. Tested in C#.

    using Godot;
    public partial class Control : Godot.Control
    {
        public override void _Ready()
        {
            AddChild(new SpinBox());	//works
            AddChild(new EditorSpinSlider());	//crashes
        }
    }

gives this error:

> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr, IntPtr, Void**, Void*)
>    at Godot.NativeCalls.godot_icall_3_673(IntPtr, IntPtr, IntPtr, Godot.NativeInterop.godot_bool, Int32)
>    at Godot.Node.AddChild(Godot.Node, Boolean, InternalMode)
>    at Control._Ready()
>    at Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
>    at Godot.CanvasItem.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
>    at Godot.Control.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
>    at Control.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
>    at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error*, G
> odot.NativeInterop.godot_variant*)

(If the editor controls are not intended to work in non-editor projects I can understand that, but this worked in 4.0.3 and it would be nice if I could use it.)

### Steps to reproduce

1. Create an EditorSpinSlider
2. Add it to the scene via AddChild()

(tested with C# only)

### Minimal reproduction project

[EditorSpinSlider.zip](https://github.com/godotengine/godot/files/11984693/EditorSpinSlider.zip)

**Comment by RedworkDE** [comment]
The crash is C# exclusive, the gdscript version: `add_child(EditorSpinSlider.new())` gives the error `Parser Error: Native class "EditorSpinSlider" cannot be constructed as it is abstract`

**Comment by YuriSizov** [comment]
> gives the error `Parser Error: Native class "EditorSpinSlider" cannot be constructed as it is abstract`

Which is also wrong, see https://github.com/godotengine/godot/issues/73525.

**Comment by RedworkDE** [comment]
What's happening here is that whatever is blocking the creating in GDScript doesn't apply to C# and the `EditorSpinSlider` instance is created successfully, but when it is added `EditorSpinSlider`  tries to access the `EditorSettings` singleton, which doesn't exist as it is not in the editor and crashes: https://github.com/godotengine/godot/blob/c3b0a92c3cd9a219c1b1776b48c147f1d0602f07/editor/gui/editor_spin_slider.cpp#L444
