### ISSUE TITLE
Importing .blend causes endless dialog loop and locks entire system

### ISSUE THREAD

**Issue by RenaKunisaki** [godotengine/godot#80530]
### Godot version

v4.1.stable.arch_linux

### System information

Artix Linux AMD64, Blender 3.6.0

### Issue description

Trying to import .blend files causes all manner of weird problems:

1. It imports as just one plane instead of the actual contents of the file
2. At one point, that plane appeared in a different scene entirely
3. I tried saving another copy of the .blend file, which Godot automatically imports, but...
4. ...the import fails, saying the file is corrupt, and then it tries again, and again, and again.

The result is it gets into a loop of opening the import progress dialog, deciding the file is corrupt, closing the dialog, and immediately opening it again. This actually made my entire desktop unusable because Godot was stealing focus several times per second and wouldn't respond to attempts to close it. I could only recover by switching to another VT and killing it there.

I can't open the project to remove extraneous files, since opening it immediately causes the same dialog loop. I've zipped the project files with unrelated ones omitted.

The relevant .blend file that fails to import is `maps/pyramid/pyramid.blend`. The one that I added that causes the dialog loop is `maps/pyramid/pyramid2.blend`. I also left `maps/fox` because that was the map that started doing strange things, like showing the plane that imports from pyramid.blend, and at one point saying its .tscn file was corrupt.

### Steps to reproduce

1. Open the project
2. If it doesn't break immediately, try to import pyramid.blend
3. The import shows just one plane, but opening it in Blender should reveal a much more complex structure

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12325937/project.zip)

**Comment by lflo5727** [comment]
Will jump in adding that I am seeing the exact same behavior trying to import blend files on Arch with Godot 4.1

**Comment by ttencate** [comment]
Me too, also on Arch. I removed the `.godot` directory for unrelated reasons, then opened the project in the editor, and it just loops indefinitely trying to import each `.blend` file in turn. The import fails, probably due to #80540, but there is no reason it should be retried over and over again.

**Comment by bytting** [comment]
Similar problem here on Archlinux. As soon as I start Godot it gets stuck in a loop going back and forth between the main window and the open dialog. This happens with both 4.1.1 and 4.1.2 RC

It does not happen with 3.5.2

**Comment by Calinou** [comment]
This is an issue with the Blender Arch Linux package. Please use the download from [blender.org](https://blender.org) until it's fixed.

**Comment by bytting** [comment]
There is definitely multiple issues here. The forever loop on the dialog doesn't seem to have anything to do with Blender

**Comment by curVV** [comment]
Getting this with both Blender 3.6.1 and 3.6.7. Testing with simple cube Godot 4.2.1 goes into a loop with errors "Error importing 'res://something.blend'".

**Comment by copygirl** [comment]
Unsure if this is exactly the same issue, but I've switched to a new PC and installed Arch Linux from scratch (as you do) and I'm getting the following error. I do want to note that this didn't appear to be a problem in my previous (also Arch) install.
```
  modules/gltf/gltf_document.cpp:7673 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://terrain.blend'.
```
Godot: v4.2.2.stable.mono.official [15073afe3]
Blender: 4.2.0

@Calinou Your comment left me just as confused and frustrated. What's the source of this claim? Is this issue tracked anywhere on Arch's end?

According to the [package details](https://gitlab.archlinux.org/archlinux/packaging/packages/blender) there's a patch enabling glTF compression, which actually allows Blender to open certain files it couldn't before. From what I understand looking at the [related issue](https://gitlab.archlinux.org/archlinux/packaging/packages/blender/-/issues/21), anyway. This is a recent issue but the patch is 2 years old. I'm not sure this is also used when exporting, but if so, this would lead me to believe the issue is with Godot not being able to open compressed glTF files. I could have a look to see if this is the case.

But if I'm wrong, regardless, I would like to know what the issue is, other than "it just doesn't work with X".

**Comment by akien-mga** [comment]
Yes, Godot doesn't support Draco mesh compression.

If there's a way to explicitly turn it off when exporting from Blender, we should do that.

**Comment by copygirl** [comment]
According to [Blender's API](https://docs.blender.org/api/current/bpy.ops.export_scene.html#bpy.ops.export_scene.gltf) for `export_scene`, the option to enable compression (`export_draco_mesh_compression_enable`) should be off by default. I wish there was an easy way to check the .gltf file Godot asks Blender to make to inspect it. That is, assuming I'm even on the right track.

**Comment by copygirl** [comment]
Okay following the error backwards and trying to understand what's going on:
```
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7673)
```
Is the error displayed in the terminal. Looking at [`append_from_file`](https://github.com/godotengine/godot/blob/03afb92efa18874da19f7fc185a32c005d20aa1d/modules/gltf/gltf_document.cpp#L7418-L7419) this likely because the file simply doesn't exist.
```
	Ref<FileAccess> file = FileAccess::open(p_path, FileAccess::READ, &err);
	ERR_FAIL_COND_V(err != OK, ERR_FILE_CANT_OPEN);
```
I can see this being called [here](https://github.com/godotengine/godot/blob/03afb92efa18874da19f7fc185a32c005d20aa1d/modules/gltf/editor/editor_scene_importer_blend.cpp#L303), which leads me to believe that Blender was started a [couple lines above](https://github.com/godotengine/godot/blob/03afb92efa18874da19f7fc185a32c005d20aa1d/modules/gltf/editor/editor_scene_importer_blend.cpp#L279), which causes [this python script](https://github.com/godotengine/godot/blob/03afb92efa18874da19f7fc185a32c005d20aa1d/modules/gltf/editor/editor_import_blend_runner.cpp#L85-L92) to run in Blender, but didn't produce a .gltf file. So the question remains: Why? Is there an error silently getting ignored?

**Comment by copygirl** [comment]
Notably, when I set the Blender RPC port to 0, I get the looping import dialog behavior described in the first post.

**Comment by copygirl** [comment]
The other potential line of attack could be checking if it has something to do with the version Python used. Unsure about official releases, but I believe Arch will build Blender with and use the system provided version of Python which for me is `3.12.4`.

**Comment by akien-mga** [comment]
You can use a debugger or add some `print_line` in the Godot code to check what command is passed to Blender, and then try to run it manually yourself from the command line, to see what happens.

**Comment by Calinou** [comment]
> You can use a debugger or add some `print_line` in the Godot code to check what command is passed to Blender, and then try to run it manually yourself from the command line, to see what happens.

Doesn't `--verbose` print it already? We should make it do that if it's not done already.

**Comment by copygirl** [comment]
Running Godot itself with that flag? Here's my output:
```
[...]

CORE API HASH: 622119089
EDITOR API HASH: 497707466
EditorSettings: Load OK!
Found .NET Sdk version '8.0.107': /usr/share/dotnet/sdk/8.0.107
Loaded system CA certificates
EditorSettings: Save OK!
Socket error: 111
Connection to remote host failed!

[Above two lines repeat about 100 times ...]

Blender 4.2.0 (hash a51f293548ad built 2024-08-03 07:45:49)
Socket error: 111
Connection to remote host failed!

[Again, above two lines repeat about 100 times ...]

Read blend: "/home/copygirl/Projects/godot/SlimeDream/terrain_source.blend"
127.0.0.1 - - [08/Aug/2024 19:00:27] "POST / HTTP/1.1" 200 -
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7673)
ERROR: Error importing 'res://terrain_source.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2061)
Read blend: "/home/copygirl/Projects/godot/SlimeDream/terrain_source.blend"
127.0.0.1 - - [08/Aug/2024 19:00:27] "POST / HTTP/1.1" 200 -
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7673)
ERROR: Error importing 'res://terrain_source.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2061)
Read blend: "/home/copygirl/Projects/godot/SlimeDream/terrain_source.blend"
127.0.0.1 - - [08/Aug/2024 19:00:27] "POST / HTTP/1.1" 200 -
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7673)
ERROR: Error importing 'res://terrain_source.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2061)
```

Now if I once again set the RPC port to 0, I get a little more:

```
Blender 4.2.0 (hash a51f293548ad built 2024-08-03 07:45:49)
Read blend: "/home/copygirl/Projects/godot/SlimeDream/terrain_source.blend"
Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/share/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties:: keyword "export_colors" unrecognized

Blender quit
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7673)
ERROR: Error importing 'res://terrain_source.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2061)

[This repeats until I forcibly close the program ...]
```

**Comment by copygirl** [comment]
`export_colors`, set [here](https://github.com/godotengine/godot/blob/03afb92efa18874da19f7fc185a32c005d20aa1d/modules/gltf/editor/editor_scene_importer_blend.cpp#L196-L200), does not exist as a parameter to `export_scene.gltf`. However, this if branch is not supposed to be run, as the Blender version is 4.2 or above:
```cpp
if (blender_major_version > 4 || (blender_major_version == 4 && blender_minor_version >= 2)) {
	if (p_options.has(SNAME("blender/meshes/colors")) && p_options[SNAME("blender/meshes/colors")]) {
		parameters_map["export_vertex_color"] = "MATERIAL";
	} else {
		parameters_map["export_vertex_color"] = "NONE";
	}
} else {
	if (p_options.has(SNAME("blender/meshes/colors")) && p_options[SNAME("blender/meshes/colors")]) {
		parameters_map["export_colors"] = true;
	} else {
		parameters_map["export_colors"] = false;
	}
}
```

**Comment by akien-mga** [comment]
@copygirl This is 4.3 code, but you're using Godot 4.2.2, which predates Blender 4.2 and its compat breakage on the `export_colors` parameter. This was already fixed by #93998 which will be cherry-picked for Godot 4.2.3 once I get a respite from finalizing 4.3 :)

Still, there's room for improving how our importer deals with failing Blender exports. You also seem to be having issues using the rpcxml method, which may be the issue that was found to be specific to the Arch package maybe?

**Comment by copygirl** [comment]
@akien-mga Considering how much effort I put into code surfing, I sure could've checked when that code was committed. :sweat_smile: Alright. All good, then. On the bright side, I hopefully will have added some information on how people can get some info on why the importing fails, if it still does.

Not sure what the socket errors mean. Are they related to communicating with Blender? It feels like the rpcxml thing works fine, after all it appears to return status code 200. Maybe the same error occurs, but it simply doesn't get displayed using this method?

**Comment by ttencate** [comment]
This issue is getting rather convoluted now, with various ways in which Blender imports can fail, some of which are tracked and fixed in other issues:

1. Whatever caused the [original report](https://github.com/godotengine/godot/issues/80530#issue-1847549280)
2. `export_nla_strips` being removed since Blender 3.6 (tracked in #80540)
3. Draco mesh compression not being supported by Godot
4. `export_colors` being removed since Blender 4.2 (fixed in #93998)

I propose for _this_ issue to be repurposed and renamed to: **Blender import failure causes endless dialog loop**, regardless of the cause of the import failure. Thus, it has nothing to do with Blender versions, and not with Arch Linux either.
