### ISSUE TITLE
Crash with references to nodes imported from blender after re-importing

### ISSUE THREAD

**Issue by ostannard** [godotengine/godot#80540]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3179) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

This project has a simple file imported from blender, with "editable children" ticked so the mesh shows up in the scene tree. The script on the top-level node has an exported Node3D property, which is set to the MeshInstance3D from the blender file. After re-importing the blender file, godot crashes, usually after changing focus between nodes and views a few times. I've found one sequence which causes the crash reliably on the attached project, for me at least.

### Steps to reproduce

* Open project in godot. `main.tscn` should be open, in the 3d view, with `TopLevel` selected
* Open `cube.blend` in blender
* Modify the blender file (I've been moving the cube slightly)
* Save the blender file
* Switch focus back to godot, it will re-import the modified blender file
* Switch to 2d view
* Switch to 3d view
* Select `cube` in the scene tree
* Select `TopLevel` in the scene tree, and godot crashes

### Minimal reproduction project

[GodotTest.zip](https://github.com/godotengine/godot/files/12327152/GodotTest.zip)

**Comment by philipp-gaddi** [comment]
I can confirm this. I think this seems to be a problem with blender 3.6, because older blender versions, i tested 3.3, work. So there could have been a change from 3.5 to 3.6 that interfere with the export script made in godot.

**Comment by philipp-gaddi** [comment]
```
blender --background --python-expr "
import bpy, sys

opts = {
    'unpack_all': True,
    'path': '/home/phil/ngp2/files/box.blend',
    'gltf_options': {
        'filepath': '/home/phil/ngp2/.godot/imported/box-e032219c0ca3957daa5daa75b4d14da0.gltf',
        'export_keep_originals': False,
        'export_format': 'GLTF_SEPARATE',
        'export_yup': True,
        'export_extras': True,
        'export_skins': True,
        'export_all_influences': True,
        'export_materials': 'EXPORT',
        'export_cameras': True,
        'export_lights': True,
        'export_colors': False,
        'use_renderable': False,
        'use_visible': False,
        'export_texcoords': True,
        'export_normals': True,
        'export_tangents': True,
        'export_nla_strips': True,
        'export_frame_range': True,
        'export_force_sampling': True,
        'export_def_bones': False,
        'export_apply': True,
    },
}

if bpy.app.version < (3, 0, 0):
    print('Blender 3.0 or higher is required.', file=sys.stderr)

bpy.ops.wm.open_mainfile(filepath=opts['path'])

if opts['unpack_all']:
    bpy.ops.file.unpack_all(method='USE_LOCAL')

bpy.ops.export_scene.gltf(**opts['gltf_options'])
"
```

this is the script use by godot to import blend files as gltf and so on. when i run this in the console i get error
```
Error: Python: Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties: : keyword "export_nla_strips" unrecognized
```
and when i remove just the ```export_nla_strips``` the script runs through. The docs of blender https://docs.blender.org/api/current/bpy.ops.export_scene.html don't show that the keyword has changed.

After some investigation i found this:
In https://github.com/KhronosGroup/glTF-Blender-IO/blob/main/addons/io_scene_gltf2/__init__.py at line 624, it is mentioned, that ```export_nla_strips``` is removed in 3.6, hence the error. Instead ```export_animation_mode``` should be used.
To fix the import script, you have to remove the ```exports_nla_strips``` code and replacing it with ```export_animation_mode``` set to ```NLA_TRACKS``` or ```ACTIONS``` in the file ```godot/modules/gltf/editor/editor_scene_importer_blend.cpp``` at 154. Which option is the right one should be tested.

This probably also affects the importer for blend files, which now has to offer the different options for ``export_animation_mode``` instead of being a checkbox.
