### ISSUE TITLE
[C#] Wrong type returned by ResourceLoader.Load when attempting to load a custom resource in the editor context

### ISSUE THREAD

**Issue by steb-vs** [godotengine/godot#81002]
### Godot version

4.2.dev3

### System information

Windows 10 - Godot v4.2.dev3 - Valkan (Forward+)

### Issue description

When attempting to load a resource using a custom implemented type, `ResourceLoader.Load<>` returns the wrong type **only when called in the editor context**.

**Expected behavior**

`ResourceLoader.Load<>` should return an object of the custom type.
In the reproduction project, it should return an object of the type `MyCustomResource`, and print out the following lines to the ouput:

```
It works!
blah
123
1.2
```

**Actual behavior**

`ResourceLoader.Load<>` returns the default type `Resource`, causing an invalid cast exception when calling the function with a custom type.
In the reproduction project, this is the current output:

```
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'MyCustomResource'.
     at Godot.ResourceLoader.Load[T](String path, String typeHint, CacheMode cacheMode) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/ResourceLoaderExtensions.cs:line 27
     at MyCustomResourceLoader._Ready() in H:\Workspace\CustomResourceLoadingIssue\scripts\MyCustomResourceLoader.cs:line 11
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2101
     at MyCustomResourceLoader.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in H:\Workspace\CustomResourceLoadingIssue\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\MyCustomResourceLoader_ScriptMethods.generated.cs:line 38
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
```

**Additional note**

Everything works as expected when running the project. This issue only happen when the same code is running in the editor context / a script has the `[Tool]` attribute.

### Steps to reproduce

1. Create a custom resource type inheriting from `Resource` and with the `[GlobalClass]` attribute.
2. Compile the C# project, then go to the editor, and create a new resource of the newly implemented type. Copy the path to that file.
3. Create a C# script with the `[Tool]` attribute.
4. Override the _Ready method, and add a call to `ResourceLoader.Load<CustomType>("res://path/to/that/resource")`.

### Minimal reproduction project

[CustomResourceLoadingIssue.zip](https://github.com/godotengine/godot/files/12441911/CustomResourceLoadingIssue.zip)

To reproduce the issue, **you must close the main scene tab, then compile the C# project, then open the main scene again.**

**Comment by raulsntos** [comment]
You can't load a non-Tool resource from the editor. The `MyCustomResourceLoader` class is a Tool script which means it will run in the editor, when the `_Ready` method executes in the editor, it tries to load the custom resource `MyCustomResource` but this class is not a Tool script so it won't work. You need to add the `[Tool]` attribute to `MyCustomResource`.

Any custom node or resource instantiated by the editor that isn't a Tool script will be instantiated using the closest native Godot class (in this case `Godot.Resource`). So it can't be downcasted.

This is somewhat explained in the [_Running code in the editor_](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#doc-running-code-in-the-editor) documentation page, but it could be more prominent since a lot of users miss this:

- https://github.com/godotengine/godot/issues/55596
- https://github.com/godotengine/godot/issues/80298
- https://github.com/godotengine/godot/issues/80693

**Comment by steb-vs** [comment]
Thank you very much for the clarification, it helped a lot.

I have read the documentation page you linked. If I understand correctly, it is describing a case where you want **a script** to execute some code in the editor context. In my case, I'm not trying to run code from my resource. Since I only want Godot to know about my class I don' t understand why I can't just annotate with `GlobalClass`? I don't understand why `Tool` is required here, it feels like a workaround.

In my opinion, `GlobalClass` being already a way to interact with the editor, should be enough to register a custom resource type so that it can be created from the new resource creation dialog as well as being loaded from `Tool` scripts calling the `ResourceLoader.Load<>` API.

**Comment by raulsntos** [comment]
The `[GlobalClass]` attribute is enough for resource types to be created from the new resource creation dialog.
Loading them using `ResourceLoader` is also possible (even without the `[GlobalClass]` attribute).

You just can't cast them to `MyCustomResource` because the type is not available in the editor context, so you'll have to use whichever base class is available to the editor (in this case `Godot.Resource`).

This should work:

```csharp
// Note that you don't need to use the generic overload because the non-generic already returns Resource.
var myCustomResource = ResourceLoader.Load<Resource>("res://path/to/that/resource");

GD.Print("It works!");
GD.Print(myCustomResource.Property1);
GD.Print(myCustomResource.Property2);
GD.Print(myCustomResource.Property3);
```
