### ISSUE TITLE
Array - System.ArgumentException: Disposable not registered. (Parameter 'weakReference') on shutdown

### ISSUE THREAD

**Issue by SamiKalliomaki** [godotengine/godot#81231]
### Godot version

4.2

### System information

Windows 11

### Issue description

```
ERROR: System.ArgumentException: Disposable not registered. (Parameter 'weakReference')

   at Godot.DisposablesTracker.UnregisterDisposable(WeakReference`1 weakReference) in C:\Users\Sami\Documents\source\godot\engine\modules\mono\glue\GodotSharp\GodotSharp\Core\DisposablesTracker.cs:line 92

   at Godot.Collections.Array.Dispose(Boolean disposing) in C:\Users\Sami\Documents\source\godot\engine\modules\mono\glue\GodotSharp\GodotSharp\Core\Array.cs:line 173

   at Godot.Collections.Array.Dispose() in C:\Users\Sami\Documents\source\godot\engine\modules\mono\glue\GodotSharp\GodotSharp\Core\Array.cs:line 162

   at Godot.DisposablesTracker.OnGodotShuttingDownImpl() in C:\Users\Sami\Documents\source\godot\engine\modules\mono\glue\GodotSharp\GodotSharp\Core\DisposablesTracker.cs:line 55

   at Godot.DisposablesTracker.OnGodotShuttingDown() in C:\Users\Sami\Documents\source\godot\engine\modules\mono\glue\GodotSharp\GodotSharp\Core\DisposablesTracker.cs:line 17
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (C:/Users/Sami/Documents/source/godot/engine/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112)
```

### Steps to reproduce

1. Have a project that uses Array
2. Shutdown game when debugging with Visual Studio Code
3. Observe debug console

### Minimal reproduction project

N/A

**Comment by SamiKalliomaki** [comment]
Proposed fix in #81230

**Comment by raulsntos** [comment]
Godot 4.2 has not been released yet. Are you using one of the released `dev` builds? If so, please specify which one. If you are building Godot yourself, please specify from which commit.

Could you also provide an MRP? I'm unable to reproduce this issue.

**Comment by SamiKalliomaki** [comment]
I have verified the issue at the `master` branch as well as Godot version `4.1.1`. I tried to spend some time trying to reproduce the issue in a simpler project now but no luck so far.

I suspect a contributing factor is maybe having a Resource in the project with ArrayMesh as part of it. However, I was still not able to reproduce this. So maybe using MultiMeshInstance2D is also a contributing factor?

To me the issue from the code side looks quite clear but if we need a reproduction I may need to go the other direction and start deleting complexity from my project until I find the simplest reproduction.

**Comment by SamiKalliomaki** [comment]
I added some debug code to the Array class just to get the stack traces for the dispose calls.

First is:
```
51 is being disposed. Disposing: True
   at Godot.Collections.Array.Dispose(Boolean disposing)
   at Godot.Collections.Array.Dispose()
   at Godot.NativeInterop.VariantUtils.CreateFromSystemArrayOfGodotObject(GodotObject[] from)
   at CircuitGame.Ui.CircuitNodeList.GetGodotClassPropertyValue(godot_string_name& name, godot_variant& value)
   at Godot.Bridge.CSharpInstanceBridge.Get(IntPtr godotObjectGCHandle, godot_string_name* name, godot_variant* outRet)
```

Second:
```
51 is being disposed. Disposing: True
   at Godot.Collections.Array.Dispose(Boolean disposing)
   at Godot.Collections.Array.Dispose()
   at Godot.DisposablesTracker.OnGodotShuttingDownImpl()
   at Godot.DisposablesTracker.OnGodotShuttingDown()
```

**Comment by SamiKalliomaki** [comment]
Ok, I believe I habe debugged what is going wrong here.

The instance is created through this constructor:
https://github.com/godotengine/godot/blob/d2ae309f2cec2000257c1ff203a64170fc146b17/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs#L124

This constructor calls the base constructor that registers the disposable. However, the constructor also registers the disposable again itself.

When the object is disposed, it unregisters itself but this only removes one registration. Thus it will get disposed again on program exit.
