### ISSUE TITLE
GDScript crash when calling anonymous lambda stored as Callable

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#81572]
### Godot version

4.2.dev (98b50eb3083094a352b36b184d7b60b77ad982fe)

### System information

Mageia 9 - Vulkan (Forward+) - dedicated AMD Radeon RX Vega M GL Graphics (RADV VEGAM) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

I'm getting a crash in a project when using Godot 4.2-dev4 and later, which worked fine in 4.2-dev2 and earlier (including 4.1.x.). With 4.2-dev3, there's no crash but another regression preventing from running the project. So the crash causing regression happened between dev2 and dev4.

Stacktrace:
```
Thread 1 "godot.linuxbsd." received signal SIGSEGV, Segmentation fault.
0x0000000005459e80 in Variant::get_type (this=0x0) at ./core/variant/variant.h:330
330                     return type;

(gdb) bt
#0  0x0000000005459e80 in Variant::get_type (this=0x0) at ./core/variant/variant.h:330
#1  0x0000000005f0847d in GDScriptFunction::_get_call_error (this=0xddf0280, p_err=..., p_where=..., argptrs=0x7fffb0003f88) at ./modules/gdscript/gdscript_vm.cpp:121
#2  0x0000000005ec0a43 in GDScriptFunction::call (this=0xddf0280, p_instance=0xff6d690, p_args=0x0, p_argcount=0, r_err=..., p_state=0xf858c70) at ./modules/gdscript/gdscript_vm.cpp:1773
#3  0x0000000005e8d74c in GDScriptFunctionState::resume (this=0xf858b00, p_arg=...) at ./modules/gdscript/gdscript_function.cpp:216
#4  0x0000000005e8cfd3 in GDScriptFunctionState::_signal_callback (this=0xf858b00, p_args=0x7fffffff04f0, p_argcount=2, r_error=...) at ./modules/gdscript/gdscript_function.cpp:166
#5  0x0000000005fb0bb1 in MethodBindVarArgTR<GDScriptFunctionState, Variant>::call (this=0xdd3ab60, p_object=0xf858b00, p_args=0x7fffffff04f0, p_arg_count=2, r_error=...) at ./core/object/method_bind.h:260
#6  0x0000000009b0bafa in Object::callp (this=0xf858b00, p_method=..., p_args=0x7fffffff04f0, p_argcount=2, r_error=...) at ./core/object/object.cpp:766
#7  0x0000000009812ee0 in Callable::callp (this=0xfe069e0, p_arguments=0x7fffffff04f0, p_argcount=2, r_return_value=..., r_call_error=...) at ./core/variant/callable.cpp:62
#8  0x00000000098163bc in CallableCustomBind::call (this=0xfe069d0, p_arguments=0x7fffffff0850, p_argcount=1, r_return_value=..., r_call_error=...) at ./core/variant/callable_bind.cpp:144
#9  0x0000000009812bfe in Callable::callp (this=0xe28f1e0, p_arguments=0x7fffffff0850, p_argcount=1, r_return_value=..., r_call_error=...) at ./core/variant/callable.cpp:50
#10 0x0000000009b0d876 in Object::emit_signalp (this=0x7fffb0005120, p_name=..., p_args=0x7fffffff0850, p_argcount=1) at ./core/object/object.cpp:1113
#11 0x0000000005f2274e in Object::emit_signal<Variant> (this=0x7fffb0005120, p_name=...) at ./core/object/object.h:899
#12 0x0000000005e8d945 in GDScriptFunctionState::resume (this=0x7fffb0005120, p_arg=...) at ./modules/gdscript/gdscript_function.cpp:237
#13 0x0000000005e8cfd3 in GDScriptFunctionState::_signal_callback (this=0x7fffb0005120, p_args=0x7fffffff0d00, p_argcount=1, r_error=...) at ./modules/gdscript/gdscript_function.cpp:166
#14 0x0000000005fb0bb1 in MethodBindVarArgTR<GDScriptFunctionState, Variant>::call (this=0xdd3ab60, p_object=0x7fffb0005120, p_args=0x7fffffff0d00, p_arg_count=1, r_error=...) at ./core/object/method_bind.h:260
#15 0x0000000009b0bafa in Object::callp (this=0x7fffb0005120, p_method=..., p_args=0x7fffffff0d00, p_argcount=1, r_error=...) at ./core/object/object.cpp:766
#16 0x0000000009812ee0 in Callable::callp (this=0xfe0b970, p_arguments=0x7fffffff0d00, p_argcount=1, r_return_value=..., r_call_error=...) at ./core/variant/callable.cpp:62
#17 0x00000000098163bc in CallableCustomBind::call (this=0xfe0b960, p_arguments=0x7fffffff12b8, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/variant/callable_bind.cpp:144
#18 0x0000000009812bfe in Callable::callp (this=0xfe123c8, p_arguments=0x7fffffff12b8, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/variant/callable.cpp:50
#19 0x0000000009b0d876 in Object::emit_signalp (this=0xe246e60, p_name=..., p_args=0x7fffffff12b8, p_argcount=0) at ./core/object/object.cpp:1113
#20 0x000000000981590e in Signal::emit (this=0x7fffffff1290, p_arguments=0x7fffffff12b8, p_argcount=0) at ./core/variant/callable.cpp:463
#21 0x000000000998cc60 in _VariantCall::func_Signal_emit (v=0x7fffffff1288, p_args=0x7fffffff12b8, p_argcount=0, r_ret=..., r_error=...) at ./core/variant/variant_call.cpp:1060
#22 0x000000000986b841 in Method_Signal_emit::call (base=0x7fffffff1288, p_args=0x7fffffff12b8, p_argcount=0, r_ret=..., p_defvals=..., r_error=...) at ./core/variant/variant_call.cpp:2058
#23 0x0000000009826d79 in Variant::callp (this=0x7fffffff1288, p_method=..., p_args=0x7fffffff12b8, p_argcount=0, r_ret=..., r_error=...) at ./core/variant/variant_call.cpp:1182
#24 0x0000000005ec05b5 in GDScriptFunction::call (this=0xde31900, p_instance=0xff6e430, p_args=0x7fffffff6c78, p_argcount=0, r_err=..., p_state=0x0) at ./modules/gdscript/gdscript_vm.cpp:1733
#25 0x0000000005e1b01f in GDScriptInstance::callp (this=0xff6e430, p_method=..., p_args=0x7fffffff6c78, p_argcount=0, r_error=...) at ./modules/gdscript/gdscript.cpp:1843
#26 0x0000000009b0ba13 in Object::callp (this=0xe246e60, p_method=..., p_args=0x7fffffff6c78, p_argcount=0, r_error=...) at ./core/object/object.cpp:744
#27 0x0000000009826cc0 in Variant::callp (this=0x7fffffff6b70, p_method=..., p_args=0x7fffffff6c78, p_argcount=0, r_ret=..., r_error=...) at ./core/variant/variant_call.cpp:1170
#28 0x0000000005ec05b5 in GDScriptFunction::call (this=0xde31d40, p_instance=0xff6e430, p_args=0x7fffffffc780, p_argcount=4, r_err=..., p_state=0x0) at ./modules/gdscript/gdscript_vm.cpp:1733
#29 0x0000000005e1b01f in GDScriptInstance::callp (this=0xff6e430, p_method=..., p_args=0x7fffffffc780, p_argcount=4, r_error=...) at ./modules/gdscript/gdscript.cpp:1843
#30 0x0000000009b0ba13 in Object::callp (this=0xe246e60, p_method=..., p_args=0x7fffffffc780, p_argcount=4, r_error=...) at ./core/object/object.cpp:744
#31 0x0000000009812ee0 in Callable::callp (this=0xd9ed1f0, p_arguments=0x7fffffffc780, p_argcount=4, r_return_value=..., r_call_error=...) at ./core/variant/callable.cpp:62
#32 0x0000000009b0d876 in Object::emit_signalp (this=0xdf89bb0, p_name=..., p_args=0x7fffffffc780, p_argcount=4) at ./core/object/object.cpp:1113
#33 0x0000000007bcd462 in Node::emit_signalp (this=0xdf89bb0, p_name=..., p_args=0x7fffffffc780, p_argcount=4) at ./scene/main/node.cpp:3587
#34 0x0000000007c3c62d in Object::emit_signal<int, int, Vector<String>, Vector<unsigned char> > (this=0xdf89bb0, p_name=...) at ./core/object/object.h:899
#35 0x0000000007ba9e96 in HTTPRequest::_request_done (this=0xdf89bb0, p_status=0, p_code=200, p_headers=..., p_data=...) at ./scene/main/http_request.cpp:481
#36 0x0000000007ccf671 in call_with_variant_args_helper<__UnexistingClass, int, int, Vector<String> const&, Vector<unsigned char> const&, 0ul, 1ul, 2ul, 3ul> (p_instance=0xdf89bb0, 
    p_method=(void (__UnexistingClass::*)(__UnexistingClass * const, int, int, const Vector<String> &, const Vector<unsigned char> &)) 0x7ba9e16 <HTTPRequest::_request_done(int, int, Vector<String> const&, Vector<unsigned char> const&)>, p_args=0x7fffffffc970, r_error=...) at ./core/variant/binder_common.h:303
#37 0x0000000007cb4384 in call_with_variant_args_dv<__UnexistingClass, int, int, Vector<String> const&, Vector<unsigned char> const&> (p_instance=0xdf89bb0, 
    p_method=(void (__UnexistingClass::*)(__UnexistingClass * const, int, int, const Vector<String> &, const Vector<unsigned char> &)) 0x7ba9e16 <HTTPRequest::_request_done(int, int, Vector<String> const&, Vector<unsigned char> const&)>, p_args=0x7fffffffcbe0, p_argcount=4, r_error=..., default_values=...) at ./core/variant/binder_common.h:450
#38 0x0000000007c9a990 in MethodBindT<int, int, Vector<String> const&, Vector<unsigned char> const&>::call (this=0xc755f50, p_object=0xdf89bb0, p_args=0x7fffffffcbe0, p_arg_count=4, r_error=...)
    at ./core/object/method_bind.h:331
#39 0x0000000009b0bafa in Object::callp (this=0xdf89bb0, p_method=..., p_args=0x7fffffffcbe0, p_argcount=4, r_error=...) at ./core/object/object.cpp:766
#40 0x0000000009812ee0 in Callable::callp (this=0xd3723d0, p_arguments=0x7fffffffcbe0, p_argcount=4, r_return_value=..., r_call_error=...) at ./core/variant/callable.cpp:62
#41 0x0000000009b06019 in CallQueue::_call_function (this=0xad970e0, p_callable=..., p_args=0xd3723e8, p_argcount=4, p_show_error=false) at ./core/object/message_queue.cpp:219
#42 0x0000000009b0673e in CallQueue::flush (this=0xad970e0) at ./core/object/message_queue.cpp:324
#43 0x0000000007bd0a57 in SceneTree::physics_process (this=0xd3886e0, p_time=0.016666666666666666) at ./scene/main/scene_tree.cpp:471
#44 0x000000000547e04b in Main::iteration () at main/main.cpp:3467
#45 0x00000000053fd320 in OS_LinuxBSD::run (this=0x7fffffffcf50) at platform/linuxbsd/os_linuxbsd.cpp:933
#46 0x00000000053f5dc0 in main (argc=1, argv=0x7fffffffd538) at platform/linuxbsd/godot_linuxbsd.cpp:74
```

This works around the crash, but the call still fails so functionality is broken:
```diff
diff --git a/modules/gdscript/gdscript_vm.cpp b/modules/gdscript/gdscript_vm.cpp
index a7dc0b6d59..7545108c53 100644
--- a/modules/gdscript/gdscript_vm.cpp
+++ b/modules/gdscript/gdscript_vm.cpp
@@ -116,6 +116,7 @@ String GDScriptFunction::_get_call_error(const Callable::CallError &p_err, const
 
 	if (p_err.error == Callable::CallError::CALL_ERROR_INVALID_ARGUMENT) {
 		int errorarg = p_err.argument;
+		ERR_FAIL_NULL_V_MSG(argptrs[errorarg], "Invalid argument type in " + p_where + ".", "CallError holds invalid pointers to arguments.");
 		// Handle the Object to Object case separately as we don't have further class details.
 #ifdef DEBUG_ENABLED
 		if (p_err.expected == Variant::OBJECT && argptrs[errorarg]->get_type() == p_err.expected) {
```
Might be worth committing anyway to catch such bugs if we prefer error prints to a nullptr dereference.

With this patch, I get this output:
```
ERROR: CallError holds invalid pointers to arguments.
   at: _get_call_error (./modules/gdscript/gdscript_vm.cpp:119)
SCRIPT ERROR: Invalid argument type in function '<anonymous lambda>(lambda) (Callable)'.
          at: async (res://addons/w4gd/rest-client/client_promise.gd:44)
SCRIPT ERROR: Invalid call. Nonexistent function 'is_error' in base 'Nil'.
          at: host_game_w4_cloud (res://autoloads/Net.gd:43)
```
The script errors are the consequence of `await`'ing a `Callable.call()` that fails.

---

I'm seeing this on an internal W4 demo, which isn't public yet.

I haven't attempted to extract a MRP yet, but I've done some checks to identify what caused the regression. As pointed out above, it's tricky to bisect as there have been multiple regressions between dev2 and dev4.

But I have a strong suspicion for #79880 or one of its follow-up regression fixes. I confirmed it by reverting these 4 related commits (first 3 needed to revert #79880 cleanly), which solves the bug.

```
commit a26cffb2c473de7875298989301f3b95b3fa9498 (HEAD -> test)
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Tue Sep 12 13:12:54 2023 +0200

    Revert "GDScript: Fix bug with identifier shadowed below in current scope"
    
    This reverts commit d53fc92b4c6b5e4484e8f0bfff6ac55163dde3fb.

commit 880735f89bdc740fb7c38dce162c4f900e46133f
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Tue Sep 12 13:12:49 2023 +0200

    Revert "GDScript: Allow use local constants as types"
    
    This reverts commit 68a567bd1389a2cb410fc002632ccd5b5fb59f5c.

commit efd2eda69d538fb495df195df6a5309f19e76dfc
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Tue Sep 12 13:06:38 2023 +0200

    Revert "GDScript: Fix regression with native signal not found"
    
    This reverts commit f19377160cb6cee6db223660ce8df02d18c38a08.

commit 27f5f22ec31998af9dc960e7158e863fdb417bfc
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Tue Sep 12 13:06:23 2023 +0200

    Revert "GDScript: Fix "Identifier not found" error when accessing inner class from inside"

    This reverts commit fb45cab133103de4f641cc72a553a28463bed7fd.
```

*Edit:* I've tested with revert just the 3 last PRs and not #79980, and I get an endless stream of compilation errors, like in 4.2-dev3. So the problem did start with #79980, and morphed from compilation errors to a lambda call failure in a follow-up.

CC @dalexeev 

### Steps to reproduce

TBD

### Minimal reproduction project

The project where I reproduced it is moderately complex and I haven't extracted a MRP yet. I can't share the project publicly yet, but I can share it privately with GDScript maintainers.

**Comment by dalexeev** [comment]
It looks like my PRs for some reason exposed another existing bug. I've noticed similar lambda related crashes before, but I couldn't localize them. Probably related:

* #62769
* #69491
* #74607
