### ISSUE TITLE
Android 3D crashes and black screen

### ISSUE THREAD

**Issue by mahdisml** [godotengine/godot#82525]
### Godot version

4.1.1 Stable

### System information

Android 12 - 4.1.1 Stable - Snapdragon 720G adreno 618 - Vulkan Mobile

### Issue description

Hi ! Everything is okay in 2D, but when my scene goes 3D, it crashes. sometimes shows black screen with displaying my 2D HUD.
(Everything works in my editor (windows))

with debug i got this error in logs (When its comes with BlackScreen) :

```
E  open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found

```

(When it Crashes) :

```
E  open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x716a5fdf88 in tid 13436 (VkThread), pid 13391
```

probably related with : 
https://godotforums.org/d/34483-godot-4-camera3d-crashes-android-device
https://github.com/godotengine/godot/issues/82237 

full log :

```
2023-09-29 16:27:42.487 13391-13391 ziparchive              dev.mahdisml.testapp                   W  Unable to open '/data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/base.dm': No such file or directory
2023-09-29 16:27:42.487 13391-13391 ziparchive              dev.mahdisml.testapp                   W  Unable to open '/data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/base.dm': No such file or directory
2023-09-29 16:27:42.530 13391-13391 nativeloader            dev.mahdisml.testapp                   D  Configuring clns-4 for other apk /data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/lib/arm64:/data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/dev.mahdisml.testapp
2023-09-29 16:27:42.539 13391-13391 Perf                    dev.mahdisml.testapp                   I  Connecting to perf service.
2023-09-29 16:27:42.545 13391-13391 GraphicsEnvironment     dev.mahdisml.testapp                   V  ANGLE Developer option for 'dev.mahdisml.testapp' set to: 'default'
2023-09-29 16:27:42.546 13391-13391 GraphicsEnvironment     dev.mahdisml.testapp                   V  Neither updatable production driver nor prerelease driver is supported.
2023-09-29 16:27:42.549 13391-13391 ForceDarkHelperStubImpl dev.mahdisml.testapp                   I  initialize for dev.mahdisml.testapp , ForceDarkOrigin
2023-09-29 16:27:42.550 13391-13391 OpenGLRenderer          dev.mahdisml.testapp                   D  JNI_OnLoad success
2023-09-29 16:27:42.550 13391-13391 MiuiForceDarkConfig     dev.mahdisml.testapp                   I  setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
2023-09-29 16:27:42.552 13391-13391 NetworkSecurityConfig   dev.mahdisml.testapp                   D  No Network Security Config specified, using platform default
2023-09-29 16:27:42.552 13391-13391 NetworkSecurityConfig   dev.mahdisml.testapp                   D  No Network Security Config specified, using platform default
2023-09-29 16:27:42.618 13391-13391 ViewScrollStubImpl      dev.mahdisml.testapp                   D  the value of mScrollFrictionRes is: 0.015
2023-09-29 16:27:42.687 13391-13391 MiuiMultiWindowUtils    dev.mahdisml.testapp                   D  freeform resolution args raw data:{  "zizhan":{    "freeform_args": {      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}}    },    "mini_freeform_args":{      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.165},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.165}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.293},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.293}}    }  },  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":0.125,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":-1,"left_margin":0.0714},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":0.125,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":-1,"left_margin":0.0714}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "vertical_landscape":{"aspect_ratio":-1, "original_ratio":0.144},        "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":0.144}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":1,"original_scale":0.7182,"top_margin":0.142,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.8, "original_ratio":1,"original_scale":0.7182,"top_margin":-1,"left_margin":0.05},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":0.142,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":-1,"left_margin":0.05}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "vertical_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3},        "horizontal_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio
2023-09-29 16:27:42.701 13391-13391 System.err              dev.mahdisml.testapp                   W  org.json.JSONException: No value for curtana
2023-09-29 16:27:42.702 13391-13391 System.err              dev.mahdisml.testapp                   W  	at org.json.JSONObject.get(JSONObject.java:398)
2023-09-29 16:27:42.702 13391-13391 System.err              dev.mahdisml.testapp                   W  	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
2023-09-29 16:27:42.702 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgsOfDevice(MiuiMultiWindowUtils.java:1433)
2023-09-29 16:27:42.702 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.util.MiuiMultiWindowUtils.initFreeFormResolutionArgs(MiuiMultiWindowUtils.java:1427)
2023-09-29 16:27:42.702 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.util.MiuiMultiWindowUtils.<clinit>(MiuiMultiWindowUtils.java:209)
2023-09-29 16:27:42.702 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorViewMultiWinStubImpl.<init>(DecorViewMultiWinStubImpl.java:19)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider$SINGLETON.<clinit>(DecorViewMultiWinStubImpl$Provider.java:21)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideSingleton(DecorViewMultiWinStubImpl$Provider.java:10)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorViewMultiWinStubImpl$Provider.provideSingleton(DecorViewMultiWinStubImpl$Provider.java:8)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.miui.base.MiuiStubRegistry.get(MiuiStubRegistry.java:129)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.miui.base.MiuiStubRegistry.get(MiuiStubRegistry.java:123)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.miui.base.MiuiStubUtil.getInstance(MiuiStubUtil.java:46)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.miui.base.MiuiStubUtil.getImpl(MiuiStubUtil.java:30)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorViewMultiWinStub$SingletonHolder.<clinit>(DecorViewMultiWinStub.java:11)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorViewMultiWinStub.newInstance(DecorViewMultiWinStub.java:16)
2023-09-29 16:27:42.704 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.DecorView.<init>(DecorView.java:335)
2023-09-29 16:27:42.705 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2380)
2023-09-29 16:27:42.705 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2760)
2023-09-29 16:27:42.705 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2140)
2023-09-29 16:27:42.705 13391-13391 System.err              dev.mahdisml.testapp                   W  	at androidx.activity.ComponentActivity.initViewTreeOwners(ComponentActivity.java:431)
2023-09-29 16:27:42.705 13391-13391 System.err              dev.mahdisml.testapp                   W  	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:402)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:63)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.Activity.performCreate(Activity.java:8163)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.Activity.performCreate(Activity.java:8130)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2023-09-29 16:27:42.713 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.os.Looper.loopOnce(Looper.java:210)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.os.Looper.loop(Looper.java:299)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at android.app.ActivityThread.main(ActivityThread.java:8319)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at java.lang.reflect.Method.invoke(Native Method)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2023-09-29 16:27:42.714 13391-13391 System.err              dev.mahdisml.testapp                   W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
2023-09-29 16:27:42.714 13391-13391 IS_CTS_MODE             dev.mahdisml.testapp                   D  false
2023-09-29 16:27:42.714 13391-13391 MULTI_WIND...CH_ENABLED dev.mahdisml.testapp                   D  false
2023-09-29 16:27:42.715 13391-13391 IS_CTS_MODE             dev.mahdisml.testapp                   D  false
2023-09-29 16:27:42.715 13391-13391 MULTI_WIND...CH_ENABLED dev.mahdisml.testapp                   D  false
2023-09-29 16:27:42.715 13391-13391 IS_CTS_MODE             dev.mahdisml.testapp                   D  false
2023-09-29 16:27:42.715 13391-13391 MULTI_WIND...CH_ENABLED dev.mahdisml.testapp                   D  false
2023-09-29 16:27:42.735 13391-13391 DecorView[]             dev.mahdisml.testapp                   D  getWindowModeFromSystem  windowmode is 1
2023-09-29 16:27:42.752 13391-13391 FullScreenGodotApp      dev.mahdisml.testapp                   V  Creating new Godot fragment instance.
2023-09-29 16:27:42.962 13391-13391 DecorView[]             dev.mahdisml.testapp                   D  getWindowModeFromSystem  windowmode is 1
2023-09-29 16:27:42.962 13391-13391 DecorView[]             dev.mahdisml.testapp                   D  updateDecorCaptionStatus displayWindowDecor is false
2023-09-29 16:27:42.970 13391-13391 Looper                  dev.mahdisml.testapp                   W  PerfMonitor looperActivity : package=dev.mahdisml.testapp/com.godot.game.GodotApp time=1ms latency=502ms running=2ms  procState=-1  historyMsgCount=4 (msgIndex=3 wall=97ms seq=3 running=77ms runnable=11ms h=android.app.ActivityThread$H w=110) (msgIndex=4 wall=402ms seq=4 running=200ms runnable=52ms late=100ms h=android.app.ActivityThread$H w=159)
2023-09-29 16:27:42.992 13391-13391 DecorView[]             dev.mahdisml.testapp                   D  getWindowModeFromSystem  windowmode is 1
2023-09-29 16:27:42.992 13391-13391 DecorView[]             dev.mahdisml.testapp                   D  updateDecorCaptionStatus displayWindowDecor is false
2023-09-29 16:27:43.016 13391-13414 AdrenoGLES-0            dev.mahdisml.testapp                   I  QUALCOMM build                   : 820d4a4028, I5580630f49
                                                                                                    Build Date                       : 11/04/21
                                                                                                    OpenGL ES Shader Compiler Version: EV031.32.02.16
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2023-09-29 16:27:43.016 13391-13414 AdrenoGLES-0            dev.mahdisml.testapp                   I  Build Config                     : S P 10.0.7 AArch64
2023-09-29 16:27:43.016 13391-13414 AdrenoGLES-0            dev.mahdisml.testapp                   I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2023-09-29 16:27:43.020 13391-13414 AdrenoGLES-0            dev.mahdisml.testapp                   I  PFP: 0x016ee190, ME: 0x00000000
2023-09-29 16:27:43.031 13391-13414 hw-ProcessState         dev.mahdisml.testapp                   D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2023-09-29 16:27:43.035 13391-13391 SurfaceView             dev.mahdisml.testapp                   D  UPDATE null, mIsCastMode = false
2023-09-29 16:27:43.040 13391-13436 godot                   dev.mahdisml.testapp                   I  Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
2023-09-29 16:27:43.043 13391-13436 godot                   dev.mahdisml.testapp                   I  TextServer: Added interface "Dummy"
2023-09-29 16:27:43.055 13391-13414 .mahdisml.gula          dev.mahdisml.testapp                   E  open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
2023-09-29 16:27:43.064 13391-13391 SurfaceView             dev.mahdisml.testapp                   D  UPDATE Surface(name=SurfaceView[dev.mahdisml.testapp/com.godot.game.GodotApp])/@0xb664f3, mIsProjectionMode = false
2023-09-29 16:27:43.065 13391-13436 godot                   dev.mahdisml.testapp                   I  TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
2023-09-29 16:27:43.076 13391-13436 vulkan                  dev.mahdisml.testapp                   D  searching for layers in '/data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/lib/arm64'
2023-09-29 16:27:43.076 13391-13436 vulkan                  dev.mahdisml.testapp                   D  searching for layers in '/data/app/~~7QXTyBAF_wBw4-UIeDAToA==/dev.mahdisml.testapp-p0fHcwjUmWtc2lkhZ4_YtA==/base.apk!/lib/arm64-v8a'
2023-09-29 16:27:43.076 13391-13436 godot                   dev.mahdisml.testapp                   I  Optional extension VK_EXT_debug_utils not found
2023-09-29 16:27:43.082 13391-13436 AdrenoVK-0              dev.mahdisml.testapp                   I  ===== BEGIN DUMP OF OVERRIDDEN SETTINGS =====
2023-09-29 16:27:43.082 13391-13436 AdrenoVK-0              dev.mahdisml.testapp                   I  ===== END DUMP OF OVERRIDDEN SETTINGS =====
2023-09-29 16:27:43.082 13391-13436 AdrenoVK-0              dev.mahdisml.testapp                   I  QUALCOMM build          : 820d4a4028, I5580630f49
                                                                                                    Build Date              : 11/04/21
                                                                                                    Shader Compiler Version : EV031.32.02.16
                                                                                                    Local Branch            : 
                                                                                                    Remote Branch           : 
                                                                                                    Remote Branch           : 
                                                                                                    Reconstruct Branch      : 
2023-09-29 16:27:43.082 13391-13436 AdrenoVK-0              dev.mahdisml.testapp                   I  Build Config            : S P 10.0.7 AArch64
2023-09-29 16:27:43.082 13391-13436 AdrenoVK-0              dev.mahdisml.testapp                   I  Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
2023-09-29 16:27:43.086 13391-13436 godot                   dev.mahdisml.testapp                   I  Vulkan devices:
2023-09-29 16:27:43.086 13391-13436 godot                   dev.mahdisml.testapp                   I    #0: Qualcomm Adreno (TM) 618 - Supported, Integrated
2023-09-29 16:27:43.086 13391-13436 godot                   dev.mahdisml.testapp                   I  Vulkan API 1.1.128 - Forward Mobile - Using Vulkan Device #0: Qualcomm - Adreno (TM) 618
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I  Optional extension VK_KHR_fragment_shading_rate not found
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I  Optional extension VK_KHR_16bit_storage not found
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I  - Vulkan Variable Rate Shading not supported
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I  - Vulkan multiview supported:
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I    max view count: 6
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I    max instances: 4294967295
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I  - Vulkan subgroup:
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I    size: 64
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I    stages: STAGE_COMPUTE
2023-09-29 16:27:43.087 13391-13436 godot                   dev.mahdisml.testapp                   I    supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE
2023-09-29 16:27:43.088 13391-13391 DecorView[]             dev.mahdisml.testapp                   D  onWindowFocusChanged hasWindowFocus true
2023-09-29 16:27:43.091 13391-13436 godot                   dev.mahdisml.testapp                   I  Using present mode: VK_PRESENT_MODE_MAILBOX_KHR
2023-09-29 16:27:43.121 13391-13436 godot                   dev.mahdisml.testapp                   I  Startup PSO cache (0.4 MiB)
2023-09-29 16:27:43.123 13391-13436 godot                   dev.mahdisml.testapp                   I  Using "default" pen tablet driver...
2023-09-29 16:27:43.124 13391-13436 godot                   dev.mahdisml.testapp                   I  Creating VMA small objects pool for memory type index 0
2023-09-29 16:27:43.126 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CanvasSdfShaderRD' SHA256: 69889b33026d98c9285a346194a1fb1bf83e5288b9690fab153cfb3c17662b86
2023-09-29 16:27:43.133 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'SkeletonShaderRD' SHA256: 0099811fb3bad8b2b8ca64d732658e93824c306d4782117d3ef82bbe66393597
2023-09-29 16:27:43.137 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'SortShaderRD' SHA256: 40920f3d62acd63ea51108eca2744dc51cc4e7ce948eba4d1c8ec4f9184a2090
2023-09-29 16:27:43.138 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'ParticlesShaderRD' SHA256: bf806f90a7d64b5408f32c15a89552dfa22acf3fa645548596fadfa3effaa029
2023-09-29 16:27:43.140 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'ParticlesCopyShaderRD' SHA256: 2369ae441912975b0e9825d6dfeaa3d6a219590e8d0bbdcf351ffec8675f9296
2023-09-29 16:27:43.155 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CanvasShaderRD' SHA256: e5f13424e1230ddc9730ce03991ed83a8a7a128a49e59de337f594f3c4ce2225
2023-09-29 16:27:43.158 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CanvasOcclusionShaderRD' SHA256: 0046faa32106f99ab9959e5d6947aeba7cb97ba5d48f365f992a49053c5e84e9
2023-09-29 16:27:43.174 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'SceneForwardMobileShaderRD' SHA256: 4f2e85b8fe6f3b78b22c5eafb5e77179f079cdcb722268714171df2b8c0f958e
2023-09-29 16:27:43.181 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'SkyShaderRD' SHA256: e3be75fbf9fe56b725a3f5603f3d18d5bc2e573994e52343269c323e3393ab42
2023-09-29 16:27:43.184 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'BokehDofRasterShaderRD' SHA256: 67fe5ad260e6321363dda1de7d5b84c4ec15e09ca88a09f65a790a260335a861
2023-09-29 16:27:43.188 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'BlurRasterShaderRD' SHA256: 2fda8b00e8a9145d9c4c514e80890651b3bf6f47daa0fa4d3fde056fd35157ba
2023-09-29 16:27:43.188 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CopyToFbShaderRD' SHA256: e27a3604fa1f029f6026da6211fb0f902cdf85a85186b274a78b3285f45c4a4a
2023-09-29 16:27:43.189 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CubeToDpShaderRD' SHA256: d9502c62f9b7f3ed3e4c841c55cbe656115521e7a9ee83fa55c0f9e20fa51541
2023-09-29 16:27:43.189 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CubemapDownsamplerRasterShaderRD' SHA256: 86f1347cbfdcf7840ae4dfa1166f4bbd2b7c2c0a76649f61577498d1ef54bef6
2023-09-29 16:27:43.189 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CubemapFilterRasterShaderRD' SHA256: 548f079c102f33b8e4890dd6cc9e3141208f91deb1d0152da89a429275119146
2023-09-29 16:27:43.190 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'CubemapRoughnessRasterShaderRD' SHA256: 30655a16d02ae29a65a9d13c03f2e9fcaffc77f90418c6a1f54d35d07b49f534
2023-09-29 16:27:43.190 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'SpecularMergeShaderRD' SHA256: 2174d9ba72b5783ae549ba96d0b91eb9ab222d1263391466df0870b272d7378b
2023-09-29 16:27:43.190 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'LuminanceReduceRasterShaderRD' SHA256: 5ee8afa4b1eb952ef197e19270fc5e94df2111b8d546869007a7dc3ddba64df0
2023-09-29 16:27:43.191 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'TonemapShaderRD' SHA256: a3a3d0eefb2c8c275b17518402b466c3b86e2311ac4c3090d53c7d1501fb0bd1
2023-09-29 16:27:43.192 13391-13436 godot                   dev.mahdisml.testapp                   I  Shader 'BlitShaderRD' SHA256: 37cceb064042ba2506be49a39d2db4f0a4dad253e3514cf73d530c1959ffbe85
2023-09-29 16:27:43.200 13391-13436 godot                   dev.mahdisml.testapp                   I   
2023-09-29 16:27:43.201 13391-13436 .mahdisml.gula          dev.mahdisml.testapp                   D  PlayerBase::PlayerBase()
2023-09-29 16:27:43.203 13391-13436 .mahdisml.gula          dev.mahdisml.testapp                   D  TrackPlayerBase::TrackPlayerBase()
2023-09-29 16:27:43.203 13391-13436 libOpenSLES             dev.mahdisml.testapp                   I  Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
2023-09-29 16:27:43.221 13391-13436 AudioTrack              dev.mahdisml.testapp                   D  createTrack_l(318771987): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1772
2023-09-29 16:27:43.236 13391-13436 godot                   dev.mahdisml.testapp                   I  TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
2023-09-29 16:27:43.400 13391-13436 godot                   dev.mahdisml.testapp                   I  CORE API HASH: 3144975361
2023-09-29 16:27:43.401 13391-13436 godot                   dev.mahdisml.testapp                   I  EDITOR API HASH: 3244853458
2023-09-29 16:27:44.250 13391-13436 godot                   dev.mahdisml.testapp                   I  Loaded system CA certificates
2023-09-29 16:27:44.274 13391-13436 godot                   dev.mahdisml.testapp                   I  Creating VMA small objects pool for memory type index 1
2023-09-29 16:27:44.288 13391-13436 libc                    dev.mahdisml.testapp                   A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x716a5fdf88 in tid 13436 (VkThread), pid 13391 (.mahdisml.testapp)
2023-09-29 16:27:44.416 13391-13468 AudioTrack              dev.mahdisml.testapp                   I  isLongTimeZoreData zoer date time 1 Seconds

```

### Steps to reproduce

having any 3D scene in android devices

### Minimal reproduction project

https://drive.google.com/file/d/1_EQKzXjswSwvoFuCY-1tIbDRIGql-8An/view?usp=drive_link

**Comment by mahdisml** [comment]
sometimes it gets weird (i just rebuild project) :
![image](https://github.com/godotengine/godot/assets/1758504/dba4d031-c5cb-4369-8082-b482c39548fc)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/73384.

**Comment by mahdisml** [comment]
> * Related to [Vulkan Mobile: 3D rendering is black on Android (only 2D rendering is visible) #73384](https://github.com/godotengine/godot/issues/73384).
> 
> I suggest switching to the Compatibility rendering method, including for the mobile override in the Project Settings.

I tried compatibility renderer and bug also occurred again.

**Comment by mahdisml** [comment]
I tested Godot 4.2 beta 3 , it works !
problem is gone .

**Comment by Calinou** [comment]
Alright, closing then.
