### ISSUE TITLE
Calling AnimationPlayer.RootNode from C# errors in exported version

### ISSUE THREAD

**Issue by poohcom1** [godotengine/godot#82993]
### Godot version

4.2-dev6

### System information

Windows 11

### Issue description

Using the `RootNode` getter on `AnimationPlayer` from C# causes the following error in both debug and release exports.

```sh
ERROR: System.TypeInitializationException: The type initializer for 'Godot.AnimationMixer' threw an exception.
 ---> Godot.GodotObject+NativeMethodBindNotFoundException: Unable to find the native method bind. (Method 'AnimationMix)
   at Godot.GodotObject.ClassDB_get_method_with_compatibility(StringName type, StringName method, UInt64 hash)
   at Godot.AnimationMixer..cctor()
   --- End of inner exception stack trace ---
   at Godot.AnimationMixer.GetRootNode()
   at Godot.AnimationMixer.get_RootNode()
   at TestCSharp._Ready() in C:\Users\Pooh\Code\games\test-4.2dev6-animplayer\TestCSharp.cs:line 11
   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at Godot.CanvasItem.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at Godot.Node2D.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at TestCSharp.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:8
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** arg)
   at: void Godot.NativeInterop.ExceptionUtils.LogException(System.Exception) (:0)
```

The code runs fine in the editor and the same issue does not happen with GDScript.

### Steps to reproduce

**From scratch:**

1. Create a C# script that references an `AnimationPlayer`.
2. Call `AnimationPlayer.RootNode`.
3. Create a debug or release export.
4. Run the export with console.
5. The scene will show a "GDScript" label, but not the "CSharp" label because the CSharp script errored.
6. Check the console output for the error message.

**With the MRP:**

1. Create an export.
2. Run the export with console.
3. Same steps as above.

### Minimal reproduction project

[dotnet-getrootnode-mrp.zip](https://github.com/godotengine/godot/files/12840388/dotnet-getrootnode-mrp.zip)

**Comment by raulsntos** [comment]
It seems https://github.com/godotengine/godot/pull/80813 introduced methods that are only bound when running in the editor:

https://github.com/godotengine/godot/blob/6916349697a4339216469e9bf5899b983d78db07/scene/animation/animation_mixer.cpp#L2075-L2082

I think this is the same as https://github.com/godotengine/godot/issues/72864. This was fixed by moving the `#ifdef DEBUG_ENABLED` to the methods implementation (https://github.com/godotengine/godot/pull/72922) so maybe we should do something similar here.

cc @TokageItLab
