### ISSUE TITLE
HTML5 won't run after load and gives error "SharedArrayBuffer is not defined"

### ISSUE THREAD

**Issue by charliewhitfield** [godotengine/godot#83899]
### Godot version

4.2.beta2 (and earlier betas & devs)

### System information

Windows 11; Brave or Firefox browsers

### Issue description

Project works if exported as Windows exe. When exported as HTML5 and deployed on the web, it loads and then stalls with circle graphic. Throws the following 1 error & 2 warnings:

```
Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
    at planetarium-rc.js:549:38
    at planetarium-rc.js:14134:8
```

```
SharedArrayBuffer will require cross-origin isolation. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
1 source
planetarium-rc.js:544
Learn more: This change will go into effect with milestone 106.
```

```
SharedArrayBuffer usage is restricted to cross-origin isolated sites
SharedArrayBuffers (SABs) can be used to construct high-resolution timers. High-resolution timers simplify Spectre attacks on cross-origin resources.
To mitigate security risks across browsers, SharedArrayBuffers are gated behind cross-origin isolated contexts starting with Chrome 92 (July 2021). To continue using SharedArrayBuffers, please ensure that this page opts-into cross-origin isolation by setting Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy appropriately.
Note that for each iframe, only the first issue is reported for performance reasons.
1 violation
Source Location	Trigger	Status
planetarium-rc.js:544	Instantiation	warning
Learn more: Enabling SharedArrayBuffer
```

Link for the last one "Learn More": [https://developer.chrome.com/blog/enabling-shared-array-buffer/](https://developer.chrome.com/blog/enabling-shared-array-buffer/)

Error at line 549 has text "instanceof SharedArrayBuffer":
```
if (ENVIRONMENT_IS_PTHREAD) {
 wasmMemory = Module["wasmMemory"];
 buffer = Module["buffer"];
} else {
 if (Module["wasmMemory"]) {
  wasmMemory = Module["wasmMemory"];
 } else {
  wasmMemory = new WebAssembly.Memory({
   "initial": INITIAL_MEMORY / 65536,
   "maximum": 2147483648 / 65536,
   "shared": true
  });
  if (!(wasmMemory.buffer instanceof SharedArrayBuffer)) {
   err("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag");
   if (ENVIRONMENT_IS_NODE) {
    console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)");
   }
   throw Error("bad memory");
  }
 }
}
```
Error at line 14134 has text "Godot(me. ...":
```
				function doInit(promise) {
					// Care! Promise chaining is bogus with old emscripten versions.
					// This caused a regression with the Mono build (which uses an older emscripten version).
					// Make sure to test that when refactoring.
					return new Promise(function (resolve, reject) {
						promise.then(function (response) {
							const cloned = new Response(response.clone().body, { 'headers': [['content-type', 'application/wasm']] });
							Godot(me.config.getModuleConfig(loadPath, cloned)).then(function (module) {
								const paths = me.config.persistentPaths;
								module['initFS'](paths).then(function (err) {
									me.rtenv = module;
									if (me.config.unloadAfterInit) {
										Engine.unload();
									}
									resolve();
								});
							});
						});
					});
				}
```

### Steps to reproduce

Here's a link to the error-causing project on the web (it's big, sorry):

[https://www.ivoyager.dev/app-rc/planetarium-rc.html](https://www.ivoyager.dev/app-rc/planetarium-rc.html)

This project works when exported as a Windows app.

### Minimal reproduction project

See link above.

Unfortunately, I can't reproduce the error with a simple project and I don't know how to narrow the problem.

**Comment by MBCX** [comment]
Have you tried enabling the required HTTP headers in your website? More specifically:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```
These headers are a requirement, [as specified here (tip portion)](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#serving-the-files)

**Comment by MBCX** [comment]
@charliewhitfield Well, those headers I mention need to be set server side (the part that handles serving the webpage to the user). Unless you're not hosting the site yourself (and there's no way for you to modify it), then there's very little you can do about it, regardless if your app is PWA or not.

**Comment by charliewhitfield** [comment]
Solved!

My web host has an option to turn off NGINX, which I deactivated. Then I added .htaccess file with:
```
Header set Cross-Origin-Opener-Policy: same-origin
Header set Cross-Origin-Embedder-Policy: require-corp
```
I'll go ahead and close the issue as this seems to be a user error.
