### ISSUE TITLE
Failed to create C# project using .NET 8.0.0-rc.2

### ISSUE THREAD

**Issue by denovodavid** [godotengine/godot#83915]
### Godot version

v4.2.beta3.mono.official [e8d57afae]

### System information

Godot v4.2.beta3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 Threads)

### Issue description

Godot fails to create the C# project files.
Creating a new issue as per this comment: https://github.com/godotengine/godot/issues/81133#issuecomment-1778345498

`dotnet --info` output:
```
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

---

Running `Godot_v4.2-beta3_mono_win64.exe --verbose D:\Dev\godot-c-sharp-test\project.godot` and clicking `Create C# Solution` output:
```
Godot Engine v4.2.beta3.mono.official.e8d57afae - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2550378914096
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
Vulkan devices:
  #0: NVIDIA NVIDIA GeForce GTX 1060 - Supported, Discrete
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060
Optional extension VK_KHR_fragment_shading_rate not found
Optional extension VK_KHR_incremental_present not found
Optional extension VK_GOOGLE_display_timing not found
- Vulkan Variable Rate Shading not supported
- Vulkan multiview supported:
  max view count: 32
  max instances: 134217727
- Vulkan subgroup:
  size: 32
  min size: 32
  max size: 32
  stages: STAGE_VERTEX, STAGE_TESSELLATION_CONTROL, STAGE_TESSELLATION_EVALUATION, STAGE_GEOMETRY, STAGE_FRAGMENT, STAGE_COMPUTE, STAGE_RAYGEN_KHR, STAGE_ANY_HIT_KHR, STAGE_CLOSEST_HIT_KHR, STAGE_MISS_KHR, STAGE_INTERSECTION_KHR, STAGE_CALLABLE_KHR
  supported ops: FEATURE_BASIC, FEATURE_VOTE, FEATURE_ARITHMETIC, FEATURE_BALLOT, FEATURE_SHUFFLE, FEATURE_SHUFFLE_RELATIVE, FEATURE_CLUSTERED, FEATURE_QUAD, FEATURE_PARTITIONED_NV
  quad operations in all stages
Startup PSO cache (3.2 MiB)
Using "winink" pen tablet driver...
Creating VMA small objects pool for memory type index 7
Shader 'CanvasSdfShaderRD' (group 0) SHA256: a14034aa0762e5902d2a94b40503b725131176c93e03634e60fdf46091efeb47
Shader 'SkeletonShaderRD' (group 0) SHA256: 5fed378e9e80f3940283824fd6941fbc990a3b37fa61f75fee84e1f1796e0dc0
Shader 'SortShaderRD' (group 0) SHA256: cd0b067b1ed7530da074fdd5c99ffff6c5f11bb674d39ea87d48077b3d1e725a
Shader 'ParticlesShaderRD' (group 0) SHA256: a643750dfc4686d273c2cd243185090c22179f49dbb9da3b00b3b80a904f88a6
Shader 'ParticlesCopyShaderRD' (group 0) SHA256: 9e4cfc23d6ee3730c1b59ef9bf26608027dff0b7f8c34ede5630f07cb82b785d
Shader 'CanvasShaderRD' (group 0) SHA256: b620e8693c2e4b9e60fb257f851db3cf66ff9eb1e66940f890e6a06d236f79eb
Shader 'CanvasOcclusionShaderRD' (group 0) SHA256: c3c2704e82bfd9697354370ea881e16095844d441b911dc61979c35760156b8d
Shader 'ClusterRenderShaderRD' (group 0) SHA256: 9a485cbe5170bb3b3d98df08e58f19aed40f25fc9256731f96db4dc2d29f4fef
Shader 'ClusterStoreShaderRD' (group 0) SHA256: c18130ac3827edc6b1e21c98aba5a7d79f07278fc2d35fcb5f9248b923366d12
Shader 'ClusterDebugShaderRD' (group 0) SHA256: 7dd9a354be7b96bbd29cfc429c8a2b362051ea014486c652d44e40b31f1d353a
Shader 'SceneForwardClusteredShaderRD' (group 0) SHA256: 649c5dff1ac33cc478fbf3763977263c75e65fde82346880337e086969b20a87
Shader 'SceneForwardClusteredShaderRD' (group 1) SHA256: 76993a027e9be5925a773a190936f7e378dfc6b8cd8eea7e43f9178794c7a489
Shader 'SceneForwardClusteredShaderRD' (group 2) SHA256: 8fd12f96b59eba6c2527512a0b189092066a4af4b70420c3f00411303574b19a
Shader 'SceneForwardClusteredShaderRD' (group 3) SHA256: 0beb61778f34213e996aac175054aac7e0e92ce5c35d164ec12e242f994cc0af
Shader 'ResolveShaderRD' (group 0) SHA256: 58c2f55c7bbb995813d737950b17733a1d9015b570cb39ff98dbc08e99830cba
Shader 'TaaResolveShaderRD' (group 0) SHA256: 2dd7e28249697869faa3a2e6c3eed17900ac76d0efaa4b9a6b672ab6e05804fa
Shader 'Fsr2DepthClipPassShaderRD' (group 0) SHA256: 86079c81bee02e4b0bc6136cd01eef8baf2bf5eb6681ce31363a9c6301bbdc3f
Shader 'Fsr2ReconstructPreviousDepthPassShaderRD' (group 0) SHA256: 6637228e4db600de3fc65c7cda1e01303eb30fe7269c067775b0d600b65be10d
Shader 'Fsr2LockPassShaderRD' (group 0) SHA256: 028f5eb527e80205507a57d10317c28d1cedb379e7c1a888e6e48046314927aa
Shader 'Fsr2AccumulatePassShaderRD' (group 0) SHA256: e30005ff7b3359e4a31057a4c4ede3aa4011d78d04374ba9d94516a6d63d9003
Shader 'Fsr2RcasPassShaderRD' (group 0) SHA256: b06444aa4ac0c1841a520bdcc5bf272dd814507884dba4d2d32c1fbf94dce2a4
Shader 'Fsr2ComputeLuminancePyramidPassShaderRD' (group 0) SHA256: 0992744412274ae3d7953e704025b585fa4c77e16eba08c7c528abc26230901c
Shader 'Fsr2AutogenReactivePassShaderRD' (group 0) SHA256: 5137bfc2ea3be9703c96be7051206119aa37b34670688f4ca36f43634a778892
Shader 'Fsr2TcrAutogenPassShaderRD' (group 0) SHA256: b5977a4ea9a451c9102b8d5312f5d4468b4377f9bf319deae62360fb4eb28f83
Shader 'SsEffectsDownsampleShaderRD' (group 0) SHA256: 444d83c540361f72932b09ded26d114ffd353ade9ae8ca23b24bae90ea719fb4
Shader 'SsilShaderRD' (group 0) SHA256: 47ba36f8c5e29881aae9d2909a16ae622ec694d0cd9637c9591464460167c849
Shader 'SsilImportanceMapShaderRD' (group 0) SHA256: fee5a7c268c78f9f3a9ad6873e97baf77aac2da5c69a270b96debec8cd2cdfd3
Shader 'SsilBlurShaderRD' (group 0) SHA256: 19eca625967d5ced474e4b802cf7d8a4df771efca223713f282370d4844dfafc
Shader 'SsilInterleaveShaderRD' (group 0) SHA256: 8cfd43c71ebdb618f18137d40ece06e7e4baa5efbf5a7524901ae6cd8597102b
Shader 'SsaoShaderRD' (group 0) SHA256: 54e697ad64cabfddbdb6e0b98efe578fafba1db7d18532e19254dddde969fe64
Shader 'SsaoImportanceMapShaderRD' (group 0) SHA256: c11c841e157325394519fabc14b03a1d988d0907be2e5ade49b9c1eb058548d6
Shader 'SsaoBlurShaderRD' (group 0) SHA256: 526de911098506724e4ded2f41b130938eac1a41381fec1b40b3e4a3c3cd142c
Shader 'SsaoInterleaveShaderRD' (group 0) SHA256: 7f586aa7a28c2d57db13781b722d21f09608dbc737e24a526b2b57c49feabdd3
Shader 'ScreenSpaceReflectionScaleShaderRD' (group 0) SHA256: 46c27c2c657bcb8610324d0b04eb99c4c1cda6f7778ae05ac26c31c98847f187
Shader 'ScreenSpaceReflectionShaderRD' (group 0) SHA256: 09c51bb9ebd8375138c797ad728b4f4192c54a76b07049bfd01b9f47ed50a601
Shader 'ScreenSpaceReflectionFilterShaderRD' (group 0) SHA256: 2fa61fe19d17470336983f5586cca941231b5cab2fbfa426bb6413e033c8d64c
Shader 'SubsurfaceScatteringShaderRD' (group 0) SHA256: c5ea79f5fb39e1bb7d96fc0e032efc61efcaf0d4c56d5db905acf3d17875f565
Shader 'SkyShaderRD' (group 0) SHA256: 87a170f35cc56934fb408d0769fbaa33b3079a3f0ef27114edf016a5e45819ea
Shader 'VoxelGiShaderRD' (group 0) SHA256: 62ee1159efbfdf46efa8035a0d2cc73170f124b9868039ee36b49b864f04e2b1
Shader 'VoxelGiDebugShaderRD' (group 0) SHA256: 6da53a6d105431e954a90455cdac213c13328e0f6fdea0a720da34385e12964c
Shader 'SdfgiPreprocessShaderRD' (group 0) SHA256: 2fa72684dd22e28c090624653d604c398fa78a3638b5869ebeb25a85a74ef621
Shader 'SdfgiDirectLightShaderRD' (group 0) SHA256: ba15720a8a110616ab1a0681f9d53a1ec0c9175086a846de33823088cee7cbdb
Shader 'SdfgiIntegrateShaderRD' (group 0) SHA256: 47401525f9bc16d2aa34f3bd3e38d825f8c65389b54de030f2160333f73cf55c
Shader 'GiShaderRD' (group 0) SHA256: fb016ff6eac4496fecb63b86f191c7effbd0bb03d26845ed4c8c5652d77bd72e
Shader 'SdfgiDebugShaderRD' (group 0) SHA256: dcb730c4449831656a19834040bd41f1104904aa264aa46ff688bfb81f386d69
Shader 'SdfgiDebugProbesShaderRD' (group 0) SHA256: 77010cf9beec7b735048de9a89de6bda517b6291b6d6634b4ae93fcc65534f8e
Shader 'VolumetricFogShaderRD' (group 0) SHA256: a29924511b8914c33bc16b5e8eda2c86ed3a1401004440ed53e00f9c9cb49980
Shader 'VolumetricFogProcessShaderRD' (group 0) SHA256: 05a2288d69e718687c68af14185313af4119d5c6578c58d221fa0bf529c528a3
Shader 'BokehDofShaderRD' (group 0) SHA256: 846f56021bfdbd7d36b490eb6dcae9d01c55084fa244a9c1c61c6efc87fb7b52
Shader 'CopyShaderRD' (group 0) SHA256: 6575c32b19343de03fd5aa6a0c43b83fa00d8d1d4935daab0185d4b5dda6d000
Shader 'CopyToFbShaderRD' (group 0) SHA256: 3e82d8c01daef050ac7e9424ab0d73ed5999860a72a78f3c964342336ad0a71a
Shader 'CubeToDpShaderRD' (group 0) SHA256: c61546ead340f5dbbe971ae63dc6a7a7c0a5d247acadb8c29d4524041b204dcb
Shader 'CubemapDownsamplerShaderRD' (group 0) SHA256: fabfaeea824a8fbb279bcc34c93da173cc0512a870d66e9b4faace40aaa424bb
Shader 'CubemapFilterShaderRD' (group 0) SHA256: 434bc88ad35f0a23c8d7467333eb6a1bb1ea865ede22c5208c416b930ed7f22f
Shader 'CubemapRoughnessShaderRD' (group 0) SHA256: d7263454c1567e2c241fc53104b44cd4209b93ba94f9238232273e02c4550618
Shader 'SpecularMergeShaderRD' (group 0) SHA256: 28d5bde43ee6fadbd5ff81b1bce467e19de763297ef8c84a3834b6d343b35007
Shader 'ShadowFrustumShaderRD' (group 0) SHA256: dbad0299b18079b7b3a87f76c4a42969f6a6657426240e139e27f66911dbac73
Shader 'MotionVectorsShaderRD' (group 0) SHA256: 3fe17ea881fa9b224c5ac0f6a94a76e5da67ae5fef949524cea2231cdca7a624
Shader 'LuminanceReduceShaderRD' (group 0) SHA256: c57f6263e421dbe39f210a235eaf80b9289c3e15584ec8cdfb0bd3b6890eba11
Shader 'TonemapShaderRD' (group 0) SHA256: 48bf63cf6345735422d47d6f48079f445303e0065698df3bd68c0a978dd2bd58
Shader 'FsrUpscaleShaderRD' (group 0) SHA256: ebabed9013c59d0fa784f57c89dfc133a8d0b059183c08a954fee64ab09d02d3
Shader 'BlitShaderRD' (group 0) SHA256: 564957557b75d4e55a74ef7a5daab50ec2642e14a39de5a2e0e94ce791aabb23
WASAPI: Activated output_device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 44100
WASAPI: nAvgBytesPerSec = 352800
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 44100
WASAPI: fundamental_period_frames = 1
WASAPI: min_period_frames = 309
WASAPI: max_period_frames = 441
WASAPI: selected a period frame size of 441
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 441 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
.NET: Initializing module...
Found hostfxr: C:\Program Files\dotnet\host/fxr/8.0.0-rc.2.23479.6/hostfxr.dll
.NET: hostfxr initialized
.NET: GodotPlugins initialized
.NET: Failed to load project assembly
CORE API HASH: 3379163053
EDITOR API HASH: 550358033
EditorSettings: Load OK!
Found .NET Sdk version '8.0.100': C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\
Loaded system CA certificates
Creating VMA small objects pool for memory type index 9
EditorSettings: Save OK!
ERROR: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at GodotTools.ProjectEditor.ProjectGenerator.GenAndSaveGameProject(String dir, String name)
   at GodotTools.CsProjOperations.GenerateGameProject(String dir, String name) in /root/godot/modules/mono/editor/GodotTools/GodotTools/CsProjOperations.cs:line 13
   at: string GodotTools.CsProjOperations.GenerateGameProject(string, string) (/root/godot/modules/mono/editor/GodotTools/GodotTools/CsProjOperations.cs:13)
```

### Steps to reproduce

1. Install Godot 4.2 beta 3 "mono"
2. Install .NET SDK 8.0.0-rc.2
3. Create new Godot project
4. Click `Project -> Tools -> C# -> Create C# Solution` (or create a new C# script)
5. "Failed to create C# project."

### Minimal reproduction project

N/A

**Comment by FyiurAmron** [comment]
FWIW, just setting the TargetFramework to net8.0 causes a very similar problem in the end even if you have different .NET versions available, https://github.com/godotengine/godot/issues/81133#issuecomment-1747491280 - I'd assume these are somehow related.

**Comment by raulsntos** [comment]
@denovodavid Can you try setting the environment variable`DOTNET_ROLL_FORWARD_TO_PRERELEASE` to `1`? I suspect, the roll-forward policy ignores pre-releases so it ends up loading the latest installed runtime (which in your case would be 7.0.10).

@FyiurAmron Setting the `<TargetFramework>` could be a different issue, and you need to make sure that the hostfxr version matches, otherwise the editor can't load your project assembly.
Assuming that Godot finds an SDK compatible with your project TFM[^1], then it _could_ be the same issue. In that case, setting the environment variable `DOTNET_ROLL_FORWARD_TO_PRERELEASE` as described above could also work.

[^1]: To check this you would have to look at the output of `dotnet --info` and `godot --verbose`.

**Comment by denovodavid** [comment]
> @denovodavid Can you try setting the environment variable `DOTNET_ROLL_FORWARD_TO_PRERELEASE` to `1`? I suspect, the roll-forward policy ignores pre-releases so it ends up loading the latest installed runtime (which in your case would be 7.0.10).

It works! Setting `DOTNET_ROLL_FORWARD_TO_PRERELEASE` to `1` fixed the issue. I can create the project files, scripts, and run the game printing "Hello from C#!"

I imagine this won't be an issue come stable .NET 8 release, but maybe good to document somewhere for those without any other .NET version.

Here are the successfully generated solutions files:

godot-csharp-test.csproj
```xml
<Project Sdk="Godot.NET.Sdk/4.2.0-beta.3">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net7.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'ios' ">net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>godotcsharptest</RootNamespace>
  </PropertyGroup>
</Project>
```

godot-csharp-test.sln
```sln
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2012
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "godot-csharp-test", "godot-csharp-test.csproj", "{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
	Debug|Any CPU = Debug|Any CPU
	ExportDebug|Any CPU = ExportDebug|Any CPU
	ExportRelease|Any CPU = ExportRelease|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}.ExportDebug|Any CPU.ActiveCfg = ExportDebug|Any CPU
		{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}.ExportDebug|Any CPU.Build.0 = ExportDebug|Any CPU
		{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}.ExportRelease|Any CPU.ActiveCfg = ExportRelease|Any CPU
		{8842ABCF-019E-4AF0-A12B-194B0ADCDCF3}.ExportRelease|Any CPU.Build.0 = ExportRelease|Any CPU
	EndGlobalSection
EndGlobal
```

**Comment by FyiurAmron** [comment]
@denovodavid I agree this could/should be documented... because it seems that in 12 months with .NET 9 prereleases this will re-appear etc. :)

**Comment by FyiurAmron** [comment]
@raulsntos 
`DOTNET_ROLL_FORWARD_TO_PRERELEASE` works like a charm, thanks for figuring this out!

BTW, do you maybe know what's up with the example code? The line `GD.Log(OS.getCurrentRenderingDriverName());` from example code causes

>CS0117: 'GD' does not contain a definition for 'Log' C:\Codes\Godot\_Projects\TestX\root.cs(10,6)
>CS0117: 'OS' does not contain a definition for 'getCurrentRenderingDriverName' C:\Codes\Godot\_Projects\TestX\root.cs(10,13)

(it does have `using Godot;` BTW)
