### ISSUE TITLE
Executing `TextServerAdvanced.create_font` function leaks memory in Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#84693]
### Godot version

4.2.beta.custom_build. 9df649185

### System information

Ubuntu 22.04 CI

### Issue description

When executing (this code was automatically minimized, so it is possible, that an even more "minimal" project can be created)
```
extends Node
func _process(delta):
	var temp_variable1829 = TextServerAdvanced.new()
	temp_variable1829.create_font()
```
Godot leaks memory:
```
Godot Engine v4.2.beta.custom_build.9df649185 - https://godotengine.org
WARNING: The Multi-Threaded rendering thread model is experimental, and has known issues which can lead to project crashes. Use the Single-Safe option in the project settings instead.
     at: setup2 (main/main.cpp:2423)
WARNING: Rendering thread not supported by this display server.
     at: release_rendering_thread (servers/display_server.cpp:561)
WARNING: Rendering thread not supported by this display server.
     at: make_rendering_thread (servers/display_server.cpp:565)
Time set to: 0 seconds.
Loaded settings:
modules/gdscript/gdscript_vm.cpp:698:13: runtime error: store to misaligned address 0x62100012df5c for type '<unknown> *', which requires 8 byte alignment
0x62100012df5c: note: pointer points here
  04 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  15 00 00 00 10 00 00 01  14 00 00 00 06 00 00 00
              ^ 
'number_of_function_repeats' with value '6'
modules/gdscript/gdscript_vm.cpp:705:42: runtime error: load of misaligned address 0x62100012df5c for type '<unknown> *', which requires 8 byte alignment
0x62100012df5c: note: pointer points here
  04 00 00 00 05 e5 3d b4  4b 56 00 00 00 00 00 00  15 00 00 00 10 00 00 01  14 00 00 00 06 00 00 00
              ^ 
'use_parent_methods' with value 'true'
'maximum_executed_functions_on_object' with value '15'
######################## Ending test ########################
ERROR: 1 RID allocations of type 'PN18TextServerAdvanced12FontAdvancedE' were leaked at exit.
=================================================================
==20334==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 448 byte(s) in 1 object(s) allocated from:
    #0 0x7fec7e2b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564bb2e9b207 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x564bb2e9b118 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x564ba0165f2d in TextServerAdvanced::_create_font() modules/text_server_adv/text_server_adv.cpp:1835
    #4 0x564ba02442b9 in TextServerAdvanced::create_font() modules/text_server_adv/text_server_adv.h:719
    #5 0x564baa44ef92 in void call_with_variant_args_ret_helper<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:755
    #6 0x564baa43fc4c in void call_with_variant_args_ret_dv<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #7 0x564baa432bb3 in MethodBindTR<RID>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #8 0x564bb47ebca0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:775
    #9 0x564bb3ba01ce in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #10 0x564b9b4ea45d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #11 0x564b9ade40b4 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #12 0x564ba85aaad0 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #13 0x564ba84e92c0 in Node::_notification(int) scene/main/node.cpp:57
    #14 0x564b9a8f4863 in Node::_notificationv(int, bool) scene/main/node.h:49
    #15 0x564bb47ed82a in Object::notification(int, bool) core/object/object.cpp:837
    #16 0x564ba86a8c92 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #17 0x564ba86abf36 in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #18 0x564ba869a02c in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #19 0x564b99f322f1 in Main::iteration() main/main.cpp:3636
    #20 0x564b99c4a225 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #21 0x564b99c28757 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #22 0x7fec7d629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fec7e2b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564bb2e9b207 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x564bb2e9b118 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x564bb3b0b9da in Dictionary::Dictionary() core/variant/dictionary.cpp:391
    #4 0x564ba0282287 in TextServerAdvanced::FontAdvanced::FontAdvanced() modules/text_server_adv/text_server_adv.h:302
    #5 0x564ba0165f5d in TextServerAdvanced::_create_font() modules/text_server_adv/text_server_adv.cpp:1835
    #6 0x564ba02442b9 in TextServerAdvanced::create_font() modules/text_server_adv/text_server_adv.h:719
    #7 0x564baa44ef92 in void call_with_variant_args_ret_helper<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:755
    #8 0x564baa43fc4c in void call_with_variant_args_ret_dv<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #9 0x564baa432bb3 in MethodBindTR<RID>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #10 0x564bb47ebca0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:775
    #11 0x564bb3ba01ce in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #12 0x564b9b4ea45d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #13 0x564b9ade40b4 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #14 0x564ba85aaad0 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #15 0x564ba84e92c0 in Node::_notification(int) scene/main/node.cpp:57
    #16 0x564b9a8f4863 in Node::_notificationv(int, bool) scene/main/node.h:49
    #17 0x564bb47ed82a in Object::notification(int, bool) core/object/object.cpp:837
    #18 0x564ba86a8c92 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #19 0x564ba86abf36 in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #20 0x564ba869a02c in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #21 0x564b99f322f1 in Main::iteration() main/main.cpp:3636
    #22 0x564b99c4a225 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #23 0x564b99c28757 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #24 0x7fec7d629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fec7e2b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564bb2e9b207 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x564bb2e9b118 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x564bb3b0b9da in Dictionary::Dictionary() core/variant/dictionary.cpp:391
    #4 0x564ba0282310 in TextServerAdvanced::FontAdvanced::FontAdvanced() modules/text_server_adv/text_server_adv.h:302
    #5 0x564ba0165f5d in TextServerAdvanced::_create_font() modules/text_server_adv/text_server_adv.cpp:1835
    #6 0x564ba02442b9 in TextServerAdvanced::create_font() modules/text_server_adv/text_server_adv.h:719
    #7 0x564baa44ef92 in void call_with_variant_args_ret_helper<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:755
    #8 0x564baa43fc4c in void call_with_variant_args_ret_dv<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #9 0x564baa432bb3 in MethodBindTR<RID>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #10 0x564bb47ebca0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:775
    #11 0x564bb3ba01ce in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #12 0x564b9b4ea45d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #13 0x564b9ade40b4 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #14 0x564ba85aaad0 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #15 0x564ba84e92c0 in Node::_notification(int) scene/main/node.cpp:57
    #16 0x564b9a8f4863 in Node::_notificationv(int, bool) scene/main/node.h:49
    #17 0x564bb47ed82a in Object::notification(int, bool) core/object/object.cpp:837
    #18 0x564ba86a8c92 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #19 0x564ba86abf36 in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #20 0x564ba869a02c in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #21 0x564b99f322f1 in Main::iteration() main/main.cpp:3636
    #22 0x564b99c4a225 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #23 0x564b99c28757 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #24 0x7fec7d629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fec7e2b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564bb2e9b207 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x564bb2e9b118 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x564bb3b0b9da in Dictionary::Dictionary() core/variant/dictionary.cpp:391
    #4 0x564ba02821fe in TextServerAdvanced::FontAdvanced::FontAdvanced() modules/text_server_adv/text_server_adv.h:302
    #5 0x564ba0165f5d in TextServerAdvanced::_create_font() modules/text_server_adv/text_server_adv.cpp:1835
    #6 0x564ba02442b9 in TextServerAdvanced::create_font() modules/text_server_adv/text_server_adv.h:719
    #7 0x564baa44ef92 in void call_with_variant_args_ret_helper<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:755
    #8 0x564baa43fc4c in void call_with_variant_args_ret_dv<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #9 0x564baa432bb3 in MethodBindTR<RID>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #10 0x564bb47ebca0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:775
    #11 0x564bb3ba01ce in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #12 0x564b9b4ea45d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #13 0x564b9ade40b4 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #14 0x564ba85aaad0 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #15 0x564ba84e92c0 in Node::_notification(int) scene/main/node.cpp:57
    #16 0x564b9a8f4863 in Node::_notificationv(int, bool) scene/main/node.h:49
    #17 0x564bb47ed82a in Object::notification(int, bool) core/object/object.cpp:837
    #18 0x564ba86a8c92 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #19 0x564ba86abf36 in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #20 0x564ba869a02c in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #21 0x564b99f322f1 in Main::iteration() main/main.cpp:3636
    #22 0x564b99c4a225 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #23 0x564b99c28757 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #24 0x7fec7d629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fec7e2b4887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564bb2e9b207 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x564bb2e9b118 in operator new(unsigned long, char const*) core/os/memory.cpp:40
    #3 0x564bb3b0b9da in Dictionary::Dictionary() core/variant/dictionary.cpp:391
    #4 0x564ba028194f in TextServerAdvanced::FontAdvanced::FontAdvanced() modules/text_server_adv/text_server_adv.h:302
    #5 0x564ba0165f5d in TextServerAdvanced::_create_font() modules/text_server_adv/text_server_adv.cpp:1835
    #6 0x564ba02442b9 in TextServerAdvanced::create_font() modules/text_server_adv/text_server_adv.h:719
    #7 0x564baa44ef92 in void call_with_variant_args_ret_helper<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, Variant&, Callable::CallError&, IndexSequence<>) core/variant/binder_common.h:755
    #8 0x564baa43fc4c in void call_with_variant_args_ret_dv<__UnexistingClass, RID>(__UnexistingClass*, RID (__UnexistingClass::*)(), Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) core/variant/binder_common.h:534
    #9 0x564baa432bb3 in MethodBindTR<RID>::call(Object*, Variant const**, int, Callable::CallError&) const core/object/method_bind.h:496
    #10 0x564bb47ebca0 in Object::callp(StringName const&, Variant const**, int, Callable::CallError&) core/object/object.cpp:775
    #11 0x564bb3ba01ce in Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) core/variant/variant_call.cpp:1168
    #12 0x564b9b4ea45d in GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) modules/gdscript/gdscript_vm.cpp:1704
    #13 0x564b9ade40b4 in GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) modules/gdscript/gdscript.cpp:1896
    #14 0x564ba85aaad0 in bool Node::_gdvirtual__process_call<false>(double) scene/main/node.h:318
    #15 0x564ba84e92c0 in Node::_notification(int) scene/main/node.cpp:57
    #16 0x564b9a8f4863 in Node::_notificationv(int, bool) scene/main/node.h:49
    #17 0x564bb47ed82a in Object::notification(int, bool) core/object/object.cpp:837
    #18 0x564ba86a8c92 in SceneTree::_process_group(SceneTree::ProcessGroup*, bool) scene/main/scene_tree.cpp:951
    #19 0x564ba86abf36 in SceneTree::_process(bool) scene/main/scene_tree.cpp:1028
    #20 0x564ba869a02c in SceneTree::process(double) scene/main/scene_tree.cpp:508
    #21 0x564b99f322f1 in Main::iteration() main/main.cpp:3636
    #22 0x564b99c4a225 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:933
    #23 0x564b99c28757 in main platform/linuxbsd/godot_linuxbsd.cpp:74
    #24 0x7fec7d629d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
SUMMARY: AddressSanitizer: 768 byte(s) leaked in 5 allocation(s).
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visible when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

   

### Steps to reproduce

Above

### Minimal reproduction project

Above

**Comment by bruvzg** [comment]
Not sure if it's a bug, RIDs (`create_font()` return RID) are expected to be freed manually, and none of the `RID_PtrOwner` users (physics, texture storage, text server) seems to clear owned RIDs on exit.
