### ISSUE TITLE
`CodeEdit.duplicate_lines` freeze Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#84742]
### Godot version

4.2.beta.custom_build. 2b987d1c5

### System information

Ubuntu 22.04 CI

### Issue description

When executing (this code was automatically minimized, so it is possible, that an even more "minimal" project can be created)
```
extends Node
func _process(delta):
	var temp_variable385 = CodeEdit.new()
	add_child(temp_variable385)
	temp_variable385.set_fit_content_height_enabled(true)
	temp_variable385.duplicate_lines()
	temp_variable385.set_scroll_past_end_of_file_enabled(true)
	temp_variable385.duplicate_lines()
	temp_variable385.queue_free()
```
Godot freeze:
```
Godot Engine v4.2.beta.custom_build.2b987d1c5 - https://godotengine.org
Vulkan API 1.2.0 - Forward+ - Using Vulkan Device #0: Unknown - SwiftShader Device (LLVM 10.0.0)
0x00000000057f440e in Vector<TextEdit::Text::Line>::size (this=0xe46a1b8) at ./core/templates/vector.h:93
Downloading source file /home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/vector.h
93      ./core/templates/vector.h: No such file or directory.                                                                                                                                                                       
(gdb) backtrace
#0  0x00000000057f440e in Vector<TextEdit::Text::Line>::size (this=0xe46a1b8) at ./core/templates/vector.h:93
#1  0x00000000057f24d2 in TextEdit::Text::size (this=0xe46a1b0) at scene/gui/text_edit.h:224
#2  0x00000000057b22ab in TextEdit::_notification (this=0xe469850, p_what=30) at scene/gui/text_edit.cpp:900
#3  0x00000000054f3570 in TextEdit::_notificationv (this=0xe469850, p_notification=30, p_reversed=false) at ./scene/gui/text_edit.h:42
#4  0x00000000054f3edf in CodeEdit::_notificationv (this=0xe469850, p_notification=30, p_reversed=false) at scene/gui/code_edit.h:38
#5  0x00000000075f3b06 in Object::notification (this=0xe469850, p_notification=30, p_reversed=false) at core/object/object.cpp:836
#6  0x000000000530c2bb in CanvasItem::_redraw_callback (this=0xe469850) at scene/main/canvas_item.cpp:140
#7  0x00000000042f3266 in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0xe469850, 
    p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x530c220 <CanvasItem::_redraw_callback()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:303
#8  0x00000000042f036f in call_with_variant_args<CanvasItem> (p_instance=0xe469850, p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x530c220 <CanvasItem::_redraw_callback()>, p_args=0x0, p_argcount=0, r_error=...)
    at ./core/variant/binder_common.h:417
#9  0x00000000042eb740 in CallableCustomMethodPointer<CanvasItem>::call (this=0x1086c0e0, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#10 0x000000000726611a in Callable::callp (this=0x106a7b70, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:57
#11 0x00000000075ec016 in CallQueue::_call_function (this=0xb9b0a30, p_callable=..., p_args=0x106a7b88, p_argcount=0, p_show_error=false) at core/object/message_queue.cpp:219
#12 0x00000000075ec7f3 in CallQueue::flush (this=0xb9b0a30) at core/object/message_queue.cpp:324
#13 0x00000000053c5f2f in SceneTree::process (this=0xe261d20, p_time=0.14655200000000002) at scene/main/scene_tree.cpp:511
#14 0x0000000002a321e1 in Main::iteration () at main/main.cpp:3613
#15 0x00000000029a01ec in OS_LinuxBSD::run (this=0x7fffffffcf20) at platform/linuxbsd/os_linuxbsd.cpp:933
#16 0x0000000002998365 in main (argc=2, argv=0x7fffffffd4e8) at platform/linuxbsd/godot_linuxbsd.cpp:74



back0x0000000002f62f4f in Vector<Vector2>::push_back (this=0x7fffffffc2c0, p_elem=...) at ./core/templates/vector.h:317
317     ./core/templates/vector.h: No such file or directory.                                                                                                                                                                       
(gdb) backtrace
#0  0x0000000002f62f4f in Vector<Vector2>::push_back (this=0x7fffffffc2c0, p_elem=...) at ./core/templates/vector.h:317
#1  0x00000000061a575f in draw_rounded_rectangle (verts=..., indices=..., colors=..., style_rect=..., corner_radius=0x7fffffffc370, ring_rect=..., inner_rect=..., inner_color=..., outer_color=..., corner_detail=5, skew=..., 
    is_filled=true) at scene/resources/style_box_flat.cpp:305
#2  0x00000000061a08f6 in StyleBoxFlat::draw (this=0xe20b970, p_canvas_item=..., p_rect=...) at scene/resources/style_box_flat.cpp:499
#3  0x00000000057b00be in TextEdit::_notification (this=0xe469850, p_what=30) at scene/gui/text_edit.cpp:530
#4  0x00000000054f3570 in TextEdit::_notificationv (this=0xe469850, p_notification=30, p_reversed=false) at ./scene/gui/text_edit.h:42
#5  0x00000000054f3edf in CodeEdit::_notificationv (this=0xe469850, p_notification=30, p_reversed=false) at scene/gui/code_edit.h:38
#6  0x00000000075f3b06 in Object::notification (this=0xe469850, p_notification=30, p_reversed=false) at core/object/object.cpp:836
#7  0x000000000530c2bb in CanvasItem::_redraw_callback (this=0xe469850) at scene/main/canvas_item.cpp:140
#8  0x00000000042f3266 in call_with_variant_args_helper<CanvasItem>(CanvasItem*, void (CanvasItem::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (p_instance=0xe469850, 
    p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x530c220 <CanvasItem::_redraw_callback()>, p_args=0x0, r_error=...) at ./core/variant/binder_common.h:303
#9  0x00000000042f036f in call_with_variant_args<CanvasItem> (p_instance=0xe469850, p_method=(void (CanvasItem::*)(CanvasItem * const)) 0x530c220 <CanvasItem::_redraw_callback()>, p_args=0x0, p_argcount=0, r_error=...)
    at ./core/variant/binder_common.h:417
#10 0x00000000042eb740 in CallableCustomMethodPointer<CanvasItem>::call (this=0x1180b2e0, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at ./core/object/callable_method_pointer.h:104
#11 0x000000000726611a in Callable::callp (this=0x11729ed0, p_arguments=0x0, p_argcount=0, r_return_value=..., r_call_error=...) at core/variant/callable.cpp:57
#12 0x00000000075ec016 in CallQueue::_call_function (this=0xb9b0a30, p_callable=..., p_args=0x11729ee8, p_argcount=0, p_show_error=false) at core/object/message_queue.cpp:219
#13 0x00000000075ec7f3 in CallQueue::flush (this=0xb9b0a30) at core/object/message_queue.cpp:324
#14 0x00000000053c5f2f in SceneTree::process (this=0xe261d20, p_time=0.14655200000000002) at scene/main/scene_tree.cpp:511
#15 0x0000000002a321e1 in Main::iteration () at main/main.cpp:3613
#16 0x00000000029a01ec in OS_LinuxBSD::run (this=0x7fffffffcf20) at platform/linuxbsd/os_linuxbsd.cpp:933

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visible when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

   

### Steps to reproduce

Above

### Minimal reproduction project

Above

**Comment by TheSofox** [comment]
Confirmed.

Tentatively looking into it, it's something about the size that's causing an infinite loop in `message_queue.cpp`.

`Control::_update_minimum_size()` and `Control::_size_changed()` are called over and over again, and `data.size_cache` and `data.last_minimum_size` are updated over and over again with bigger and bigger values.

**Comment by kitbdev** [comment]
This can happen even in the editor when enabling fit_content_height and scroll_past_end_of_file_enabled on a TextEdit.
