### ISSUE TITLE
"Godot quit unexpectedly" crash on macos when C# thread references uninitialised variable

### ISSUE THREAD

**Issue by klajo** [godotengine/godot#84988]
### Godot version

v4.1.3.stable.mono.official [f06b6836a]

### System information

Godot v4.1.3.stable.mono - macOS 14.1.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When referencing an uninitialised variable from eg. the _Ready() method from C# on MacOS the following error message is printed to the console (as expected):

```
E 0:00:00:0447   Main.cs:14 @ void Main._Ready(): System.NullReferenceException: Object reference not set to an instance of an object.
  <C# Error>     System.NullReferenceException
  <C# Source>    Main.cs:14 @ void Main._Ready()
  <Stack Trace>  Main.cs:14 @ void Main._Ready()
...
```

When the same call is done from inside a Thread() the app crashes and MacOS shows the "Godot quit unexpectedly" dialog for a report to be sent to Apple.

Running the same project on Windows prints an error message similar to the one above to the console, which is what I would have expected:

```
E 0:00:01:0006   Main.cs:15 @ void Main.<_Ready>b__1_0(): System.NullReferenceException: Object reference not set to an instance of an object.
<C# Error>     System.NullReferenceException
<C# Source>    Main.cs:15 @ void Main.<_Ready>b__1_0()
<Stack Trace>  Main.cs:15 @ void Main.<_Ready>b__1_0()
                 :0 @ void System.Threading.Thread.StartCallback()
...
```

### Steps to reproduce

Here's a small example to reproduce (example project attached):

```csharp
using Godot;
using System;
using System.Threading;

public partial class Main : Node3D
{
    // Node foo = new();
    Node foo;
    
    public override void _Ready()
    {
        // should generate:
        // Main.cs:<line> @ void Main._Ready(): System.NullReferenceException: Object reference not set to an instance of an object.
        // GD.Print("outside thread" + foo.GetChildren());
        Thread t = new Thread(() => GD.Print("within thread: " + foo.GetChildren()));
        t.Start();
    }

}
```

### Minimal reproduction project

[thread-crash.zip](https://github.com/godotengine/godot/files/13382980/thread-crash.zip)

**Comment by raulsntos** [comment]
I think it's expected behavior that .NET applications abort on unhandled exceptions. Are you saying MacOS doesn't print the exception message to the console before aborting? I'm not sure if this is intended.

Either way, this sounds like it's on the .NET side and not something Godot can do anything about.

**Comment by klajo** [comment]
The following happens:

On MacOS:
- in _Ready(): NullReferenceException error message is shown in the editor
- in Thread() inside _Ready(): nothing is printed, MacOS crash handler takes over

On Windows:
- in _Ready(): NullReferenceException error message is shown in the editor
- in Thread() inside _Ready(): NullReferenceException error message is shown in the editor

Note the difference in the threaded case on MacOS.

I should perhaps add that this is when I'm running the example from within the godot editor (haven't tested this specific example as a standalone, built, app).

**Comment by klajo** [comment]
FYI I'm still seeing this in these versions:

- v4.2.2.stable.mono.official [15073afe3]
- v4.3.beta1.official [a4f2ea91a]

**Comment by raulsntos** [comment]
Can you reproduce in a console application?

**Comment by klajo** [comment]
Do you mean something that runs from the terminal, headless?

Here's when exporting the project on MacOS, for MacOS and starting it with the GUI:

```
➜  build csharp-crash-test.app/Contents/MacOS/csharp-crash-test       
Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: Apple - Apple M1 Pro
 
ERROR: Unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Main.<_Ready>b__1_0() in .../src/godot/csharp-crash-test/Main.cs:line 15
   at System.Threading.Thread.StartCallback()
   at: void Godot.NativeInterop.ExceptionUtils.LogUnhandledException(System.Exception) (:0)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Main.<_Ready>b__1_0() in .../src/godot/csharp-crash-test/Main.cs:line 15
   at System.Threading.Thread.StartCallback()
[1]    13933 abort      csharp-crash-test.app/Contents/MacOS/csharp-crash-test
```
(and I get the MacOS crash reporter)


Here's when running the same app, but headless:
```
➜  build csharp-crash-test.app/Contents/MacOS/csharp-crash-test --headless
Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
 
ERROR: Unhandled exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Main.<_Ready>b__1_0() in .../src/godot/csharp-crash-test/Main.cs:line 15
   at System.Threading.Thread.StartCallback()
   at: void Godot.NativeInterop.ExceptionUtils.LogUnhandledException(System.Exception) (:0)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Main.<_Ready>b__1_0() in .../src/godot/csharp-crash-test/Main.cs:line 15
   at System.Threading.Thread.StartCallback()
[1]    21147 abort      csharp-crash-test.app/Contents/MacOS/csharp-crash-test --headless
```

(and I get the MacOS crash reporter)


Both of these give me more information on the crash, than when I run this from within the editor.

This is what it looks like from within the editor (i.e. it doesn't show anything about the error):

<img width="583" alt="image" src="https://github.com/godotengine/godot/assets/150513/4e11863a-2073-4aaf-a1d1-7f9197a1d79c">

**Comment by raulsntos** [comment]
I meant a [.NET console application](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/console-teleprompter) without Godot, but it looks like the terminal displays the exception so the issue may be in Godot's logger. Maybe the macOS crash handler takes over before Godot has a chance to update the GUI.

**Comment by klajo** [comment]
Got it.

Here's a snippet:

```
public class Foo
{
    Object? foo;

    public void Ready()
    {
        Thread t = new Thread(() => Console.WriteLine("within thread: " + foo.ToString()));
        t.Start();
    }
}

internal class Program
{
    static void Main(string[] args)
    {
        var foo = new Foo();
        foo.Ready();
    }
}
```

Which yields:

```
➜ dotnet run
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Foo.<Ready>b__1_0() in /private/tmp/foo/Program.cs:line 7
   at System.Threading.Thread.StartCallback()
```
