### ISSUE TITLE
"Stopped Working" when opening the editor at all.

### ISSUE THREAD

**Issue by NancokPS2** [godotengine/godot#85584]
### Godot version

4.2 stable mono win64

### System information

Windows 10 x64 - Godot v4.2 - OpenGL (Compatibility) - dedicated. GPU: FirePro v4900. CPU: AMD Phenom II X6

### Issue description
Be it by opening an old project, one from 4.1 or even creating a new one, it just crashes before the editor ever loads. (Running in Compatibility mode)    
  
Godot 4.1.2 is working just fine

Error log:  
```
Godot Engine v4.2.stable.mono.official.46dc27791 - https://godotengine.org
OpenGL API 3.3.13397 Core Profile Forward-Compatible Context FireGL 15.200.1045.0 - Compatibility - Using Device: ATI Technologies Inc. - AMD FirePro V4900 (FireGL V) Graphics Adapter

ERROR: Mono Cache: Managed callback for 'GD_OnCoreApiAssemblyLoaded' is null.
   at: (modules/mono/mono_gd/gd_mono_cache.cpp:86)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Unmanaged callbacks size mismatch. (Parameter 'unmanagedCallbacksSize')
   at GodotTools.Internals.Internal.Initialize(IntPtr unmanagedCallbacks, Int32 unmanagedCallbacksSize) in /root/godot/modules/mono/editor/GodotTools/GodotTools/Internals/Internal.cs:line 81
   at GodotTools.GodotSharpEditor.InternalCreateInstance(IntPtr unmanagedCallbacks, Int32 unmanagedCallbacksSize) in /root/godot/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:line 661
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GodotPlugins.Main.LoadToolsAssembly(Char* nAssemblyPath, IntPtr unmanagedCallbacks, Int32 unmanagedCallbacksSize) in /root/godot/modules/mono/glue/GodotSharp/GodotPlugins/Main.cs:line 190
ERROR: FATAL: Condition "editor_plugin_obj == nullptr" is true.
   at: _editor_init_callback (modules/mono/csharp_script.cpp:1202)

```

### Steps to reproduce

Try to create/open a project.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Are you using godot-jolt by any chance? If so you need to upgrade it or remove it to open in 4.2, the old version is not compatible and crashes.

**Comment by NancokPS2** [comment]
I couldn't tell you, the editor never opens.

**Comment by NancokPS2** [comment]
No, even new projects refuse to open.  
I also deleted my settings file to make sure it wasn't that.

**Comment by NancokPS2** [comment]
I forgor to copy over the GodotSharp folder from the .zip for some reason.  
Solved.
