### ISSUE TITLE
dotnet cant build on arm64

### ISSUE THREAD

**Issue by bodonkerhoderos** [godotengine/godot#85769]
### Tested versions

4.2

### System information

Godot v4.2.stable.mono - Manjaro ARM #1 SMP PREEMPT Sun Oct 15 18:48:13 UTC 2023 - Wayland - GLES3 (Compatibility) - Mali-T860 (Panfrost) -  (6 Threads)

### Issue description

When attempting to build a dotnet godot project on arm64 it errors with the following:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.ThreadPoolWorkQueue.GetOrCreateThreadLocals()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(System.Threading.PortableThreadPool, Boolean ByRef)
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

output of `dotnet --info`:
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     manjaro-arm
 OS Version:  
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

### Steps to reproduce

on arm64 device create a new project. create c# solution. attempt to build.

### Minimal reproduction project (MRP)

a blank project

**Comment by bruvzg** [comment]
I can't reproduce with current master and dotnet 7.0.113, tested on Fedora 39 in ARM64 VM on M1 Mac.

**Comment by bruvzg** [comment]
But it is reproducible with dotnet 8.0.0 manually installed via `https://dot.net/v1/dotnet-install.sh`.

**Comment by akien-mga** [comment]
If it works with .NET 7.0 but not .NET 8.0, this is possibly an upstream bug where they'd have regressed in their Linux arm64 support.

I remember testing it a few weeks ago on a Linux environment on an arm64 Chromebook and I also got .NET working fine with Godot 4.2-beta. I tested with .NET 6.0 from the Microsoft generic tarball. https://twitter.com/Akien/status/1719693063570837779
