### ISSUE TITLE
Failing to build GDExtension according to tutorial; KeyError: 'is_bitfield'

### ISSUE THREAD

**Issue by MyStarrySpace** [godotengine/godot#85929]
### Tested versions

- Reproducible in: master (48afa82), 4.2 (54136ee), 4.1 (631cd5f), 4.0 (2fdac1c)
- GDExtension does not exist in previous versions

### System information

Godot v4.2.beta4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.4592) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

I am trying to create a new extension for Godot v4. I am following the documentation here and using VSCode: https://docs.godotengine.org/en/4.2/tutorials/scripting/gdextension/gdextension_cpp_example.html; I am able to do everything up to the step where I generate and compile the bindings. 

I am running the following command inside of godot-cpp:
`scons platform=windows custom_api_file=C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj\extension_api.json`

However, instead of the bindings being generated, I get the following error:
```
PS C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj3\godot-cpp> scons platform=windows custom_api_file=C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj3\extension_api.json     
scons: Reading SConscript files ...
Auto-detected 12 CPU cores available for build parallelism. Using 11 cores by default. You can override it with the -j argument.
Building for architecture x86_64 on platform windows
scons: done reading SConscript files.
scons: Building targets ...
scons_generate_bindings(["gen\include\godot_cpp\core\ext_wrappers.gen.inc", "gen\include\godot_cpp\variant\string.hpp", 
```
(Then it continues the big list of a bunch of files that are part of the engine),
```
 "gen\include\godot_cpp\classes\global_constants.hpp", "gen\include\godot_cpp\classes\global_constants_binds.hpp", "gen\include\godot_cpp\core\version.hpp", "gen\src\variant\utility_functions.cpp"], ["C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj3\extension_api.json", "gdextension\gdextension_interface.h", "binding_generator.py"])
Built-in type config: float_64
scons: *** [gen\include\godot_cpp\core\ext_wrappers.gen.inc] KeyError : 'is_bitfield'
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\SCons\Action.py", line 1279, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj3\godot-cpp\binding_generator.py", line 152, in scons_generate_bindings
    generate_bindings(
  File "C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj3\godot-cpp\binding_generator.py", line 176, in generate_bindings
    generate_global_constants(api, target_dir)
  File "C:\Users\hayan\LocalDocuments\Programming\Gamedev\testProj3\godot-cpp\binding_generator.py", line 1707, in generate_global_constants
    if enum_def["is_bitfield"]:
KeyError: 'is_bitfield'
scons: building terminated because of errors.
```

### Steps to reproduce

I am just following the tutorial linked above

### Minimal reproduction project (MRP)

[testProj.zip](https://github.com/godotengine/godot/files/13619361/testProj.zip)

**Comment by AThousandShips** [comment]
What version of Godot was the API generated from? And what version of godot-cpp are you using?

**Comment by MyStarrySpace** [comment]
Ah I see, I was generating the API from Godot Engine v4.0.alpha.calinou.0c5f25495 while calling godot --dump-extension-api. I had downloaded Godot 4.2, but I guess my Godot PATH variable was still set to the old version. Let me try to change it to the new Godot version and try again
