### ISSUE TITLE
C# EditorInspectorPlugin throws errors when connected to the Resource.Changed signal

### ISSUE THREAD

**Issue by tjpotts** [godotengine/godot#86244]
### Tested versions

Reproducible in: 4.2.stable.mono, 4.1.3.stable.mono, 4.1.stable.mono, 4.1.beta3.mono, 4.1.dev4.mono, 4.1.dev2.mono
Not-reproducible in: 4.0.4.stable.mono, 4.1.dev1.mono

### System information

Manjaro Linux

### Issue description

I'm trying to create an `EditorInspectorPlugin` in C# to display some information about a custom `Resource` I've created in the Inspector. The `EditorInspectorPlugin` connects to the `Changed` signal on the resource in order to redraw when the resource is changed. If any instance of the plugin is present in the Inspector when rebuilding the C# project, I get the following error message:

```
Attempt to disconnect a nonexistent connection from '<Resource#-9223369747536478755>'. Signal: 'changed', callable: 'Delegate::Invoke'.
```

Initially the plugin continues working, however rebuilding again gives the following errors mentioning #78513 and the plugin ceases functioning at all:

```
 /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.ObjectDisposedException: Cannot access a disposed object.
  Object name: 'CustomResourceEditor'.
     at Godot.GodotObject.GetPtr(GodotObject instance) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 73
     at Godot.GodotObject.GetInstanceId() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/GodotObject.cs:line 461
     at Godot.DelegateUtils.TrySerializeSingleDelegate(Delegate delegate, Byte[]& buffer) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 151
     at Godot.DelegateUtils.TrySerializeDelegate(Delegate delegate, Array serializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 110
     at Godot.DelegateUtils.TrySerializeDelegateWithGCHandle(IntPtr delegateGCHandle, godot_array* nSerializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 302
  modules/mono/mono_gd/gd_mono.cpp:528 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/csharp_script.cpp:819 - Condition "managed_callable->delegate_handle.value == nullptr" is true. Continuing.
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.ObjectDisposedException: Cannot access a disposed object.
  Object name: 'CustomResourceEditor'.
     at Godot.GodotObject.GetPtr(GodotObject instance) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 73
     at Godot.GodotObject.GetInstanceId() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/GodotObject.cs:line 461
     at Godot.DelegateUtils.TrySerializeSingleDelegate(Delegate delegate, Byte[]& buffer) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 151
     at Godot.DelegateUtils.TrySerializeDelegate(Delegate delegate, Array serializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 110
     at Godot.DelegateUtils.TrySerializeDelegateWithGCHandle(IntPtr delegateGCHandle, godot_array* nSerializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 302
  modules/mono/mono_gd/gd_mono.cpp:528 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/csharp_script.cpp:819 - Condition "managed_callable->delegate_handle.value == nullptr" is true. Continuing.
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.ObjectDisposedException: Cannot access a disposed object.
  Object name: 'CustomResourceEditor'.
     at Godot.GodotObject.GetPtr(GodotObject instance) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:line 73
     at Godot.GodotObject.GetInstanceId() in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/GodotObject.cs:line 461
     at Godot.DelegateUtils.TrySerializeSingleDelegate(Delegate delegate, Byte[]& buffer) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 151
     at Godot.DelegateUtils.TrySerializeDelegate(Delegate delegate, Array serializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 110
     at Godot.DelegateUtils.TrySerializeDelegateWithGCHandle(IntPtr delegateGCHandle, godot_array* nSerializedData) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 302
  modules/mono/mono_gd/gd_mono.cpp:528 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/mono_gd/gd_mono.cpp:512 - .NET: Giving up on assembly reloading. Please restart the editor if unloading was failing. (User)
```

This issue occurs when using the base `Resource` class as well, not only for the custom resource. Manually disconnecting the signal in either the destructor or `_ExitTree` method of the plugin does not help.

Maybe related to #76708?

### Steps to reproduce

* Open the MRP
* Build the project
* Double-click `test.tres` to open it in the Inspector.
* `MSBuild -> Rebuild Project`
* `MSBuild -> Rebuild Project` again

### Minimal reproduction project (MRP)

[TestProject.zip](https://github.com/godotengine/godot/files/13694115/TestProject.zip)

**Comment by tjpotts** [comment]
Some more testing narrowed this down to being introduced between `4.1.dev1` and `4.1.dev2`.

#72421 was included in that release, which was mentioned as the source of regression in #76708. Sounds like #77199 claims to have mostly fixed the issue, except in the case of reloading assemblies. I'm getting a bit out of my depth in understanding the internals of how Godot integrates with C#, so not sure where to go from here without some assistance.

**Comment by chase-cobb** [comment]
Similarly I have added two custom resources to my project and after registering to the Changed event I get thousands of errors related to this event and "Invoke" each time I build my project. It wasn't obvious to me if there was an expected flow of registering/unregistering this event, or if this is a regression.

**Comment by shadowman** [comment]
Same here. Creating a custom resource and registering to the change event.

I'm using Godot 4.4.1.stable.mono

**Comment by raulsntos** [comment]
Can still reproduce in Godot 4.7.2.
