### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/SupervisorKt

### ISSUE THREAD

**Issue by myselfuser1** [godotengine/godot#86355]
### Tested versions

Occurs in all version of Godot, tested with the latest v4.2.1 as well

### System information

Godot v4.2.1.stable - macOS 13.6.1 - Vulkan (Mobile) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

I am trying to use coroutines feature which is from kotlin language for my android plugin. but my app crashes with below message

```
Process: com.example.mygodotapp, PID: 21586
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/SupervisorKt;
                                                                                                    	at com.example.androidlocation.LocationService.<init>(LocationService.kt:21)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4922)
                                                                                                    	at android.app.ActivityThread.access$1800(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.SupervisorKt" on path: DexPathList[[zip file "/data/app/~~ODYQy-wm45_J8E3bkTjOVA==/com.example.mygodotapp-TDcRajdFrZrn0B_hub7hLA==/base.apk"],nativeLibraryDirectories=[/data/app/~~ODYQy-wm45_J8E3bkTjOVA==/com.example.mygodotapp-TDcRajdFrZrn0B_hub7hLA==/lib/arm, /data/app/~~ODYQy-wm45_J8E3bkTjOVA==/com.example.mygodotapp-TDcRajdFrZrn0B_hub7hLA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.example.androidlocation.LocationService.<init>(LocationService.kt:21) 
                                                                                                    	at java.lang.Class.newInstance(Native Method) 
                                                                                                    	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129) 
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75) 
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4922) 
                                                                                                    	at android.app.ActivityThread.access$1800(ActivityThread.java:310) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
``` 

I think the issue is because Godot android ships with koltin 1.7.0, i have tried overriding it to 1.9.20 but it still does not work

### Steps to reproduce

Download the project given below and tried to run it on android device, as soon as you click the first button the app crashes

### Minimal reproduction project (MRP)

[Here](https://github.com/kyadalu1/AndroidLocEg) is the my android library repo and [here](https://github.com/kyadalu1/GodotLocEg) is the Godot repo which you can use

**Comment by EiTaNBaRiBoA** [comment]
I am having a constant crash  when trying to work with workmanager
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/OneTimeWorkRequest$Builder; `
even though i added the dependacies to AndroidExportPlugin		
var dependencies = PackedStringArray(["com.google.android.gms:play-services-base:18.2.0",
		"com.google.android.play:review:2.0.1","org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3","androidx.work:work-runtime-ktx:2.9.0"])

Is there a way to fix it?

**Comment by BraveEvidence** [comment]
Try [this](https://www.youtube.com/watch?v=65c85lSvWqQ&list=PLQhQEGkwKZUo54QWpXeJGpvV0i-QYJtSh&index=8).

**Comment by EiTaNBaRiBoA** [comment]
> Try [this](https://www.youtube.com/watch?v=65c85lSvWqQ&list=PLQhQEGkwKZUo54QWpXeJGpvV0i-QYJtSh&index=8).

I followed his tutorial and also commented on his other [video](https://youtu.be/9YO4On0Lzg8?si=k2zDbd26hBjNRggT)
Still doesn't work specifically on worker
