### ISSUE TITLE
Listening to socket fails when exporting to HTML5

### ISSUE THREAD

**Issue by JonasPf** [godotengine/godot#8897]
**Operating system or device - Godot version:**

Ubuntu 16.04 with Godot 2.1.3.stable.official

**Issue description:**

My godot project listens to a socket using this code:

```
var port = 4545
var server = TCP_Server.new()

func _ready():
	if server.listen(port) == 0:
		print("Server running on port " + str(port))
		set_process(true)
	else:
		print("Cannot listen on port " + str(port))
		get_tree().quit()

```

I export it to HTML5 and run it locally using the python internal webserver: `sudo python -m SimpleHTTPServer`. When I open the webpage, it starts loading and fails with the following message:

```
**WARNING**: At: ./drivers/unix/socket_helpers.h:87:_socket_create() - Unable to set/unset IPv4 address mapping over IPv6
bad ioctl syscall 21537
abort("bad ioctl syscall 21537") at Error
    at jsStackTrace (http://127.0.0.1:8000/index.js:1:17538)
    at stackTrace (http://127.0.0.1:8000/index.js:1:17709)
    at abort (http://127.0.0.1:8000/index.js:3:12282)
    at ___syscall54 (http://127.0.0.1:8000/index.js:1:174652)
    at qoj (http://127.0.0.1:8000/index.asm.js:27:104858)
    at Array.CRa (http://127.0.0.1:8000/index.asm.js:18:126238)
    at Array.cRi (http://127.0.0.1:8000/index.asm.js:14:809595)
    at Array.MHh (http://127.0.0.1:8000/index.asm.js:16:643720)
    at p4i (http://127.0.0.1:8000/index.asm.js:14:1161263)
    at UA (http://127.0.0.1:8000/index.asm.js:23:909097)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
**EXCEPTION**:
```

**Comment by vnen** [comment]
AFAIK networking was never implemented for the HTML5 platform.

**Comment by eska014** [comment]
That's right, in fact this can't be implemented, direct TCP is impossible in browsers.
However I want to get `HTTPClient` working in time for 3.0, maybe we'll also add support for WebSocket or WebRTC eventually

**Comment by JonasPf** [comment]
Ok cool, thanks for all the great work :-)

**Comment by eska014** [comment]
We have #4226 open for HTTPClient, so closing this

**Comment by vnen** [comment]
@eska014 BTW, apparently Emscripten is capable of proxying UDP packets over WebSockets: https://twitter.com/icculus/status/860379737658621952
