### ISSUE TITLE
C# Array of StringNames Exported property with null default value causes null value exceptions in editor and in game.

### ISSUE THREAD

**Issue by operation404** [godotengine/godot#89586]
### Tested versions

Reproducible in v4.2.1.stable.mono b09f793

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When exporting a C# array of StringName objects with a null default value, null argument exceptions are thrown both in the editor and at runtime, unlike C# arrays of other reference or value types such as Resources or Vector2s. The exception is also not thrown when exporting a single StringName set to null or exporting a `Godot.Collections.Array<StringName>`.
```cs
[Export] public StringName[] ExportedArray;
```

The editor error in question:
```
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.ArgumentNullException: Value cannot be null. (Parameter 'array')
     at Godot.Collections.Array..ctor(Span`1 array) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs:line 87
     at Godot.NativeInterop.VariantUtils.CreateFromSystemArrayOfStringName(Span`1 from) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:line 235
     at ExportArray.ExportArrayTest.GetGodotPropertyDefaultValues() in [[personal computer directory name omitted]]\ArrayTesting\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\ExportArray.ExportArrayTest_ScriptPropertyDefVal.generated.cs:line 18
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
     --- End of inner exception stack trace ---
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(Type type, IntPtr scriptPtr,  addDefValFunc) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 1052
```

### Steps to reproduce

Make a class extending from Node or Resource with the GlobalClass attribute and an exported property of type `StringName[]`. Upon building or running the project, the null argument exceptions are thrown.

```cs
using Godot;
namespace ExportArray;

[GlobalClass]
public partial class ExportArrayTest : Resource {
    [Export]
    public StringName[] ExportedArray;
}
```

### Minimal reproduction project (MRP)

[StringName Array Bug MRP.zip](https://github.com/godotengine/godot/files/14625219/StringName.Array.Bug.MRP.zip)

**Comment by ScottPeabody** [comment]
Was messing around and tried to set property with a default initialized size of 0, and it worked. Was able to work with it in the UI after as well.

```
    [Export]
    public StringName[] ExportedArray = new StringName[0];
```
another workaround is
```
    public StringName[] ExportedArray = Array.Empty<StringName>();
```

<img width="467" alt="image" src="https://github.com/godotengine/godot/assets/88902054/8bc9df6a-2869-44b9-973d-039541350680">


Looking at the type definition there is no handler for if it is null so if there is no philosophical reason for this, the engine class could be updated to handle it. Maybe something like this?

```
public StringName(string name)
{
    if (!string.IsNullOrEmpty(name))
    {
        godot_string_name value = NativeFuncs.godotsharp_string_name_new_from_string(name);
        NativeValue = (godot_string_name.movable)value;
        _weakReferenceToSelf = DisposablesTracker.RegisterDisposable(this);
    }
    else
    {
        // Handle empty or null strings gracefully
        NativeValue = godot_string_name.movable.Zero;
        _weakReferenceToSelf = DisposablesTracker.RegisterDisposable(this);
    }
}
```
