### ISSUE TITLE
Object.call_deferred crashes without an error after being called too many times

### ISSUE THREAD

**Issue by Zagusan** [godotengine/godot#90061]
### Tested versions

- **Reproducible in:** 4.2.1 Stable (x64, .NET), 4.3-dev5 (x64, .NET)
- **Doesn't run:** 4.0 Stable (x64, .NET), 4.1.3 Stable (x64, .NET)

Both of these versions didn't run because of the following error, which showed up 12 times in the console:
```
E 0:00:02:0451   mesh_add_surface: Meshes must contain a vertex array, an index array, or both
<C++ Error>    Condition "!p_surface.index_count && !p_surface.vertex_count" is true.
<C++ Source>   servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:388 @ mesh_add_surface()
```

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

I made a maze generation program which worked flawlessly until I tried to add multithreading to it. Then, I noticed that `Object.call_deferred()` was causing a crash without an error output when generating larger mazes, regardless if multithreading was being used. I'd expect `Object.call_deferred()` to either not crash, or output an error while doing so.

**GDScript Example:**
The program works fine (sometimes it crashes regardless) with a maze size of 600*600, but when increased to 601*601, the program crashes. When the deferred and the multithreading variables are disabled, the script is able to generate much larger mazes.
https://github.com/godotengine/godot/assets/101441443/32deabe6-dd0e-477d-8d09-682953b4de4a

**C# Example:**
The situation is exactly the same, but the C# limit is much lower, at 559* 559, and crashing at higher values, however, it exhibits much more consistency in its behavior.
https://github.com/godotengine/godot/assets/101441443/d1b2442a-afe8-487c-9b68-375d58d6ca10

### Steps to reproduce

1. Open the project
2. Select the `MazeGen` object in the editor
	**You may change the script from `MazeGen.gd` to `MazeGen.cs` to test C#**
3. Set the Size property to its default value (max value which won't crash), then run the project
4. Increase the Size property and re-run the project (now it crashes)
5. Disable Multithreading, then re-run the project (still crashes)
6. Disable Deferred, then re-run the project (now it works fine)

**Note:** The mouse is captured by default. Press ESC to release it, and left click to recapture it.

### Minimal reproduction project (MRP)

[Maze MRP.zip](https://github.com/godotengine/godot/files/14813790/Maze.MRP.zip)

**Comment by JekSun97** [comment]
I confirm this problem. Nice labyrinth by the way!
Only for me it crashes from the game on 608,
and if I disable deferred, but enable multithreading, game crashes and the following error appears:
`E 0:00:02:0088   MazeGen.gd:159 @ PlaceTileDeferred(): This function in this node (/root/Maze/MazeGen) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  <Ошибка C++>   Condition "!is_readable_from_caller_thread()" is true. Returning: (Ref<World3D>())
  <Исходный код C++>scene/3d/node_3d.cpp:757 @ get_world_3d()
  <Трассировка стека>MazeGen.gd:159 @ PlaceTileDeferred()
                 MazeGen.gd:208 @ Generate()
`

**Comment by Zagusan** [comment]
Thanks! Yeah, the crashing when multithreading is enabled and deferred is disabled is intended, since `GridMap.set_cell()` isn't thread safe, but I was too lazy to add an error or a warning. By the way, how did you get an error to show up? It would be quite helpful to know in order to completely rule out my code as being the problem

**Comment by AThousandShips** [comment]
Can you run the editor from the console? It should print an error there (the fact that crash messages don't show up in the editor log is a known issue, can't find the report now though)

**Comment by Zagusan** [comment]
I ran it from the console and I got this error:
```
ERROR: Caller thread can't call this function in this node (/root/Maze/MazeGen). Use call_deferred() or call_thread_group() instead.
   at: (scene/main/node.cpp:3575)
Failed method: GridMap::set_cell_item. Message queue out of memory. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_mb' in project settings.
```
Curiously, when ran from C#, the error is different:
```
ERROR: Caller thread can't call this function in this node (/root/Maze/MazeGen). Use call_deferred() or call_thread_group() instead.
   at: (scene/main/node.cpp:3575)
Failed method: GridMap::set_cell_item. Message queue out of memory. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_mb' in project settings.
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_call(IntPtr, IntPtr, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error ByRef)
   at Godot.NativeCalls.godot_icall_2_701(IntPtr, IntPtr, Godot.NativeInterop.godot_string_name, Godot.Variant[], Godot.NativeInterop.godot_string_name)
   at Godot.GodotObject.CallDeferred(Godot.StringName, Godot.Variant[])
   at MazeGen.PlaceTileDeferred(Tile, Godot.Vector2I)
   at MazeGen+<Generate>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at MazeGen.Generate()
```
I went ahead and increased the message queue memory limit, as stated in the error, and it worked with larger sizes. Is this all normal behavior? Should I go ahead and close the issue? Also, thanks for your help! I wouldn't have figured out the problem without it

**Comment by Zagusan** [comment]
> Can you run the editor from the console? It should print an error there (the fact that crash messages don't show up in the editor log is a known issue, can't find the report now though)

I wasn't able to find any duplicate report either, so I'll go ahead and edit this one to be more inline with what's happening. If there is a duplicate, please go ahead and mark it as such
