### ISSUE TITLE
Command line export doesn't exit if there is a build error

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#91527]
### Tested versions

Reproducible in v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

If I try to export the project from command line but there is build error, either GDScript error or C# error, Godot executable doesn't exit. I need to press Ctrl-C to exit.

A build error seems to cause this problem every time. But I also noticed that sometimes even working build doesn't exit cleanly if I ran the export command from Window's bat-file. However, I don't know to reprocude that. 

I also wonder, if it would be better to instantly quit the exporting process, if the build fails. Now the process continues with the savepack.

This is a somewhat shortened and anonymized output:
```
λ "C:\godot\Godot_v4.3-dev6_mono_win64\Godot_v4.3-dev6_mono_win64_console.exe" --verbose --headless --no-window --export-release "Windows Desktop"
Godot Engine v4.3.dev6.mono.official.89850d553 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Using "default" pen tablet driver...

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
.NET: Initializing module...
Found hostfxr: C:\Program Files\dotnet\host/fxr/8.0.4/hostfxr.dll
.NET: hostfxr initialized
.NET: GodotPlugins initialized
CORE API HASH: 3400182566
EDITOR API HASH: 130872444
EditorSettings: Load OK!
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Generating new icons.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
Found .NET Sdk version '8.0.204': C:\Program Files\dotnet\sdk\8.0.204
Loaded system CA certificates
Failed to bind socket. Error: 3
Failed to bind socket. Error: 3
EditorSettings: Save OK!
update_scene_groups: begin: Update Scene Groups steps: 16
        update_scene_groups: step 0: Updating Scene Groups...
        update_scene_groups: step 1: Updating Scene Groups...
        update_scene_groups: step 2: Updating Scene Groups...
        update_scene_groups: step 3: Updating Scene Groups...
        update_scene_groups: step 4: Updating Scene Groups...
        update_scene_groups: step 5: Updating Scene Groups...
        update_scene_groups: step 6: Updating Scene Groups...
        update_scene_groups: step 7: Updating Scene Groups...
        update_scene_groups: step 8: Updating Scene Groups...
        update_scene_groups: step 9: Updating Scene Groups...
        update_scene_groups: step 10: Updating Scene Groups...
        update_scene_groups: step 11: Updating Scene Groups...
        update_scene_groups: step 12: Updating Scene Groups...
        update_scene_groups: step 13: Updating Scene Groups...
        update_scene_groups: step 14: Updating Scene Groups...
        update_scene_groups: step 15: Updating Scene Groups...
update_scene_groups: end
dotnet_publish_project: begin: Publishing .NET project... steps: 1
        dotnet_publish_project: step 0: Running dotnet publish
Running:  "C:\Program Files\dotnet\dotnet.EXE" publish C:/godot/foo/bar.csproj -c ExportRelease -r win-x64 --self-contained true -v normal -l:GodotTools.BuildLogger.GodotBuildLogger,... ...
dotnet publish exited with code: 1. Log file: ...
dotnet_publish_project: end
ERROR: Failed to export project: Failed to build project.
   at: void GodotTools.Export.ExportPlugin._ExportBegin(System.String[], bool, string, uint) (/root/godot/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:123)
System.InvalidOperationException: Failed to build project.
   at GodotTools.Export.ExportPlugin._ExportBeginImpl(String[] features, Boolean isDebug, String path, Int64 flags) in /root/godot/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:line 255
   at GodotTools.Export.ExportPlugin._ExportBegin(String[] features, Boolean isDebug, String path, UInt32 flags) in /root/godot/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs:line 123
savepack: begin: Packing steps: 102
...
savepack: end
ERROR: Attempting to parent and popup a dialog that already has a parent.
   at: (scene/main/window.cpp:1838)
EditorSettings: Save OK!
Unloading: Disposing tracked instances...
Unloading: Finished disposing tracked instances.
XR: Clearing primary interface
XR: Removed interface "Native mobile"
XR: Removed interface "OpenXR"
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2314)
Leaked instance: Image:9223373671391885761 - Resource path:
Leaked instance: Image:9223373672683731395 - Resource path:
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
Orphan StringName: _setup_local_to_scene (static: 0, total: 2)
Orphan StringName: EditorFileDialog (static: 1, total: 7)
Orphan StringName: AudioStream (static: 0, total: 1)
Orphan StringName: ItemList (static: 1, total: 9)
Orphan StringName: TabBar (static: 1, total: 9)
Orphan StringName: FileDialog (static: 6, total: 12)
Orphan StringName: AudioStreamRandomizer (static: 1, total: 5)
Orphan StringName: export_presets_runnable_updated (static: 0, total: 1)
Orphan StringName: OptionButton (static: 2, total: 12)
Orphan StringName: Node (static: 12, total: 13)
Orphan StringName: export_presets_updated (static: 0, total: 1)
Orphan StringName: Texture2D (static: 0, total: 5)
Orphan StringName: PopupMenu (static: 1, total: 15)
StringName: 13 unclaimed string names at exit.
^C
```

### Steps to reproduce

1. Add some build breaking error to the project code.
2. Run `"C:\godot\Godot_v4.3-dev6_mono_win64\Godot_v4.3-dev6_mono_win64_console.exe" --verbose --headless --no-window --export-release "Windows Desktop"`

### Minimal reproduction project (MRP)

N/A

**Comment by robert-wallis** [comment]
![image](https://github.com/godotengine/godot/assets/145938/c850b999-8ffe-4f16-a854-85dfff686002)

I've noticed something similar, however when I look at Task Manager the process actually did quit.  And when I simply press RETURN a few times on the keyboard, an empty prompt appears in the text (see the top few lines of the following screenshot)
![image](https://github.com/godotengine/godot/assets/145938/7e8ddf7a-86a9-49b2-a3c2-a88bba2ab637)

Is this the same in your case?

# Steps to reproduce:
1. use godot 4.3.dev on Windows in Powershell
2. cd to a folder where a godot project does not exist, like `~/Desktop`
3. run the command `godot --headless -v --export-release "anything" anything.exe`
4. appears to not exit, but does exit

Also this causes a crash and that crash should be fixed too.

![image](https://github.com/godotengine/godot/assets/145938/8048f3ac-8271-4885-9e47-b84412c2dae3)

**Comment by akien-mga** [comment]
Does this crash only happen in 4.3 versions, or also 4.2?

**Comment by robert-wallis** [comment]
This particular terminal issue doesn't even need a crash for me and is reproducible with 4.2.2 stable

# Repro Steps:
1. `godot --version`
2. terminal appears to hang
3. type `echo $?`
4. the value `echo` command prints `True` because `godot --version` exited successfully


https://github.com/godotengine/godot/assets/145938/1c27935b-7e90-4324-b2c1-3df1f4564203

**Comment by robert-wallis** [comment]
It's not limited to Terminal, Command Prompt (cmd.exe) also shows this issue.

1. open cmd.exe
2. `godot --version`
3. looks like it's hung
4. `echo %errorlevel%`
5. echo executes and returns `0` (success)

**Comment by bruvzg** [comment]
Are you running `console.exe` executable? If not, this is expected, it's GUI executable and it doesn't own the console, so shell have no idea it should redraw the prompt.

**Comment by robert-wallis** [comment]
Using the `.console.exe` executable solves this issue for me, thanks @bruvzg !

**Comment by miv391** [comment]
Still hangs with v4.3.beta1.mono.official [a4f2ea91a], but now it hangs immediately after "`ERROR: Attempting to parent and popup a dialog that already has a parent.`". I made some updates to the issues description.

**Comment by lokimckay** [comment]
I also have this issue using Godot 4.2.2 stable and executing the *.console.exe binary like so

```
Godot_v4.2.2-stable_win64_console.exe --headless --path <path> --export-release <preset> output.exe
```

**Comment by Calinou** [comment]
@miv391 @lokimckay Can you (or anyone else) still reproduce this bug in [Godot 4.7.1](https://godotengine.org/article/maintenance-release-godot-4-7-1/) or any later release?

I've noticed a different issue as of recently, which I reported separately:

- https://github.com/godotengine/godot/issues/122153

**Comment by miv391** [comment]
> Can you (or anyone else) still reproduce this bug in [Godot 4.7.1](https://godotengine.org/article/maintenance-release-godot-4-7-1/) or any later release?

I tested this in Godot 4.7.1. I don't have Win 10 anymore, so the test system is somewhat different:

Godot v4.7.1.stable.mono - Windows 11 (build 26200) - Multi-window, 1 monitor - Direct3D 12 (Forward+) - dedicated AMD Radeon RX 7600S (Advanced Micro Devices, Inc.; 32.0.31021.5001) - AMD Ryzen 7 7735HS with Radeon Graphics (16 threads) - 15.24 GiB memory - WASAPI (48000 Hz, Stereo/mono)

I couldn't reproduce the original bug (export stucks if there is an error in GDScript code) anymore.

However, I noticed that now export happily produces an executable even if there are errors in GDScript code. Command line output and exit code are identical in both cases (valid code / invalid code). When the executable is run, I get:

```
c:\godot\build-test-471
λ Godot Engine v4.7.1.stable.mono.official.a13da4feb - https://godotengine.org
D3D12 12_0 - Forward+ - Using Device #0: AMD - AMD Radeon RX 7600S

SCRIPT ERROR: Parse Error: Unexpected identifier "" in class body.
          at: GDScript::reload (res://node_2d.gd:3)
ERROR: Failed to load script "res://node_2d.gd" with error "Parse error".
   at: load (modules/gdscript/gdscript_resource_format.cpp:46)
```

I think this is very bad for any kind of CI/CD. 

I tested exporting project containing bad code also in Linux. Executable is produced, error code is 0, but at least script errors are printed to stderr.

**Comment by Calinou** [comment]
> However, I noticed that now export happily produces an executable even if there are errors in GDScript code. Command line output and exit code are identical in both cases (valid code / invalid code). When the executable is run, I get:

I've opened a new issue for this:

- https://github.com/godotengine/godot/issues/122169

Closing this issue, since the original issue this one was tracking appears to be resolved.
