### ISSUE TITLE
Godot 4 dynamically evaluating C# script then crash, Fatal error.System.AccessViolationException

### ISSUE THREAD

**Issue by renleidedadi** [godotengine/godot#92906]
### Tested versions

- Reproducible in:
v4.3.beta1.mono.official [a4f2ea91a],
v4.2.2.stable.mono.official [15073afe3],
v4.1.4.stable.mono.official [fe0e8e557],
v4.0.4.stable.mono.official [fc0b241c9].

- Not reproducible in:
v3.5.3.stable.mono.official [6c814135b].

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

i creating a interactive tutorial like "[Learn Godot GDScript From Zero](https://github.com/GDQuest/learn-gdscript)". When running C# code, godot 3 works, but godot 4 crash.

How to dynamically evaluate C# code at Godot 4?

in this video, dynamically evaluate GDScript and C#, the Godot 4 chashed:

https://github.com/godotengine/godot/assets/67264008/b4ef231f-193a-4aef-9f04-59f4f6f7fce7

### Steps to reproduce

1. download the MRP.
2. open Godot 4 version(Godot 3 version is for comparison).
3. run Main scene.
4. click "run C#" button.
5. Godot 4 crash, Godot 3 works.

### Minimal reproduction project (MRP)

[Csharp Interpreter in Godot C#.zip](https://github.com/user-attachments/files/15748645/Csharp.Interpreter.in.Godot.mono.zip)

**Comment by AThousandShips** [comment]
Please provide the error messages as text as well, it's impossible to investigate them if they're just in a video

How did you convert the code to 4.x? The link you provided is for 3.x only, it even says so, so this isn't a bug unless you've converted the code correctly, Godot 4 can't just run projects for Godot 3 without some conversion

**Comment by renleidedadi** [comment]
> Please provide the error messages as text as well, it's impossible to investigate them if they're just in a video
> 
> How did you convert the code to 4.x? The link you provided is for 3.x only, it even says so, so this isn't a bug unless you've converted the code correctly, Godot 4 can't just run projects for Godot 3 without some conversion

oh, the MRP convert the code to 4.x is unzip the file, then can in find the 4.x code inside.

of course, this error messages:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_string_new_with_utf16_chars(Godot.NativeInterop.godot_string ByRef, Char*)
   at Godot.NativeInterop.Marshaling.ConvertStringToNative(System.String)
   at Godot.GD.Print(System.String)
   at Submission#0+<<Initialize>>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Submission#0.<Initialize>()
   at Submission#0.<Factory>(System.Object[])
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState+<RunSubmissionsAsync>d__9`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Scripting.ScriptExecutionState+<RunSubmissionsAsync>d__9`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Scripting, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<RunSubmissionsAsync>d__9`1<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.CodeAnalysis.Scripting.ScriptExecutionState+<RunSubmissionsAsync>d__9`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Scripting, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<RunSubmissionsAsync>d__9`1<System.__Canon> ByRef)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Immutable.ImmutableArray`1<System.Func`2<System.Object[],System.Threading.Tasks.Task>>, System.Func`2<System.Object[],System.Threading.Tasks.Task>, System.Runtime.CompilerServices.StrongBox`1<System.Exception>, System.Func`2<System.Exception,Boolean>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1+<RunSubmissionsAsync>d__21[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.CodeAnalysis.Scripting.Script`1+<RunSubmissionsAsync>d__21[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Scripting, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<RunSubmissionsAsync>d__21<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.CodeAnalysis.Scripting.Script`1+<RunSubmissionsAsync>d__21[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Scripting, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<RunSubmissionsAsync>d__21<System.__Canon> ByRef)
   at Microsoft.CodeAnalysis.Scripting.Script`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunSubmissionsAsync(Microsoft.CodeAnalysis.Scripting.ScriptExecutionState, System.Collections.Immutable.ImmutableArray`1<System.Func`2<System.Object[],System.Threading.Tasks.Task>>, System.Func`2<System.Object[],System.Threading.Tasks.Task>, System.Func`2<System.Exception,Boolean>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync(System.Object, System.Func`2<System.Exception,Boolean>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RunAsync(System.Object, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.RunAsync[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String, Microsoft.CodeAnalysis.Scripting.ScriptOptions, System.Object, System.Type, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String, Microsoft.CodeAnalysis.Scripting.ScriptOptions, System.Object, System.Type, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.EvaluateAsync(System.String, Microsoft.CodeAnalysis.Scripting.ScriptOptions, System.Object, System.Type, System.Threading.CancellationToken)
   at CSharp.OnButtonPressed()
   at CSharp.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error*, Godot.NativeInterop.godot_variant*)
```

**Comment by raulsntos** [comment]
You can't just execute C# code that uses Godot functions, because these functions are implemented in C++ and your assembly didn't go through the initialization process that sets this up.

Instead, you should reuse the existing running GodotSharp assembly from the current ALC. This should work:

```csharp
public void OnButtonPressed()
{
    CodeEdit input = GetNode<CodeEdit>("CodeEdit");
    Assembly[] references = GetValidAssemblies();
    ScriptOptions options = ScriptOptions.Default.WithReferences(references);
    using var assemblyLoader = new Microsoft.CodeAnalysis.Scripting.Hosting.InteractiveAssemblyLoader();
    foreach (var assembly in references)
    {
        assemblyLoader.RegisterDependency(assembly);
    }
    var script = Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript.Create(input.Text, options, assemblyLoader: assemblyLoader);
    Task result = script.RunAsync();
}
```

**Comment by renleidedadi** [comment]
> you should reuse the existing running GodotSharp assembly from the current ALC. This should work:

This code work! it looks like this is my code problem. thanks
