### ISSUE TITLE
System.AccessViolationException when creating a new Node2D in a unit test with xUnit

### ISSUE THREAD

**Issue by DevSavvySerge** [godotengine/godot#92917]
### Tested versions

- Reproductible in Godot 4.2.1 & 4.2.2

### System information

Windows 10 - Godot 4.2.2

### Issue description

# System.AccessViolationException when creating a new Node2D in a unit test with xUnit

## Description
When running a simple unit test using xUnit that creates a new instance of `Node2D`, the test host process crashes with a `System.AccessViolationException`. This issue occurs consistently and seems to indicate memory corruption.

## Reproducibility
100% - The error occurs every time the test is run.

## Additional Information
- the issue occurs with other nodes (not just `Node2D`).

## Steps to Reproduce

1. Create a new project in Godot.
2. Add a C# script file named `UnitTest1.cs` with the following code:

    ```csharp
    using Godot;
    using Xunit;

    namespace Test2
    {
        public class UnitTest1
        {
            [Fact]
            public void Test1()
            {
                var o = new Node2D();
            }
        }
    }
    ```

3. Run the unit test using the `dotnet test` command.

## Expected Result
The test should pass without any exceptions.

## Actual Result
The test host process crashes with the following error:

    The active test run was aborted. Reason: Test host process crashed : Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at Godot.NativeInterop.NativeFuncs.godotsharp_string_new_with_utf16_chars(Godot.NativeInterop.godot_string ByRef, Char*)
       at Godot.NativeInterop.Marshaling.ConvertStringToNative(System.String)
       at Godot.NativeInterop.NativeFuncs.godotsharp_string_name_new_from_string(System.String)
       at Godot.StringName..ctor(System.String)
       at Godot.StringName.op_Implicit(System.String)
       at Godot.Node2D..cctor()
       at Godot.Node2D..ctor()
       at Test2.UnitTest1.Test1()
       ...

### Minimal reproduction project (MRP)

N/A

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="GodotSharp" Version="4.2.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>

**Comment by AThousandShips** [comment]
Is xUnit officially supported in any way? This doesn't seem like a Godot issue necessarily

**Comment by DevSavvySerge** [comment]
Be it xUnit or any other framework (but Godot?), the issue actually is you cannot create Node2d based objects which makes it impossible for running some tests automatically.

**Comment by AThousandShips** [comment]
Are you running the code from within Godot? Or as a separate application?

**Comment by DevSavvySerge** [comment]
As a separate application. To my current knowledge, the only way to run code from within Godot is to actually run a scene.

**Comment by AThousandShips** [comment]
It is not possible to run Godot code as an isolated application, see https://github.com/godotengine/godot/issues/92906#issuecomment-2156129842

**Comment by DevSavvySerge** [comment]
Would the only solution be to create a scene and trigger tests from within? Meaning creating some kind of tests runner running within godot?

**Comment by AThousandShips** [comment]
Indeed, the C# bindings are just bindings, all the background code is run in c++ within the engine, with a few exceptions all the classes in C# are just calling engine methods to do the work, there's no version of the engine written in C# directly

**Comment by DevSavvySerge** [comment]
Ok, thank you for the quick answer. That is important knowledge to start with.

**Comment by AThousandShips** [comment]
Let's see if the dotnet team thinks this should be documented more clearly, but moving this to the documentation repo as it's a documentation issue and not part of the class reference
