### ISSUE TITLE
memory overflow when shader's uniform array out of range

### ISSUE THREAD

**Issue by AkiYama-Ryou** [godotengine/godot#93144]
### Tested versions

4.2.2 stable

### System information

windows 10

### Issue description

yesterday I wrote a shader with a uniform Array:
```uniform sampler2D[7] gradient :source_color```
but I forgot the uplimit range.Then I added 11 gradient color in inspector.
Then memory overflow and Godot editor crashed. I can't open my project anymore until I understood the reason.
I think the inspector should stop me add child when the child count over the up limit of array.
Or the engine should just give me a helpful error instead of crashing

### Steps to reproduce

1. download this MRP and open this project if you can.
2. open control.tscn. It is a simple control with a subview container and a label.
3. the subview container have a materail.Open the inspector you can see there is 5 gradient color have been defined.
4. open the popupfont.gdshader file. you can see sampler2D[2]. So it will memory overflow.
5. run the game and press A. the script control.gd will do this:
```
var obj = SUB_VIEWPORT_CONTAINER.instantiate() as SubViewportContainer
obj.material = obj.material.duplicate()
```
6. Then you will get the Bug: first our game crashed without any error massage. 
7. At this time, maybe we want to try restart godot editor. So, close the editor.
8. try to open this project again. You will get the editor crashing.
9. delete the .godot folder or delete the control.tscn you can open project but it will crash again just a while

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/15830473/test.zip)

**Comment by Chaosus** [comment]
Call stack:
```
>	godot.windows.editor.dev.x86_64.exe!_free_base(void * block) Line 105	C++
 	godot.windows.editor.dev.x86_64.exe!Memory::free_static(void * p_ptr, bool p_pad_align) Line 168	C++
 	godot.windows.editor.dev.x86_64.exe!CowData<RenderingDevice::AttachmentFormat>::_unref(void * p_data) Line 268	C++
 	godot.windows.editor.dev.x86_64.exe!CowData<RenderingDevice::AttachmentFormat>::~CowData<RenderingDevice::AttachmentFormat>() Line 477	C++
 	godot.windows.editor.dev.x86_64.exe!Vector<RenderingDevice::AttachmentFormat>::~Vector<RenderingDevice::AttachmentFormat>() Line 291	C++
 	godot.windows.editor.dev.x86_64.exe!RenderingDevice::framebuffer_create_multipass(const Vector<RID> & p_texture_attachments, const Vector<RenderingDevice::FramebufferPass> & p_passes, __int64 p_format_check, unsigned int p_view_count) Line 2363	C++
 	godot.windows.editor.dev.x86_64.exe!RenderingDevice::framebuffer_create(const Vector<RID> & p_texture_attachments, __int64 p_format_check, unsigned int p_view_count) Line 2298	C++
 	godot.windows.editor.dev.x86_64.exe!FramebufferCacheRD::_allocate_from_data(unsigned int p_views, unsigned int p_hash, unsigned int p_table_idx, const Vector<RID> & p_textures, const Vector<RenderingDevice::FramebufferPass> & p_passes) Line 168	C++
 	godot.windows.editor.dev.x86_64.exe!FramebufferCacheRD::get_cache_multiview<RID>(unsigned int p_views, RID <args_0>) Line 256	C++
 	godot.windows.editor.dev.x86_64.exe!RendererRD::TextureStorage::RenderTarget::get_framebuffer() Line 3013	C++
 	godot.windows.editor.dev.x86_64.exe!RendererRD::TextureStorage::render_target_get_rd_framebuffer(RID p_render_target) Line 3432	C++
 	godot.windows.editor.dev.x86_64.exe!RendererCanvasRenderRD::_render_items(RID p_to_render_target, int p_item_count, const Transform2D & p_canvas_transform_inverse, RendererCanvasRender::Light * p_lights, bool & r_sdf_used, bool p_to_backbuffer, RenderingMethod::RenderInfo * r_render_info) Line 1168	C++
 	godot.windows.editor.dev.x86_64.exe!RendererCanvasRenderRD::canvas_render_items(RID p_to_render_target, RendererCanvasRender::Item * p_item_list, const Color & p_modulate, RendererCanvasRender::Light * p_light_list, RendererCanvasRender::Light * p_directional_light_list, const Transform2D & p_canvas_transform, RenderingServer::CanvasItemTextureFilter p_default_filter, RenderingServer::CanvasItemTextureRepeat p_default_repeat, bool p_snap_2d_vertices_to_pixel, bool & r_sdf_used, RenderingMethod::RenderInfo * r_render_info) Line 1660	C++
 	godot.windows.editor.dev.x86_64.exe!RendererCanvasCull::_render_canvas_item_tree(RID p_to_render_target, RendererCanvasCull::Canvas::ChildItem * p_child_items, int p_child_item_count, const Transform2D & p_transform, const Rect2 & p_clip_rect, const Color & p_modulate, RendererCanvasRender::Light * p_lights, RendererCanvasRender::Light * p_directional_lights, RenderingServer::CanvasItemTextureFilter p_default_filter, RenderingServer::CanvasItemTextureRepeat p_default_repeat, bool p_snap_2d_vertices_to_pixel, unsigned int p_canvas_cull_mask, RenderingMethod::RenderInfo * r_render_info) Line 76	C++
 	godot.windows.editor.dev.x86_64.exe!RendererCanvasCull::render_canvas(RID p_render_target, RendererCanvasCull::Canvas * p_canvas, const Transform2D & p_transform, RendererCanvasRender::Light * p_lights, RendererCanvasRender::Light * p_directional_lights, const Rect2 & p_clip_rect, RenderingServer::CanvasItemTextureFilter p_default_filter, RenderingServer::CanvasItemTextureRepeat p_default_repeat, bool p_snap_2d_transforms_to_pixel, bool p_snap_2d_vertices_to_pixel, unsigned int canvas_cull_mask, RenderingMethod::RenderInfo * r_render_info) Line 405	C++
 	godot.windows.editor.dev.x86_64.exe!RendererViewport::_draw_viewport(RendererViewport::Viewport * p_viewport) Line 616	C++
 	godot.windows.editor.dev.x86_64.exe!RendererViewport::draw_viewports(bool p_swap_buffers) Line 808	C++
 	godot.windows.editor.dev.x86_64.exe!RenderingServerDefault::_draw(bool p_swap_buffers, double frame_step) Line 88	C++
 	godot.windows.editor.dev.x86_64.exe!RenderingServerDefault::draw(bool p_swap_buffers, double frame_step) Line 410	C++
 	godot.windows.editor.dev.x86_64.exe!Main::iteration() Line 4115	C++
 	godot.windows.editor.dev.x86_64.exe!OS_Windows::run() Line 1686	C++
 	godot.windows.editor.dev.x86_64.exe!widechar_main(int argc, wchar_t * * argv) Line 180	C++
 	godot.windows.editor.dev.x86_64.exe!_main() Line 206	C++
 	godot.windows.editor.dev.x86_64.exe!main(int argc, char * * argv) Line 220	C++
 	godot.windows.editor.dev.x86_64.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 234	C++
 	[Inline Frame] godot.windows.editor.dev.x86_64.exe!invoke_main() Line 102	C++
 	godot.windows.editor.dev.x86_64.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!00007ffc4af6257d()	Unknown
 	ntdll.dll!00007ffc4b7aaf28()	Unknown
```

**Comment by jsjtxietian** [comment]
For me sometimes I can get the above crash callback, sometimes it crashed when I closed the window:

```
_free_base(void * block) Line 105	C++
Memory::free_static(void * p_ptr=0x0000029053f59960, bool p_pad_align=false) Line 169	C++
memdelete<HashMapElement<StringName,Node::GroupData>>(HashMapElement<StringName,Node::GroupData> * p_class=0x0000029053f59960) Line 120	C++
DefaultTypedAllocator<HashMapElement<StringName,Node::GroupData>>::delete_allocation(HashMapElement<StringName,Node::GroupData> * p_allocation=0x0000029053f59960) Line 221	C++
HashMap<StringName,Node::GroupData,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Node::GroupData>>>::erase(const StringName & p_key={...}) Line 350	C++
HashMap<StringName,Node::GroupData,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Node::GroupData>>>::remove(const HashMap<StringName,Node::GroupData,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Node::GroupData>>>::Iterator & p_iter={...}) Line 512	C++
Node::remove_from_group(const StringName & p_identifier={...}) Line 2312	C++
Viewport::_notification(int p_what=11) Line 598	C++
Viewport::_notificationv(int p_notification=11, bool p_reversed=true) Line 95	C++
SubViewport::_notificationv(int p_notification=11, bool p_reversed=true) Line 793	C++
Object::notification(int p_notification=11, bool p_reversed=true) Line 918	C++
Node::_propagate_exit_tree() Line 376	C++
Node::_propagate_exit_tree() Line 367	C++
Node::_propagate_exit_tree() Line 367	C++
Node::_propagate_exit_tree() Line 367	C++
Node::_set_tree(SceneTree * p_tree=0x0000000000000000) Line 3158	C++
SceneTree::finalize() Line 643	C++

```

**Comment by qarmin** [comment]
```
=================================================================
==326286==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5040005cc340 at pc 0x62c31ea73038 bp 0x7fffcfc29ef0 sp 0x7fffcfc29ee0
WRITE of size 8 at 0x5040005cc340 thread T0
    #0 0x62c31ea73037 in RendererRD::MaterialStorage::MaterialData::update_textures(HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, HashMap<StringName, HashMap<int, RID, HashMapHasherDefault, HashMapComparatorDefault<int>, DefaultTypedAllocator<HashMapElement<int, RID> > >, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, HashMap<int, RID, HashMapHasherDefault, HashMapComparatorDefault<int>, DefaultTypedAllocator<HashMapElement<int, RID> > > > > > const&, Vector<ShaderCompiler::GeneratedCode::Texture> const&, RID*, bool, bool) servers/rendering/renderer_rd/storage_rd/material_storage.cpp:950
    #1 0x62c31ea7741c in RendererRD::MaterialStorage::MaterialData::update_parameters_uniform_set(HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, bool, bool, HashMap<StringName, ShaderLanguage::ShaderNode::Uniform, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ShaderLanguage::ShaderNode::Uniform> > > const&, unsigned int const*, Vector<ShaderCompiler::GeneratedCode::Texture> const&, HashMap<StringName, HashMap<int, RID, HashMapHasherDefault, HashMapComparatorDefault<int>, DefaultTypedAllocator<HashMapElement<int, RID> > >, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, HashMap<int, RID, HashMapHasherDefault, HashMapComparatorDefault<int>, DefaultTypedAllocator<HashMapElement<int, RID> > > > > > const&, unsigned int, RID&, RID, unsigned int, bool, bool) servers/rendering/renderer_rd/storage_rd/material_storage.cpp:1038
    #2 0x62c32006ccc7 in RendererCanvasRenderRD::CanvasMaterialData::update_parameters(HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, bool, bool) servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:2403
    #3 0x62c31ea98dec in RendererRD::MaterialStorage::_update_queued_materials() servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2042
    #4 0x62c31ed6916e in RendererRD::Utilities::update_dirty_resources() servers/rendering/renderer_rd/storage_rd/utilities.cpp:253
    #5 0x62c31fe70480 in RendererSceneCull::update_dirty_instances() servers/rendering/renderer_scene_cull.cpp:4128
    #6 0x62c31fe7128d in RendererSceneCull::update() servers/rendering/renderer_scene_cull.cpp:4143
    #7 0x62c31dcffe25 in RenderingServerDefault::_draw(bool, double) servers/rendering/rendering_server_default.cpp:79
    #8 0x62c31dd0d8be in RenderingServerDefault::draw(bool, double) servers/rendering/rendering_server_default.cpp:410
    #9 0x62c30389ead7 in Main::iteration() main/main.cpp:4114
    #10 0x62c30358d1f1 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:962
    #11 0x62c30356c03f in main platform/linuxbsd/godot_linuxbsd.cpp:85
    #12 0x7b8c65c2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #13 0x7b8c65c2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #14 0x62c30356bab4 in _start (/home/rafal/Downloads/godot.linuxbsd.editor.dev.x86_64.san+0x42a24ab4)

0x5040005cc340 is located 0 bytes to the right of 48-byte region [0x5040005cc310,0x5040005cc340)
allocated by thread T0 here:
    #0 0x7b8c668b3ec7 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x62c320feb3c1 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:75
    #2 0x62c30928ca75 in Error CowData<RID>::resize<false>(long) core/templates/cowdata.h:340
    #3 0x62c30927daaa in Vector<RID>::resize(long) core/templates/vector.h:95
    #4 0x62c31ea76b19 in RendererRD::MaterialStorage::MaterialData::update_parameters_uniform_set(HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, bool, bool, HashMap<StringName, ShaderLanguage::ShaderNode::Uniform, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, ShaderLanguage::ShaderNode::Uniform> > > const&, unsigned int const*, Vector<ShaderCompiler::GeneratedCode::Texture> const&, HashMap<StringName, HashMap<int, RID, HashMapHasherDefault, HashMapComparatorDefault<int>, DefaultTypedAllocator<HashMapElement<int, RID> > >, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, HashMap<int, RID, HashMapHasherDefault, HashMapComparatorDefault<int>, DefaultTypedAllocator<HashMapElement<int, RID> > > > > > const&, unsigned int, RID&, RID, unsigned int, bool, bool) servers/rendering/renderer_rd/storage_rd/material_storage.cpp:1025
    #5 0x62c32006ccc7 in RendererCanvasRenderRD::CanvasMaterialData::update_parameters(HashMap<StringName, Variant, HashMapHasherDefault, HashMapComparatorDefault<StringName>, DefaultTypedAllocator<HashMapElement<StringName, Variant> > > const&, bool, bool) servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:2403
    #6 0x62c31ea98dec in RendererRD::MaterialStorage::_update_queued_materials() servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2042
    #7 0x62c31ed6916e in RendererRD::Utilities::update_dirty_resources() servers/rendering/renderer_rd/storage_rd/utilities.cpp:253
    #8 0x62c31fe70480 in RendererSceneCull::update_dirty_instances() servers/rendering/renderer_scene_cull.cpp:4128
    #9 0x62c31fe7128d in RendererSceneCull::update() servers/rendering/renderer_scene_cull.cpp:4143
    #10 0x62c31dcffe25 in RenderingServerDefault::_draw(bool, double) servers/rendering/rendering_server_default.cpp:79
    #11 0x62c31dd0d8be in RenderingServerDefault::draw(bool, double) servers/rendering/rendering_server_default.cpp:410
    #12 0x62c30389ead7 in Main::iteration() main/main.cpp:4114
    #13 0x62c30358d1f1 in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:962
    #14 0x62c30356c03f in main platform/linuxbsd/godot_linuxbsd.cpp:85
    #15 0x7b8c65c2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #16 0x7b8c65c2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #17 0x62c30356bab4 in _start (/home/rafal/Downloads/godot.linuxbsd.editor.dev.x86_64.san+0x42a24ab4)

```
