### ISSUE TITLE
Build error in VS 2022

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#93447]
### Tested versions

#93428 (master)

### System information

Windows 10.0.19045 - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

Editor build fails on VS 2022 (There were no problems with 4.3 dev 6):

```
1>scons: done reading SConscript files.
1>scons: Building targets ...
1>Linking Program bin\godot.windows.editor.x86_64.exe ...
1>Building compilation database compile_commands.json
1>progress_finish(["progress_finish"], [])
1>scons: *** [bin\godot.windows.editor.x86_64.exe] UnicodeEncodeError : 'charmap' codec can't encode character '\u2568' in position 3: character maps to <undefined>
1>scons: building terminated because of errors.
1>Traceback (most recent call last):
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Taskmaster\__init__.py", line 246, in execute
1>    self.targets[0].build()
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Node\__init__.py", line 755, in build
1>    self.get_executor()(self, **kw)
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Executor.py", line 384, in __call__
1>    return _do_execute_map[self._do_execute](self, target, kw)
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Executor.py", line 117, in execute_action_list
1>    status = act(*args, **kw)
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Action.py", line 1221, in __call__
1>    return c.__call__(self, target, source, env, *args, **kw)
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Action.py", line 1152, in __call__
1>    return act(
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Action.py", line 1392, in __call__
1>    stat = act(target, source, env, exitstatfunc, presub,
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Action.py", line 705, in __call__
1>    stat = self.execute(target, source, env, executor=executor)
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Action.py", line 969, in execute
1>    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
1>  File "D:\Godot 4\4.3\godot-master\4.3 beta2\godot-master\godot-master\./platform/windows\detect.py", line 440, in spawn_capture
1>    log.write(line + "\n")
1>  File "C:\Users\FireRun\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
1>    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
1>UnicodeEncodeError: 'charmap' codec can't encode character '\u2568' in position 3: character maps to <undefined>
1>[Time elapsed: 00:00:53.62]
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(45,5): error MSB3073: leaving the team "echo Starting SCons && cmd /V /C set "plat=x64" ^& (if "x64"=="x64" (set "plat=x86_amd64")) ^& call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" !plat! ^& scons --directory="D:\Godot 4\4.3\godot-master\4.3 beta2\godot-master\godot-master" progress=no platform=windows target=editor arch=x86_64" with code 2.
1>Building project "godot.vcxproj" completed with an error.`
```

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/93305.
