### ISSUE TITLE
Unable to initialize engine render view

### ISSUE THREAD

**Issue by iimadouu** [godotengine/godot#95595]
### Tested versions

using godot : 4.2.2-stable

### System information

widnows 10 godot 4.2.2-stable (mobile)

### Issue description

 im trying to export to android (empty scene with a gsbox in the center) just trying the exporting before starting to build the actuall game, i followed godot android export docs step by step but alas the app keeps crashing after starting it either on an android emulator or exporting it to a physical phone.

godot console does not show any error:
```
Signing binary using:
C:\Users\SMC\AppData\Local\Android\Sdk/build-tools/34.0.0/apksigner.bat sign --verbose --ks --ks-pass pass: --ks-key-alias C:/Users/SMC/AppData/Local/Godot/tmpexport.1723692742.apk
Signed

Installing to device (please wait…): Samsung SM-S908N
```

heres adb logcat *:E results:

```
--------- beginning of crash
08-15 04:17:57.744 4703 4703 E AndroidRuntime: FATAL EXCEPTION: main
08-15 04:17:57.744 4703 4703 E AndroidRuntime: Process: com.example.testgame, PID: 470
08-15 04:17:57.744 4703 4703 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testgame/com.godot.game.GodotApp}: java.lang.IllegalStateException: Unable to initialize engine render view
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2958)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6840)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Unable to initialize engine render view
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at org.godotengine.godot.GodotFragment.performEngineInitialization(GodotFragment.java:196)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at org.godotengine.godot.GodotFragment.onCreate(GodotFragment.java:182)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at org.godotengine.godot.GodotActivity.onCreate(GodotActivity.kt:79)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7148)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.Activity.performCreate(Activity.java:7139)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2938)
08-15 04:17:57.744 4703 4703 E AndroidRuntime: ... 11 more
08-15 04:17:57.827 1532 1620 E InputDispatcher: channel 'c5969cc com.example.testgame/com.godot.game.GodotApp (server)' ~ Channel is unrecoverably broken and will be disposed!
08-15 04:17:57.946 2173 2348 E EGL_adreno: tid 2348: eglSurfaceAttrib(1350): error 0x3009 (EGL_BAD_MATCH)
08-15 04:17:58.217 2173 2348 E EGL_adreno: tid 2348: eglSurfaceAttrib(1350): error 0x3009 (EGL_BAD_MATCH)
08-15 04:17:58.497 1687 1961 E EGL_adreno: tid 1961: eglSurfaceAttrib(1350): error 0x3009 (EGL_BAD_MATCH)
08-15 04:18:09.591 3322 4739 E memtrack: Couldn't load memtrack module
08-15 04:18:15.539 1532 1545 E memtrack: Couldn't load memtrack module
08-15 04:18:30.017 1448 1495 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
```

here is some informations about the emulator:

LDPlayer version: 9.0.74.1(64)
Model: Manufacture(samsung) Model(SM-S908N)
Android 9
GPU renderer : Adreno 640

### Steps to reproduce

i really appreciate some help

### Minimal reproduction project (MRP)

i hope its the right place to submit this, i already submitted same issue in godot community but no answers for more that 12 hours since the post approval.

**Comment by Calinou** [comment]
Android emulators generally have limited to no Vulkan support, so projects won't work unless they use the Compatibility rendering method.

**Comment by iimadouu** [comment]
> What physical phone model did you test the project on?

i used lg v60
- android 12
- gpu renderer adreno 650 @441 MHz

> Also, try Godot 4.3 which was released today. It may have fixed that particular issue.

And yeah im currently downloading it, i will try it and let you know if it worked or not.

**Comment by Alex2782** [comment]
Can you find your devices on this homepage? Vulkan API version and more hardware information might help.
https://vulkan.gpuinfo.org/listdevices.php?platform=android

if not: https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer&hl=en_US

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
