### ISSUE TITLE
HTML5 exporter broken

### ISSUE THREAD

**Issue by trsh** [godotengine/godot#979]
To reproduce:

Try to export any godot scene to HTML5 (for ex. Bullet shower). Optionally name the export index.html.

Errors:

1) The included .js in HTML are wrong named and some missing?
2) If it try to set it up similar to my older working exports, I got:

 Uncaught Assertion failed: best_error <= 255, at: drivers/etc1/rg_etc1.cpp,1926,pack_etc1_block_init at Error
    at stackTrace (file:///home/janist/Software/godot/exports/shower/index.js:1049:15)
    at ___assert_fail (file:///home/janist/Software/godot/exports/shower/index.js:8184:210)
    at s3 (file:///home/janist/Software/godot/exports/shower/index.js:9497:561018)
    at f3 (file:///home/janist/Software/godot/exports/shower/index.js:9497:529873)
    at JC (file:///home/janist/Software/godot/exports/shower/index.js:9493:235678)
    at dj (file:///home/janist/Software/godot/exports/shower/index.js:9505:52054)
    at cj (file:///home/janist/Software/godot/exports/shower/index.js:9505:47185)
    at Object.Ri [as _main] (file:///home/janist/Software/godot/exports/shower/index.js:9505:12815)
    at Object.callMain (file:///home/janist/Software/godot/exports/shower/index.js:11296:30)
    at doRun (file:///home/janist/Software/godot/exports/shower/index.js:11353:25)

And so on...

**Comment by Evi1M4chine** [comment]
[Since the title of this bug fits, I’ll add this here too.]

I got a different error:

First I had to add the .mem file, which the exporter didn’t export, but I had to add manually.

Then these two errors appear when running it in the browser:

````
ERROR: get_executable_path: Warning, don't know how to obtain executable path on this OS! Please override this function properly.
   At: drivers/unix/os_unix.cpp:425.
````

and probably most importantly

````
missing function: _Z31register_iphone_global_defaultsv
````

, the latter of which being an error that is also shown during compilation of Godot for Javascript.

**Comment by vkbsb** [comment]
I've observed that the emscripten compiler would report multiple unresolved symbols .. which include all the modules as well. I found a link which suggested that the order of object files provided to create an static library is important when dealing with emcc. So i decided to do away with the .a and .o files in favor of .bc files by changing the config.py for javascript platform with the following. 

    env['CC'] = em_path+'/emcc'
    env['CXX'] = em_path+'/em++'
    #env['AR'] = em_path+"/emar"
    env['AR'] = em_path+"/emcc"
    env['ARFLAGS'] = "-o"

#    env['RANLIB'] = em_path+"/emranlib"
    env['RANLIB'] = em_path + "/emcc"
    env['OBJSUFFIX'] = '.bc'
    env['LIBSUFFIX'] = '.bc'
    env['CCCOM'] = "$CC -o $TARGET $CFLAGS $CCFLAGS $_CCCOMCOM $SOURCES"

im' now able to get the exporter to export the files and the symbols are all there.. but i get the following error in browser... 
Uncaught Assertion failed: best_error <= 255, at: drivers/etc1/rg_etc1.cpp,1926,pack_etc1_block_init at Error
    at jsStackTrace (http://localhost/~vkrishna/godot/MyTest/index.js:1:18330)
    at stackTrace (http://localhost/~vkrishna/godot/MyTest/index.js:1:18513)
    at ___assert_fail (http://localhost/~vkrishna/godot/MyTest/index.js:1:158022)
    at y4 (http://localhost/~vkrishna/godot/MyTest/index.js:27:530721)
    at o4 (http://localhost/~vkrishna/godot/MyTest/index.js:27:508544)
    at CG (http://localhost/~vkrishna/godot/MyTest/index.js:17:767309)
    at Si (http://localhost/~vkrishna/godot/MyTest/index.js:24:49862)
    at Ri (http://localhost/~vkrishna/godot/MyTest/index.js:24:45463)
    at Object.Fi [as _main] (http://localhost/~vkrishna/godot/MyTest/index.js:24:11858)
    at Object.callMain (http://localhost/~vkrishna/godot/MyTest/index.js:36:31267)

If anybody knows whats' going on please help.

**Comment by vkbsb** [comment]
https://github.com/okamstudio/godot/pull/1526

**Comment by eska014** [comment]
This issue is pretty old and there were some bigger changes to HTML5 export, so I assume this was fixed. If this issue still persists, please comment here or open a new issue.
