### ISSUE TITLE
[.Net] Duplicate Key Exceptions from `ScriptTypeBiMap.Add`

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot#98094]
Eventually Leads to #78513

### Tested versions

v4.4.dev3.mono [f4af8201b]

### System information

Godot v4.4.dev3.mono - Windows 10.0.17763 - Multi-window, 4 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6109) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Issue description

Under certain type-inheritance-structure, Godot Editor may encounter the following error:
```
/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:118 - System.ArgumentException: An item with the same key has already been added. Key: <SomeType>
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
     at Godot.Bridge.ScriptManagerBridge.ScriptTypeBiMap.Add(IntPtr scriptPtr, Type scriptType) in /godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.types.cs:line 27
     at Godot.Bridge.ScriptManagerBridge.TryReloadRegisteredScriptWithClass(IntPtr scriptPtr) in /godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 638
```
In this state, all exported variables of C# scripts will become null and cannot be changed anymore, and restarting the editor will not work either; the only fix is to close the Godot Editor, delete the `.godot` directory, reopen the Godot Editor, and build the C# project.
The same error will happen again for the second C# build attempt.

### Steps to reproduce

1. Download and extract the MRP.
2. Open the MRP with Godot 4.4.dev3.mono.
3. Open every scene in the PackedScenes directory.
4. Build the C# Project.
5. Rebuild the C# Project.

https://github.com/user-attachments/assets/edcec1a5-fe69-4180-b577-c6f30e9227bc

### Minimal reproduction project (MRP)

[MRP_Bi_Map_Duplicate_Key.zip](https://github.com/user-attachments/files/17344952/MRP_Bi_Map_Duplicate_Key.zip)

**Comment by Delsin-Yu** [comment]
Close as the `mono` module (aka `GodotSharp`) wasn't designed for handling external scripts, and this reminder doesn't enable that support either. Let's wait for the new binding implementation.
