### ISSUE TITLE
Overriding virtual properties in C# leads to errors in the generated code.

### ISSUE THREAD

**Issue by hdfyeg35** [godotengine/godot#99885]
### Tested versions

4.2 and 4.3

### System information

Godot v4.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.6603) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Overriding virtual properties in C# leads to errors in the generated code.

### Steps to reproduce

Uncomment override code in SimpleOverride.cs

### Minimal reproduction project (MRP)

[Scripts.zip](https://github.com/user-attachments/files/17966933/Scripts.zip)

Included just a simple scripts folder for a fresh Godot project.

**Comment by AdamLearns** [comment]
I just hit this issue myself with the same version of Godot. For reference, [here's a working C# playground](https://dotnetfiddle.net/yaJ7So) indicating that this should be fine in C# itself:

```cs
using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine("Hello World");
	}
}

public class BaseClass {
	public virtual long BuildCost {get; set;}
}

public class DerivedClass : BaseClass {
	public override long BuildCost { get => 500; }
}
```

**Comment by DarkStoorM** [comment]
I don't really know how this works under the hood, but if you just add an empty setter `set { }` to the overridden property, it builds properly, so in the OP's attached code, it should be this:

```cs
public override bool TestVar {
    get { return false; }
    set { } // extra empty setter
}
```

**Comment by Nallebeorn** [comment]
Confirmed on 4.4.1.stable.mono. These are the error messages when running `dotnet build` in a project with the scripts attache to the issue:

```
CSC : warning CS8785: Generator 'ScriptPropertiesGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Users\Benjamin\dev\godot-projects\overriding-virtual-properties\overriding-virtual-properties.csproj]

CSC : warning CS8785: Generator 'ScriptSerializationGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Users\Benjamin\dev\godot-projects\overriding-virtual-properties\overriding-virtual-properties.csproj]

C:\Users\Benjamin\dev\godot-projects\overriding-virtual-properties\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\PlayerCore_ScriptPropertyDefVal.generated.cs(16,33): error CS0117: 'Node.PropertyName' does not contain a definition for 'Primary' [C:\Users\Benjamin\dev\godot-projects\overriding-virtual-properties\overriding-virtual-properties.csproj]

C:\Users\Benjamin\dev\godot-projects\overriding-virtual-properties\.godot\mono\temp\obj\Debug\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\Player.APlayer_ScriptPropertyDefVal.generated.cs(18,33): error CS0117: 'CharacterBody3D.PropertyName' does not contain a definition for 'CameraA' [C:\Users\Benjamin\dev\godot-projects\overriding-virtual-properties\overriding-virtual-properties.csproj]

```

@AThousandShips

**Comment by fangchudark** [comment]
godot 4.6.1 still causes this issue

```csharp
public partial class Battler : CharacterBody2D
{
    public virtual string Id { get; protected set; } = string.Empty;
}
```

```csharp
public sealed partial class Player : Battler
{    
    // This will cause the source generator to throw an exception
    public override string Id => "koishi";
}
```

More information about the compilation is as follows:
```
Generator 'ScriptPropertiesGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.
System.NullReferenceException: Object reference not set to an instance of an object.
at Godot.SourceGenerators.ScriptPropertiesGenerator.c. b__2_6(GodotPropertyData pi)
at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
at Godot.SourceGenerators.ScriptPropertiesGenerator.VisitGodotScriptClass(GeneratorExecutionContext context, TypeCache typeCache, INamedTypeSymbol symbol)
at Godot.SourceGenerators.ScriptPropertiesGenerator.Execute(GeneratorExecutionContext context)
at Microsoft.CodeAnalysis.SourceGeneratorAdaptor. b__6_5(SourceProductionContext productionContext, GeneratorContextBuilder contextBuilder) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\GeneratorAdaptor.cs:line 68
at Microsoft.CodeAnalysis.UserFunctionExtensions.c__DisplayClass3_0`2. b__0(TInput1 input1, TInput2 input2, CancellationToken token) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\UserFunction.cs:line 103
```

```
Generator 'ScriptSerializationGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'.
System.NullReferenceException: Object reference not set to an instance of an object.
at Godot.SourceGenerators.ScriptSerializationGenerator.c. b__2_3(IPropertySymbol property)
at System.Linq.Utilities.c__DisplayClass1_0`1. b__0(TSource x)
at System.Linq.Enumerable.IEnumerableWhereIterator`1.MoveNext()
at Godot.SourceGenerators.ExtensionMethods.WhereIsGodotCompatibleType(IEnumerable`1 properties, TypeCache typeCache)+MoveNext()
at System.Linq.Enumerable. g__EnumerableToArray|314_0[TSource](IEnumerable`1 source)
at Godot.SourceGenerators.ScriptSerializationGenerator.VisitGodotScriptClass(GeneratorExecutionContext context, TypeCache typeCache, INamedTypeSymbol symbol)
at Godot.SourceGenerators.ScriptSerializationGenerator.Execute(GeneratorExecutionContext context)
at Microsoft.CodeAnalysis.SourceGeneratorAdaptor. b__6_5(SourceProductionContext productionContext, GeneratorContextBuilder contextBuilder) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\GeneratorAdaptor.cs:line 68
at Microsoft.CodeAnalysis.UserFunctionExtensions.c__DisplayClass3_0`2. b__0(TInput1 input1, TInput2 input2, CancellationToken token) in Z:\BuildAgent\work\3b7ce003563d6f8f\src\Compilers\Core\Portable\SourceGeneration\UserFunction.cs:line 103
```

**Comment by Temptica** [comment]
I can confirm, I have the exact same issue on 4.6.3.stable.mono.

> Parent class:
> public virtual ItemResource Resource { get; private set; }
> public virtual ItemResource NextResource { get; private set; }

> Childclass:
> public override ItemResource Resource => LeftVariant.Resource;
> 
>  public override ItemResource NextResource => LeftVariant.NextResource;

**Comment by raulsntos** [comment]
- Closing as duplicate of https://github.com/godotengine/godot/issues/71102
- This should be fixed by https://github.com/godotengine/godot/pull/98396 which will be merged for 4.8
